### ISSUE TITLE
ジャッカルショート説明文の脱字

### ISSUE THREAD

**Issue by Niccori250k** [yukieiji/ExtremeRoles#1]
https://github.com/yukieiji/ExtremeRoles/blob/master/ExtremeRoles/Resources/LangData/stringData.json#L1624
“サイドキックともに、皆殺しだ”となっていますが、“サイドキックとともに〜”ではないでしょうか。

**Comment by yukieiji** [comment]
v1.18.4.2で修正しました
https://github.com/yukieiji/ExtremeRoles/releases/tag/v1.18.4.2
