### ISSUE TITLE
呪術師：クルー役職

### ISSUE THREAD

**Issue by Inumiya** [yukieiji/ExtremeRoles#10]
### 役職名 / Role Name
呪術師

### 役職の色 / Role color
紫系統

### 役職の説明 / Role description
死体を消費して呪いをかけ、インポスターなどのキル役職を弱体化させる

### 役職の能力 / Role ability

呪術：
・ショートレンジ内の死体１体に対して使用
　・使用可能回数はオプションで変更できる
・死体を削除する代わりに以下の能力を両方発動
　1. その死体をキルした人物のキルクールタイムを増加させる
　　・クールタイムの増加は永続
　　・クールタイムの増加量はオプションで変更できる
　　・死体を消すのにかかる時間はオプションで変更できる
　2. その死体をキルした人物のキルボタンをクールダウン状態にする
　　・既にクールダウン中の場合は、カウントが最大値に戻る

・メリット：インポスターのキル速度を落とせる
・デメリット：死体を通報せずに消す。そもそも死体を発見しないと発動できない

怨念感知：
・１ゲーム中に１度だけ自動的に発動
・死後長時間経過している死体１つの位置が矢印で表示される
　・長時間＝1分以上のイメージ
　・時間はオプションで変更できる

・メリット：死体を発見しないと何も出来ないデメリットの軽減
・デメリット：デメリット軽減用の能力なので特になし

### 他陣営への影響 / Effect on other teams
・クルーへのメリット
　・インポスターからキルされにくくなる
・クルーへのデメリット
　・死体を消される
　・エボルバーと呪術師の区別が必要になる

・インポスターへのメリット
　・死体を消してもらえる
・インポスターへのデメリット
　・キルしにくくなる

### 陣営 / Team
- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
役職の能力はきちんとメリットデメリットがしっかりしてますし、問題なさそうです。v1.19.0.0のマイルストーンにセットします
エボルバーの隠れ蓑としても使えて語れるって部分でもバランス的に問題はなさそうかなと思われます

> 使用可能回数はオプションで変更できる

デフォルトは一回って感じでしょうか

> 死後長時間経過している死体１つの位置が矢印で表示される
　・長時間＝1分以上のイメージ
　・時間はオプションで変更できる

オプションの幅的に45～90秒って感じで、デフォルトは75秒か60秒ってところでしょうか

**Comment by Inumiya** [comment]
> デフォルトは一回って感じでしょうか
オプションの幅的に45～90秒って感じで、デフォルトは75秒か60秒ってところでしょうか

この値で良いと思います
よろしくお願いします

**Comment by yukieiji** [comment]
色はこんな感じでどうでしょうか
https://www.color-sample.com/colors/196/

**Comment by Inumiya** [comment]
イメージ通りです！

**Comment by yukieiji** [comment]
呪術師という英語でしっくり来たものがなかったので「ソーサリー(Sorcery)」という名前で実装していますが大丈夫でしょうか

**Comment by Inumiya** [comment]
問題ありません！

**Comment by Inumiya** [comment]
死体を扱うのでネクロマンサーもいいかなと思いました
すみません開発進んでいるのに今更

**Comment by yukieiji** [comment]
> 細かくてすみませんが、人物を指す場合はソーサラーだと思います

英語力がなくて申し訳ない、ソーサラー(Sorcerer)に治します

> 死体を扱うのでネクロマンサーもいいかなと思いました
すみません開発進んでいるのに今更

ネクロマンサーはぐぐったら死者との降霊とあったのでちょっとずれてるかな？って感じです

**Comment by Inumiya** [comment]
カーサー（Curser）って単語もあるみたいですね
呪い（curse）+　人（er）なのでこれが一番直訳感ありますが、カタカナにするとちょっとダサい
これ最終決定はいつまでとかありますか？

**Comment by Inumiya** [comment]
カースメーカーでお願いします
他のゲームだと呪術師はこう訳されているようです
ソーサラーは他のもっと魔術師らしい職のためにとっておいたほうが良いかなと

**Comment by yukieiji** [comment]
> カースメーカーでお願いします
他のゲームだと呪術師はこう訳されているようです
ソーサラーは他のもっと魔術師らしい職のためにとっておいたほうが良いかなと

了解です。カースメーカー(CurseMaker)で実装します

**Comment by yukieiji** [comment]
新しいオプションも含め、開発版コミットf08e9529e62fa65d23f2eede8a4e13efd25d5826で実装できたためクローズします
