### ISSUE TITLE
ボディーガードのシールドで、シューターのシュートを身代わりできる機能を追加する案

### ISSUE THREAD

**Issue by appleaoi** [yukieiji/ExtremeRoles#102]
### 追加する機能の詳細 / Feature details
#78 シューターのIssuesにて
#### 質問（少し余分な文を省いてます）
>ボディガードでシュートを防ぎたい
>クルー側にも防衛手段があれば面白いかなと思い提案しました
>それとも、キルボタンのキルでないから不可でしょうか？
#### 解答
>タスクフェーズ中に守った人を守るくらいなら出来るとは思います(シールド引き継ぎみたいな形で)

と技術的にはできそうとの回答を頂けたので、実装できないか提案させてもらいました

### 機能を追加するメリット / Benefits of adding features
1. 現状、シュートからクルーを守る手段はないので、身代わりという形ですが、強い役職のクルーを守ることができる
2. クルー目線、ボディーガード役職者が有力情報を持っていてシュートされたのか、かばってシュートされたのかわからないため、シューターの大幅な弱体化にはならないと思われる
3. シールドを張ったのに会議中にキルされた場合、ミッショナリーだと特定できる（ボディーガード目線）
4. 絵が映えそう（勝手なイメージです。動画化や支援絵などにつながりそう）

### 課題
ボディーガードのシールドは、wikiより
#### 「キルボタン」でのキルのみ防ぐことが可能、それ以外は「シールド」を貫通する
とのことなので、例外としての採用はありなのか？
そして、シュートを身代わりできることで、バランスが崩れないか？

**Comment by yukieiji** [comment]
個人的にはまだ実装されて1日しかたってなくて、使われている回数も少ないのにボディーガードを入れてバランス調整を行う必要があるのかと言うのが疑問に思えます

**Comment by appleaoi** [comment]
お疲れ様です。返答ありがとうございます。

>個人的にはまだ実装されて1日しかたってなくて、使われている回数も少ないのにボディーガードを入れてバランス調整を行う必要があるのかと言うのが疑問に思えます

一応、当時、
>シューターの実装が確実化しましたら、提案させてもらうかもしれません

と書いたので、今回提案させてもらいました。
（今、提案しとかないと忘れそうなので、このタイミングでの提案になりました）
 正直、メリット1，2，3は後付けで、4が主な理由だったので、バランス調整で提案したわけではなかったです。紛らわしいタイミングでの提案及び書き方になってしまい、申し訳ありません。

今後、プレイヤーからのシューターのバランス調整の要望や面白くなる提案などがありましたら、その時に採用するアイデアの一つとして考えてもらえればで構いません。（ですので、優先度最低でOKです）


ここからはおまけなので読まなくても構いません
シューターのIssuesで、序盤に意見した者として感想を書かせてもらいます
6/11に、某配信でシューターが動いているところを見させてもらいました
文章で最初に見たときは、バランス調整が難しそうだし、クルーが一方的にキルされるだけなのではと思いましたが、実際見てみると、後で撃とうとして抱え落ちする人がいたり、赤同士の連携がうまくいかず勝確盤面を逃したりと、程よく赤が強くなっている感じで非常に楽しむことができました。
（プレイヤーさんたちも好感触で、いいスタートを切れているようでよかったです）
現状、バランスも良さそう（まだ一回しか見れてないのにバランスもないですが）なので、バランス関連の文章は書かなくてもよかったなと少し後悔してました（この提案をしたのは見る前でした）

以上です。よろしくお願いします。

**Comment by yukieiji** [comment]
> 今後、プレイヤーからのシューターのバランス調整の要望や面白くなる提案などがありましたら、その時に採用するアイデアの一つとして考えてもらえればで構いません。（ですので、優先度最低でOKです）

まだ日も浅いとのことなので優先度を最低に設定かつ提案のまま置かせていただきます(実装するかどうかもわからないチケット)

**Comment by appleaoi** [comment]
>まだ日も浅いとのことなので優先度を最低に設定かつ提案のまま置かせていただきます(実装するかどうかもわからないチケット)

了解しました
対応ありがとうございました

**Comment by appleaoi** [comment]
お疲れ様です。
#141 を読ませてもらいました。
個人的にボディーガードは現状だとあまりパッとしないなと思っていたため、強化をすることで少しでも活躍する機会が増えそうでありがたいです。

現在、modマップが利用できるようになったことにより、そちらに配信者さんたちの興味がいってしまい、シューターの検証頻度が減って、この機能がメリットになるのか（ゲームとして面白くなるのかも含め）が、あまりはっきりしていない事が気がかりですが（自分が見れてないだけかもしれませんが）、対応よろしくお願いします。

**Comment by yukieiji** [comment]
とりあえずの実装が完了したのでクローズ残りのバグ等は #141 で対応
