### ISSUE TITLE
[ニュートラル幽霊] : 神隠し/ spirit away (姿を透明にする)

### ISSUE THREAD

**Issue by UzomuZo** [yukieiji/ExtremeRoles#103]
### 幽霊役職名 / Role Name
神隠し

### 幽霊役職の色 / Role color
薄い紫色

### 幽霊役職の説明 / Role description
能力を使用すると相手の姿を一時的に透明にする。
22/8/27時点でトトカルチョ、サーヴァント、サイドキックのみこの幽霊役職になる。

### 幽霊役職の能力 / Role ability

生存しているプレイヤーに能力を使用すると一時的に姿を透明にするが、透明になっているかは本人にわからない。
キルや能力の対象にはなる。

### 死亡前の役職 / Role befor Dead
特になし

### 他陣営への影響 / Effect on other teams
クルー、ニュートラル陣営に使えば生き残りやすくなる。
インポスター陣営に使えば現行犯になりにくくなる。
別の人とすれ違う寸前で使うと視認がなくなるので怪しくできる。

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
役職のコンセプトとしてこの役職がほぼ負けが決まっている死亡したニュートラルにアサインされた場合に能力を使うのかと言うのが疑問に思えます

**Comment by UzomuZo** [comment]
> 役職のコンセプトとしてこの役職がほぼ負けが決まっている死亡したニュートラルにアサインされた場合に能力を使うのかと言うのが疑問に思えます

ジャッカルの場合はサイドキックに使う場面はあると思いますが、他の役職の場合は能動的に使う必要性？はないですね。
キルされてやることが無くなったニュートラルがクルー、インポスターどちらでも干渉できるように、という事で考えました。

例えば同じ対象に使うたびに効果時間が長くなって、3～4回目に使うと対象を霊界に引き込んで自分が成り代わり勝利できる、みたいなこともできるんですかね？（効果時間と回数は調整必要かもしれません）
単独勝利の場合は生存側は使われている対象を落とす必要が出てくるし、死んでても能力を使う価値が出てくると思います。

**Comment by yukieiji** [comment]
> ジャッカルの場合はサイドキックに使う場面はあると思います

ジャッカルとサイドキック専用にするというのは一つの手段だとは思えますが、それは強すぎな気がします

> 例えば同じ対象に使うたびに効果時間が長くなって、3～4回目に使うと対象を霊界に引き込んで自分が成り代わり勝利できる、みたいなこともできるんですかね？（効果時間と回数は調整必要かもしれません）

「自分が成り代わる」ってのはどういうことでしょうか

**Comment by UzomuZo** [comment]
> 「自分が成り代わる」ってのはどういうことでしょうか
申し訳ありません、ふわっとしたイメージで書きました。
対象が死亡して自分が勝利になるということです。（あるいは自分が勝利で、TORの弁護士のように対象が勝利しても敗北扱いになるのでもよい）

**Comment by yukieiji** [comment]
> 対象が死亡して自分が勝利になるということです。（あるいは自分が勝利で、TORの弁護士のように対象が勝利しても敗北扱いになるのでもよい）

クルー目線3～4回それも同じ対象に選択されているかどうかを推理出来ない気がします

**Comment by UzomuZo** [comment]
使用した時の会議開始時のメッセージと効果時間が延びるのでわかるかな、と思いましたがちょっと甘かったですかね。
というわけで変更案です。

1. 対象にされた人に会議中にマークを付ける
→ マークが増えなければ同じ対象に使用

2. 会議開始時のメッセージに〇回目と表示する
→ 回数が増えたら視認がない人を探す

3. 使用したタイミングでSEあるいは一瞬光るなどの画面効果を付ける
→ 誰かに会えたら切れるタイミングがわかる？

4. 一定範囲内に複数人いないと使用できない（使用する毎に範囲を狭めても良い　例：8→5→3→2）
→ 消えた対象が判明しやすくなる

**Comment by yukieiji** [comment]
> 対象にされた人に会議中にマークを付ける

誰が対象になったのかを覚え続けるのは難しい気がします

> 会議開始時のメッセージに〇回目と表示する

あの表示はほぼ一瞬なんでクルー的にその表示はきつい気がします(あとあそこに流れるメッセージは固定を想定して作ってました)

> 使用したタイミングでSEあるいは一瞬光るなどの画面効果を付ける

SEなら実装は出来ますけど対象は全員？

> 一定範囲内に複数人いないと使用できない（使用する毎に範囲を狭めても良い　例：8→5→3→2）

固まってたら誰に使ったのかが判明できないような

**Comment by UzomuZo** [comment]
> > 対象にされた人に会議中にマークを付ける
> 
> 誰が対象になったのかを覚え続けるのは難しい気がします
> 

対象にされた人のマークは消えないようにはできないんですか？

> > 会議開始時のメッセージに〇回目と表示する
> 
> あの表示はほぼ一瞬なんでクルー的にその表示はきつい気がします(あとあそこに流れるメッセージは固定を想定して作ってました)
> 

そうだろうとは思っていました。
あとはチャット欄に表示とかですかね？

> > 使用したタイミングでSEあるいは一瞬光るなどの画面効果を付ける
> 
> SEなら実装は出来ますけど対象は全員？
>

対象は全員になりますね
 
> > 一定範囲内に複数人いないと使用できない（使用する毎に範囲を狭めても良い　例：8→5→3→2）
> 
> 固まってたら誰に使ったのかが判明できないような

これはほかの案と合わせてですね。（案1.マーク or 2.メッセージと）

**Comment by yukieiji** [comment]
能力的な問題点としこれをクルーが推理したとしても、それを止めるすべがないってのが一番な気がします(吊らないといけない)

> 対象にされた人のマークは消えないようにはできないんですか？

出来ますけど、何回目かクルー側から判定するのが難しい気がします(マークを変えればってありますけど会議の情報が増え過ぎると他の部分の推理が全く出来ない気がします)

> あとはチャット欄に表示とかですかね？

チャット表示を毎回見ているのかという問題もあります

**Comment by UzomuZo** [comment]
> 能力的な問題点としこれをクルーが推理したとしても、それを止めるすべがないってのが一番な気がします(吊らないといけない)

前に出した案4とは逆に誰かが近くにいると能力が使えなくして二人行動すれば防げるようにするとか？（使えない範囲が前と逆で広くなっていく）
クルー側としては二人行動してて死んでたら一緒に行動してた人が怪しくなるし、第三者からキルはしにくくなる。
あとは前に案をだしておいてあれですが、人が少なくなったら複数人集まるのも難しいので勝てなくなってしまうというのもあります。

> 出来ますけど、何回目かクルー側から判定するのが難しい気がします(マークを変えればってありますけど会議の情報が増え過ぎると他の部分の推理が全く出来ない気がします)
> チャット表示を毎回見ているのかという問題もあります

今回使用された対象者にマーク表示で、出来ればマークも①、②、③…とかにすればわかりやすい、かも？

**Comment by yukieiji** [comment]
> 前に出した案4とは逆に誰かが近くにいると能力が使えなくして二人行動すれば防げるようにするとか？（使えない範囲が前と逆で広くなっていく）
クルー側としては二人行動してて死んでたら一緒に行動してた人が怪しくなるし、第三者からキルはしにくくなる。
あとは前に案をだしておいてあれですが、人が少なくなったら複数人集まるのも難しいので勝てなくなってしまうというのもあります。

ペア行動が前提になってきてしまうとインポスター側がとてもきつくなる気がします

> 今回使用された対象者にマーク表示で、出来ればマークも①、②、③…とかにすればわかりやすい、かも？

マークを変えればわかりやすいってのはあるとは思いますが、情報が増えて生存者側での推理が全然できない気がします(クルー的に言えば黒吊らないと行けないのにこの役職の処理もしないといけない(一番わかり易い例：魔女の第三陣営版が居たとしてそれとインポスターを処理するみたいな感じ))

**Comment by melonjagaimo** [comment]
TORのそれのインスパイアという点に気を取られて類似する役職との相違点・独自性を見出すことを忘れて考えてました。
この意見は忘れてください。

**Comment by UzomuZo** [comment]
> ペア行動が前提になってきてしまうとインポスター側がとてもきつくなる気がします

となると、案4.だけど条件となる人数は生存者全体の2～3割いないといけないとか？
（2割の場合、11人以上生存で3人、10人～6人なら2人、5人以下なら1人なので無条件）

あるいは会議で得票率が生存者全体の1～2割で解除というのはどうでしょうか？
議論がまとまらずにスキップのときに1票入れておいて解除とか、票を集めたところに黒が乗っかって吊られるとか。

あとは1回のタスクフェーズで1人1段階しか進まないオプションとかもあった方がいいのかな？
（2段階溜まってるところに2分以上経って2段階進んで勝利っていうのを防ぐ）

> マークを変えればわかりやすいってのはあるとは思いますが、情報が増えて生存者側での推理が全然できない気がします(クルー的に言えば黒吊らないと行けないのにこの役職の処理もしないといけない(一番わかり易い例：魔女の第三陣営版が居たとしてそれとインポスターを処理するみたいな感じ))

正直これは難しいですね。
いっそのこと単独勝利なしにして処理の優先度を下げるくらいしか思い浮かばないです。

**Comment by yukieiji** [comment]
大変、返信が遅れてしまって申し訳ないです
一つ思いついたのはトトカルチョ、サーヴァント、サイドキック専用の役職として生きている役職のサポートが出来る能力としてチューニングするってのはありかなって思いました

**Comment by UzomuZo** [comment]
>大変、返信が遅れてしまって申し訳ないです
一つ思いついたのはトトカルチョ、サーヴァント、サイドキック専用の役職として生きている役職のサポートが出来る能力としてチューニングするってのはありかなって思いました

普段はバグや他の方の役職案等の対応していただいてますし、私としては提案したコマンダーも実装していただいてますので大丈夫です。

いろいろと追加しなくていいのでわかりやすいですし、確かにそれも面白いかもしれません。
あと念のため確認ですがサイドキックから昇格したジャッカルは対象外ですよね？

**Comment by yukieiji** [comment]
> いろいろと追加しなくていいのでわかりやすいですし、確かにそれも面白いかもしれません。
あと念のため確認ですがサイドキックから昇格したジャッカルは対象外ですよね？

そうですね、ジャッカルとクイーンは対象外でいいと思います

**Comment by UzomuZo** [comment]
>そうですね、ジャッカルとクイーンは対象外でいいと思います

あとはヤンデレが死んだ後に想い人のサポートっていうのは、無くてもいいかな？
今後の新規役職追加時に対象増やすかどうかはお任せします。

**Comment by yukieiji** [comment]
> あとはヤンデレが死んだ後に想い人のサポートっていうのは、無くてもいいかな？
今後の新規役職追加時に対象増やすかどうかはお任せします。

想い人はどっちの味方もできるって部分があるのでなくてもいいかなって思ってます(取得も面倒くさいですし)

**Comment by UzomuZo** [comment]
>想い人はどっちの味方もできるって部分があるのでなくてもいいかなって思ってます(取得も面倒くさいですし)

分かりました、ではヤンデレは無しでお願いします。

**Comment by yukieiji** [comment]
> 分かりました、ではヤンデレは無しでお願いします。

あとは能力だけですね

**Comment by UzomuZo** [comment]
とりあえずデフォルトは、効果時間は3秒で、クールタイムは通常の幽霊と同じ60秒かな。
あとはサポート専用ならかけられた本人が透明になったのがわかった方がいいかも、オンオフ設定でもいいですが。

**Comment by yukieiji** [comment]
> とりあえずデフォルトは、効果時間は3秒で、クールタイムは通常の幽霊と同じ60秒かな。
あとはサポート専用ならかけられた本人が透明になったのがわかった方がいいかも、オンオフ設定でもいいですが。

個人的にはその透明にするってところも含めて考える必要があるかなってのは思いました

**Comment by UzomuZo** [comment]
> 個人的にはその透明にするってところも含めて考える必要があるかなってのは思いました

透明にする以外でサポートする能力を考えるってことですか？
トトカルチョがいるのでキル陣営以外も有効な能力となると、移動速度変更、扉の開閉、会議で1票入れる（1試合1回限定）、死体場所の通知とかですかね。（あとは守護天使のシールド）

**Comment by yukieiji** [comment]
> 透明にする以外でサポートする能力を考えるってことですか？
トトカルチョがいるのでキル陣営以外も有効な能力となると、移動速度変更、扉の開閉、会議で1票入れる（1試合1回限定）、死体場所の通知とかですかね。（あとは守護天使のシールド）

そうですね
透明だといつ透明にされたか分からないと解除されたのを目撃された時点で吊られるますし、いつか分かると理不尽な透明キルが通るので個人的にはダメな気がします

**Comment by UzomuZo** [comment]
提案された能力周りでジャッカルとクイーンの援護になるような能力といえば会議と扉の開閉ですが、前者は落としたのに票が入るので防ぐのが難しい、後者はインポスターのサボタージュを妨害できるのでインポスターが辛くなるのでキツイ気がします

会議で吊るのに使えないように投票先をスキップ固定にするならどうでしょうか？

他に考えたのは、情報集め系の
1.サポート対象に能力ボタン使った対象の場所を矢印表示（キル陣営や目撃者になりそうな人に）
2.サポート対象に能力ボタン使った対象の陣営をメッセージ送信

あとは、サポ対象がキル陣営かキル無し陣営で効果を変えるとかできるんでしょうか？
例えばキル陣営ならキルレンジ延長、キル無し陣営なら一時的な視界強化など。

**Comment by yukieiji** [comment]
> 会議で吊るのに使えないように投票先をスキップ固定にするならどうでしょうか？

それでも、3人盤面でもう防ぎようがないPPが出来てしまうのでどうなんでしょうか

> 1.サポート対象に能力ボタン使った対象の場所を矢印表示（キル陣営や目撃者になりそうな人に）

ありといえばありなのではないでしょうか

> 2.サポート対象に能力ボタン使った対象の陣営をメッセージ送信

せっかく陣営を見えなくしてるのにそれを表示するってのは違う気がします

> あとは、サポ対象がキル陣営かキル無し陣営で効果を変えるとかできるんでしょうか？

出来ます、ですが現状親陣営は全部キル陣営なので分ける必要があるのかってのはあります

**Comment by UzomuZo** [comment]
>それでも、3人盤面でもう防ぎようがないPPが出来てしまうのでどうなんでしょうか

トト以外は基本残り一人の陣営で残り3人になるまで残らないといけないし、しかも幽霊がスキップに入れてくれるのも読んで投票するとなると意外と難しいかな？と思ったので。
強いのはたしかなので投票はやめておきます。

>せっかく陣営を見えなくしてるのにそれを表示するってのは違う気がします

幽霊自身はキル現場等を目撃しないと誰がどの陣営かわからないし、しかも幽霊に知らされたことは基本会議では言えないので、適当な誰かに使って役職までわかると強すぎるかと思って陣営だけにしたんですがだめでしたか。
ダメならシェリフとボタンが生えるフェンサーも含まれる、キルボタンがあるかどうかだけ表示とかどうですかね？

>出来ます、ですが現状親陣営は全部キル陣営なので分ける必要があるのかってのはあります

一応トトがキル陣営以外に賭けることがあるので分ければ考えやすいかと思っただけです。

**Comment by yukieiji** [comment]
> 幽霊自身はキル現場等を目撃しないと誰がどの陣営かわからないし、しかも幽霊に知らされたことは基本会議では言えないので、適当な誰かに使って役職までわかると強すぎるかと思って陣営だけにしたんですがだめでしたか。
ダメならシェリフとボタンが生えるフェンサーも含まれる、キルボタンがあるかどうかだけ表示とかどうですかね？

幽霊目線ならある程度陣営を理解するってのは難しくはないと思います(幽霊会話での情報もありますし)、そういったのを現世の情報に持ち込むのはちょっとずるいかなって思った感じです
第三陣営も最初にすることはキルボタン持ちを把握することだと誰かが言ってましたし、そのような情報を霊界から持ち出すのは推理ゲームとは違うと思います

**Comment by UzomuZo** [comment]
>幽霊目線ならある程度陣営を理解するってのは難しくはないと思います(幽霊会話での情報もありますし)、そういったのを現世の情報に持ち込むのはちょっとずるいかなって思った感じです
第三陣営も最初にすることはキルボタン持ちを把握することだと誰かが言ってましたし、そのような情報を霊界から持ち出すのは推理ゲームとは違うと思います

そういうことであればやめておきましょう

正直もう能力が思いつかないのですが、
１．サポーターみたいにランダムでクルー陣営の一人の役職をチャットに書き込む（回数制限あり）
　　チャットに気づかずに流れたら意味が無くなる、ランダムなので死んでる人や判明してる人も含める

以前出した案
２．サポート対象に能力ボタン使った対象の場所を矢印表示（キル陣営や目撃者になりそうな人に）
３．キル陣営：効果中キルレンジ延長、キル以外：効果中視界延長
４．ニュートラル用守護天使

**Comment by yukieiji** [comment]
> 正直もう能力が思いつかないのですが、
１．サポーターみたいにランダムでクルー陣営の一人の役職をチャットに書き込む（回数制限あり）
　　チャットに気づかずに流れたら意味が無くなる、ランダムなので死んでる人や判明してる人も含める

クルーから見えたら意味が無いような気がしますけど、本人しか見えないって設定ですか？

> ２．サポート対象に能力ボタン使った対象の場所を矢印表示（キル陣営や目撃者になりそうな人に）

これは上にもある通りありに近いとは思ってます

**Comment by UzomuZo** [comment]
>クルーから見えたら意味が無いような気がしますけど、本人しか見えないって設定ですか？

見えるのは自分と親、つまりサポート対象のみです。
1回だけクルーの人がわかって、サポーター騙りするとか死んでる人なら役職乗っ取りできる、かもしれない。

>これは上にもある通りありに近いとは思ってます

まあ、これが今の最有力ですかね

**Comment by yukieiji** [comment]
> とりあえず候補はこの二つでしたが、もう他に良さそうな案が出ないので１の矢印表示にします。

これがありといえばありという表現をしているのは赤っぽい人をすれ違った時に能力を使い表示することで霊界の情報を擬似的に持ってこれてしまう事ができてしまうってのがあるからですね
なので、それをちょっと考えないといけないと思います

**Comment by UzomuZo** [comment]
この中からどれか複数でしょうか。

- １．発動にランダムでタイムラグ（1～10秒くらい？）をつける。
発動タイミングまでに別の人にすれ違うかも。
- ２．対象をランダム（1～3人）にする。
そもそも対象を選べない。
- ３．確率で別の人に矢印が表示される。
基本は合ってるけど違う可能性が出てくる。
- ４．同じ人には（連続）使用できない。
対象に選ぶのは1人1回、あるいは間に別の人を入れないと指定できない。

**Comment by yukieiji** [comment]
かなり返信が遅れてしまい申し訳ないです
こういうのは基本的に直感的ではないと使われない、その上でバランスを取る必要があると思っています
そう考えると1と3を合わせた上でデメリットを撤回できるようにするのが一番だと思われるのですがどうでしょうか、時間が空いたので新しい意見があればお願いします

**Comment by UzomuZo** [comment]
>かなり返信が遅れてしまい申し訳ないです
こういうのは基本的に直感的ではないと使われない、その上でバランスを取る必要があると思っています
そう考えると1と3を合わせた上でデメリットを撤回できるようにするのが一番だと思われるのですがどうでしょうか、時間が空いたので新しい意見があればお願いします

急ぐものでもないので問題ありません。
デメリットを撤回というと
１．は遅延発動した時間(の一部？)は次回クールタイムが短くなるとかでしょうか？
（例えば短縮率50％なら10秒遅延→5秒短縮で60秒が55秒に）
あるいは遅延が一定時間たまると次回短縮される（例　20秒以上溜まると10秒短縮）

３．でやるなら案は
(1)違う人の場合は成功率が上がって正しい場合は下がる（例　違う場合+20%、正しい-10%）
(2)違う人の場合のみ次回クールタイムをさらに2～5程度秒短縮
(3)一定回数違う人を示すと、生存者全員に矢印表示する能力を1回使える（例　3回外れで1回使用）

**Comment by yukieiji** [comment]
> 急ぐものでもないので問題ありません。
デメリットを撤回というと
１．は遅延発動した時間(の一部？)は次回クールタイムが短くなるとかでしょうか？
（例えば短縮率50％なら10秒遅延→5秒短縮で60秒が55秒に）
あるいは遅延が一定時間たまると次回短縮される（例　20秒以上溜まると10秒短縮）
３．でやるなら案は
(1)違う人の場合は成功率が上がって正しい場合は下がる（例　違う場合+20%、正しい-10%）
(2)違う人の場合のみ次回クールタイムをさらに2～5程度秒短縮
(3)一定回数違う人を示すと、生存者全員に矢印表示する能力を1回使える（例　3回外れで1回使用）

いやただ単に外れる確率を0％とかタイムラグを0秒にオプションで設定できるようにするという考えでした

**Comment by UzomuZo** [comment]
>いやただ単に外れる確率を0％とかタイムラグを0秒にオプションで設定できるようにするという考えでした

ああ、そういうことだったんですね。
バランス調整のためにもそれはできたほうがいいですね。

**Comment by yukieiji** [comment]
v7.1.0.0にて「フォラス」という名前で実装いたしました
