### ISSUE TITLE
提案: クルーの殺意(仲間割れ)オプション

### ISSUE THREAD

**Issue by wilfrem** [yukieiji/ExtremeRoles#11]
### 追加する機能の詳細 / Future details

* 追加対象となったプレイヤーAの勝利条件に「殺意: Xさんが死んでいること」を追加する
* この場合、Aさんは自陣営が勝利しても(例えばクルーでタスク勝利しても) 、Xさんが生きていれば敗北となる(Xさんが死んでいないと勝利できない)
* ただし、Aさん自身が死んでいる場合はXさんが生きていても敗北することは無い(幽霊のタスク拒否防止)
* Xさんは設定により一人～複数人設定できる。0人であればこのオプションが無いのと同じ。
* 勝利条件の追加対象となるAさんはクルー陣営の一部または全員。
* 殺意の対象となるXさんはクルー陣営または全陣営
* このオプションでキル能力が追加されたりはしない。あくまでも勝利条件の判定にのみ影響。そのため、AさんはXさんを吊るかインポスターに殺してもらう必要がある。

### 各陣営への影響 / Effect on each teams

以下の影響によりクルー不利、インポスター陣営/第三陣営が有利になる。
ハンデやバランス調整に使えるかも。

* クルー陣営の「真実に向かう意思」を弱めることができる。
* Xを殺したいクルー陣営Aが嘘をつく可能性が生まれる。
* 早期にインポスターが吊られた場合、残ったクルーにインポスターを生かす理由が生まれる。
* インポスターがクルーのフリをしやすくなる。

### 備考 / note

* ラバーズの相手が殺意の対象にならないようにはしないとダメそう

**Comment by yukieiji** [comment]
クルー全体のデバフにはなると思うのですが対象になったAさんがゲームとしてつまらなくなると思います。
またランダム対象になった人がインポスターだったらデバフにならない気がします

あとこの機能を追加するメリットがいまいち見えてこないです。メリットの説明文は消さないで下さい

**Comment by wilfrem** [comment]
>  またランダム対象になった人がインポスターだったらデバフにならない気がします
言われてみれば。
クルー限定だと、Aさんから見てXさんはクルーだと判明するのが微妙かなと思ったけど、後述の点も考えるとむしろそっちの方が良いですね。

> クルー全体のデバフにはなると思うのですが対象になったAさんがゲームとしてつまらなくなると思います。
あー、微妙か。
「クルーに嘘をつく必要のあるクルー」ができないかなと思って考えてはみたのですが。
強力なクルー役職だけどクルーのキルが必要、みたいな形に整理・再提案した方が良いかも？

> あとこの機能を追加するメリットがいまいち見えてこないです。メリットの説明文は消さないで下さい

* インポスター/第三陣営側が有利になる調整ができる
* クルー陣営が嘘をつく可能性と、それに伴う会議の複雑性向上

辺りをメリットとして狙っていました。



ところで、「メリットの説明文」ってどれのことですか？
issueの9や10を参考にissueを立てましたが、どれかは分からず。

**Comment by yukieiji** [comment]
> クルー限定だと、Aさんから見てXさんはクルーだと判明するのが微妙かなと思ったけど、後述の点も考えるとむしろそっちの方が良いですね。

クルー限定だとクルーで簡単にラインが繋げてるのでオプションとしての価値が下がってる気がします。初期COするだけで白確が2人作れるので

> あー、微妙か。
「クルーに嘘をつく必要のあるクルー」ができないかなと思って考えてはみたのですが。
強力なクルー役職だけどクルーのキルが必要、みたいな形に整理・再提案した方が良いかも？

役職として出す場合は別のissueを上げて下さい

> インポスター/第三陣営側が有利になる調整ができる
クルー陣営が嘘をつく可能性と、それに伴う会議の複雑性向上

それは「マーリンとアサシン」という役職がいるので

> ところで、「メリットの説明文」ってどれのことですか？
issueの9や10を参考にissueを立てましたが、どれかは分からず。

issueのところに機能拡張のテンプレートがあったとおもいます。それでissueを立ててほしかったです(役職の提案でもないので)
このissueはそのままにして下さい(増えすぎるとこっちも管理が大変なので)

**Comment by yukieiji** [comment]
4/24までに返信がない場合はクローズさせていただきます

**Comment by yukieiji** [comment]
返信や更新がないためクローズします
