### ISSUE TITLE
[インポスター/Imposter] : グラスパー/Grasper(仮) (条件付きで複数票投じられるインポスター)

### ISSUE THREAD

**Issue by subarun4** [yukieiji/ExtremeRoles#110]
### 役職名 / Role Name
- グラスパー/Grasper(仮)
### 役職の色 / Role color
- 未定
### 役職の説明 / Role description
- 会議がスキップされるたびに投票権を獲得し、投票権を使用して複数票投じられるインポスター陣営
### 役職の能力 / Role ability
- 会議がスキップされた(誰も吊られない)場合、特別な投票権を１つ獲得する
- 会議中、通常の投票の他に特別な投票権を１つ使用して追加で１票入れることができる
   - 特別な投票権がある限り１会議中何票でも入れることができる
   - 投票結果で特別な投票権を使用した票はすべての陣営から確認することができる
- 味方のインポスターが吊られると特別な投票権を１つ失う

### 他陣営への影響 / Effect on other teams
- クルー陣営
   - 会議で吊り意識が低かったり議論が長引くと投票権を重ねられてPPが起こりうる
      - 但し、議論を詰めるため１スキップ⇒ローラーで黒を１吊ることができれば投票権は±０となる
   - キルクール伸ばしの会議ボタンによるスキップ進行にもデメリットをもたらす
- インポスター陣営
   - **議論による戦略が生まれる**
      - 議論をかき乱してスキップ進行に持っていくだけでもメリットが生まれる
      - 会議が踊って投票がばらけそうなタイミングで白吊りを強行できる
      - うまくキルとスキップを重ねた褒美として黒２白３盤面や黒１白２盤面で勝ちを確定することができる

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 会議がスキップされた(誰も吊られない)場合、特別な投票権を１つ獲得する
会議中、通常の投票の他に特別な投票権を１つ使用して追加で１票入れることができる
特別な投票権がある限り１会議中何票でも入れることができる
投票結果で特別な投票権を使用した票はすべての陣営から確認することができる
味方のインポスターが吊られると特別な投票権を１つ失う

正直この能力だとインポスターを会議で吊り切ることが不可能な気がします
会議が3回スキップで3人キルでインポスター3人盤面だとスキップ投票数6、ジャッカルやSKが生き残ってたりしてスキップに入ったり投票が間に合わなかったりしたらスキップになりかねず、もうその時点でインポスターを止めることが出来ない気がします

**Comment by subarun4** [comment]
コメントありがとうございます。
上記の指摘ですが、確かにそのような状況が発生する場合はインポスターを止めることはできないため、特別な投票権を用いた投票ではスキップに票を入れることができない制約をつけることで序盤のＰＰを防ぐことができると思います。

**Comment by yukieiji** [comment]
> 会議以外では通常のインポスターと変わらないため推理要素を増やさない

逆にクルー的にこの役職を狙って止めることが出来ないのではないでしょうか？(シューターとかであれば設定によるとは思いますがデフォルト設定であれば序盤はキルをしないとシュートできないので怪しい動きで黒ポイントが加算されて吊られやすくはなるとは思いますけど)

> クルー目線でもスキップの回数と使われている投票権の数、おおよそ吊れたインポスターの数で残りの投票権の数を想定できる

それを実行するにはクルー的にこの役職が入ると毎回毎回票を洗う必要が出てくると思います。そう考えると推理に割かれる会議時間は基本的に短めだと思われます(その時点でも大分強いとは思いますけど)

> シューターやToRのゲッサーような理不尽なキルは発生しないためクルー側でストレスを感じないという点でシンプルなルールに相性が良いと思われます。

推理を伴わない理不尽な吊りやスキップがそれもインポスター主導で発生するので、それをストレスに感じる人は感じるのではないでしょうか？

> 複数票持つためインポスターを吊り切れず止めることができない点ですが、ここ１カ月のふにんがすのウォーミングアップルールを調査し(9試合分)、インポスターの一人の役職をグラスパーとして、かつ最後の一人のインポスターとした場合で検証を行いました。その結果、
PPができる盤面は９試合中２会議（クルーorジャッカル4人、インポスター1人、投票権4票：ジャッカル1人、インポスター1人、投票権2票）
インポスター吊りを回避できる盤面は9試合中2会議(クルーorジャッカル5人、インポスター2人、投票権3票：クルーorジャッカル4人、インポスター2人、投票権2票）
のみだったため、インポスターとして強すぎることはないと思います。

役職が入ると入らないとで人の動きや考え、推理傾向、心構えが変わるはずなので単純に今までの試合にいれた場合の想定して強くないって言うのは間違っている気がします
古いチケットにも書いてはいたのですが役職を想定する場合は最悪手と最高手を想定するべきだと思ってます

**Comment by subarun4** [comment]
> 逆にクルー的にこの役職を狙って止めることが出来ないのではないでしょうか？(シューターとかであれば設定によるとは思いますがデフォルト設定であれば序盤はキルをしないとシュートできないので怪しい動きで黒ポイントが加算されて吊られやすくはなるとは思いますけど)

確かにクルーは狙ってこの役職を止めることはできないですね・・・特に終盤はスキップ進行で簡単に票数がひっくりかえるので対策を入れないと一方的な試合になります。
> それを実行するにはクルー的にこの役職が入ると毎回毎回票を洗う必要が出てくると思います。そう考えると推理に割かれる会議時間は基本的に短めだと思われます(その時点でも大分強いとは思いますけど)

投票権の数の確認は、スキップされた会議の回数で投票権が増えるので毎回毎回票を洗う必要はありません。
インポスターが吊れた数は普段の試合でも推理しているので、スキップされた会議から推理しているインポスターの数を引くことで現在の投票権の数を求めるのでわりと簡単に共通認識として持つことができると思います。
> 推理を伴わない理不尽な吊りやスキップがそれもインポスター主導で発生するので、それをストレスに感じる人は感じるのではないでしょうか？

投票権の数を理解していれば、生き残りのインポスターと合わせて最大の黒票数がわかるのでクルー側はその時点でPP盤面の会議であることは理解できるので理不尽という点ではストレスはあまり感じないと思います。（強すぎるという点ではストレスを感じるかもしれませんが）
混乱に乗じた吊りについては、むしろグラスパー能力の投票権の票が全員から認識できるのでクルー視点怒りの矛先を謀略にはめたインポスターに向けることができ、勢いで吊られるよりはるかにストレスは感じないと思います。
> 役職が入ると入らないとで人の動きや考え、推理傾向、心構えが変わるはずなので単純に今までの試合にいれた場合の想定して強くないって言うのは間違っている気がします
> 古いチケットにも書いてはいたのですが役職を想定する場合は最悪手と最高手を想定するべきだと思ってます

最悪手と最高手を想定する場合（クルー目線）
- 最悪手は会議でインポスターを確実に吊れるタイミングでスキップorクルーを吊られてしまう点
- 最善手は会議でスキップが起きないorスキップの回数＝インポスターの吊り数によって投票権がないため通常のインポスターと変わらない

それぞれが起こりうる頻度として、最善手はグラスパーが生き残っている場合大抵会議のスキップ回数がインポスター吊りの回数より多いので０はほぼなく少なくとも１票か２票は持っている、最悪手は２票以上持っていて５人盤面なら無理にキルを通しても吊り逃れできるので割と起こりうる。

なので、この役職を実装する場合全員で投票権の数を認識しながら試合することになります。投票権の数自体は推理は簡単なので議論時間が持っていかれることはあまりないと思いますが、クルー・インポスター・第３陣営が投票権の数に応じた動きをしなければならないので、役職の特性としてはアサシンマーリンに近いのかなと思います。
当初考えていたウォーミングアップルールに組み込むシンプルな役職としては不向きな気がしてきましたので、優先度は高く無くていいと思います。

**Comment by subarun4** [comment]
役職の能力の説明の
> 投票結果で特別な投票権を使用した票はすべての陣営から確認することができる

という項目をについて、こちらの説明不足ですべての陣営から確認できるというのがこの票は投票結果画面で金色のチケットのようなアイコンで通常の票とは異なるというように見えるものという説明です。

**Comment by yukieiji** [comment]
> という項目をについて、こちらの説明不足ですべての陣営から確認できるというのがこの票は投票結果画面で金色のチケットのようなアイコンで通常の票とは異なるというように見えるものという説明です。

AmongUsの仕様的にそういう事はできない気がします

**Comment by subarun4** [comment]
> AmongUsの仕様的にそういう事はできない気がします

了解です。この部分が実装できないと役職のバランスがとれないのでこちらの提案はこれでクローズします。
