### ISSUE TITLE
[クルー/Crewmate] : アンダーカバー/Undercover (クルー陣営が不利になると覚醒するシェリフ亜種)

### ISSUE THREAD

**Issue by hijiki55** [yukieiji/ExtremeRoles#111]
### 役職名 / Role Name
アンダーカバー/Undercover
### 役職の色 / Role color
赤味がかった橙
### 役職の説明 / Role description
クルー陣営が不利になると覚醒するシェリフ亜種

### 役職の能力 / Role ability

 - 《アンダーカバー》はクルーからタスク覚醒する。
   - クルーの生存数と人外の生存数の差が設定数以下になったタイミングでフラグを立て、以降の必要タスク率を設定％軽減する。
 - 《アンダーカバー》は全プレイヤーを対象とした『キル』ボタンを持つ。回数制限、クールダウンがある。
   - クルー陣営を『キル』対象にした場合、そのプレイヤーは死亡しない。回数消費やクールダウンは発生する。
 - オプションにより、《アンダーカバー》はベントを使用できる。

### 他陣営への影響 / Effect on other teams
人外はクルーよりピンチ条件を把握しやすい。騙りや黒塗りに利用する。

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

ピンチになると覚醒する、あるいは覚醒でピンチが分かる。
シェリフと比べると白を撃っても自爆しない反面、他目線の確白も出ない。

**Comment by yukieiji** [comment]
役職を否定する形にはなってしまうのですがシェリフのタスク周りのオプションやヒーローとあまり差別化出来ていない気がします(何なら切って自爆しない点でもシェリフの上位職に近い形に見えてしまいます、タスク周りのオプションは今後も拡張する予定はあります)

> オプションにより、《アンダーカバー》はベントを使用できる。

エンジニアの能力の上位互換になってしまうので、基本的にコンビ役職ではない役職にベントは持たせたくはないですね
