### ISSUE TITLE
[クルー陣営] : エクスポーザー (何度か会議を生き残ると、役職を公開させる能力を覚醒させる)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#112]
### 役職名 / Role Name
エクスポーザー（公開する者）

### 役職の色 / Role color
薄紫

### 役職の説明 / Role description
指定された回数の会議を生き残ると強力な能力を覚醒させるクルー陣営
クルー陣営でCO抑止を実現できそう

### 役職の能力 / Role ability

ゲーム開始時からエクスポーザーとしてアサインされるが、初期状態では能力を持たない。
指定された回数の会議を生き残ると「公開」能力を覚醒させる。デフォルトでは5回を想定している。

公開能力は会議ごとに1度、プレイヤー1人を会議中に対象に指定して発動できる。そのプレイヤーの役職を生きている全プレイヤーに公開させる。死亡しているプレイヤーや、エクスポーザー自身も公開能力の対象にできる。

#### メリット
能力覚醒は基本的に中盤から終盤なので、確実な白塗り・黒塗りで一気にクルー陣営勝利を手繰り寄せられる

#### デメリット
覚醒前はただのクルーと同じ
覚醒するまでエクスポーザーだとバレてはいけないのでクルー陣営のCOが抑制される
ゲーム展開が早すぎると覚醒するころには手遅れ（あるいは逆にクルー陣営の勝ちがほぼ確定）な状態になって、能力が腐ることもある

#### 固有の設定項目
覚醒に必要な会議数：0～8回
0回は役職超強化ルール用。

### 他陣営への影響 / Effect on other teams
エクスポーザーの覚醒を防ぐため、インポスター陣営およびニュートラル陣営はキルに積極的になり、会議発動に対して消極的になる。つまりゲーム展開が早くなる。
さらにそれらの陣営が議論を引き延ばしてボタンを消費させる行為に対して、エクスポーザーの覚醒を早めるリスクを負わせられる。

またデメリットにもあるように、エクスポーザーは騙れない上に覚醒されると強力なので真っ先に狙われるため、エクスポーザーを守りたいクルー陣営のCOが抑制される。

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
覚醒した時点で黒がほぼ割れるようなもので、全体的に強化占い師なきがしてバランスが取れてない気がします

> ゲーム開始時からエクスポーザーとしてアサインされるが、初期状態では能力を持たない。
指定された回数の会議を生き残ると「公開」能力を覚醒させる。デフォルトでは5回を想定している。

たった5回の会議でこの能力に覚醒するのはダメだと思います

> 公開能力は会議ごとに1度、プレイヤー1人を会議中に対象に指定して発動できる。そのプレイヤーの役職を生きている全プレイヤーに公開させる。死亡しているプレイヤーや、エクスポーザー自身も公開能力の対象にできる。

毎会議誰かの役職を明かせる時点で強すぎる気がします

**Comment by melonjagaimo** [comment]
強すぎでしたか。
実は「指定の回数、会議を生き残ると強力な能力を得る」役職案は3つあり、その1つとしてこの役職を出しました。
残りの2つは
エクスキューショナー：指定回数会議を生き残るとシューターと同じ能力を得る

サロメ：指定回数会議を生き残るとクルーの敵を1人だけ死なせることができる
です。これらについてはどうでしょうか。

**Comment by yukieiji** [comment]
> 実は「指定の回数、会議を生き残ると強力な能力を得る」役職案は3つあり、その1つとしてこの役職を出しました。

会議自体クルーにデメリットが無いので起こせば起こす分だけ特になるので、その上で協力な能力を得るのは間違ってる気がします
インポスターが会議やキルで狭量な能力を得るのには吊られたり浮くデメリットがあるので問題はないと思いますが

**Comment by melonjagaimo** [comment]
そうでしたか。それではこちらはクローズします
