### ISSUE TITLE
[クルー陣営] : ナイトビジョン (タスクを一定量進めると視界拡大能力に覚醒)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#113]
### 役職名 / Role Name
ナイトビジョン

### 役職の色 / Role color
紺色

### 役職の説明 / Role description
カーペンターみたいにタスクを一定量こなすと通常クルーがナイトビジョンに覚醒
自分の視界を拡大し、自分への停電効果を無効にする

### 役職の能力 / Role ability

ゲーム開始時は通常のクルーとしてアサインされるが、タスクを一定量こなすとナイトビジョンに覚醒する。
必要な進捗はオプションで変更可能（デフォルトでは60％程度を想定）

能力を発動すると一定時間、自分の視界が拡大する。また、効果時間中は停電の効果を受けない。

#### 固有の設定項目
能力発動中の視界の広さ
能力の持続時間
能力のクールタイム
覚醒に必要なタスク進捗

#### メリット
遠くまで見通せる

#### デメリット
覚醒までに死亡すると乗っ取られる恐れがある

### 他陣営への影響 / Effect on other teams
インポスター・ニュートラルは、主にゲーム後半に視界が広いクルーがいることを考慮して動かねばならない。しかし、それらの陣営はナイトビジョンを騙ることも予想される。

必要な進捗が少ない設定だと早くから能力を使える代わりに、騙りが通りやすくなる。

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
基本的に覚醒役職は別視界設定を持つ場合、覚醒後にその視界が反映されるようになってます(v2.2.0.2は不具合でできてないんですが)、あとタスク覚醒役職にしては釣り餌が小さい気がします
そう考えるとこの役職を追加で入れる必要があるのかな、入れたとしても使ってくれるのかなって思います

**Comment by melonjagaimo** [comment]
以前何かの役職の議論中に「ライターの能力をそのままは強すぎる」という意見を聞きましたのでタスク覚醒役職にしたのですが、それでは弱すぎましたか。

それでは、最初からナイトビジョンとしてアサインされて「能力に回数制限があり、初期状態で使用回数所持している他、タスクをある程度こなす毎に補充される」のはどうでしょうか。
例:初期状態で1回、タスクを2つ完了させるごとに1回

**Comment by yukieiji** [comment]
> 以前何かの役職の議論中に「ライターの能力をそのままは強すぎる」という意見を聞きましたのでタスク覚醒役職にしたのですが、それでは弱すぎましたか。

ライターが強すぎるとは確か言っていないはずです、スペシャルクルーの能力設定と食い合ってしまうから実装していないとは言っていたはずですが

> それでは、最初からナイトビジョンとしてアサインされて「能力に回数制限があり、初期状態で使用回数所持している他、タスクをある程度こなす毎に補充される」のはどうでしょうか。
例:初期状態で1回、タスクを2つ完了させるごとに1回

上にも言ったのですがライターの能力はスペシャルクルーの能力を食い合ってしまってると思ってます

**Comment by melonjagaimo** [comment]
スペシャルクルーならオプション変更で視界を広くして停電無効化して、常時ライターなクルーが可能でしたね…。
クローズします
