### ISSUE TITLE
[ニュートラル] : 秘密の恋人(殺さないで！私達には子供がいるの！)

### ISSUE THREAD

**Issue by gang-lion8** [yukieiji/ExtremeRoles#118]
### 役職名 / Role Name
秘密の恋人/Secret Lovers
### 役職の色 / Role color
流し見程度では白との違いに気づかないかもしれないくらいの薄いピンク色
### 役職の説明 / Role description
恋人とTORのオポチュニストを合体してメリットとデメリットが増えた感じの二人一組第三陣営
### 役職の能力 / Role ability
二人一組の第三陣営だがゲーム終了条件的にはクルー判定。
最後に二人のうちどちらかでも生き残っていれば勝利陣営に相乗りできる。

開始時点では通常の恋人と同じく片方が死亡するともう片方が後追い自殺をしてしまう(この時点で敗北確定)。
二人が至近距離にいる時に互いが(もしくは片方が)「逢瀬」ボタンを押す事で「逢瀬」が出来る。決められた時間一緒にいれば「逢瀬」完了。その前に離れると失敗。
「逢瀬」中は名前の色が他の人に見えるので見つかると二人もろとも陣営がバレる(白に近い色なので流し見してるとバレないかもという感じにしたいです)。
「逢瀬」をすると一定確率で次の会議終了時に子供が出来る。「逢瀬」の回数が増えるほど子供が出来る確率も上がる。

子供が出来るとペアレンツに変化(逢瀬ボタン消失)。片方が死んでも後追い自殺をしなくなり親権を持つ方(ランダムに決定)の投票数が二つになる。親権を持っている方が死ぬともう片方に親権が移る。

死にやすい恋人なのに死んではいけないので共倒れしないよう子供を作りたいが子供を作るにはそれなりのリスクを伴う上に運要素もあるという中々に厳しい陣営。
ただし子供が出来れば強気に動けるボーナスタイムというイメージ。

### 他陣営への影響 / Effect on other teams
同時勝利できるどの陣営にとっても味方にも敵にもなりうる不安要素。
こいつらの気分次第で最大三票がどこにでも動く厄介な存在。
### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 子供が出来るとペアレンツに変化(逢瀬ボタン消失)。片方が死んでも後追い自殺をしなくなり親権を持つ方(ランダムに決定)の投票数が二つになる。親権を持っている方が死ぬともう片方に親権が移る。

「子供」ってのはどういうものなのでしょうか、内部的なカウントなのでしょうか？それとも誰がどこから見ても分かるなにかなのでしょうか

> 死にやすい恋人なのに死んではいけないので共倒れしないよう子供を作りたいが子供を作るにはそれなりのリスクを伴う上に運要素もあるという中々に厳しい陣営。
ただし子供が出来れば強気に動けるボーナスタイムというイメージ。

「秘密の恋人」は基本的に「逢瀬」をするために行動をするとは思いますが、それをクルーが発見した時にすぐ吊りましょうってなるのか疑問に思えました(人外にとっては吊りましょうってなるとは思いますが)。クルー的には味方しなかったら吊ります or シェリフキル or 今後実装するであろうナイスゲッサー的な何かで殺すっていう脅しでこの役職をクルー役職として使える気がします(追加で昇降機右に張り付いといてねで人外を完全完封できる気がします)


クルー的にこの役職を消すメリットがあるのか少し疑問に思えました

**Comment by gang-lion8** [comment]
> 「子供」ってのはどういうものなのでしょうか、内部的なカウントなのでしょうか？それとも誰がどこから見ても分かるなにかなのでしょうか

「そういう設定」というフレーバー的なイメージで、特に視覚的な何かはあまり想定していなかったです。
「恋人が死んでも生きる理由」が欲しかっただけなので票数が増えるとかも別に必要ではないかなと。
会議の後に「恋人たちの間に子供が生まれました」みたいなメッセージが出るとか、誰の子かはわからないけど招集ボタンの近くにぽつんと小さいクルーが立ってるとか出来たら視覚的にも楽しめるのかなとは。
そういうのがなくても票数が増えている事に気づければ子供が生まれてる事はわかりますが、エンタメ性を考えるとやはり視覚的な何かはあった方が良い気がしますね。

> クルー的には味方しなかったら吊ります or シェリフキル or 今後実装するであろうナイスゲッサー的な何かで殺すっていう脅しでこの役職をクルー役職として使える気がします(追加で昇降機右に張り付いといてねで人外を完全完封できる気がします)

現状だとクルーの味方をするのが安パイ過ぎてバランスが悪いという事ですよね？
・保安官に撃たれるような事はしてないのでシェリフからはクルー判定
・役職が父と母みたいな感じでそれぞれ違う役職になるのでゲッサーで落とすのは賭けになる
・サボタージュ対応ができない
という設定ならどうでしょうか。
現状のままでもクルー視点「状況が傾けば裏切る可能性がある不安要素」、人外視点「味方につけられればグッと楽になる存在」である事は確かだと思うので、クルー寄りになりやすい要素を削っていけばクルーとしても余裕があれば排除したい存在になるんじゃないかなと。
僕がこれを考える上で重視したのは『バレたらいけない秘密の恋人』という他とは一風違った緊張感なので、そこさえ維持できればバランスの為にどんな設定になっちゃっても良いかなと思っています(コンセプト的には自分達の票で結果が決まるという状況まで潜伏し続けるのがベターになるのが理想ではありますが)。
なので他にもこうしたらバランスが良くなるという考えがあったら教えていただきたいです。

最初は最後まで生き残ってれば他の勝利を乗っ取って単独勝利する第三陣営として考えていたけど、僕の設定厨的な部分が「逢瀬を重ねてたら単独勝利になる意味がわからない」と否定して、そこからオポチュニスト的要素や子供という要素を足していった、という流れなので、一周回ってこの能力で単独勝利でも良い気もします。

**Comment by yukieiji** [comment]
> 「そういう設定」というフレーバー的なイメージで、特に視覚的な何かはあまり想定していなかったです。
「恋人が死んでも生きる理由」が欲しかっただけなので票数が増えるとかも別に必要ではないかなと。
会議の後に「恋人たちの間に子供が生まれました」みたいなメッセージが出るとか、誰の子かはわからないけど招集ボタンの近くにぽつんと小さいクルーが立ってるとか出来たら視覚的にも楽しめるのかなとは。
そういうのがなくても票数が増えている事に気づければ子供が生まれてる事はわかりますが、エンタメ性を考えるとやはり視覚的な何かはあった方が良い気がしますね。

視覚的な何かを作ろうとすると色々と面倒なので、内部カウントで視覚的に無い方が実装的には楽です

> 現状だとクルーの味方をするのが安パイ過ぎてバランスが悪いという事ですよね？

安パイ過ぎてと言うか「逢瀬」をしてる部分を見られても特に困らないのではないかなって
クルーに見られたとしてもクルーに味方すればいい、基本的に二人行動してたら一部のインポスター役職以外対応することは不可能なのでクルー有利盤面になりやすい
人外に見られたとしても二人いるからキルできない、会議中に告発したとしてもじゃあクルーの味方ねってなりそうな気がします

> ・保安官に撃たれるような事はしてないのでシェリフからはクルー判定
・役職が父と母みたいな感じでそれぞれ違う役職になるのでゲッサーで落とすのは賭けになる
・サボタージュ対応ができない

ゲッサーみたいなものなのでゲッサー見たく役職を指定するかどうかはわからないです(シューター的なものだって考えていただくといいと思います。このゲッサーみたいな役職のバランスは置いといてください)
たとえサボが治せなくてもセキュ張り付きであったりアドミンに張り付けてればそれでクルーの味方できてしまう気がします

> 僕がこれを考える上で重視したのは『バレたらいけない秘密の恋人』という他とは一風違った緊張感なので、そこさえ維持できればバランスの為にどんな設定になっちゃっても良いかなと思っています(コンセプト的には自分達の票で結果が決まるという状況まで潜伏し続けるのがベターになるのが理想ではありますが)。

返信の上にもある通り今のままだとバレても問題ない感じはします(バレても排除しようって流れにはなりにくい気がします)

> 最初は最後まで生き残ってれば他の勝利を乗っ取って単独勝利する第三陣営として考えていたけど、僕の設定厨的な部分が「逢瀬を重ねてたら単独勝利になる意味がわからない」と否定して、そこからオポチュニスト的要素や子供という要素を足していった、という流れなので、一周回ってこの能力で単独勝利でも良い気もします。

単独勝利にするってのは一つの解決策だとは思います

**Comment by yukieiji** [comment]
> 正体が発覚するだけで死亡リスクが跳ね上がるので結構困ると私は思っています。

敵でもない第三陣営の役職が分かると死亡リスクは上がらないと思うのですがどうでしょうか
明らかに敵対行動を取るような陣営(分かりやすい部分で言えばシューターとかジェスター、ミッショナリーとか)であればキル陣営やクルー的に優先的に落としたくなるので死亡リスクは上がると思うんですが、クルーが「逢瀬」をしているのを発見したとした場合にこの役職を排除しましょう！！ってなるのかなってのが疑問な気がします(クルー的には人を減らしたくないので無害なこの役職を排除して生存者の人数を減らすのかなって部分ですね)
この役職的にも4人位がタスクやってて視認情報があるアーカイブのど真ん中で「逢瀬」をやったとしてもデメリットはない気がします

> 例えば残り12人インポスター3恋人バレでインポスターが絞りきれない盤面だったらクルー的には「この会議終わりに子供が出来たら次の会議でPP盤面だから今の内に恋人潰しとこう」ってなっちゃいませんか？(10人中3インポスターも中々厳しくはありますが)

この役職を落とすと2人落ちる可能性があるので12人盤面でこの役職を落とそうって考えにくいはずです(12人盤面でこの役職が落ちて2人落ちたとした場合、3キル+1キルでゲームセットなので)
PP盤面になったとしてもインポスターの勝利条件を満たす必要があるためクルーを5人落とす必要(この役職2人+クルー1人にしなければならない、その5人の中にインポスターを妨害できるような役職(カースメーカー、シェリフ、フェンサーなど)が居るかもしれない)があるのでどっちのほうがインポスター的に楽かと言われれば3キル+1キルの方が楽な気がします
この盤面だとシェリフとかが生き残ってれば銃口を突きつけてクルーの味方をしろさもなければ撃ち殺すっていう脅しが基本戦術になりそうな気がします(もしクルーが敗北しそうになった場合でもこの役職をキルして相乗り勝利を防げますし)
シェリフがその盤面居なかったらスキップでタスクで行きましょうな気がします(この役職を生かしておけば生存勝利の人数のかさ増しとして使えますし)

> それはそれとしてさらにクルーの味方をしづらくなる要素も考えてみましたが、「子供を作ることが勝利条件に含まれる」などはどうでしょうか
「逢瀬」に時間を割く為にクルーに協力してばかりも居られないですし、最後まで生き残っても子供がいなければ敗北なので状況次第で情報を隠す、人外に白だしする、スキップに入れて決着を遅延させるなどの妨害を行う必要が出てくる。これならクルーにとって信頼性に欠ける、余裕があるなら潰しておきたい存在になってきませんか？

どちらにせよ「逢瀬」をやるメリットはあるけど「隠れる」必要性が全くないってのが問題な気がします(上の例にもある通りアーカイブのど真ん中とか人が通りやすいところで「逢瀬」をやって「クルーさん私は味方をします！！！！」ってアピールできますし(人が多いところでやるとキル陣営的にキルはしにくいですしね))
無害なこの役職がバレて釣られるのかって言われると微妙な気がします
クルー目線的にその二人が確定でこの役職であるって分かる時点でアドバンテージは大きい(その二人以外に人外が居るってわかる)ですし、投票権があれば味方的にも強力、裏切ったら始末すればいい(わかりやすく言えば言えばいつでも自由に呼び出せて捨てれる) <=> この役職の目線的に勝ちやすい陣営に味方したい、クルー有利である人狼ゲームにおいてゲーム開始時から「逢瀬」をやって延命しつつ存在をクルーアピールして媚びを売ろう(わかりやすく言えばクルーっていう強者についていって味方すれば基本的に命は狙われにくい)。この2つの関係は結構WinWinな関係な気がします
キル陣営目線的に基本二人行動だから早めに排除したい、最終盤面までこの役職残れればPP出来る。だけど、この役職は人が多いところで「逢瀬」をやってクルーに媚びるし、時間が経てば二人行動を剥がすことができないから排除しにくい。(わかりやすくいうなら排除したいししたくもない)<=> この役職の目線的にキルされたくないからキルされやすい人目のつかない場所で「逢瀬」をやりたくない、人数不利なキル陣営に最初から付くメリットがない。(わかりやすく言うとわざわざ自分の命を奪うような人の味方をするのか)。この関係は明らかに敵対してますしキル陣営に付くメリットが少ない気がします

> 子供が居ない時は通常の恋人同様後追い自殺がある(子供の存在が恋人が死んでも生きる理由になるイメージ)ので普通にキルされてしまうと思います。寧ろ「逢瀬」をしているという事はまだ子供が居ない事が確定、しかも周りに人が居ない可能性が高いのでキルチャンスかと。

「逢瀬」が終わっていたらキル陣営側が排除することが難しいって事になりませんか

> この方向で行くのであれば、「子供は何人でも作れて(一度の会議で一人まで)、子供の人数が恋人陣営の人数として加算され、恋人陣営の人数がその他陣営の生き残りの数を越せば勝利」なども思いつきましたがなんか全別物になってる気がします。思いついたのでとりあえず書きましたが普通に今のままでいい気がします。

別物にはなってますけど、例えばそれが会議開始時に報告されるとかなら一つの推理要素にはなりますからそれはそれでありなのではっておもいました(「隠れる」っていう必要性も上がってますし)

**Comment by gang-lion8** [comment]
何とかクルーにとっても邪魔になりやすい存在にしたいのですがなかなか難しいですね…
一応いただいた意見をもとに思いついた要素は書いておきますが、この方向は諦めて単独勝利陣営として考えた方が良いかなという気持ちが強くなってきました。
・周りに人が居る状態では「逢瀬」が出来ない。
・「逢瀬」中は名前が派手なピンク色に、「逢瀬」が完了した後しばらくは名前が薄いピンク色になる。
・「逢瀬」中は動けない(これは最初からそのつもりでしたが書き忘れていました)。
・「逢瀬」中は視界が狭くなる。
・恋人の内片方が開幕からインポスター(あるいはセットでアサインされる別の役職・陣営)に命を握られていていつでも遠隔キル可能(誰が自分の命を握っているかは把握できない)なので最初はインポスターの味方をしなければいけないが、子供が出来た後は1人の命を犠牲にクルーや他陣営の味方をしても良い。
・ボタンはなしで2人きりで居ると自動で「逢瀬」状態になる(2人きりで居る事がデメリットにもなりうる)


これは色々考えていたら思いついたまた別の方向の話なのですが、クルーの邪魔者になるかどうかは考えずに
・付近に人が居ると「逢瀬」が出来ず、途中で誰かに近づかれると中断される
・「逢瀬」が中断されると慌てふためいて少しの間動けなくなる。
というのはどうでしょうか。
人目を忍んで逢瀬をしているという設定的にも2人きりじゃないといけない方がしっくり来ますし、恋人達的には「相手が誰であれ近づかれたくない」「人目を避けている以上それがキル陣営だと非常に危険」という事で「逢瀬」の間は緊張感があると思います。
これだと何かホラー映画などでみんなで真剣に対策を考える流れを無視して二人きりでいちゃついてたら死ぬ枠っぽくてそれはそれでありかなという気がしましたがいかがでしょうか。
これだと名前を「バカップル」とかに変える必要がありますかね。


>別物にはなってますけど、例えばそれが会議開始時に報告されるとかなら一つの推理要素にはなりますからそれはそれでありなのではっておもいました(「隠れる」っていう必要性も上がってますし)

ではこちらの方も別ものとして検討お願いしても良いでしょうか？
単に「この船は我らファミリーが占拠した！！」的なイメージか、二人組ではなく1人の単独陣営で危険な生物を生み出す実験をしているマッドサイエンティスト的な感じも面白いかもしれませんね。
あるいは合体して自分らの子供を化け物にデザインしているマッドサイエンティスト夫婦…？

**Comment by yukieiji** [comment]
> 一応いただいた意見をもとに思いついた要素は書いておきますが、この方向は諦めて単独勝利陣営として考えた方が良いかなという気持ちが強くなってきました。
・周りに人が居る状態では「逢瀬」が出来ない。
・「逢瀬」中は名前が派手なピンク色に、「逢瀬」が完了した後しばらくは名前が薄いピンク色になる。
・「逢瀬」中は動けない(これは最初からそのつもりでしたが書き忘れていました)。
・「逢瀬」中は視界が狭くなる。
・恋人の内片方が開幕からインポスター(あるいはセットでアサインされる別の役職・陣営)に命を握られていていつでも遠隔キル可能(誰が自分の命を握っているかは把握できない)なので最初はインポスターの味方をしなければいけないが、子供が出来た後は1人の命を犠牲にクルーや他陣営の味方をしても良い。
・ボタンはなしで2人きりで居ると自動で「逢瀬」状態になる(2人きりで居る事がデメリットにもなりうる)

こういうものは基本的にデメリットを増やすよりかはメリットを増やしたほうがいいと私は思います
デメリットを増やすと「逢瀬」をやらずに逃げた方がいいってなりますし(現状+このデメリットだと、確率で子供が貰えるってのも相まって二人で浮き位置に立つ方がデメリットが多くなる気がします(2人で動き回ってるインポスターかもしれないって思われるので))

> これは色々考えていたら思いついたまた別の方向の話なのですが、クルーの邪魔者になるかどうかは考えずに
・付近に人が居ると「逢瀬」が出来ず、途中で誰かに近づかれると中断される
・「逢瀬」が中断されると慌てふためいて少しの間動けなくなる。
というのはどうでしょうか。
人目を忍んで逢瀬をしているという設定的にも2人きりじゃないといけない方がしっくり来ますし、恋人達的には「相手が誰であれ近づかれたくない」「人目を避けている以上それがキル陣営だと非常に危険」という事で「逢瀬」の間は緊張感があると思います。
これだと何かホラー映画などでみんなで真剣に対策を考える流れを無視して二人きりでいちゃついてたら死ぬ枠っぽくてそれはそれでありかなという気がしましたがいかがでしょうか。
これだと名前を「バカップル」とかに変える必要がありますかね。

上にもある通り逃げた方がいいってなりそうな気がします

> ではこちらの方も別ものとして検討お願いしても良いでしょうか？

これを検討するのであれば以下の部分を考える必要があります
- 子供の生まれる判定が会議依存をどうにかしないと負け確になる問題(確率で生まれるって部分もあって結局規定回数会議を起こさないといけないのはバランス的にちょっと・・・)
- 子供ができると片方が落ちると何もできない無力な役職が生まれてしまう問題

**Comment by gang-lion8** [comment]
まず現状子供を作る事のメリットが「片方が死んでも後追いしなくなる」と「子供の分の持ち票が増える」の二つだけしかなくて、「逢瀬」そのものは危険な行為でしかないので、「逢瀬」そのものにメリットを見出せるようにする事が重要でしょうか。
さらにはそのメリットがクルーを脅かすものであればなおよし？
・指定回数「逢瀬」をすれば必ず子供が出来る(運が良ければ指定回数未満でも出来る)
・現状の設定とは逆に「逢瀬」をしないと名前の色が変わってしまう
・「逢瀬」をした後は一定時間「賢者タイム」モードになり様々な能力を得る
例:2人で一緒にいれば自動でキルを防ぐ。離れてもお互いの位置がわかる。視界が広くなる。矢印などで周囲に居る人間の位置がわかる。キル能力を持たない相手のみキル出来るがどちらかがキルをした時点で両者共に「賢者タイム」が強制終了する。
最後のは流石にどうなのとは思いますが、役職を明かしたくない理由になりますし、お互いにキルができないのでキル陣営と協力関係を結びやすくなる気がします。
因みにランダムにどれか一つの能力を得るっていうのは出来るんでしょうか？

別物になってる方については二つのものを並行して話しているとややこしくなってしまいますし別でチケットを出した方が良いですかね？

**Comment by yukieiji** [comment]
> まず現状子供を作る事のメリットが「片方が死んでも後追いしなくなる」と「子供の分の持ち票が増える」の二つだけしかなくて、「逢瀬」そのものは危険な行為でしかないので、「逢瀬」そのものにメリットを見出せるようにする事が重要でしょうか。
さらにはそのメリットがクルーを脅かすものであればなおよし？

メリットを見いだせるというかメリットが有るような状態ですね(メリットが見いだせるだけだとデメリットを増やす方向にも生きそうな気がするので)

> ・現状の設定とは逆に「逢瀬」をしないと名前の色が変わってしまう

隠れることが基本の第三陣営がそうなると使いにくい役職になる気がします

> 「逢瀬」をした後は一定時間「賢者タイム」モードになり様々な能力を得る

これくらいならできますけど

> 例:2人で一緒にいれば自動でキルを防ぐ。

人外に即バレしますけど問題ないですか

> 離れてもお互いの位置がわかる。

わかってもインポスター見たく連携が必須の役職ではないからどうなのかな・・・

> 視界が広くなる。

オプションで設定する内容と被るのでどうなのかな・・・

> 矢印などで周囲に居る人間の位置がわかる。

上にもありますけど周囲に人が居ても困らないので必要な能力なのかな

> キル能力を持たない相手のみキル出来るがどちらかがキルをした時点で両者共に「賢者タイム」が強制終了する。

もしこれを実装するなら単独陣営にするべきだと思います

> 別物になってる方については二つのものを並行して話しているとややこしくなってしまいますし別でチケットを出した方が良いですかね？

2つのことを考えないといけないということはきちんと基礎が固まってないはずなのでディスカッションに移動します、それぞれコメントを立てるのでそこに返信してください
