### ISSUE TITLE
フェンサー(剣客)：クルー陣営役職。

### ISSUE THREAD

**Issue by issyoukimizu** [yukieiji/ExtremeRoles#12]
### 役職名 / Role Name
フェンサー
### 役職の色 / Role color
緑系統
### 役職の説明 / Role description
「敵を返り討ちにしてやろう」
自分をキルしてきた相手をキルし返せる役職。
### 役職の能力 / Role ability

ある回数(設定で変更可能。最大2回)だけ一定時間の間「受け身」受付状態になる事ができる。
「受け身」中に敵がキルをしてきた場合、そのキルを無効化すると同時にキルボタンが出現し、相手を殺せるようになる。
この受け身中は無敵であるため、即座に反応できれば一方的に相手を殺すことが可能。
ただし、受け身が終了した後は次の受け身が可能になるまでクールダウンが発生する為、もたつくと殺されてしまう。

動画投稿者の猫野和錆さんがモチーフ(ジェダイ騎士のイメージ)
「今、あやしい動きをしたのだ？」

### 他陣営への影響 / Effect on other teams
純粋に人外にとって脅威となるが、タイムマスターのように発動の瞬間を他プレイヤーが認知することができないため、人外がうまく撃ち勝てば役職を乗っ取ることが可能。
また、ジャッカルにサイドキックにされてから昇格した場合も、同様にフェンサーを騙ってやり過ごすことが可能となる。
この他、キルボタンは陣営を区別しないため、場合によっては誤って無実のクルーを殺してしまうリスクもある。

### 陣営 / Team
- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 敵がキルをしてきた場合、そのキルを無効化する。その後、クルー陣営(ライトフェンサー)の場合は普段は無効化されているキルボタンが有効化、インポスター陣営(ダークフェンサー)の場合はキルクールが一瞬で明ける。
ただし、相手側のキルクールは明けたままの上、キルを一度防いだ後は次の受け身までクールダウンが発生する為、もたつくと殺されてしまう。

これキルボタンを連打されたら貫通してしまうのですがそれは問題ないのでしょうか

**Comment by issyoukimizu** [comment]
うーん、例えば相手のキルクールを一秒だけ追加する、とかが可能でしたらそうしたほうがいいかもしれません。

あと、人外目線でキルモーション自体は発生する、という場合は殺せていないことに気づくのに時間が一瞬かかる可能性があるかもしれません。

**Comment by yukieiji** [comment]
> うーん、例えば相手のキルクールを一秒だけ追加する、とかが可能でしたらそうしたほうがいいかもしれません。

1秒でキルボタンが出たかどうかを判定出来るかって問題も出てきます。

> あと、人外目線でキルモーション自体は発生する、という場合は殺せていないことに気づくのに時間が一瞬かかる可能性があるかもしれません。

それはプログラムの実装上無理です

**Comment by issyoukimizu** [comment]
キルボタン自体は最初から存在しているイメージです。
ライトフェンサーの場合は押しても反応しないのが、切られた瞬間キルボタンが押せるようになる、という感じです。
1秒で難しいなら2～3秒くらい……？ここら辺は設定で調整できませんでしょうか。

**Comment by yukieiji** [comment]
> キルボタン自体は最初から存在しているイメージです。
ライトフェンサーの場合は押しても反応しないのが、切られた瞬間キルボタンが押せるようになる、という感じです。

それはプログラムの実装上無理です

**Comment by issyoukimizu** [comment]
ならば、単純にキルしてきた相手への付与クールを2秒～3秒と少々長めにする感じでどうでしょうか。

**Comment by yukieiji** [comment]
> ならば、単純にキルしてきた相手への付与クールを2秒～3秒と少々長めにする感じでどうでしょうか。

一番の問題はタスクやってる最中にライトフェンサーがキルされた時に気づくかどうかってのもあります

**Comment by issyoukimizu** [comment]
パッシブではなく、TMのように受け身受付時間があるのも考えています。
元々は両方とも受け身受付時間が存在すると考えていたのですが、ダークフェンサーがキルクールが明けている状態では気づけないというハンデがあるのでダークフェンサーにテコ入れをする目的でパッシブにしていました。
ライトは受け身時間制限あり、ダークはパッシブというパターンも考えていますが、あまり両者の能力差異を大きくしたくなかったのでパッシブでそろえていました。
なので、パッシブでは強すぎるのであれば受け身受付時間ありで行こうと思います。

**Comment by yukieiji** [comment]
チケットも更新お願いします

**Comment by yukieiji** [comment]
返信が遅れました

実装簡略化の観点からTMと同じく能力発動中にキルされた時にキルボタンが生えてくる仕様でも問題ないでしょうか

**Comment by issyoukimizu** [comment]
はい、それでいいと思います。

**Comment by yukieiji** [comment]
能力としても問題はなさそうに見えます
色さえきちんと決まれば実装に取り掛かろうと思います

**Comment by yukieiji** [comment]
色を[Pin](https://www.color-sample.com/colors/3061/)に決定(色が気に食わない場合はコメントして下さい)
開発版コミット4841d6d73bdf0fb1e0838134e257cb50d6e190dc完成したのでクローズします
