### ISSUE TITLE
StreamerModeで表示されるカスタムメッセージが正しく表示されない

### ISSUE THREAD

**Issue by soukunsandesu** [yukieiji/ExtremeRoles#120]
## バグの情報 / Info of bug
StreamerModeを有効にしたときにwith Extreme Rolesが隠れてしまう。また、StreamerModeを有効にしていても、部屋に入った瞬間はテキストが表示されない。設定を再度有効にしたら表示された。
### 期待される動作 / Your Expectation
******のところにすっぽりはまると思っていました。
![image](https://user-images.githubusercontent.com/76250388/175759487-45cacca4-78e0-4c60-a9a8-3c0d9a27564e.png)

### 実際の動作 / The Reality
画面の下にテキストが行ってしまってみることができない。下の動画は改行コードを消したものになります
https://user-images.githubusercontent.com/76250388/175759668-e24321b5-8d67-4031-ae43-18d00411bf7a.mp4

### このバグに対するあなたの意見 / Your Proposal
せっかくシステムでテキストを用意しているのに表示されないのはもったいないのかな...?と思いました。

### バグ発生時のログ / log when issue occur
[ExtremeRolesDumpedLog 2022-06-25T14-27-37.log](https://github.com/yukieiji/ExtremeRoles/files/8983967/ExtremeRolesDumpedLog.2022-06-25T14-27-37.log)

### Among Usバージョン/ Among Us Version
Among Us v2022.6.22e

### Modバージョン / Mod Version
Extreme Roles v3.1.0.1 with Extreme Skins

### リージョン/Region
- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [x] :アジア/Asia
- [ ] :カスタム/Custom

### プレイヤー人数/Player Num
1人

### 使用したオプション/Use Option
[option.csv](https://github.com/yukieiji/ExtremeRoles/files/8983969/option.csv)

**Comment by yukieiji** [comment]
画面解像度の問題だと思います、解像度HDでは正しく動作していますがご使用の解像度を教えていただいてもよろしいでしょうか？

**Comment by soukunsandesu** [comment]
1920x1080です

**Comment by yukieiji** [comment]
FullHDでも問題ないんですがゲームの解像度はFullHDで間違ってないですか？
![code_](https://user-images.githubusercontent.com/40425798/175774280-e1cc963d-6177-488a-99f0-bfd867e99815.PNG)

**Comment by soukunsandesu** [comment]
間違っていないです

**Comment by yukieiji** [comment]
再現しないかつ、表示ロジックを変更したためクローズします
それでも出る場合はコメントを願いします
