### ISSUE TITLE
インポスターの役職が正常に割り当てられず、暗転バグが起きた。（役職テキストがなく、第二イントロも無かった。）

### ISSUE THREAD

**Issue by TAKUGG** [yukieiji/ExtremeRoles#121]
## バグの情報 / Info of bug
インポスターの役職が正常に割り当てられず、暗転バグが起きた。（役職テキストがなく、第二イントロも無かった。）
### 実際の動作 / The Reality
https://70.gigafile.nu/0702-604c63d1f8e9bebd1b0588a90b55288f

### このバグに対するあなたの意見 / Your Proposal
特にないです

### バグ発生時のログ / log when issue occur
https://70.gigafile.nu/0702-bd7431ac7576f88d9df27d18979a7f341

### Among Usバージョン/ Among Us Version

Among Us v2022.6.21s
Among Us v2022.6.22e

### Modバージョン / Mod Version

Extreme Roles v3.1.0.1

### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [x] :アジア/Asia
- [ ] :カスタム/Custom

### プレイヤー人数/Player Num
11

### 使用したオプション/Use Option

[option.csv](https://github.com/yukieiji/ExtremeRoles/files/8984939/option.csv)

**Comment by yukieiji** [comment]
ExRのパフォーマンスが上がったために発生した不具合だと思われます
IntroCutsceneCoBeginに遅延処理を入れる修正を行いますので少々お待ち下さい

**Comment by yukieiji** [comment]
v3.1.0.2で恐らく修正
