### ISSUE TITLE
SChinese trans missing

### ISSUE THREAD

**Issue by ponyzerteal** [yukieiji/ExtremeRoles#124]
### SChinese trans missing

| Key | Cur | Fixed |
| --- | --- | --- |
| (each impostor role spawn rate) | 生成几率  | (each impostor role spawn rate) |
| (each impostor and neutral role spawn num) | 职业最大数量  | (each role spawn num) |

xlsx that has been fixed(2022/06/27T21:39(JST update))
[ExtremeRolesTransData.xlsx](https://github.com/yukieiji/ExtremeRoles/files/8991754/ExtremeRolesTransData.xlsx)

<details>
<summary>Original issues</summary>
Sorry, only crew is displayed correctly in the "roles Spawn Rate" option. This is the fixed document
[ExtremeRolesTransData.xlsx](https://github.com/yukieiji/ExtremeRoles/files/8991754/ExtremeRolesTransData.xlsx)
</details>

**Comment by yukieiji** [comment]
I will not release a corrected version immediately(wait and see about 1week), as it was just released today and there may be other errors.

**Comment by ponyzerteal** [comment]
I know it's bad to update frequently, but some roles names don't show up.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月27日(星期一) 晚上8:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yukieiji/ExtremeRoles] SChinese trans missing (Issue #124)





 
I will not release a corrected version immediately(wait and see about 1week), as it was just released today and there may be other errors.

**Comment by yukieiji** [comment]
I understand the urgency, but I'm looking at the translation data right now and there are a few mistakes(neutral role spawn num options)

This is a request, but please don't delete [translate xlsx](https://github.com/yukieiji/ExtremeRoles/blob/master/ExtremeRolesTransData.xlsx) column of translated data, but change them.(It's hard to copy-paste every time)

**Comment by yukieiji** [comment]
I will make a new release(include hotfix trans) tomorrow in case there is a crucial issue with the poltergeist.

**Comment by ponyzerteal** [comment]
OK, thank you for your hard work.

**Comment by ponyzerteal** [comment]
Next time there is an update, I will download the new file without changing its column

**Comment by yukieiji** [comment]
fixed in [v3.1.1.1](https://github.com/yukieiji/ExtremeRoles/releases/tag/v3.1.1.1)

**Comment by ponyzerteal** [comment]
I revised the imperfect translation, and then if there is any translation omission, I will revise it and submit it to you, so that you don't have to worry about it.
At present, I have only revised the translation problems I have received so far, and then I will send you the  json file if there are any translation problems
[ExtremeRoles.Resources.LangData.stringData.zip](https://github.com/yukieiji/ExtremeRoles/files/9002114/ExtremeRoles.Resources.LangData.stringData.zip)
.
