### ISSUE TITLE
[ニュートラル/Neutral] : レボリューショナリー/Revolutionary (誤吊りをさせて勝つ陣営)

### ISSUE THREAD

**Issue by Nushigami** [yukieiji/ExtremeRoles#127]
### 役職名 / Role Name
レボリューショナリー

### 役職の色 / Role color
黄色系統

### 役職の説明 / Role description
- 吊りで革命を起こすニュートラル役職
  - 投票時、自分の票が２人分になります｡
  - キル・ベントが使える。
  - オプションでサボタージュも使えるようになる。
  - 能力「特殊工作」は相手の能力を一度だけ空撃ちする状態にする。
  
- 勝利条件
  - 他のキル陣営全滅かつ生存者の過半数が同じ陣営。
  - クルー陣営を２人吊り、かつ生存している。

### 役職の能力 / Role ability
- 「特殊工作」
  - 近くのプレイヤーのキル・能力ボタンを一度だけ押しても発動せず、再びクールタイムを発生させる状態にする。
(会議を挟んでもこの状態は継続し、使用上限のある能力の使用可能回数は減らない)
  - デフォルトでは１回使える。

(相手が能力を使用したいときに使えないのは結構めんどくさいと思う。
他のいい案があったらそちらでも可。)

- 役職オプション(希望)
※他のキル役職と同じ部分は割愛
  - サボタージュを使えるか
    - デフォルトではOFF (ON/OFF)
  - 「特殊工作」の発動できる距離
    - (ここら辺よくわかってない)
  - 「特殊工作」のクールタイム
    - デフォルトでは30秒 (0.5〜120秒)
  - 「特殊工作」の使用上限
    - デフォルトでは１回 (0〜10回)
  - 投票時、自分の票が何人分になるか
    - デフォルトでは２人 (1〜15人)
  - 勝利条件２で何人吊る必要あるか
    - デフォルトでは２人 (1〜14人)
  - 勝利条件２でクルー陣営を含むか
    - デフォルトではON (ON/OFF)
  - 勝利条件2でインポスター陣営を含むか
    - デフォルトではOFF (ON/OFF)
  - 勝利条件2でニュートラル陣営を含むか
    - デフォルトではOFF (ON/OFF)

### 他陣営への影響 / Effect on other teams
- 間違えると負けてしまうため推理が慎重になる。

### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> クルー陣営を２人吊り、かつ生存している。
間違えると負けてしまうため推理が慎重になる。

正直クルー視点吊った人が自陣営であるかどうかを完全に理解することは不可能なので理不尽極まりない気がします
いくら推理で詰めても確実に分かるってことはない気がします

吊りで革命を起こすのがモットーなのに何故キルボタンをもたせるのかが疑問です、アリス見たく生きてて詰みが発生することは稀な気がしますが

**Comment by Nushigami** [comment]
> 正直クルー視点吊った人が自陣営であるかどうかを完全に理解することは不可能なので理不尽極まりない気がします
いくら推理で詰めても確実に分かるってことはない気がします

吊る必要のある人数を３人～４人にすればいいと思います。
(というか２人は少なすぎました)

> 吊りで革命を起こすのがモットーなのに何故キルボタンをもたせるのかが疑問です。

~~「革命とはとどのつまり殺しだから」という安直な考えです~~
ジェスターやタスクマスターのように自分の力だけで勝利できる訳ではないのでキルボタンは必要だと思います。
(一応議論誘導や情報隠蔽などできることはあるけど決め手に欠ける。ジェスターは＋動きで怪しく見せることができるためこれより簡単と判断)
ただキルしすぎてしまうとコンセントと反するためキルするのに何かデメリットをつけた方が良かったですね。
(例えばキルする度にクールタイムが増えるとか)

P.S.
「特殊工作」の回数はデフォルト１回だと少ないかも

**Comment by yukieiji** [comment]
> 吊る必要のある人数を３人～４人にすればいいと思います。
(というか２人は少なすぎました)

3～4人にしてもクルー側からしたらローラーができなくなってインポスターもニュートラルにしても吊れない、インポスター側からしたらキルをしてクルーを誤吊りさせたいのにできない(キルをしても負けるし、キルをしなくても負けるって言う事になりそうな気がします)からそんなに変わらない気がします(逆に5人にしたら勝利できなくなりますし)

> ジェスターやタスクマスターのように自分の力だけで勝利できる訳ではないのでキルボタンは必要だと思います。
(一応議論誘導や情報隠蔽などできることはあるけど決め手に欠ける。ジェスターは＋動きで怪しく見せることができるためこれより簡単と判断)
ただキルしすぎてしまうとコンセントと反するためキルするのに何かデメリットをつけた方が良かったですね。
(例えばキルする度にクールタイムが増えるとか)

この役職にキルボタンがあるとキルして隠れて他の人が吊れると勝てるということになるので、キルし得になると思います(キルすることで両方の勝利が近づいてる感じですかね)

**Comment by Nushigami** [comment]
> 3～4人にしてもクルー側からしたらローラーができなくなってインポスターもニュートラルにしても吊れない、インポスター側からしたらキルをしてクルーを誤吊りさせたいのにできない(キルをしても負けるし、キルをしなくても負けるって言う事になりそうな気がします)からそんなに変わらない気がします

票数見ればエボリューショナリーが生きていることがわかりますし、後半エボリューショナリーが生きているのを見てから吊るか吊らないか決めることだってできるのではないでしょうか?

> この役職にキルボタンがあるとキルして隠れて他の人が吊れると勝てるということになるので、キルし得になると思います(キルすることで両方の勝利が近づいてる感じですかね)

キルが通ったらそうなんですが、バレて吊られたら負けなので、、、
あとそれはアリスも同じだと思ってるんですが

**Comment by yukieiji** [comment]
> 票数見ればエボリューショナリーが生きていることがわかりますし、後半エボリューショナリーが生きているのを見てから吊るか吊らないか決めることだってできるのではないでしょうか?

生きているとわかっていても誰がクルーではないかを判定することは難しい気がします、また後半そんな暇があるとは思えないです

生きてるのはわかってもそれを見分けることは難しいはずです

> キルが通ったらそうなんですが、バレて吊られたら負けなので、、、

バレなかったらクルーが吊られるのでしょう？

> あとそれはアリスも同じだと思うのですが

アリスの場合はキルをするとインポスターをキルしてしまう可能性があって、それは自身の勝利を狭める行為になります

**Comment by Nushigami** [comment]
> 生きてるのはわかってもそれを見分けることは難しいはずです

行動や最終位置や議論中の言動・姿勢・証言などで大体の黒はわかるのではないでしょうか？
エボリューショナリーはキル陣営なので分からない時は最悪タスク進行で頑張ればいいです。

>バレなかったらクルーが吊られるのでしょう？

エボリューショナリーがいる関係上安易に吊ることはなくなりますし、怪しかった他のキル陣営が吊られることだってあります。
また味方のいない分、位置偽装がしずらく浮きやキル可能位置で疑われる方が多いのではないでしょうか

> アリスの場合はキルをするとインポスターをキルしてしまう可能性があって、それは自身の勝利を狭める行為になります

エボリューショナリーもクルーが減って誤吊り先が居なくなるかつ他キル陣営にキルされやすくなるのではないでしょうか？
アリスでもインポスター以外をキルした場合はインポスターにキルされやすくなりますし

ただ上ではああいいましたが、キルボタンがあってバランスが取れなそうな場合は無くしてもいいです。
(自分から見てそこまで壊れてはないと思っているだけです)

これ書いている途中思い出したんですけどアサシンが誰がエボリューショナリーかが一目でわかっちゃいますね
(アサシンを入れている時にエボリューショナリーを入れなければいいだけですが)

**Comment by yukieiji** [comment]
> 行動や最終位置や議論中の言動・姿勢・証言などで大体の黒はわかるのではないでしょうか？
エボリューショナリーはキル陣営なので分からない時は最悪タスク進行で頑張ればいいです。

大体の黒がわかったとしてもそれが100％黒であることをプレイヤーが把握することは不可能なはずです(現行犯以外で100％黒吊りは不可能であると思ってます、だからローラーという手段がクルー陣営にとって有利なのです)
キル陣営であるということはキルが加速タスク進捗が少ない場合で最終盤面を迎える可能性もあるはずです、その場合でタスク進行になるのかも疑問です

> エボリューショナリーがいる関係上安易に吊ることはなくなりますし、怪しかった他のキル陣営が吊られることだってあります。
また味方のいない分、位置偽装がしずらく浮きやキル可能位置で疑われる方が多いのではないでしょうか

基本的にはローラーになる気がします、けどそのローラーが封じられてる時点でどうやってクルーが勝てるのか疑問に思えます

> エボリューショナリーもクルーが減って誤吊り先が居なくなるかつ他キル陣営にキルされやすくなるのではないでしょうか？
アリスでもインポスター以外をキルした場合はインポスターにキルされやすくなりますし

エボリューショナリーはインポスターだろうがクルーだろうが切っても特に問題ないと私には見えてます、誰でもいいから切って人がつれればエボリューショナリーは勝利に近づくはずです(ついでに切れば切るほど生存勝利に近づくのでキルボタンは押し得は気がします、吊られるデメリットよりメリットのほうが大きいでしょう)
アリスの場合はキルする人がインポスター意外であると見極める必要があります、見極めなければ勝利が遠のくので(自分の勝利も遠のくし吊られる可能性のあるアリス自体のキルボタンは重いはずです)

> ただ上ではああいいましたが、キルボタンがあってバランスが取れなそうな場合は無くしてもいいです。
(自分から見てそこまで壊れてはないと思っているだけです)

バランスというよりか持たせる必要性があるのかという疑問です
持たせなかったら持たせなかったで隠れることが出来るので、それもそれでどうなのかってのもあります(持たせると簡単に勝利できる <=> 持たせなくても簡単に勝利できるって感じです)

**Comment by yukieiji** [comment]
個人的に考えてるこの役職が入ることで各陣営の動き
- クルー
  - クルーを吊っては駄目なので大量の会議を使ってでも黒を落としたい
- インポスター
  - キルをして下手にクルーが吊られると困るので、キルができない <=> キルをしないと勝てない
  - 大量の会議が起きるので鬱陶しい
- 別ニュートラル
  - 勝手に勝利されると嫌なのでこの役職を死にものぐるいで落としたい

インポスター目線が完全に死んでる気がしますがどうでしょうか

#### 参考までにアリスの場合(理不尽な勝利を押し付けてると言うのとキルボタンを持ってるから比較されているのだろうですが)
- クルー
  - 死にものぐるいで落としたい
  - 破壊工作うざすぎる(タスクやりたくない)
- インポスター
  - 勝手に勝利されるので死にものぐるいで落としたい
  - キルを抑えてアリスに頑張ってもらおう(アリスには「破壊工作」、「サボタージュ」、「キル」という強力なインポスターサポート能力があるので、自分で頑張る必要性が無くなる)
  - 自分たちのキルはアリスが暴れ終わってからでも遅くない
- 別ニュートラル
  - 死にものぐるいで落としたい

インポスター目線はアリスが頑張れば人も減って浮いてそれで吊れれば動きやすい、破壊工作でクルーに莫大なダメージを与えれるというメリットとアリスが暴れることによって自陣営の人が減らされるというデメリットがあって、メリットはデメリットと同等かそれ以上だと思います

**Comment by Nushigami** [comment]
３時間ぐらい考えましたが、コンセプトにあった改善案が思い浮かびません。
おそらく今後考えても思い浮かばないのでこのissueはCloseします。
申し訳ありません。
