### ISSUE TITLE
敗北確定のサバイバーがクルー幽霊役職にならないオプション

### ISSUE THREAD

**Issue by Inumiya** [yukieiji/ExtremeRoles#128]
### 追加する機能の詳細 / Feature details
タスクが一定数終わってない状態で死亡したサバイバーが、クルーの幽霊役職にアサインされる/されないを選択するオプション

### 機能を追加するメリット / Benefits of adding features
死亡して勝利できなくなったサバイバーはクルーの味方をするとは限らないため、クルー幽霊役職にアサインされてもその能力を使わない可能性がある。そうなるとクルー幽霊役職が一つ無駄になってしまう。また、ポルターガイストで死体を壁に埋めるなどの迷惑行為をする可能性もある。
サバイバーの初手死をプレイングで防ぐことは難しく、敗北確定のサバイバーが幽霊役職になってしまう状況は起きてしまうため、オプションでアサインされないように制限してしまうのが良いと思います。

**Comment by yukieiji** [comment]
この機能が欲しいってのはわかりますが、[幽霊役職のアサイン仕様](https://github.com/yukieiji/ExtremeRoles/wiki/%E3%82%B4%E3%83%BC%E3%82%B9%E3%83%88%E3%83%AD%E3%83%BC%E3%83%AB)的に厳しい気がします(ここの下にある「幽霊役職の割り当ては生存役職のキルされた時の処理より先にアサインされます」)
サバイバーの場合はキルされた時の処理に敗北確定の処理が入るためです

**Comment by yukieiji** [comment]
もし実装するのであれば"サバイバー自体"が幽霊役職にならないという処理を入れるほうが楽な気がします

**Comment by yukieiji** [comment]
ごめんなさい
できそうだったので、今実装します

**Comment by yukieiji** [comment]
v3.1.3.0で実装
