### ISSUE TITLE
サイキッカー(超能力者)：クルー役職

### ISSUE THREAD

**Issue by ghost** [yukieiji/ExtremeRoles#13]
### 役職名 / Role Name
サイキッカー(超能力者)
### 役職の色 / Role color
青色系
### 役職の説明 / Role description
「仲間の断末魔を感じ取れ」
印をつけたプレイヤーの死を知ることが可能になる。
### 役職の能力 / Role ability
クルー陣営。
プレイヤーに目印を付けることが可能。そして、その目印のついたプレイヤーがキルされた瞬間にアンダーテイカーの視界が光る。
あるプレイヤーに目印を付けた後、別のプレイヤーに目印をつけなおすことも可能。その際、古い側の目印は消える。

モチーフは動画投稿者の駄犬ゆっくりさん(悲鳴要素。お前が駄犬お姉ちゃんになるんだよ！)
「うわあああああああああ！！」

### 他陣営への影響 / Effect on other teams
アンダーテイカーが存在していると、インポスターやジャッカルはキルタイミングを他者に悟られる危険性にさらされ続けることになる。
ただし、人外にも目印はつくので、場合によっては全く無駄になるリスクもある。

### 陣営 / Team
- [X] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> タスクを終了すると、誰かがキルされた瞬間に全プレイヤーの視界を光らせるようになるクルー陣営。
ただし、死を通知したときにインポスターやジャッカルの視界にバンシーの位置を示す矢印が短時間発生する。そのため、素早くその場から退避するか確白の仲間と合流しなければ殺されてしまう危険性がある。
自分が死んだ際も視界を光らせるが、他プレイヤーの場合とは色が異なる。(設定で他プレイヤーと同じに変更可能。発光無しにもできる)

能力に対して、発動するデメリット(コスト)が少ない気がします(タスク終了間際にCOすれば複数人(基本的にクルーのタスク進捗は同じだと仮定します)で囲む事でキル陣営から守ること出来ると思われます)

**Comment by issyoukimizu** [comment]
では、タスクが終了するまではただのクルーとして表記されるというのはどうでしょう？
例えばタスクが完了して会議を挟むことでバンシーに変化する、という感じです。

**Comment by yukieiji** [comment]
> では、タスクが終了するまではただのクルーとして表記されるというのはどうでしょう？
例えばタスクが完了して会議を挟むことでバンシーに変化する、という感じです。

どちらにしよタスク終了間際に固まって動けば意味ない気がします

これはすごい個人的な考えですがタスク完了は能力の発動コストとしては軽いと思ってます

**Comment by issyoukimizu** [comment]
うーん……。

では今思いつく範囲で案を2つ。
①知らせることのできるキルの回数に制限を付ける(1回。多くて2～3回くらい？)
②誰のキルでも知らせられるわけではなく、目印を付けた特定のプレイヤーがキルされた場合のみ知らせる。(会議を挟むと目印はリセットされる)

**Comment by issyoukimizu** [comment]
では、それでお願いしようと思います。

**Comment by issyoukimizu** [comment]
書き直しました。

**Comment by yukieiji** [comment]
②の能力の場合、タスクを終了させるのとインポスターに通知するって機能はいらない気がしますがどうでしょうか

**Comment by issyoukimizu** [comment]
ではそのように変更します。

**Comment by yukieiji** [comment]
目印が付け直せるってのはってのはどういうことでしょうか

**Comment by issyoukimizu** [comment]
あ、誰かに目印を付けた後、新しく別のプレイヤーに目印を付けると古いほうの目印が消えて新しくつけたほうが有効化する感じです。

**Comment by issyoukimizu** [comment]
とりあえず思いついた範囲で3つ案を。
①目印を付けたプレイヤーが死ぬとバンシーも死ぬ。
②目印を付けたプレイヤーが死ぬと２度と能力を使えなくなる。
③目印を付けたプレイヤーを殺すとインポスターのキルクールが短縮される。

**Comment by yukieiji** [comment]
バンシー本人以外にキルを知らせてる時点で恐らくウィスパーの上位互換であるのは免れない気がします

バンシー本人以外にキルを知らせる必要はあるのでしょうか

**Comment by issyoukimizu** [comment]
うーん……モチーフのイメージを守りつつ、印をつけた本人にしかキルタイミングが分からないようにするなら、サイドキックのように「印をつけた相手をバンシーにする」といったところでしょうか？
印をつける側の役職の名前は変える必要があるでしょうが。

**Comment by yukieiji** [comment]
> 印をつけた本人にしかキルタイミングが分からないようにするなら、サイドキックのように「印をつけた相手をバンシーにする」といったところでしょうか？
印をつける側の役職の名前は変える必要があるでしょうが。

印を付けた相手が相手自身が分かる必要はあるのでしょうか

**Comment by yukieiji** [comment]
> 役職としてならば、「印をつけた相手が死ぬと自分が分かる」がいいのは分かるんですが、それだとモチーフから離れてしまうんですよね……。
僕が色々役職を考え出したこと自体、ふにんがす参加者へのリスペクトの意味合いが強いので、なりすさんをモチーフに据えた以上は「叫ぶことで死を知らせる何らかの役職」という点はなるべく譲りたくない要素なんです。

能力が強すぎてバランスが大きく壊れるような役職だと、使いにくいので実装しても実際には使ってもらえない可能性は大いにあります(現状のままだとウィスパーは使われてないかつ、ウィスパーの完全上位互換かつ結構強いのでそうなるでしょう)
とにかく実装してほしいというなら実装の優先度はすごい低めになります(バランスが良くて使いやすい役職を優先的に実装していきますので、今は役職案がいっぱいあるので実装は1ヶ月以上先になると思われます(最低でもv1.20.0.0以降のどこかです))

**Comment by issyoukimizu** [comment]
むむむ……使ってもらえないなら本末転倒ですか………。

分かりました。「印をつけた相手が死ぬと自分だけが分かる」「印を付けられた対象は自分ではわからない」で行きます。

**Comment by yukieiji** [comment]
> むむむ……使ってもらえないなら本末転倒ですか………。

使ってもらえなくても実装してほしいって言うなら実装はします(ただし、優先度は低いです)

> ・印を付けた相手が吊られると、その吊られた相手がクルーだったかそうでなかったかが自分だけに分かる。ただし、詳しい役職までは分からない。(第三陣営やインポスターの区別をしない)

十分強力すぎるのですが

**Comment by issyoukimizu** [comment]
能力と名前、モチーフを変更いたしました。
どの道「殺されて悲鳴をあげる」のはちょっとズレてると思い始めていましたので……。

**Comment by yukieiji** [comment]
ユーザーが削除されたためチケットをクローズします
