### ISSUE TITLE
サバイバー敗北の条件を吊りのみにする設定

### ISSUE THREAD

**Issue by SaidRed** [yukieiji/ExtremeRoles#130]
### 追加する機能の詳細 / Feature details
サバイバー敗北の条件を吊りだけにする。
キルされた場合はクルー勝利に乗っかれる。

### 機能を追加するメリット / Benefits of adding features
サバイバーの作られた理由がクルーのローラー提案の抑止なので、初手キルなどが敗北理由になると可愛そうである。
キルされた時と追放された時で別処理できるようなので、吊りだけに限定するのはどうだろうかと思いました。

**Comment by yukieiji** [comment]
初期の段階のサバイバーであればこの提案は良しと思うのですが(どんな状況下であっても死ぬと勝利できないってのが初期案)

現実装段階のサバイバーはローラー提案の抑止とクルーのタスク高速化(タスクによる覚醒 + それによって死んでも良しとするプレイングが出来る)の2種類の役割を持っていると思います、おそらくこのオプションをいれるとタスク高速化の役割が薄れてしまうのではないかと思います

**Comment by SaidRed** [comment]
色々考え直してみました。
サバイバーがクルー幽霊役職となった場合、クルー勝利に乗っかれる設定はどうでしょう？
第一犠牲者だった場合だけの救済になりますからタスク促進の役割も薄れさせないのではと思います

**Comment by yukieiji** [comment]
> サバイバーがクルー幽霊役職となった場合、クルー勝利に乗っかれる設定はどうでしょう？
第一犠牲者だった場合だけの救済になりますからタスク促進の役割も薄れさせないのではと思います

サバイバーが勝利できない状態で死亡するとタスクがすべて消えるので、最初に死に得になりませんか

あと3点確認したいことがあります
1. 最初に提案されているオプションとは異なるこのオプションを入れたい理由は何なのでしょうか
    - キルのよる敗北が可哀想だからという理由であれば、これが提案された時に「初手キルとかで連続敗北しちゃうと萎えちゃいませんか？」って聞いた時に「特に問題ありません」という返信を頂いているので問題ないと私は思っています
2. 現状、#128 の提案にある通りサバイバーには幽霊役職にしないというオプションが実装されていましてそのオプションと提案されているオプションと相反している気がします(もし実装するとなればそれとの関係性を考える必要があります)
3. 幽霊役職のアサイン率が100％じゃない時、このオプションの意味がないのではないでしょうか

**Comment by SaidRed** [comment]
提案された時に了承を得ているとの事なので本件に関しては撤回でクローズしたいと思います。お騒がせしました。
