### ISSUE TITLE
ヤンデレの想い人をキルできなくする機能

### ISSUE THREAD

**Issue by suikouzatta** [yukieiji/ExtremeRoles#132]
### 追加する機能の詳細
ヤンデレのキル対象からヤンデレの想い人を除外する機能

### 機能を追加するメリット
ヤンデレが可哀想な思いをしないで済む

**Comment by yukieiji** [comment]
ヤンデレが想い人をキルできるような仕様になっているのは詰みが発生することを防止してるため、意図している動作です
もしキルできないようにする場合はそれ以外で何らかの詰みを防止する必要があります

**Comment by suikouzatta** [comment]
> ヤンデレが想い人をキルできるような仕様になっているのは詰みが発生することを防止してるため、意図している動作です

えっと、いまいち浮かばないのですが何かそうなるような盤面ってありましたっけ？

**Comment by yukieiji** [comment]
> えっと、いまいち浮かばないのですが何かそうなるような盤面ってありましたっけ？

詰みになる場面は以下の二種類です(他にもあるかもしれないですが私が今浮かぶ場面)
- 想い人を完全孤立させることでヤンデレを完全無害化することが出来る
- サブマージドやエアシップ等の広いマップで人が減ってくるとキルできなくなって敗北する可能性が増える(実際、以前のふにんがすでピロ彦さんが勝利したときも想い人が居たら勝利できなかったかもしれないです)

想い人はヤンデレのリミッターでもあり勝利の鍵でもあるという重要な存在であるため、それのコントロール権(生殺与奪も含めてね)はヤンデレが持つべきであると思ってます(ヤンデレに想い人のコントロール権があることによって、戦略の幅は広がっていると信じています。わざと切って暴走状態にして勝利するとか色々とあると思います)

**Comment by suikouzatta** [comment]
なるほど、そういう考えでしたらこの件は無かった事にして構いません

**Comment by suikouzatta** [comment]
はい、お騒がせしました
