### ISSUE TITLE
[ニュートラル/Neutral] : スキルイーター (キルした相手の能力をコピーする)

### ISSUE THREAD

**Issue by SaidRed** [yukieiji/ExtremeRoles#133]
### 役職名 / Role Name
スキルイーター
### 役職の色 / Role color
黒っぽい赤
### 役職の説明 / Role description
最初にキルした相手の能力をコピーする
勝利条件はジャッカルと同じ
### 役職の能力 / Role ability

最初は能力ボタンが無い状態
ゲーム中で初めてキルをする事で、キルした相手に能力があれば、その能力と同じ能力ボタンを得ることができる

○能力なしの場合
能力ボタンは発生しない
○能力ありクルー・インポスターの場合
キルした相手の能力と同じボタンが出てくる
(決めきれて無い内容)
・使用回数のある能力の回数をリセットするか、継承するか
・名前の色が他のプレーヤーに見える能力時の色
　→できるなら元々の能力元の色が良いかと
・サポーターのようにボタンじゃない相手の能力は？
　→できればコピーできるようにして欲しい
○能力ありニュートラルの場合
(決めきれて無い内容)
能力を得る
・勝利条件をどうするか
　元々の勝利条件だけにする？得た能力の勝利条件を追加する？それのみでしか勝利できないようにする？
　→条件を追加する場合
　　・食われてしまったニュートラルは同陣営として勝利に乗っかれる？

### 他陣営への影響 / Effect on other teams
COが語りの可能性が出てくる
インポスター陣営との食い合いが発生する

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
似たような他の役職の能力を奪う役職(#85 ,#49 )とかは以前提案された時に実装コストとメンテンスコスト的に非現実的だから難しいと答えた記憶があります

あとニュートラルだとサーヴァントとあんまり変わらない気がしますがどうでしょうか

**Comment by SaidRed** [comment]
> 似たような他の役職の能力を奪う役職(#85 ,#49 )とかは以前提案された時に実装コストとメンテンスコスト的に非現実的だから難しいと答えた記憶があります

すいません、前に提案されていた奪う役職を読めていませんでした。難しいとの事なのでクローズで大丈夫です。
一応、相手の職業は消さないのでゲームを壊しづらい事と、重要役職はキル出来ない設定で除外出来ると考えていました。
コピーし終わった時の動作関係のメンテナンスは考慮不足でした。

> あとニュートラルだとサーヴァントとあんまり変わらない気がしますがどうでしょうか

そうですね。それと、元々からクルーやインポスター陣営に変わらないと考えてたので、ニュートラルだけ勝利条件変えるのは間違ってますね
