### ISSUE TITLE
[陣営/Team] : 役職名/リフレクター (会議中のキルを防げる)

### ISSUE THREAD

**Issue by akinori205** [yukieiji/ExtremeRoles#134]
### 役職名 / Role Name
リフレクター
### 役職の色 / Role color
灰色
### 役職の説明 / Role description
会議中のキルに対して防ぐことができる。（これを入れるときは会議中にキルできる役職を入れる）
### 役職の能力 / Role ability

発動はシューターやゲッサーのキルを受けたときにキルボタンが発生する、フェンサーの会議バージョンみたいな感じ。
リスクはシェリフと同じようにクルーをキルすると自爆する。
### 他陣営への影響 / Effect on other teams
クルーに対して発動させると自爆するが、インポスターや第三陣営に対してはキルが発動する。（人外ルールの時にこれを入れたら適当に撃っても当たるんじゃないかな？）

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
何もせずに会議キルを防げてやり返せるのはバランス的にどうなのでしょうか
また、会議中のキルを防ぐというのであれば #102 の方がバランス的にもアクション的にも面白い気がします

**Comment by akinori205** [comment]
確認ありがとうございます。すでにそれに近い案があったんですね。たしかに#102のほうがバランス的にもいいですね。
この案はシューターによるキルを0にすることは出来ないかな？と考えてみたんです。そこで、この案とボディーガードの意見を組み合わせてみて考えてみたのですが、ボディーガードをフェンサーに置き換えてみたらどうでしょうか？
改めまして、ご返事ありがとうございます。

**Comment by yukieiji** [comment]
> この案とボディーガードの意見を組み合わせてみて考えてみたのですが、ボディーガードをフェンサーに置き換えてみたらどうでしょうか？

これはどういうことですか？

**Comment by akinori205** [comment]
最初に#102の案を見たときボディーガードだと結局キルされる。どうすれば自分の意図と噛み合うだろうと考えて出てきたのがフェンサーのカウンターの能力を会議に引き継げないだろうかです。でもよくよく考えたらパクリでしかないので却下してください。すみませんでした。

**Comment by yukieiji** [comment]
> 最初に#102の案を見たときボディーガードだと結局キルされる。どうすれば自分の意図と噛み合うだろうと考えて出てきたのがフェンサーのカウンターの能力を会議に引き継げないだろうかです。でもよくよく考えたらパクリでしかないので却下してください。すみませんでした。

この能力でも提案されている能力でもよくよく考えると普通のキル見たく誰がどういった状況かわからない状態ではなく、会議というみんなが議論している中でシューターがこの役職をピンポイントで打ち抜くのか疑問に思えました(COしたらふつう撃たないですし、COしなかったらこの役職が狙われることはない気がします)

**Comment by appleaoi** [comment]
お疲れ様です。横から失礼します。
#102 を提案しているものです。

akinori205さんへ
>でもよくよく考えたらパクリでしかないので却下してください。

個人的な考えですが、パクリであると感じてもどんどん提案していいと思います。（そこから、yukieijiさんや他の人のアイデアにつながる可能性があると自分は思っています。）

以降、この役職に関して。
この役職を見ていて自分も思ったのですが、「会議中のキルのみ」に対応できる役職だと、対応する役職がいるときだけの採用になってしまい、あまりゲームに採用されない役職になってしまうと思います。
なので、「フェンサー」か「シェリフ」にこの機能を追加（設定でON/OFFできる）し、シュートを受けるとキルボタンができるのほうが役職としての採用率は高いのかなと思いました。（相手をキルできるか・自爆するかは、シェリフと同じ。）

ただ、現状の役職の強化になってしまうので、yukieijiさんが最初にあげているバランス面をクリアできているかは怪しいです・・・。
（シュートされるかは、役職COしなくても議論を強く主導していけば撃たれる確率があがると思うので大丈夫だと思っています）

以上です。実装するなら、この案のほうが実装が楽かなと思いコメントさせてもらいました。

長文失礼しました。
