### ISSUE TITLE
［インポスター陣営］ : ヒーラー(クールタイムの回復を速める)

### ISSUE THREAD

**Issue by misosoup8374** [yukieiji/ExtremeRoles#135]
### 役職名 / Role Name
・ヒーラー
### 役職の色 / Role color
・未定
### 役職の説明 / Role description
・緑色の陣を貼り味方インポスターのクールタイムを速く進める事ができる
### 役職の能力 / Role ability

能力ボタン「陣設置」
・インポスター陣営にのみ有効なクールタイムを速める陣を設置する事ができます
・キルクール以外にも他のインポスターの能力クールダウンも陣の効果の対象になります
（陣の大きさや回復倍率は設定で変更可能です）
・陣は設定された秒数で非活性化状態になります
・陣は活性化状態でしか効果を発動せず陣がどの状態であろうと全陣営が視認できます
（陣は会議後消滅します）

陣の効果の対象外となる能力
・サボタージュ
・ヒーラーの陣
・サンドワームの強襲

### 他陣営への影響 / Effect on other teams
クルー陣営
陣を見つけてインポスターを特定する事ができる
インポスター 陣営 / Team
キルを加速させることができ序盤でも後半でも役割を持てる

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
発動に関してデメリットが少ない気がします
キルクールタイムを早めるという役職として #30 もありますし、そっちとの差別化も必要だと思います

**Comment by misosoup8374** [comment]
ご回答ありがとうございます。
発動条件につきましては以下の物を改善案として掲載します
・能力クールダウンを長めに設ける
・陣を設置するまでの時間を設定する
・陣の設置を会議時アナウンスを行う

この役職はキルクール以外にも他の能力のクールダウンも対象にしている点と
陣の中でしか発動出来ないという点で差別化を行っています

**Comment by yukieiji** [comment]
> 能力クールダウンを長めに設ける

デフォルトのクールタイムは30秒固定です(それ以外だと村ごとでの調整です)

> ・陣を設置するまでの時間を設定する
・陣の設置を会議時アナウンスを行う

門番してればこれらのデメリットは無いようなものな気がします

> この役職はキルクール以外にも他の能力のクールダウンも対象にしている点と
陣の中でしか発動出来ないという点で差別化を行っています

個人的には司令官が必要なくなってるんじゃないかなって思ってます
陣の中に入っていれば永続的に恩恵が得られるという点も相まって門番して、そこに陣を貼ればデメリットが無い気がします

**Comment by misosoup8374** [comment]
ご回答ありがとうございます
改善案として陣を発動の回数を1ターンに1回という制限を行いヒーラーが陣にいないと発動しないという条件を設けてみるのはどうでしょうか
改善案２として陣が活性化状態である場合陣自体が動いていくという特性を追加するのはどうでしょうか
動き方としましては左に向かって動き初め壁にぶつかると停止しますドアは貫通して進みます

**Comment by yukieiji** [comment]
> 改善案として陣を発動の回数を1ターンに1回という制限を行いヒーラーが陣にいないと発動しないという条件を設けてみるのはどうでしょうか

1ターンに1回よりゲーム全体に回数制限は付けるべきだと思います
その上でヒーラーが陣に居ないことって多分無い気がします(門番をするなら基本そうなると思います)

> 改善案２として陣が活性化状態である場合陣自体が動いていくという特性を追加するのはどうでしょうか
動き方としましては左に向かって動き初め壁にぶつかると停止しますドアは貫通して進みます

移動するよりかは陣の設置が会議後とかにしたほうがいい気がします
そうなると設置する意味がなくなってきてしまいますが

**Comment by misosoup8374** [comment]
ご回答ありがとうございます
この役職は司令官との役割が被ってしまってるんでこれ以上の改善は厳しいと考えクローズします
この案は第三陣営で流用しようと思っています
ありがとうございました
