### ISSUE TITLE
[ニュートラル] : 役職名/共犯者 (あなたも共犯だ)

### ISSUE THREAD

**Issue by unhappyset** [yukieiji/ExtremeRoles#136]
### 役職の説明 / 
他のキルができる陣営の勝利に乗ることができる

### 役職の能力 / Role ability
共犯者は、最初はキルできないニュートラル陣営しかしキルできる陣営が設定人数減るとキルができるようになる生き残った状態でキルできる陣営が勝利すると追加勝利となり自分でキルができるようになった場合単独陣営になりほかのキル陣営が勝っても自分は勝利できない

### 他陣営への影響 / 
キルできる状態になった時クルー陣営からはキルできる人が増えて厄介
　　　　　　　　　　第三陣営からは相方など殺される可能性がある

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by unhappyset** [comment]
能力を書き忘れたので追加します
￥

**Comment by yukieiji** [comment]
最初は隠れて人数が減ったら普通にキルしていけば勝てる気がするので、個人的にこの役職が負けるパターンが少なすぎる気がします

**Comment by unhappyset** [comment]
設定回数減ったら設定回数だけキルできるようにするのはどうでしょうか
2回に設定すれば2回だけキルができるなど

**Comment by yukieiji** [comment]
> 設定回数減ったら設定回数だけキルできるようにするのはどうでしょうか
2回に設定すれば2回だけキルができるなど

設定回数分キルし終わったあと詰みが発生しませんか
クルー的には人外吊りきってるのにゲーム終わらない、この役職的にはキルできないからどうすればいいのかってなる気がします

**Comment by unhappyset** [comment]
設定回数キルしたら普通にクルーメイト勝利とかですかね
人外を吊られないようにする立ち回りが必要ですが
強すぎたり弱すぎたりするならまあ諦めます

**Comment by unhappyset** [comment]
ちなみにキルできる陣営が一人もいなくてキルを使い切った場合はクルーメイト勝利です

**Comment by yukieiji** [comment]
> 設定回数キルしたら普通にクルーメイト勝利とかですかね
人外を吊られないようにする立ち回りが必要ですが

そうなると時々ある人外1 + クルー10人で人外が釣られた時、確定敗北が決定してしまうのですが

> 強すぎたり弱すぎたりするならまあ諦めます

強いかどうかをどう判断するかにもよりますが、個人的には能力的に言えばそこまで強くはないけど役職として勝ちすぎる気がするって感じです

**Comment by unhappyset** [comment]
わかりました
お騒がせしてすみません

**Comment by yukieiji** [comment]
クローズで大丈夫でしょうか？

**Comment by unhappyset** [comment]
OKです
