### ISSUE TITLE
[ニュートラル/Neutral] : アーソニスト(燃やせ)

### ISSUE THREAD

**Issue by misosoup8374** [yukieiji/ExtremeRoles#138]
### 役職名 / Role Name
アーソニスト
### 役職の色 / Role color
赤橙
### 役職の説明 / Role description
塗りと発火を駆使し生存者全員を燃やし尽くす事が目的の第三陣営
ベントやサボタージュは行えない
勝利条件：生存者全員にオイルを塗り付け発火
アーソニスト陣営以外の生存者が無害かつアーソニスト陣営の人数以下

### 役職の能力 / Role ability
●塗り付け
○塗り付けボタン長押しで効果を発動し対象のプレイヤーにオイルを塗りつます
○塗り付けを行っている最中に塗り付け範囲から外れると解除されます
○アーソニスト視点でオイルを塗り付けたプレイヤーの名前はオレンジ色に変化します
○塗り付けを行う事でオイルのストック本数が1本減少します

●重ね塗り
○塗り付けを行ったプレイヤーにもう1度オイルを塗り付ける事ができます
○重ね塗りを行われたプレイヤーは一定の範囲内に塗られてないプレイヤーが入るとそのプレイヤーにオイルを塗りつけます
○重ね塗りされたプレイヤーは会議が終わると塗り付け状態に戻ります
○重ね塗りをしたプレイヤーにもう1度重ね塗りは行えません
（重ね塗りは通常の塗り付けの2倍の時間がかかりオイルを2本消費します）

●会議中の塗り付け
○会議中にオイルのストックが5本以上あることで発動できます
○投票を行う際に塗り付けボタンが発生し任意のプレイヤーにオイルを塗れます
○既にオイルを塗ってあるプレイヤーに塗り付けることはできません
○この能力を発動させると全てのオイルストックを失います

●発火
○発火ボタンを押すとアーソニスト特有の発火キルを行います
・発火キルはオイルを塗っていないプレイヤーには5秒長押しで発動します
・オイルを塗っているプレイヤーには即発動します
・発火キルを行うと死体の色が焦げた色に変化し死体の色が区別できなくなります

○発火キルを行うことでオイルのストックを回復させます
・オイルの入手本数は設定で変更可能でランダム本数を入手させることも可能です
・オイルのストック上限は最大9本で上限を設定で変更することもできます

○全員にオイルを塗った状態で誰かに発火を行うと勝利できます
（この状況での発火の場合勝利画面に行く前に全員に死亡判定が発生します）

### 他陣営への影響 / Effect on other teams
クルー陣営：他プレイヤーの行動に注目しなければならなくなり集団行動を避けるような行動を行わなければならなくなる
インポスター陣営：特殊キルが行える点や生存者を減らすことはアーソニスト側のメリットにもなるので早めにキルをしたい

### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
まず全体的な疑問なのですがこの役職は何個のボタンを持つのでしょうか

> ○塗り付けボタン長押しで効果を発動し対象のプレイヤーにオイルを塗りつます
・発火キルはオイルを塗っていないプレイヤーには5秒長押しで発動します

長押しって処理は考慮して作っては無いのでこの処理はおそらく無理な気がします

**Comment by misosoup8374** [comment]
ご回答ありがとうございます
記入足らずすみません
ボタンは塗り付けボタン発火ボタン通報ボタン使用ボタンの4種類が基本です
長押しはエボルバーの進化方法を応用できないでしょうか？

**Comment by yukieiji** [comment]
> ボタンは塗り付けボタン発火ボタン通報ボタン使用ボタンの4種類が基本です

能力ボタンは基本1つしか持てない様な設計になっていますので能力を削るか、統合する必要があると思います

> 長押しはエボルバーの進化方法を応用できないでしょうか？

あれは長押ししているというか死体の近くに一定時間いるという判定ですので、その判定みたいな一定時間人の近くに居るというものにするとかなら出来ると思います

**Comment by misosoup8374** [comment]
発火ボタンをキルボタンに変更を行い処理を行わせることは可能でしょうか

**Comment by yukieiji** [comment]
> 発火ボタンをキルボタンに変更を行い処理を行わせることは可能でしょうか

可能だと思いますが、以下の理由でやりたくはないです
- キルボタンという名の能力ボタンになるのでバグの素になる(名前と異なる処理をやってる、人が見て処理を追い求めれない)
- 能力ボタンを複数持たせるとユーザーが混乱する(どのボタンをいつ押せばいいのかわからない、TORのハッカーがわかり易い例でしょう)

**Comment by misosoup8374** [comment]
オイルのストックが無くなった時と生存者全員に塗り終わった場合塗り付けボタンを変化させて発火ボタンにするという変更はできないでしょうか

この方法も実現が難しい場合は能力の調整を行い再投稿いたします

**Comment by misosoup8374** [comment]
会議中の塗り付けはあと1人が塗れないという対策としての救済措置なのでなくても大丈夫です
発火に関してはオイルビンの回復の為の手段でありアーソニストの潜伏問題を解消するために導入しています
初手の所持本数を０本にすることでアーソニストがキルをしないといけないというリスクを作っております
どちらかに傾けるとはどういうことでしょうか？

**Comment by yukieiji** [comment]
> 発火に関してはオイルビンの回復の為の手段でありアーソニストの潜伏問題を解消するために導入しています
初手の所持本数を０本にすることでアーソニストがキルをしないといけないというリスクを作っております

0本だとしても潜伏したほうがいいのではないでしょうか(最初キルするメリットがあんまり無いような、1キルでいっぱい貰えるなら初手からなんでその設定をしてないんだって話ですし)

> どちらかに傾けるとはどういうことでしょうか？

「オイルビン」という内部カウント(？)で色々と能力が使える使えない能力を重点的にするか、TORのアーソニストの能力を重点的にするかと言うかたちですね
今は言い方が悪いかもしれないですが中途半端に混ざってる気がします

**Comment by misosoup8374** [comment]
例えばですが
オイルビンを使う場合は何らかの方法でビンをためていき貯まった本数に応じて塗りや特殊キルが行えるという能力を与えるというパターンと
ビンを削除してTORのアーソニストに寄せつつ新たな能力をつけるというコンセプトで行えばいいでしょうか

**Comment by yukieiji** [comment]
> オイルビンを使う場合は何らかの方法でビンをためていき貯まった本数に応じて塗りや特殊キルが行えるという能力を与えるというパターンと
ビンを削除してTORのアーソニストに寄せつつ新たな能力をつけるというコンセプトで行えばいいでしょうか

そんな感じです、ビンを削除してアーソニストに寄せる場合は能力を付けるかどうかはコンセプト次第ですが

**Comment by yukieiji** [comment]
> ・オイルビンを貯める方法

貯める方法は時間経過でいいとは思いますけどね

> ・貯まったオイルビンの活用方法

現状提案されている方法で十分だとは思います。本数とかは調整する必要があるとは思いますが

**Comment by misosoup8374** [comment]
返信遅くなり申し訳ありません
この案はクローズし再投稿いたします
