### ISSUE TITLE
[クルーメイト] : ベントトラッパー (通気口を使う人外をしとめよう)

### ISSUE THREAD

**Issue by unhappyset** [yukieiji/ExtremeRoles#139]
### 役職名 / 
ベントトラッパー

### 役職の色 / 
黄色

### 役職の説明 /
 通気口に罠をしかけて敵をひっかけよう

### 役職の能力 / Role ability
ベントの近くでボタンを押して数秒止まることでベントに罠をしかけることができそこのベントに入った人は死んでしまう　しかし公式役職のエンジニアなどクルーメイトなどが死んでしまうリスクもある

### 他陣営への影響 / 
インポスターへの影響:インポスターがベントに入った際相方もしくは自分が死んでしまう
クルーメイト:エンジニア等が死んでしまう
ニュートラル:インポスター同様にベントに入った際相方等が死ぬ

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by unhappyset** [comment]
書き忘れましたがベントに罠仕掛けるのは設定回数のみです

**Comment by yukieiji** [comment]
> 書き忘れましたがベントに罠仕掛けるのは設定回数のみです

設定回数に追加して何らかのデメリットがあるべきだと思います(カーペンターのベント封鎖が要らない子になるので、それとの差別化は必要だと思います)

**Comment by unhappyset** [comment]
ベントに罠をしかけてる途中名前の色が人外視点だけ黄色になって役職がばれるなどはどうでしょう

**Comment by ankomon** [comment]
横から失礼します
罠が仕掛けられたベントから範囲内に一定時間いた存在がキルされるのはどうでしょうか?
これにより、ベントタスクやベント近くのタスクをしているクルーをキルしてしまうデメリットが生まれると思います
ただ、これはベントタスクがあるマップでしかデメリットにならない気がするので、良いデメリットではない気もしてますが

**Comment by unhappyset** [comment]
> 横から失礼します 罠が仕掛けられたベントから範囲内に一定時間いた存在がキルされるのはどうでしょうか? これにより、ベントタスクやベント近くのタスクをしているクルーをキルしてしまうデメリットが生まれると思います ただ、これはベントタスクがあるマップでしかデメリットにならない気がするので、良いデメリットではない気もしてますが

私はいいと思いますがyukieijiさんはどう思いますか

**Comment by yukieiji** [comment]
> 横から失礼します
罠が仕掛けられたベントから範囲内に一定時間いた存在がキルされるのはどうでしょうか?
これにより、ベントタスクやベント近くのタスクをしているクルーをキルしてしまうデメリットが生まれると思います
ただ、これはベントタスクがあるマップでしかデメリットにならない気がするので、良いデメリットではない気もしてますが

距離によるとは思いますがタスクの位置とベントの位置は結構離れてると思います、それとクルーがベントに近づくかと言われたらベントタスク以外で近づくことはないと思います、そう考えるとベントに近づく=人外になるのでそこまでクルーが当たるかなってのは疑問に思えます
どちらにせよカーペンターのベント封鎖より強い問題が解決していない気がします

**Comment by ankomon** [comment]
> ベントが使える範囲に近づいてボタンを押した場合、操作可能になるまでおそらく1秒近くくらい(遠くからボタンを押した場合は1秒は超えると思います)かかると思います、範囲とキルまでの時間によるとは思いますがこの役職の意味を持たせるようなオプションを考えた時は操作可能になった瞬間に弾け飛ぶのではないでしょうか

個人的にはキルの対象になる範囲はベントタスクが出来る範囲で、その範囲に居てキルされる時間は、ベントタスクをやり終えて離れるタイミングでキルされるかどうかくらいの時間で考えてましたが、確かに入ったら動く前にキルされるかもしれませんね…
unhappyset様はどう思いますか?

**Comment by yukieiji** [comment]
> 個人的にはキルの対象になる範囲はベントタスクが出来る範囲

確かAmongUsはベントタスク出来る範囲とベントが使用できる範囲は異なってると思ったので調査してきました
ベントタスクのほうが検知範囲が広いです
- ベントタスク出来る範囲
![ventClean](https://user-images.githubusercontent.com/40425798/179800727-10d58bb8-f280-4503-b98c-e2f49f1402ce.jpg)
- ベントが使える範囲
![ventUse](https://user-images.githubusercontent.com/40425798/179800884-1d4b13d0-81bd-4733-b118-96d36badf2ca.jpg)

> ベントタスクをやり終えて離れるタイミングでキルされるかどうかくらいの時間で考えてましたが、確かに入ったら動く前にキルされるかもしれませんね…

ベントタスクをやり始めてから離れるまでの時間というのであれば(個人差があるがおそらく10秒程度)問題ないとは思いますが能力としての意味がなさない気がします
上記範囲かつベント部分からベントタスクを終わって離れるまでの時間であれば入った瞬間にキルが発生すると思います

**Comment by ankomon** [comment]
> ベントタスクをやり始めてから離れるまでの時間というのであれば(個人差があるがおそらく10秒程度)問題ないとは思いますが能力としての意味がなさない気がします 上記範囲かつベント部分からベントタスクを終わって離れるまでの時間であれば入った瞬間にキルが発生すると思います

そうですね…
unhappysetさんはどうお考えですか?

**Comment by unhappyset** [comment]
> > ベントタスクをやり始めてから離れるまでの時間というのであれば(個人差があるがおそらく10秒程度)問題ないとは思いますが能力としての意味がなさない気がします 上記範囲かつベント部分からベントタスクを終わって離れるまでの時間であれば入った瞬間にキルが発生すると思います
> 
> そうですね… unhappysetさんはどうお考えですか?

そうですね　ベントの近くの人がキルされるのではなくベントに一定時間入っていた人がキルされるってのはどうでしょうもしくはキルされるのではなくベントから外が見えないなどは

**Comment by yukieiji** [comment]
> そうですね　ベントの近くの人がキルされるのではなくベントに一定時間入っていた人がキルされるってのはどうでしょう

ベントに入って一定時間待つと言う行為はエンジニア等のクルーがやることってほぼ無いような気がします、そう考えるとクルーが引っかかるというデメリットはなく人外ホイホイになってしまう気がします(引っかかりやすいようなベントにとりあえず使う、使うわずに置いておくメリットがあんまり無いような気がします(設置型はどうしても使い得にはなりやすいですけど、クルーに引っかからないという点であんまりクルーの事を考えなくていいってのはあります)

> もしくはキルされるのではなくベントから外が見えないなどは

ベントが見えなくなると言うのはカーペンターが一応その能力を持っています

**Comment by unhappyset** [comment]
ここまで見てきて考えたのですがベントに入ったらキルされるなどは強すぎに感じました自分で言うのもあれですけど（）
ベントに入ったらキルクールダウンが増加し、エンジニアが入った場合、ベントから追い出されてベントクールだけが消費される　これはどうでしょう

**Comment by yukieiji** [comment]
> ここまで見てきて考えたのですがベントに入ったらキルされるなどは強すぎに感じました自分で言うのもあれですけど（）
ベントに入ったらキルクールダウンが増加し、エンジニアが入った場合、ベントから追い出されてベントクールだけが消費される　これはどうでしょう

キルクール増加ならおそらく問題はないとは思います
問題なのはエンジニアのクールでしょう、ExRにはエンジニアのベント仕様をインポスターと同じに出来るのでそのオプションが有効時ほぼ無意味になってしまう点でしょうか

**Comment by yukieiji** [comment]
> インポスターがベントに入った際、キルクールダウンが増加、エンジニアの場合追い出されてクールダウンだけ消費　インポスターと同じオプションがONの場合そのターンベントから追い出されてベントが使えなくなる、というのはどう思いますかね

これで一番問題なのはエンジニアの役職が証明できてしまうという点でしょう
あと問題点があるとするならこのトラップが永続発動かどうかでしょうか

**Comment by ankomon** [comment]
> > インポスターがベントに入った際、キルクールダウンが増加、エンジニアの場合追い出されてクールダウンだけ消費　インポスターと同じオプションがONの場合そのターンベントから追い出されてベントが使えなくなる、というのはどう思いますかね
> 
> これで一番問題なのはエンジニアの役職が証明できてしまうという点でしょう あと問題点があるとするならこのトラップが永続発動かどうかでしょうか

インポスターが負うデメリットはキルクールが長くなることだけなので、追い出され方、キルクールの増加が永続なのか、次の会議までなのか次第ではありますが、その人がベントを使える人外ではなくエンジニア、という証明は、私は難しいように思います
どうでしょうか?

**Comment by yukieiji** [comment]
> インポスターが負うデメリットはキルクールが長くなることだけなので、追い出され方、キルクールの増加が永続なのか、次の会議までなのか次第ではありますが、その人がベントを使える人外ではなくエンジニア、という証明は、私は難しいように思います

追い出され方は1取りしか無いんで入ってすぐ追い出されたらエンジニア確定でいいでしょう、ボタン連打よりプログラムの処理速度のほうが圧倒的に早いはずです

**Comment by ankomon** [comment]
> 追い出され方は1取りしか無いんで入ってすぐ追い出されたらエンジニア確定でいいでしょう、ボタン連打よりプログラムの処理速度のほうが圧倒的に早いはずです

なるほど。ありがとうございます
