### ISSUE TITLE
サンドワーム（旧エイリアン）：インポスター役職

### ISSUE THREAD

**Issue by Inumiya** [yukieiji/ExtremeRoles#14]
### 役職名 / Role Name
サンドワーム

### 役職の色 / Role color
インポスター色

### 役職の説明 / Role description
ベントに入ったままキルができるインポスター陣営
光が苦手なのでベントから出ると弱体化する

### 役職の能力 / Role ability

キル（アクティブ）：
- 通常のインポスターと同様
- キルを使用しても強襲はクールダウン状態にならない

強襲（アクティブ）：
- ベントの中でのみ使用できる
  - 使用時にベントの蓋が開くアニメーション
- 自分が入っているベントの周辺にいるプレイヤー1人をキルする
  - 自分自身はベントに入ったまま
  - レンジは通常のキルより長い
- クールタイムはベントに入っている間、または、停電中に回復する
  - クールタイムの秒数は通常のキルとは別にオプションで設定できる
- 強襲を使用してもキルはクールダウン状態にならない

弱体化（パッシブ）：
- ベントから出ているときに常時発動
- 一定時間後に死亡する
  - デフォルト40秒
  - ベントに入ると一瞬でカウントが最大値に戻る
  - 停電中はカウントが最大値で固定される

メリット：姿を見せずにキルできる。キルレンジが長い
デメリット：定期的にベントに入る必要があるため、単独行動せざるを得ない

### 他陣営への影響 / Effect on other teams
- 単独行動をしていると吊られやすくなる
- ベントを使う役職がベントに近づきにくくなる
  -  調整のため、ベントを使う役職を強襲でキル出来るか否かオプションを用意（デフォルトはキル可）

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by Inumiya** [comment]
連投ですみません。
いいアイディアを頂いてしまったので

**Comment by Inumiya** [comment]
>  単独行動を続けている人が疑われやすくなる
これがインポスターへのデメリットかなと思います

いっそのことモンスターをインポスター陣営にしてもいいかなと思いました

**Comment by Inumiya** [comment]
いやコイツをインポスターにすると勝利条件がゆるくなって強すぎますね
ベントをモンスター以外が使用できない状態にする能力を追加するとかどうでしょう

**Comment by yukieiji** [comment]
> これがインポスターへのデメリットかなと思います
いっそのことモンスターをインポスター陣営にしてもいいです

個人的にはこいつの能力はインポスター陣営でも問題ないとは思います(勝利条件は全て無効化した状態で、デメリットを考え直す必要はありますが)

> ベントをモンスター以外が使用できない状態にする能力を追加するとかどうでしょう

そのベントにモンスターがいるとバレてしまいますがよろしいでしょうか

**Comment by Inumiya** [comment]
> ベントをモンスター以外が使用できない状態にする能力

ベント汚染：
- ベントの中でボタンを押して発動
- 一定時間そのベントをモンスター以外が使用できなくする

こういうイメージでした。
モンスターがベントを移動したあとも継続するので、「ベントが使えない≠そこモンスターがいる」です
まあ少し前までそこにいたことはバレてしまいますが


> 個人的にはこいつの能力はインポスター陣営でも問題ないとは思います

インポスター陣営にするなら、地上でのキルのデメリットをすごく重くすると良いかなと
地上でキルできる回数を決めるなど

**Comment by Inumiya** [comment]
インポスター役職として調整し直しました

**Comment by yukieiji** [comment]
返信が遅れてしまいました
概ね問題はない気がしますがメリーの特殊ベント「陣」と組み合わせた時、最強になってしまう気がする点ですね

**Comment by Inumiya** [comment]
ベントを増やす役職との組み合わせは想定していなかったです。。。
メリーの特殊ベントは対象外にするとか技術的に可能でしょうか？

無理な場合は、メリーと併用する際は強襲のクールタイムをオプションで長くするなど、ユーザ側で調整してもらう形がいいかなと思います
元々マップによって強さが変わる役職ですし、ユーザ側がオプションで色々調整しながら遊ぶ想定です

**Comment by yukieiji** [comment]
> ベントを増やす役職との組み合わせは想定していなかったです。。。
メリーの特殊ベントは対象外にするとか技術的に可能でしょうか？

増やされたベントはMOD内で管理してるので恐らく可能でしょう

あとはパッシブの自殺がちょっと重い気がします。デフォルトでキルクール増加やなんかがいい気がします

**Comment by Inumiya** [comment]
> 増やされたベントはMOD内で管理してるので恐らく可能でしょう

では役職説明にあるベントは、すべてMAPに元々あるベントのみを指しているものとして実装お願いします

> あとはパッシブの自殺がちょっと重い気がします

では、キルボタンと強襲ボタンのクールタイム+5秒から+10秒ですかね
ここの増える秒数もオプションで変更できるとありがたいです

**Comment by yukieiji** [comment]
> では、キルボタンと強襲ボタンのクールタイム+5秒から+10秒ですかね
ここの増える秒数もオプションで変更できるとありがたいです

停電中以外のキルはキルクールが伸び続ける(会議でもリセットされない)ってのを考えてますがどうでしょうか(停電中のキルもしくは強襲の使用で一定値回復とか)

**Comment by Inumiya** [comment]
> 私的には停電中以外のキルはキルクールが伸び続ける(会議でもリセットされない)ってのを考えてますがどうでしょうか(停電中のキルもしくは強襲の使用で一定値回復とか)

停電以外でキルをする→キルクールの最大値がXX秒増える
停電中にキルするor強襲でキルする→キルクールの最大値がyy秒減る
ってことですよね。いいと思います！

**Comment by yukieiji** [comment]
> 停電以外でキルをする→キルクールの最大値がXX秒増える
停電中にキルするor強襲でキルする→キルクールの最大値がyy秒減る
ってことですよね。いいと思います！

そんな感じです。あとは各種オプションの設定値とキルクールの回復はデフォルトキルクールを突き抜けて回復するかどうかでしょうか
恐らく専用のボタンを作る必要があるため強襲もクールタイムもいじれるはずです
- 強襲クールタイム：15秒(5～45秒)
- 停電時以外のキルによるキルクール増加量：5秒(1～10秒)
- 停電中のキル及び強襲によるキルクール減少量：3秒(1～5秒)

**Comment by Inumiya** [comment]
強襲のキルクール回復させるの大変な気がするのでデフォルトより短いのはいいですね
クルー側には推理の材料にもなりますし

> 強襲クールタイム：15秒(5～45秒)
停電時以外のキルによるキルクール増加量：5秒(1～10秒)
停電中のキル及び強襲によるキルクール減少量：3秒(1～5秒)

これでお願いします

**Comment by yukieiji** [comment]
わかりました
マイルストーンをv1.19.0.0にセットします

**Comment by Inumiya** [comment]
お願いします

**Comment by Inumiya** [comment]
すみません
こちら役職名、サンドワームに変えても良いですかね

**Comment by yukieiji** [comment]
開発版コミット375889cac266460a79ae5c75d7cd29178bb87b12にてでサンドワームが期待通りに動作することを確認しました
クローズします
