### ISSUE TITLE
[ニュートラル/Neutral] : アンブレイヤー/Umbrer (TORのアーソニストをバックポート/調整)

### ISSUE THREAD

**Issue by misosoup8374** [yukieiji/ExtremeRoles#140]
### 役職名 / Role Name
アンブレイヤー/Umbrer

### 役職の色 / Role color
未定

### 役職の説明 / Role description
- 生存者全員にウイルスを感染させることが目的の第三陣営
- キルやサボタージュ、ベントは使用できない
- 勝利条件:生存者にウイルスを感染させる

### 役職の能力 / Role ability

- ウイルス注入
  - ボタンを押し塗り付け範囲内にいるプレイヤーにウイルスを感染させます
  - アンブレイヤーから感染状態のプレイヤーの名前は役職の色に変化します
  - ウイルスの感染状況は会議後も引き継ぎます
  - 注入にかかる時間は設定で変更可能です

- ウイルス強化
  - 既に感染しているプレイヤーに対してもう1度ボタンを押すことで行うことで発生します(アイコンも変化)
  - ウイルスが強化されたプレイヤーは指定された範囲内に感染していないプレイヤーが一定時間入った時にウイルスに感染させます
  - 他のプレイヤーに感染させるか一定時間がたつか会議後には通常のウイルスの状態に戻ります
  - 「ウイルスの強化」の効果が切れる時間は設定で変更可能です

### 他陣営への影響 / Effect on other teams
- クルー陣営
  - 他プレイヤーの行動に注目しなければならなくなり集団行動を避けるような行動を行わなければならなくなる
- インポスター陣営
  - キルクールタイムが終わっていない時はなるべく誰にも近づかないように行動しないといけなくなる

### 陣営/team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

<details>
<summary>旧チケット内容</summary>

前回のアーソニスト案から大分離れてしまった為再投稿いたします
（編集方法がわからなかっただけとも言えます）

### 役職名 / Role Name
アーソニスト
### 役職の色 / Role color
赤橙
### 役職の説明 / Role description
生存者全員にオイルを塗り付け発火させることが目的の第三陣営
ベントやサボタージュが使えない
勝利条件
生存者全員にオイルを塗り発火する
アーソニスト陣営以外の生存者が無害かつアーソニスト陣営の人数以下

### 役職の能力 / Role ability
●塗り付け
塗り付けボタンを押し一定の範囲内にいるプレイヤーにオイルを塗り付ける事ができます
塗り付けにかかる時間は設定で変更可能です
アーソニスト視点でオイルを塗り付けたプレイヤーの名前はオレンジ色に変化します
塗り付けを行う事でオイルビンの本数を1本消費します
塗り付けが行われたプレイヤーには塗り付けをすることはできません
塗り付けは会議後も引き継がれます

●重ね塗り
オイルビンを3本以上持っているときに発動します
塗り付けに時間はかかりますが塗り付け範囲が少し広くなっています
対象1人に重ね塗りを行います
重ね塗りが行われた対象は近くに塗られていないプレイヤーが入ると即時オイルを塗り付けます
塗られていないプレイヤーが範囲内に入るかキルされるか会議後が終わると通常塗り付け状態になります
重ね塗りを行うとオイルビンを2本消費します

●オイルビン
この能力はアーソニストが能力を使う為に必要なものです
アーソニストが停止状態であるときにのみ製造が進みます
一定時間が経過するとオイルビンを1本製造します
製造されたオイルビンは会議後も引き継がれ最大9本までストック可能です

●発火
この能力は塗り付けが全員に終わった時に塗り付けボタンが変化します
発火ボタンの発動にはオイルビンを消費するかは設定で変更可能です
発火ボタンを押すと生存者全員に死亡判定が行われてから勝利画面へ行きます

塗り付け案2
この案はオイルビンを更に活用した内容としております
上の塗り付け案かこちらの案のどちらかを採用していただきたいです

●塗り付け
塗り付けボタンを押し一定の範囲内にいるプレイヤーにオイルを塗り付ける事ができます
塗り付けにかかる時間は設定で変更可能です
アーソニスト視点でオイルを塗り付けたプレイヤーの名前はオレンジ色に変化します
オイルビンの消費本数で効果が変わり塗り付け終わると全てのオイルビンを消費します
オイルビンの消費本数が増えるほどアーソニストが塗れる範囲が大きくなります
オイルビンの消費本数が3本以上の場合
塗り付け範囲にいるプレイヤー3人までにオイルを塗り付けます
オイルビンの消費本数が5本以上の場合
塗り付け範囲にいる全てのプレイヤーにオイルを塗ることが可能になります
ストック本数は最大9本までです

●重ね塗り
オイルビンの消費本数が5本の状態でオイルを塗ると発動します
重ね塗りが行えるようになり重ね塗り範囲内にいるプレイヤーは重ね塗りが行われます
重ね塗りが行われた対象は近くに塗られていないプレイヤーが入ると即時オイルを塗り付けます
塗られていないプレイヤーが範囲内に入るかキルされるか会議後が終わると通常塗り付け状態になります
重ね塗りを行うとオイルビンを2本消費します
重ね塗りの範囲は5本消費だとオイルビンの消費本数が1本の時の塗り範囲と同等であり消費本数が増えると拡大していきます

（その他の能力は変わらないため省略）
### 他陣営への影響 / Effect on other teams
クルー陣営：他プレイヤーの行動に注目しなければならなくなり集団行動を避けるような行動を行わなければならなくなる
インポスター陣営：キルクールタイムが終わっていない時はなるべく誰にも近づかないように行動しないといけなくなる

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral
</details>

**Comment by yukieiji** [comment]
> 前回のアーソニスト案から大分離れてしまった為再投稿いたします
（編集方法がわからなかっただけとも言えます）

左上の・・・のEditから編集できます

> （その他の能力は変わらないため省略）

どこからどこまでが変わらないのかよくわからないのでできる限りの記載をお願いします

### 両案共通
> ●重ね塗り

個人的には重ね塗りが強すぎて普通の塗りを行う必要がない気がします
この行為自体にデメリットか制限がないと劣化ペスト医師みたいな感じになる気がします

### 第一案返信
> ●発火
この能力は塗り付けが全員に終わった時に塗り付けボタンが変化します
発火ボタンの発動にはオイルビンを消費するかは設定で変更可能です
発火ボタンを押すと生存者全員に死亡判定が行われてから勝利画面へ行きます

全員が塗り終わったらその瞬間の勝利でいいと思いますがどうでしょう

### 第2案返信
> オイルビンの消費本数が5本以上の場合

オイルビン5本以上での能力発動が重ね塗りとダブっていますがどっちの処理が優先されますか？

**Comment by misosoup8374** [comment]
返信ありがとうございます
両案共通の返信です
省略した部分は勝利条件と発火とオイルビンのシステムになります
重ね塗りデメリットをつけるなら
・重ね塗りされたプレイヤーが他のプレイヤーにオイルを塗る時間の増加
・時間経過でオイルが剝がれる
・他人から重ね塗りが見えてしまう　などがデメリット候補ですかね

発火に関しては塗ってない人がキルされたり落ちたりしていきなり勝利画面に変位させないためです
発火が行えた方がよりアーソニストらしいと考えています

案2の返信です
オイルビンが5本以上ある場合両方発動します
通常の塗り付け範囲と重ね塗り範囲が発生します
重ね塗りと通常塗りの境界線が生れる感じです

**Comment by yukieiji** [comment]
> ・重ね塗りされたプレイヤーが他のプレイヤーにオイルを塗る時間の増加
・時間経過でオイルが剝がれる

ペスト医師でも数秒かかるということを考えれば塗る時間とそれが切れる時間は必ず必要だと思います、でないと緊急とか誰も治せない気がします(治しに行ったらアーソニスト勝利で即ゲーム終了とかになるので)
ペスト医師の能力を持つことを考えるにかなり重めのデメリットが無いと駄目な気がします

> ・他人から重ね塗りが見えてしまう

これはどういうことでしょうか？

> 発火に関しては塗ってない人がキルされたり落ちたりしていきなり勝利画面に変位させないためです

キルされたり人が落ちた場合はその人は塗らなくていい扱いになって、発火ボタンは押せるようになるのではないでしょうか

> 発火が行えた方がよりアーソニストらしいと考えています

"発火"を行えるのがアーソニストらしいのであれば"発火"という行為をゲーム中(勝利するために押すボタンではなくて何らかのアクション要素として、前チケットにあったようなもの)に行えたほうがいいのではないでしょうか("勝利が確定して追加で発火ボタンを押すTORのアーソニスト"がアーソニストらしいと言うのであれば話は違いますが)
勝利が確定しているような状況で追加でボタンを押す行為が必要なのかってのが私の中の疑問です(死亡するというロジックを入れると他の処理(幽霊役職アサイン)とも交じるのであんまりやりたくはないですね(最終結果だけ変える(見た目上死ぬ)って処理なら問題ないですがね))

> オイルビンが5本以上ある場合両方発動します
通常の塗り付け範囲と重ね塗り範囲が発生します
重ね塗りと通常塗りの境界線が生れる感じです

両方発生するのであれば通常の塗りつけを行うメリットがますます無いような気がします
範囲広い + ベースから3本広がってる状態で重ね塗りが全員に行える + 通常の塗りつけも出来る

**Comment by misosoup8374** [comment]
他人から塗りが見えるという点は重ね塗りされているプレイヤーにオレンジ色の輪郭を追加する
重ね塗りされたプレイヤーのネームタグがオレンジ色に変化するなど
他人からしか見えないという形ですかね

発火ボタンはTORを意識したり上がりに条件を付ける為に設置していたのでバランスを考える上でなくてもいいものかなとは思っています

重ね塗りはオイルビンを1本作る時間を10秒と仮定した場合
重ね塗りは30秒で1人確定で塗れる+遠隔でもう1人塗れるかもしれないという状況で
通常の塗りだと最速で30秒で確定2人に塗ることができます
リスクとか理想論で比べてますが重ね塗りは誰かに塗れるかわからないという大きな不確定要素があります
仮にも誰かに出会えたとして塗れるのは1人だけ
案１であれば大きくバランスが壊れることはないと思っています

**Comment by yukieiji** [comment]
> 他人から塗りが見えるという点は重ね塗りされているプレイヤーにオレンジ色の輪郭を追加する
重ね塗りされたプレイヤーのネームタグがオレンジ色に変化するなど
他人からしか見えないという形ですかね

これかなりクルー有利に働くと思うのですがどうでしょうか(黒ポイントが高くて塗られてるから吊りましょうとかアーソニストの勝利を邪魔するために吊りましょうってなると思います)

> 発火ボタンはTORを意識したり上がりに条件を付ける為に設置していたのでバランスを考える上でなくてもいいものかなとは思っています

バランスというよりか必要性でしょうか、勝ちが決まってるのに追加でアクションを取る必要性ですね

一応、アーソニストがExRに実装する予定がなかった理由を上げておきます
 - クルーインポスター的にほとんど推理要素がなくて人狼ゲームっぽくない
 - 下手に強化したり能力を追加するとペスト医師見たく、止めれないしよく分からないけどふわっとゲームが終わる
   - TORのアーソニストは勝率がそこまで高くないから推理要素がなくても問題ない(人外にも近づくので勝手に消えてることが多いので勝率が高くない、それが故に表に出てない)、ペスト医師はアーソニストより勝率も高いし推理要素が更に消えてるから問題になってる(なのそんでペスト医師が出禁になっている理由もそれにだと思います)

その上で返信していきます

> 重ね塗りはオイルビンを1本作る時間を10秒と仮定した場合
重ね塗りは30秒で1人確定で塗れる+遠隔でもう1人塗れるかもしれないという状況で
通常の塗りだと最速で30秒で確定2人に塗ることができます
リスクとか理想論で比べてますが重ね塗りは誰かに塗れるかわからないという大きな不確定要素があります
仮にも誰かに出会えたとして塗れるのは1人だけ
案１であれば大きくバランスが壊れることはないと思っています
（記述に不備があった為更新致しました）

ボタンがどんな使用になるかいまいち見えてこないので「塗る」という能力の通常のクールタイムと内部タイマー的な物があると考えます
基本的に能力のクールタイムは30秒なので塗るが使えるときには「重ね塗り」が基本になるのではないでしょうか
クールタイムを減らして10秒とかでも「重ね塗り」はTORのアーソニスト本来のデメリットである人外に近づく必要がなくなるって部分で積極的に使うことのほうが多いと思います(重ね塗りがあることで潜伏しないメリットもなくなってると思います、人が減ってきた時に「重ね塗り」を行えば広がりやすく隠れやすいでしょう)

> 案2に関しては
アーソニストの普通の塗り付けができる範囲を重ね塗りに置き換え
置き換えられる範囲がオイルビン1本相当分の範囲と考えております
重ね塗りは1人にしか行えません
重ね塗りの範囲に2人以上いる際はランダムに1人を重ね塗りの対象に変更します

その仕様になったとしても、重ね塗りとより遠距離から濡れるということを考えればそれを基本的に使うことが多いと思います

**Comment by misosoup8374** [comment]
アーソニストにも行動で推理を行なうという人狼要素はギリギリあるとは思います
推理要素を押し出すなら塗られた事を通知されるようにするとかまだやりようはあると思います
塗りボタンのクールタイムは無い物として考えています
そのクールタイムの代わりになるのがオイルビンの作成だと考えています

重ね塗りのデメリット案
・オイルビンの消費本数を増やす
・重ね塗りされたプレイヤーが塗りを行なった場合塗られたプレイヤーは塗られた事を自覚できるようにする
・重ね塗りが行える回数を制限する
・重ね塗りを行った後オイルビンの作成クールタイムを長くするなどです

第2案はこれ以上の修正案を出すことができなくなってしまったので第1案のみの返信とさせて頂きたいです

**Comment by yukieiji** [comment]
> アーソニストにも行動で推理を行なうという人狼要素はギリギリあるとは思います

人に近づくという行動が推理要素になるので、それが無くなる「重ね塗り」という行為はサブ行動かもっとレアな行動にするべきだと思います

> 塗りボタンのクールタイムは無い物として考えています
そのクールタイムの代わりになるのがオイルビンの作成だと考えています

クールタイムをなくすってのは出来ないはずです

> 重ね塗りのデメリット案
・オイルビンの消費本数を増やす
・重ね塗りされたプレイヤーが塗りを行なった場合塗られたプレイヤーは塗られた事を自覚できるようにする
・重ね塗りが行える回数を制限する
・重ね塗りを行った後オイルビンの作成クールタイムを長くするなどです

これらのデメリットがあったとしても最初に動かなければ特に問題がないように思えます
2つ目のデメリットは「重ね塗り」自体ができなくなるのでどうなのでしょうか

**Comment by misosoup8374** [comment]
レア行動にするという点では重ね塗りが行える回数を制限するという点で補えると思います
塗りのクールタイムは設定で変更可能という形にして村に任せるという形でいいと思います
最初に潜伏を行えてしまわないようにオイルビンが飽和すると自爆するという設定を付けるというので対処できると思います
2つ目のデメリットですが重ね塗りされていたプレイヤーがわかるというデメリットなので視認から詰めることができるというTORの魔女に近いデメリットとしています

**Comment by yukieiji** [comment]
> レア行動にするという点では重ね塗りが行える回数を制限するという点で補えると思います

回数制限を付けたとしても、1回であれば「重ね塗り」という行為の必要性が問われますし2～3回であれば最初に動かなくて「重ね塗り」をすればいい気がします(最初に通常塗りを行う必要性が無い気がします)

> 最初に潜伏を行えてしまわないようにオイルビンが飽和すると自爆するという設定を付けるというので対処できると思います

そこまでするとこの役職自体が使いにくいものになると思います(第三陣営は潜伏もしつつ必要な時に動けるってのが重要だと思います)

> 2つ目のデメリットですが重ね塗りされていたプレイヤーがわかるというデメリットなので視認から詰めることができるというTORの魔女に近いデメリットとしています

複数人居る陣営でもかなり重ためのデメリットで1人のアーソニストにそのデメリットを付けると「重ね塗り」を行う必要がないってなると思います(実際魔女も普通のキルをしたほうが強いって結論になってましたし)

**Comment by misosoup8374** [comment]
塗りのクールタイムを長めに設けて塗りを行っていくごとに減少させていくというのはどうでしょうか
これを重ね塗りのデメリット案として以下の案を提示できるようになります
・重ね塗りを行うと塗りのクールタイムを増加させる
・重ね塗りを行うとそのターンはオイルビンを作成できなくなる　
・重ね塗りを行っていくごとにオイルビンの作成クールタイムの増加

**Comment by misosoup8374** [comment]
現状をまとめて頂きありがとうございます
この2種類の塗り付けのバランスを取る方法として以下のものを提示します
・塗りを行うとランダムで重ね塗りか通常の塗りが行われる
・塗り付け時間で区別化する
○例　塗り付けボタンを押して5秒以上範囲内にプレイヤーがいたら通常の塗り10秒以上で重ね塗り
この方法をとることで重ね塗りを行える場面を限定することが可能になります

**Comment by yukieiji** [comment]
> ・塗りを行うとランダムで重ね塗りか通常の塗りが行われる

そうすると重ね塗りを使った戦略ができなくなりますけどよろしいでしょうか

> ・塗り付け時間で区別化する

ボタンのタイマーは減少式なので発動時の塗り付け時間は変更できますが、発動中に時間を変更するってのは出来ないはずです

**Comment by misosoup8374** [comment]
重ね塗りなのでシンプルに2回目の塗り付けで発動する形はどうでしょうか
通常の塗りが行われているプレイヤーにもう1回塗り付けることで発動という形です
局所的な場面ではささると思います
できたらの機能ですが重ね塗りの塗り付け時間を増やすこともデメリットにはなると思います
重ね塗りに必要なオイルビンの設定次第で大分化けさせることがこの案ではできると思います
塗りのバランス案はこの案が最後の案になります

**Comment by yukieiji** [comment]
> 重ね塗りなのでシンプルに2回目の塗り付けで発動する形はどうでしょうか
通常の塗りが行われているプレイヤーにもう1回塗り付けることで発動という形です
局所的な場面ではささると思います
できたらの機能ですが重ね塗りの塗り付け時間を増やすこともデメリットにはなると思います

確かにそれいいバランスだと思いますが、オイルビンがあると多分通常の塗りでいいってなりそうです(オイルビンが要らないものになってる感じですかね)
密結合してるがゆえに多分こうなってしまうのだと思います

**Comment by misosoup8374** [comment]
オイルビンは通常の塗り付けで消費しないとすれば解決できると思います
通常の塗りで消費されたとしてもオイルビンの余裕があったら使うというものなので後半の塗りの選択肢としての重ね塗りであると考えています

**Comment by yukieiji** [comment]
> オイルビンは通常の塗り付けで消費しないとすれば解決できると思います
通常の塗りで消費されたとしてもオイルビンの余裕があったら使うというものなので後半の塗りの選択肢としての重ね塗りであると考えています

ボタンのクールタイムもあってオイルビンのクールもあるという話だったので、同じ人に「重ね塗り」ができる時間が経ってる時点でオイルビンは常に使えるレベルで溜まっているような状態ではないでしょうか
オイルビンでこれを縛る必要性ってのもあるとは思います

**Comment by misosoup8374** [comment]
オイルビンは人が残っている前半に重ね塗りの抑制を行うためという目的があります
前半にいろんな人へ塗りを行おうとするとオイルビンが枯渇しすぐに試合が終わってしまうことを防げます
重ね塗りを活用しようとするなら前半潜伏してオイルビンを貯めていくという戦略や
積極的に色んな人に塗りに行って会えてない時は貯めるなど
立ち回りや戦略の幅を増やすために取り入れております

**Comment by yukieiji** [comment]
> オイルビンは人が残っている前半に重ね塗りの抑制を行うためという目的があります
前半にいろんな人へ塗りを行おうとするとオイルビンが枯渇しすぐに試合が終わってしまうことを防げます

抑制する必要はないのではないでしょうか？
重ね塗りを行おうとするとボタンのクールタイムが2重で発生する + 何回も同じ人と一緒になっていればその時点で疑いがかかるのでオイルビンによる抑制すら私には必要ないように思えます

**Comment by misosoup8374** [comment]
オイルビンを無くすと「重ね塗り強くね？」状態に陥ると考えています
そもそもこのオイルビン事態が初期の頃の重ね塗りのデメリットとして設定していたため現段階の案となるとオイルビンのデメリットが大きくなりすぎてしまったと考えています
オイルビンまで消してしまったらTORのアーソニストの上位互換であり流石に個性を潰していると思っています
なのでオイルビンはこのまま重ね塗りの強化でバランスを取りにいくという方法で活かしてあげたいです
付けるメリット案
・範囲内の即時塗り付け（最初の重ね塗り案の4行目）
・オイルビンの消費本数を1本へ
・会議後と他人への塗り付け後で重ね塗り状態の解除

**Comment by yukieiji** [comment]
> オイルビンを無くすと「重ね塗り強くね？」状態に陥ると考えています
そもそもこのオイルビン事態が初期の頃の重ね塗りのデメリットとして設定していたため現段階の案となるとオイルビンのデメリットが大きくなりすぎてしまったと考えています

クールタイムが2重になるので「重ね塗り」が強くね？ってなることはないはずでしょう、デフォルト設定だとある人に通常塗り30秒で重ね塗りは60秒必要になります、そうなるとかなりのジレンマが生まれると思っています

> オイルビンまで消してしまったらTORのアーソニストの上位互換であり流石に個性を潰していると思っています
なのでオイルビンはこのまま重ね塗りの強化でバランスを取りにいくという方法で活かしてあげたいです

要素が追加されている時点でTORのアーソニストとは別のものであると思っています
上の方にもあるのですが"TORのアーソニスト"がアーソニストらしいのか、提案されているものが真の"アーソニスト"とするのかによって上位互換であるのかアーソニストらしいのかってのは変わってくるはずです

> ・範囲内の即時塗り付け（最初の重ね塗り案の4行目）

この強化が入ると普通塗りのメリットが消えてる気がします

> ・オイルビンの消費本数を1本へ

個人的にはオイルビンが1本だったら何故あるのかってなる気がします

> ・会議後と他人への塗り付け後で重ね塗り状態の解除

逆に重ね塗りのメリットが消えてる気がします

**Comment by misosoup8374** [comment]
塗りクールダウンが30秒はちょっと想定してませんでした
私は塗りクールタイムは20秒
オイルビン作成のクールタイムは10秒をデフォルト値とする予定ではありました
この2つのクールタイムの関係を調整できれば上手くオイルビンを活用できると思います
オイルビンの必要性に関してはアーソニストは塗れていない人を見つけるまでのロスをオイルビンの作成の時間に割り当てて
その作った時間で重ね塗りを実行するという2パターンを想定しておりました

**Comment by yukieiji** [comment]
> 塗りクールダウンが30秒はちょっと想定してませんでした
私は塗りクールタイムは20秒
オイルビン作成のクールタイムは10秒をデフォルト値とする予定ではありました

ボタンのデフォルト値は基本的に30秒です

> オイルビン作成のクールタイムは10秒をデフォルト値とする予定ではありました
この2つのクールタイムの関係を調整できれば上手くオイルビンを活用できると思います

オイルビンの活用と言うかオイルビンで縛る必要が無いって思います

**Comment by misosoup8374** [comment]
重ね塗りに対しても縛る必要性がないのであればオイルビンのシステムは諦めます
これ以外に疑問点や問題点はあるでしょうか？

**Comment by yukieiji** [comment]
> 重ね塗りに対しても縛る必要性がないのであればオイルビンのシステムは諦めます
これ以外に疑問点や問題点はあるでしょうか？

重ね塗りと通常塗りそれぞれかなり仕様が変わってるので一度チケット本体でもいいですし、返信でもいいので再度内容を記載してもらってよろしいでしょうか

**Comment by misosoup8374** [comment]
了解しました

ニュートラル　アーソニスト（燃やせ）

役職の色
赤橙

役職の説明
生存者全員にオイルを塗り付けることが目的の第三陣営
キルやサボタージュ、ベントは使用できない
勝利条件
生存者全員にオイルを塗る

役職の能力

塗り付け
塗り付けボタンを押し塗り付け範囲内にいるプレイヤーにオイルを塗り付けます
アーソニスト視点でオイルを塗りつけたプレイヤーの名前はオレンジ色に変化します
塗り付けは会議後も引き継ぎます
塗り付けにかかる時間は設定で変更可能です

重ね塗り
既に塗り付けが行われているプレイヤーに対してもう1度塗り付けを行うことで発生します
重ね塗りが行われたプレイヤーは指定された範囲内に塗られていないプレイヤーが一定時間入った時
塗り付けを行います
他のプレイヤーに塗り終えるか一定時間がたつか会議後には通常の塗り状態に戻ります
重ね塗りの効果が切れる時間は設定で変更可能です

他陣営への影響
クルー陣営　他プレイヤーの行動に注目しなければならなくなり集団行動を避けるような行動を行わなければならなくなる
インポスター陣営　キルクールタイムが終わっていない時はなるべく誰にも近づかないように行動しないといけなくなる

**Comment by yukieiji** [comment]
概ね問題はなさそうです
問題があるとするならこの役職の名前が「アーソニスト」(放火魔(火を使う要素一切なし、TORもそうですけど))で良いのかどうかでしょうか

**Comment by misosoup8374** [comment]
アーソニスト勝利時にこのようなテキストをいれればいいと思います
「アーソニストが全てを燃やし尽くした」
オイル塗り終わった後に発火したという設定で

**Comment by yukieiji** [comment]
> アーソニスト勝利時にこのようなテキストをいれればいいと思います
「アーソニストが全てを燃やし尽くした」
オイル塗り終わった後に発火したという設定でお願いします

いや色々と設定的にも無理矢理(なんで重ね塗りをすると他の人に伝播するんだとか)がすぎるから設定とか能力とかにもあった役職名にするのはどうなのかなって思いました(見栄えとかRPとかもやりやすくはなりますしね)

役職名例 : アンブレイヤー(Umbrer, バイオのアンブレアをもじる)
- 能力名：ウイルス注入とウイルス進化

**Comment by misosoup8374** [comment]
私にネーミングセンスはないので例の役職名でお願いします

**Comment by yukieiji** [comment]
仮優先度を設定します(実装バージョンは未定です)

**Comment by yukieiji** [comment]
チケットの内容も更新しました

**Comment by yukieiji** [comment]
色とアイコンが決まっていませんが開発版に入ったため優先度とタグを更新しました

**Comment by yukieiji** [comment]
実装完了のためクローズ
