### ISSUE TITLE
[ニュートラル] : 未定（TORのチェインシフターを調整したもの)

### ISSUE THREAD

**Issue by appleaoi** [yukieiji/ExtremeRoles#142]
### 役職名 / Role Name
「未定」
　TORのチェインシフターを調整した役職を作りたいが、元になるシフターが無いため名前を未定にしています
### 役職の色 / Role color
灰色
### 役職の説明 / Role description
TORのチェインシフターを自分なりに調整したもの
カオスな展開になりやすいと思うので、そういった展開が好きな村用の役職の予定

「シフト」ボタン（仮）を使い、他のプレイヤーと役職などを入れ替える。

#### 勝利条件
なし
（なので、早めに交換する相手を見つけ、交換する必要がある）

### 役職の能力 / Role ability

他のプレイヤーとすれ違い時に「シフト」ボタン（仮）を使用することができる。（1度だけ）
会議後、対象相手が生きていれば、役職などを入れ替える。
（対象相手の陣営によって結果が違う）

1.クルー陣営の場合：タスク状況、能力の使用状況を自身が引き継ぎ、相手をこの役職にする
2.インポスター、マーリンの場合：会議・通報と同時に自爆する
3.ニュートラル陣営の場合：能力の使用状況を自身が引き継ぎ、相手をこの役職にする

会議後、ボタンが復活する。
（下で説明するが対象が死んでいた場合、シフトされないため）

#### 詳細説明
1.シフトした相手が死んでいた場合は、シフトしない
　⇒押し付けた相手が死んでしまい、負け確にならないようにしたい
　　死んだ人に押し付けたから、COして大丈夫というのを防ぎたい
2.シフトした直後の会議でシフトした相手が吊られた場合は、シフトしない
　⇒Aさんにシフトしたので、吊ってくださいはできない
　　ジェスターの勝利を邪魔しないため
3.インポスター陣営がばれないように、インポスター及びマーリンにはシフトできない
　⇒推理せずにシフトできないようにするための意図もある
4.自身が死んでも、「シフト」ボタンを押していればシフトの判定は行われる
5.ヤンデレの「片思いの人」と「邪魔者」は変わらない
　⇒ヤンデレ側にシフトされたことがわからないようにするため
　
### 他陣営への影響 / Effect on other teams
クルー陣営の場合、うかつに役職COし辛くなる
インポスター陣営の場合、タイムマスターなど避けたい役職が他の人になっている可能性がある

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> カオスな展開になりやすいと思うので、そういった展開が好きな村用の役職の予定

今はそういった役職を作りたいとは思ってない(需要もニッチすぎると思ってます)のでもし実装するとなっても優先度は低くなりますがよろしいでしょうか

> 1.クルー陣営の場合：タスク状況、能力の使用状況を自身が引き継ぎ、相手をこの役職にする
3.ニュートラル陣営の場合：能力の使用状況を自身が引き継ぎ、相手をこの役職にする

以前も似たような役職を提案されたときにも言いましたが能力の使用状況は各個人に保存されてないので引き継ぐことは不可能です

> 2.シフトした直後の会議で吊られた場合は、シフトしない
　⇒Aさんにシフトしたので、吊ってくださいはできない
　　ジェスターの勝利を邪魔しないため

これ誰が吊られた場合ですか

> 5.ヤンデレの「片思いの人」と「邪魔者」は変わらない
　⇒ヤンデレ側にシフトされたことがわからないようにするため

ヤンデレの邪魔者も上の能力と同じになってるので不可能です

> クルー陣営の場合、うかつに役職COし辛くなる

逆にCOしやすくなるのではないのでしょうか
AさんがCOしてAさんとシフトしてBという役職でしただから各白です！！で終わる気がします(この役職がCOの裏付けをしているようなものだと思ってます)

チェインシフターと違ってインポスターを引く必要性がなくなってるが上にインポスターの味方をする必要がなくなってるのが一番の問題な気がします(クルーに味方してれば安全という)

**Comment by appleaoi** [comment]
お疲れ様です。返答ありがとうございます。
>今はそういった役職を作りたいとは思ってない(需要もニッチすぎると思ってます)のでもし実装するとなっても優先度は低くなりますがよろしいでしょうか。

それで構いません。以前、ルナハ村（もう活動しない？）でチェインシフターがよく使われてたときいた（勘違いかもしれませんが）ので、実装できればニッチな需要にも答えられるのではと思っての提案です。
ですので、今後、検討及びこれらの回答への返信も優先度最低で構いません。

>能力の使用状況は各個人に保存されてないので引き継ぐことは不可能です

では、実装する際は能力使用状況は、試合開始状態になるでお願いします。

>>2.シフトした直後の会議で吊られた場合は、シフトしない
>>　⇒Aさんにシフトしたので、吊ってくださいはできない
>>　　ジェスターの勝利を邪魔しないため

>これ誰が吊られた場合ですか

わかりにくくて、すいません。
　シフトした直後の会議で「シフトした相手が」吊られた場合は、シフトしない
です。上の説明文も直しておきます。


>>5.ヤンデレの「片思いの人」と「邪魔者」は変わらない
>>　⇒ヤンデレ側にシフトされたことがわからないようにするため

>ヤンデレの邪魔者も上の能力と同じになってるので不可能です

了解しました。ヤンデレの人も邪魔者が変わったかまでは、そこまで把握しないと思うので、
たぶん大丈夫だと思います。

>逆にCOしやすくなるのではないのでしょうか
>AさんがCOしてAさんとシフトしてBという役職でしただから各白です！！で終わる気がします(こ>の役職がCOの裏付けをしているようなものだと思ってます)

一応自分が考えているのは、この役職はそう簡単に幽霊側に行かないため
（詳細説明1・2・4で説明した内容）、役職coすると常にこの役職を押し付けられる危険があるため、簡単には役職coできないと考えました。

例：Aさんが役職coして、Zさんがシフトをして、「Aさんは確白です」と宣言する
⇒今後、この「未定」役職になった人は、AさんとZさんにほぼ安全にシフトできる。
⇒常にAさんとZさんは負けの可能性がある。

以上です。上にも書きましたが、返信優先度最低で構いません。
よろしくお願いします。

**Comment by yukieiji** [comment]
> では、実装する際は能力使用状況は、試合開始状態になるでお願いします。

これちょっと思ったんですけどSKとかどうすれば良いんですかね
ボタンの使用回数はどう考えてもシンクロできないですし、多分SKはジャッカル昇格しますし

> 了解しました。ヤンデレの人も邪魔者が変わったかまでは、そこまで把握しないと思うので、

TORにヤンデレはいません

> （詳細説明1・2・4で説明した内容）、役職coすると常にこの役職を押し付けられる危険があるため、簡単には役職coできないと考えました。

押し付けられたとしても押し付け返せばいいので特に困らないのでは

> 常にAさんとZさんは負けの可能性がある。

やっぱりこれとインポスターの味方をしなくて良いってのが一番の問題な気がします
誰が貧乏くじを引くのか(押し付け合うってのもある)って言うのとインポスターの敵で有り続ければいいってのは問題な気がします

**Comment by appleaoi** [comment]
お疲れ様です。素早い返答ありがとうございます。
なかなか自分の伝えたい文章が作れず、返信が遅くなってしまいました。
大変申し訳ありません。

>これちょっと思ったんですけどSKとかどうすれば良いんですかね
ボタンの使用回数はどう考えてもシンクロできないですし、多分SKはジャッカル昇格しますし

ジャッカルが無限に出てきて、カオスでいいかなと思っていました。
（以前、サイドキック二人がお互いわかってなくて、混乱が起きたりと面白かったので）
その結果バグが起きやすくなるなど別の不具合がおきそうでしたら、
「能力の回数は0の状態でシフトする」
でお願いします。

>>>>5.ヤンデレの「片思いの人」と「邪魔者」は変わらない
         　⇒ヤンデレ側にシフトされたことがわからないようにするため

>>>ヤンデレの邪魔者も上の能力と同じになってるので不可能です

>>了解しました。ヤンデレの人も邪魔者が変わったかまでは、そこまで把握しないと思うので、たぶん大丈夫だと思います。

>TORにヤンデレはいません

すいません。自分の読解力が無いせいで、なぜ、この流れでTORの話になったのか、わかりませんでした。
申し訳ないのですが、詳しく説明してもらえないでしょうか？

>押し付けられたとしても押し付け返せばいいので特に困らないのでは

確認なのですが、yukieijiさんの考えとしては「未定」役職を実装すると、次のような試合展開になると予想しているであっていますでしょうか？
（少々読みづらいかもしれませんがお許しください）

-----------------------
1.Aさんがタイムマスター、Zさんが「未定」役職として試合が始まったとする
2.キルが起きて、会議にてAさんとPさんが容疑者候補になる

yukieijiさんの回答1回目の
>逆にCOしやすくなるのではないのでしょうか
>AさんがCOしてAさんとシフトしてBという役職でしただから各白です！！で終わる気がします

より
3.Aさんが「私はタイムマスターです」とCOして、Pさんが吊られる。
4.ZさんがAさんにシフトして、次の次の会議にてZさんが「Aさんにシフトでき、タイムマスターだったのでAさんは確白です」とCOする

yukieijiさんの回答2回目の

>押し付けられたとしても押し付け返せばいいので特に困らないのでは


より
5.AさんとZさんを中心に「未定」役職の押し付け合いが始まる

--------------------------

自分の考えとしては、
3.にて、5.の状態を避けるためにCOせず、ローラーを希望するかなと思っていました。
4.にて、すでにAさんは「未定」役職になっていて、ZさんがAさんの役職が正しいとCOするメリットは無いかなと思っていました。
ただ、自分は動画視聴勢で実際にプレイしたことがないため、yukieijiさんのような考えのかたのほうが多いのかもしれません。

>やっぱりこれとインポスターの味方をしなくて良いってのが一番の問題な気がします
誰が貧乏くじを引くのか(押し付け合うってのもある)って言うのとインポスターの敵で有り続ければいいってのは問題な気がします

#### ・問題：誰が貧乏くじを引くのか(押し付け合うってのもある)
相手の役職の証明が出来てしまう以上、必ず負けるというデメリットしかないかなと思っていました。
現状、これ以外のアイデアが無いため、今後、実装を検討するときに別のアイデアが欲しいとの事でしたら、少し考える時間をください。

#### ・問題：インポスターの敵で有り続ければいい
自分の考えとしては、役職COを誰もしなければ、シフトする相手を選ぶ方法が白ポイントが高い人や議論姿勢が白い人から選ぶと思いました。
（一度シフトできれば、今後、相手が生きている間は同じ人にシフトするだけになりますが）
なので、この役職をシフトされないようにするためには、あまり白ポイントを稼がないように行動するのかなと思っていました。
（常にインポスターの敵ではありますが、他人の白を出しつつ自分の白は出さないような行動をとるイメージ）

以上です。前回同様、返信優先度低くて構わないです。
よろしくお願いします。

**Comment by yukieiji** [comment]
> ジャッカルが無限に出てきて、カオスでいいかなと思っていました。
（以前、サイドキック二人がお互いわかってなくて、混乱が起きたりと面白かったので）

サイドキック同士が理解できない問題は今後の機能拡張で解決する予定です
あと処理的にサイドキックが無限にできるってことはないはずです、ジャッカルを置き換えるときにサイドキックがジャッカルに昇格するという処理が入ります

> その結果バグが起きやすくなるなど別の不具合がおきそうでしたら、
「能力の回数は0の状態でシフトする」
でお願いします。

無限サイドキック程度で不具合が発生することは無いはずです
もしサイドキックの能力を0にするのであればすべての能力の使用を0回にしたほうがコード的にも不具合発生率的にも低いと思われます

> すいません。自分の読解力が無いせいで、なぜ、この流れでTORの話になったのか、わかりませんでした。
申し訳ないのですが、詳しく説明してもらえないでしょうか？

「ヤンデレの人も邪魔者が変わった」ってのがよくわからなかったので、TORにヤンデレがいてチェインシフターでそのまま交換できたって考えたのかなって思いました
「ヤンデレの人も邪魔者が変わった」ってのはどういうことですか？

> 確認なのですが、yukieijiさんの考えとしては「未定」役職を実装すると、次のような試合展開になると予想しているであっていますでしょうか？

これは下の返信の答えでもあるんですけど、この役職をクルーがローラーという手段を使ってでも落とそうとするのか疑問です。各個人的には落としたいってのはあるとは思いますがクルー全体の総意として落とそうっていう結論には至らないと思ってます

> 相手の役職の証明が出来てしまう以上、必ず負けるというデメリットしかないかなと思っていました。
現状、これ以外のアイデアが無いため、今後、詳細を検討するときに別のアイデアが欲しいとの事でしたら、少し考える時間をください。

チェインシフターにもあるんですけど最後の最後にシフトしてボタン押されて会議で人外が吊られれば安全に勝てるってのもあります
あとは勝利がないから、とりあえずタスクフェーズで白や擦りつけた人になすりつけ返すっていう戦略が基本になってワンパターンになると思います。能力のボタンを使わないって戦略性が全然ないと思います

> 自分の考えとしては、役職COを誰もしなければ、シフトする相手を選ぶ方法が白ポイントが高い人や議論姿勢が白い人から選ぶと思いました。
（一度シフトできれば、今後、相手が生きている間は同じ人にシフトするだけになりますが）
なので、この役職をシフトされないようにするためには、あまり白ポイントを稼がないように行動するのかなと思っていました。（常にインポスターの敵ではありますが、他人の白を出しつつ自分の白は出さないような行動をとるイメージ）

AmongUs等の非対称型のゲームだと人が多い陣営が圧倒的に有利です、なので基本的にクルーの味方をしていけば黒とか第三陣営は浮いていくと思います。なので、黒とか第三陣営を落として行って黒が最後吊られるギリギリ白い人に交換すればキルされる確率も低く安全に勝てる
追加でこの役職COしたとしてもクルー総意的に落とすメリットがほぼ無い(個人的には落としときたいけど、なすりつけ返せば問題がない => シェリフがいたらそれで落とすレベル？)

- クルー的に落とさないメリット
  - 肉壁が増える
  - 役職が入れ替わっても9割がた白のみ
    - 勝手に自分たちの役職を白証明してくれる
    - 第三陣営に使うメリットは一切ない(泥舟に乗る可能性もあるので)ですし
  - 黒に使ったら勝手に死んでくれるから釣り縄を使う必要性がない
- クルー的に落とさないデメリット
  - 推理が少しグチャる(？、白証明してくれるからグチャる要素がほぼ0では？) 
  - 勝手に死んだ部分でよくわからない

**Comment by appleaoi** [comment]
おつかれさまです。
自分のわかりにくい文章に、親切にお答えいただき、ありがとうございます。

そして、申し訳ないのですが、このIssuesをクローズさせてください。
理由としましては、yukieijiさんの意見をきいていく内に、この役職に自分が感じていた魅力がだんだんわからなくなってしまい、これ以上回答することがつらくなってきてしまいました。

このような形になってしまい、申し訳ありませんでした。

一応、回答して頂いたので、記録として自分からの回答を残しておきます。
ですので、読まなくても大丈夫です。
今後、似たような役職を提案する方がいたら、その方のアイデアの糧になれば幸いです。

------------

>処理的にサイドキックが無限にできるってことはないはずです、ジャッカルを置き換えるときにサイドキックがジャッカルに昇格するという処理が入ります

無限という自分の書き方が不適切でした。ジャッカル自体がシフトされれば、サイドキックボタンが復活してサイドキックを量産できるかなと思っての回答でした。

>「ヤンデレの人も邪魔者が変わった」ってのはどういうことですか？

邪魔者になった人にシフトをすると以下のようになるかなと思いました。
・邪魔者の矢印がついた人がシフトされて、会議後に矢印が消える。
・矢印がなかった人に、会議後に矢印がつく。

ただ、ヤンデレの役職になった人の配信を見ていると、誰が邪魔者になったかをそこまで気にしているようでは無かったので影響は少ないかなと思った　という回答でした。
わかりにくくてすいませんでした。

>この役職をクルーがローラーという手段を使ってでも落とそうとするのか疑問です。

これも自分の文章が悪くて伝わってないみたいです。
自分の前回の回答の
>3.にて、5.の状態を避けるためにCOせず、ローラーを希望するかなと思っていました。

というのは、「ローラーをキル陣営を落とすために使う」という意味で使っていて、この「未定」役職はつりでは、ほぼほぼ落とせないつもりでした。
・「未定」役職の人をつっても、事前に〇〇さんにシフトしていれば、〇〇さんに「未定」役職が移る
・シフトボタンを押した相手をつると、シフト自体が起きないので幽霊側にはいかない

>最後の最後にシフトしてボタン押されて会議で人外が吊られれば安全に勝てるってのもあります

すいません。自分が能力詳細に記入するのを忘れていたのですが、

・会議で最後の人外を吊った際はシフトを行わない

というものでした。
なので、最後の人外が吊られそうなときは、この役職の人は議論を伸ばすや混乱させるなどの行動をとる必要があるつもりでした。
それでも、最後の一個前の会議でシフトすれば変わらないので、あまり関係ないかもしれません。

>とりあえずタスクフェーズで白や擦りつけた人になすりつけ返すっていう戦略が基本になってワンパターンになると思います。能力のボタンを使わないって戦略性が全然ないと思います

これは、おっしゃる通りです。
一応、脳死でボタンを押せばいいにならないように、インポスターに使うと自爆するというデメリットをつけましたが、弱かったです。

>黒とか第三陣営を落として行って黒が最後吊られるギリギリ白い人に交換すればキルされる確率も低く安全に勝てる

長時間、集団で行動するなどして、他人からの白ポイントが高すぎるとキル陣営からは、罪をなすり付けにくい相手となり優先的にキル対象になると思います。なので、キルされる確率は低くなく、また、キルされる優先度が高い状態でこの「未定」役職になったまま、試合終盤までシフトしないでいるのかなと思っていました。

>この役職COしたとしてもクルー総意的に落とすメリットがほぼ無い(個人的には落としときたいけど、なすりつけ返せば問題がない => シェリフがいたらそれで落とすレベル？)

この役職をCOした人を会議で吊っても、事前にシフトしていたら、シフトされた人の役職が幽霊側に行き、この「未定」役職は生き残るので、そもそも落とせないつもりでした。
（落とすメリットがないではなく、落としたいけど落とせない役職）
シェリフで撃とうとしても、シェリフの人にシフトされるなどして簡単には落ちないつもりでした。
（クルー陣営は、押し付けられるので近づきたがらないと思っていました）

>肉壁が増える

「未定」役職がキルされても、事前にシフトがされていれば、役職交換が行われるため、結果的にクルー陣営が1減っているので、肉壁が増えることにはならないと思っていました。
（シフトした相手が第三陣営でしたら、肉壁になりますが。）

>第三陣営に使うメリットは一切ない

自分としてはcoがし辛くなるとおもったので、シフトしたくないが、誰がどの役職かわからないので第三陣営にも使ってしまう役職のつもりでした。
また、COし辛くなる要素として、潜伏している第三陣営に使ってしまう可能性があるので、シフトしたことをCOできないつもりでした。
（〇〇さんにシフトしましたと宣言すると、次の会議でジャッカルなどをとられたので、さっき宣言した人がジャッカルですと言われてしまう）

>勝手に自分たちの役職を白証明してくれる
>推理が少しグチャる(？、白証明してくれるからグチャる要素がほぼ0では？)

自分としては「Aさんは当時Bという役職でした」と白証明するメリットがないと思ったので、白証明は基本的にしてくれないと思っていました。（押し付け合いが発生する。かつ、会議後に別の人にシフトして、ジャッカルやアリスなどキル能力もちになっている可能性もあるので。）


「つもりでした」が多い酷い文章ですが、記録として残しておきました。
自分の見積もりが甘いことが再確認できました。

以上です。ありがとうございました。
