### ISSUE TITLE
[第三陣営/Neutral] : ファントム/Phantom (敵をこちら側に誘おう)

### ISSUE THREAD

**Issue by a-nemu** [yukieiji/ExtremeRoles#145]
### 役職名 / Role Name

ファントム

### 役職の色 / Role color

暗い水色

### 役職の説明 / Role description

プレイヤーを乗っ取り、仲間を増やせる。クルーと同数がファントムになったら勝利する役職。

### 役職の能力 / Role ability

・能力ボタン「乗っ取る」
　・ゲーム中に任意の生存者を同陣営のファントムにできる。
　　・これはクールタイムはあるが、生存中なら何度でも使用可能。
　　・プレイヤーが乗っ取られた時、その場に通報できない自身の死体が発生する(フェイカーが作った偽死体の感じ)。
　・コスト…クールタイム、リスク…人が多い場所で発動すると誰が乗っ取られたかバレる
・キル、サボタージュはできないが、ベントを使える。
・生存中は議論に参加し投票も可能だが、投票結果にファントムの票が反映されることはない。
・クルー陣営からは、姿が見えない。インポスターや第三陣営からは見える。
　・ただし、カメラ越しなら見られる。アドミンとドアログでも正常に位置が表示され、バイタルも生存中は緑色(OK)。
・吊られたり、キルされたら死亡する。キルされた場合死体は残らず、バイタルの表示も灰色(D/C)となる。

### 他陣営への影響 / Effect on other teams

(クルー視点)ファントムを増やさないようにボタン意識が高くなる。詰めるために、誰が誰を見たかを話し合う。
(インポスター視点)ファントムが誰かわからない且つファントムはインポスターにしか見えないので、誰が見えたかという情報を選別して出す必要がある。

### 陣営 / Team

 -->
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
この役職の問題として二次関数的に陣営が増えていくファントムをクルーやインポスターや他陣営が処理できない気がします

> ・生存中は議論に参加し投票も可能だが、投票結果にファントムの票が反映されることはない。

これ、最終的に人外を吊り切ることができなくなるのではないでしょうか

> ただし、カメラ越しなら見られる。

これは多分無理ですね、透明なら透明のままです
