### ISSUE TITLE
[ホスト専用 / Host only] : シオン/Xion (TORのGMをバックポート)

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#147]
### 役職名 / Role Name

シオン/Xion

### 役職の色 / Role color

未定

### 役職の説明 / Role description

TORのGMをバックポートして色々と機能を追加
- タスクフェーズ時
  - プレイヤーキル / 蘇生のボタン
  - 拡大 / 縮小
  - 移動速度 Up / Down
- 会議中
  - 投票可 / 特殊投票化
- アサイン時、ホストに幽霊としてアサインされる
- ホストの暴走防止用にプレイヤーの2/3が特殊チャットコマンドを使用することで試合を強制的に終わらせることが出来るようにする(こいつが有効時のみ)
- GUI非表示も出来る

### 役職の能力 / Role ability
- プレイヤーキル / 蘇生
  - 左下に全員のプレイヤーアイコン
- 拡大 / 縮小
  - カメラの拡大と縮小ができる
- 移動速度Up / Down
  - 移動速度を変えれる 

### 他陣営への影響 / Effect on other teams

ホスト用のお遊び役職なんでなし

### 陣営 / Team

どの陣営にも属さない

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
欲しい能力があれば記載してください

**Comment by unhappyset** [comment]
サボタージュを発動したり直したりできる能力はどうでしょう

**Comment by yukieiji** [comment]
素材作成等に使えるように、ローカルゲーム専用モードとして以下の機能を追加実装
- ダミープレイヤーを強制召喚してゲームを開始できるようにする
  - ホスト以外にプレイヤーが存在しないことが前提
- ゲーム中に任意の役職に変更可能(コマンド)
- 死体錬成可能
