### ISSUE TITLE
SChinese Translations Update

### ISSUE THREAD

**Issue by fivefirex** [yukieiji/ExtremeRoles#148]
## Feature details

Hi! Such a long time no see!
I let ponyzerteal(123) help me with the lost translations and merge them with your repository before because of my studies.
ponyzerteal(123) is belong to 四个憨批汉化组, and I(FiveFireX) am belong to 风尘汉化组. The 2 groups are friends, click [here](https://github.com/4H-Developers) to see our GitHub org and click [here](https://amonguscn.club/) to see our website.
And now I am not as busy as before. So I finished the newest ExRoles translations.
Thanks!

*There's another question I want to ask: It's really inconvenient that I have to make issues or pull requests every time I translate, so I always have to follow up and you always have to respond to me and release new versions. So, maybe you can contact me via Discord or E-mail, etc. When there is a new version to be released, I will submit the new string, and you will not have to repeat the releases.*

## Files:
[ExtremeRolesTransData.xlsx](https://github.com/yukieiji/ExtremeRoles/files/9228830/ExtremeRolesTransData.xlsx)
[ExtremeSkinsTransData.xlsx](https://github.com/yukieiji/ExtremeRoles/files/9228831/ExtremeSkinsTransData.xlsx)

**Comment by yukieiji** [comment]
Thank you! I will release this in the next update!
I checked the translation and found that "SurvivorNoWinSurvivorAssignGhostRole" was not translated.

You can contact Discord from the button that appears on the lower left of the title screen after v3.2.0.0.

**Comment by fivefirex** [comment]
I see it! Just translate it to:
当求存者无法获胜时分配一个幽灵角色

**Comment by yukieiji** [comment]
Thank you, I will make a release tomorrow or the next day or two, including bug fixes.

**Comment by yukieiji** [comment]
I'll leave it open for now until release.

**Comment by yukieiji** [comment]
implemented in v3.2.0.4
