### ISSUE TITLE
[第三陣営＆クルー] : 未定 (第三陣営版アサマリ)

### ISSUE THREAD

**Issue by mitsuki17291** [yukieiji/ExtremeRoles#149]
### 役職の説明 / 
ニュートラルアサシン:インポスターでなく独立したキル可能な第三陣営であり、クルーと同数になれば勝利できることとアサシン会議でニュートラルマーリンを指定すれば単独勝利すること以外はアサシンと同一
ニュートラルマーリン:ニュートラルアサシンが見えることを除けばマーリンと同一

### 役職の能力 / Role ability

ニュートラルアサシン:キルボタン、ベント、吊られた際に発動するアサシン会議発生能力(ここでニュートラルマーリンを指定することが出来れば勝利できる)
ニュートラルマーリン:ボタン等はないがパッシブスキルとしてニュートラルアサシンとインポスターが見える(インポスターとニュートラルアサシンを区別できるようにするか、キル可能第三陣営が見えるかどうかなど詳細は未定)

### 他陣営への影響 / Effect on other teams
インポスター(ニュートラルマーリンがキル可能第三陣営も見える設定の場合キル可能第三陣営も)はニュートラルアサシンが吊られる前にニュートラルマーリンを殺せないと詰むのでニュートラルアサシンにバレないようにニュートラルマーリンを見つけて殺す必要があります。

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
インポスター目線、このニュートラルアサシンをどうやって処理すればいいのか分からないような・・・・

**Comment by mitsuki17291** [comment]
あー確かに、マーリン側だけ見ててそっちのこと全然考えてませんでした。現状だと吊り落とすしかないけど

**Comment by mitsuki17291** [comment]
あっ間違えてCloseしちゃいました　現状だと吊り落とすしかないけど「ニュートラルマーリンまだ殺せてないからニュートラルアサシン生かさなきゃ」みたいな駆け引きが生まれるんで強い村ならそれはそれで面白いかもしれません

**Comment by yukieiji** [comment]
> あっ間違えてCloseしちゃいました　現状だと吊り落とすしかないけど「ニュートラルマーリンまだ殺せてないからニュートラルアサシン生かさなきゃ」みたいな駆け引きが生まれるんで強い村ならそれはそれで面白いかもしれません

駆け引きが生まれてもそれをインポスター側が処理できないと何も出来ない気がします
何も出来ないとクルーのタスクは進むけど落とせない => 落とせないから負けるって事になりそう
