### ISSUE TITLE
サイレントキラー(密殺者)：インポスター役職

### ISSUE THREAD

**Issue by issyoukimizu** [yukieiji/ExtremeRoles#15]
### 役職名 / Role Name
サイレントキラー
### 役職の色 / Role color
インポスターと同じ
### 役職の説明 / Role description
「目立つことなく堂々と殺せ」
キルモーションなしで相手をキルできる役職。
### 役職の能力 /  Role ability
通常のキルボタンとは別に、「密殺」という特殊なキルボタンがあるインポスター役職。
「密殺」をするとキルモーションを伴わずに相手を殺害できる。「密殺」でキルできる距離は通常のキル可能範囲より少し広い。
「密殺」ボタンはクール時間を通常のキルボタンと共用しており、かつ「密殺」後は通常のキルボタン含めてキルクールに最大20秒のペナルティが付く。ペナルティ時間は設定で変更可能。

モチーフは動画投稿者のジローさん(HITMAN実況をしているから)
「絶対に許さないぞあの天然マッドメイト！」

### 他陣営への影響 / Effect on other teams
単に公衆の面前で「密殺」するだけでは、距離が近いサイレントキラーがすぐに疑われてしまう為、あまり意味はない。
しかし、多人数がごく狭い範囲に固まっている状況で「密殺」されると、サイレントキラーの仕業だとまでは分かっても、誰がそれなのかを特定するのが難しくなってしまう。
つまり、所謂「ごちゃキル」の状況で真価を発揮する役職であるといえる。
その為、この役職が混ざっている状況では、クルー側は多人数で固まっての行動がしにくくなる。(設計上はこっちがメインの目的)

### 陣営 / Team
- [ ] :クルー/Crewmate
- [X] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by issyoukimizu** [comment]
フェンサーから分離しました。
なにかご意見があればよろしくお願いします。

**Comment by yukieiji** [comment]
インポスターがキルされることは1回あるか無いかなのでそのキルを完全に無効化出来てしまうのはかなり強力だと私は思いますがどうでしょうか

> リボルターがいる盤面では反撃で殺されるリスクがあるので、シェリフとの撃ち合いがしにくくなる。

みんなが見ている場合での撃ち合いは逆にしやすくなると思います(キルが無効化されれば人外確定、キルされても人外確定になりますし)

**Comment by issyoukimizu** [comment]
まあ、元々フェンサーでしたからね……。
これに関しては難しそうなら別の役職に書き直そうと思います。もうフェンサーが実装されて、猫野さんモチーフの役職の実装という目的は達成しましたから。

**Comment by issyoukimizu** [comment]
別役職に変更しておきました。

**Comment by yukieiji** [comment]
別役職として書くなら新しいチケットでお願いしますこのチケットはクローズします。(履歴やコメントが残るので)
