### ISSUE TITLE
[インポスター/Impostor] : 愉快犯/未定 (注目を集めろ)

### ISSUE THREAD

**Issue by takuto1341** [yukieiji/ExtremeRoles#157]
### 役職名 / Role Name
愉快犯/未定
### 役職の色 / Role color
赤
### 役職の説明 / Role description
会議時に自分に投票が入ることでキルクールが減少する
### 役職の能力 / Role ability
会議時に浮いていたり怪しいが吊られるまでいかない位置にいるなどして吊りにまで持ってはいけないが票が入ることでキルクールが減少し、その後のキルがやりやすくなる。票の増加でTM貫通などをつけてもいいかも？

### 他陣営への影響 / Effect on other teams
クルー：票を入れることでこの人が怪しいと表明するなどのムーブがやりづらくなり、浮き吊りや、怪しい人が複数人いる場合のローラーが難しくなる

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
個人的に使える能力か疑問に思います
- 票を入れてこの人が怪しいってことをすることはあまり無いような気がします
  - キャプテンとかが入っていると尚更発生しにくいと思います
- 個人的に能力が使えるときは票が割れるときが大半になると思いますが、そういった状況になるためには他の人と同じくらいの黒点をキープしないといけない(それでも、ローラーになりそうなのでお土産キルができるかできないかだと思いますが)
- 自殺票を入れることで自分で能力を使うことができるがそれをするのはこの役職だけなのでやり過ぎるとバレる

**Comment by takuto1341** [comment]
能力を発動できる状況にもっていくメリットが少ないんですね、投票されることを何かメリットにできないかと思い提案しましたが難しそうです
