### ISSUE TITLE
[クルー、インポスター] : ネクロマンサー (死亡したプレイヤーを一時的、限定的にゲームに復帰させる)

### ISSUE THREAD

**Issue by majiponi** [yukieiji/ExtremeRoles#159]
### 役職名
ネクロマンサー

### 役職の色
~~死亡前と同じ~~
灰色(8/16：ご指摘を受け入れて変更)

### 役職の説明
死亡したプレイヤーを一時的、限定的にゲームに復帰させる。

### 役職の能力
ネクロマンサーは、ゲーム中に一度だけ、会議中に、既に死亡したプレイヤー1人を指定できる。そうした場合、次のいずれかの条件が満たされるまで、指定されたプレイヤーはゲームに復帰する。

条件1：ネクロマンサーの死亡
条件2：クルー陣営の場合、復帰したプレイヤーが死体を通報する。
条件3：インポスター陣営の場合、復帰したプレイヤーが誰かをキルする。

復帰したプレイヤーは、他プレイヤーからは死体が動いているように見える。(8/16：復活したプレイヤーの存在を認識できるようにしてある。会議で死亡を確認しているので、容易にゾンビだと理解できる。)
**復帰したプレイヤーは、壁を無視して移動できるが、死体なので、移動速度が、クルーの3分の2になる。** (8/16：ゾンビっぽさが足りなかったので追加。これがあることで、簡易ベイトなど、開発者が懸念する多くの問題は解決する。)
~~復帰したプレイヤーは、コックピット情報などには表示されない。~~ (8/16：無理らしいのと、特に意味があるわけではなかったので削除)
復帰したプレイヤーは、会議に参加できない。
**復活したプレイヤーの役職は、元がインポスター陣営以外の場合、イレイサーに消されたとき同様に消滅する。例えばシェリフやアーソニストは、死体として復活すると、以後、ただのクルーになる。また、幽霊役職も同時に消滅する。元がインポスター陣営の場合、役職のないインポスターになる。**
復帰したプレイヤーがクルー陣営の場合、タスクをするか、通報することしかできない。通報した場合、通報した瞬間に、通常のクルーの死亡者と同じ状態に戻る。
復帰したプレイヤーがインポスター陣営の場合、キルしかできない(サボタージュなどは使えない)。キルした場合、その場に死体として残り、次の会議まで一切動けなくなる。会議後は通常の死亡したインポスターと同じ状態に戻る。

### 他陣営への影響
~~なし~~
**死亡者の陣営が変化することがあるため、場合によってはサイドキックの裏切りなどが発生する。** (8/16：陣営変化がありうるようになったので追記)

### 陣営
- [x] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> クルー、インポスターのデフォルトと同じ

クルーの場合、死亡した人からの見栄えが悪くなりすぎるので別の色でお願いします

> ネクロマンサーは、ゲーム中に一度だけ、会議中に、既に死亡したプレイヤー1人を指定できる。そうした場合、次のいずれかの条件が満たされるまで、指定されたプレイヤーはゲームに復帰する。
条件1：ネクロマンサーの死亡
条件2：クルー陣営の場合、復帰したプレイヤーが死体を通報する。
条件3：インポスター陣営の場合、復帰したプレイヤーが誰かをキルする。

クルーの場合はキルした人に着いていって即通報で簡易外付けベイトとして使えて、インポスターの場合だと防ぐのが難しい不可視最強のキルができるのでかなり強力だと思いますがどうでしょうか

> 復帰したプレイヤーは、他プレイヤーからは死体が動いているように見える。が、通報はできない。

クルーが困惑するもとだと思いますがこれを付ける理由はありますでしょうか

> 復帰したプレイヤーは、コックピット情報などには表示されない。

恐らくこれは不可能な気がします

> 復帰したプレイヤーがクルー陣営の場合、タスクをするか、通報することしかできない。

キルした人について回って切った瞬間に通報できるので強すぎませんか

あと全体的な疑問としては幽霊役職はどうするのか、元役職はどうなるのか

**Comment by majiponi** [comment]
移動速度に関する内容を加えることで、多くの問題は解決しました。ご意見いただけますと幸いです。

**Comment by yukieiji** [comment]
> 8/16：復活したプレイヤーの存在を認識できるようにしてある。会議で死亡を確認しているので、容易にゾンビだと理解できる。

認識して理解できたとしても生存者側から復活した人に対してアクションを取るとか出来ないですし、見えてると人外の人を追いかけ回すだけで簡単に人外が釣れてしまうのではって今思いました

> 移動速度に関する内容を加えることで、多くの問題は解決しました。ご意見いただけますと幸いです。

これを入れると復活した人のタスクが非常にやりづらくなってゲームの速度を落とす事になりませんか
タスクがしにくいからベイト見たく使う or 待ち伏せキルって事になりそうな気もしなくはないです

もう一つ懸念事項があったのを今書いてて思い浮かびました
死ぬとすべての情報が開示される事が可能なExRにおいて死んで復活できるとかなり有利な情報を現世にもたらすことが出来るきがします、特に見えたりするとそれが出来ると思います
