### ISSUE TITLE
一部の誤字脱字

### ISSUE THREAD

**Issue by Niccori250k** [yukieiji/ExtremeRoles#16]
PRを行うので確認をお願いしたいです。
以下、より適切だと思われる表現を記載します。
(太字は変更箇所)

- "ghostsSee\*"について、「～**を**表示する」に変更
- "importError"/"exportError"について、2行目行頭の空白を削除
- "BodyGuardIntroDescription"について、""船員たちにシールド**を**張って""の「を」を追加
- "BodyGuardShortDescription"について、「身を張って」を「**体**を張って」に変更
- "BodyGuard\*"について、「貼る」「張る」等を「付与する」等に修正
- "TimeMasterFullDescription"について、一部不自然だった箇所を修正(詳細は以下)
- "BakaryFullDescription"について、「焼けてる」を「焼けて**い**る」に修正
- "BakaryFullDescription"について、パンの焼け具合の説明行頭を字下げし、箇条書きに変更
- "BomberFullDescription"について、"**「**「爆弾設置」後、爆発するまでの時間の最小\n時間」"の最初の'「'を追加
- "AssassinFullDescription"について、特殊会議の説明行頭を字下げし、箇条書きに変更
- "MeryFullDescription"の1行目について、"「陣」設置できるをインポスター"を"「陣」を設置できるインポスター"に修正
- 「サボタージ」をすべて「サボタージ**ュ**」に修正
- 一部行末のU+3002(。)の削除

"TimeMasterFullDescription"について、以下のように変更
> 能力「タイムシールド」が使えるクルー役職
> 能力「タイムシールド」の発動中に、キルボタンによるキルが
> 発生すると設定された時間の巻き戻りが発生する
> 時間の巻戻り中は「タイムマスター」本人は影響を受けない
> 更に、キルボタンによって「タイムマスター」本人をキルする
> ことも不可能
> 時間の巻き戻りはプレイヤーの移動だけ巻き戻る
> 巻き戻る時間は「「タイムシールド」によって巻き戻る時間」
> によって決定される。

**Comment by yukieiji** [comment]
翻訳をどんな感じで治したのか書いていただきたいです。Excelは確認できないので
あとビルドが通ることは確認してないということでよろしいですか

**Comment by Niccori250k** [comment]
より適切だと思われる表現を記載します。
(太字は変更箇所)

- "ghostsSee\*"について、「～**を**表示する」に変更
- "importError"/"exportError"について、2行目行頭の空白を削除
- "BodyGuardIntroDescription"について、""船員たちにシールド**を**張って""の「を」を追加
- "BodyGuardShortDescription"について、「身を張って」を「**体**を張って」に変更
- "BodyGuard\*"について、「貼」を「張」に修正
- "TimeMasterFullDescription"について、一部不自然だった箇所を修正(詳細は以下)
- "BakaryFullDescription"について、「焼けてる」を「焼けて**い**る」に修正
- "BomberFullDescription"について、"**「**「爆弾設置」後、爆発するまでの時間の最小\n時間」"の最初の'「'を追加
- "AssassinFullDescription"について、特殊会議の説明行の頭を全角空白からU+30FB(・)に変更
- 「サボタージ」をすべて「サボタージ**ュ**」に修正
- 一部行末のU+3002(。)の削除

"TimeMasterFullDescription"について
旧:
能力「タイムシールド」**が**発動中に、キルボタンによるキルが
発生する**の**と時間が巻き戻る。ただし、「タイムマスター」
本人は影響を受け**ない**、また、キルボタンに**とる**キルすること
新:
能力「タイムシールド」**の**発動中に、キルボタンによるキルが
発生すると時間が巻き戻る。ただし、「タイムマスター」
本人は影響を受け**ず**、また、キルボタンに**より**キルすること

**Comment by yukieiji** [comment]
マージされたためクローズします

**Comment by Niccori250k** [comment]
8729b9af234fabbdd8c1f4708a6dfa45cc1ec0eb で上書きされてしまったようですが、再度修正した方が良いでしょうか？
