### ISSUE TITLE
[インポスター陣営] : リザレクション (条件達成で一度だけ生き返る)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#161]
### 役職名 / Role Name
リザレクション

### 役職の色 / Role color
赤

### 役職の説明 / Role description
一定回数キルすることでインポスターから覚醒する
死亡後一定回数の会議経過時にインポスター陣営が全滅してなければ復活する

### 役職の能力 / Role ability

ラストウルフと同様、ゲーム開始時は通常のインポスターとしてアサインされる。
覚醒予定のインポスターが指定された回数キルするとリザレクションに覚醒する。

リザレクションが死亡した時、専用の幽霊役職になって復活待ち状態になる。この仕様は1度目の死亡時に死亡済みの役職を把握させないためのもの。
専用の幽霊役職はアクティブ能力を持たないが、指定された回数の会議が経過したときにインポスター陣営が全滅していない場合、生き返る。復活後は死亡直前のコンビネーション役職を保持しつつ通常のインポスターになる。

#### 固有のオプション
覚醒に必要なキル数
復活までの会議数

#### メリット
中盤以降にインポスター陣営の頭数を回復できる
もう一度吊るにしても吊り縄を減らせる

#### デメリット
最後の一人になるまで生き残ると能力が使えなくなる
味方が全滅したり覚醒前に死亡すると復活できない
生きている間は能力を持たないのと同じ

### 他陣営への影響 / Effect on other teams
黒陣営らしきプレイヤーを吊っても復活の危険性があるので安心できなくなり、怪しいプレイヤーを一気に吊りきるなりシェリフで撃つなりして決着を早めることが予想される。
またむやみに会議を開こうとするプレイヤーに対し、リザレクションの復活を待つインポスター陣営の容疑がかかる。

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
インポスターが殺されることってまず無いような気がします、それでこの役職の能力が使えるかどうか疑問に思えます
あとクルー側がこの役職を止める手段が少なすぎると思います、インポスターを吊らない止まらないのに会議を起こすと復活するってのは少し理不尽な気がします

> 復活後は死亡直前のコンビネーション役職を保持しつつ通常のインポスターになる。

これはどういうことですか？リザレクションはリザレクションでしょう？

**Comment by melonjagaimo** [comment]
「コンビ役職を保持して通常インポスターとして復活」はリザレクションが再度復活しないように、このような書き方をしたのです。もし復活後も復活したことを記憶できるならこの部分は無視して大丈夫です。

クルー陣営がこの役職を止める手段、ですか…。死因を判別する機能は以前難しいという話がありましたね。それが可能なら「追放された場合は復活までの会議数が増える、あるいは追放された場合は復活不可能」を提案したのですが…。
「クルー全体のタスク進捗が一定割合を超えた場合、復活を阻止できる」というのはどうでしょうか。

**Comment by melonjagaimo** [comment]
もう一つ、インポスター陣営が死ぬことが少ないから能力が腐る点ですね。
自分としてはその点そのものがデメリットのひとつだと考えております。最後の1人になると復活条件の関係で能力が使えなくなる点もわざとです。
だからこの役職になったプレイヤーに
「仲間が生き残ってくれることを信じてキルを重ねて適度に怪しまれて吊られ、生き返ることを祈る」か
「仲間が生き残れないかもしれないので能力が使えなくなってでも怪しまれにくい動きをする」かの2択を突きつけられるのです。

（いっそタスクで覚醒するクルー陣営にしようかとも考えましたが、死人に口があると強すぎますかね…？）

**Comment by yukieiji** [comment]
> 「コンビ役職を保持して通常インポスターとして復活」はリザレクションが再度復活しないように、このような書き方をしたのです。もし復活後も復活したことを記憶できるならこの部分は無視して大丈夫です。

復活したらただのインポスターになるってことでいいですかね

> クルー陣営がこの役職を止める手段、ですか…。死因を判別する機能は以前難しいという話がありましたね。それが可能なら「追放された場合は復活までの会議数が増える、あるいは追放された場合は復活不可能」を提案したのですが…。
「クルー全体のタスク進捗が一定割合を超えた場合、復活を阻止できる」というのはどうでしょうか。

初手でキルをいっぱいして死ねばそれで序盤で能力が使えますし終盤じゃないと止めれないってのはだめだと思ってます、いつでも止めれるような物ではないとだめだと思ってます

> 自分としてはその点そのものがデメリットのひとつだと考えております。最後の1人になると復活条件の関係で能力が使えなくなる点もわざとです。

デメリットというよりか能力が使いにくい役職ってなると思います
デメリットは自分のアクション要素でカバーもしくは選択できるようなものが一番重要だと思います

**Comment by melonjagaimo** [comment]
復活後は普通のインポスター、という解釈で問題ないです。

いつでも止められる要素と能力デメリットの自力解消、ですね。
いつでも復活を阻止できるようにするには…
「復活するには復活までの間、会議で誰も追放されないこと」を条件に追加するのはどうでしょうか。
追放の場合はローラーを完遂するだけで復活を阻止できますし、仮に初手であっても、リザレクションがキルされてかつ復活まで誰も吊られない状況はそうそう起きないと思われます。

デメリットの解消でのカバーや選択についてはこちらを思いつきました。
「覚醒後は命のストックを得、能力ボタンを発動することで1度だけ自分へのキルをその場で無効化するシールドを貼る」
です。こちらだと一部例外を除いて返り討ちにできる代わりに追放には無力になります。

**Comment by yukieiji** [comment]
> 「復活するには復活までの間、会議で誰も追放されないこと」を条件に追加するのはどうでしょうか。
追放の場合はローラーを完遂するだけで復活を阻止できますし、仮に初手であっても、リザレクションがキルされてかつ復活まで誰も吊られない状況はそうそう起きないと思われます。

結局それは会議が起きれば毎会議誰かを吊らなければならないってことになるのでボタンが押しにくくなるだけではないでしょうか

> デメリットの解消でのカバーや選択についてはこちらを思いつきました。
「覚醒後は命のストックを得、能力ボタンを発動することで1度だけ自分へのキルをその場で無効化するシールドを貼る」
です。こちらだと一部例外を除いて返り討ちにできる代わりに追放には無力になります。

復活しなくなるってことですかね？

**Comment by melonjagaimo** [comment]
・復活阻止の方はまた考えてみます。

・シールドを貼ると復活の権利を失いますね。追放に対して無力になる代わりにキルクールタイムが明けていれば、自分をキルしようとしたプレイヤーを返り討ちにできます

**Comment by yukieiji** [comment]
> ・シールドを貼ると復活の権利を失いますね。追放に対して無力になる代わりにキルクールタイムが明けていれば、自分をキルしようとしたプレイヤーを返り討ちにできます

強すぎでは？ジャッカルとかの他の第三陣営がこの役職を落とすことができなくなるのでは

**Comment by melonjagaimo** [comment]
ニュートラル陣営の方は完全に失念しておりました。
これ以上いい案が出ないのでクローズします
