### ISSUE TITLE
ヤンデレの片思いの人が落ちるとキルボタンが表示されない

### ISSUE THREAD

**Issue by RanasGlif** [yukieiji/ExtremeRoles#163]
### 期待される動作 / Your Expectation

ヤンデレの想い人が回線落ちした場合に会議を挟むとヤンデレのキルボタンが消えるというものでした
ヤンデレ2人の状態で想い人が回線落ちし発生しました
![unknown](https://user-images.githubusercontent.com/106647901/184544937-f9a75150-6d32-4508-ad0c-3f1e385abda6.png)

### このバグに対するあなたの意見 / Your Proposal

想い人が消えてもキルボタンが保持された方が良いと思う
### バグ発生時のログ / log when issue occur

Among Us v

### Modバージョン / Mod Version

Extreme Roles v3.2.1.1 

### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [x] :アジア/Asia
- [ ] :カスタム/Custom

### プレイヤー人数/Player Num

13
### 使用したオプション/Use Option

[option.csv](https://github.com/yukieiji/ExtremeRoles/files/9333666/option.csv)

**Comment by RanasGlif** [comment]
[ExtremeRolesDumpedLog_2022-08-15T00-42-33.log](https://github.com/yukieiji/ExtremeRoles/files/9333678/ExtremeRolesDumpedLog_2022-08-15T00-42-33.log)
発生時のログ貼り直し

**Comment by yukieiji** [comment]
タイトルは正しく記載して下さい

**Comment by yukieiji** [comment]
v3.2.1.2で修正
