### ISSUE TITLE
[ニュートラル陣営] : コウモリ男 (クルーかインポスターの味方に付いて便乗勝利を目指そう)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#170]
### 役職名 / Role Name
コウモリ男

### 役職の色 / Role color
灰色系

### 役職の説明 / Role description
クルーやインポスターの支援をしつつ片方の勝利に便乗するニュートラル陣営
TORのオポチュニストに能動的要素を追加した。ついでに死んでも勝てるようにした

### 役職の能力 / Role ability

・ゲーム開始時はノーマル状態。ノーマル状態の時に、後述するクルー手伝い能力を先に発動するとクルーサイド状態に、キル能力を先に発動するとインポスターサイド状態になる。ノーマル状態及びクルーサイド状態では無害なニュートラル陣営として扱われるが、インポスターサイド状態では有害なニュートラル陣営として扱われる。
トグル式の「サイドチェンジ」能力を発動することでクルーサイド状態とインポスターサイド状態を切り替えられる。切り替え回数には上限があり、死亡すると直前の状態で固定される。
サイドチェンジ能力はクルー手伝い能力かキル能力のうちいずれか1つを発動しないと使用できない。

・クルーサイド状態の時はクルー陣営の勝利に、インポスターサイド状態の時はインポスター陣営の勝利に便乗できる。この時、自身の生死は問わない。ノーマル状態の場合、残りの生存者が自身とクルーまたは無害なニュートラルの2人きりになると単独勝利。

・クルーのタスク勝利にカウントされないタスクを持ち、一定量こなすことで「クルー手伝い」能力が発動。ほかのクルー陣営プレイヤー1人の未完了タスクをいくつか完了したことにできる。クルー手伝い能力はインポスターサイド状態でも発動できる。タスクを全て完了させるともう1度発動する。

・常にキルボタンを所持し、すべてのプレイヤーがキル対象になる。妖狐には常に敵として扱われ、ベント使用とサボタージュ発動はともに不可能。

#### 固有オプション
クルー手伝いに必要なタスク進捗：10%～50%
クルー手伝いで完了したことにできるタスク数：1～3
サイドチェンジ使用回数：2～99
サイドチェンジのクールタイム：1秒～10秒

### 他陣営への影響 / Effect on other teams
クルー・インポスター両陣営とも、コウモリ男を味方につけるべく各々勝利への行動を積極的にするだろう。
敵対するようなことがあればコウモリ男の容疑者を排除することが予想される。
また、インポスターやジャッカルなどが命乞いのためにコウモリ男を騙る選択肢が生まれる。

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
これはトトカルチョのときにもあったんですけどクルー陣営が有利なAmongUsにおいて人外に加担するメリットが一切無い気がします
特にトグル式で切り替えれるし、タスクやってればクルーに味方できる時点で人外に加担なんて無意味に見えます

**Comment by melonjagaimo** [comment]
自分では改善案が思いつかないのでクローズします
