### ISSUE TITLE
カーペンターのベント封鎖でベントタスクができない現象

### ISSUE THREAD

**Issue by Yuzuriha40n** [yukieiji/ExtremeRoles#173]
### 期待される動作 / Your Expectation

カーペンターの能力によるベント封鎖で、対象のベントを塞いでもベントタスクができる
### 実際の動作 / The Reality

ベントを塞いだことによって、対象のベントのタスクが出来ずにタスク進行が不可能になった
### このバグに対するあなたの意見 / Your Proposal

これによってカーペンターを使用しての試合が難しくなったので、取り急ぎ報告しました。
### バグ発生時のログ / log when issue occur

この現象になったのが初めてでログが取れてません。申し訳ございません…
### Among Usバージョン/ Among Us Version

Among Us v2022.8.24s

### Modバージョン / Mod Version

Extreme Roles v.3.2.2.2

### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [x] :アジア/Asia
- [ ] :カスタム/Custom

### プレイヤー人数/Player Num

14人
### 使用したオプション/Use Option

こちらもとれておりませんでした…申し訳ございません…

取り急ぎのご報告となってしまったため、不備が多く大変申し訳ございません。
次回、ご報告する際には気を付けたいと思っている所存でございます。

以下添付ファイルとなっております。
[2022-08-27 22-18-36_Trim (2)_Trim.zip](https://github.com/yukieiji/ExtremeRoles/files/9440029/2022-08-27.22-18-36_Trim.2._Trim.zip)

**Comment by yukieiji** [comment]
再現しませんでした、ログがないと恐らく調査できないです
![CarpenterBug](https://user-images.githubusercontent.com/40425798/187084665-e90f65a5-bc9e-40c7-95a4-0ed24c2db116.PNG)

**Comment by yukieiji** [comment]
返信がないためクローズ
再現できたらコメントしてReopenをお願いします
