### ISSUE TITLE
[クルー陣営] : エクスキューショナー (タスク完了でシェリフが進化)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#177]
### 役職名 / Role Name
エクスキューショナー

### 役職の色 / Role color
シェリフと同じ

### 役職の説明 / Role description
タスクを完了したシェリフが覚醒する役職
クルーにキル能力を実行しても自爆しない。もちろん対象のクルーも無事

### 役職の能力 / Role ability

・ゲーム開始時はシェリフとしてアサインされ、タスクをすべて完了することでエクスキューショナーに覚醒する。

・キルできない対象にキル能力を発動した場合、キルワープのみを発生させて対象と自身ともに死亡しない。

・シェリフを同じオプションを個別に設定できる。（シェリフよりキルクールタイムが短い、シェリフがキルできないニュートラル陣営をキルできるなどの設定が可能）

#### メリット
タスク完了で自爆しなくなる

#### デメリット
覚醒を待つ間にキルされたり手遅れな状態になるリスクがある

### 他陣営への影響 / Effect on other teams
終盤にインポスター陣営やニュートラル陣営がシェリフを騙りにくくなる。
また、シェリフの進化を待たせないために積極的にキル行為を行うことが予想される。

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
通常のキルが出来るのはヒーローの特権で、そのヒーローの完全上位互換になってませんか？

**Comment by melonjagaimo** [comment]
そうでしたね。ではこちらはクローズします。
役職の進化については別のもので考えます。
