### ISSUE TITLE
[ニュートラル/Neutral] : ドラゴノイド (人々を根絶やしにする竜の化身)

### ISSUE THREAD

**Issue by kabitamon** [yukieiji/ExtremeRoles#178]
### 役職名 / Role Name

ドラゴノイド

### 役職の色 / Role color

橙

### 役職の説明 / Role description

生存者が固まった場合、強引に殲滅します。

### 役職の能力 / Role ability

インポスターと同様にキルが出来る。
以下の能力を発動しやすくする為に、アドミンを利用する事が出来る。
固有能力は逆鱗
発動条件は以下の通り
画面に写っている生存者が一定人数以上必要になる。会議終了時の生存人数が多い場合は4〜5人と厳しく、逆にその生存人数が少ないほど条件が優しくなる。最低2人。
マップによって、発動する確率が影響する。スケルドは、マップが狭く人が集まりやすく、逆にエアシップは、人が集まりにくい。
ただし、スポーンからの一定時間・サポタージュやその終了後の一定時間は条件から外れる。
条件が揃うと、10秒以内に利用する事が可能。利用可能期間に発動条件が揃えば、10秒にリセットされる。
逆鱗が発動した場合は、以下の状態になる。
発動期間中は、自動的にキルをする。
移動速度が強化され、キルレンジがロングになる。
扉の前で使用を押した場合、タスクをスキップして開ける事が可能。
キルクールは発生しない。
発動時間は、会議終了後の生存人数が多いほど2〜3秒と短くなる。その生存人数が減れば減るほど長くなり、最終的に5〜10秒と伸びる。
発動期間中にキルをすると、発動時間がリセットされる。
発動終了後は、通常キルのクールタイムが発生する。

### 他陣営への影響 / Effect on other teams

集団行動が減少し、浮きやラインが増加する。よってインポスターが行動しやすくなる。

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 以下の能力を発動しやすくする為に、アドミンを利用する事が出来る。

ボタンで使用できるってことですか、それともふつうのコンソールが使えるということですか？

> マップによって、発動する確率が影響する。スケルドは、マップが狭く人が集まりやすく、逆にエアシップは、人が集まりにくい。

発動確率ってなんでしょうか

> 条件が揃うと、10秒以内に利用する事が可能。利用可能期間に発動条件が揃えば、10秒にリセットされる。

ここどういうことでしょうか

全体的に発動さえさせれば無条件で何人でもキルできる時点でデメリットが少ない気がしますけどどうでしょうか

**Comment by kabitamon** [comment]
> ボタンで使用できるってことですか、それともふつうのコンソールが使えるということですか？

普通のコンソールが使えるで大丈夫です。

> 発動確率ってなんでしょうか

条件の成立がしやすさと言うことで意味が伝わりますか？

> ここどういうことでしょうか

必要な生存人数が揃うと、逆鱗と言うコマンドをボタン入力で利用することが出来る。ただし、10秒以内に利用しなかった場合は、それを使う事が出来なくなる。
逆鱗が利用可能状態中に必要な生存人数が揃うと、制限時間が10秒にリセットされる。

> 全体的に発動さえさせれば無条件で何人でもキルできる時点でデメリットが少ない気がしますけどどうでしょうか

逆鱗の発動中は、時間制限が設けられており、その時間を超えると強制的に解除されます。制限時間は、説明のとうりに人数が多い場合2〜3秒、少ない場合は5〜10秒となっております。
それでも効果が強すぎる場合は逆鱗の制限時間をさらに短くしても問題ありません。
さらに、サポタージュが発動した場合は逆鱗を解除される、逆鱗が再度利用する場合発動可能に必要人数を増やす、逆鱗発動終了後に自身の行動が出来ないと言うデメリットを提案します。

**Comment by yukieiji** [comment]
> 普通のコンソールが使えるで大丈夫です。

基本的に使えないってことはないのであんまり考慮しなくてもいいような

> 必要な生存人数が揃うと、逆鱗と言うコマンドをボタン入力で利用することが出来る。ただし、10秒以内に利用しなかった場合は、それを使う事が出来なくなる。
逆鱗が利用可能状態中に必要な生存人数が揃うと、制限時間が10秒にリセットされる。

必要な生存者ってのが発動に必要な生存者数でってことですか？
その発動に必要な生存者の数によって制限時間が変化するってことですか

> それでも効果が強すぎる場合は逆鱗の制限時間をさらに短くしても問題ありません。

効果時間ってより発動さえさせてしまえば近くにいる人を全員まとめてキルできるってのが個人的にダメじゃないかなって思ってます(ボマーの初期元案の自爆(自爆で周りにいる人を完全に巻き込める)みたいな感じでしょうか、サボタージュに集まった人を問答無用で吹き飛ばせるので現在の仕様に変更しています、この役職だとまとめてキルしたあとに追加で高速に移動して目撃者を問答無用でキルできるってことを考えればかなり強力ではないでしょうか)
効果時間が短かったり人が多くなると多分使いにくい役職になるとは思います

> さらに、サポタージュが発動した場合は逆鱗を解除される

サボタージュがトリガーになるとインポスター側がキルされないようにサボを連打する必要があってインポスター自身がきつくなると思います(逆に連打されるとこの役職が死んでしまう気がします)

> 逆鱗が再度利用する場合発動可能に必要人数を増やす

上にある通り人数が増えると使いにくい役職になるような気がします

> 逆鱗発動終了後に自身の行動が出来ないと言うデメリットを提案します。

自信の行動ってどの部分の行動ですか

**Comment by kabitamon** [comment]
> 必要な生存者ってのが発動に必要な生存者数でってことですか？
その発動に必要な生存者の数によって制限時間が変化するってことですか

必要な生存者は必要な生存者数であってます。
スキルは発動するのに条件が揃った場合に自動的におきる発動可能時間と、発動可能時間中にボタンを押すと本格的に発動する本格発動時間の2つがあります。それぞれの時間は別々に考えください。
発動可能時間は、変化と言うより制限時間の上書きになります。例えば、制限時間が6秒残っている状態で必要な生存者数が揃えた場合、制限時間が10秒残る状態になります。必要な生存者数が多い少ない関係なく制限時間は固定になります。


> 効果時間ってより発動さえさせてしまえば近くにいる人を全員まとめてキルできるってのが個人的にダメじゃないかなって思ってます

では、大幅な変更になりますがこれはどうでしょう。
スキル:逆鱗→ドラゴンブレス
発動条件:逆鱗と同じ
効果: 発動開始してから一定時間は、特殊なサポタージュが発動する。
特殊サポタージュ中は緊急サポタージュの音が鳴る。
最後に発動条件に必要な人数が揃い、かつ自分と最も近い生存者がドラゴンブレスの対象になる。
一定時間後、ドラゴンブレスの対象になった人とその部屋にいる生存者をまとめてキルする。ドラゴンブレスの対象者が廊下にいる場合は廊下にいる生存者をまとめてキル、ポーラスの外出中にいる場合はドラゴンブレスの対象者の視界の広さ1倍にいる生存者をまとめてキルする。
ドラゴンブレスでキルを終えた場合、特殊なサポタージュが終了する。
特殊サポタージュの発動を開始した場合、全員が対象になる。それは、マップにドラゴンブレスの対象の人がいる部屋を知らせるマークが付く。ただし、発動中はドラゴンブレスの対象にされてる人は移動をし、マップに表示されてるマークは移動せずに固定される。特殊サポタージュ終了時、そのマークはマップ上の表示されなくなる。
特殊サポタージュ中は緊急招集ボタンが使えない。
必要であれば、ドラゴンブレス発動中に現在一定時間後にキルされる位置にいる場合、「強力な威圧を感じる」を表示する。
ドラゴンブレス発動中に死体報告などで会議が開かれる場合、ドラゴンブレスは失敗する。

> サボタージュがトリガーになるとインポスター側がキルされないようにサボを連打する必要があってインポスター自身がきつくなると思います(逆に連打されるとこの役職が死んでしまう気がします)

問題が起きそうな状態なので取りやめます。

> 自信の行動ってどの部分の行動ですか

移動速度が0になります。

**Comment by yukieiji** [comment]
> スキルは発動するのに条件が揃った場合に自動的におきる発動可能時間と、発動可能時間中にボタンを押すと本格的に発動する本格発動時間の2つがあります。それぞれの時間は別々に考えください。
発動可能時間は、変化と言うより制限時間の上書きになります。例えば、制限時間が6秒残っている状態で必要な生存者数が揃えた場合、制限時間が10秒残る状態になります。必要な生存者数が多い少ない関係なく制限時間は固定になります。

発動するのに条件が整ったとに生存者数が揃う場合ってどういうことですか、また、制限時間が6秒で制限時間が10秒残るってどういうことですか
発動可能条件ってのが必要な生存者は必要な生存者数ですよね、その上で生存者が揃うってどういう場合になりますか

> では、大幅な変更になりますがこれはどうでしょう。
スキル:逆鱗→ドラゴンブレス
発動条件:逆鱗と同じ
効果: 発動開始してから一定時間は、特殊なサポタージュが発動する。
特殊サポタージュ中は緊急サポタージュの音が鳴る。
最後に発動条件に必要な人数が揃い、かつ自分と最も近い生存者がドラゴンブレスの対象になる。
一定時間後、ドラゴンブレスの対象になった人とその部屋にいる生存者をまとめてキルする。ドラゴンブレスの対象者が廊下にいる場合は廊下にいる生存者をまとめてキル、ポーラスの外出中にいる場合はドラゴンブレスの対象者の視界の広さ1倍にいる生存者をまとめてキルする。
ドラゴンブレスでキルを終えた場合、特殊なサポタージュが終了する。
特殊サポタージュの発動を開始した場合、全員が対象になる。それは、マップにドラゴンブレスの対象の人がいる部屋を知らせるマークが付く。ただし、発動中はドラゴンブレスの対象にされてる人は移動をし、マップに表示されてるマークは移動せずに固定される。特殊サポタージュ終了時、そのマークはマップ上の表示されなくなる。
特殊サポタージュ中は緊急招集ボタンが使えない。
必要であれば、ドラゴンブレス発動中に現在一定時間後にキルされる位置にいる場合、「強力な威圧を感じる」を表示する。
ドラゴンブレス発動中に死体報告などで会議が開かれる場合、ドラゴンブレスは失敗する。

長すぎて仕様をイマイチ理解できないですけどボマーとほぼ同じってことでいいですか？(同じだとしてもサボタージュ周りや人に表示するとかが多いのでやりたくはないですが)
あと廊下にいるっていうのは取得できなかったはずです

> 移動速度が0になります。

キルは出来るってことでいいですか？
