### ISSUE TITLE
役職被り機能の希望

### ISSUE THREAD

**Issue by ankomon** [yukieiji/ExtremeRoles#18]
追加する機能の詳細 / Feature details
クルーやインポスター等に割り振られる役職に加えて
属性としてもう一つ役職が付与される機能

機能を追加するメリット / Benefits of adding features
既存の役職でとられる事のなかった動きが見れるようになる、かも

このような感じでしょうか?

**Comment by yukieiji** [comment]
これは「双子」っていうニュートラルの新しい役職なのでしょうか？それとも「双子」っていう新しい属性を役職に追加してほしいのでしょうか？

**Comment by yukieiji** [comment]
> あ、新しい属性の方です

双子「属性」という新しい機能拡張になるので以下のテンプレートに従ってチケットを更新して下さい(新しいissueは建てないで下さい)
また現状、EXロールは役職に「属性」という概念は持ち合わせていません。ラバーズも一つの役職として実装しています


# 以下テンプレート
### 追加する機能の詳細 / Feature details


### 機能を追加するメリット / Benefits of adding features

**Comment by ankomon** [comment]
分かりました

チケットの更新は一番上のコメントを編集する事でよろしいでしょうか?

**Comment by yukieiji** [comment]
そうです。管理等の都合上よろしくおねがいします

**Comment by ankomon** [comment]
このような感じでよろしいでしょうか?

**Comment by yukieiji** [comment]
古い文章は全て消してタイトルも更新して下さい

**Comment by ankomon** [comment]
このような感じでしょうか?

**Comment by yukieiji** [comment]
ちゃんとタイトルもどういった機能の提案か書いて下さい

**Comment by ankomon** [comment]
すみませんでした

**Comment by yukieiji** [comment]
「属性」として「役職」を付与したいって感じですか？それとも「役職」とは全く異なる「属性」を付与したいってことですか？

役職に別の役職を追加するってことは元々出来ます
「役職」は「SingleRoleBase」を拡張、別の役職の能力を持つような「役職」は「MultiAssignRoleBase」を拡張して作ってますので

**Comment by ankomon** [comment]
考えていたものは「属性」として「役職」を付与するもの、だと思います
「属性」がふんわりとしたイメージなので断定が出来ませんが

**Comment by yukieiji** [comment]
タイトルにもissueにも「属性」に関する情報が一切書いてないのでその部分も記載をお願いします
もしその「属性」がふんわりして言葉に出来ないのであれば、私もそれを理解するのは難しいのでこのチケット自体一旦クローズさせて下さい(意見がきちんと固まった際に新しいチケットを作って下さい)

**Comment by yukieiji** [comment]
「役職」は「Role(SingleRoleBaseやMultiAssignRole)」でプレイヤーが所持するものです(オブジェクト指向的に言えば「Player has Role」です)、EXロール上でもそうなるように(それに近い形で)実装されています
「属性」は「Attribute(どう実装するかクラス名はわかんないけど)」で役職(Role)が所持するものではないでしょうか？(オブジェクト指向的に言えば「Role has Attribute」だと思います。)
なので「属性」に「役職」を追加することはプログラム実装上及びオブジェクト指向のパラダイム的に出来ないということになります
Role has Attributeの関係である以上「属性」は「役職」を包括するような機能であったり役職を越えるような機能実装することは出来ないです

**Comment by ankomon** [comment]
> タイトルにもissueにも「属性」に関する情報が一切書いてないのでその部分も記載をお願いします もしその「属性」がふんわりして言葉に出来ないのであれば、私がそれを理解して実装するのは難しいのでこのチケット自体一旦クローズさせて下さい(意見がきちんと固まった際に新しいチケットを作って下さい)

すみません。言葉に出来そうにないのでクローズお願いします
