### ISSUE TITLE
ゲーム終了時のヤンデレの思い人の先表示

### ISSUE THREAD

**Issue by sigcolotet** [yukieiji/ExtremeRoles#180]
### 追加する機能の詳細 / Feature details
ゲーム終了時の役職一覧にヤンデレの想い人の先などのプレイヤー名を表示するようにしてほしい
（ヤンデレ勝利時だけでなく、一覧に出してほしい）

### 機能を追加するメリット / Benefits of adding features
・配信や動画化の際に、わかりやすい
・感想戦の際に誰だったかがわかりやすい

**Comment by yukieiji** [comment]
ExRのリポジトリのREADMEの実装予定の機能にある、「幽霊役職の最終結果表示」と「死亡時役職が持つ固有の情報を表示できるようにする」とダブっているのでクローズします
![info](https://user-images.githubusercontent.com/40425798/188514675-bf10ddc9-c4da-43f6-b4a4-f9ae19fb1059.PNG)

現状は各個人にしか保存されていないような情報もあったり、計算量的にスマートな方法を思いついてないため、かなり前から仕様を検討しているような状態です
