### ISSUE TITLE
ゲーム終了時の乗っ取り役職の元役職の表示

### ISSUE THREAD

**Issue by sigcolotet** [yukieiji/ExtremeRoles#181]
### 追加する機能の詳細 / Feature details
ジャッカルのサイドキック乗っ取りのような役職の場合、
ゲーム終了時の役職一覧表示が「サイドキック」になってしまうが、サイドキックになる前の初期役職の表示もほしい

### 機能を追加するメリット / Benefits of adding features
配信・動画化の際に分かりやすい
感想戦をする際に分かりやすい

**Comment by yukieiji** [comment]
ExRのリポジトリのREADMEの実装予定の機能にある、「幽霊役職の最終結果表示」と「死亡時役職が持つ固有の情報を表示できるようにする」と似たような機能提案のためクローズします
![info](https://user-images.githubusercontent.com/40425798/188514675-bf10ddc9-c4da-43f6-b4a4-f9ae19fb1059.PNG)

現状は各個人にしか保存されていないような情報もあったり、計算量的にスマートな方法を思いついてないため、かなり前から仕様を検討しているような状態です
