### ISSUE TITLE
[ニュートラル/Neutral幽霊コンビ役職] : ワルガキ/Delinquent(生前)とウィスプ/Wisp (幽霊、生前悪さをした分妨害能力が使える)

### ISSUE THREAD

**Issue by Inumiya** [yukieiji/ExtremeRoles#182]
### 幽霊役職名 / Role Name
ウィスプ
### 幽霊役職の色 / Role color
蛍光グリーン
### 幽霊役職の説明 / Role description
特徴
- 特定の生前役職からのみなれる幽霊役職
- 生前役職が能力を使った回数だけ、幽霊役職の能力を使える

勝利条件
- 能力で一定回数デバフを付与できたら勝利陣営に相乗り勝利
  - 回数は生存者数 ± (オプションで指定) 回
  - 生存者数は、死亡時、吊られた時、自爆能力の使用時に確定
### 幽霊役職の能力 / Role ability

灯火
- 最大使用可能回数：生前役職でらくがき能力を使った回数+1回
- スポーン地点に灯火を設置
  - プレイヤーを1~2人ランダムで選択し、そのスポーン位置に設置
  - 設置されたことは矢印で通知
- 設置された灯火はミドルレンジ内のプレイヤーにアンチデバフをかけ続ける
  - アンチデバフ効果時間：灯火の消滅まで
- 設置から30秒後に消滅＆アンチデバフが付与されていないプレイヤーにデバフ付与
  - デバフの効果：視界を停電時と同じにする
  - デバフの効果時間：15秒

### 死亡前の役職 / Role befor Dead
ワルガキ/delinquent
- ニュートラル陣営
- 死ぬと必ずウィスプになる
- 勝利条件：自爆能力使用後に生存者数が０になる

能力：らくがき
- 最大使用可能回数：5回
- ボタンを押した場所に落書きする
  - 全員から見えるだけで特に何もない

能力：自爆ボタン
- らくがきを5回使用している かつ 周囲に人がいるときのみ使用可
- 自分自身と周囲のプレイヤーを全てキルする

デメリット
- 幽霊役職のために積極的に能力を使用したいが、使用した直後に人とすれ違うとバレてしまう
- 人気のないところで能力を使おうとすると浮きやすい

### 他陣営への影響 / Effect on other teams
- デバフが陣営関係なくほぼすべての役職にとって厄介なので、らくがきが少ない内に全陣営が吊るそうとする
- 吊るさずにいると自爆で大量キルされる恐れがある

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> ボタン能力のクールタイム増加
増加はごくわずか（３秒程度）
キルボタンを持っている場合は、必ずキルボタンのクールタイムが増加する

キルボタン周りのオフセットはv3.3.0.0以降かなりダイレクトに効くようにロジックが変更されるので3秒でもかなり辛いような気もしなくはないです
- 参考 : #158 より
  - 各役職のキルクールを直接変更しているロジックをキルクールタイムの最終決定計算時にペナルティを与えるように変更
     - これにより大幅にキルクールが減った上で加算のペナルティが入る + 会議後のリセットがなくなるのでキル加速役職のキル加速にブレーキがかかる
        - 例：オーバーローダー、キルクール減少率75％、基礎クール20秒、キルクールペナルティ5秒の場合
          - 変更前：(20秒 + 5.0秒) * 0.25 = 6.25秒
          - 変更後：20秒 * 0.25 + 5.0秒 = 10秒

> デバフが陣営関係なくほぼすべての役職にとって厄介なので、らくがきが少ない内は全陣営が吊るそうとする

クルー的にもインポスター的にも吊るという選択を取るのか疑問に感じます。吊らないという選択肢が取られた結果、疎外感がすごい気がします
- クルー陣営
  - 生存者が少しでも多く弾除けに使いたい
  - 弾除けになったとしてもボタン能力持ち(クルー24役職中ボタン持ちが14役職、ボディーガードはv3.3.0.0で会議能力を持つのであんまり関係なくなるので実質的には13役職)が少ないので実害が少ない
  - 弾除けで死んでも実害があるのはインポスター陣営
- インポスター陣営
  - 霊界に送ると邪魔されて勝てなくなるから吊りたくはない

**Comment by Inumiya** [comment]
> キルボタン周りのオフセットはv3.3.0.0以降かなりダイレクトに効くようにロジックが変更されるので3秒でもかなり辛いような気もしなくはないです

倍率掛かるところ変わったの失念してました。。あえて無視する戦法が取れる程度の増加量にしたいので、１～２秒増加がいいでしょうか

> クルー的にもインポスター的にも吊るという選択を取るのか疑問に感じます。吊らないという選択肢が取られた結果、疎外感がすごい気がします

普通のニュートラル陣営は、単独陣営で正体がバレると吊るされて勝利できなくなります
この役職は、単独陣営で正体がバレると吊るされなくなって勝利できなくなります
正直あまり差がないように感じます（幽霊チャットに参加できるかどうかの差でしょうか）

**Comment by yukieiji** [comment]
> 普通のニュートラル陣営は、単独陣営で正体がバレると吊るされて勝利できなくなります
この役職は、単独陣営で正体がバレると吊るされなくなって勝利できなくなります
正直あまり差がないように感じます（幽霊チャットに参加できるかどうかの差でしょうか）

人によりけりだとは思いますが、私は身バレしたTORジェスターより無力感がすごいと感じてしまいますが、どうなんでしょうか(ジェスターは殺さなきゃ吊るみたいな事やExRだと暴発もありますしね)

あと何回か見返してちょっと気になった点

> 能力で一定回数デバフを付与できたら勝利陣営に相乗り勝利

この一定回数ってどれくらいを想定してますか、また灯火からどれくらい離れて何秒たったらてのは想定してますか
この回数と運用ボタンクール、灯火がどれくらいで撤去されるかによってだとは思いますがAirShipとかの広いマップだと初手吊ってくれでも勝利できるような気がしてます

**Comment by Inumiya** [comment]
> 人によりけりだとは思いますが、私は身バレしたTORジェスターより無力感がすごいと感じてしまいますが、どうなんでしょうか(ジェスターは殺さなきゃ吊るみたいな事やExRだと暴発もありますしね)

吊られなくてもキルされればいいので、勝ち目がほぼ０になるTORジェスターよりかはマシかとは思います
緊急タスクの前で待機する、誰かしらをストーカーし続けるなど、自分を殺させるよう圧力をかける方法はあり、身バレしても全くやることがなくなるわけではないです

ただこういうことをしだすとインポスターに対してより不利になってしまうので、自死する手段があったほうが良いでしょうか。らくがきを一定回数やり終えると自死ボタンに変化するとか（クール30秒で10回くらい）

> この回数と運用ボタンクール、灯火がどれくらいで撤去されるか
一番使われているAirShipで、6人がボタン持ちを想定して設定すると、必要回数7回、灯火の出現時間30秒、ボタンクールは幽霊役職なのでデフォ60秒（ホントはもう少し短くしたいですが）です
能力使用1~2回では相乗り勝利できないようなイメージです

**Comment by yukieiji** [comment]
> ただこういうことをしだすとインポスターに対してより不利になってしまうので、自死する手段があったほうが良いでしょうか。らくがきを一定回数やり終えると自死ボタンに変化するとか（クール30秒で10回くらい）

自死できる手段を持つと準備が終わったら死んでボタンをポチポチ押して勝利できるか祈るみたいな感じになるので、絶対自分に当たるようなジェスターの暴発とかのほうが良いかもしれないです(それもインポスター不利なので自爆して周りの人を巻き込む？とかもありかもしれない(それで人数全滅できたら勝利ってのもあり))

> 一番使われているAirShipで、6人がボタン持ちを想定して設定すると、必要回数7回、灯火の出現時間30秒、ボタンクールは幽霊役職なのでデフォ60秒（ホントはもう少し短くしたいですが）です

ボタン持ち6人と言うことはクルーのボタン持ちは2人想定って感じでいいですか(インポスター3人、ジャッカル or クイーン or ヤンデレ1人)
そうなると中終盤だいぶきつくないですかね

**Comment by Inumiya** [comment]
> 絶対自分に当たるようなジェスターの暴発とかのほうが良いかもしれないです(それもインポスター不利なので必ず周りに人が居ないと使えない自爆ボタンがあって周りの人を巻き込む？とかもありかもしれない(それで人数全滅できたら勝利ってのもあり))

自爆ボタンいいですね
- らくがきを5回以上使用している かつ 周囲に人がいるときのみ使える
- 自分自身と周囲の人全てをキルする
- 自爆ボタンで生存者が０になった場合は勝利
この仕様でどうでしょうか

> ボタン持ち6人と言うことはクルーのボタン持ちは2人想定って感じでいいですか(インポスター3人、ジャッカル or クイーン or ヤンデレ1人)
そうなると中終盤だいぶきつくないですかね

確かに終盤はボタン持ちが2人とかになりがちですし、ルールによってボタン持ちの数が結構変わる問題もあるので、
デバフの内容を変更して、ボタン持っていない人にも影響があるようにしようかと思います
新デバフ案
- 視界が停電時並に狭くなる
とかどうでしょうか

> 灯火の詳しい仕様

灯火出現から消滅までは以下の流れになるイメージです
- ボタン能力で灯火を出現させる
  - ボタン能力の運用クール：40秒
  - 灯火の位置は矢印で通知したい
- 灯火が周囲のプレイヤーにアンチデバフを付与
  - 灯火がアンチデバフを付与する範囲：ショートレンジ 
  - アンチデバフの効果時間：灯火が消滅するまで
- 灯火が消滅した時、アンチデバフを付与されていないプレイヤーに即時デバフを付与
  - 灯火が設置されてから消滅するまで：30秒
  - デバフの効果時間：15秒（視界が停電になるデバフの場合）

**Comment by yukieiji** [comment]
> 確かに終盤はボタン持ちが2人とかになりがちですし、ルールによってボタン持ちの数が結構変わる問題もあるので、
デバフの内容を変更して、ボタン持っていない人にも影響があるようにしようかと思います
新デバフ案
視界が停電時並に狭くなる
とかどうでしょうか

多分、ボタン持ち以外にも影響があると初手吊ってくれでおｋになりそうな気がします
ラストウルフやトトカルチョみたいに生存者に応じて必要人数を減らすというのもひとつな気がします(個人的には序盤は基本勝利条件、中盤は基本勝利と幽霊勝利に揺らぐ、終盤は幽霊勝利が少しやりやすい位がちょうどいいのかなって思ってます)

> 灯火がアンチデバフを付与する範囲：ショートレンジ

ショートレンジだと距離0(密接)してないとダメだったと思うのですが大丈夫ですか

**Comment by Inumiya** [comment]
> ラストウルフやトトカルチョみたいに生存者に応じて必要人数を減らすというのもひとつな気がします(個人的には序盤は基本勝利条件、中盤は基本勝利と幽霊勝利に揺らぐ、終盤は幽霊勝利が少しやりやすい位がちょうどいいのかなって思ってます)

なるほど。自分が死亡した時の生存者の数を参照して、勝利条件を決定すると良いでしょうか。
勝利条件：死亡時の生存者数と同数 ± (オプションで指定) 回デバフをかける

> ショートレンジだと距離0(密接)してないとダメだったと思うのですが大丈夫ですか

よく考えるとショートレンジである必要はないので、ミドルレンジにします

**Comment by yukieiji** [comment]
> なるほど。自分が死亡した時の生存者の数を参照して、勝利条件を決定すると良いでしょうか。
勝利条件：死亡時の生存者数と同数 ± (オプションで指定) 回デバフをかける

問題ないと思います
自爆した時はボタンを押した瞬間の生存者を指定する形で問題ないですか？(自爆が終わった時の生存者を参照すると強い気がしますので)

> よく考えるとショートレンジである必要はないので、ミドルレンジにします

あと考える部分としたらAirShip以外はスポーン地点がオブジェクトで塞がれてるので灯火を設置できないような気がします

**Comment by Inumiya** [comment]
> 自爆した時はボタンを押した瞬間の生存者を指定する形で問題ないですか

それで問題ないです

> あと考える部分としたらAirShip以外はスポーン地点がオブジェクトで塞がれてるので灯火を設置できないような気がします

なぜスポーン位置に灯火が出現するようにしたかったかというと、
ウィスプ自身が灯火の設置場所を決められるようにすると、壁の中に設置できないようにする処理やマップの端っこに設置すると勝ちやすくなってしまうなどの問題があるかと思ったからです
なので、これらの問題が回避できるなら必ずしもスポーン位置に設置する必要はないです

ウィスプ自身がスポーンした位置など取得できるならそこでも良いかと思います
AirShipの場合はそこ以外にもう１箇所設置場所を決める必要がありますが

**Comment by yukieiji** [comment]
> なぜスポーン位置に灯火が出現するようにしたかったかというと、
ウィスプ自身が灯火の設置場所を決められるようにすると、壁の中に設置できないようにする処理やマップの端っこに設置すると勝ちやすくなってしまうなどの問題があるかと思ったからです

たしかにそれはそうです
確か壁の中にいるってのは取るのは難しかったような気がします

> ウィスプ自身がスポーンした位置など取得できるならそこでも良いかと思います
AirShipの場合はそこ以外にもう１箇所設置場所を決める必要がありますが

AirShip以外の会議終了後のスポーン位置(あの円形の配置)は人数が一緒だと固定のため、ウィスプのスポーン位置を取ってしまうとあの人がこの役職だと即バレしますけど大丈夫ですか
必ずホストの場所に設置されるとかなら問題ないのかな・・・？

**Comment by Inumiya** [comment]
> AirShip以外の会議終了後のスポーン位置(あの円形の配置)は人数が一緒だと固定のため、ウィスプのスポーン位置を取ってしまうとあの人がこの役職だと即バレしますけど大丈夫ですか
必ずホストの場所に設置されるとかなら問題ないのかな・・・？

ウィスプ的にはあまり問題ないですが、他陣営に影響出てしまいますね
必ずホストの位置や、ランダムでプレイヤー１～２人を選んでその位置とかは可能ですか？

**Comment by yukieiji** [comment]
> ウィスプ的にはあまり問題ないですが、他陣営に影響出てしまいますね
必ずホストの位置や、ランダムでプレイヤー１～２人を選んでその位置とかは可能ですか？

ランダムな位置は恐らく取得可能だと思います

**Comment by Inumiya** [comment]
> ランダムな位置は恐らく取得可能だと思います

では、ランダムでプレイヤー１～２人を選んでそのスポーンした位置に灯火を設置する仕様にします

**Comment by yukieiji** [comment]
あと決めなければならないの #116 の勝利条件周りですかね？
実装予定はv3.4.0.0で大丈夫ですか？

**Comment by Inumiya** [comment]
> あと決めなければならないの#116 の勝利条件周りですかね？

8前で良いかと思います

> 実装予定はv3.4.0.0で大丈夫ですか？

大丈夫です
お願いします

**Comment by yukieiji** [comment]
優先度とマイルストーンをセットします

**Comment by yukieiji** [comment]
@Inumiya 役職の色についてですがRGB値で色を緑系列の色がかなりあって探すのに苦労してるので教えていただいてもいいでしょうか

- 現在、使用済みの緑周りの色(それぞれRGB値)
  - サポーター：153, 255, 153
  - スーパーバイザー：51, 204, 102
  - エージェンシー：181, 255, 20
  - フェンサー：0, 87, 86
  - オープナー：0, 250, 154
  - トトカルチョ：0, 255, 0
  - マイナー：76, 103, 51

**Comment by Inumiya** [comment]
140, 170, 0
はいかがでしょうか
既存の役職とあまり被っていないはずです

**Comment by yukieiji** [comment]
こんな感じですが大丈夫ですか
![Kids](https://user-images.githubusercontent.com/40425798/204287046-eae39c6b-8af2-47f5-8619-62fbaf58b0d8.PNG)

**Comment by Inumiya** [comment]
大丈夫です
ありがとうございます
