### ISSUE TITLE
[ニュートラル陣営] : アヴェンジャー (指定のプレイヤーをキルして復讐を果たそう)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#183]
### 役職名 / Role Name
アヴェンジャー

### 役職の色 / Role color
暗い赤色

### 役職の説明 / Role description
指定のプレイヤー（以下、復讐対象）をキルして、キル後最初に開かれた会議で自身が追放されずに生き残れば勝つニュートラル陣営

#### 勝利条件
1:ゲーム開始時に指定される復讐対象をキルし、次の会議を生き残った場合。その後の本人の生死を問わず、妖狐以外のあらゆる勝利に便乗して勝利
2:残り生存者が自身とクルーまたは無害なニュートラルの2人きりになる。アヴェンジャーの単独勝利

#### 基本仕様
・アヴェンジャーは有害なニュートラル（勝利条件1達成で無害化する）であり、勝利条件1を達成するまではキル能力を持つ。

・アヴェンジャーはサボタージュ発動ができない。ベントはオプションで使用可否を変更可能。

・アヴェンジャーは常に妖狐に「敵」と判定されないが、常にシェリフのキル対象になる。

#### 復讐
・アヴェンジャーはゲーム開始時に「〇〇への復讐に燃えろ」のように復讐対象を指定される。復讐対象の位置は矢印で表示される。

・復讐対象をキルして次の会議を生存した場合、復讐を果たして勝利条件1を満たす。
・勝利条件1を満たさない条件下で復讐対象が死亡した場合、アヴェンジャーは勝利条件2を満たすためにクルーを皆殺しにせんとする。

### 他陣営への影響 / Effect on other teams
クルー陣営：復讐の途中または復讐を果たせなかったアヴェンジャーは有害なので排除しなければならない。

インポスター陣営：「今のキルで復讐を果たした。会議後無害になるから吊らないでくれ」のように命乞いのために騙る選択肢ができる。

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 1:ゲーム開始時に復讐対象をキルし、次の会議を生き残った場合。その後の本人の生死を問わず、妖狐以外のあらゆる勝利に便乗して勝利
2:復讐対象に投票した会議で、その復讐対象が追放された場合。その後の本人の生死を問わず、妖狐以外のあらゆる勝利に便乗して勝利

これ結局初手ボタンを押して「あの人復習対象なんで吊って下さい」ですぐ勝利出てしまうんじゃないんですかね
吊ってしまえば、復習対象がクルーであれば1：1交換で強いキルボタンがもらえますし、人外だった場合はダメージが入りますし吊らないって選択肢はないんじゃないんですかね

**Comment by melonjagaimo** [comment]
しまった、それを失念していました。
しかし追放じゃダメ、にするとアサシンが復讐対象になった場合に詰んでしまう場合があります。
アサシンを復讐対象から除外することは可能でしょうか？

それと、復讐を果たしたアヴェンジャーは無害化してキル能力を失いますよ。

**Comment by yukieiji** [comment]
> しかし追放じゃダメ、にするとアサシンが復讐対象になった場合に詰んでしまう場合があります。
アサシンを復讐対象から除外することは可能でしょうか？

除外することは可能です

> それと、復讐を果たしたアヴェンジャーは無害化してキル能力を失いますよ。

どっちにしろクルー的にキルボタンが1:1交換で減るなら爆アドでは？、人外だった場合だとキルボタンが2つも減りますし

根本的に思ったんですけど1，2の勝利条件って基本無理な気がするんですけど良いんですかね

**Comment by melonjagaimo** [comment]
1,2は「1か2いずれか」です。

アサシンを復讐対象から除外できるなら追放させる方の条件を削除しましょう。アサシンがキルできない設定からこの条件をつけたのですし

**Comment by melonjagaimo** [comment]
それと運ゲーというのも、キルしても次の会議を生き残らないと勝利できないので即座にキルするわけにはいかないでしょう。

**Comment by yukieiji** [comment]
> 1,2は「1か2いずれか」です。

いずれかでもほぼ不可能ではないんですかね、初手スポーンが同じではないAirShipとかサブマージドで復習対象が遠くに湧くとその時点で初手キルクールのうちに殺されることもありますし

> アサシンを復讐対象から除外できるなら追放させる方の条件を削除しましょう。アサシンがキルできない設定からこの条件をつけたのですし

上にもあった通り別の人に殺されないようにするために初手のキルクールタイム中に出会う運ゲーが始まりませんか？

> それと運ゲーというのも、キルしても次の会議を生き残らないと勝利できないので即座にキルするわけにはいかないでしょう。

次の会議がどの次の会議かわからないですけど、切って即通報して次ボタン押せば達成されませんか？目の前でキル時点でこの役職ほぼ確定でしょうし

**Comment by melonjagaimo** [comment]
追放の方の条件削除にともない、勝利条件を現在は

1:ゲーム開始時に指定される復讐対象をキルし、キル後後最初に開かれた会議で自分が追放されず生き残った場合。その後の本人の生死を問わず、妖狐以外のあらゆる勝利に便乗して勝利
2:残り生存者が自身とクルーまたは無害なニュートラルの2人きりになる。アヴェンジャーの単独勝利

に変更しました。


他人にキルされた場合ですか…。復讐対象をキルしたプレイヤーを新たな復讐対象にする（アサシンを除く）とどうでしょうか。

**Comment by yukieiji** [comment]
> 1:ゲーム開始時に指定される復讐対象をキルし、キル後後最初に開かれた会議で自分が追放されず生き残った場合。その後の本人の生死を問わず、妖狐以外のあらゆる勝利に便乗して勝利

復讐のターゲットを人の目の前で切って即通報でもう勝利って問題が解決してないような気がしますがどうなんでしょうか

> 他人にキルされた場合ですか…。復讐対象をキルしたプレイヤーを新たな復讐対象にする（アサシンを除く）とどうでしょうか。

負け筋が少なくなるような気がしますがどうなんですかね

**Comment by melonjagaimo** [comment]
切って即通報だと「インポスター陣営がアヴェンジャーを騙っている」ことも考えられます。
またキルしても直後の会議で追放されてしまうと勝利できません。

復讐対象の変更はなしですね。

**Comment by yukieiji** [comment]
> 切って即通報だと「インポスター陣営がアヴェンジャーを騙っている」ことも考えられます。
またキルしても直後の会議で追放されてしまうと勝利できません。

人がいるところでキルをする時点でこの役職ではない可能性を探す方が難しいのでは？
切って即通報、黒点が高かったらスキップして即ボタンを押して次の会議で吊れば良いんじゃないんですかね
黒点が高くなかったらそれでスキップで良いのでは？

**Comment by melonjagaimo** [comment]
では、「便乗するのではなく復讐を果たした瞬間に単独勝利する」に変更した場合はどうなるでしょうか。

**Comment by yukieiji** [comment]
> では、「便乗するのではなく復讐を果たした瞬間に単独勝利する」に変更した場合はどうなるでしょうか。

アリスみたいに防ぎようがあるなら話は別ですけど、他の人から防げないそれは理不尽すぎるでしょう？

**Comment by melonjagaimo** [comment]
これ以上いい案が出ないのでクローズします
