### ISSUE TITLE
[インポスター/Impostor] : アンダーワーパー/UnderWarper (覚醒する最強のベント使い)

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#184]
### 役職名 / Role Name
？？？

### 役職の色 / Role color
インポスターレッド

### 役職の説明 / Role description
- ベント周り最強のインポスター
  - ベントアニメーション等が再生されず、ほぼ確定でベントを使用できるため覚醒役職とする
  - 役職も能力も指定開始数キル後の会議終了後 + インポスター人数で確定

### 役職の能力 / Role ability

- これらの能力はカスタムベントの「陣」には影響されない
- パッシブ能力「？？？」
  - MiraHQと同じく全てのベントが接続される
  - オプションで「カーペンター」で塞いだベントに入る or 移動できる
- パッシブ能力「？？？」
  - ベントに出入り、ベントの開閉に関してアニメーションが一切表示されない
- パッシブ能力「？？？」
  - ベントの使用距離が伸びる
  - オプション設定可

### 他陣営への影響 / Effect on other teams
- インポスター以外：ベントに関する常識がこの役職では通用しなくなる、またラストウルフと異なりどれくらいでどの強さになってるかが推測しにくい

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by melonjagaimo** [comment]
役職や能力の名前の案です。
役職名「ベントエキスパート」

全ベント接続能力「ベント内隠し通路」

アニメーションなしの出入り「サイレントベント」

使用距離が伸びる「ベントダイブ」
