### ISSUE TITLE
[インポスター/Impostor] : ヒプノティスト/Hypnotist (覚醒することで強化出来る仲間を作ることが出来るインポスター)

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#186]
### 役職名 / Role Name
未定

### 役職の色 / Role color
インポスターレッド

### 役職の説明 / Role description
- 覚醒役職
  - インポスターの生存者数が1人になったあと、以下のいずれか条件を満たした時
    - クルー全体のタスク進捗率60％以上
    -  指定回キルを行ったあとの会議終了後

### 役職の能力 / Role ability

- ボタン能力「催眠術」
  - 目標一人に対して使用する
  - 目標の役職をリセットし「ドール」にする
  - リセット時マップ上に「能力のかけら」が設置される(復活しない、位置はランダム)
    - 「能力のかけら（レッド）」：「ドール」に一定秒数キルボタンを生やす、生えている場合、「ドール」のキルクールタイム減少
    - 「能力のかけら（ブルー）」：「ドール」のマップモジュールを一つ解禁(永続)
    - 「能力のかけら（グレー）」：「ドール」にクラッキング能力の1モジュールを付与(永続)
    - 「能力のかけら（グレー）」と「能力のかけら（ブルー）」は固定設置
    - 「能力のかけら（レッド）」は初期設定個数 + 元役職のインターフェースの個数等によって設置個数は変化する
      - IRoleVoteModifier > IRoleMeetingButtonAbility > IRoleAwake > IRoleAbility > IRoleOnRevive > IRoleMurderPlayerHock > IRoleUpdate > IRoleReportHock
    - 「能力のかけら」は他の人から見えない
  - ヒプノティストが死ぬと「ドール」も死ぬ

- 役職「ドール」
  - ニュートラル陣営、勝利条件：インポスターの勝利条件を満たすこと
  - ベント、タスク、全てのマップモジュールにアクセスすることができない
  - 「能力のかけら」によって強化される
  - 上のヒプノティストが死ぬと死ぬ

### 他陣営への影響 / Effect on other teams
- クルー：強い役職は強い「ドール」になりやすいのでCOはしにくい(サーヴァントと違って能力は引き継がれない) + インポスターが1人に残っても油断できない。またこの役職は「能力のかけら」を集めるためにとても浮くので吊りやすい
- ニュートラル：キルペースを上げることでこの役職をとっとと落としたい

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by melonjagaimo** [comment]
1つ質問があります。
能力のかけらを探すのはヒプノティストですか？それともドールですか？

**Comment by yukieiji** [comment]
>「能力のかけら」は他の人から見えない　と　この役職は「能力のかけら」を集めるためにとても浮くので吊りやすい

って書いてあります

**Comment by melonjagaimo** [comment]
つまりヒプノティストが能力のかけらを使ってドールを強化する、でよろしいのですね？

**Comment by yukieiji** [comment]
そうです
