### ISSUE TITLE
未定：インポスター役職(役職&能力偽装)

### ISSUE THREAD

**Issue by UzomuZo** [yukieiji/ExtremeRoles#19]
### 役職名 / Role Name
ドッペルゲンガー、ミミック、エミュレーター、ペルソナなど
### 役職の説明 / Role description
役職を騙ってクルーを追い詰める

### 役職の能力 / Role ability

・試合開始時に配役されるクルー役職のいずれかが選ばれ、役職偽装発動中にそのクルー役職の能力が使用可能になる。
・ラバーズは選ばれない。
・偽装中はクルーの視界＆移動速度で名前がクルーと同色になり、インポスター仲間からのキルの対象となる。

メリット
・役職COによる白確定ができなくなる。
・偽装中はシェリフからキルされない。

デメリット
・仲間がごちゃキル、キル連打すると誤ってキルされる。
・偽装中はキルできないのでキルペースが落ちる。
・偽装してからクールタイムが経過しないと戻ることはできない。

### 他陣営への影響 / Effect on other teams
・ジャッカルがいる場合、サイドキックと間違われてキルされる。
・パン屋死亡後にパン屋に偽装して会議に入るとパン屋のメッセージが復活する？

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
この役職には以下の問題点があると思います
- 実装的な部分の問題点
  1. 役職を能力を使っているときだけ役職を追加するみたいな作りはしていないため、この役職自体が実装できるかわかりません
      - 特にパン屋を追加してまた削除とか言うことは考慮して作ってないです
      - また、有害な陣営から無害な陣営に変化する(逆は問題ないと思いますが)ということは考慮して作ってないです 
- バランス的な問題点
  1.  クルーの能力は基本クルー有利、インポスターが不利になるように作られているはずなので、インポスターが使ってメリットは無いと思われます
     - ニートやボディーガード、マーリンのようにインポスターが全く使えないようなクルー役職を引いた場合、無力になると思われます
  2. 役職COした人が複数人居た場合ローラーすればいいので、この役職はむしろデメリットになっている気がします
    - 結局、役職を語るのと違う部分が見えてこないです

**Comment by UzomuZo** [comment]
なるほど、たしかに自分は気づいてなかったですがいろいろと問題がありそうです。
全てを解決する案が思い浮かびそうにないので閉めておきます。
