### ISSUE TITLE
[インポスター陣営/Impostor＆クルー陣営/Crew_コンビネーション役職] : 勇者と魔王 (人々を守る光の戦士と全てを滅ぼす闇の帝王)

### ISSUE THREAD

**Issue by seono968** [yukieiji/ExtremeRoles#191]
役職提案者からの依頼で代理投稿となります。
以降のやり取りも基本当方が行います、レスポンスに間が空くかと思いますがよろしくお願いします。

### 役職名 / Role Name
勇者/Warrior of Right

### 役職の色 / Role color
黄色

### 役職の説明 / Role description
魔王とのコンビネーション役職(対立)

### 役職の能力 / Role ability
タスクをn個完了するかx回会議が終わるまでは1度だけ自身へのキルを防ぐ加護を受けている。
またタスクをm個完了させると周囲の人(勇者含め)を一定時間キルから守るバリアを展開できるようになる。

### 他陣営への影響 / Effect on other teams
コンビである魔王(後述)に倒されると魔王が能力を得るためタスクの順番に気を付ける事や、序盤は自身を終盤は周囲の人をキルから守るため人外がキルをしにくい。

### 陣営 / Team
- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

────────────────────────────────────

### 役職名 / Role Name
魔王/Emperor of Darkness

### 役職の色 / Role color
赤

### 役職の説明 / Role description
勇者のコンビネーション役職
勇者と倒すまでは通常のインポスターと同じ性能だが、勇者を倒すと勇者のオーラで使えなかった瘴気を操る能力を解放できる。

### 役職の能力 / Role ability
最初は勇者のバリアを貫通する能力しかないが(加護は破れない)、勇者を倒すと能力が解放される。
(相方も勇者がわかるが相方が勇者を倒すと能力解放はされない)
☆解放される能力の説明――――――――――
キルボタンがなくなり常時発動の"瘴気"スキルに代わる
♤♤♤瘴気♤♤♤
20秒間(設定による)近くにいた人を会議になると一度にキルする(TORのペストみたいにメーターが進んでいき、感染状態のようになると死ぬ)
また湧きから10秒は瘴気を発さない

### 他陣営への影響 / Effect on other teams
覚醒ができればほぼ勝利である(即勝利にしていないのは覚醒されてもキルを詰めれば他の陣営も勝機を見出だせるため)

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
バランスの話の前に役職の仕様の確認です
- 加護とバリアの違いは何でしょうか
  - 両方とも効果的にはキルを防ぐという同じ書き方がされてますが名前が別々の書き方になってるのでエフェクトとか効果時間が違うという形ですか
- 会議になると一度にキルをするということは開始時に全員をキルをする形ですか？それとも会議中に順番に一人ずつキルをする形ですか
- TORのペストみたいにメーターが進んでいき感染状態のようになると死ぬとありますが、ペスト見たく伝染すると言う形ですか？

**Comment by seono968** [comment]
＞＞加護とバリアの違いは何でしょうか
加護…魔王からでも1度だけkillが防がれ、勇者単体しかkillを防がない
バリア…魔王のkillは防げない、近くにいる人と自身をkillから守る

＞＞会議になると一度にキルをするということは開始時に全員をキルをする形ですか？それとも会議中に順番に一人ずつキルをする形ですか
会議になったタイミングで同時killを想定しております

＞＞TORのペストみたいにメーターが進んでいき感染状態のようになると死ぬとありますが、ペスト見たく伝染すると言う形ですか？
魔王に近づかなければ瘴気を多く吸った人の近くにいても死にません、ペストと書きましたが占い師のようなシステムの方が近いです

**Comment by yukieiji** [comment]
> 加護…魔王からでも1度だけkillが防がれ、勇者単体しかkillを防がない
バリア…魔王のkillは防げない、近くにいる人と自身をkillから守る

エフェクト等は全く発生しない(ボディーガードと一緒)と言う考え方で大丈夫でしょうか、また防いだ後のキルクール周りはリセットされるのでしょうか？

**Comment by seono968** [comment]
加護は一律KCTリセット、バリア内だと魔王以外はkillボタンを押せません
また、どちらのシールドが発動してもSNRのスタントマンのように勇者にkill通知はいきません

**Comment by yukieiji** [comment]
> 加護は一律KCTリセット、バリア内だと魔王以外はkillボタンを押せません

展開されたバリアは設置されるということでいいですか？それとも常に周りに存在するということですか？

> また、どちらのシールドが発動してもSNRのスタントマンのように勇者にkill通知はいきません

勇者に通知が行かないということは加護が発動したときはキルした人には分かるということでいいですか？

**Comment by yukieiji** [comment]
> バリアは勇者の周囲に存在するカタチです
加護(1度しかkillを防げない)を破った際にはkillerはKCTのリセットで加護を破ったとわかります

わかりました

以下バランス的な部分の話です
全体的に勇者がヒーローの上位互換になっていて第三陣営に対して刺さりすぎてる感じがします
第三陣営に刺さりすぎててマイナー、ジェスター、アンブレイヤー、ミッショナリー以外対処できないのは問題だと思います
実際大本のヒーロは第三陣営にも無敵でしたが刺さりすぎてるのでなしになったはずです

魔王は勇者に対して刺さってるけど勇者が魔王に対してあんまり刺さってないような気がします

> 加護は一律KCTリセット、バリア内だと魔王以外はkillボタンを押せません
また、どちらのシールドが発動してもSNRのスタントマンのように勇者にkill通知はいきません

キルボタンを押せなくなるとクールタイムも止まるのでバリアが張られて魔王が落ちてると他の役職が何もできなくなっているような気がします

> タスクをn個完了するかx回会議が終わるまでは1度だけ自身へのキルを防ぐ加護を受けている。
またタスクをm個完了させると周囲の人(勇者含め)を一定時間キルから守るバリアを展開できるようになる。

この部分で思ったのは最初にタスクをする意味がないような気がしますがどうでしょうか
初期は全くタスクせずに会議で黒を釣って、加護がなくなってからタスクをしてもいいように見えます(mの個数によりますが黒が釣れればm個完了させることも難しくはない気がします)

> コンビである魔王(後述)に倒されると魔王が能力を得るためタスクの順番に気を付ける事や、序盤は自身を終盤は周囲の人をキルから守るため人外がキルをしにくい。

魔王に付与される能力がそんなに強くないので気にしなくていいような気がします

> 最初は勇者のバリアを貫通する能力しかないが(加護は破れない)、勇者を倒すと能力が解放される。
(相方も勇者がわかるが相方が勇者を倒すと能力解放はされない)
☆解放される能力の説明――――――――――
キルボタンがなくなり常時発動の"瘴気"スキルに代わる
♤♤♤瘴気♤♤♤
20秒間(設定による)近くにいた人を会議になると一度にキルする(TORのペストみたいにメーターが進んでいき、感染状態のようになると死ぬ)
また湧きから10秒は瘴気を発さない

開放される能力がそこまで強いとは思えないのですがどうでしょうか
20秒も接触することはないですし視認情報が無駄に出る + キルボタンが無いのでシェリフにも勝てなくなってますから

> 覚醒ができればほぼ勝利である(即勝利にしていないのは覚醒されてもキルを詰めれば他の陣営も勝機を見出だせるため)

覚醒したほうが弱くなってるような気がしますがそれで勝利とはいえないような気がします
