### ISSUE TITLE
[クルー陣営] : スパイ (インポスター陣営に潜入し、タスク完了で情報を盗む)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#192]
### 役職名 / Role Name
スパイ

### 役職の色 / Role color
赤橙

### 役職の説明 / Role description
インポスター陣営に潜入して諜報活動を行うクルー陣営
タスクを一定量完了するまでインポスター陣営から名前が赤く見える
タスク完全完了でインポスター陣営のプレイヤーを把握

TORのスパイとスニッチをもとに考案した。

### 役職の能力 / Role ability

・スパイがアサインされた場合の陣営発表時、インポスター陣営の視点では本来のインポスターに追加でスパイの人が表示される。スパイ本人の視点ではクルー陣営として表示される。

・スパイは初期状態ではインポスター陣営から見た名前が赤く表示される。
しかし、この状態でもインポスター陣営のキルや能力の対象になる。

・スパイは以下の条件のうちいずれかを満たすとインポスター陣営から見た名前が白くなる。
１：スパイ本人のタスク進捗率がオプションで決められた割合になる。この時、スパイには「あなたがスパイだとインポスター陣営にバレた」と通知が入る。
２：死亡する
３：サイドキックなど、前の役職の能力を引き継がない役職になる

・スパイがタスクをすべて完了させると「諜報」能力が発動し、スパイはインポスター陣営のプレイヤーをランダムにオプションで指定された人数だけ把握する。オプションによっては発動時に死亡しているインポスターも諜報能力の対象になる。
死亡しているインポスターを諜報の対象にしない設定でかつ諜報能力の発動時にインポスター陣営が全滅していた場合、その旨がスパイに通知される。

#### 固有オプション
スパイがバレるタスク進捗率（デフォルトでは75％程度を想定）
死亡したインポスターを諜報の対象にする（オン/オフ）
諜報能力で把握するインポスターの人数（デフォルトでは1人を想定）

#### メリット
タスクを完了するとインポスター陣営を把握できる

#### デメリット
インポスター陣営を把握する前にインポスター陣営にバレる
把握されないように動くと浮き位置になりやすくなったり、タスク勝利が厳しくなる

### 他陣営への影響 / Effect on other teams
インポスター陣営：味方だったはずのプレイヤーの名前が白くなった場合、スパイの可能性があるので積極的に粛清に向かうことが予想される。
また、吊られそうになった人外がタスクを完了したスパイを騙り、クルーを道連れにしようとするかもしれない。

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
バランスの都合上実装を見送っているスパイをさらに強化する意味はあまりないような気がします

> スパイがバレるタスク進捗率（デフォルトでは75％程度を想定）

スパイがタスクをする必要がなくなると思うのですが

**Comment by melonjagaimo** [comment]
スパイがタスクをしなくなる問題の解決案として「タスク進捗ではなく会議経過数でバレるようにする（急いでタスクをしないとバレる）」のはどうでしょうか。

そして、スパイがインポスター陣営にキルされた場合にすべてのインポスターのキルクールタイムが永続で減少する（スパイ粛清で士気向上）デメリットを追加するということも浮かびました。

**Comment by yukieiji** [comment]
> スパイがタスクをしなくなる問題の解決案として「タスク進捗ではなく会議経過数でバレるようにする（急いでタスクをしないとバレる）」のはどうでしょうか。

タスクの進みは人それぞれなのにそれを一概にオプション値で決定するのはどうなのでしょうか

> そして、スパイがインポスター陣営にキルされた場合にすべてのインポスターのキルクールタイムが永続で減少する（スパイ粛清で士気向上）デメリットを追加するということも浮かびました。

デメリットがでかすぎてスパイがクルーのお荷物になってる気がします

**Comment by melonjagaimo** [comment]
これ以上の改善案が浮かばないのでクローズします
