### ISSUE TITLE
Hypnotist.cs の恐らくスペルミス

### ISSUE THREAD

**Issue by piropirohiko** [yukieiji/ExtremeRoles#196]
## バグの情報 / Info of bug
恐らくHookと書くべき所がHockになっているため、役職のインターフェースを取得で「能力のかけら（赤）」が追加設置される個数に誤差が生じる。

### 期待される動作 / Your Expectation
                    case "IRoleMurderPlayerHook":
                        addNum = 4;
                        break;
                    case "IRoleUpdate":
                        addNum = 3;
                        break;
                    case "IRoleReportHook":
                        addNum = 2;
                        break;

### 実際の動作 / The Reality
                    case "IRoleMurderPlayerHock":
                        addNum = 4;
                        break;
                    case "IRoleUpdate":
                        addNum = 3;
                        break;
                    case "IRoleReportHock":
                        addNum = 2;
                        break;
https://github.com/yukieiji/ExtremeRoles/search?q=Hock

### このバグに対するあなたの意見 / Your Proposal
恐らくスペルミス

### Among Usバージョン/ Among Us Version

Among Us v

### Modバージョン / Mod Version
Extreme Roles v3.30.2

Extreme Roles v

### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [ ] :アジア/Asia
- [x] :カスタム/Custom

### 最終チェックリスト
- [ ] : このバグは記載されている手順通りに操作し、ほぼ同じ条件下で再度発生することを確認した
- [x] : GitHubのチケットを検索し同様のIssuesが無いことを確認した

**Comment by yukieiji** [comment]
v3.3.0.3で修正済み
