### ISSUE TITLE
ヒプノティストの「能力のかけら青」がAirship船外右下に配置される

### ISSUE THREAD

**Issue by piropirohiko** [yukieiji/ExtremeRoles#197]
## バグの情報 / Info of bug
ヒプノティストの青い矢印がバイタル右下の船外を指し示しています。

### 期待される動作 / Your Expectation
「能力のかけら青」が船内に配置される。

### 実際の動作 / The Reality
10/16のじょかあきさんアーカイブの52:37でバイタル右下へ、52:43でバイタル右上ドア真下へ青い矢印が指し示しています。
https://youtu.be/7Pf1fiHtfLg?t=3156

### このバグに対するあなたの意見 / Your Proposal
恐らく座標ミス。

### Among Usバージョン/ Among Us Version

Among Us v2022.9.20s

### Modバージョン / Mod Version

Extreme Roles v3.3.0.2

### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [ ] :アジア/Asia
- [x] :カスタム/Custom

### プレイヤー人数/Player Num
15

### 最終チェックリスト
- [ ] : このバグは記載されている手順通りに操作し、ほぼ同じ条件下で再度発生することを確認した
- [x] : GitHubのチケットを検索し同様のIssuesが無いことを確認した

**Comment by yukieiji** [comment]
セキュリティカメラの青がそこに設置されていたっぽいので、別の座標に変更しました(なぜそこに設置したのかは謎です)

**Comment by yukieiji** [comment]
v3.3.0.3で修正済み
