### ISSUE TITLE
[インポスター/Impostor] : Madman (自殺、インポスターをキルできるインポスター)

### ISSUE THREAD

**Issue by majiponi** [yukieiji/ExtremeRoles#198]
### 役職名 / Role Name
裏切者/Traitor改めMadman

### 役職の色 / Role color
赤/Red

### 役職の説明 / Role description
自殺、インポスターをキルできるインポスター。シェリフを騙りやすい。/They can kill anyone, including themselves and other Impostors.  They can pretend like a Sheriff.

### 役職の能力 / Role ability
自殺コマンドは、通常のキルクールが明けていなくても使えます。/They can suicide even if they killed somebody just right now.

### 他陣営への影響 / Effect on other teams
なし/Nothing

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
トレイターと言う役職はもう存在するのですが

**Comment by majiponi** [comment]
では、Madmanではどうでしょう? Madmateではなく、ただのやべーやつです。

**Comment by yukieiji** [comment]
役職名はそれで問題ないと思いますが、能力的にメリットが無いような気がしますがどうでしょうか
シェリフが語りやすい役職としてラストウルフとかマッドメイトもありますがそこまで機能していないってことを考えるとちょっとって思ってます
