### ISSUE TITLE
妖狐:ニュートラル陣営

### ISSUE THREAD

**Issue by Nushigami** [yukieiji/ExtremeRoles#2]
内容は現在のものです。
### 役職名 / Role Name
妖狐
### 役職の色 / Role color
紫苑色(色コード:867ba9)
### 役職の説明 / Role description
勝利条件:他陣営の勝利条件達成時代わりに単独勝利
視界はインポスター並 ベントは使用不可
能力の取り憑くでキルから身を守れる
### 役職の能力 / Role ability

取り憑く
他プレイヤーを"取り憑かれた状態"にする。
妖狐がキルされると代わりに取り憑かれた状態のプレイヤーが死亡してしまう。
(複数いた場合はランダムに１人死んでしまう。また吊られた場合は発動しない)
### 他陣営への影響 / Effect on other teams
妖狐はどの陣営からも敵になる存在です。
### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
要望ありがとうございます。以下気になる点です

> また妖狐化したプレイヤーは自身が妖狐化していることには気づかない。

これは基本無理です、基本的に役職を置き換える形になります。基本的に誰がどの役職に属しているかってのが分かるような処理になっています。元の役職の能力を引き継ぐなら妖狐化(役職名がわからないんですが)自体をマルチアサイン可能な役職にするっていう手段もあるのですが基本的元々マルチアサイン可能な役職をどうするかという問題が発生してきます
「妖狐化」を属性として扱うことは現状は考慮されているような設計ではないです(多大な改修が必要になってバグの原因になりそうです)

> クルータイム少なめがいいと思います。

ボタンのクールタイムは全職一括で30秒がデフォルトで設定されます

役職全体として気になる点は道士自体は妖狐専用のカウンターになってるけど妖狐が道士のカウンターになっていない点でしょうか
妖狐はシェリフにもキルされるし、道士にもキルされるという弱点だらけの職に見えてしまいます

**Comment by Nushigami** [comment]
返信ありがとうございますm(_ _)m
項目１:妖狐化について
妖狐化は、職業ではなく状態って言った方が近いです。また陣営も変わりません。(ボマーのボムがついている状態的な感じです。)

項目２ クールタイムについて
ボタンって会議ボタンのことでしょうか?(分からない)

項目３:妖狐の道士への対抗について
妖狐の道士への対抗は妖狐化のつもりです。
妖狐化によって道士に無駄に陣営を減らさせるというような感じです。
最初は能力を使いすぎると死ぬっていうのを考えたのですが、、、クールタイムと迷ったのでクールタイムの方を選んだ感じです。

項目４:妖狐の事
妖狐はシェリフでは切れません。
切ったあとのシェリフが生き残るかどうかは、設定で切り替えてもいいかもしれません。
(妖狐が死ぬのは吊りや、道士の能力、ラバーズ等のシステムのみ)

**Comment by Nushigami** [comment]
補足:能力を使いすぎて死ぬのは道士の方です。

**Comment by yukieiji** [comment]
> 妖狐化は、職業ではなく状態って言った方が近いです。また陣営も変わりません。(ボマーのボムがついている状態的な感じです。)

妖狐化したプレイヤーはただの変わり身ってことでしょうか

> ボタンって会議ボタンのことでしょうか?(分からない)

能力のボタンです

> 妖狐の道士への対抗は妖狐化のつもりです。
妖狐化によって道士に無駄に陣営を減らさせるというような感じです。
最初は能力を使いすぎると死ぬっていうのを考えたのですが、、、クールタイムと迷ったのでクールタイムの方を選んだ感じです。

妖狐化によって陣営が減って困るのはインポスターや他のニュートラルだけではないでしょうか、クルーの道士的にはデメリットは少ない気がします(最大クルー2人が落とされてそこまで困ることはないでしょう、クルーは10人もいますし(ローラーもクルーなら普通にやりますし))

> 妖狐はシェリフでは切れません。
切ったあとのシェリフが生き残るかどうかは、設定で切り替えてもいいかもしれません。
(妖狐が死ぬのは吊りや、道士の能力、ラバーズ等のシステムのみ)

シェリフで切れなくした理由は何でしょうか

**Comment by Nushigami** [comment]
項目１について
はい、ただの変わり身、、、というかそのプレイヤーが本当に妖狐だったかをわからなくさせるためです。

項目２:ボタンについて
要は初期設定は決まっているということですね。

項目３について
それもそうか、、、
道士にカウンターできない代わりに道士を弱くするくらいしか思いつきません。
(思いついたらなんか書いときます。)

項目４:妖狐がシェリフで切れない理由
元の人狼ゲームでの妖狐の死亡条件が、占い師に占われる、または吊られることです。
この２つの条件のみなのでシェリフでは切れません。
(ラバーズで相方が死んだのに死なないのは話が違うと思うのでさすがに殺しますが、、、)

追記
インポスター等にキルできないって言われたらまずいからそれも対策しないといけないかも、、、(重大な欠点)

**Comment by yukieiji** [comment]
> 項目４:妖狐がシェリフで切れない理由
元の人狼ゲームでの妖狐の死亡条件が、占い師に占われる、または吊られることです。
この２つの条件のみなのでシェリフでは切れません。
(ラバーズで相方が死んだのに死なないのは話が違うと思うのでさすがに殺しますが、、、)
追記
インポスター等にキルできないって言われたらまずいからそれも対策しないといけないかも、、、(重大な欠点)

インポスターにすらキルされないようになっているということでしょうか

**Comment by Nushigami** [comment]
項目１:キルできるかについて
はい 本家もキルできないので

**Comment by yukieiji** [comment]
> はい 人狼ゲームでもキルできないので
※妖狐の役職説明の勝利条件の下にキル役職にキルされないって記入していますね。

そうなると別の第三陣営(ジャッカル見たく増やせないようなもの)とかはどうやって妖狐を処理すれば良いのでしょうか

**Comment by Nushigami** [comment]
項目１:他の第三陣営がどうやって妖狐を処理するのか
基本的に吊るか、道士がキルしてくれるしかありませんね、、、

**Comment by yukieiji** [comment]
> 項目１:他の第三陣営がどうやって妖狐を処理するのか
基本的に吊るか、道士がキルしてくれるしかありませんね、、、

道士が落ちてる状態で1on1になった場合はどうしますか

**Comment by Nushigami** [comment]
項目１:１on１になった時
妖狐は第三陣営なので１on1になることはないと思いますが、、、

**Comment by yukieiji** [comment]
> 妖狐は第三陣営なので１on1になることはないと思いますが、、、
ミッショナリーと妖狐等を混ぜれば1 on 1になることはあります

**Comment by Nushigami** [comment]
項目１について
ミッショナリーに関しては妖狐はキルを持たない無害な第三陣営扱いで、ミッショナリーの勝利条件が達成してそのまま妖狐が勝ちますね。
アリスは１on1になってしまいますが、、、どちらかの勝利条件を変えるしか方法がなさそうですね、、、

**Comment by yukieiji** [comment]
> ミッショナリーに関しては妖狐はキルを持たない無害な第三陣営扱いで、ミッショナリーの勝利条件が達成してそのまま妖狐が勝ちますね。
他の勝利条件を乗っ取れる以上、ミッショナリーに勝ち目がないのでは

> アリスは１on1になってしまいますが、、、どちらかの勝利条件を変えるしか方法がなさそうですね、、、

アリスもそうですが、次期実装のヤンデレもキル能力を持って対処することが出来ないってのはちょっと
第三陣営間での殺し合いで最強になれてしまうのはAmongUs的に問題な気がします、これは人狼ではなくAmongUsなのでキルできなくするにこだわる必要もないと私は思います

**Comment by Nushigami** [comment]
設定で第三陣営からキルされる項目を追加するというのは?(さすがにキルされるようになると劣化アリスなので)
(1on1になる前にクルーローラーで死にそうだが)

**Comment by yukieiji** [comment]
> 設定で第三陣営からキルされる項目を追加するというのは?(さすがにキルされるようになると劣化アリスなので)
(1on1になる前にクルーローラーで死にそうだが)

元々キルできるようにするのは元ネタの人狼で殺されない以外、何か問題(バランス的に)がありますか
劣化アリスではないでしょう、あれは勝利条件も能力も全く違いますし

**Comment by Nushigami** [comment]
あ、キルボタン持ってないです

**Comment by Nushigami** [comment]
キルされるようになるとキルされたら勝てるアリスの方が強いようなと思いましたが妖狐は他の勝ち方があったか、、、
キルできなくするのは単独勝利する都合上どの陣営からも狙われるわけです。(他陣営はもちろん勝ちたいわけで)
少しでも生存できるようキルされないようにしたのです(あとTORのオポチュニストみたいに協力できないからさらに死にやすい)

**Comment by yukieiji** [comment]
> キルされるようになるとキルされたら勝てるアリスの方が強いようなと思いましたが妖狐は他の勝ち方があったか、、、

アリスはインポスターにキルされたら勝利なので他の陣営等にキルされたら負けです。
生きていればありとあらゆる勝利(アリスやジェスターの特殊勝利)を乗っ取ることが出来るのを考えれば、妖狐は第三陣営の中で一番強いと思っています
それでなおかつキルできないのと身代わりを持つことを考えれば妖狐に他の陣営が勝つことはほぼ不可能だと思われます。(道士が落ちたらクルーですら抵抗することが難しくなる(浮き位置に建たなければ吊られることはないでしょう))

> 少しでも生存できるようキルされないようにしたのです(あとTORのオポチュニストみたいに協力できないからさらに死にやすい

生存を意識することを目的とするならシステムで保護するより、プレイによって達成できる方がゲーム性が保てると思います
例えばキルされるようになる代わりに、身代わりを持てて、全てのクルーの位置が矢印で表示されるとかでしょうか(もうそうなると道士すら要らない気がしますが)

**Comment by Nushigami** [comment]
正直無敵にこだわりすぎたかもしれませんね、、、
(出来ればインポスター陣営だけにキルされないくらいはあって欲しかったけど､､､)
能力については道士を消して妖狐化の能力を変えるって感じにしますか、、、(道士は妖狐をそのままで登場させた場合だと強すぎると思ったので占い師的立場で登場させた感じです。)
身代わりはいいと思いますが、全クルーの位置がわかる状態だと画面がわちゃわちゃしちゃうのでは?

**Comment by yukieiji** [comment]
> 身代わりはいいと思いますが、全クルーの位置がわかる状態だと画面がわちゃわちゃしちゃうのでは?

死体は表示されないようにするとか色々とあると思います。あくまで私のは例なので微妙だなーって思ったら別に考えて頂いても構いません
道士自体も消さずにいい感じに残していただいても構いません

**Comment by Nushigami** [comment]
最終的にこんなんでどうでしょうか?
### 役職名 / Role Name
妖狐
### 役職の色 / Role color
紫苑色(色コード:867ba9)
### 役職の説明 / Role description
勝利条件:他陣営の勝利条件達成時代わりに単独勝利
視界はインポスター並 ベントは使用不可
能力の取り憑くでキルから身を守れる
### 役職の能力 / Role ability

取り憑く
他プレイヤーを"取り憑いた状態"にする。
妖狐がキルされると代わりに死亡してしまう。
(複数いた場合はランダムに１人死んでしまう。)
### 他陣営への影響 / Effect on other teams
妖狐はどの陣営からも敵になる存在です。
### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [妖狐] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
特に問題はないです、新しくissueを作って下さい

**Comment by yukieiji** [comment]
> 取り憑く
他プレイヤーを"取り憑かれた状態"にする。
妖狐がキルされると代わりに取り憑かれた状態のプレイヤーが死亡してしまう。
(複数いた場合はランダムに１人死んでしまう。また吊られた場合は発動しない)

これは何回でも使える能力という形でいいですか？

**Comment by Nushigami** [comment]
試合前に決められた回数ですね

**Comment by Nushigami** [comment]
１か２回ですかね  ３回だと多すぎるかな?
(まぁ告発された瞬間に終わるんですが、、、)

**Comment by yukieiji** [comment]
> (まぁ告発された瞬間に終わるんですが、、、)

それを欠点とするか対処するかですね

**Comment by Nushigami** [comment]
例えば自分を食べようとした人をキルするとかですね、、、ただそれだと強すぎる気がしますが、、、

**Comment by yukieiji** [comment]
> 例えば自分を食べようとした人をキルするとかですね、、、ただそれだと強すぎる気がしますが、、、

逆襲系を考えるのならばアサシンを逆襲してしまったときのパターンを考えてほしいです
アサシンが吊り以外で死んだ時の処理は結構面倒くさいので

**Comment by Nushigami** [comment]
じゃあ取り憑くじゃない能力を考えた方が良さそうなのかな、、、例えば能力使用時にインポスターの位置がわかるとか、、、

**Comment by Nushigami** [comment]
TORに妖狐が追加されてたのか、、、

**Comment by yukieiji** [comment]
タイトルも変更するならissueの内容も変更して下さい

**Comment by Nushigami** [comment]
始めたばっかでやり方が分からない(ごめんなさい)

**Comment by yukieiji** [comment]
issueの右上の・・・のEditから更新して下さい(できれば調べても欲しいです)

**Comment by Nushigami** [comment]
ごめんなさいm(_ _)m

**Comment by Nushigami** [comment]
これでいいでしょうか？

**Comment by yukieiji** [comment]
はい問題ないです。あとここはTwitterではなく役職に関する議論の場なのでこのコメントも含めて20時頃不必要なコメントを削除します

**Comment by Nushigami** [comment]
TORの妖狐が実装されているらしいので参考になるかも
https://wikiwiki.jp/amasmod/TheOtherRoles-GM%E7%AC%AC%E4%B8%89%E9%99%A3%E5%96%B6#hb5cddc4

**Comment by yukieiji** [comment]
> TORの妖狐が実装されているらしいので参考になるかも
https://wikiwiki.jp/amasmod/TheOtherRoles-GM%E7%AC%AC%E4%B8%89%E9%99%A3%E5%96%B6#hb5cddc4

それを私に言われても困ります。強いて意見を言うなら背徳者はいらないのでは？という感想

**Comment by Nushigami** [comment]
返信が遅れてすいません

> それを私に言われても困ります。

TORで、実装されたってことはしっかり調整されていると思うのでこれを参考にするのも手じゃないかと、、、
(それにTORに追加されたのも最近ですし)

**Comment by yukieiji** [comment]
> TORで、実装されたってことはしっかり調整されていると思うのでこれを参考にするのも手じゃないかと、、、

それを参考に役職の案を考えるのはNushigamiさんです。私はそれに対して出来るできない、バランス的にどうなのかとかは言います(私は他のMODと比較してどうこうってのは言いません、EXロールはEXロールなので)

**Comment by Nushigami** [comment]
TORにもあったのですがサボタージュを直せないのはいいと思うのですが、、、
ただTORでは占い師とセットだったからどこか変えないといけないですね、、、
(ただタスクをする第三陣営だとタスクマスターがいるからタスクはなしがの方がいいのかな？って)

**Comment by Nushigami** [comment]
すいません返信と被っちゃいましたね、、、

> それを参考に役職の案を考えるのはNushigamiさんです。私はそれに対して出来るできない、バランス的にどうなのかとかは言います(私は他のMODと比較してどうこうってのは言いません、EXロールはEXロールなので)

確かにそれはそうですが、、、
実際に参考にできるものがあれば製作者もダメだしとかしやすいかなぁって思ったのもありますね、、、
それに自分自身もTORと全く同じようにはするつもりありませんし、、、
(あくまで参考であり比較ではないです)

**Comment by yukieiji** [comment]
> 実際に参考にできるものがあれば製作者もダメだしとかしやすいかなぁって思ったのもありますね、、、
それに自分自身もTORと全く同じようにはするつもりありませんし、、、
(あくまで参考であり比較ではないです)

私はEXロールの「妖狐」という役職が人狼ベースの「妖狐」やTORから考えた「妖狐」である必要はないと思っています(あまりに名前と能力がかけ離れてるとちょっと考えますが)。なので、他のMODの能力や人狼と比べてダメとか、他のMODや人狼はこうだからこうすべきとか言いません。(言ってたら本当に申し訳ないです)
考えるのはEXロールに実装した時のバランスやEXロールの他の役職との噛み合いだけです。

**Comment by Nushigami** [comment]
> 私はEXロールの「妖狐」という役職が人狼ベースの「妖狐」やTORから考えた「妖狐」である必要はないと思っています

よくよく考えると自分は｢妖狐｣っぽいでTORの能力と同列考えていましたね、、、
本当に申し訳ないです。
(ここまでの会話は議論に関係ないと思うので返信があった後消そうと思いますm(_ _)m)

**Comment by Nushigami** [comment]
どうしよう、、、消しちゃっていいのだろうか、、、

**Comment by Nushigami** [comment]
本日20時には消そうと思います。
本当に申し訳ないです。

**Comment by Nushigami** [comment]
20時に消すと言ったものは消しました。

**Comment by yukieiji** [comment]
長時間返信が無いのですが上記意見についてはどうでしょうか

**Comment by Nushigami** [comment]
今のところ妖狐のいい能力案が思い浮かばないんですよね
実装するとしたら
- 緊急サボが直せない。
- タスクをして終わったら勝利を乗っ取れるようにする。
- キル役職を矢印で示す
くらいですかね

**Comment by yukieiji** [comment]
チケットに書いてある内容とズレていますがどちらのほうが優先されるのでしょうか

**Comment by yukieiji** [comment]
> 告発問題はその人の良心かなぁ
他に案があるとすればキルされなくなる透明化とかですかね

インポスターやクルー側からの告発というのは一つの推理に近いところもあると言えばあるので大きな問題ではないと思います
逆に妖狐側からの告発は1つの陣営を終わらせるほど強力なので個人的にそれは避けたいです(実装しても無意味なものになるレベル(アサシン見たく、告発することで勝利が遠のくとか)の物にするべきではないかと思ってます)

> 他の第三陣営の勝利条件に比べて楽だと思ったのでタスクという条件を追加しました感じです。

タスク自体を持たせないという部分でタスク偽造をする必要が出てくるのでそういったプレイングからタスクを持たないほうが難易度事態は上がると思います(タスクをもたせると完全にクルーに紛れやすいので)
TOR見たくキル陣営が完全にわかるようなものは上にもある通り避けたいので、そういった部分を考慮すると生き残るのは難しいはずです

**Comment by yukieiji** [comment]
> 一応妖狐は他プレイヤー共通の敵なので告発したらすぐ吊られると思いますけどね

妖狐からの告発によってインポスター側には一切メリットが無いという点が問題です(アサシンの場合は吊ったことで勝利する可能性もあるので)
妖狐的には告発してゲームをすぐ終わらせて次の試合に行けるメリットはあるが、インポスター的にはせっかくいい試合だったのにすぐゲームリセットされてしまうという点があるので個人的には避けたいです

> 確かに言われればそうか
ただ、キルできない第三陣営の勝利がしずらくなる点をなんとかしないといけないですかね

キルできない第三陣営の勝利には乗っかれないようにするとかですかね

> 難易度をあげると言うならなおのこと「取り憑く」はない方がいいと思います。

能力に関しては別に難易度を上げる必要が無いかなって思ってます
勝利条件の難易度は調整が必要だと思いますが

**Comment by Nushigami** [comment]
> 妖狐からの告発によってインポスター側には一切メリットが無いという点が問題です(アサシンの場合は吊ったことで勝利する可能性もあるので)
妖狐的には告発してゲームをすぐ終わらせて次の試合に行けるメリットはあるが、インポスター的にはせっかくいい試合だったのにすぐゲームリセットされてしまうという点があるので個人的には避けたいです

ではかわりの能力として「常時近くにいるプレイヤーに矢印+能力中は能力の対象にならない透明化」がいいと思います。
(取り憑くに関しては告発問題があるのでなしで)

**Comment by yukieiji** [comment]
> 近くにいるプレイヤーに矢印

近くってどれくらいでしょうか

> 能力中は能力の対象にならない透明化

姿を消すということでしょうか？それともありとあらゆる能力等の対象(ターゲット設定)から外れるということでしょうか

**Comment by Nushigami** [comment]
> 近くってどれくらいでしょうか

インポスターの視界よりちょっと広めくらいですかね
(隠れる能力の補助として)

> 姿を消すということでしょうか？それともありとあらゆる能力等の対象(ターゲット設定)から外れるということでしょうか

姿を消す+ターゲットにならない 効果で

**Comment by yukieiji** [comment]
> インポスターの視界よりちょっと広めくらいですかね
(隠れる能力の補助として)

視界を広くすることと余り変わらないと思うのですがどうでしょうか

> 姿を消す+ターゲットにならない 効果で

ターゲットにならないは実装コストが高いので避けたい感じはします

**Comment by Nushigami** [comment]
> 視界を広くすることと余り変わらないと思うのですがどうでしょうか

壁外のプレイヤーを探知するためな感じです。
矢印の出る範囲をもっと広げてもいいかもしれませんが

> ターゲットにならないは実装コストが高いので避けたい感じはします

キルされてしまうと隠れる意味がないような感じがするのでどうしましょ

**Comment by yukieiji** [comment]
> キルされてしまうと隠れる意味がないような感じがするのでどうしましょ

ターゲットにならないってのは技術的には可能なんですけど実装したらいろいろなことを考え始める必要が出てきてしまう感じです(今実装してる全役職のターゲット判定を書き換える方法を探すとか、ヤンデレの矢印のサーチ系の能力にも引っかからないのか)

逃げるだけが能力ではないので攻撃的な妖狐でも問題ないと言えば問題はないと思います

**Comment by melonjagaimo** [comment]
妖狐の攻撃能力として「妖術」を提案します
・能力を発動して一定時間他のプレイヤーに接近するとそのプレイヤーを同士討ち状態にする（デフォルトは1回きり。同士討ち状態になって初めて回数が消費される）
・同士討ち状態になったプレイヤーに最初に近づいた味方プレイヤーは、同士討ち状態のプレイヤーにキルされるような挙動をとる（同士討ち状態のプレイヤーがキルワープする）。例えばクルーを同士討ち状態にした場合はクルーが近づくとキルされるような挙動を取る。ニュートラル陣営が同士討ち状態になった場合は役職を問わず、最初に接近したニュートラル陣営がキルされるような挙動を取る

**Comment by yukieiji** [comment]
> 同士討ち状態のプレイヤーがキルワープする

これはキルワープをするだけですか？

**Comment by melonjagaimo** [comment]
同士討ち状態にされたプレイヤーがキルワープして、最初に接近したプレイヤーは死にます
側から見ればまるで同士討ち状態のプレイヤーがキルしたように見えます

**Comment by yukieiji** [comment]
能力の説明がわかりにくかったのでいまいち来なかったのですが、ジェスターの「暴発」の強化版ってことで問題ないですか？

違う点
- 秒数発動ではなくその人が近づいたら自動発動
- キル能力を持ってなくても発動する

**Comment by melonjagaimo** [comment]
はい、その通りです
同士討ちさせることで生存者数を減らして決着を早めて勝利を奪いやすくするのです

**Comment by yukieiji** [comment]
> はい、その通りです
同士討ちさせることで生存者数を減らして決着を早めて勝利を奪いやすくするのです

ジェスターの能力と違って人能力を使った後別の人がいる時に発動するってのは難しい気がします

@Nushigami 
私からの能力案です、問題なければ以下で実装します
- 「気配察知」
  - 数秒間隔で自動発動、周囲のプレイヤーにキル陣営が居るかどうかを自動察知する
    - キル陣営の察知には一定の確率で失敗する、また一部の役職は確定察知 or 確定察知失敗
    - 範囲は結構広め、小さくは出来ない(出来ても一部屋分)

**Comment by Nushigami** [comment]
能力に関しては自分的には特に問題ないと思います。
視野設定やサボ・ベント使用をどうするかですが、、、
(個人的には視野はインポ、ベント使用はありでいい気がする。)

**Comment by yukieiji** [comment]
> 視野設定やサボ・ベント使用をどうするかですが、、、
(個人的には視野はインポ、ベント使用はありでいい気がする。)

視野設定は個別設定になります
推理要素が減るのでベントも要らないと思います

**Comment by Nushigami** [comment]
わかりました

**Comment by yukieiji** [comment]
マイルストーンと優先度、プロジェクトをセットし直しました

**Comment by yukieiji** [comment]
開発版にて実装が完了したのでクローズします
