### ISSUE TITLE
ヒットマン(暗殺者)：第三陣営役職

### ISSUE THREAD

**Issue by ghost** [yukieiji/ExtremeRoles#20]
### 役職名 / Role Name
ヒットマン(暗殺者)
### 役職の色 / Role color
濃い灰色系
### 役職の説明 / Role description
「目立つことなく堂々と殺せ」
キルモーション無しに殺せる第三陣営。
### 役職の能力 / Role ability
「密殺」という特殊なキルボタンがある第三陣営。「密殺」は、通常のインポスターなどのキルと違ってキルモーションを伴わずに相手を殺害できるのが特徴。キルできる距離は通常のキル可能範囲よりもやや広い。
クルー陣営及びキル不能な第三陣営が残り一人となるか、自分以外の全員を抹殺することで勝利となる。

モチーフは動画投稿者のジローさん(HITMAN要素)
「絶対に許さないぞあの天然マッドメイト！」
### 他陣営への影響 / Effect on other teams
単に衆人環視の中「密殺」するだけでは、近くにいるヒットマンが真っ先に疑われやすいのであまり意味はない。
しかし、多人数が狭い範囲にいる状況で「密殺」した場合は、ヒットマンの仕業だとは分かっても誰がキルしたのかを詰めるのが難しくなる。その為、所謂「ごちゃキル」の状況で真価を発揮する役職であるといえる。
また、遠隔キルや時間差キルができるインポスターが存在している場合、あるプレイヤーの前で誰かが死んでもそれがヒットマンの仕業か否かの判別が付けづらくなる。

### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [X] :ニュートラル/Neutral

**Comment by issyoukimizu** [comment]
改めて新チケットで投稿いたしました。
ご迷惑をおかけしました。

**Comment by yukieiji** [comment]
> 「密殺」をすると、キルモーションを伴わずに相手を殺害できる。キルできる距離は通常のキル可能範囲よりやや広い。

キルレンジを長くする理由はあるのでしょうか

> 単に衆人環視の中「密殺」するだけでは、近くにいるサイレントキラーが真っ先に疑われやすいのであまり意味はない。
しかし、多人数が密集している状況で「密殺」した場合は、サイレントキラーの仕業だとは分かっても誰がキルしたのかを詰めるのが難しくなる。その為、所謂「ごちゃキル」の状況で真価を発揮する役職であるといえる。
結果、クルー陣営や第三陣営は大人数で固まりにくくなる。

ごちゃキル以外で真価を発揮しにくいってのは使いにくいと思うのですがどうでしょうか

**Comment by issyoukimizu** [comment]
実はこれ、ボマーのような遠隔ないしは時間差キルができるインポスターと組む事も考慮に入れて設計しています。
つまり、このような組み合わせの場合、あるプレイヤーが誰かの近くで弾け飛んだとしても、それがサイレントキラーの仕業なのかそれとも時間差or遠隔キルなのかが判りにくくなるわけです。
まだこういった能力を持つインポスターは殆ど無いですが、今後登場する事も考えて作りました。

あと、キル範囲がやや広いと設定したのは、流石に通常キルと同じキル範囲だと使える場面が限られすぎると思ったからです。

**Comment by yukieiji** [comment]
> 実はこれ、ボマーのような遠隔ないしは時間差キルができるインポスターと組む事も考慮に入れて設計しています。
つまり、このような組み合わせの場合、あるプレイヤーが誰かの近くで弾け飛んだとしても、それがサイレントキラーの仕業なのかそれとも時間差or遠隔キルなのかが判りにくくなるわけです。
まだこういった能力を持つインポスターは殆ど無いですが、今後登場する可能性も考えて作りました。

インポスターがその役割を持つことは私は避けたいと考えています。別陣営で持つなら問題無いと思います

**Comment by issyoukimizu** [comment]
別陣営という事ならば、第三陣営にして通常のキルボタンが無く、「密殺」だけができるという事にするのはどうでしょうか？
サボタージュは使えず、ジャッカルのように仲間は作れないので単独で勝利しなければならない＝クルーを残り1人にするか全滅させるしかないので、それなりに難易度が高い役職になると思います。
流石にベント位は使えてもいいと思いますが……。

**Comment by yukieiji** [comment]
第三陣営とする場合、キルボタンが必要なのかを問いたいです

**Comment by issyoukimizu** [comment]
それは、通常のキルボタンが無くて「密殺」だけが出来る、という意味でしょうか？
それも候補としては考えています。

**Comment by yukieiji** [comment]
> それは、通常のキルボタンが無くて「密殺」だけが出来る、という意味でしょうか？
それも候補としては考えています。

第三陣営だから「密殺」だけでいいと思ってます

通常キルが必要な理由はありますか

**Comment by issyoukimizu** [comment]
では「密殺」だけで行きましょう。

**Comment by issyoukimizu** [comment]
編集いたしました。
一応、キルクールペナルティはなくしています。

**Comment by yukieiji** [comment]
だいぶ、返信が遅れましたが、密殺とキルを持っていたとしてもミッショナリーの下位互換な気がしてきました(密殺だけだと完全にミッショナリーの下位互換だと思います)

**Comment by issyoukimizu** [comment]
ごちゃキルで真価を発揮する役職である都合上、何らかの方法で人を集めることができれば強化になりますね。

一番単純なのはやはりサボタージュを行使する能力を付与する事でしょう。
リアクターや衝突回避などは失敗するとインポスター勝利に繋がってしまうので、一概にヒットマンに恩恵ばかりでないのも個人的には悪くないポイントだと思います。
ただ、インポスターとクール時間が共用でない場合、サボタージュの重ね掛けで延々とボタン妨害が出来てしまうので、ここは共用にせざるを得ないでしょう。そうなると、ヒットマンの好きなタイミングで欲しいサボタージュを発生させられないという事もあり得ますね。無論、逆もしかりですが。

他に考えるとすれば、トラップ敷設能力でしょうか。
トラップに引っかかったプレイヤーは動けなくなり、かつ一定時間以内に解除されないと爆死します。
しかし、トラップは2～3人が同時に近くに居れば解除可能で、かつ誰かが引っかかると全員の視界にトラップの方向への矢印が表示されます。
これは無制限敷設ができるとさすがに凶悪すぎるので、1～3回程度に回数制限を設ける必要があるでしょうが。

とりあえず、この場で思いついた分はこんな所でしょうか。

**Comment by yukieiji** [comment]
> 一番単純なのはやはりサボタージュを行使する能力を付与する事でしょう。
リアクターや衝突回避などは失敗するとインポスター勝利に繋がってしまうので、一概にヒットマンに恩恵ばかりでないのも個人的には悪くないポイントだと思います。
ただ、インポスターとクール時間が共用でない場合、サボタージュの連続行使で延々とボタン妨害が出来てしまうので、ここは共用にせざるを得ないでしょう。そうなると、ヒットマンの好きなタイミングで欲しいサボタージュを発生させられないという事もあり得ますね。無論、逆もしかりですが。

人が集まるところでキルすると吊られやすいし、逆に人が集まらないところだと能力としてあんまり意味がない気がします

> 他に考えるとすれば、トラップ敷設能力でしょうか。
トラップに引っかかったプレイヤーは動けなくなり、かつ一定時間以内に解除されないと爆死します。
しかし、トラップは2～3人が同時に近くに居れば解除可能で、かつ誰かが引っかかると全員の視界にトラップの方向への矢印が表示されます。
これは無制限敷設ができるとさすがに凶悪すぎるので、1～3回程度に回数制限を設ける必要があるでしょうが。

どうやって解除するかという問題が出てきます

**Comment by issyoukimizu** [comment]
>どうやって解除するかという問題が出てきます
トラップに何人かが触れば解除できる感じでどうでしょう。

**Comment by yukieiji** [comment]
> トラップに何人かが同時に触れば解除できる感じでどうでしょう。

最終盤面で無双できてしまうのですがそれはいいのでしょうか

どちらにせよ現状の実装だと複数のボタンを実装することは考慮してないです(任意発動能力は1役職1機能としないばあい、役職が使用者にとって使いにくいものになると考えているためです(実際にインポスターに1機能付けるだけで混乱することもあるので))

**Comment by issyoukimizu** [comment]
となると、密殺を強化するか、ボタンを使わない何らかの能力を有することになりますね。

①自分をキル可能な相手をキルする事でボーナスを得る。

②キル可能範囲なら壁や扉の判定を無視してキルできる。

③ベントに誰かが入っているとハイライトされる。

④キルできる役職が誰かがわかる。(陣営までは分からない)

今思いつく範囲ではこんな所でしょうか。

**Comment by yukieiji** [comment]
> ①自分をキル可能な相手をキルする事でボーナスを得る。

どんなボーナスを得るのでしょうか

> ②キル可能範囲なら壁や扉の判定を無視してキルできる。

あんまり強化にはなってないのでは

> ③ベントに誰かが入っているとハイライトされる。

キルボタンが反応するはずなのでそんなに強化ではないと思います

> ④自分をキルできる役職が誰かがわかる。(陣営までは分からない)

全滅が目的の陣営でキル陣営が分かるのは強力すぎると思います

**Comment by yukieiji** [comment]
ユーザーが削除されたためチケットをクローズします
