### ISSUE TITLE
英語への翻訳 English Translation of MOD

### ISSUE THREAD

**Issue by yuhgao** [yukieiji/ExtremeRoles#200]
### 追加する機能の詳細 / Feature details
・Extreme RolesおよびExtreme Skinsの英語翻訳

### 機能を追加するメリット / Benefits of adding features
・英語版ユーザーでもExtreme RolesとExtreme Skinsが楽しめる。

**Comment by yukieiji** [comment]
v4.0.0.0でリリース済み
