### ISSUE TITLE
ウィスパー、エージェンシー、カースメーカー、コマンダー能力発動とタスク追加にSEをつけてわかりやすくする

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#202]
### 追加する機能の詳細 / Feature details
- 役職の能力発動時にSEがなるようにして、効果を受けた or 発動させたことをわかりやすくする(#193 を含む)

#### 実装予定の役職
- 全体的な部分：タスク追加時に同じSEがなるようにする
  - タスク追加される役職(能力込み)：エージェンシー、リザレクター、スレイヴドライバー、タスクマスター、アリス

|  役職  |  SEのなるタイミング  |  対象  |  SE(予定)  |
|  ---  |  ---  | ---  |  ---  |
|  ウィスパー  |  キルを検知した時  |  役職の人  |  キル音(小さめ)  |
|  ボディーガード  |  キルを肩代わりした時  |  役職の人  |  ガーディアンエンジェルの防御音(ｶｷﾝの部分)  |
|  エージェンシー  |  「肩代わり」を発動させた時  |  役職の人と対象になった人  |  未定  |
|  カースメーカー  |  「呪う」を完了させた時  |  対象になったキル能力を持つ人  |  未定  |
|  スレイヴドライバー  |  各種能力発動時  |  役職の人  |  未定  |
|  コマンダー  |  「攻撃司令」発動時  |  インポスターの人達  |  未定  |

### 機能を追加するメリット / Benefits of adding features
- 役職自体を使いやすくわかりやすくする

### 実装予定
- [x] : v4.0.x.x内で音を鳴らす基本ロジック実装
- [ ] : v4.1.0.0で本実装

**Comment by yukieiji** [comment]
他に追加したい役職があれば募集しておきます

**Comment by melonjagaimo** [comment]
・フェンサーがカウンター能力でキルを無効化した際、フェンサー本人とキルを無効化された人にガーディアンエンジェルの防御音(ｶｷﾝの部分)

・ラストウルフのラストウルフ覚醒時、ラストウルフ本人に狼の遠吠え

・サイドキックのジャッカル昇格時、そのサイドキックから昇格したジャッカル本人にピコーンと鳴る

このあたりが欲しいと個人的に思います

**Comment by yukieiji** [comment]
> フェンサーがカウンター能力でキルを無効化した際、フェンサー本人とキルを無効化された人にガーディアンエンジェルの防御音(ｶｷﾝの部分)
サイドキックのジャッカル昇格時、そのサイドキックから昇格したジャッカル本人にピコーンと鳴る

ここらへんは視覚的にキルボタンが生えるはずなのであえてわかりやすくする必要はないと思ってます
フェンサーなんかはキルしてくることを予測しててその反応速度をデメリットに取っているので、わかりやすくするということ自体がフェンサーの強化に繋がります

> ・ラストウルフのラストウルフ覚醒時、ラストウルフ本人に狼の遠吠え

ラストウルフの覚醒でわかりにくいって思われたことはないような気がします

**Comment by yukieiji** [comment]
ボディーガードとスレイブ以外は実装完了
スレイブは使用率が低い、ボディーガードは必要性も薄いため別チケットを発行し別途対応、クローズ
