### ISSUE TITLE
英訳に関する不備の修正

### ISSUE THREAD

**Issue by yuhgao** [yukieiji/ExtremeRoles#203]
## バグの情報 / Info of bug
英語翻訳に関する複数の不備
・ExtremeRolesTransData.xlsxのCracker関連が一行ずれている
・勝利画面で複数役職が同時勝利した際に語と語の間にスペースがない
　・ほか、「～の～」という形で日本語表記される文章の英訳に語間のスペースがない

### 期待される動作 / Your Expectation
正しい翻訳及び表示

### 実際の動作 / The Reality
翻訳データが間違っており文章がおかしい（もしくは、文章表示の仕様が英語にそぐわない）。

### このバグに対するあなたの意見 / Your Proposal
翻訳データを修正すべき（しました）。

### バグ発生時のログ / log when issue occur
なし

### Among Usバージョン/ Among Us Version
Among Us v2022.10.25

### Modバージョン / Mod Version
Extreme Roles v4.0.0.0

### リージョン/Region
（すべて）
- [x] :北アメリア/Noth America
- [x] :欧州/Europa
- [x] :アジア/Asia
- [x] :カスタム/Custom

### プレイヤー人数/Player Num
（すべて）

### 使用したオプション/Use Option
（オプションの如何に関わらない）

**Comment by yukieiji** [comment]
急ぎではないと思いますので11月4日リリースのv4.0.0.2にマイルストーンをセットします(急ぎの場合調整します)

**Comment by yuhgao** [comment]
かしこまりました！

**Comment by yukieiji** [comment]
リリース準備が整ってるのでクローズ

**Comment by yukieiji** [comment]
基本的に翻訳周りは自動的に埋め込まれるように作っているはずなのでどこか間違えてるか空欄になっているのだと思います

**Comment by yuhgao** [comment]
もしやと思って確認したところプルリクのマージ時に古い方（フォーク元）のエクセルが合成されているようです　再度プルリクエストを開きますのでマージをお願いいたします

**Comment by yukieiji** [comment]
最新のDevelopよりExcelを作ってPRをお願いします
数分後にリワークしたシューターの翻訳が入ったものが上がります

**Comment by yukieiji** [comment]
上げました
恐らくリベースしてPRを送らないと新しいコミットに上書きされてしまうからだと思います
