### ISSUE TITLE
[クルー/インポスター] : ナイスゲッサー(Nice Guesser)/イビルゲッサー(Evil Guesser)(TORの物をバックポート、調整)

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#207]
### 役職名 / Role Name
- ナイスゲッサー(Nice Guesser)/イビルゲッサー(Evil Guesser)

### 役職の色 / Role color
- 未定

### 役職の説明 / Role description
- TORのゲッサーをバックポート/調整

### 役職の能力 / Role ability

- 能力：「推殺」
  - 基本的にはTORのものと同じ、ExRの仕様に合わせるため他の会議中能力と発動方法は統一
  - ExRの役職仕様と各役職との兼ね合いで以下の仕様になる
    - 他の役職を持つ場合、両方の役職を当てる必要があります
      - 例：シェアーズ + シェイプシフター => シェアーズやシェイプシフターで打っても失敗、「シェアーズ + シェイプシフター」で打つ必要があります
    - ナイスゲッサーの場合、素クルーで打てなくするオプションを追加する
    - 以下に当てはまる場合、「推殺」はどの役職で打ったとしても失敗扱いになる(ゲッサー本人が死亡します)
      1. 以下の役職のどれかに当てはまる場合
         - マーリン
         - アサシン
         - ヴィラン
      2. ボディーガードに守られている場合
    - 覚醒前がクルーもしくはインポスターの役職の場合、覚醒後の役職を推測する必要があります
    - 2022/11/13(追記)：イビルとナイス両対応の場合はナイスとイビルを外した役職名で打つ必要があります
      - 例：イビルサポーターを打つ場合、サポーターで打つ
### 他陣営への影響 / Effect on other teams
- クルー陣営：COが基本的にしにくくなる
- インポスター陣営：ボディーガードが対ゲッサーとして強力なので打ちにくい
### 陣営 / Team

- [x] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by melonjagaimo** [comment]
質問があります。
対象が覚醒役職の場合は現在の役職を当てればよろしいのでしょうか。それとも覚醒前でも覚醒後の役職で撃てるのでしょうか。（例：カーペンターになる予定のクルーに対しカーペンター指定で撃った場合は当たるのか）

**Comment by yukieiji** [comment]
> 質問があります。
対象が覚醒役職の場合は現在の役職を当てればよろしいのでしょうか。それとも覚醒前でも覚醒後の役職で撃てるのでしょうか。（例：カーペンターになる予定のクルーに対しカーペンター指定で撃った場合は当たるのか）

基本的に覚醒役職はCO抑制と能力制御のために作ってるので覚醒前の役職で打てること自体がかなり強力であると思ってます
なので、覚醒後の役職で打たないと失敗になります
