### ISSUE TITLE
インポスター役職：二人一組で連携を取りやすくする『双子』

### ISSUE THREAD

**Issue by kurenainoki** [yukieiji/ExtremeRoles#21]
### 役職名 / Role Name
双子
### 役職の色 / Role color
インポスター
### 役職の説明 / Role description
二人一組でアサインされ、もう片方の行動が遠隔からでも把握しやすくなり連携を促すインポスター役職
### 役職の能力 / Role ability

相方の位置が常に矢印で表示されるようになる能力と、相方のキルクールダウンを把握できる能力（技術的に難しいようであれば相方がキルした時のみ自身に通知が届くなど）の２つを主軸にしたインポスター役職。
二人一組で行動しやすくなり、ダブルキルや遠隔でもサボタージュなどをタイミングよく出来るようになる。
ただし片方がいなくなれば無能力インポスターとなるのが最大のデメリットであり、吊られるだけでなく食い合いが起こったりサイドキックにされたりと能力を活かせない場面も想定されるかなと

### 他陣営への影響 / Effect on other teams
特になし

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
キルクールを常時シンクロするのは無理なので、恐らくキルを通知するだけかもしくは位置だけの能力になると思います

個人的にはクルーのデメリットになるような能力ではないので片方が落ちた場合に別役職になるってのでもいい気がします

**Comment by kurenainoki** [comment]
コメントありがとうございます。
ダブルキルをしやすくするというコンセプトなので可能であれば基本的には２つの能力がデフォルトでオンの状態で、設定でそれぞれ相方の位置情報とキル把握能力がオンオフできるようになると良いなと思っております。
片方が死んだ場合に別の役職化は死亡時のデメリットとして何もないほうが良いかな？と思ってましたが生存時の能力だけだと魅力が足りない場合は何かしらボーナスがあっても良いかもしれませんね

**Comment by yukieiji** [comment]
名前をシェアーズとして2人以上に対応して、死亡した相方にも矢印が付くように調整して実装を行います

**Comment by yukieiji** [comment]
開発用ブランチのコミット628dd4b30678caa4d570a56d4c31cbbf1ab7475eで完成したためクローズします
