### ISSUE TITLE
[インポスター陣営] : ストーカー (発信器をつけ、ストーキングでキルクールのカウント加速)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#213]
### 役職名 / Role Name
ストーカー

### 役職の色 / Role color
インポスターレッド

### 役職の説明 / Role description
発信器をつけて位置を把握し、ストーキングでキルクールタイムのカウントを加速させるインポスター陣営

#### 発信器
・誰にも発信器がついていない状態で、クルー陣営またはニュートラル陣営のプレイヤーに近づいて「発信器」能力を発動すると対象に発信機を付けられる。

・ストーカーは自分が付けた発信器が付いたプレイヤーの位置を矢印で把握できる。発信器をつけられたプレイヤーはそのことを把握しない。

・発信器を付けたプレイヤーが死亡すると発信器が壊れ、矢印が消滅する。発信器が壊れた次の会議終了後（発信器持ちが追放された場合、その追放された会議の後）、再び発信器能力を使用できるようになる。

#### ストーキング
・ストーカーは自分が付けた発信器が付いたプレイヤーをキルレンジ内に入れている間、ストーキングしてキルクールタイムのカウントが加速する。

#### 固有オプション
発信器能力の使用回数
発信器能力のクールタイム
ストーキング中のキルクールタイム加速度（100％にすると通常の倍の速さ）

#### メリット
キルクールタイムが早く明ける

#### デメリット
つけまわすので怪しまれる

### 他陣営への影響 / Effect on other teams
特定のプレイヤーと長く一緒に行動することに対してストーカー疑惑が生まれる。

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
人の位置がわかる時点でかなり強力でその上に近づくだけでキルクールが溜まるのはデメリットがないようなものではないんでしょうか
近くに居なかったら適当な人をキルして、近くにいればキルすればいいだけですし

**Comment by melonjagaimo** [comment]
改善案が2つ思い浮かびました。
１：ストーキング中は通常の速度、ストーキングしていない場合はキルクールタイムのカウントが減速する

２：発信器能力をなくす
・ゲーム開始時にランダムな敵プレイヤー1人がストーキング対象に指定され、そのプレイヤーをキルレンジに入れている間だけキルクールタイム加速
・矢印による位置把握はない

**Comment by yukieiji** [comment]
> 改善案が2つ思い浮かびました。
１：ストーキング中は通常の速度、ストーキングしていない場合はキルクールタイムのカウントが減速する
２：発信器能力をなくす
・ゲーム開始時にランダムな敵プレイヤー1人がストーキング対象に指定され、そのプレイヤーをキルレンジに入れている間だけキルクールタイム加速
・矢印による位置把握はない

これらをつけるとバウンティーハンターとの差別化が難しくありませんか？

**Comment by melonjagaimo** [comment]
１と２は片方だけを採用する前提で考えてました
個人的には「ストーキングでキルクールタイムのカウント加速」か「発信器能力」のどちらかはストーカーというコンセプト上欠かせないと思っています

独自のパッシブ能力として「ゲーム終了時にストーキング対象と自身が両方生存している場合、ストーカーはインポスター陣営が負けたとしても、妖狐以外すべての勝利に便乗できる」というものも考えましたがそれは強すぎるということで先の案を出したわけです

**Comment by yukieiji** [comment]
> １と２は片方だけを採用する前提で考えてました
個人的には「ストーキングでキルクールタイムのカウント加速」か「発信器能力」のどちらかはストーカーというコンセプト上欠かせないと思っています

どちらをつけるにしてもバウンティーハンターとの差別化要素があまりないような気がしますがどうでしょうか

**Comment by Inumiya** [comment]
横から失礼します
ストーカーしていることを告発されるのがデメリットのハズなのに、ストーカー相手をキルして口封じ出来てしまうのが強すぎるポイントだと思うので、弱体化させるなら発振器を付けた相手はキル出来ないとかどうでしょう

**Comment by melonjagaimo** [comment]
発信器を付けたプレイヤーをストーカーはキルできないってのは良いですね

**Comment by yukieiji** [comment]
発振器の人をキルできないとなると近づくことに意味がないように見えます
- 近づく
  - キルクールが早くなる <=> 推理要素を与えてつられやすい
- 近づかない
  - その人の位置を常に知れる + 推理要素を与えずにキルできる <=> キルクールが早く上がらない

**Comment by melonjagaimo** [comment]
自分としてはこれでキルクールのために近づく・怪しまれないために近づかないの駆け引きができると思っているのですがね…。
ストーキング対象をキルできない場合、メリットを増やした方がいいんです？

**Comment by yukieiji** [comment]
> 自分としてはこれでキルクールのために近づく・怪しまれないために近づかないの駆け引きができると思っているのですがね…。

遠くに居ても矢印で位置がわかるというメリットがあってデメリットがないので、近づくって選択が出ないのではないのでしょうか？
TORのバウンティが矢印更新時間60秒がデフォルトになってるのは位置がわかるメリットがあるからそれを封じてると思ってます

> ストーキング対象をキルできない場合、メリットを増やした方がいいんです？

遠くにいるデメリットをつけるか、近づくことのメリットを増やすでしょうか
インポスター的にバレることが一番嫌がることなのでデメリットを遠くにいるデメリットをつけるのがいいと思いますがそうするとバウンティと何が違うのかって問題が出てきます

**Comment by melonjagaimo** [comment]
バウンティはバウンティ対象をキルする/そのプレイヤー以外をキルする、の違いでキルクールタイムそのものが増減し、バウンティ対象は選べない
一方ストーカーはストーキング対象に近づく/近づかないの違いでキルクールタイムのカウント進行が異なり、ストーキング対象は選べる

この相違点があると考えています

その上で遠くにいるデメリットとして「長いこと離れているとキルクールタイムのカウントが遅くなる」を追加することを提案します

**Comment by melonjagaimo** [comment]
能力を使わない方がいい問題は「発信器能力を使用していないばあいも発信器付きプレイヤーから離れている扱いになる」で解決はするのですが、「使いにくいバウンティ」ですか……

もしかして「他のプレイヤーをつけまわす」というコンセプトから間違えてましたか…？

**Comment by yukieiji** [comment]
> 能力を使わない方がいい問題は「発信器能力を使用していないばあいも発信器付きプレイヤーから離れている扱いになる」で解決はするのですが

いや最初から使う必要があんまり無いって感じでしょうか

> もしかして「他のプレイヤーをつけまわす」というコンセプトから間違えてましたか…？

コンセプトとしては間違ってはないですが、目的(キルクール)と手段(特定の人を追いかけるてキルをする)がバウンティと同じなのでそこと比べる(もし実装されたとしても比べられる)と思います(使いやすさ等)
目的が全く異なれば話は違うんですがね

**Comment by melonjagaimo** [comment]
全く違う目的ですか……。
キルクールタイム以外でインポスター陣営に欲しい目的といえば
・敵プレイヤーの陣営・役職を知る（役職を知る場合、マーリンなどの例外を入れる）。

が思いつきました。ストーキングして素性を特定するという意味になってストーカーのコンセプトにも合います

**Comment by yukieiji** [comment]
> 全く違う目的ですか……。
キルクールタイム以外でインポスター陣営に欲しい目的といえば
・敵プレイヤーの陣営・役職を知る（役職を知る場合、マーリンなどの例外を入れる）。
が思いつきました。ストーキングして素性を特定するという意味になってストーカーのコンセプトにも合います

役職の提案にもあるんですが「何らかのアクションで役職が分かる系」と言うのは基本的に実装はしたくはないです

**Comment by melonjagaimo** [comment]
そうでしたね。
これ以上いい案が出ないのでクローズします
