### ISSUE TITLE
[クルー陣営] : グレートシェリフ (シェリフがタスク進捗で覚醒、ロックオンで狙いを定める)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#215]
### 役職名 / Role Name
グレートシェリフ

### 役職の色 / Role color
シェリフと同じ色

### 役職の説明 / Role description
タスクを一定量完了させたシェリフが覚醒
ロックオン能力を追加

### 役職の能力 / Role ability

・ゲーム開始時はシェリフとしてアサインされ、本人のタスク進捗によってグレートシェリフに覚醒。覚醒に必要な進捗はオプションで変更可能（デフォルトでは100％を想定）。

・グレートシェリフに覚醒した時、キル能力の使用回数が回復する。回復する回数はオプションで変更可能で、0回にして回復しないようにもできる。

#### ロックオン能力
・グレートシェリフは会議中に1度、他のプレイヤーを対象に「ロックオン」能力を発動することでそのプレイヤーに印をつける。
この能力は印をつけられたプレイヤーが存在しない場合にのみ発動できる。
印は対象が死亡した場合に削除され、グレートシェリフ本人にのみ視認できる。
印をつけたプレイヤーが生きている限り、印の付いていないプレイヤーはグレートシェリフのキル能力対象から除外される。
例えばクイーンに印をつけた場合、狙われたクイーンをサーヴァントが身を挺してかばってクイーンが仇討ち、といった展開が起きない。

#### 固有オプション
覚醒に必要なタスク進捗
回復するキル能力の使用回数
ロックオンの使用回数

#### メリット
確実に狙ったプレイヤーをキルできる

#### デメリット
印をつける対象を間違えると結局自滅する
ロックオン後の不意打ちに弱い

### 他陣営への影響 / Effect on other teams
グレートシェリフへの覚醒を止めるべく、インポスター陣営およびニュートラル陣営は積極的にクルー陣営の排除にかかるだろう。
また、ロックオン中のグレートシェリフは他のインポスターらのキルに対して無防備になるため、そこを狙ってくることをほかのクルーたちは覚えておくとよい。

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> ・グレートシェリフは会議中に1度、他のプレイヤーを対象に「ロックオン」能力を発動することでそのプレイヤーに印をつける。
この能力は印をつけられたプレイヤーが存在しない場合にのみ発動できる。
印は対象が死亡した場合に削除され、グレートシェリフ本人にのみ視認できる。
印をつけたプレイヤーが生きている限り、印の付いていないプレイヤーはグレートシェリフのキル能力対象から除外される。
例えばクイーンに印をつけた場合、狙われたクイーンをサーヴァントが身を挺してかばってクイーンが仇討ち、といった展開が起きない。

現行犯を打てなくなったりしますし、印をつけてなんかいいことも無いですしメリットが一切ないような気がします

> 確実に狙ったプレイヤーをキルできる

印がある事によって確実にキルできる訳ではないような気がします

**Comment by melonjagaimo** [comment]
ロックオンはダメみたいですね。
他に考えていた強化案としては
１：1度だけシューターのように会議中にキル可能（ただしクルーなどを撃とうとすると通常通り自爆）

２：キル能力を発動して自爆した場合、強制的にグレートシェリフ本人による通報扱いの死体通報が入る

３：ジャッカルのサイドキック作成のように部下を1人任命できる。部下がクルー陣営の場合のみ自身の死亡時にその部下がシェリフになる

があります。どうでしょうか。

**Comment by yukieiji** [comment]
> １：1度だけシューターのように会議中にキル可能（ただしクルーなどを撃とうとすると通常通り自爆）

会議中に白確を取れるのはタスク100％でも軽い気がします

> ２：キル能力を発動して自爆した場合、強制的にグレートシェリフ本人による通報扱いの死体通報が入る

今後、ベイトは実装されなくなりますけどいいですか？

> ３：ジャッカルのサイドキック作成のように部下を1人任命できる。部下がクルー陣営の場合のみ自身の死亡時にその部下がシェリフになる

これもキルも出来て白確を簡単につくれるのでタスク100％でも足りないと思います

**Comment by melonjagaimo** [comment]
これ以上の案が浮かばないのでクローズします
