### ISSUE TITLE
[インポスター陣営/imposter] : セーブアンドローダー（仮） (セーブしたときの位置に全プレイヤーを戻すインポスター)

### ISSUE THREAD

**Issue by T-NANANON** [yukieiji/ExtremeRoles#217]
### 役職名 / Role Name
セーブアンドローダー（仮）
### 役職の色 / Role color
赤(インポスター)
### 役職の説明 / Role description
「セーブ」したときの位置に「ロード」で全プレイヤーを戻すインポスター。通常キルあり
「セーブ」→キル→「ロード」として死体の位置を動かしたり、単純なタスク妨害にもなったりする(と思う)。
テクニカルなキルにつながると強い。
そして何より移動系能力は面白い。(デリュージョナー、タイムマスターなど)

### 役職の能力 / Role ability

ボタン能力：セーブ/ロード
「セーブ」ボタンをを押すと「ロード」に一定時間変化し、「ロード」を押すと「セーブ」のときの位置に全員飛ばされ、ボタンは「セーブ」に戻る（このときCT発生）。「ロード」変化が終わるとセーブデータは破棄される。
「ロード」しても変わらないものとして
・タスクなどの進捗
・プレイヤーの生死
・SKなどの陣営変更
・キルク　　　　　　　　　などを想定している。あくまでデリュージョナーと同じ移動。
また時間制限付きサボ（リアクター系統）発生中は「ロード」できない。できればこの系統だけにしていただきたいが、無理なら他のサボでも使用不可にしてください。バランスが壊れてしまいます。

CTなどの設定は初期、会議後の「セーブ」が10秒前後、「ロード」に変化するのは10~15秒、「ロード」時間切れ後の「セーブ」再使用が10秒「ロード」後の「セーブ」再使用が30秒くらいを想定しています。「ロード」時にキルクが増える設定はあったほうがいいかもしれない。　　　　　　
### 他陣営への影響 / Effect on other teams

他のキル可能者：切ったときにセーブされると「ロード」時も現行犯の危機を背負う可能性がある。
クルー：会議が混乱しやすい。普通よりテクニカルなキルが増える。
### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

「ロード」の回数上限などは１〜２回ほどで
インポスター版タイムマスターを作ろうとしたらこうなりました
使い所が難しそうですが様子見でセーブしてやばくなったらロードって感じで使われそう

**Comment by T-NANANON** [comment]
投稿するのここで合ってたんやろか？

**Comment by yukieiji** [comment]
> 「セーブ」→キル→「ロード」として死体の位置を動かしたり、単純なタスク妨害にもなったりする(と思う)。
テクニカルなキルにつながると強い。
「セーブ」ボタンをを押すと「ロード」に一定時間変化し、「ロード」を押すと「セーブ」のときの位置に全員飛ばされ、ボタンは「セーブ」に戻る（このときCT発生）。「ロード」変化が終わるとセーブデータは破棄される。

ここの2つの部分が相反してる気がします、「プレイヤー」だけを動かすのか「死体」も含めて動かすのかどっちなんでしょうか

> そして何より移動系能力は面白い。(デリュージョナー、タイムマスターなど)

現時点では面白さを目的として役職を作るってことはしてないのでそこはご了承くださいませ(デリュージョナーは覚醒役職で有る点から本来の想定では強めの役職として作ってあります(作った結果おもしろ役職になってるだけです、刺されば強い時は強いですし))

> CTなどの設定は初期、会議後の「セーブ」が10秒前後、「ロード」に変化するのは10~15秒、「ロード」時間切れ後の「セーブ」再使用が10秒「ロード」後の「セーブ」再使用が30秒くらいを想定しています。「ロード」時にキルクが増える設定はあったほうがいいかもしれない。

能力のクールタイムは一部の特殊なボタンを持つものを除き基本的にデフォルト30秒です(どちらにせよこの能力を10秒程度で何回も使われるとクルー的にうざすぎるとは思いますが)

能力全体の仕様がいまいち見えてこないですが、能力を最大限に活かすには10秒程度前に能力を使う必要があるという認識で間違いないでしょうか
それならば、使いたい時に能力をフルパワーで使えないとなってかなり使いにくくないでしょうか？

**Comment by T-NANANON** [comment]
> ここの2つの部分が相反してる気がします、「プレイヤー」だけを動かすのか「死体」も含めて動かすのかどっちなんでしょうか

説明不足でした。死体とかクラッカーのキラキラとかも動くということでお願いします。なので「ロード」で死体が目の前に運ばれてきたりするという感じです。
 
> 現時点では面白さを目的として役職を作るってことはしてないのでそこはご了承くださいませ(デリュージョナーは覚醒役職で有る点から本来の想定では強めの役職として作ってあります(キルレンジロングより遠くの人を飛ばせるので白確を作りつつ自身はキルされない役職です、作った結果おもしろ役職になってるだけです、刺されば強い時は強いですし))

まあ私も面白くなったらラッキーぐらいの感じです。

> > CTなどの設定は初期、会議後の「セーブ」が10秒前後、「ロード」に変化するのは10~15秒、「ロード」時間切れ後の「セーブ」再使用が10秒「ロード」後の「セーブ」再使用が30秒くらいを想定しています。「ロード」時にキルクが増える設定はあったほうがいいかもしれない。
> > 能力のクールタイムは一部の特殊なボタンを持つものを除き基本的にデフォルト30秒です(どちらにせよこの能力を10秒程度で何回も使われるとクルー的にうざすぎるとは思いますが)

デフォルトの目安に、と思って書いたんですが全部３０秒でしたか。
> 能力全体の仕様がいまいち見えてこないですが、能力を最大限に活かすには10秒程度前に能力を使う必要があるという認識で間違いないでしょうか それならば、使いたい時に能力をフルパワーで使えないとなってかなり使いにくくないでしょうか？

その認識で大丈夫です。使いにくいのはそうなので「セーブ」はポンポンできるようにして試行回数を稼ぎ強いタイミングで「ロード」とできるような感じでどうでしょう。「セーブ」の回転率だけ上げれば試合にあまり影響せずに使い勝手が良くなると思います。（まあプレイヤーの方々が決めることなんで、Wikiにでも書いてもらえれば）
なので「ロード」時間切れ後の「セーブ」再使用のCTはなしにして
セーブデータをShift＋「ロード」で破棄できるようにしたいです（フェイカーの要領）
雑キルの保険や、キル位置だけどキルクがないときに「セーブ」しておいてたまったら「ロード」→キルとかには最低限使えると思います

**Comment by yukieiji** [comment]
> 説明不足でした。死体とかクラッカーのキラキラとかも動くということでお願いします。なので「ロード」で死体が目の前に運ばれてきたりするという感じです。

とかで曖昧な表現をされるとこちらも困りますのでどれが動いてどれが動かないのかのかはっきり仕様をお願いします

> その認識で大丈夫です。使いにくいのはそうなので「セーブ」はポンポンできるようにして試行回数を稼ぎ強いタイミングで「ロード」とできるような感じでどうでしょう。

それはどういった仕様なのでしょうか

> 「セーブ」の回転率だけ上げれば試合にあまり影響せずに使い勝手が良くなると思います。（まあプレイヤーの方々が決めることなんで、Wikiにでも書いてもらえれば）

セーブの回転率が上げ過ぎると能力としてボタンにする必要性が有るのかが疑問に思います
CT開けたらとりあえずセーブしとけばいいですし、CT開けてからいつ使うというジレンマが一切ない気がします

> それか「ロード」時間切れ後の「セーブ」再使用のCTはなしにしたり

CTは基本的に30秒です、時間が切れたかどうかってのを判定するのはとてつもなく面倒です(恐らくですがそういう仕様はユーザー視点からもわかりにくい気がします)

> セーブデータをShift＋「ロード」で破棄できるようにしたりしたいです（フェイカーの要領）

破棄するメリットが一切浮かばないような気がしますがどうでしょうか

**Comment by T-NANANON** [comment]
> > 説明不足でした。死体とかクラッカーのキラキラとかも動くということでお願いします。なので「ロード」で死体が目の前に運ばれてきたりするという感じです。
> 
> とかで曖昧な表現をされるとこちらも困りますのでどれが動いてどれが動かないのかのかはっきり仕様をお願いします
動くもの：生存プレイヤー、死体、騒霊・キャリー・ペイント・クラックされ中の死体、プレイヤーについたボマーの爆弾
動かない、変わらないもの：幽霊、マップに設置するもの（マイナー・カーペンター・メリーなど）フェイカーのダミー
＜リザレクター＞セーブ時に能力発動待機→復活→ロード：「ロード」時死体の場所にロードされる
　　　　　　　　ロード時に能力発動待機→復活：ロードで死体移動後、ランダムスポーン
WIKIみてだいたいこんなもんかなと
> > その認識で大丈夫です。使いにくいのはそうなので「セーブ」はポンポンできるようにして試行回数を稼ぎ強いタイミングで「ロード」とできるような感じでどうでしょう。
> 
> それはどういった仕様なのでしょうか
> 下記の通りです。
> > 「セーブ」の回転率だけ上げれば試合にあまり影響せずに使い勝手が良くなると思います。（まあプレイヤーの方々が決めることなんで、Wikiにでも書いてもらえれば）
> 
> セーブの回転率が上げ過ぎると能力としてボタンにする必要性が有るのかが疑問に思います CT開けたらとりあえずセーブしとけばいいですし、CT開けてからいつ使うというジレンマが一切ない気がします
> 
雑に使ってもあまり強くないと思ったので考えていませんでした。時間制限もありますし、そういうジレンマはロードに任せました。
> > それか「ロード」時間切れ後の「セーブ」再使用のCTはなしにしたり
> 
> CTは基本的に30秒です、時間が切れたかどうかってのを判定するのはとてつもなく面倒です(恐らくですがそういう仕様はユーザー視点からもわかりにくい気がします)
> 
まずイメージとしてオーバーローダーのダウン/オーバーロードのような感じです。今までの話を要約すると

セーブボタンを押すとロードボタンに一定時間（a秒とする）変化し、ロードボタンは　[押す、a秒経過、Shift+押す]　のどれかでセーブボタンに戻る。このとき [押す]の場合だけプレイヤーなどを飛ばし、次のセーブまでCTが発生する。
という感じです。
オバロがオーバーロード後即ダウンロードできないのと反対に
こいつはセーブ後a秒経つまでにロードしなければならない。
って感じにしたいんです、キャリヤーみたいに緑数字でa秒のカウントダウンしてそれ中に再押したらロード、カウントなくなるorShift+押しでセーブを押せる状態まで戻る
　　
> > セーブデータをShift＋「ロード」で破棄できるようにしたりしたいです（フェイカーの要領）
> 
> 破棄するメリットが一切浮かばないような気がしますがどうでしょうか
次のセーブをしたいときに使うのではないでしょうか

**Comment by yukieiji** [comment]
> 動くもの：生存プレイヤー、死体、騒霊・キャリー・ペイント・クラックされ中の死体、プレイヤーについたボマーの爆弾
動かない、変わらないもの：幽霊、マップに設置するもの（マイナー・カーペンター・メリーなど）フェイカーのダミー

ペイント、クラックされ中の死体というものは存在しないです
「ペイント」は死体の色を消しているだけなので死体はそこにあります
クラックは死体自体が消えてそこにオブジェクトを設置もしくは死体の通報ロジック(正確には当たり判定ですが)を消しているだけです
そして、死体やクラックの跡と言うものは基本的にマップ上に設置されている or 設置するものになります。なので基本的に数秒前の座標をどうやって取得するのかという問題があります
キャリーや騒霊は死体を子オブジェクトとしてプレイヤーに付いてるのでプレイヤーが動けばプレイヤーと勝手についてきます

> 雑に使ってもあまり強くないと思ったので考えていませんでした。時間制限もありますし、そういうジレンマはロードに任せました。

セーブにジレンマがないということはセーブする行為自体が必要ない(必要性が無い)と思っています(わざわざCTを設けてユーザーにボタンを押させる必要性があるかなって感じです)

> まずイメージとしてオーバーローダーのダウン/オーバーロードのような感じです。今までの話を要約すると

オーバーローダーの場合はオーバーロードとダウンロードを切り替えるパッシブ能力なので違うと思ってます(なんならボタンは基本的にタイマーが動いている状態だとボタンは押すことができないような仕組みです)

> セーブボタンを押すとロードボタンに一定時間（a秒とする）変化し、ロードボタンは　[押す、a秒経過、Shift+押す]　のどれかでセーブボタンに戻る。このとき [押す]の場合だけプレイヤーなどを飛ばし、次のセーブまでCTが発生する。
という感じです。
オバロがオーバーロード後即ダウンロードできないのと反対に
こいつはセーブ後a秒経つまでにロードしなければならない。
って感じにしたいんです、キャリヤーみたいに緑数字でa秒のカウントダウンしてそれ中に再押したらロード、カウントなくなるorShift+押しでセーブを押せる状態まで戻るのような

最後の方にもあったのですが恐らくこれはキャリヤーのボタンのほうが正しい挙動だと思います
どちらにせよ上にある通りセーブする意味がちょっとわからないのでこういうボタンにする必要性が有るのかを問いたいですが

> 次のセーブをしたいときに使うのではないでしょうか

新しいセーブをしたら上書きされるのではないでしょうか？

**Comment by T-NANANON** [comment]
> > 動くもの：生存プレイヤー、死体、騒霊・キャリー・ペイント・クラックされ中の死体、プレイヤーについたボマーの爆弾
> > 動かない、変わらないもの：幽霊、マップに設置するもの（マイナー・カーペンター・メリーなど）フェイカーのダミー
> 
> ペイント、クラックされ中の死体というものは存在しないです 「ペイント」は死体の色を消しているだけなので死体はそこにあります クラックは死体自体が消えてそこにオブジェクトを設置もしくは死体の通報ロジック(正確には当たり判定ですが)を消しているだけです そして、死体やクラックの跡と言うものは基本的にマップ上に設置されている or 設置するものになります。なので基本的に数秒前の座標をどうやって取得するのかという問題があります キャリーや騒霊は死体を子オブジェクトとしてプレイヤーに付いてるのでプレイヤーが動けばプレイヤーと勝手についてきますので問題はないんですが
> 
なるほど死体は設置物なのか。
なら、死体などがワープしなくてもコンセプトが崩壊するわけではないので霊含む全プレーヤーとその子オブジェクトの移動に変えます（霊も移動しないと騒霊が面倒くさいと思います）
> > 雑に使ってもあまり強くないと思っ
たので考えていませんでした。時間制限もありますし、そういうジレンマはロードに任せました。
> 
> セーブにジレンマがないということはセーブする行為自体が必要ない(必要性が無い)と思っています(わざわざCTを設けてユーザーにボタンを押させる必要性があるかなって感じです)
> 
私はどちらかというと戻る時刻を逐一決められた方が自由度が高くいい役職になると思っています。ですが「セーブ」がないボタンで一定時間巻き戻す役職もそれでいい気もしてきました。でもそれだとシンプルすぎるので戻す時間を
n(今までキルした数)秒（ｎは設定する）とかにしたいです。

**Comment by yukieiji** [comment]
> 私はどちらかというと戻る時刻を逐一決められた方が自由度が高くいい役職になると思っています。ですが「セーブ」がないボタンで一定時間巻き戻す役職もそれはそれでいい気もしてきました。でもそれだとシンプルすぎるので戻す時間を
n(今までキルした数)秒とかにしたいです。カッコ内についてはもっといいのがあったらそれで（ｎは任意）

戻る時刻を可変にしたとしても一瞬で最大秒数ではない1秒程度の場所に戻ることで何らかのメリットが有るのかと言われると微妙だとは思います(1秒戻ることで行動とかが変わるのかという話です)
キル回数と秒数だとどう頑張っても2秒が限界でしょう、更に弱体化してる気がします

**Comment by T-NANANON** [comment]
> 

すいません文字が消えてました。
（設定した秒数）×（キルした回数）戻るようにしたいです。

**Comment by yukieiji** [comment]
> すいません文字が消えてました。
（設定した秒数）×（キルした回数）秒戻るようにしたいです。

どちらにせよ、この提案は以下の要素の技術的に不可能です
- 全プレイヤーの位置情報を最初から最後まで保持し続ける必要がある => 膨大なメモリと計算量が必要になりラグの原因になる

**Comment by T-NANANON** [comment]
> > すいません文字が消えてました。
> > （設定した秒数）×（キルした回数）秒戻るようにしたいです。
> 
> どちらにせよ、この提案は以下の要素の技術的に不可能です
> 
> * 全プレイヤーの位置情報を最初から最後まで保持し続ける必要がある => 膨大なメモリと計算量が必要になりラグの原因になる

TM的な感じでもだめですかね？

**Comment by yukieiji** [comment]
> TM的な感じでもだめですかね？あと「この提案」って全体の話ですか？

役職全体ではなくゲーム中に可変で秒数が増えたりすることです
TMの場合は役職アサイン時にそれぞれ別々の人にそれぞれのデータを特定のサイズで初期化しているため、高いパフォーマンスを維持してます

**Comment by T-NANANON** [comment]
> > TM的な感じでもだめですかね？あと「この提案」って全体の話ですか？
> 
> 役職全体ではなくゲーム中に可変で秒数が増えたりすることです

ならば可変性をもたせるならセーブ・ロード制が一番良さそうな気がします。セーブの時点での全プレイヤーの座標？くらいなら記録できませんかね？

**Comment by yukieiji** [comment]
> ならば可変性をもたせるならセーブ・ロード制が一番良さそうな気がします。セーブの時点での全プレイヤーの座標？くらいなら記録できませんかね？

それは結局、セーブする意味が技術的な背景のみで、ユーザーからしたら必要性のない行為を技術的な背景をもとに不便を押し付けてる事になってます(桜井さんが[動画](https://youtu.be/otyLLbYDF1g)で説明しているようなことだと思います)

**Comment by T-NANANON** [comment]
今のところ私の中では固定値分巻き戻すかセーブロード式かのどちらかなのですが、後者は前者に比べて操作は複雑になりますがどの時刻に戻るかの選択が簡単になっていると思います。
私の想定する能力の使用例は
セーブしてベント行ってベントキルして帰りのベントを見られたくないのでロードで帰る
キルチャンスなのにキルクがあけていないのでセーブしてキルクあけたらロード→キル
とかを想定しています。先ほどの前者だとちゃんと秒数を数えていないと事故りかねません。それよりかは後者の方が使いやすいとこの場合思います。
私には前者の方が使いやすいか同じくらいになる使い方が思いつきません。あるのなら私も前者でいいと思います

**Comment by yukieiji** [comment]
言い方がきつくなってたらすいません
セーブをなくす = 固定秒巻き戻りにするという話ではないです、セーブ自体をなくし能力全体の仕様を考える必要があるということです(固定秒数巻き戻りもわかりにくいとは思ってます)
理由としては以下です
 - セーブ自体のシステムが複雑すぎて使いにくい役職になっている
 - 別の場所である企画から提案されている役職でこれと非常に似たような役職が提案されている
   - 実際、現状このチケットで提案されている内容より、別企画で調整している役職の方が使いやすく能力、使用感的にも上位互換に近い状態になってます(強いので制限はかかってはいますが))
     - 以下別の場所で提案されている役職の能力の一部抜粋(全ては載せませんし能力についての質問にも答えないのであしからず)
       - 発動時、生存者と死体を特定のランダムな場所に飛ばす
なのでこの役職は上記能力を持つ役職との差別化を図りつつ使い勝手を上げる必要があります

**Comment by T-NANANON** [comment]
わかりました考えてみます

**Comment by T-NANANON** [comment]
名前だけ同じでこんなのどうでしょう

ボタン能力：セーブ/ロード

・セーブ
　・このボタンはキルクが溜まっていないかつ死体を通報できるときしか押せない（つまり自分がキルしていないと押せないよ　　
　　うにしたい）
　・その時の全プレイヤーの位置を記録しこのボタンはロードに変わる

・ロード
　・このボタンはキルクが溜まっているかつサボが鳴っていないとき押せる
　・「セーブ」した位置に生存者全員が飛び、「ロード」使用者以外が止まるor減速する（Now　Loadingとか出したい）
　・キルするかボタンが押されると「ロード」を押したときの位置に生存者全員が戻る。停止、減速解除
　・「ロード」中サボや能力の使用はできない

昔に戻ってキルができるが移動速度が一人だけ速いのでオバロみたいにバレる。
複雑過ぎですかねえ

**Comment by yukieiji** [comment]
> ・「セーブ」した位置に生存者全員が飛び、「ロード」使用者以外が止まるor減速する（Now　Loadingとか出したい）

これはゲームの進行速度をかなり落とす気がします

> ・キルするかボタンが押されると「ロード」を押したときの位置に生存者全員が戻る。停止、減速解除

ではボタンやキルをしなければ全員のキルクールを回復させつつ必ずお見上げが出来る気がしますがどうでしょうか？

> このコンセプトどう頑張っても複雑になるようです

だから上にもある通り能力全体の仕様を考える必要があるということです

**Comment by T-NANANON** [comment]
> > ・「セーブ」した位置に生存者全員が飛び、「ロード」使用者以外が止まるor減速する（Now　Loadingとか出したい）
> 
> これはゲームの進行速度をかなり落とす気がします
> 
> > ・キルするかボタンが押されると「ロード」を押したときの位置に生存者全員が戻る。停止、減速解除
> 
> ではボタンやキルをしなければ全員のキルクールを回復させつつ必ずお見上げが出来る気がしますがどうでしょうか？

制限時間５〜１０秒とかにすれば解決すると思ってます。
> だから上にもある通り能力全体の仕様を考える必要があるということです

がんばります。ニコニコＸふにんがすあとがたり聞きながら

**Comment by yukieiji** [comment]
> 制限時間５〜１０秒とかにすれば解決すると思ってます。

制限時間について記載してないので存在しないと思いこんでました
まぁどちらにせよ、5秒でも止まればゲーム速度は落ちるのでは？

**Comment by T-NANANON** [comment]
止まりはしますが、アサシン会議のような通常とは違うフェーズになると考えています。ロードされたからにはキルがおきますから、能力使用者以外もいつの時間軸に飛ばされたのか考察する必要性が出てきて退屈したりはしないと思います

**Comment by yukieiji** [comment]
> 止まりはしますが、アサシン会議のような通常とは違うフェーズになると考えています。ロードされたからにはキルがおきますから、能力使用者以外もいつの時間軸に飛ばされたのか考察する必要性が出てきて退屈したりはしないと思います

アサシン会議の場合は能力が発動するタイミングが他の人がわかる点(この人がインポスターだろうと考えて吊るので能力が発動するであろうという心構えが有る状態で能力が発動します)と、一回発動してしまえば2回目が発動することはほぼ無いという点でこの役職と異なります(何回も発動してそれを他の人が予測できないという時点で5秒も止まれば、ゲームテンポが悪くなると感じる人は多いとは思います)

**Comment by T-NANANON** [comment]
> アサシン会議の場合は能力が発動するタイミングが他の人がわかる点(この人がインポスターだろうと考えて吊るので能力が発動するであろうという心構えが有る状態で能力が発動します)と、一回発動してしまえば2回目が発動することはほぼ無いという点でこの役職と異なります(何回も発動してそれを他の人が予測できないという時点で5秒も止まれば、ゲームテンポが遅く歯切れが悪いと感じる人は多いとは思います)

ならばセーブした次の会議でロード発動(自動)、その会議後のリスポーンでワープはどうでしょう。自動なら使いやすいですし、タイミングも分からなくはないです。回数についてはプレイヤーさんに決めてもらうか一回固定でどうでしょう

**Comment by yukieiji** [comment]
> ならばセーブした次の会議でロード発動(自動)、その会議後のリスポーンでワープはどうでしょう。自動なら使いやすいですし、タイミングも分からなくはないです。

いつセーブしたかわからない時点でタイミングはわからないのではないでしょうか？
あとは、会議後に強制ワープさせるメリットが全く言っていいほど無い気がします

**Comment by T-NANANON** [comment]
> いつセーブしたかわからない時点でタイミングはわからないのではないでしょうか？

キルしないとセーブできないので多少はという感じです。ロードする会議の終わりの追放場面でロード中とか出したらいきなり感減るかもしれません。
> あとは、会議後に強制ワープさせるメリットが全く言っていいほど無い気がします

ロードの能力のワープです。それを否定されるとコンセプト崩壊します

**Comment by yukieiji** [comment]
> キルしないとセーブできないので多少はという感じです。ロードする会議の終わりの追放場面で"ロード中"とか出したらいきなり感減るかもしれません。

それは結局、会議中死体が上がった全ての会議で能力が発動するのかをビクビクする必要があるということです(魔女よりビクビクすんじゃないんですかね)

> ロードの能力のワープです。それを否定されるとコンセプト崩壊します。紛らわしくてすみません

どちらにせよ会議後にセーブした箇所に飛ばすメリットって何なんですかってことです
AirShipとかでもワープ目的でボタンが押されるのにそれを手助けしてませんかってことです

**Comment by T-NANANON** [comment]
> それは結局、会議中死体が上がった全ての会議で能力が発動するのかをビクビクする必要があるということです(魔女よりビクビクすんじゃないんですかね)

会議はじめに"セーブ完了"なり"Now loading"なりだすことにします

> どちらにせよ会議後にセーブした箇所に飛ばすメリットって何なんですかってことです AirShipとかでもワープ目的でボタンが押されるのにそれを手助けしてませんかってことです

ロードしたらキルクをローダー本人だけなくし、キルしたら改めて始まるという感じです。肝心なところを書いてませんでした

**Comment by T-NANANON** [comment]
クルー目線からは"ロードの追加キル死体を見つければその死体は前の死体の近くなので詰めやすくなる"ってしたいです。なのでロード時クルーに鈍足か停止をかけます。キルスポから出にくいようにしないとロードキルしにくそうなので

**Comment by yukieiji** [comment]
> 会議はじめに"セーブ完了"なり"Now loading"なりだすことにします。

会議のはじめのあのアニメーションの中で読み取るのは幽霊役職が入っていればそっちに基本意識を割きますし不可能に近いのでは？(幽霊役職の表示も最初に役職名だけ表示させることでわかりやすくはしてるんですけどおそらく全部を読まれてはないと思ってます)

> それか会議ボタンが押された直後発動→キル→会議にしますか？

これの意味がわからないのですがどういうことですか？

> ロードしたらキルクをローダー本人だけなくし、ワープします。ローダーがキルしたら改めて始まるという感じです。肝心なところを書いてませんでした

確実に1人以上持っていけるのはバランス的にどうなんですかね

> クルー目線からは"ロードの追加キル死体を見つければその死体は前の死体の近くなので詰めやすくなる"ってしたいです。なのでロード時クルーに鈍足か停止をかけます。キルスポから出にくいようにしないとロードキルしにくそうなので

それは結局ゲーム速度が落ちるって問題がある気がします

**Comment by T-NANANON** [comment]
> 会議のはじめのあのアニメーションの中で読み取るのは幽霊役職が入っていればそっちに基本意識を割きますし不可能に近いのでは？(幽霊役職の表示も最初に役職名だけ表示させることでわかりやすくはしてるんですけどおそらく全部を読まれてはないと思ってます)

もうちょっと別の場所に表示させることは可能ですか？「投票終了まで」の左とか
> 
> > それか会議ボタンが押された直後発動→キル→会議にしますか？
> 
> これの意味がわからないのですがどういうことですか？

さっき言及なさっていた会議前に能力が発動するパターンです。そうしたからと言って歯切れが良くなりはしないですが…
> > ロードしたらキルクをローダー本人だけなくし、ワープします。ローダーがキルしたら改めて始まるという感じです。肝心なところを書いてませんでした
> 確実に1人以上持っていけるのはバランス的にどうなんですかね

なので発動回数は1回ですし、セーブは自分が切った死体の近くでしかできないので（このコメの13個前参照）制限時間も相まってリスキーなキルを通さないといけません。（自分が切った死体から5秒ぐらいのところに他プレイヤーがいないと追加キルできない）
 
> > クルー目線からは"ロードの追加キル死体を見つければその死体は前の死体の近くなので詰めやすくなる"ってしたいです。なのでロード時クルーに鈍足か停止をかけます。キルスポから出にくいようにしないとロードキルしにくそうなので
> 
> それは結局ゲーム速度が落ちるって問題がある気がします

では停電視界にしますか。逃げられたら追加キルできないので。
> > クルー目線からは"ロードの追加キル死体を見つければその死体は前の死体の近くなので詰めやすくなる"ってしたいです。なのでロード時クルーに鈍足か停止をかけます。キルスポから出にくいようにしないとロードキルしにくそうなので
> それは無理なのでは・・・ 追加キル死体の位置と前の死体の位置が同じ場所とは限らないですし、何個も死体が上がればどこで死んだかなんてわからないですし

13個前のコメントの設定を引き継いでいるつもりで話してました。

**Comment by yukieiji** [comment]
> もうちょっと別の場所に表示させることは可能ですか？「投票終了まで」の左とか、気づくところに置けないですかね。会議中ずっと

[ここ](https://github.com/yukieiji/ExtremeRoles/discussions/87)にもありますが基本的に役職固有の処理はあんまり増やしたくはないです(バグの原因になります)

> さっき言及なさっていた会議前に能力が発動するパターンです。そうしたからと言って歯切れが良くなりはしないですが…
あくまで可能性の一つです

ここで言う会議前ってのはタスクフェーズ中に発動する能力ということです

> なので発動回数は1回想定ですし、セーブは自分が切った死体の近くでしかできないので（このコメの13個前参照）制限時間も相まってリスキーなキルを通さないといけません。（自分が切った死体から5秒ぐらいのところに他プレイヤーがいないと追加キルできない）

1回でも発動すれば1人以上は確定で持っていけるはずだと思います、ラストウルフとかオーバーローダー等がいればロードが発動さえすれば4人位一気に持っていけるはずでしょう

> 13個前のコメントの設定を引き継いでいるつもりで話してました。セーブは死体の近くでしか〜の下りです。一度キルすれば改めて次の回が始まります。そのときに前の死体予想位置にみんな湧くはずです。会議にてロードに気がつくので。なので死体発見は簡単かと。
一つ思ったのはロードキル後すぐはサボできないほうが良いかなと。

記載がちょっとわかりにくく最後が自分がキルすれば使えると書いてあったのでそう考えてました、通報ボタンが光る状態じゃないと使えないってことですかね？
けどどちらにせよロードされたところが必ず以前の死体の場所とは限らないでしょう？
例：A、B、C、D、Eさん例
1. CさんがAさん、Bさんをキル
2. CさんがBさんのところでセーブしました
3. CさんがAさんの死体を通報しました
4. 会議の結果、Bさんの死体の位置は冷えすぎててわかりませんでした
5. ロードが入りました
6. DさんがCさんのセーブ地点に飛ばされました <= ここはAさんの死体ではないでしょう？

**Comment by T-NANANON** [comment]
> > もうちょっと別の場所に表示させることは可能ですか？「投票終了まで」の左とか、気づくところに置けないですかね。会議中ずっと
> 
> [ここ](https://github.com/yukieiji/ExtremeRoles/discussions/87)にもありますが基本的に役職固有の処理はあんまり増やしたくはないです(バグの原因になります)

わかりました。他の案を模索します。
> > さっき言及なさっていた会議前に能力が発動するパターンです。そうしたからと言って歯切れが良くなりはしないですが…
> > あくまで可能性の一つです
> 
> ここで言う会議前ってのはタスクフェーズ中に発動する能力ということです

それは理解してました。会議前というより会議中に近かったですね。

> 1回でも発動すれば1人以上は確定で持っていけるはずだと思います、ラストウルフとかオーバーローダー等がいればロードが発動さえすれば4人位一気に持っていけるはずでしょう

最初は停止のつもりだったのでそいつらは意識外でした。確かにロード中キルできますね。ロードした人以外はキル不能にできたりしませんかね？
> > 13個前のコメントの設定を引き継いでいるつもりで話してました。セーブは死体の近くでしか〜の下りです。一度キルすれば改めて次の回が始まります。そのときに前の死体予想位置にみんな湧くはずです。会議にてロードに気がつくので。なので死体発見は簡単かと。
> > 一つ思ったのはロードキル後すぐはサボできないほうが良いかなと。
> 
> 記載がちょっとわかりにくく最後が自分がキルすれば使えると書いてあったのでそう考えてました、通報ボタンが光る状態じゃないと使えないってことですかね？ 

その認識で大丈夫です
’’自分がキルすれば’’が良かったのですが判定しにくそうなので’’通報が光る’’と書きました
>けどどちらにせよロードされたところが必ず以前の死体の場所とは限らないでしょう？ 例：A、B、C、D、Eさん例
> 6. DさんがCさんのセーブ地点に飛ばされました <= Bさんの死体の位置はここですけどそれが正しいか証明できないですし、ここはAさんの死体ではないでしょう？
> 7. EさんがDさんのセーブ地点に飛ばされました <= ここは誰の位置でもない
> 8. CさんがEさんのデーブ地点に飛ばされました  <= ここは誰の位置でもない
> 9. CさんがDさんをキルします <= 完全犯罪達成では？

この場合CさんはCさんがいたところに、DさんはDさんのいたところに行く想定でした。自分のいたところに飛びます。
ちょっと国語力の授業を取ってきます

**Comment by yukieiji** [comment]
> この場合CさんはCさんがいたところに、DさんはDさんのいたところに行く想定でした。自分のいたところに飛びます。
ちょっと国語力の授業を取ってきます（）

自分の所に飛ぶならなおさら意味がないのでは、他の人が推理も出来ないですし

> 最初は停止のつもりだったのでそいつらは意識外でした。確かにロード中キルできますね。ロードした人以外はキル不能にできたりしませんかね？

うーん正直、全体的に処理が複雑になり始めてる気がします、もし実装できても複雑すぎて誰も使わない気がします

**Comment by T-NANANON** [comment]
もうたぶん今の10倍ぐらいシンプルにしないと実装できなそうですし一旦諦めます
奇跡的にできる展望が見えたらまたコメントします。

**Comment by yukieiji** [comment]
とりあえずクローズで問題ないでしょうか？

**Comment by T-NANANON** [comment]
はい
