### ISSUE TITLE
間接物理キル能力インポスター：ギャングスター

### ISSUE THREAD

**Issue by Agurari** [yukieiji/ExtremeRoles#22]
### 役職名 / Role Name
ギャングスター
### 役職の色 / Role color
インポスター色
### 役職の説明 / Role description
脅して身代わりを差し出させる
### 役職の能力 / Role ability

能力「脅す」により対象のプレイヤー１人にクールタイムｎ秒/１回のキル能力を付与
脅されたプレイヤーはキル能力を残したまま会議が開かれた場合、会議開始時に死亡する
### 他陣営への影響 / Effect on other teams
メリット
・対象プレイヤーがキルした場合、自身が殺害現場に居ないため疑われにくい
・会議開始時でのキルが発生した場合にも疑われにくい

デメリット
・付与されたキル能力で自身及び味方インポスターがキルされる可能性がある
・付与する状況次第では第三者キルからの通報で吊られる可能性がある
・会議開始時のキルが発生した場合、ギャングスターの生存がほぼ確定する
　(ほぼ確定、というのは第３陣営にキルされている可能性はあるので)
### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
チケットのタイトルもわかりやすくして下さい、このチケットを見るのは私だけではないので

**Comment by Agurari** [comment]
申し訳ありませんでした、これでよろしいでしょうか

**Comment by yukieiji** [comment]
> 能力「脅す」により対象のプレイヤー１人にクールタイムｎ秒/１回のキル能力を付与
脅されたプレイヤーはキル能力を残したまま会議が開かれた場合、会議開始時に死亡する

インポスターがこの能力を使うメリットがない気がします
この能力をクルーに使った場合即反撃を受けるのではないでしょうか

**Comment by Agurari** [comment]
即反撃を受ける、と言うのが
インポスターＡとクルーＢが二人きりの状況でキルボタンが発生したらＢはＡをインポスターと確定する
と言うことでしょうか？
もしそうであるなら「脅す」は通常キルに置き換わるものではなく、二人きりであれば通常キルと使い分けていく考えでいたので
こちらの説明不足です

**Comment by yukieiji** [comment]
> もしそうであるなら「脅す」は通常キルに置き換わるものではなく、二人きりであれば通常キルと使い分けていく考えでいたので

この能力は能力ボタンで発動するものですよね、そうであれば、通常キルと「脅す」は両立するのでは無いでしょうか

**Comment by Agurari** [comment]
> この能力は能力ボタンで発動するものですよね

そうですね、２人きりなら通常キル、緊急タスク等で密集していたら能力ボタンで脅す、キルの現場を見られるわけではないのでインポスター確定まではされないと考えています

**Comment by yukieiji** [comment]
> そうですね、２人きりなら通常キル、緊急タスク等で密集していたら能力ボタンで脅す、キルの現場を見られるわけではないのでインポスター確定まではされないと考えています

キルボタンを持って会議に挑めば証拠を抹消して会議に挑めるので2人きりでも能力を使うことは選択肢に入るでしょう
ですが、2人きりで使えば逆襲されるし、まとまっても殺される危険がある時点でデメリットしか無い気がします

**Comment by Agurari** [comment]
付与したキル能力はインポスターに対して無駄撃ちになると言うのは可能なのでしょうか？

インポスターを狙う→ボタンは消費するがキル出来ない→キルしてない判定→会議で死亡

という流れならどうかな、思ったのですが
こうなると１キルは確実に決められますが、やはり会議開始時にギャングスターが残っている、ということを知られるデメリットの方が大きいと感じますか？

とにかく本人が脅した対象にキルされる可能性がある以上、デメリットしか感じない環境は変わらないと思うのでこのように考えてみたのですが

**Comment by yukieiji** [comment]
> 付与したキル能力はインポスターに対して無駄撃ちになると言うのは可能なのでしょうか？
インポスターを狙う→ボタンは消費するがキル出来ない→キルしてない判定→会議で死亡
という流れならどうかな、思ったのですが
こうなると１キルは確実に決められますが、やはり会議開始時にギャングスターが残っている、ということを知られるデメリットの方が大きいと感じますか？

インポスターが切れる切れないにしろキルボタンが生えた瞬間に誰か切ってセルフレポートするだけで確実にギャングスターを落とせる気がします
なんなら脅された人が色んな人と視認情報が出ている状況下なら誰もキルしない状態で会議に挑んでも9割型ギャングスターを絞り込めるでしょう(TORの魔女と同じような感じで)

**Comment by Agurari** [comment]
脅された側からしたらどうキルボタン生えたらｓの時傍にいた人で確定ですもんね
キルは人に任せて自分は関わっていないと高みの見物・・・みたいな感じなものが出来たらなと思っていたのですが
根本的にきびしそうですね

それでも一つ提案、というか聞いても良いでしょうか？
キルボダンは生えた時点でほぼ確定出来てしまう、なら脅すタイミングが会議の最中に対象を指定し会議終了後にキルボタンが生えていた、であれば誰に脅されたか特定には至らないと思います
ただ会議は集めた情報から推理するパートなので、そこで何かしら干渉するのは好ましくないと感じますか？
もし、そうであるなら今回の提案はダメだったね、とし終わりたいと思います

**Comment by Agurari** [comment]
流石に会議中の干渉となるなら回数の制限は必要だと思っています

「脅す」の使用は１試合中１回のみ、「脅す」は対象にキル能力を付与
「脅す」は会議中に一人を対象を指定、脅されたプレイヤーは次の会議発生時までにキルしないと会議開始時に死亡

でどうでしょうか

**Comment by yukieiji** [comment]
どちらにせよ無条件で1人持っていける時点で強すぎます

**Comment by Agurari** [comment]
そうですか…全然想像力が足りていなかったようです
ではクローズで大丈夫です、ありがとうございました
