### ISSUE TITLE
ゲッサーで〇〇 + クルーと 〇〇 + インポスターで推殺できない

### ISSUE THREAD

**Issue by xciss** [yukieiji/ExtremeRoles#227]
### 期待される動作 / Your Expectation
ゲッサーの推殺でサーヴァントクルーを撃ち抜きたい

### 実際の動作 / The Reality
無職クルーの推殺をありにしてもサーヴァントクルーが選択肢に出てこず仕方なくクルーで撃ち抜こうとするとゲッサー死亡となる

### バグ発生時のログ / log when issue occur
ごめんなさい、はじめてでとれてないです

### Among Usバージョン/ Among Us Version

Among Us v

### Modバージョン / Mod Version

Extreme Roles v5.0.0.1

### リージョン/Region

- [x] :北アメリア/Noth America
- [ ] :欧州/Europa
- [ ] :アジア/Asia
- [ ] :カスタム/Custom

### プレイヤー人数/Player Num
10

**Comment by yukieiji** [comment]
この不具合についてどうしてほしいのかの記載をしてください(これはどちらかと言えば未定義の動作に近いです)

> ゲッサーの推殺でサーヴァントクルーを撃ち抜きたい
無職クルーの推殺をありにしてもサーヴァントクルーが選択肢に出てこず

これ自体が期待されている動作かどうかも不明です

> 仕方なくクルーで撃ち抜こうとするとゲッサー死亡となる

#207 にもある通り役職は両方とも当てないといけないとあります、なのでこの部分に関しては期待されている正しい動作をしていると思いますがどうでしょうか

**Comment by xciss** [comment]
https://cdn.discordapp.com/attachments/969933012303216640/1053295791093067796/7.png

そうですね、役職は両方とも当てないといけない点は正しいと思います。なので選択肢にサーヴァント＋クルーを追加していただきたいです

**Comment by yukieiji** [comment]
v5.0.0.2で対応完了
