### ISSUE TITLE
？ボタンや情報表示ビューを開くボタンを連打すると半透明のスクリーンが非表示になる

### ISSUE THREAD

**Issue by mitsuki17291** [yukieiji/ExtremeRoles#228]
### 期待される動作 / Your Expectation
会議画面で右上の「？」マークを押した際、黒い半透明の背景と共に役職説明が表示される。
### 実際の動作 / The Reality

右上の「？」マークを連打すると役職説明は表示されるが黒い半透明の背景が表示されないことがある[(画像)](https://twitter.com/mitsuki1729/status/1603935412200046594?s=20&t=LqgQ0FvAQzT35wblcA-LeA)。
### このバグに対するあなたの意見 / Your Proposal

あまり重要度の高いバグではないと思います。また、本筋とは外れますが、私の使用しているノートPCだとpgup,pgdnキーが反応せず(本来crtl+十字キーで同じ挙動をするはずだが反応しない)、ほとんどの役職説明を確認することが出来ない状態になっています。通常の上下字キーでも同様に反応するようにしてもいいかもしれません。
### Among Usバージョン/ Among Us Version

Among Us v2022.12.8

### Modバージョン / Mod Version

Extreme Roles v5.0.0.1

### リージョン/Region

- [x] :北アメリア/Noth America
- [ ] :欧州/Europa
- [ ] :アジア/Asia
- [ ] :カスタム/Custom

### プレイヤー人数/Player Num

12人
### 使用したオプション/Use Option

(恐らくオプション未関係だと思われます。関係あるようなら後で貼ります)

**Comment by yukieiji** [comment]
この不具合はかなり昔から存在していて恐らくTOR-GMも同様の不具合を抱えていたはずです、そのためクローズします

> 私の使用しているノートPCだとpgup,pgdnキーが反応せず(本来crtl+十字キーで同じ挙動をするはずだが反応しない)、ほとんどの役職説明を確認することが出来ない状態になっています。通常の上下字キーでも同様に反応するようにしてもいいかもしれません。

上下キーはキャラクターの操作のキーと被っているのであえて現在の挙動になっています

**Comment by yukieiji** [comment]
Submarged対応の開発版の開発版にて情報表示周りを大きく変更(#291 )を行い
この不具合の修正も完了

マイルストーンも含めて再セットかつ再オープン
