### ISSUE TITLE
かくれんぼモードにおけるMOD導入時のベントの挙動異常

### ISSUE THREAD

**Issue by nyaromelon** [yukieiji/ExtremeRoles#229]
## バグの情報 / Info of bug

ExR(ver.5.0.0.1)を導入した状態でかくれんぼモードをプレイすると陣営ごとに、MOD未導入時とは異なる挙動が見られます。

### 期待される動作 / Your Expectation

インポスター陣営
・ベントの使用が不可能

クルー陣営
・ベントの使用が可能(使用回数・使用時間制限付き)
・キルされた後、憑依機能を使うことで任意のプレイヤーを追跡できる

### 実際の動作 / The Reality

インポスター陣営
・ショートカットキーを使用することでベントに入ることができる

クルー陣営
・ベントに入っても即座にはじき出されるため、移動が実質不可能となっている
・設定してある使用回数制限を無視してのベント使用が可能
・キル後、憑依機能自体がそもそも表示されない

ベント内潜伏ができないため、検証できてないですがインポスターがベント内にいるクルーをキルできる挙動となっている可能性も挙げられていました。

ベント周りの検証動画
https://www.youtube.com/watch?v=3kbA_bBfGx4

### このバグに対するあなたの意見 / Your Proposal

ゲーム性を損ない遊ぶほどのできなくなるバグや、そもそもMODをはずしてしまえば通常の挙動で遊ぶことができるため、致命的な問題には感じません。しかし、毎回MODのオンオフを参加者全員に要求する手間が発生するため、対応していただけるとありがたいです。

### バグ発生時のログ / log when issue occur

インポスター時
[ExtremeRolesDumpedLog 2022-12-18T19-31-18.log](https://github.com/yukieiji/ExtremeRoles/files/10253663/ExtremeRolesDumpedLog.2022-12-18T19-31-18.log)
クルー時
[ExtremeRolesDumpedLog 2022-12-18T19-33-09.log](https://github.com/yukieiji/ExtremeRoles/files/10253665/ExtremeRolesDumpedLog.2022-12-18T19-33-09.log)

### Among Usバージョン/ Among Us Version

Among Us v2022.12.12s

### Modバージョン / Mod Version

Extreme Roles v5.0.0.1

### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [x] :アジア/Asia
- [ ] :カスタム/Custom

### プレイヤー人数/Player Num
5人

### 使用したオプション/Use Option

[option.csv](https://github.com/yukieiji/ExtremeRoles/files/10253673/option.csv)

**Comment by yukieiji** [comment]
v5.0.0.2で修正が完了していると思われるのでクローズします

**Comment by yukieiji** [comment]
あとは1チケット1不具合にしてください、読む側も確認する側も手間画がかかります
