### ISSUE TITLE
呪われしもの:クルー役職→インポスター役職

### ISSUE THREAD

**Issue by tkser** [yukieiji/ExtremeRoles#23]
### 役職名 / Role Name
呪われしもの / Noroware （表示名: クルー→インポスター）
### 役職の色 / Role color
白→黒
### 役職の説明 / Role description
あなたはクルーである。然しながらインポスターにキルされるとインポスターへと変化する。

ゲーム開始時、役職はクルーと表示され通常のクルーと同様にタスクが付与される。プレイヤーはこの役職に選ばれたことに気付くことはできない。また、何も起きなければクルー勝利に参加することができる。
但しインポスターがキルしようとした場合、役職が通常のインポスターに変化する。（会議での吊りや他陣営によるキルではこの処理が起きずクルー陣営のまま死亡する）

### 役職の能力 / Role ability
能力自体は通常のクルー及びインポスターと変わりはありません。

##### メリット
- 無役職に配役された場合でもインポスターになる可能性があるため楽しみが増す。
- 無役職COをした場合でも吊る要因ができる
- 吊り意識が向上する
##### デメリット
- 特になし
##### メリット
- クルーからの信用がある人を赤陣営に引き入れることができる。
- 無役職をキルすることで仲間を増やすことができる
##### デメリット
- 特になし

### 陣営 / Team
- [x] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
15人盤面でほぼ無条件でインポスターを1人追加できるのは相当強力な役職に見えます(インポスター3人=>4人に増えるのは相当強いでしょう)

**Comment by tkser** [comment]
では、当役職は必ずしも赤役職になるとは限らないという点でバランスを考えると、インポスターではなく**マッドメイドを実装した上で**マッドメイドに変化するという感じだと良いのではないでしょうか。
また設定でマッドメイドに変化するかインポスターに変化するかを変更できれば、ゲームオーナー側もバランスを取りやすいのではないかと思います。

**Comment by yukieiji** [comment]
> では、当役職は必ずしも赤役職になるとは限らないという点でバランスを考えると、インポスターではなくマッドメイド(狂人)を実装した上でマッドメイドに変化するという感じだと良いのではないでしょうか。
また設定でマッドメイドに変化するかインポスターに変化するかを変更できれば、ゲームオーナー側もバランスを取りやすいのではないかと思います。
インポ3+呪われマッド1やインポ2+呪われインポ1など柔軟に対応できます。

マッドメイドが実装される前提で話されてますが、現状実装する予定はないです

> また追記ですが他陣営にキルされた場合に覚醒するかしないかは設定項目にしても良いかもしれません。

そうされた場合、即インポスターバレするんですがそれはいいのでしょうか

**Comment by tkser** [comment]
> マッドメイドが実装される前提で話されてますが、現状実装する予定はないです

そうですか。(マッドメイドや狂人も良い役職だと思うのですが)
そうなら、インポスターへ変化という形になりますね。どちらにせよ覚醒懸念があるのでクルーに白確が置けないというのは赤側のメリットで、白目の人を赤にできるというのはだいぶ違いますがサイドキックのようなものなので、赤2呪われ1でも十分戦えると思います。また、キルしないと覚醒しないという点ではキル促進につながると思います。

> そうされた場合、即インポスターバレするんですがそれはいいのでしょうか

その際は逆にキルされた側も相手が敵陣営の役職持ちというのが分かるので、敵とわかりながら共闘しても良いですし、クールタイムが開けたら打ち合っても良いですしと戦略の幅が広がるのかなと思います。ただ設定自体はデフォルトではdisableかなとは思います。

あとは15人盤面以外で10人盤面の場合でも登用することはできると思うので存在するメリットはあると思います。

**Comment by yukieiji** [comment]
> そうですか。(マッドメイドや狂人も良い役職だと思うのですが)

良い役職=バランスが取れているとは限らないです。
もし、本当に欲しい場合は新しいチケットを発行して、メリットとデメリットをきちんと記載して下さい

> そうなら、インポスターへ変化という形になりますね。どちらにせよ覚醒懸念があるのでクルーに白確が置けないというのは赤側のメリットで、白目の人を赤にできるというのはだいぶ違いますがサイドキックのようなものなので、赤2呪われ1でも十分戦えると思います。また、キルしないと覚醒しないという点ではキル促進につながると思います。

上にも書いてあるようにデメリット無しでインポスターが増えるのは強すぎると思います

> その際は逆にキルされた側も相手が敵陣営の役職持ちというのが分かるので、敵とわかりながら共闘しても良いですし、クールタイムが開けたら打ち合っても良いですしと戦略の幅が広がるのかなと思います。ただ設定自体はデフォルトではdisableかなとは思います。

基本的に第三陣営は完全にインポスターが敵なのでキル可能なインポスターが分かるのはどうなのでしょうか？(アサシンはキルできないし残しておくメリットはあるので問題はないと思ってます)

**Comment by tkser** [comment]
> 上にも書いてあるようにデメリット無しでインポスターが増えるのは強すぎると思います

では、通常のインポスターでない赤役職に変化するというのはどうでしょうか。例えば覚醒したインポスター(仮)はサボタージュが行えない、他のインポスターよりもキルクールが長いなど。
ただ単純にインポ4:その他11は赤が強いことはわかりきっているので、登用条件としてはインポ2呪われ1やインポ2呪われ2(他陣営にキル吊られるなどして減る)などを想定しています。なので覚醒したインポスター(仮)は普通のインポスターよりも性能高めでも良いと思っています。(設定項目)
ただ懸念点としては序盤の覚醒していない状態でのキルペースが落ちてしまう問題ですが、これは上記の覚醒後が強くなるという点でカバーできると思ってます。
強いて言うなら覚醒前に他陣営にキルないしはつられてしまい減ってしまう場合、インポスターが不利になる状況ですが、誰からも誰がこの役職かがわからない為、議論力で呪われ懸念のあるクルーを吊るなどでき、負け確定とまでは行かない上に疑心暗鬼が増えるので議論に面白みが増すと思います。またこの役職を登用するときは他インポスターを強化することによってこの問題もクリアできると考えています。

> 基本的に第三陣営は完全にインポスターが敵なのでキル可能なインポスターが分かるのはどうなのでしょうか？(アサシンはキルできないし残しておくメリットはあるので問題はないと思ってます)
ではなかったことにしていただいて構いません。

**Comment by yukieiji** [comment]
> では、通常のインポスターでない赤役職に変化するというのはどうでしょうか。例えば覚醒したインポスター(仮)はサボタージュが行えない、他のインポスターよりもキルクールが長いなど。
ただ単純にインポ4:その他11は赤が強いことはわかりきっているので、登用条件としてはインポ2呪われ1やインポ2呪われ2(他陣営にキル吊られるなどして減る)などを想定しています。なので覚醒したインポスター(仮)は普通のインポスターよりも性能高めでも良いと思っています。(設定項目)

最初と最後で矛盾してますが結局どっちなのでしょうか
ここの登用条件ってのは何をしたときの条件を指すのですか

この役職が入れば基本的にキルペースが上がるはずなのでインポスターが4人残って会議に挑むことのほうが多いはずです。1人が落ちてもインポスターは3人、一時的には4人になるってことを考えればキルペースは3人以上であることを想定すべきでしょう。(私は能力を考える際は最強想定の能力をベースに考えてます)

> 誰からも誰がこの役職かがわからない為、議論力で呪われ懸念のあるクルーを吊るなどでき、負け確定とまでは行かない上に疑心暗鬼が増えるので議論に面白みが増すと思います。

上にも書いてありますが面白いとバランスは必ずしも同じ方向を向くとは限りません

**Comment by tkser** [comment]
> 最初と最後で矛盾してますが結局どっちなのでしょうか

例えばインポ3呪われ1の配役だと明らかに赤陣営が強くなるので覚醒後を弱くする、逆に2-1の配役だと赤陣営が弱くなるので覚醒後を強くするといった形です。

> ここの登用条件ってのは何をしたときの条件を指すのですか

実際にゲームに登用する際にどのように配役することを想定しているかということです。

> この役職が入れば基本的にキルペースが上がる(キルペースが上がれば基本第三陣営も潰す)はずなのでインポスターが4人残って会議に挑むことのほうが多いはずです。1人が落ちてもインポスターは3人、一時的には4人になるってことを考えればキルペースは3人以上であることを想定すべきでしょう。(私は能力を考える際は最強想定の能力をベースに考えてます)

はい。なのでふにんがすのように議論での吊りが多い卓では上記のようにインポ2呪われ1(or2)を想定しています。その際赤陣営が弱くなるので設定で呪われの覚醒後を強くする感じです。

**Comment by yukieiji** [comment]
> 例えばインポ3呪われ1の配役だと明らかに赤陣営が強くなるので覚醒後を弱くする、逆に2-1の配役だと赤陣営が弱くなるので覚醒後を強くするといった形です。

弱い強いを設定で変えれるということでしょうか、基本的にキルクールの調整オプションは自動生成されるのでこちら側で設定することは出来ないです。またインポスターがサボタージュを使用できなくする事も不可能です

> はい。なのでふにんがすのように議論での吊りが多い卓では上記のようにインポ2呪われ1(or2)を想定しています。その際赤陣営が弱くなるので設定で呪われの覚醒後を強くする感じです。

インポスター2人で15人はキツイでしょう(インポスター3人でもキツイときはキツイですし)。クルーが普段より1人多くキルペースが上がっているということを考えれば死体は自然と見つかりやすくはなるのではないでしょうか(例え覚醒したと言っても最初から3人いるのとは大きく違うでしょう)
このMODで強力なインポスター役職は少ないのでインポスター2人でどうにかするのも難しいでしょう

**Comment by yukieiji** [comment]
返信が無いので私からの意見を一つ(この返信に1ヶ月近く反応がない場合、クローズさせていただきます)

- この役職をCOしにくい足かせクルー役職とする
  - 能力例：吊ったら確実にクルー1人を持っていく(これは強すぎるので考え直さないといけない、COした時に7～8割程度吊れる位のバランスがいい気がする。この状態だとCOした場合5割も吊らないと思います)
  - ゲーム開始一定時間経過後にインポスターに切られたらインポスターの勝利条件が自分の勝利条件として再設定される
    - 再設定後の全プレイヤーの会議のチャットに通知が入る
  - インポスターに勝利条件が設定されている状態の能力
    - 吊っても能力が発動しない
    - シェリフでキルできる
    - サボタージュ治せない
    - タスク出来ない
    - クルーの勝利に乗れない
    - ベント入れる
    - インポスターからもキルされる(覚醒時数秒間無敵)
    - 覚醒させたインポスターが落ちれば自分も死ぬ
