### ISSUE TITLE
アサシン会議で投票が出来ない

### ISSUE THREAD

**Issue by seono968** [yukieiji/ExtremeRoles#230]
## バグの情報 / Info of bug
アサシンが追放され、アサシン会議が呼ばれた際、会議画面で投票が出来ない
### 期待される動作 / Your Expectation
会議画面でマーリンと思われる人物に任意で投票出来る
### 実際の動作 / The Reality
アサシン会議の会議画面で対象の選択が出来ません
投票の出来ない画面が割れた状態(＝アサシン本人が死亡判定？)になっています
### このバグに対するあなたの意見 / Your Proposal
死亡判定の切り替わりがバニラのアップデートで変更されたからかと思います。
### バグ発生時のログ / log when issue occur
[ExtremeRolesDumpedLog 2022-12-18T21-37-26.log](https://github.com/yukieiji/ExtremeRoles/files/10253833/ExtremeRolesDumpedLog.2022-12-18T21-37-26.log)
[ExtremeRolesDumpedLog 2022-12-18T21-37-52.log](https://github.com/yukieiji/ExtremeRoles/files/10253834/ExtremeRolesDumpedLog.2022-12-18T21-37-52.log)
[ExtremeRolesDumpedLog 2022-12-18T21-38-08.log](https://github.com/yukieiji/ExtremeRoles/files/10253835/ExtremeRolesDumpedLog.2022-12-18T21-38-08.log)
一応会議を呼んだタイミング、投票確定、勝利画面の三段階でログを出してあります
ローカル多重起動での再現ログです
### Among Usバージョン/ Among Us Version
2022.12.14s
### Modバージョン / Mod Version
5.0.02(最新)
### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [x] :アジア/Asia
- [ ] :カスタム/Custom

### プレイヤー人数/Player Num
10人～
再現では6名です
### 使用したオプション/Use Option
[option.csv](https://github.com/yukieiji/ExtremeRoles/files/10253840/option.csv)

**Comment by yukieiji** [comment]
古いバージョン(v5.0.0.0とv5.0.0.1)では正しく動作しましたか？

**Comment by seono968** [comment]
まず最初に起きたのは5.0.01でした
5.0.0.0では確認していません、確認してみますね

**Comment by seono968** [comment]
5.0.0.0でも同様のバグを確認しました

**Comment by yukieiji** [comment]
画面が割れている状態でも普通に投票できましたけど、投票できませんでしたか？

**Comment by seono968** [comment]
投票出来ませんでしたね
画面クリックしても投票のUIが出ませんでした
今回現象が起きたのは全てゲストです、ホストアサシンは確認していません
