### ISSUE TITLE
名前未定(支援したプレイヤーの陣営の勝利に相乗りする能力):第三陣営の役職

### ISSUE THREAD

**Issue by Nushigami** [yukieiji/ExtremeRoles#24]
### 役職名 / Role Name
※名称未定(サポーターが既にいるので)

### 役職の色 / Role color
※名前が決まった時に決めたい

### 役職の説明 / Role description
- 支援しているプレイヤーの陣営の勝利に相乗りする第三陣営の役職。
   - 勝利条件:｢支援｣を使った人の陣営が勝利する。
   - ｢支援｣でそのプレイヤーを支援して、その人の陣営を勝利に導こう。

### 役職の能力 / Role ability

- 支援(仮名称)
→対象のプレイヤーの陣営の勝利に相乗りができる。

- 以下注意点
  - 自分が死亡してもその陣営が勝利すれば相乗りができる。
(第三陣営のニートの様に生存している必要はない。)
  - 自分は支援している人の陣営は分かりません。
(その人の陣営を推理して適切な援護をしましょう。)
  - 相手は自分が支援していることを知る情報はありません。
(騙ることもできるということです。)
  - 能力を使用しないと勝つ条件がないです。
(抱え落ちに気をつけて。)

### 他陣営への影響 / Effect on other teams
自分の陣営か他の陣営についているか分からないため、状況によって変わる。

### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
これ最後の最後に「支援」を行えば常に勝てるつまらない役職だと思うのでうがどうでしょうか

**Comment by Nushigami** [comment]
> これ最後の最後に「支援」を行えば常に勝てるつまらない役職だと思うのでうがどうでしょうか

最後に支援するとなると抱え落ちして勝てなくなるリスクも付きまとうと思います。

**Comment by yukieiji** [comment]
> 最後に支援するとなると抱え落ちして勝てなくなるリスクも付きまとうと思います。
(ジャッカルのサイドキックみたいに最後まで残しておくと強いけどその前にキルされたら意味が無い的な感じです。)

ジャッカルと違ってキルも何も出来ない役職のため基本的にグレー位置に立つことはないでしょう
グレー位置に立たなければ吊られない、クルーと複数人行動をしていれば基本キルされないので抱え落ちはまず無いでしょう

**Comment by Nushigami** [comment]
> グレー位置に立たなければ吊られない、クルーと複数人行動をしていれば基本キルされないので抱え落ちはまず無いでしょう

それはジャッカルもキルしなければ同じことが言えると思います。

**Comment by yukieiji** [comment]
> それはジャッカルもキルしなければ同じことが言えると思います。

いいえ、ジャッカルはベントが使えるかつタスクが出来ないという点で同じことは言えません
第三陣営であろうとタスクをやることは出来ます

**Comment by Nushigami** [comment]
> ジャッカルはベントが使えるかつタスクが出来ないという点で同じことは言えません
第三陣営であろうとタスクをやることは出来ます

その場合、ジャッカルはベントを使わなければいいですし、、、この役職自体はタスクないため同じなように思いますが、、、(+この役職に緊急タスクができない仕様にすればいいのか)

**Comment by yukieiji** [comment]
> その場合、ジャッカルはベントを使わなければいいですし、、、この役職自体はタスクないため同じなように思いますが、、、(+この役職に緊急タスクができない仕様にすればいいのか)

どちらにせよ潜伏ジャッカルは強いですし、基本的に浮き位置にはならないでしょう
更に、この役職は生きていようがゲームが終わるのでクルーは殺すメリットすら無いでしょう

**Comment by Nushigami** [comment]
基本的に浮き位置にはならないでしょう
更に、この役職は生きていようがゲームが終わるのでクルーは殺すメリットすら無いでしょう

**Comment by Nushigami** [comment]
押すボタン間違えました、、、
> 基本的に浮き位置にはならないでしょう。

どんなに気をつけても死んでしまうのがこのゲームだと思うのですが

> クルーは殺すメリットすら無いでしょう

クルー以外の他の陣営を支援するとPP盤面を作ることができるので、、、一応はあると思います。

最終盤面で能力を残していても確実に勝てるというわけでもないです。(白位置が黒だったとか、勝ちが遠い陣営だったりとかするため)
(ただ普通にインポスター陣営だけを支援する狂人でもいいですが、、、)

**Comment by yukieiji** [comment]
> どんなに気をつけても死んでしまうのがこのゲームだと思うのですが

常にクルーと2人以上のクルーと行動していれば吊られないですしキルされないでしょう。何なら、誰も行かないような場所に引き込もってしまえばキルされることなんてまず無いでしょう
更に、COするデメリットすら無いのでCOして白の味方をするだけで勝利できるでしょう(基本的に白が有利なゲームで白が増えるので黒に加担するメリットは一切ないでしょう)

> クルー以外の他の陣営を支援するとPP盤面を作ることができるので、、、一応はあると思います。

正直黒に加担するメリットが一切見えてこないのです

> 最終盤面で能力を残していても確実に勝てるというわけでもないです。(白位置が黒だったとか、勝ちが遠い陣営だったりとかするため)
(ただ普通にインポスター陣営だけを支援する狂人でもいいですが、、、)

初期にCOしている人で生き残っていればほぼ白ですし、騙ってるとしても最終盤面であれば勝てる確率のほうが高いでしょう

**Comment by Nushigami** [comment]
素直に狂人(インポスター陣営だけを支援するやつ)を作った方が良いですね、、、
(人外村とか第三陣営の比率が高いところに入れたらこの能力も面白そうですが、、、)

**Comment by yukieiji** [comment]
この役職についてはクローズでよろしいですか？

**Comment by Nushigami** [comment]
はい やっときます
