### ISSUE TITLE
オープナーの強化案

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#243]
### 追加する機能の詳細 / Feature details
オープナーの強化案です
3つ思いつきました

#### １：設定で開ける扉を増やす
オプションで開ける扉の数を2以上にすることで、能力発動時にオープナーから近い順に複数の扉を開けられるようになる

#### ２：開けっ放しにできるようにする
タスク進捗によって能力が進化。開けた扉が一定時間閉まらなくなる
設定された時間の間、開けっ放しになっている扉にサボタージュで扉を閉めるアイコンが押せなくなる

#### ３：ベントも開けられるようにする
タスク進捗で能力が進化
能力発動時にベントも開けてベントにいるプレイヤーを全員、その時ベントから出たら着地する予定のベントから引きずり出す
メリーの陣にいるプレイヤーは引きずり出せない

#### 追加するオプション
１：開けられる扉の数
２：開けっ放し解禁に必要なタスク進捗
２：開けっ放しの時間（扉開けで開いた扉はここで設定した時間の間閉まらない）
３：ベント開けに必要なタスク進捗

### 機能を追加するメリット / Benefits of adding features
オープナーを強化することで使用率増加が見込める

**Comment by yukieiji** [comment]
これらの強化案はどういうコンセプトのオープナーに元提供するのかがいまいち理解できないです
個人的には役職の強化やリワークはコンセプトがないと役職の方向性やコンセプトを無意味に失うと思っています

**Comment by melonjagaimo** [comment]
オープナーのコンセプトとして「扉を開けて移動を快適にする」というものを考えておりました。
1つ目は単純に開ける扉の数を増やしてより味方に貢献しようとしたものです。
2つ目はせっかく開けた扉がすぐ閉められないようにしたものです。

一方3つ目は「扉だけでなく、他のものも開けられれば面白そうだ」という考えのもと、ベントも開けられるようにしたものです。

**Comment by yukieiji** [comment]
> 1つ目は単純に開ける扉の数を増やしてより味方に貢献しようとしたものです。
2つ目はせっかく開けた扉がすぐ閉められないようにしたものです。
一方3つ目は「扉だけでなく、他のものも開けられれば面白そうだ」という考えのもと、ベントも開けられるようにしたものです。

私が言いたいのはこれらの強化を施すことによってオープナーがどういうコンセプトになるかってのが見えてこないです
1と2はベースのコンセプトの延長ですが結局強さも価値観も変わってない、3はオープナー自体のコンセプトが崩壊してないですかってことです
