### ISSUE TITLE
[クルー陣営] : サイキック (覚醒後、生きている人外の数がわかる)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#248]
### 役職名 / Role Name
サイキック

### 役職の色 / Role color
明るい紫色

### 役職の説明 / Role description
タスク進捗と死者数が両方一定以上になると覚醒。TORの同名役職を改変
1度だけ生きているインポスター・ニュートラルの数を把握できる

### 役職の能力 / Role ability

・ゲーム開始時は通常のクルーとしてアサインされ、死者の数が一定以上かつ自身のタスク進捗が一定以上になった場合に覚醒する。

・能力ボタンを押して「霊能」能力を発動すると幽霊と会話して、次の会議開始時に「今生きているインポスター陣営の数」と「今生きているニュートラル陣営の数」がサイキック本人にチャット形式で通知される。この能力はゲーム中1度しか発動できない。
例：インポスター陣営は1人生きていて、ニュートラル陣営は0人生きている

#### 固有オプション
覚醒に必要な死者数
覚醒に必要なタスク進捗

#### メリット
吊り進行かタスク進行かを決める手掛かりになる
食い合いが起きたかもしれないことを把握できる

#### デメリット
死者数も覚醒条件に含むので覚醒前に死亡しやすく、騙りが起きやすい

### 他陣営への影響 / Effect on other teams
生きているインポスター陣営・ニュートラル陣営にとっても、キルペース調整や食い合いの有無を把握できる有益な情報になるだろう。もしヒプノティストが、生きているニュートラル陣営が自身のドールのみだと把握した場合その場でPPに誘導できる。
デメリットにあるように他の覚醒クルー役職よりも覚醒前死亡が起きやすく、騙りやすい。しかしそれはCOの信用が低いことにもつながる。サイキックCOが出た場合、そのプレイヤーの過去の行動を振り返ることが審議を推理するのに役立つだろう。

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> TORの同名役職を改変

全く同じ機能を提供するのであれば同じ役職名でも問題はないとは思いますが能力も仕様も異なる同じ役職名を提供するのは個人的にしたくはないです(海外の方が使った時に余計なことを考える必要が出てきます、妖狐は役職と能力的にそうなりましたが)

**Comment by melonjagaimo** [comment]
では、役職の名前をサイキックに変更します
