### ISSUE TITLE
ローカルにおいてシオンの「ダミープレイヤー」召喚が出来ない

### ISSUE THREAD

**Issue by ankomon** [yukieiji/ExtremeRoles#249]
## バグの情報 / Info of bug

シオンを使おうとローカルのロビーでFキー(連打)をしましたが、ダミープレイヤーが召喚されません
一度、Among Usをアンインストールし、ローカルファイルを消去して、入れ直してみましたが
それでも、召喚されませんでした

### 期待される動作 / Your Expectation

シオンの機能を使う為に、一緒にやる人は居ないのでダミープレイヤーを召喚してゲームを開始しようとしましたが、シオンがオンで、Fキーを押してもダミープレイヤーが召喚されませません

### 実際の動作 / The Reality

プレイヤーダミーを召喚しようとしていますが、召喚されていないように見えます。人数も増えていません
https://user-images.githubusercontent.com/101639771/214569461-20b4cf41-24c3-4968-b5c7-3a33b52fdfe1.mp4
個人情報云々で大部分隠してしまっています
大まかにFキー(と横のGキー)を押されるキーボードとその状態でのPC画面を映しています

### このバグに対するあなたの意見 / Your Proposal

バグであるならば、修正されてほしいです。私のPCが問題だった場合は、何事もなくて良かったと安堵して絶望します

### バグ発生時のログ / log when issue occur

[ExtremeRolesDumpedLog 2023-01-25T21-48-04.log](https://github.com/yukieiji/ExtremeRoles/files/10499352/ExtremeRolesDumpedLog.2023-01-25T21-48-04.log)

### Among Usバージョン/ Among Us Version

Among Us v2022.12.14s

### Modバージョン / Mod Version

Extreme Roles v.5.0.0.6

### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [x] :アジア/Asia
- [ ] :カスタム/Custom
オンラインはアジアになっています

### プレイヤー人数/Player Num

1人

### 使用したオプション/Use Option

[option.csv](https://github.com/yukieiji/ExtremeRoles/files/10499368/option.csv)

**Comment by yukieiji** [comment]
AmongUs v2022.12.08の対応作業中にシオンでダミープレイヤーを召喚してプレイするとブラックアウトする重篤な不具合が見つかっていて修正が終わってない(原因も把握しきれていない)ため、現状(2023/01/25T23:32)シオンの「ダミープレイヤー」を召喚してプレイする機能は意図的に使えないようになっています

[v5.0.0.0リリースノート](https://github.com/yukieiji/ExtremeRoles/releases/tag/v5.0.0.0)等には記載していましたがWikiへの記載が漏れていましたので記載しておきます

**Comment by yukieiji** [comment]
一応このチケットは上記の不具合が解決しリリースされるまでオープンのままにしておきます

**Comment by ankomon** [comment]
分かりました。ありがとうございます

**Comment by yukieiji** [comment]
v5.1.0.0の完成に目処が立ったので再調査した結果以下のことが判明したため、優先度を最低に再セットします

- このバグの原因
  - ダミープレイヤーにインポスターがアサインされていない
- 修正検討
  - 上記を解消するためにインポスターをアサインするロジックを実装したが[BepInEx側の不具合](https://github.com/BepInEx/BepInEx/issues/550)を発見
    - これを回避して実装することも出来なくはないがExMoの開発(#223 )に影響が出ることが予想される
    - 更にこの不具合が修正されたとしてもBepInEx 6.0.0-be663は[ExSとの不具合](https://github.com/BepInEx/BepInEx/issues/514)、BepInEx 6.0.0-be665はビルドすら出来なかった記憶があるため対応に時間がかかる

**Comment by yukieiji** [comment]
BepInEx側の不具合修正が完了したとのこととExSとの不具合も修正の目処がたったため、バグ/Bugのラベルを外します
ExtremeRoles.BepInExInstallerでは対処できないBepInExのアップデートが必要なため公式のアップデート後になりますがそこで対応を行います

**Comment by ankomon** [comment]
ありがとうございます

**Comment by yukieiji** [comment]
BepInEx側の更新が来たので対応ブランチのコミット[20d99851784f9c85b14692b35fda7a62f53adcdd](https://github.com/yukieiji/ExtremeRoles/commit/20d99851784f9c85b14692b35fda7a62f53adcdd)にて修正が完了、修正済みラベルを付与します
修正版リリースは公式リリース対応予定のv6.0.0.0にセットします
