### ISSUE TITLE
マインドアイ(心眼)※仮名:クルー陣営

### ISSUE THREAD

**Issue by Nushigami** [yukieiji/ExtremeRoles#25]
### 役職名 / Role Name
マインドアイ

### 役職の色 / Role color
黒系統

### 役職の説明 / Role description
- 壁越しの情報を得られるクルー陣営の役職。
  - 能力｢心眼｣は視野が極小になる等のデメリットがあるかわりに範囲内のプレイヤーの位置がわかる。

### 役職の能力 / Role ability

- 心眼
→デメリットがあるかわりに範囲内のプレイヤーの位置がわかる。(ベントの中、死体も含む)
- デメリットの内容
  -  視野が極小になる。
  - 通報のレンジがショートになる。
  - アドミン、バイタル、ドアログが使えなくなる。

`メリット`
- 普段では分からない壁越しの情報がわかる。
- 停電中に使用すれば、情報が増える。

`デメリット`
- 視野が狭いため、その時に通過したプレイヤーの色が分からない。

`配信者へのデメリット`
-  能力使用中は真っ暗なので配信向きじゃないこと
(前は常にこの能力が発動している予定だったのでマシにはしたが)

### 他陣営への影響 / Effect on other teams
物陰でキルがしづらくなる?からキル陣営がやりづらくなる

### 陣営 / Team
- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> デメリットがあるかわりに範囲内のプレイヤーの位置がわかる。(ベントの中、死体も含む)

範囲内のプレイヤーの位置がわかるならこの能力自体のデメリットをすべて打ち消している気がします

**Comment by Nushigami** [comment]
能力の使用中はプレイヤーの位置がわかるだけで色が分からないので、、、

**Comment by yukieiji** [comment]
> 能力の使用中はプレイヤーの位置がわかるだけで色が分からないのでそこら辺で調整しているつもりです。
(元々ずっと暗闇のつもりでしたがずっとわかるのもあれだし、配信映えしないなと思ったので)

他の人の視認情報を組み合わせればどれくらいの場所にどのプレイヤーが居たか絞れるので、プレイヤーの位置がわかればそのプレイヤーが誰かは明白に分かると思います

**Comment by Nushigami** [comment]
> 他の人の視認情報を組み合わせればどれくらいの場所にどのプレイヤーが居たか絞れるので、プレイヤーの位置がわかればそのプレイヤーが誰かは明白に分かると思います

確かにそうですが、そのことに議論時間を使うのと死亡者の位置を自身が騙ることも可能だとは思います。
(それに視認が出るならそもそもの場所がわかると思います。)

**Comment by yukieiji** [comment]
> 確かにそうですが、そのことに議論時間を使うのと死亡者の位置を自身が騙ることも可能だとは思います。
(それに視認が出るならそもそもの場所がわかると思います。)

会議時間うんぬんではなくて、能力自体のデメリットを完全に消せてしまう部分がダメではないでしょうか？

**Comment by yukieiji** [comment]
> それでもやっていることはスーパーバイザーと同じだと思うんですよ、、、(デメリット増やすとしても能力発動中タスク・緊急タスクができないとかぐらいしか思い浮かばないし、、、)

スーパーバイザーはアドミンしか使用できないです、それもデフォルトでは3秒しか使えない。その3秒ですべての人の情報を記憶するのは相当困難なはずです。
また、アドミン自体は部屋にいる位しかわからないのでそこで何をやっていたかはプレイヤーがウソを付くことも可能です

この役職は特定の範囲内のすべてのプレイヤーの軌跡を知ることが出来ます。それはそこに居たプレイヤーが何をやっていたのか全て掌握することが出来ます(キルなんかすれば座標が飛ぶのですぐ理解することが出来るでしょう)

**Comment by Nushigami** [comment]
まぁそっか
範囲が小さすぎてもこの能力は弱いですし、これ常時真っ暗でも、メリットに釣り合うか？
常時真っ暗だと配信映しないだろうし、、、うーん

**Comment by Nushigami** [comment]
改善案が思いうかばないのでクローズします
