### ISSUE TITLE
About the display of role names after banishing players

### ISSUE THREAD

**Issue by xiaojinna** [yukieiji/ExtremeRoles#250]
### 追加する機能の詳細 / Feature details
プレイヤーを追放する際に、追放されたプレイヤーの職業を表示します。
例：「プレイヤー名」は「職業名」

When exiling a player, the role of the exiled player is displayed.
For example: [Player name] was the [Role name]

### 機能を追加するメリット / Benefits of adding features
プレイヤーを追放した後、プレイヤーキャラクターを通じて次のラウンドの対応を行うことができ、より良いゲーム体験を向上させることができます。

After the players are exiled, the next round of response can be carried out through the players' roles to improve the better game experience.

**Comment by yukieiji** [comment]
I think it's generally all right.
I would like to check the following points
- Is it Okay if this function is only available if 'Confirm Ejects' in AmongUs vanilla options is enabled?
  - Because some people like the current features.

**Comment by yukieiji** [comment]
Some ExR players and I only want the current ConfirmEjects on behaviour
So the current behaviour and this behaviour must be designed so that there is no conflict.

**Comment by yukieiji** [comment]
When adding options, some people will want to check Neutral or Crewmate only, so we need to consider options that take this into account.

**Comment by xiaojinna** [comment]
> When adding options, some people will want to check Neutral or Crewmate only not role name, so we need to consider options that take this.

I hope that the role of impostor can be displayed, and these changes should not cause some conflicts. Of course, you can also set whether to display these.

**Comment by xiaojinna** [comment]
> Some ExR players and I only want the current ConfirmEjects on behaviour So the current behaviour and this behaviour must be designed so that there is no conflict.

I don't think there will be any problem. I have studied the code of other mods. They just replace or add the exiled information.

**Comment by yukieiji** [comment]
> I don't think there will be any problem. I have studied the code of other mods. They just replace or add the exiled information.

I think it's a problem because some of the rules I know of are based on the presence of an imposter display.
And it should be possible to create a wider range of rules with such switching rather than just replacing them

**Comment by yukieiji** [comment]
Set milestone v6.0.0.0

**Comment by yukieiji** [comment]
Change milestone v5.2.0.0 to v6.0.1.0, because updated AmongUs .

**Comment by yukieiji** [comment]
Implementation and release completed in [v7.1.0.0](https://github.com/yukieiji/ExtremeRoles/releases/tag/v7.1.0.0)
