### ISSUE TITLE
最新ExRv5.1.0.1＆ExSのzipからの起動時modを認識しない

### ISSUE THREAD

**Issue by Kurato-Tsukishiro** [yukieiji/ExtremeRoles#254]
## バグの情報 / Info of bug
最新[ExR v5.1.0.1＆ExS 5.0.0.8]の[zip](https://github.com/yukieiji/ExtremeRoles/releases/download/v5.1.0.1/ExtremeRoles-v5.1.0.1.with.Extreme.Skins.zip)をダウンロードした場合modを認識しない

### 期待される動作 / Your Expectation
- AmongUs ver2022.12.14sが導入されたフォルダに[ExtremeRoles-v5.1.0.1.with.Extreme.Skins.zip]を解凍して起動すると、ExRが読み込まれる。

### 実際の動作 / The Reality
- AmongUs ver2022.12.14sが導入されたフォルダに[ExtremeRoles-v5.1.0.1.with.Extreme.Skins.zip
]を解凍して起動するとバニラ状態で起動されてしまう
  - 4人で検証
    - BepInExのみ読み込まれ、バニラ状態で起動した人が2人いた。
    - BepInExすら読み込まれず、バニラ状態で起動した人が2人いた。
      - この二人はlog取得できていない。
        - log取得できなかったうちの一人は[パスに全角文字を含んだ状態で]起動していた。
        - パスから全角を抜いた所、BepinExのみが読み込まれたlogが出力され、バニラ状態で起動した

- 旧バージョンのExRからmod内で更新をかけた場合、正常にExtremeRoles-v5.1.0.1が起動した。
  - [発端]起動できた人とできていなかった人が混在し、調査
    1. 起動できなかった人が2人いた。
    2. 起動できていなかった人のlogを確認した所、BepInExのロードのみ行われていた。
    3. 起動できた人(元々Mod内アップデートしていた人)が、新規インストールの形で導入した。
    4. 新規インストールでは起動できず、logが生成されなかった。(パスに全角含む状態)
    5. 別の起動できていた人(Mod内アップデート済み)も、新規インストールを試した。
    6. その人も起動できず、logが生成されなかった。
    7. 起動できなかった2人がExRver5.0.0.6から、mod内アップデートを試みたところ起動した。

### このバグに対するあなたの意見 / Your Proposal
- 修正してほしいです。
- [[ExtremeRoles-v5.1.0.1.with.Extreme.Skins.zip](https://github.com/yukieiji/ExtremeRoles/releases/download/v5.1.0.1/ExtremeRoles-v5.1.0.1.with.Extreme.Skins.zip)]内のdllに問題があると考えられます。 
  - 元々旧バージョンで起動していたフォルダに、zip内のdllを導入した所、同じエラーが生じ起動できませんでした。
  - zipから新規インストールした起動不能なフォルダのdllを、Latestのassetのdll([ExtremeRoles.dll](https://github.com/yukieiji/ExtremeRoles/releases/download/v5.1.0.1/ExtremeRoles.dll)と[ExtremeSkins.dll](https://github.com/yukieiji/ExtremeRoles/releases/download/v5.1.0.1/ExtremeSkins.dll))と置き換えた場合正常に起動できました。
  - [ExtremeRoles-v5.1.0.1.zip](https://github.com/yukieiji/ExtremeRoles/releases/download/v5.1.0.1/ExtremeRoles-v5.1.0.1.zip)からの新規インストールは正常に起動できました。

### バグ発生時のログ / log when issue occur
- Modが起動できていない為dump形式のlogは取得できませんでした。
- BepInEx直下のlogになります。
  - [LogOutput.log](https://github.com/yukieiji/ExtremeRoles/files/10715316/LogOutput.log)
  - [LogOutput (1).log](https://github.com/yukieiji/ExtremeRoles/files/10715317/LogOutput.1.log)
  - [LogOutput.log](https://github.com/yukieiji/ExtremeRoles/files/10715338/LogOutput.log)(初回全角パス使用し出力されなかった人のlog)
```log
[Error  :   BepInEx] Error loading [Extreme Roles 3.2.99]: System.TypeLoadException: Could not resolve type with token 0100008f from typeref (expected class 'GameOptionsData' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
  at BepInEx.IL2CPP.IL2CPPChainloader.LoadPlugin (BepInEx.PluginInfo pluginInfo, System.Reflection.Assembly pluginAssembly) [0x00011] in <cfcb4a496b9a4b168c3cd418c91c4bf3>:0 
  at BepInEx.Bootstrap.BaseChainloader`1[TPlugin].Execute () [0x00284] in <9ce333e69168415e8bcbfda371eec752>:0 
[Warning:   BepInEx] Skipping [Extreme Skins 3.2.1] because it has a dependency that was not loaded. See previous errors for details.
[Message:   BepInEx] Chainloader startup complete
```

### Among Usバージョン/ Among Us Version
Among Us v2022.12.14s

### Modバージョン / Mod Version
起動不能の為、期待されるバージョン
Extreme Roles v5.1.0.1

### リージョン/Region

- [x] :北アメリア/Noth America
- [x] :欧州/Europa
- [x] :アジア/Asia
- [x] :カスタム/Custom

### プレイヤー人数/Player Num
1人

### 使用したオプション/Use Option
起動ができない為、エクスポート不可能

**Comment by yukieiji** [comment]
ExtremeRoles-v5.1.0.1.with.Extreme.Skins.zipの内部ビルドが古かったので更新しておきました

**Comment by Kurato-Tsukishiro** [comment]
新規インストールを試し、正常起動した事確認いたしました。
迅速な対応ありがとうございます!
