### ISSUE TITLE
[コンビネーション(第三/クルー)] : ハンター/フェアリー (切られないクルーとそれを吊る第三)

### ISSUE THREAD

**Issue by T-NANANON** [yukieiji/ExtremeRoles#255]
### 役職名 / Role Name
ハンター/フェアリー
### 役職の色 / Role color
緑/薄ピンク
### 役職の説明 / Role description
フェアリーはキルされないクルーで最初からこの能力はありますが覚醒しないと自分の役を把握できません。またＳＫ、催眠、魅惑を受けません。(職が変わるとだるいので)勝利条件はクルーが勝ち、ハンターが勝たないことです。

ハンターはキルができ、それによって切れないフェアリーを探せます。(ベントありサボなし)またボタン能力で対象に一定時間付いていると次の会議での対象の得票数を増やします。(アンブレのボタン能力みたいな感じ)回数制限CTあり
勝利条件は
❶自分が生存時にフェアリーを会議で吊ることです。このときハンターは道連れになり、ゲーム終了時相乗り勝利となります。
(単独勝利だとフェアリーを隠す必要性からアサマリと似るので､相乗りにした。道連れは勝確キル陣営を生まないため)
❷インポスター及びキル能力を持つニュートラルが全滅しており、生存者の半数以上が同じ陣営。

フェアリーが覚醒役である理由はそうでないとハンターには序盤に動く必要性がなくなるからです。
### 役職の能力 / Role ability

フェアリー(クルー陣営)
　・キルされない(ゲッサーなどの特殊キルも失敗する、ラバーズ複合のとき自決しない)キルボタンは光るが反応しない
　・タスクによる覚醒
　　覚醒前からキルされないが、役はクルーとして表示される。覚醒により表示もフェアリーになる
ハンター(ニュートラル)
　・キルありベントありサボなし
　・ボタン能力「出荷箱」
　　近くに他プレイヤーがいると発動でき一定時間接触していると実行される。対象プレイヤーは次の会議で一定票数投票される。CTあり　回数制限あり
### 他陣営への影響 / Effect on other teams
キル陣営
キルされないクルーがおり門番、ダブルキルがしにくくなるが一人キル陣営は増える。最終盤面でフェアリーを告発してハンターとＰＰができる可能性が生まれる
クルー
フェアリーを吊ると1人外道連れになるので吊りたい
フェアリーであるかの確認のため一定のタイミングまでタスク意識が高くなる

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

去年末にな○すさんの枠で彼とリスナーをモチーフにした役職を提案すると言った者です。遅くなりましたが採用してくだされば幸いです。

**Comment by yukieiji** [comment]
フェアリーの覚醒条件って何ですか？

> フェアリーはキルされないクルーで最初からこの能力はありますが覚醒しないと自分の役を把握できません。またＳＫ、催眠、魅惑を受けません。
キルされない(ゲッサーなどの特殊キルも失敗する、ラバーズ複合のとき自決しない)キルボタンは光るが反応しない

[このコメント](https://github.com/yukieiji/ExtremeRoles/issues/73#issuecomment-1140396933)にもある通り中途半端な"対象にならない"ってのが一番面倒くさい(バグの温床にもなる)です。逆に中途半端じゃなくなった場合いくつかの第三陣営の対抗手段がなくなるのでそこを考える必要が出てきます
あとラバーズはコンビネーションなので複合になることは絶対にないです

> ハンターはキルができ、それによって切れないフェアリーを探せます。(ベントありサボなし)またボタン能力で対象に一定時間付いていると次の会議での対象の得票数を増やします。(アンブレのボタン能力みたいな感じ)回数制限CTあり
勝利条件は
❶自分が生存時にフェアリーを会議で吊ることです。このときハンターは道連れになり、ゲーム終了時相乗り勝利となります。
(単独勝利だとフェアリーを隠す必要性からアサマリと似るので､相乗りにした。道連れは勝確キル陣営を生まないため)

フェアリーを探せたとしてもフェアリーを吊ることが不可能な気がします
あと増える得票数は何票でしょうか

> フェアリーが覚醒役である理由はそうでないとハンターには序盤に動く必要性がなくなるからです。

覚醒でも覚醒ではないにしても序盤に動く必要があまりないような気がしますがどうでしょうか

**Comment by T-NANANON** [comment]
> フェアリーの覚醒条件って何ですか？
> 
一定量のタスクの完了です

> [このコメント](https://github.com/yukieiji/ExtremeRoles/issues/73#issuecomment-1140396933)にもある通り中途半端な"対象にならない"ってのが一番面倒くさい(バグの温床にもなる)です。
>
能力を発動したフェンサーに対するキルの感じを想定していたのですがそれが面倒なのでしょうか？

>逆に中途半端じゃなくなった場合いくつかの第三陣営の対抗手段がなくなるのでそこを考える必要が出てきます 
>
マイナーやミッショナリーならば確かに勝つのが難しくなりそうですね。ハンターが落ちているなら無敵がなくなるというオプションを付けるのはどうでしょう
>あとラバーズはコンビネーションなので複合になることは絶対にないです
> 
良かったです
 
> フェアリーを探せたとしてもフェアリーを吊ることが不可能な気がします あと増える得票数は何票でしょうか
> 
そこをいじれるようにしました。制限一回１５票CT１０とかなら一人確実に吊れます。制限４回３票CT5とかなら吊りたい人を追いかけ回せれば吊れます。ある程度幅をもたせた形です。上で「一定」と書いたものはそれぞれ設定で変えられる値という感じでお願いします
> 覚醒でも覚醒ではないにしても序盤に動く必要があまりないような気がしますがどうでしょうか
>
間違えました、フェアリーにキルされないように立ち回られるとハンターはきつすぎるので、最終盤面まで耐えてからフェアリーを見つけ行く運ゲーになってしまいます。なので途中まででもフェアリーが浮きやすくなる覚醒の形にしました。

**Comment by yukieiji** [comment]
> 能力を発動したフェンサーに対するキルの感じを想定していたのですがそれは面倒なのでしょうか？

フェンサーはキルボタンに対する防御でそれ以外は貫通します、それで問題ないなら問題ないですが

> マイナーやミッショナリーならば確かに勝つのが難しくなりそうですね。ハンターが落ちているなら無敵がなくなるというオプションを付けるのはどうでしょう

どっちかというと対象に取らなくなった時点でアンブレイヤーの勝利が消えます

> そこをいじれるようにしました。制限一回１５票CT１０とかなら一人確実に吊れます。制限４回３票CT5とかなら吊りたい人を追いかけ回せれば吊れます。ある程度幅をもたせた形です。上で「一定」と書いたものはそれぞれ設定で変えられる値という感じでお願いします

いじれるようにしましたって言われてもその記載がないので通じてはないですし、実装もされてないのでしましたってのは文章的におかしいとは思います
票数が多いならフェアリーを狙って落とす必要が無い気がします会議で吊られることがない以上、この役職を殺すことは不可能ですし

> 間違えました、フェアリーにキルされないように立ち回られるとハンターはきつすぎるので、最終盤面まで耐えてからフェアリーを見つけ行く運ゲーになってしまいます。なので途中まででもフェアリーが浮きやすくなる覚醒の形にしました。

無敵なのにキルされないように立ち回る必要性がいまいちわからないです、どちらにせよフェアリーは無敵であるが故にタスクで覚醒する前に普通に気づくと思われます

**Comment by T-NANANON** [comment]
> フェンサーはキルボタンに対する防御でそれ以外は貫通します、それで問題ないなら問題ないですが
どっちかというと対象に取らなくなった時点でアンブレイヤーの勝利が消えます
> 
対象にならないじゃなくてキルの処理だけ無効化するなんて芸当（ボマーのボムはつくし爆発するけど自分は爆殺されないとか）は難しいということでよろしいですか？
ならば直接のキルボタンのみ無効化でいいです
> いじれるようにしましたって言われてもその記載がないので通じてはないです
>
伝わるように精進します。自分の頭を整理するとハンターのボタン能力のオプションでいじれるようにしたいのは
追加票数　CT　能力の回数制限　接触しなければならない秒数
の４つです
> ~これは文章的なあやなので無視していただいてもいいですが実装もされてないので"しました"ってのは文章的におかしいとは思います~
>
 よく英語の授業でこういうのを間違えますｗ
<票数が多いならフェアリーを狙って落とす必要が無い気がします会議で吊られることがない以上、この役職を殺すことは不可能ですし
> 
上で整理しましたが回数制限があるのでハンターが吊られないなんてことはないです。

> 無敵なのにキルされないように立ち回る必要性がいまいちわからないです、どちらにせよフェアリーは無敵であるが故にタスクで覚醒する前に普通に気づくと思われます
>
ハンターに斬られて（切れないことから）役バレするとほぼ負けるのでキルされないように立ち回ると思います。
普通に気づくなんてことはなかなかないと思うのですがまあそれはいいです

**Comment by yukieiji** [comment]
> 対象にならないじゃなくてキルの処理だけ無効化するなんて芸当（ボマーのボムはつくし爆発するけど自分は爆殺されないとか）は難しいということでよろしいですか？

キルの処理は個人 => 全員と個人個人で実行するものの二種類あって全員の情報が正しくシンクロできるように作られてないのでチェックするのがめんどいです
キルボタンのみの防御だとSKとかサーヴァント化、ドール化は防ぐことができないですが問題ないですか？

> 追加票数　CT　能力の回数制限　接触しなければならない秒数

回数制限があったとして1回だと吊ること自体が運ゲーになりますし、2回以上だと吊られることがないような気がしますがどうなんでしょうか
第一クルーがこの役職を積極的に落とそうって思うのかも疑問点ではあります

> ハンターに斬られて（切れないことから）役バレするとほぼ負けるのでキルされないように立ち回ると思います。
普通に気づくなんてことはなかなかないと思うのですがまあそれはいいです

相乗り勝利である以上バレて困ることはないんじゃないんでしょうか
普通にプレイしてても気づくと思いますキルが無効化されてるので黒と一緒に居て無傷であったが複数回あれば推測はできるとは思います

**Comment by T-NANANON** [comment]
>キルボタンのみの防御だとSKとかサーヴァント化、ドール化は防ぐことができないですが問題ないですか？
> 
自分としてはハンターがフェアリーがいないことで負け確定になるのを防ぎたいです。キルボタンとは別でSK系統を無効化できませんか？
> 回数制限があったとして1回だと吊ること自体が運ゲーになりますし、2回以上だと吊られることがないような気がしますがどうなんでしょうか 
>
運ゲーにならない為にキルをするんです。キルして切れないならそこで能力を使って勝てます。切れたならフェアリー候補も減ります。勿論最終的には運ゲーになりますが
>第一クルーがこの役職を積極的に落とそうって思うの
かも疑問点ではあります
> 
キル役職である以上吊る必要性はあるかと思います。 
> 相乗り勝利である以上バレて困ることはないんじゃないんでしょうか 
>
フェアリーの勝利条件はクルーが勝ち、ハンターが勝たないことです。

**Comment by yukieiji** [comment]
> 自分としてはハンターがフェアリーがいないことで負け確定になるのを防ぎたいです。キルボタンとは別でSK系統を無効化できませんか？できないならまた別の策を考えます。例えばSKフェアリー,ドールフェアリーを作ってしまうのもありかと。強すぎかもしれませんが

基本的にそういうのを防ぐために"対象にならない"が一番楽な方法です
それ以外は基本的に面倒くさいです

> キルは運ゲー緩和にならないでしょうか。キルして切れないならそこで能力を使って勝てます。切れたならフェアリー候補も減ります。勿論最終的には運ゲーになりますが確率をプレイで限りなく上げられると思います。

キルをする前提で考えられてますがキルをする必要性が有るか個人的に疑問に感じます
キルをしなくてもフェアリーから勝手に分かりに来ますしキルボタンを使って吊られるデメリットを増やしつつ探すことが有るのかが疑問です

> フェアリーの勝利条件はクルーが勝ち、ハンターが勝たないことです。なのでハンターに見つかったらほぼ負けです

そうなると完全にフェアリー自体がフェアリーだと分かる前にハンターを落とし切るという運ゲーになるのでは？

**Comment by T-NANANON** [comment]
> 基本的にそういうのを防ぐために"対象にならない"が一番楽な方法です それ以外は基本的に面倒くさいです
> 
理解できていなかったのですが「ボタンが光るが発動しない」の部分が面倒ということですか？
ならばSK等に関しては光らないということにしてください。
> キルをする前提で考えられてますがキルをする必要性が有るか個人的に疑問に感じます キルをしなくてもフェアリーから勝手に分かりに来ますしキルボタンを使って吊られるデメリットを増やしつつ探すことが有るのかが疑問です
> 
フェアリーが勝手にわかりに来るというのは具体的にどんな感じですか？
> そうなると完全にフェアリー自体がフェアリーだと分かる前にハンターを落としきるという運ゲーになるのでは？
>
それはハンターのキルするタイミング次第かと

**Comment by yukieiji** [comment]
> 理解できていなかったのですが「ボタンが光るが発動しない」の部分が面倒ということですか？
ならばSK等に関しては光らないということにしてください。

基本的にキルだろうがこういう能力はプレイヤー(1人でも複数人でも)を"対象に取った"上で発動するので"対象に取らなくする"が一番楽な方法です
光る光らないにしても"対象に取った"上でそうなるので

> フェアリーが勝手にわかりに来るというのは具体的にどんな感じですか？

時間が経てばタスクによる覚醒が発生しますし黒と一緒に居て死なないという部分から勝手にフェアリーがわかるのではないのでしょうか

> それはハンターのキルするタイミング次第かと

だからハンター目線でキルする必要がないのにキルをするのですかという部分です

**Comment by T-NANANON** [comment]
遅くなりました
> 基本的にキルだろうがこういう能力はプレイヤー(1人でも複数人でも)を"対象に取った"上で発動するので"対象に取らなくする"が一番楽な方法です 光る光らないにしても"対象に取った"上でそうなるので
> 
あまりそのあたりの仕様がわからないのですが対象に取らなくするとどんな風になるのですか?恐らくそれで大丈夫だと思うのですが。
> 時間が経てばタスクによる覚醒が発生しますし黒と一緒に居て死なないという部分から勝手にフェアリーがわかるのではないのでしょうか
だからハンター目線でキルする必要がないのにキルをするのですかという部分です
>
確かにハンターが積極的にキルするという前提で話していましたが、むしろ潜伏してフェアリーの当たりをつける→切ってみて切れたらリスク、切れなかったらほぼ勝ちこんな役でもいいと思います。このときハンターを吊る意味がなくなる問題に関してはフェアリーは覚醒無しでずっと自覚できない、ラバーズのような複合役にすればいいと思います。こうすれば白役含めハンター吊り意識が上がるのではないでしょうか。

**Comment by yukieiji** [comment]
> あまりそのあたりの仕様がわからないのですが対象に取らなくするとどんな風になるのですか?恐らくそれで大丈夫だと思うのですが。

上にも書いたんですが"対象に取らなくする"と第三陣営が死にますのでそれをどう考えるのかの必要があります

> 確かにハンターが積極的にキルするという前提で話していましたが、むしろ潜伏してフェアリーの当たりをつける→切ってみて切れたらリスク、切れなかったらほぼ勝ちこんな役でもいいと思います。このときハンターを吊る意味がなくなる問題に関してはフェアリーは覚醒無しでずっと自覚できない、ラバーズのような複合役にすればいいと思います。こうすれば白役含めハンター吊り意識が上がるのではないでしょうか。

吊り意識を上げたとしてもキルをしないハンターをどうやって吊るのかという問題と潜伏ハンターの場合フェアリーの勝ちの目がほぼ無い問題が未解決な気がします

**Comment by T-NANANON** [comment]
> 上にも書いたんですが"対象に取らなくする"と第三陣営が死にますのでそれをどう考えるのかの必要があります
>
面倒なのでしょうがキルに関しては能力発動したフェンサーのようにして、SK等（できればキルに直接つながるボマーとかの能力も）のみ対象に取らなくするというのは可能ですか？ 
> 吊り意識を上げたとしてもキルをしないハンターをどうやって吊るのかという問題と潜伏ハンターの場合フェアリーの勝ちの目がほぼ無い問題が未解決な気がします
>
どちらの問題も勝利条件に「指定した数以上キルをする」を入れれば解決するかと思います。複雑になりすぎな気もしますが

**Comment by yukieiji** [comment]
> 面倒なのでしょうがキルに関しては能力発動したフェンサーのようにして、SK等（できればキルに直接つながるボマーとかの能力も）のみ対象に取らなくするというのは可能ですか？

それが面倒くさいしバグの原因や今後のメンテコストが増えることが目に見えてわかってるからやりたくはないのです
これはこのディスカッション(#47  )の理由1とほぼ同じです、中途半端な例外を作ると役職を作る or バランスを考えたときにその例外に常に考え対処する必要が出てきてしまい非常に面倒くさいです

> どちらの問題も勝利条件に「指定した数以上キルをする」を入れれば解決するかと思います。複雑になりすぎな気もしますが

指定回数キルでもあまり変わらない気がします、1回なら4人盤面まで潜伏してキルしてセルフで問題ないですし2回でも序盤にキルするメリットが一切ないような気がします(潜伏して生存勝利を狙いつつキルすればいい)
書いてて思い出しましがハンターが4人盤面まで生き残ってればほぼ勝ち確定で負けないですね

**Comment by T-NANANON** [comment]
潜伏ハンター問題について
解決策としてハンターのボタン能力をこのようにします

キルするとキルした相手の残りタスク量のn％「票」を獲得します。タスクがない場合はp「票」。
q票以上たまっている時ボタンを押すと対象の次の会議での得票数をq票増やし、q「票」消費します。(n、p、qは設定する。)
回数制限なしCTあり

試合進行の早さに強さが左右されますが、序盤にキルするメリットができたと思います。

SK等に関しては例外を作れないとのことなので、普通のクルーに予備フェアリーを割り当てておいてフェアリーがいなくなったらフェアリーになるとかでどうでしょう。アサイン順的にもこれの数は設定できたらいいと思います。

**Comment by yukieiji** [comment]
> キルするとキルした相手の残りタスク量のn％「票」を獲得します。タスクがない場合はp「票」。
q票以上たまっている時ボタンを押すと対象の次の会議での得票数をq票増やし、q「票」消費します。(n、p、qは設定する。)
回数制限なしCTは(何回使ったかわかりやすくするため)あり

設定が複雑な上に無駄なボタン処理も含めて誰も使わなくなる気がします

> SK等に関しては例外を作れないとのことなので、予備フェアリー(ただのクルーと変わらない)を割り当てておいてフェアリーが吊り以外でいなくなったらフェアリーに昇格とかでどうでしょう。アサイン順的にもこれの数は設定できたらいいと思います。

1人当たりExRの役職枠は3枠以上確保できないですなので自分がフェアリー予備であるとかは恐らくわかると思われます(第一複雑になりすぎでは)

**Comment by T-NANANON** [comment]
> 設定が複雑な上に無駄なボタン処理も含めて誰も使わなくなる気がします
> 
複雑なのは承知の上ですが、無駄なのはどのあたりでしょう。全消費のほうがわかりやすいでしょうか。あと設定「する」のが複雑なのか「設定」自体が複雑なのかどっちの意味でしょうか
> 1人当たりExRの役職枠は3枠以上確保できないですなので自分がフェアリー予備であるとかは恐らくわかると思われます(第一複雑になりすぎでは)
>
フェアリー予備にアサインされた人は素のクルーになるということです。この設定なら複合役、指定回数キルにするというのはなくてもいいかと思います。

**Comment by yukieiji** [comment]
> 複雑なのは承知の上ですが、無駄なのはどのあたりでしょう。全消費のほうがわかりやすいでしょうか。あと設定「する」のが複雑なのか「設定」自体が複雑なのかどっちの意味でしょうか

"設定する"ことと"設定が複雑であること"は同じ意味だと思ってます(オプション自体は結構簡単に作れるのでオプションの追加コストはあまり考えなくていいです)
基本的に直感的ではない能力のオプションはいくらこうですよって言っても使われないことは経験則的にわかってます
提案されてる能力はタスクの進捗周りで能力が変わることからスレイヴのオプションに近いですが比較的直感的にわかりやすいキルクールが減るスレイヴですら使われない現状を見ると絶対に使われないと言い切れると思います
またユーザーにクールタイム設定の意味が少ないボタンの操作をさせるという部分でUX的にダメだと思ってます

> フェアリー予備にアサインされた人は素のクルーになるということです。この設定なら複合役、指定回数キルにするというのはなくてもいいかと思います。

素のクルーになるという事は"その人は役職にアサインされない素のクルーである"ことを役職決定時に予約しないといけないことになります、そうなるとこの役職はフェアリー、ハンター + 素のクルー複数人というかなり使いにくいコンビネーション役職ということになります

**Comment by T-NANANON** [comment]
> "設定する"ことと"設定が複雑であること"は同じ意味だと思ってます(オプション自体は結構簡単に作れるのでオプションの追加コストはあまり考えなくていいです) 基本的に直感的ではない能力のオプションはいくらこうですよって言っても使われないことは経験則的にわかってます 提案されてる能力はタスクの進捗周りで能力が変わることからスレイヴのオプションに近いですが比較的直感的にわかりやすいキルクールが減るスレイヴですら使われない現状を見ると絶対に使われないと言い切れると思います
>
スレイヴが使われない理由はややこしくて直感的でないのもそうですがキルクが減るのは他役でいいからだと思うのです。その点序盤から動かないといけない第三となったこれには独自性はあると思います。まあわかりやすい他の方法は考えておきます。
> またユーザーにクールタイム設定の意味が少ないボタンの操作をさせるという部分でUX的にダメだと思ってます
> 
では投票能力にしましょう。キャプテンみたいな感じで今貯めている票を表示して、特殊投票ボタンを付けることになりますが、その場合全投票になって多少使い勝手が悪くなるかと思います。
> 素のクルーになるという事は"その人は役職にアサインされない素のクルーである"ことを役職決定時に予約しないといけないことになります、そうなるとこの役職はフェアリー、ハンター + 素のクルー複数人というかなり使いにくいコンビネーション役職ということになります
>
予備フェアリーオプションをSK役や遠隔キル役と一緒の時のみ一人以上で使うことをWIKIに明記することを前提に話します。
現状で退場しない役職ｘSKにする上での案は出し尽くしたと思います。SKの例外が認められない以上これが駄目なのならSK役職と一緒に使えない役になってしまい、幅が狭くなってしまいます。

**Comment by yukieiji** [comment]
> スレイヴが使われない理由はややこしくて直感的でないのもそうですがキルクが減るのは他役でいいからだと思うのです。その点序盤から動かないといけない第三となったこれには独自性はあると思います。まあわかりやすい他の方法は考えておきます。

スレイヴはタスクの巻き戻しという部分でも独自性もありますが、その上でも使われてないので独自性が有る = 絶対に使われるというわけでもないです
更にこの役職がコンビ役職であって、コンビ役職の現状の使用率がそこまで多くないことを鑑みるに使われないのではないでしょうか

> 予備フェアリーオプションをSK役や遠隔キル役と一緒の時のみ一人以上で使うことをWIKIに明記することを前提に話します。

海外の方も使っているのでWikiが全員を読んでいる前提での役職は個人的によろしくないと思います
人を増やすのをオンオフするのはとても面倒くさいです

> 現状で退場しない役職ｘSKにする上での案は出し尽くしたと思います。SKの例外が認められない以上これが駄目なのならSK役職と一緒に使えない役になってしまい、幅が狭くなってしまいます。

だからこういう役職は現状実装できないってことです
個人的にメンテコストと実装コストを実装した時のメリットでペイできないから実装していないだけであって、他の人が作ってくれるなら話は違うのですが
