### ISSUE TITLE
ティンダロスの猟犬:インポスター役職

### ISSUE THREAD

**Issue by issyoukimizu** [yukieiji/ExtremeRoles#26]
### 役職名 / Role Name
ティンダロスの猟犬
### 役職の色 / Role color
インポスターと同じ
### 役職の説明 / Role description
「どこまでも追いかけて殺せ」
全てのベントを繋いで行き来できるインポスター。
### 役職の能力 / Role ability
二つの能力を持つインポスター役職。

一つ目は、ある特定の対象に印を付けることでその対象の方向を指し示す矢印が発生するようになる能力。これにより、対象の大まかな位置が推定可能。また、一度付けた印は付け直さない限り会議を挟んでも維持される。

二つ目は、マップの全ての通常ベントを繋ぐことのできる能力(一つのベントから全てのベントに直に行けるというより、独立したベント通路同士に通路を作って繋ぐイメージ。例えばエアシップならシャワーのベントからメイン上のベント、メイン上ベントからメイン下ベント、キッチンのベントから展望デッキのベントに行けるようになる、といった具合)。こちらは常時発動しているが、ベント内に居られる時間には制約があり、これを超えると強制的にベントから吐き出されてしまう(10秒～60秒。デフォルトで10秒)。しかし、一度ベントから出ればこの時間はリセットされる。
また、メリーなどが設置する特殊ベントは通常のベントとは繋ぐ事ができない。

この二つを組み合わせることで、狙いを定めた相手を正反対の場所からでも迅速に襲撃して殺したり、相方に印を付けることで離れた状態から素早く合流してダブルキルを狙うといったことが可能となる。

ただし、ベント内ではキルクールが停止しているのは変わらない上、あまりに大移動しすぎると視認情報や移動経路などからぼろが出やすくなってしまうデメリットがある。
また、ベントを多用すれば当然孤立しやすくなる為、状況によっては浮き位置ローラーであえなく吊られてしまう可能性もある。
　
ニコライ・ボルコフさんのカタタタキ多々鷹さんストーキング事件がモチーフ。
「助けてー！助けてー！嫌だー！助けてー！」

### 他陣営への影響 / Effect on other teams
移動能力が非常に高い為、単純に最終位置から犯人を詰める事は難しくなる。

また、普通のキルによって発生した死体に関しても、他陣営はティンダロスの猟犬の仕業の可能性を追わざるをえなくなる他、状況によってはそもそも通報がセルフ通報か否かを見分ける事が難しくなる為、議論が混乱しやすくなる。

さらに、目を付けられると目印能力で動向を把握されてしまう可能性があるので、ジャッカルなどはより慎重に潜伏する必要が出てくる。

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by issyoukimizu** [comment]
鷹さんの悲鳴の動画を見ていてインスピレーションが湧いたので作りました。
連投失礼します。

**Comment by yukieiji** [comment]
能力に対してデメリットがなさすぎるのでクローズしてよろしいですか？

**Comment by issyoukimizu** [comment]
元々インポスターよりクルーの方が有利なバランスのゲームですし、死体を消しながら恒常パワーアップまでできるエボルバーが許されるならこれ位はいいかなと思ったのですが……。

まあ、どうしてもパワーバランス上無理があると仰るのであれば、是非もなしですね。

**Comment by yukieiji** [comment]
> 元々インポスターよりクルーの方が有利なバランスのゲームですし、死体を消しながら恒常パワーアップまでできたり、キルするごとにキルクールが短くなったりと、リスクはあっても目立ったデメリットのないエボルバーやサイコキラーが許されるならこれ位はいいかなと思ったのですが……。

エボルバーとサイコキラーはメリットとデメリットが釣り合うように調整されてます

- エボルバー：切った死体の近くに長時間留まる必要があります、それはインポスターにとって最も避けがたい行為です。最も避けがたい行為をするというデメリットに対してキルクールの永続減少という大きめのメリットが付与されています
- サイコキラー：切って強くはなりますが1回目のキルで減るキルクールは1.5秒(最大設定)、2キルのあとは加速度的にキルクールが減っていきますが、それが反映されるのは3キル目です(会議と会議の間で1人で3キル以上するのは難しいはずです)。そのため、サイコキラー自体のメリットはすごい小さいですし大きなメリットを得ることは難しいです

現状この役職には2つの能力を持っていて能力自体にはデメリットがないのでこのままでは受け入れられないです

**Comment by issyoukimizu** [comment]
了解しました。

まあ、印をつける能力はモチーフ上付けただけで別になくてもいいですが、多分それだけではまだ受け入れられないでしょうね……。
一つ考えるとしたら、ティンダロスがベントを使っていると他プレイヤー視点でベントが赤くマークされるとかですかね？

**Comment by yukieiji** [comment]
> 一つ考えるとしたら、ティンダロスがベントを使っていると他プレイヤー視点でベントが赤くマークされるとかですかね？

そのデメリットはティンダロスの強みを潰すレベルで大きいですがよろしいですか？

**Comment by issyoukimizu** [comment]
そこは役職設定などに応じてオンオフできるようにできればと思います。

あともう一つ考えたのはのは、一度ベントに潜ってから出ると最大10秒ほどのクール時間が発生するというのでしょうか。これならキルして即ベントで離脱という事はできないので、ベントの制限時間も相まって中々リスキーに仕上がるのではと思います。

**Comment by yukieiji** [comment]
> そこは役職設定などに応じてオンオフできるようにできればと思います。

オンだと能力として使いにくいですし、オフだと強いから使いにくいでしょう

> あともう一つ考えたのは、一度ベントに潜ってから出ると、再びベントに入れるようになるまで最大10秒ほどのクール時間が発生するというのでしょうか。これならキルして即ベントで離脱という事はできないので、ベントの制限時間も相まって中々リスキーに仕上がるのではと思います。

インポスターのベントボタンを無効化するのは恐らく不可能でしょう

**Comment by issyoukimizu** [comment]
NebulaOnTheShipのリーパーというよく似た職にベントクールがありましたので、そこから引っ張ってきたのですが……難しいですか。

最初の案を一捻りするとしたら、「ティンダロスが現在いるベントのみ赤くなる」でしょうか。
これだと、あまり動き回りすぎるとティンダロスが移動しているとバレる事になりますし、奇襲難度はベントの制限時間もあってかなり上がるでしょう。
しかし、単純な長距離移動手段としてはある程度使い勝手を維持できるのではと思います。

**Comment by yukieiji** [comment]
> NebulaOnTheShipのリーパーという似た職にベントクールがありましたので、そこから引っ張ってきたのですが……難しいですか。

他のMODにあるからその役職が(EXロールにとって、もしくはAmongUs的、人狼ゲーム的)バランスが良いとは限りません

> 最初の案を一捻りするとしたら、「ティンダロスが現在いるベントのみ赤くなる」でしょうか。
これだと、あまり動き回りすぎるとティンダロスが移動しているとバレる事になりますし、奇襲難度はベントの制限時間もあってかなり上がるでしょう。
しかし、単純な長距離移動手段としてはある程度使い勝手を維持できるのではと思います。

ティンダロスがベントを使ってる時に全てのベントが光る同様、デメリットでメリットを潰している気がしますがどうでしょうか

**Comment by issyoukimizu** [comment]
>他のMODにあるから〜

ああいえ、似た職でベントクールというのに前例があるので、こっちでもベント使用にクールダウンを設けられるのではと思った、ということです。
要するに、ベントクールダウンは技術的に可能なのでは？と言いたかった訳ですね。言葉が足りずにすみません。

**Comment by yukieiji** [comment]
> ああいえ、似た職でベントクールというのに前例があるので、こっちでもベント使用にクールダウンを設けられるのではと思った、ということです。
要するに、ベントクールダウンは技術的に可能なのでは？と言いたかった訳ですね。言葉が足りずにすみません。

技術的に可能であっても、このMODでは実装したくない(もしくはした場合に多大な影響がでる)可能性もあります
そのMODのどこらへんのコードかつどれくらいのコストでそれが実装されてるかわかりませんが、今のEXロールの実装状況を鑑みると難しい気がします

> ついでにもう一つ聞きたいのですが、例えば印をつけた相手以外をキルするとキルクールが延長してしまう、とかはできるのでしょうか？

それはもう、バウンティーハンターと何も変わらないのですが

**Comment by issyoukimizu** [comment]
そうですか……。
例えば、「ベントに入れない」ではなく、「ベントには入れるけど即座に吐き出されてしまう」。つまり、「ある時間までベント使用制限時間がゼロカウントのままになっている」というのでも無理でしょうか？

それ以外に思いつくとしたら、ティンダロスに襲われた死体に全プレイヤーに見える何かしらの目立つ目印をつけるとかでしょうか。
奇襲の効果は失われませんし、ティンダロスがキルしたかどうかが判別できてしまうのはそれなりのデメリットになると思います。

**Comment by yukieiji** [comment]
> そうですか……。

TORのコードベースのMODは1つの役職の処理が色んな所にありすぎてそれがバグやラグの原因になってると考えています
NebulaOnTheShipのどのコードでそれがどのように実現されているのかがわかればこのMODに入れれるかわかりますが、私は読みたくないです(悪口になってしまいますがTORのコードベースのMODは非常に読みづらいです、NebulaはそれにTOR外の様々なMODの役職の処理が組み合わさってるので・・・)

> それ以外に思いつくとしたら、ティンダロスに襲われた死体に全プレイヤーに見える何かしらの目立つ目印をつけるとかでしょうか。
奇襲の効果は失われませんし、ティンダロスがキルしたかどうかが判別できてしまうのはそれなりのデメリットになると思います。

ティンダロスのキル自体がデメリットになってしまうのですが・・・・

**Comment by issyoukimizu** [comment]
> ティンダロスのキル自体がデメリットになってしまうのですが・・・・

プレイヤー目線だと、ティンダロスのキルだとは分かっても、どこから来てどこに行くのかの選択肢が普通のインポスターより多い以上、議論を混乱させやすいのは間違いないと思います。

その一方で、長距離ベント移動を多用してキルをすると移動経路が不自然になりやすく、また辻褄を合わせようとウソをつくと他の人との視認情報に齟齬が出るリスクがあるなど、気軽な運用はできなくなるでしょう。

また、こうしたデメリットを逆手に取り、あえてベント移動をせずキルを取ったりセルフ通報をしたりする事で、他の浮き位置のプレイヤーに疑いをかけるといった戦術も可能なので、使い手の話術次第で化けるテクニカルな役職になるのではと思っています。

**Comment by yukieiji** [comment]
> プレイヤー目線だと、ティンダロスのキルだとは分かっても、どこから来てどこに行くのかの選択肢が普通のインポスターより多い以上、状況次第ではかなり議論を混乱させうるのは間違いないと思います。
その一方で、長距離ベント移動を多用してキルをすると移動経路が不自然になりやすく、また辻褄を合わせようとウソをつくと他の人との視認情報に齟齬が出るリスクがあるため、キルが誰の仕業か分かってしまう都合上気軽な運用はできなくなるでしょう。

選択肢があるのは基本的にベントがあるところに限定されます。クルーだとベントに近づくことはベントタスク以外無いでしょう
その状態で切ってすぐベントに飛び込めるのかという疑問が湧いてきます。例えベントに逃げたとしても浮き位置になることはほぼ確定でしょう(誰が切ったかもすぐ分かるので、1会議で詰めれる気がします)

> また、こうしたデメリットを逆手に取り、あえてベント移動をせずキルを取ったりセルフ通報をしたりする事で、他の浮き位置のプレイヤーに疑いをかけるといった戦術も可能なので、使い手の運用と話術次第で化ける役職になるのではと思っています。

最後の方のセルフ通報は問題ないと思うのですが、最初の方はデメリットが多いですしセルフ通報前提で作るのは役職としてどうなのかという疑問が残ります

**Comment by issyoukimizu** [comment]
>選択肢があるのは基本的にベントがあるところに限定されます。クルーだとベントに近づくことはベントタスク以外無いでしょう
>その状態で切ってすぐベントに飛び込めるのかという疑問が湧いてきます。例えベントに逃げたとしても浮き位置になることはほぼ確定でしょう

そういうリスクが存在するということであれば、そもそもデメリットが必要なのかという気もしてきます。
浮き位置で詰められるという事態は元々より大きなリスクとして提示していますし、前にも書いたように移動経路を精査されると苦しくなるので、ベントの無制限移動はそれほど大きなメリットではないと思います。
単に現状から印を付ける能力を取り払うだけで十分バランスは取れるのではないでしょうか？

**Comment by yukieiji** [comment]
> そういう意味で、特にデメリットがなくとも強すぎるということはないと思います。

この役職の一番強いところはマップの端から端までほぼ一瞬で飛べることです(マップのありとあらゆる障害物と視認情報を消してどんなベントにでも行ける事が可能です)。やろうと思えば貨物に居てコクピットの人をキルして貨物に戻るということが出来ます。恐らく10秒もあれば可能でしょう10秒のティンダロスの視認情報が無ければ貨物でタスクをやっていたでごまかせる。
これは十分強すぎる気がしますがどうでしょうか？

**Comment by issyoukimizu** [comment]
その貨物でタスクをやっていたことを証明できる人間がいなければ、濃いめのグレー位置には間違いなく入ると思います。
浮き位置の人間が少なければ、そのままローラーで吊られてしまうという事態もあり得るでしょう。
それに10秒もあれば可能というのは、偶々都合よく獲物が単独でベント近くに存在していた場合に限るので、結構運任せになります。それでも強いというなら、ベントに潜れる時間を単にもっと短くすればよいと思います。

仲間のインポスターと合流したうえで口裏を合わせて偽装すれば話は別ですが、その場合はラインが疑われることになりますし、仲間インポスターを10秒ほどの間一か所に拘束することになります。キルペースには悪影響が出るでしょうし、仲間が貨物にやってきたプレイヤーを口封じしても、口裏合わせを優先するならティンダロスが帰ってくるまではその場から簡単には逃げられず、最悪セルフ通報せざるを得なくなるという大きなリスクを負うことになります。

**Comment by yukieiji** [comment]
> その貨物でタスクをやっていたことを証明できる人間がいなければ、濃いめのグレー位置には間違いなく入ると思います。
浮き位置の人間が少なければ、そのままローラーで吊られてしまうという事態もあり得るでしょう。逆に、浮き位置が多ければ誤魔化せる、というより容疑者の多さで詰められないということになるでしょうが、これは普通のベント移動を伴わないキルでも同じことですし。

タスクをやってる証明が出来なくて濃いめのグレー位置に立つなら、ほぼすべてのクルーが濃いめのグレー位置に立つことになります
全てのベントがつながっている以上グレー位置にすら入らないでしょう。また、10秒前の視認情報で浮き位置に立つのか疑問に残ります

> それに10秒もあれば可能というのは、偶々都合よく獲物が単独でベント近くに存在していた場合に限るので、結構運任せになります。それでも強いというなら、ベントに潜れる時間を単にもっと短くすればよいと思います。

私が言っているのは運とか関係無しでマップの端から端まで10秒でキルして戻ってこれる事が可能だから強いって言っているのです(「アサシンとマーリン」で「アサシン」が運悪く初手吊られてインポスターがすぐ全滅する可能性があるからバランスが悪いって言ってるのと同じに聞こえます)
役職を考える際は運や議論の事を考え出すと全く何も進まなくなるので、基本的に運を考えず能力を使用したときの最悪想定と能力を使用したときの最良想定をすべきです。

**Comment by issyoukimizu** [comment]
>タスクをやってる証明が出来なくて濃いめのグレー位置に立つなら、ほぼすべてのクルーが濃いめのグレー位置に立つことになります
>全てのベントがつながっている以上グレー位置にすら入らないでしょう。また、10秒前の視認情報で浮き位置に立つのか疑問に残ります

そういう事であれば、死体に目印が付く場合でも極端に弱すぎる事にはならないのではないでしょうか。

ティンダロスの仕業とは分かっても、どこから来たのか分からない以上、タスク行動視認の取れていない人間だらけという最悪の場合容疑者が多くなって追えなくなりますし、逆に相互視認がないのがティンダロス本人だけ、という事になればラインを追わなければほぼ一択という状況になります。

上手くいけば議論を混乱させられ、悪ければ速攻でティンダロス容疑で吊られてしまう。
リスクはあるが、リターンも大きい能力になると思います。

**Comment by yukieiji** [comment]
> そういう事であれば、死体に目印が付く場合でも極端に弱すぎる事にはならないのではないでしょうか。

ベントが使えない状況下でのキルが極端に弱くなってしまうですけどいいんですか？って話です

> ティンダロスの仕業とは分かっても、どこから来たのか分からない以上、タスク行動視認の取れていない人間だらけという最悪の場合では容疑者が多くなって追えなくなりますし、逆に相互視認がないのがティンダロス本人だけ、という事になればラインを追わなければほぼ一択という状況になります。
上手くいけば議論を混乱させられ、悪ければ速攻でティンダロス容疑で吊られてしまう。
リスクもリターンも大きい能力になると思います

ティンダロス1回のキルにこれだけのリスクがあるのは使いにくい役職だと思います。リターンには全然見合わないでしょう

**Comment by issyoukimizu** [comment]
ベントを使えない状況なのなら、ティンダロスにキルされた証拠が付いてようと付いていまいと同じ事だと思います。どっちにしろ、最終位置を詰められれば疑い位置に入りやすくなります。
そもそもベントが最大の強みの役職である以上、ベントが使えなければ印があろうとなかろうと弱体化は避けられません。

それと、相互視認が取れていないのが自分だけの場合吊られてしまいやすいのは、どんなインポスターにも共通している事だと思います。
大きすぎるリスクというほどではないのではないでしょうか。

もしそれでもリスクがリターンより大きいのなら、なんらかのバフを付けるまでです。

**Comment by issyoukimizu** [comment]
なんだか段々と議論というより言い合いみたいになって来ていますし、中々すり合わせも難しそうなので、ここで閉めようと思います。

ベントを使うインポスター役職に関しては、また別のアイデアを考えて、いいものが思いつき次第改めて投稿しようと思います。

ご迷惑をおかけしました。
議論に長々と付き合っていただき、ありがとうございます。

**Comment by yukieiji** [comment]
閉めるとのことでクローズさせていただきます
