### ISSUE TITLE
ボマーが爆弾を設置中に会議もしくは誰にも設置していない状態でサイドキックされたりした場合にNull参照エラーが発生する

### ISSUE THREAD

**Issue by RanasGlif** [yukieiji/ExtremeRoles#263]
## バグの情報 / Info of bug
・ボマーが誰にも爆弾を設置中に会議もしくは誰にも設置していない状態でサイドキックされたりした場合にNull参照エラーが発生する
### 期待される動作 / Your Expectation
・ボマーが誰にも爆弾を設置中に会議もしくは誰にも設置していない状態でサイドキックされたりした場合問題なく動作する

### Among Usバージョン/ Among Us Version

[ExtremeRolesDumpedLogs_2023-03-05T21-21-57.zip](https://github.com/yukieiji/ExtremeRoles/files/10891842/ExtremeRolesDumpedLogs_2023-03-05T21-21-57.zip)
Among Us v2023.2.28s

### Modバージョン / Mod Version

Extreme Roles v6.0.0.1

### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [x] :アジア/Asia
- [ ] :カスタム/Custom

### プレイヤー人数/Player Num

13

**Comment by yukieiji** [comment]
不具合名はきちんと書いてくれると助かります

**Comment by RanasGlif** [comment]
すいません状況が把握しきれてなかったので解ってる範囲でのご報告となりました
