### ISSUE TITLE
[インポスター/Impostor] : デストロイヤー/Destroyer (会議で自爆して巻き込みキルをする)

### ISSUE THREAD

**Issue by kisaRagi05** [yukieiji/ExtremeRoles#264]
### 役職名 / Role Name

- デストロイヤー/Destroyer

### 役職の色 / Role color

- インポスターレッド

### 役職の説明 / Role description

- 他MODの道連れ系役職を改良
- 会議で自分を犠牲に指定人数をキルする役職
  - 人数や対象は設定可能とする

### 役職の能力 / Role ability

- 能力：「エクスプロージョン」(Explosion)
  - 自分が未投票時に投票ボタンの横に自爆ボタンが出現
    - 設定「巻き込み対象を1名選択する」（初期値オフ）
      - オンの場合は選択した相手を1名巻き込み（自身を選択するとランダムに選びます）にして2名以上巻き込みにする設定の場合ならランダムで追加対象が選ばれます
      - オフの場合は誰を選択してもランダムに選びます
  - 発動後に自分自身と設定した対象陣営から設定人数をキルします
    - 設定「巻き込む人数」（初期値1　最大値14）
      - 基本設定は1～2人を想定しています
    - 設定「巻き込み対象に第三陣営も含む」（初期値オフ）
      - オンの場合は第三陣営も巻き込み可能となります
      - オフの場合は巻き込み不可能となり対象に選んでも他陣営の人がランダムに選ばれます
    - 設定「巻き込み対象にインポスターも含む」（初期値オフ）
      - オンの場合はインポスターも巻き込み可能となります
      - オフの場合は巻き込み不可能となり対象に選んでも他陣営の人がランダムに選ばれます
    - アサシンは巻き込まれません
    - ボディガードの「ガード」の影響を受けます
    - 巻き込み可能な陣営がいない場合は誰も巻き込まずに自分自身が自爆するだけとなります
  - 死亡処理は「自分自身」→「抽選対象A」→「抽選対象B」→・・・
    - 例：インポスター陣営2名 クルー陣営3名で能力を使用して自分とクルー陣営1名が死んでもインポスター勝利判定は入らない
    - 自分が最後のインポスターの場合は使用しても勝利できません
  - 能力使用時の演出（技術的に可能で面倒じゃなければ）
    - ボタン押してから発動まで5秒程度の演出を挟む
      - Among us内で使用しているSEを流用して音を鳴らす
      - 自分のキャラを光らせる
      - 名前の部分を光らせる
      - 上記が技術的に不可能の場合は実装無し
    - 演出を見てからゲッサーが撃って阻止したりボディガードが選んだりが可能となる
    - 設定「自爆時の演出」（初期値オン）
      - オフの場合は演出無しで即キルの処理に入ります
  - 能力使用時に確認ウィンドウを表示
    - 誤爆防止
    - メッセージ案
      - 自分の命を犠牲にしてクルー（・第三陣営）（・インポスター）から（[指定人名]と）ランダムなｎ名を巻き込んでエクスプロージョンしますか？　「はい」　「いいえ」

仲間のインポスターより長く生き残る必要が無い役職であり
最後の一人になってしまうと能力がインポスター勝利に無意味となるので
インポスター役職の中でも特にキルペースが早くなると思われます

通話しながらの場合は自爆時のRPや捨て台詞が楽しめるかもしれません

### 他陣営への影響 / Effect on other teams

- 第三陣営とインポスターが巻き込まれず、クルーだけが対象に選ばれる場合
  - クルー陣営：巻き込み対象の為不利であるが、巻き込まれてキルされた人が確定でクルー陣営だとわかる
  - 第三陣営：絶対巻き込まれないので盤面が有利になる場合が大半だが、巻き込み対象にするとデストロイヤーが宣言したのに巻き込まれない場合は不利になる
  - インポスター陣営：味方を巻き込まないのでデストロイヤーは無謀なキルをハイペースで実行して自爆、他の仲間は潜伏を選びがちになると思われる
- インポスターが巻き込まれず、クルーと第三陣営が対象に選ばれる場合
  - かなり一方的な強さなので非推奨
- 第三陣営が巻き込まれず、クルーとインポスターが対象に選ばれる場合
  - 第三陣営が有利になり過ぎるので非推奨
- 全陣営が対象に選ばれる場合
  - クルー陣営：インポスターや第三陣営が巻き込まれる可能性もあり逆に有利になる事も
  - 第三陣営：運の要素で頑張りが壊される恐れもあるが、有利になる事もある
  - インポスター陣営：味方を巻き込む可能性があるのて躊躇が生まれる、巻き込まれてインポスター陣営全滅の場合もある
### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
実装するコストが全体的に高すぎる気がする点と任意の人を落とせるという部分でシューターで十分な気がします(何ならシューターに今から打ちます的な演出を付けるほうが楽かつバランスが取れそうな気もしなくもないです)

**Comment by kisaRagi05** [comment]
> 実装するコストが全体的に高すぎる気がする点
何ならシューターに今から打ちます的な演出を付けるほうが楽かつバランスが取れそうな気もしなくもないです

確かにこの役職に演出つけるなら他のシューターやゲッサーにもつけるべきであり、他の役職が優先されますね
これは無しで問題ありません

誤爆防止の確認メッセージ実装もコストが高いと思われますし
自身が自滅する能力を持つサーヴァント等の役職には誤爆防止の確認無く発動なので
こちらも無しで問題ありません

> 会議中に任意の人を落とせるという部分でシューターで十分な気がします

任意対象を落とせるという能力がシューターと被っているのは間違いないですね
これは会議内能力発動が投票ボタンの隣にボタンを配置するだけしかないと思い込んでいまして
他の人の投票ボタンの隣にボタンがあるのにその人に対しての効果は無いのはどうかと思って
任意対象指定効果を記入しました
それ以外の場所に能力発動ボタンは配置可能だったりしますでしょうか？

上記の考えにて、この任意対象指定を無しにして指定人数、指定陣営からランダムに選ばれるだけにして良いと思ってます

**Comment by yukieiji** [comment]
> これは会議内能力発動が投票ボタンの隣にボタンを配置するだけしかないと思い込んでいまして
他の人の投票ボタンの隣にボタンがあるのにその人に対しての効果は無いのはどうかと思って
任意対象指定効果を記入しました
それ以外の場所に能力発動ボタンは配置可能だったりしますでしょうか？

基本的に投票ボタンの隣にしか配置できないです、これは確か[通報とキルが同時に発生するとボタンがバグるという不具合](https://twitter.com/yukieiji/status/1528951986665558017)があったためこういう使用になっています

> 上記の考えにて、この任意対象指定を無しにして指定人数、指定陣営からランダムに選ばれるだけにして良いと思ってます

そうなった場合会議で爆発メリットがあんまりないような気がします、タスクフェーズ中に吹き飛べれるようにしたほうが良い気がします(そうなった場合、ボマーが現状の仕様になった問題を解決する必要があったりますが)

**Comment by kisaRagi05** [comment]
> 基本的に投票ボタンの隣にしか配置できないです

では投票ボタンの隣に配置のままでお願い致します

> そうなった場合会議で爆発メリットがあんまりないような気がします

会議で自分自身が吊られそうになったときに使用するのを想定しています
タスクフェーズでの現行犯通報やタイムマスター能力発動等によってキル陣営だとバレて会議に入っても使用できる事と
別の場所でキルを行ったインポスター仲間への疑いや追求に対しての議論逸しや時間稼ぎが期待できるのがメリットとなります

> タスクフェーズ中に吹き飛べれるようにしたほうが良い気がします(そうなった場合、ボマーが現状の仕様になった問題を解決する必要があったりますが)

タスクフェーズでの爆破の場合はワルガキの自爆と同じか近い仕様になると思いますが
ワルガキは自爆による勝利は限定的なのに対してインポスター陣営だと仲間のインポスターが居なくて大人数集まってるところに特攻するだけで自陣営が大きく有利になるので圧倒的に強くなってしまいます
ボマーのような爆破タイミングを正確に把握できないなら大人数集まってるところで発動するかも運次第で、誰もいないところで自爆しても着けた相手が亡くなるだけですが
この役職で時間不確定にすると誰もいないところで自爆したりとイマイチな強さになると思われます

**Comment by yukieiji** [comment]
> 会議で自分自身が吊られそうになったときに使用するのを想定しています
タスクフェーズでの現行犯通報やタイムマスター能力発動等によってキル陣営だとバレて会議に入っても使用できる事と
別の場所でキルを行ったインポスター仲間への疑いや追求に対しての議論逸しや時間稼ぎが期待できるのがメリットとなります

この使用の場合、クールタイムという概念がなさそうなのでこの役職は門番をするだけでほぼ確実に3人以上持っていけると思っています
それを考えればシューターより使いにくい気がします、現状シューターの場合は弾がなければ門番で切ったあとに持っていけ無いですし

> タスクフェーズでの爆破の場合はワルガキの自爆と同じか近い仕様になると思いますが
ワルガキは自爆による勝利は限定的なのに対してインポスター陣営だと仲間のインポスターが居なくて大人数集まってるところに特攻するだけで自陣営が大きく有利になるので圧倒的に強くなってしまいます

ボマーが現在の仕様になっているのはそれが理由です
普通にボタンを押すと命の代わりに誰かをランダムに吹き飛ばすって能力にしてもいいとは思うんですが

**Comment by kisaRagi05** [comment]
> この仕様の場合、クールタイムという概念がなさそうなのでこの役職は門番をするだけでほぼ確実に3人以上持っていけると思っています

それは1人キルして待ち構えてキルクールを溜めるが見つかり通報された後、会議自爆にて2人持っていくので3人持っていく事が可能という事でよろしいでしょうか

> それを考えればシューターより使いにくい気がします、現状シューターの場合は弾がなければ門番で切ったあとに持っていけ無いですし弾の装填自体もかなり重いデメリットがついてますので

能力発動後に自滅するデメリットはあるが、能力発動条件がない事が問題ですかね
門番する行為等を抑制する条件が必要でしょうか

> ボマーが現在の仕様になっているのはそれが理由です
普通にボタンを押すと命の代わりに誰かをランダムに吹き飛ばすって能力にしてもいいとは思うんですが

タスクフェーズで自分の命を代償に誰かランダムで吹き飛ばすという内容でしょうか？
それなら良いかもしれませんが
自分は死なないが何らかの条件を満たしてランダムに吹き飛ばすという内容の場合
この役職案は「自分の命を代償に強力な能力を発動する」がコンセプトなので
役職本人が亡くならない仕様になる場合はコンセプトから逸脱してしまいます

**Comment by yukieiji** [comment]
> それは1人キルして待ち構えてキルクールを溜めるが見つかり通報された後、会議自爆にて2人持っていくので3人持っていく事が可能という事でよろしいでしょうか

そうですね

> 能力発動後に自滅するデメリットはあるが、能力発動条件がない事が問題ですかね
門番する行為等を抑制する条件が必要でしょうか

門番が最も強い行為ですがどちらかと言えば、能力の発動もしくは開放条件が無いため"会議に入ってしまえばどんな状況下でも2人持っていける"という部分がダメだと思ってます。現状だとインポスターが複数人居る状態だとキルがバレてもバレなくても2人以上持っていけてしまいますので(目の前で人を切ったとしても自爆すれば追加で2人持っていける)

> タスクフェーズで自分の命を代償に誰かランダムで吹き飛ばすという内容でしょうか？

そのとおりです、ですが何もない場所で急に死んだりするとプレイヤーのストレスはかなり高いのではないと思ってます(マイナーが使われない理由もその一つかなって思ってます)

**Comment by kisaRagi05** [comment]
> 能力の発動もしくは開放条件が無いため"会議に入ってしまえばどんな状況下でも2人持っていける"という部分がダメだと思ってます

では発動条件等を追加したいと思います

確認ですが、投票ボタン隣の能力ボタンを入力して全員の投票が完了もしくは会議時間終了後に能力発動して自爆が行われる処理は可能でしょうか？

その処理が可能でしたら
会議自爆によって巻き込める人数の初期値を0にしてタスクフェーズでキルした回数に応じて巻き込み可能人数が加算されるが
自身が最多票（吊られる）または指定された票以上が自身に入った場合は不発となるとしまして

キルをすればするほど自爆で多くを巻き込めるが疑われると発動が困難になる役職とします

設定例
自爆で巻き込める人数の初期値　0
キルによって増加する自爆巻き込み人数　1
自身が会議で最多票の場合は不発となる　オン
不発となる自身への票数の最低値　1

> 何もない場所で急に死んだりするとプレイヤーのストレスはかなり高いのではないと思ってます

誰かと一緒に行動したり危険な場所に行かない等のキル予防が一切通用しないため与えるストレスは極めて高いと思います

**Comment by kisaRagi05** [comment]
> キルをすればするほど強くなって詰めれなければ手が付けれず会議中自爆を常に気にかける必要があるという点でリワーク前のシューターのキルをすればするほどタイマーが減る状態と同じになってる気がしますがどうでしょうか

違いとしましては
 - 能力を使った本人は確実に死亡する
 - インポスター陣営最後の一人の場合は実質無力化となる
 - インポスター陣営の数的有利を重視して使わない
 - 自爆の仕様により使用回数は1回限り

となりますが

複数箇所でキルが発生して誰かが詰められ追放される隙に自爆する戦法ができてしまうので
クルー陣営等は複数箇所の犯行のどれがデストロイヤーなのかを意識して詰めなければいけないし
仮に2名もこの役職がいれば確実に発動できそうでもありますね
気にかける必要性としてこれは結構な議論の負担となると思いますので追加としまして

「誰かが追放される場合も不発とする」

これで怪しい人をデストロイヤーとか関係無く吊っていけば自爆は防げるのと
ジェスターが最多票で吊られるところにデストロイヤーの自爆でジェスターがキルされるというのを防げるかと思います（第三陣営も巻き込み対象に含む場合）

> 投票でブロックできるという仕様があることで「とりあえず全員に1票ずつ入れましょう」とかで防げてしまう部分も問題かなって思ってます(2票以上にするとおそらく防ぐのが難しい)

自分自身に票を入れてデストロイヤーではないとアピールが可能なのが問題となる感じですかね
スキップ縛りの遊びとかでも実感しましたが、綺麗に他の人に1票ずつ入れるのは難しいと思われます

なので票による防止は「自殺票はカウントしない」で戦法が変わると思われます

**Comment by kisaRagi05** [comment]
> 逆に発動がしづらくなっている気がしなくもないですね
1票ずつ入れましょうで完封出来てしまうのではないかと

下記条件
 - 追放が発生すると不発
 - 自分が追放されると不発
 - 指定票数が自分に入ると不発

こちらの条件の数値を調整して発動難度を各村の方針で変えるのが良いかなと思いましたが中々難しいですね
これ以上の追加条件はややこしくなるので
会議自爆に拘る場合はより考える必要ありですね

> 追加でインポスターにチャンスを与えてるのも使いにくい気がしている原因かなって思ってます

会議終了後の自爆なのでタスクフェーズで死体が出るわけでもなく通報とかも無いので
確かに招集ボタンを押すのが必要ですね
だとするとマップに死体は転がってて欲しいのでタスクフェーズ中の能力発動もありとなってきました

> コンセプトに反してるかわからないんですがボマーの初期案の役職をインポスター人数とキル人数による覚醒役職 + サボ禁止くらいで実装したほうがバランスが良いような気がします

コンセプトは
 - 役職名「デストロイヤー」であること
 - 能力使用で自爆すること
 - 自らの命を対価に超強力な能力であること

この点が変わらなければ良いかなと思います

ボマーの初期案は詳しくありませんが、覚醒役職やサボ禁止とかでも良いと思ってます

会議自爆に拘っていたのは
そこで発動したら通話会議が楽しくなるかなと思っての事なので
ここが無理そうでも残念だけど仕方ないで済ませられます

**Comment by yukieiji** [comment]
> 会議終了後の自爆なのでタスクフェーズで死体が出るわけでもなく通報とかも無いので
確かに招集ボタンを押すのが必要ですね
だとするとマップに死体は転がってて欲しいのでタスクフェーズ中の能力発動もありとなってきました

会議中に吹き飛ぶならまぁ問題ないかなとは思うんですがね

> コンセプトは
役職名「デストロイヤー」であること
能力使用で自爆すること
自らの命を対価に超強力な能力であること
この点が変わらなければ良いかなと思います
ボマーの初期案は詳しくありませんが、覚醒役職やサボ禁止とかでも良いと思ってます

ボマーの初期案はキスミィさんが1年位前にツイートした(どうもキスミィさんがシャドウバンを食らってるので検索出来ないのでこれって示せないんですが)のと以前自分頭の中で思いついた案が元ネタで確かワルガキと同じく自爆特攻が出来るインポスターです(当時は覚醒であったり等が無かったのでその案をあれこれして今のボマーが生まれてます)

役職名がデストロイヤーであるかについては別途議論の余地がありそうですが(チケットに上がっててまだ実装できてないテロリストを先取りしてその役職名とするでもいいんですが)

> 会議自爆に拘っていたのは
そこで発動したら通話会議が楽しくなるかなと思っての事なので
ここが無理そうでも残念だけど仕方ないで済ませられます

楽しさを取るか使って欲しさを取るかのせめぎあいだとは思います、言い方が悪いかもしれないですが現状のままだと数回使ってシューターみたいで使いにくかったねで使われなくなりそうって言う予測が僕の中ではあります

**Comment by kisaRagi05** [comment]
> 会議中に吹き飛ぶならまぁ問題ないかなとは思うんですがね
> コンセプトに反してるかわからないんですがボマーの初期案の役職をインポスター人数とキル人数による覚醒役職 + サボ禁止くらいで実装したほうがバランスが良いような気がします

うーん、会議中に発動できて良い感じにするとなると

- キル回数に応じた覚醒役職にする
- 覚醒後の初期自爆巻き込み人数を設定で変更可能とする
  - 例：2キルで覚醒、会議で1人巻き込み可能となり更にキルをすると巻き込み人数1人追加
- 覚醒後、タスクフェーズでは「自爆準備」ボタンを表示
- 「自爆準備」を押した後に会議フェーズに入ると自爆が任意発動可能となる
- 自爆を実行せずに会議が終わると再び「自爆準備」ボタンを押さない限り発動できなくなる
  - 「自爆準備」
    - 通常のボタン能力と同様にクールタイムあり
    - そのタスクフェーズでボタンよりキルを先に実行した場合はボタン使用不可能
    - 「自爆準備」ボタンを押した後はキル不可能
    - 更に制限をかけるなら「サボタージュ使用不可」「サボタージュ修復不可」「緊急会議ボタン不可」を追加
 - 会議画面で誰かを選べるのに誰を選んでも効果無いとデザイン的に微妙なので「ピックアップ」を追加
   - 「ピックアップ」
     - 選んだ相手を設定された確率で巻き込み対象にする
     - 0～70％（上限は100％にしない）
     - 例：2人巻き込み対象、ピックアップ30％の場合
      30％の確率で選んだ対象を巻き込む抽選を行い、その後に通常のランダム抽選を実行
      当たった場合は選んだ対象を巻き込み、残り1名をランダム抽選する
      外した場合は、2名をランダム抽選する

上記内容でタスクフェーズで自爆準備、会議画面で自爆実行とすると

- 緊急招集ボタンで連続議論がされている時はクールタイムがあけないので自爆発動不可能
- キル実行時はボタン使用不可となる為、門番からの自爆は不可能
- ボタン使用後のキル制限により、誰かキルして通報して自爆も不可能

     

> 楽しさを取るか使って欲しさを取るかのせめぎあいだとは思います、言い方が悪いかもしれないですが現状のままだと数回使ってシューターみたいで使いにくかったねで使われなくなりそうって言う予測が僕の中ではあります

確かに使われなさそうな役職になってしまうのを回避できなさそうでしたらクローズにしても良いぐらいですね

**Comment by yukieiji** [comment]
返信が思い浮かばない理由をちょっと考えてみたところ、この役職の強さの軸がどこらへんにあるのかの認識が共有できてない(僕の中で認識ができてない)感じでしょうか

- 能力を「会議中の自爆」として設定する場合
  - 類似役職：ゲッサーとシューター
    - 最大と最小の強さを比較した時にどういった順番になるのか
    - 違いはどこにあるのか
 - 能力を「タスク中の自爆」として設定する場合
   - 類似役職：ボマー
     - ボマーより強い
     - 自由度が高いが確実に自分が死んでしまう

**Comment by kisaRagi05** [comment]
うーん、これ以上の改良等は当初の内容から離れてしまうので
クローズ、そして役職名「デストロイヤー」やここで出した案とかは
他の役職作成に当てはめて大丈夫としたいと思います

**Comment by yukieiji** [comment]
了解しました、クローズします
