### ISSUE TITLE
スレイヴドライバーのリワーク

### ISSUE THREAD

**Issue by kisaRagi05** [yukieiji/ExtremeRoles#266]
私が提案した役職、「スレイヴドライバー」がアンケートを見た感じあんまり使われてないのでリワークしたいと思いました

タスクに関する能力であり悪い上司というイメージを維持した感じで大きく変えたいのですが
「アサシン」がタスクできるのと同様に「スレイヴドライバー」もタスクが出来て
それに応じた能力にリワークして欲しいと思ってます

ですので、何かしらの理由で「アサシン」以外のインポスター陣営はタスクが出来ないとか
重大な不具合があるとかの場合はこの案は全部白紙で問題ありません

機能案1「1つのタスク完了によるキルクール減少を追加」

- シェリフのタスク完了数によってキルクールが減ると同じ仕様
- 非常にシンプルな仕様なので初心者でも判りやすい感じなるかと思います

機能案2「自身のタスクと他の人のタスク差での効果に変更」

- 現状では誰がタスク進んでないかまで意識してキルを行う人は多くなく
  適当にキルして偶然キルクールが短縮してラッキー程度で扱っていた人が多い印象でした
- タスク差にしまして、ある一定以上タスク完了数が離れた相手に対してキルクール短縮効果を付与
  - 第三陣営等のタスクの無い役職に対しては「全体のタスク進捗率」と「自身のタスク進捗率」によっての確率で短縮効果を付与
- 過剰になるかもしれませんが「ヤンデレ」の矢印能力を「スレイヴドライバー」にアレンジして追加
  - キルクール短縮効果対象にヤンデレと同様に矢印を付けて分かるようにします
- 対象が視覚的に分からないのも使いにくいと思われる一つかなと思います

機能案3「タスク増加能力を「特攻」キルからボタン能力「ハラスメント」に変更」

- 「特攻」によってタスクを増やしていたのを変更してボタン能力でタスクを増やす機能に変更します
- エージェンシーの「肩代わり」のように1名選択型で、アリスの「破壊工作」のような全体効果ではありません
  - タスクフェーズで目標となってる人にタスクを追加
  - 回数制限付き
  - 効果の反映は会議画面になる時
  - 「ハラスメント」を受けた人はチャット欄でタスク増加した事を知る事が可能
  - 状況次第で特定される可能性もあり
- タスク完了型覚醒役職の遅延やタスク勝利阻止が期待できる
-  現状は相手のタスクを増やせたかどうかが分からない所も使いにくいと思われる要素かなと思いました
   ボタン式にして視野的に分かりやすくします

以上となります

**Comment by yukieiji** [comment]
スレイヴやアサルトのアンケートを見た時に思ったのはおそらく基本コンセプトから派生させた役職の自体のコンセプトがしっかりしていない印象を受けた気がします
  - 基本コンセプト：「上司っぽい役職」
  - 役職コンセプト：「？？？」
    - このふわっとした部分を能力とオプションで固めようとした結果わからない役職になってる感じがします(キルクールをガッツリ減少させるって部分にフォーカスするのであればオバロとかで十分、タスク周りって部分はよくわからないって感じでしょうか)
    - 以下はアンケートの一部の意見です
      - 「ボーナスキルによる増加と通常時がキルクールだけなので判別がつきにくい」
      - 「タスク進捗に対しての特攻はいいが、いうほど目立たず現状ではあまりぱっとしない」
      - 「キル時間が短くなるというリターンに対しそれを達成する条件が複雑で扱いづらい(バウンティーで十分である)」

以上を踏まえて返信していきます

> ですので、何かしらの理由で「アサシン」以外のインポスター陣営はタスクが出来ないとか
重大な不具合があるとかの場合はこの案は全部白紙で問題ありません

一応インポスターがタスクを出来るようにした時にフラグを1箇所変更するだけで出来るようにはしてるので問題ないかと思われます

> 機能案1「1つのタスク完了によるキルクール減少を追加」
シェリフのタスク完了数によってキルクールが減ると同じ仕様
非常にシンプルな仕様なので初心者でも判りやすい感じなるかと思います

タスクをやっている間にキルクールが上がりそうってことを考えるとあんまりかなって思ってます(アサシンのときもあんまり使われた印象がない・・・)
永続にするとクルー側が対処する方法が無い気がします

> 過剰になるかもしれませんが「ヤンデレ」の矢印能力を「スレイヴドライバー」にアレンジして追加
キルクール短縮効果対象にヤンデレと同様に矢印を付けて分かるようにします
対象が視覚的に分からないのも使いにくいと思われる一つかなと思います

これをつけると本格的にバウンティーハンターで十分ってなりそうな気がします

> 機能案3「タスク増加能力を「特攻」キルからボタン能力「ハラスメント」に変更」

「特攻」によってタスクを増やしていたのを変更してボタン能力でタスクを増やす機能に変更します
エージェンシーの「肩代わり」のように1名選択型で、アリスの「破壊工作」のような全体効果ではありません
タスクフェーズで目標となってる人にタスクを追加
回数制限付き
効果の反映は会議画面になる時
「ハラスメント」を受けた人はチャット欄でタスク増加した事を知る事が可能
状況次第で特定される可能性もあり
タスク完了型覚醒役職の遅延やタスク勝利阻止が期待できる
現状は相手のタスクを増やせたかどうかが分からない所も使いにくいと思われる要素かなと思いました
ボタン式にして視野的に分かりやすくします

キルクールタイム周りを全撤廃してこれだけの能力に特化させるのは十分ありかなって思いました

以下自分が考えててたリワーク案
役職のコンセプト：「"タスク"関連に特化させたインポスター」
- 調整方針
  - オプションと現在の能力全撤廃
  - 能力
    - 全体のタスク進捗が見れるようになる
    - キルした時のタスク進捗率との差で「一定のタスクリセット」、「全タスクリセット」、「タスク追加」になる
    - 誰を切ればいいかはアイコン表示(オン/オフ化)かつ名前横に記号表示
    - 幽霊も含めて相手のタスクが見れる(これはちょっと調整中)

**Comment by kisaRagi05** [comment]
> キルクールタイム周りを全撤廃してこれだけの能力に特化させるのは十分ありかなって思いました

シンプルさを考えるとありかと思います

> 以下自分が考えててたリワーク案
役職のコンセプト：「"タスク"関連に特化させたインポスター」
    調整方針
        オプションと現在の能力全撤廃
        能力
            全体のタスク進捗が見れるようになる
            キルした時のタスク進捗率との差で「一定のタスクリセット」、「全タスクリセット」、「タスク追加」になる
            誰を切ればいいかはアイコン表示(オン/オフ化)かつ名前横に記号表示
            幽霊も含めて相手のタスクが見れる(これはちょっと調整中)

考えとしては以下がありまして

- こちらのリワーク案の「ハラスメント」ボタン型をスレイヴドライバーとして
  yukieijiさんのリワーク案の「"タスク"関連に特化させたインポスター」を別名のインポスター役職に適応
- 「ハラスメント」「"タスク"関連に特化させたインポスター」の両方の能力をスレイヴドライバーに与える
- 「ハラスメント」は無しで「"タスク"関連に特化させたインポスター」でスレイヴドライバーをリワークする

他の案でもいいかと思いますが、上記3種でしたら個人的には全然良いかなと思ってます

**Comment by yukieiji** [comment]
> 考えとしては以下がありまして

こちらのリワーク案の「ハラスメント」ボタン型をスレイヴドライバーとして
yukieijiさんのリワーク案の「"タスク"関連に特化させたインポスター」を別名のインポスター役職に適応
「ハラスメント」「"タスク"関連に特化させたインポスター」の両方の能力をスレイヴドライバーに与える
「ハラスメント」は無しで「"タスク"関連に特化させたインポスター」でスレイヴドライバーをリワークする
他の案でもいいかと思いますが、上記3種でしたら個人的には全然良いかなと思ってます

下手にいろんな能力をつけると他の役職の能力を取ってしまう危険性もありますから、シンプルに3番でいいと思います。
追加でエージェンシーの逆ポジという意味で3の能力に追加してタスクバーが見えるくらいがちょうどいい気がします(エージェンシーの逆ポジであるという役職であるとより説明可能になると思われます)

**Comment by kisaRagi05** [comment]
では3番で良いと思います
エージェンシーと同じくタスクバーが見えるのもいいですね
ここもお任せします

**Comment by yukieiji** [comment]
マイルストーンをセットします
