### ISSUE TITLE
[第三陣営] : タスクゴースト(仮)/Task ghost (TOUのphantomを調整したもの)

### ISSUE THREAD

**Issue by unhappyset** [yukieiji/ExtremeRoles#268]
### 幽霊役職名 / Role Name
タスクゴースト/Task ghost
### 幽霊役職の色 / Role color
紫色(9c458c)
### 幽霊役職の説明 / Role description
TOUのphantomを調整し、死亡してこの役職になった後タスクをすべて終わらせれば勝利
### 幽霊役職の能力 / Role ability

・キルされてこの役職になった時、新しい設定個数のタスクが割り当てられる
・毎ターン新しいタスクが設定個数づつ増えていく(1がおすすめ)
・幽霊がアサインされる可能性がある設定の場合すべてのプレイヤーに除霊ボタンが追加され幽霊が近づいた時に
除霊ボタンを押すと除霊をすることができタスクゴーストは通常の幽霊になる。
・タスクゴーストは壁への当たり判定があり壁を貫通することはできない(設定で変更可能)
・その他の設定：(単独勝利になるか これをオンにしてるとタスクゴーストのみの勝利となり、オフにしてると他の陣営と一緒に勝利することができる)：タスクゴーストの足の速さ：(これは詳しく説明するまでもなく普通に足の速さだが他のプレイヤーより早い方がおすすめ)：クルーメイト以外がこの役職になれるか (これをオンにするとインポスターやジャッカルもこの役職になれる
### 死亡前の役職 / Role befor Dead
死亡前は設定で縛られた陣営以外誰でもなれる

### 他陣営への影響 / Effect on other teams
特に大きな影響があるわけではないがタスクゴーストがいると除霊に集中することもあるためキルなどのチャンスがなくなる可能性がある

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 幽霊がアサインされる可能性がある設定の場合すべてのプレイヤーに除霊ボタンが追加され幽霊が近づいた時に
除霊ボタンを押すと除霊をすることができタスクゴーストは通常の幽霊になる。

他の人に追加でボタンを表示できるようにはExRは開発されてないのでこの能力を変更する必要がある気がします

> クルーメイト以外がこの役職になれるか (これをオンにするとインポスターやジャッカルもこの役職になれる

幽霊役職の基本的な仕様として陣営を跨いだアサインは出来ないようになっているので、生存時ニュートラル死亡後ニュートラルとなりますが問題ないですかね

**Comment by unhappyset** [comment]
生存時ニュートラル死亡後ニュートラルは問題ないとして他の人に追加でボタンを表示するのをどうするかですね...

**Comment by unhappyset** [comment]
ちなみに他の人に追加でボタンを表示させるのは作れば可能ですか？

**Comment by yukieiji** [comment]
UI/UX的にやりたくないですね

**Comment by unhappyset** [comment]
タスクゴーストが近づいた時使用ボタンを除霊ボタンに変更するというのはできるでしょうか

**Comment by yukieiji** [comment]
使用ボタンの画像を変えるのは出来ないですね
