### ISSUE TITLE
ムーバーでルビータスクを動かすとY方向の移動が反映されない

### ISSUE THREAD

**Issue by kamumoti** [yukieiji/ExtremeRoles#270]
## バグの詳細 / Detail of bug
エアシップにある金庫室の宝石磨きのタスクを新役職のムーバーで移動させたら置いた瞬間に消え、オブジェクトがもとにある宝石磨きタスクと同じy軸のところにもどり、結果的にx軸しか動いていないバグ
### 実際の動作 / The Reality
動画の通り:https://youtu.be/zyq79ZpRj6c
ムーバーの能力でエアシップの宝石磨きタスクをほかの位置に移動させるとy軸は移動せず、x軸しか移動しませんでした。

### このバグに対するあなたの意見 / Your Proposal
位置によってタスクが幽霊以外できない可能性があると思うので直していただけると幸いです。

### バグ発生時のログ / log when issue occur
[ExtremeRolesBackupLog 2023-05-02T22-09-21.log](https://github.com/yukieiji/ExtremeRoles/files/11374571/ExtremeRolesBackupLog.2023-05-02T22-09-21.log)

### Among Usバージョン/ Among Us Version

Among Us v3.28

### Modバージョン / Mod Version

Extreme Roles v7.1.0.0

### リージョン/Region

- [ ] :北アメリア/Noth America
- [x] :欧州/Europa
- [ ] :アジア/Asia
- [ ] :カスタム/Custom
- [x] :ローカル
### プレイヤー人数/Player Num
4～5人

### 使用したオプション/Use Option

[option.csv](https://github.com/yukieiji/ExtremeRoles/files/11374831/option.csv)

**Comment by kamumoti** [comment]
動画のurlを間違えました。
こちらです:https://youtu.be/5hx0xxONboI
　　　　　https://youtu.be/tLIkFCJg7YM

**Comment by yukieiji** [comment]
コミット：[096f1a6b80bab33295871c8b0f3ef418d3252900](https://github.com/yukieiji/ExtremeRoles/commit/096f1a6b80bab33295871c8b0f3ef418d3252900)で修正済み

**Comment by yukieiji** [comment]
[v7.1.0.1](https://github.com/yukieiji/ExtremeRoles/releases/tag/v7.1.0.1)にて修正
