### ISSUE TITLE
[クルーメイト/Crewmate] : スプリンター/Sprinter (短時間足が速くなる能力)

### ISSUE THREAD

**Issue by raiga0310** [yukieiji/ExtremeRoles#276]
### 役職名 / Role Name
スプリンター / Sprinter
### 役職の色 / Role color
鉛 / Lead
### 役職の説明 / Role description
一定時間足が速くなる(状態中は解除可能) 解除･能力使用可能時間終了後､または能力使用中にレポートや緊急会議が入った場合はその会議後一定時間足が遅くなる
### 役職の能力 / Role ability

- ボタン能力｢スプリント｣
  - ボタン｢スプリント｣を使用すると一定時間移動速度が上がる
  - ボタン｢スプリント｣は｢インターバル｣ボタンに変わる
- ボタン能力｢インターバル｣
  - ボタン｢インターバル｣を使用､及び｢スプリント｣使用可能時間終了､会議やレポートによる中断の後の会議後､能力｢スプリント｣の使用時間に応じて｢インターバル｣状態となり､移動速度が下がる
  - ｢インターバル｣状態はそのまま能力｢スプリント｣の使用クールタイムとなる
- 連続使用のペナルティ
  - 実際の短距離選手同様､能力｢スプリント｣は使用するたびに使用可能時間､｢インターバル｣ 状態の継続時間が伸びる
  - (これはルールの調整次第で採用しなくとも良いかもしれません)上限使用回数を使い切ると､常に｢インターバル｣状態になる
｢スプリント｣を使用すると､あらゆる場面でタスクのための移動やAirshipでの緊急招集､怪しいと考える人物から逃走しやすくなる､などが挙げられます｡(ただ移動速度の倍率によってはかなり移動しづらいとは思うのでそこまで壊れることもないと考えています)

### 他陣営への影響 / Effect on other teams
- クルーメイト陣営以外: 単純に通常のクルーではできない速度での逃走やサボタージュ対応などができるため､できるだけ排除したい(シェリフなどのような直接的に脅威にはなりづらい)
  - ただヒプノティスト､ジャッカル､クイーンなど味方に引き込める役職は簡単に白証明取れるので仲間にしやすそう

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> ボタン能力｢インターバル｣
ボタン｢インターバル｣を使用､及び｢スプリント｣使用可能時間終了､会議やレポートによる中断の後の会議後､能力｢スプリント｣の使用時間に応じて｢インターバル｣状態となり､移動速度が下がる
｢インターバル｣状態はそのまま能力｢スプリント｣の使用クールタイムとなる

この能力で以下の点が気になりました
  - 初期クールタイムのときもインターバル判定になるのか
    - インターバル判定である場合
        - ゲーム開始時から動きづらい + ゲーム開始時から真っ白の役職になるのでかなり強い or 動きづらい部分と確定で白が取りやすいので使いにくい役職になる
    - インターバル判定ではない場合
        - 必ずあるクールタイムのオプションとの兼ね合いをどう考えるのか
  - 「能力｢スプリント｣の使用時間に応じて｢インターバル｣状態となり､移動速度が下がる」この部分はどういうことですか？5秒使ったら5秒のクールタイムが発生するということでしょうか

> ただヒプノティスト､ジャッカル､クイーンなど味方に引き込める役職は簡単に白証明取れるので仲間にしやすそう

こういう白確が取りやすい役職はクイーン以外味方に引き込むことは難しいと思っています
理由としてはサーヴァント以外は能力が使えないのでインターバル状態じゃないよねとか走れないよねでつられやすいからですね

**Comment by raiga0310** [comment]
> 初期クールタイムのときもインターバル判定になるのか 

インターバル判定ではなく､通常の移動速度だと考えています｡

> インターバル判定ではない場合
    必ずあるクールタイムのオプションとの兼ね合いをどう考えるのか

状態としては｢通常｣｢スプリント｣｢インターバル｣の3種を遷移していくイメージです｡ゲーム開始時は｢通常｣で､｢スプリント｣→｢インターバル｣→｢通常｣の順でボタン使用及びクールタイムの終了で切り替わると想定しています｡

> 「能力｢スプリント｣の使用時間に応じて｢インターバル｣状態となり､移動速度が下がる」この部分はどういうことですか？5秒使ったら5秒のクールタイムが発生するということでしょうか

その認識でかんがえています｡｢スプリント｣はそこまで長い時間使える想定はしていないため(10s~15sほど)､同程度の時間であればタスクの場所などでやり過ごしたりなども可能かな､という思考でそういった説明を記載しました｡

> 理由としてはサーヴァント以外は能力が使えないのでインターバル状態じゃないよねとか走れないよねでつられやすいからですね

これに関しては考慮が漏れていました｡ご指摘ありがとうございます｡

**Comment by yukieiji** [comment]
> 状態としては｢通常｣｢スプリント｣｢インターバル｣の3種を遷移していくイメージです｡ゲーム開始時は｢通常｣で､｢スプリント｣→｢インターバル｣→｢通常｣の順でボタン使用及びクールタイムの終了で切り替わると想定しています｡

そうなるとクールタイムとどういう関係をもたせればいいのかって形になりませんか？

**Comment by raiga0310** [comment]
(質問の意図が汲めてなかったら指摘してください)
｢スプリント｣のクールタイムと"そうでない"状態のクールタイムで分ける形


現状この能力を実装可能でありそうな`CreatePassiveAbilityButton`で想定すると､
- 状態とクールタイムの関係は｢インターバル｣&｢通常｣と､｢スプリント｣で2種として管理する
  - e.g.: 既定のクールタイムが20sで初回のスプリントを5s使用した後のクールタイムは25sになり｢インターバル｣状態に移行､クールタイムが20s(=既定のクールタイム)以下で｢通常｣状態になる

のような形になるかと考えています｡

個人的には3つ状態を持てるボタン実装があれば､とも思いましたが､現状の実装を見てこのようなかたちであれば､と
(ただなんとなくで読んでるので誤解があれば指摘してくださると助かります)

**Comment by yukieiji** [comment]
うーん、現状の実装だとExRのボタンは[この状態](https://github.com/yukieiji/ExtremeRoles/blob/a2daa1e9247f4997ac41d866f4c5f20933a43a19/ExtremeRoles/Module/ExtremeAbilityButton.cs#L10)しか取れないのでそれとこの能力をどうやって組み合わせるかってのが問題ですね(ステータス周りは[ここらへん](https://github.com/yukieiji/ExtremeRoles/blob/a2daa1e9247f4997ac41d866f4c5f20933a43a19/ExtremeRoles/Module/ExtremeAbilityButton.cs#L158)で処理してるんですが)

> 現状この能力を実装可能でありそうなCreatePassiveAbilityButtonで想定すると､

パッシブ能力だと切り替え式になるのでおそらくこの能力では実装できない気がします

**Comment by raiga0310** [comment]
クールタイムの途中で何か状態を変えるなどは現状難しい感じですね。
スプリントとインターバルを別の能力ボタンとして独立させ、それぞれの状態を取って処理する、というのはどうでしょうか

**Comment by yukieiji** [comment]
> クールタイムの途中で何か状態を変えるなどは現状難しい感じですね。

ここに新しい状態を入れれればまぁ出来なくはないんですけど、そうなった場合その仕様を考える必要が出てきます

> スプリントとインターバルを別の能力ボタンとして独立させ、それぞれの状態を取って処理する、というのはどうでしょうか

基本的にボタンは一つしか作れないようになってるので難しいと思われます
謎のボタンがあるのはちょっとUX的に良くない気がします

**Comment by raiga0310** [comment]
> ここに新しい状態を入れれればまぁ出来なくはないんですけど、そうなった場合その仕様を考える必要が出てきます

そうですよね、なのでこの役職以外にそういった複数状態必要なロールが別にないので旨味がないと思いました

複数ボタンが難しいのであれば、単なる思いつきですがサーヴァント、サイドキック、ドールにするときのボタン追加、更新のような挙動で実現は可能ですか　状態に応じて自身の能力を更新してボタンを配置し直せば……と

**Comment by yukieiji** [comment]
> 複数ボタンが難しいのであれば、単なる思いつきですがサーヴァント、サイドキック、ドールにするときのボタン追加、更新のような挙動で実現は可能ですか 状態に応じて自身の能力を更新してボタンを配置し直せば……と

うーん、あれはただたんにボタンの表示を隠してるだけなので消してるわけではないんですよね

**Comment by raiga0310** [comment]
隠したものを再度表示させるのは難しいですかね

**Comment by yukieiji** [comment]
表示することは出来るんですが、インターバルを作るためだけにもう一個のボタンを作るのは力技すぎる気がします(1役職の為だけにそのような複雑なことはやりたくはないですね)

新しい状態を作ってその仕様を考えたほうが楽な気がします

**Comment by raiga0310** [comment]
`Penalty`(仮称)状態を追加
ボタン(能力)にペナルティがあるかどうかの属性を追加
- `Penalty`は能力終了後のペナルティ期間を示す 能力などに制限がかかる状態
  - `Activating`の終わり → (if `hasPenalty`) → `Penalty` → `CoolDown`
  
こんな感じでしょうか

**Comment by yukieiji** [comment]
> ボタン(能力)にペナルティがあるかどうかの属性を追加

それするとステートパターンっぽく作った意味がなくなってしまう・・・・

まあ実装できるできないは出来るとは思われるでいいので、役職の仕様的な話に戻します
気になってる点と言うか懸念点が以下の部分があります
 - ボタンを押せば白確が取れてしまうこの役職は個人的にあんまり好きではない
    - TORのスプリンターが入ってない理由ですね、白確を取りつつ人外からキルされることが不可能になる
 - インターバルとクールタイムというユーザーにとって分かりにくい要素がある
   - 分かりにくいから使いにくくなりそう？
     - 今のデリュの現状と同じになりそう
