### ISSUE TITLE
マッシュルーム / Mushroom

### ISSUE THREAD

**Issue by Harupyie1803** [yukieiji/ExtremeRoles#28]
### 役職名 / Role Name
マッシュルーム / Mushroom

### 役職の色 / Role color
黄緑 / Lime

### 役職の説明 / Role description
接触キルされたら、胞子を振りまくぞ！
船内を胞子でいっぱいにしたら勝ち

### 役職の能力 / Role ability

接触キル(ショート、ミドル、ロング問わず)された瞬間、胞子を発射する。
NOTSのエンパイリックのように全員うつすとシュルーム陣営が勝利する。
また、会議を3回挟むとその人の胞子は消えてしまう。しかしその人も再度感染することがあるので接触には注意しよう。
1試合に1体だけジャッカルのサイドキックように「シュルームキッド / Mycelium」を作ることが可能。
シュルームキッドは昇格しないが、マッシュルームのように接触キルで胞子を発射する。

### 他陣営への影響 / Effect on other teams
ヴァンパイアなど遠隔キルを行う役職にキルされた場合、胞子を発射せずに死亡してしまう。
胞子は陣営を問わず接触した瞬間に胞子を増殖させることが可能。
感染したクルーに対してキルをおこなっても胞子がキルした側に移るのでシュルーム陣営にとっては問題なし。

### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
個人的にはニュートラルはクルーとインポスター両陣営に害があるようにしたいのですが、この役職はどちらにも害がないですし運任せの役職なのでニュートラルとしてどうなのかという疑問が湧いてきます

**Comment by Harupyie1803** [comment]
害か…といわれると胞子に掛かったクルーやインポスターがスピードが遅くなるという感じのやつとか
キルクールタイムが本来より1.5延くらい伸びる(TORのサイコキラーのようなキルクール(デフォルト)が15秒から22.5秒に延びる)
他のアイデアとしては左右キーの移動が逆になる(設定で上下もできる)というのも考えてます

**Comment by yukieiji** [comment]
> 害か…といわれると胞子に掛かったクルーやインポスターがスピードが遅くなるという感じのやつとか

遅くなれば広がりにくくなって勝利が遠のきますが・・・

> キルクールタイムが本来より1.5延くらい伸びる(TORのサイコキラーのようなキルクール(デフォルト)が15秒から22.5秒に延びる)

インポスターにしかデメリットがないです

> 他のアイデアとしては左右キーの移動が逆になる(設定で上下もできる)というのも考えてます

害がプレイヤーのストレスになるのはNGだと思います

**Comment by yukieiji** [comment]
4/24までに返信がない場合はクローズさせていただきます

**Comment by yukieiji** [comment]
返信や更新がないためクローズします
