### ISSUE TITLE
プレイヤーがキルされて復活するとヤンデレの邪魔者に登録されることがない

### ISSUE THREAD

**Issue by RanasGlif** [yukieiji/ExtremeRoles#281]
## バグの詳細 / Detail of bug

ヤンデレの邪魔者の登録されたゾンビを一度キルすると復活以後想い人に接近しても邪魔者として登録されない

### 期待される動作 / Your Expectation

キルされたゾンビにも再度邪魔者として登録される
### 実際の動作 / The Reality

一度邪魔者登録されて死んだゾンビは以後　邪魔者として登録されない
### このバグに対するあなたの意見 / Your Proposal

発生したところで盤面でゾンビを吊らない　キルしない状況が想定されないので優先度は低めですが発見したのでバグとして報告させて頂きます　リザクレターでは未検証ですが同様の挙動を起こしそうだと思いました

### Among Usバージョン/ Among Us Version

Among Us v2023.3.28s

### Modバージョン / Mod Version

Extreme Roles v7.1.2.1

### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [x] :アジア/Asia
- [ ] :カスタム/Custom
- [ ] :ExR専用(東京)

### プレイヤー人数/Player Num

4人

**Comment by yukieiji** [comment]
コード的にリザレクターでも発生するような感じではありますが、リザレクターが実装されてから半年以上経っても表面化しなかったことと修正が多少面倒なので一旦優先度は低い不具合とさせていただきます
