### ISSUE TITLE
ExR東京サーバー入場時のメッセージの誤記

### ISSUE THREAD

**Issue by salicyla** [yukieiji/ExtremeRoles#282]
### 追加する機能の詳細 / Feature details
ExR東京サーバー入場時に自動送信されるシステムメッセージの「ニコニコクリエイターサポート」のURLがyukieiji様ではなくシルシラ様（user/220860）のものになっております。
バグではないのでこちらにて。

**Comment by yukieiji** [comment]
修正しました
一応、私が作った非公開サーバープラグインでこの動作は実現していますので今後はバグのチケットを作っていただけたらなと思います(機能追加であればこのテンプレートで問題ないと思います)

**Comment by salicyla** [comment]
承知いたしました。お手数おかけして申し訳ありません。
