### ISSUE TITLE
コンビネーション役職：ヒーロー、ヴィラン、ヴィジランテ（九十九さん提案）

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#3]
### 役職名 / Role Name
ヒーロー、ヴィラン、ヴィジランテ
### 役職の色 / Role color
ヒーロー：天色
ヴィジランテ：藤色
### 役職の説明 / Role description
- ヒーロー
  - 生存者が少なくなることで強くなるクルー役職
  - 少なくなることでキル能力等に覚醒していきます
  - ヴィランをキルした場合、返り討ちに合う
- ヴィラン
  - 最初から強力な能力を持つインポスター役職
  - ありとあらゆるガードシステムを貫通するキル能力を持つ
  - 更にボタンによって発動する能力を持つ
  - ヒーローをキルした場合、返り討ちに合う
- ヴィジランテ
  - ヒーローとヴィランに殴り合いをさせる盤面を作り出すゲームコントローラ的なニュートラル役職
  - 勝利条件
    1. ヒーローとヴィランが相打ちをして、生き残った場合(この時別陣営の勝利にも乗れる)
    2. ヒーロー/ヴィラン/ヴィジランテの3人のみが生き残る。
    3. ヴィランが落ちた場合はインポスター陣営の勝利
    4. ヒーローが落ちた場合はクルー陣営の勝利

### 役職の能力 / Role ability

- ヒーロー
  - パッシブ(解除不可)：One for All
    - 生存者が減っていくことで様々な能力が覚醒する
      - 第1段階：パッシブ能力「光の加護」取得
      - 第2段階：キル能力獲得(自分は自爆しない)
      - 第3段階：ボタンの能力付与
  - パッシブ(解除不可)：光の加護
    - ヴィラン以外のキルを無効化する
    - 視界設定が最大になる
   - ？？？
     - 全プレイヤーの位置が矢印と距離で表示される 
- ヴィラン
   - パッシブ(解除不可)：デストロイヤー
     - キルボタンのキルが必ず成功する
       - タイムマスターのタイムシールド、ボディーガードのシールド、守護天使のガード等を貫通する
  - パッシブ(解除不可)：闇の加護 
    - ヒーロー以外のキルを無効化する
   - ？？？
     - 全プレイヤーの位置が矢印と距離で表示される 
- ヴィジランテ
  - パッシブ(解除不可)：？？？
     -  自身はヒーロー及びヴィランにはキルされない。その他のキルや投票による追放は有効。
  - エマージェンシーコール
     - ミドルレンジ内の対象1人の居場所を一定時間(調整可能最大1分程)ヒーローに知らせる、使用時ヴィランに自身の居場所がわかる。

### 他陣営への影響 / Effect on other teams
なし、この3つの役職が勝手にバランスを調整する

### 陣営 / Team
- [x] :ヒーロー、 クルー/Crewmate
- [x] :ヴィラン、インポスター/Impostor
- [x] :ヴィジランテ、 ニュートラル/Neutral

**Comment by Inumiya** [comment]
こちらでははじめまして戌宮です

ヴィジランテ能力案
エマージェンシーコール：特定プレイヤーの位置をヒーローに知らせる
・ミドルレンジ内のプレイヤー1人が対象
・持続は長くても1分程度？
・ヴィランっぽい人に対してヴィジランテが使用するイメージ
・ヒーローにもプレイヤーの位置を把握する能力を実装予定のようですが、ヴィジランテに役目を持たせるために、ヒーローは位置把握能力を終盤まで持てなくても良いかなと思いました
・（自分の位置を知らせた方がエマージェンシーコールっぽいですが使いにくそうなので他者の位置を知らせるように）

**Comment by yukieiji** [comment]
能力は良さそうです、回数制限もつければいい感じになりそうです

> ヒーローにもプレイヤーの位置を把握する能力を実装予定のようですが、ヴィジランテに役目を持たせるために、ヒーローは位置把握能力を終盤まで持てなくても良いかなと思いました

そうですね、ヒーローの？？？「全プレイヤーの位置が矢印と距離で表示される」これは、One for Allの第三段階で付与されるボタンの能力になる予定です

**Comment by Inumiya** [comment]
> ヒーローの？？？「全プレイヤーの位置が矢印と距離で表示される」これは、One for Allの第三段階で付与されるボタンの能力になる予定です

上記承知です

エマージェンシーコールを複数回使うと誰がヒーローかなんとなく検討がついてしまいそうなのですが、ヴィジランテがヒーローの正体を知ってしまうことでゲームバランス崩れたりしないでしょうか？

**Comment by yukieiji** [comment]
> エマージェンシーコールを複数回使うと誰がヒーローかなんとなく検討がついてしまいそうなのですが、ヴィジランテがヒーローの正体を知ってしまうことでゲームバランス崩れたりしないでしょうか？

ヴィジランテ自体は第三陣営なのでヒーローの正体が分かっても問題はないと思われます
ヴィジランテ自体の特殊勝利(くっそ難しい)によっては問題が出そうですが現状はまだ決定してないので大丈夫です()

**Comment by MasakaTukumo** [comment]
ヴィジランテの単独勝利条件案
ヒーロー/ヴィラン/ヴィジランテの3人のみが生き残る。

**Comment by Inumiya** [comment]
> 使用時にヴィランにヴィジランテの位置が矢印で表示されるのはどうですか？

ヴィジランテがヴィランに対してエマージェンシーコールを使った場合、ヴィラン目線、ヴィジランテの正体が確定してしまいますね。

> ヴィジランテの単独勝利条件案
ヒーロー/ヴィラン/ヴィジランテの3人のみが生き残る。

そうなるとこの勝利条件がほぼ満たせなくなります。
ヴィジランテの単独勝利じゃなければ見逃してもらえそうですが、単独勝利ならヴィランは絶対ヴィジランテをキルします。

ただ、「ヴィジランテはヒーローの正体を知っていて、ヴィランはヴィジランテの正体を知っている」という状況は面白そうなので、ヴィジランテの勝利条件の方を調整したら良いかなと思いました

**Comment by yukieiji** [comment]
> そうなるとこの勝利条件がほぼ満たせなくなります。

ヴィジランテの単独勝利条件は少し難し目のほうがいいのかなって私は思っています(簡単なものだとゲームコントロールを放棄してそっちの勝利を目指そうとしてしまうので)

> ヴィジランテの単独勝利じゃなければ見逃してもらえそうですが、単独勝利ならヴィランは絶対ヴィジランテをキルします。

ヴィジランテはヒーローとヴィランからはキルできないようにしてもいいかなーとは適当に考えています。(バランス的にまだ未検討部分が多い)
- ヒーロ目線：ヴィジランテは生かしてヴィランを探してほしい、ヴィランを潰せるのは自分と会議以外ないので
- ヴィラン目線：ヴィジランテは潰したいけどキルできないので吊る(それを扇動すると自分が吊られる)、ヒーローとは当たりたくない(ちょっとヴィランがきついのかな？(デストロイヤーがあるってメリットを考えれば妥当？)他のインポスターがキルするのを待つ)

**Comment by Inumiya** [comment]
> ヴィジランテはヒーローとヴィランからはキルできないようにしてもいいかなーとは適当に考えています。

これいいですね。ヴィランはキル能力が最強なので、単純にキルできない相手が増えるのは良いと思います。
会議中にヴィジランテ吊りを主導するためには、白位置にいないといけないので、ヴィランによる雑キルも抑制できそうです。

（細かいですが、アサシンの特殊会議でのインポスターチャットで、味方インポスターにヴィジランテ抹殺依頼が出せるので、マーリン・アサシンとは併用難しいそうですね）

**Comment by yukieiji** [comment]
> （細かいですが、アサシンの特殊会議でのインポスターチャットで、味方インポスターにヴィジランテ抹殺依頼が出せるので、マーリン・アサシンとは併用難しいそうですね）

他のインポスターが残ってる状態でのアサシンの特殊会議でその様な会話を繰り広げることあんまり無いと思います(マーリンを当てないとインポスターが超危機的状態に陥るので・・・)

**Comment by Inumiya** [comment]
確かにマーリン吊ったら終わるし、吊れなかったらマーリンCOでインポスター壊滅でしたね

**Comment by MasakaTukumo** [comment]
ヴィジランテ(仮)
第3陣営
常時能力：自身はヒーロー及びヴィランにはキルされない。
その他のキルや投票による追放は有効。

起動能力：エマージェンシーコール
ミドルレンジ内の対象1人の居場所を一定時間(調整可能最大1分程)ヒーローに知らせる、使用時ヴィランに自身の居場所がわかる。

勝利条件
a.ヒーローとヴィランが相打ちをして、生き残った場合(この時別陣営の勝利にも乗れる)
b.ヒーロー/ヴィラン/ヴィジランテの3人のみが生き残る。
c.ヴィランが落ちた場合はインポスター陣営の勝利
d.ヒーローが落ちた場合はクルー陣営の勝利


今のところこんな感じでしょうか（勝手にまとめました）個人的にはいい感じにまとまってきてると思います。

**Comment by yukieiji** [comment]
@MasakaTukumo 
そろそろ実装にも取り掛かろうかなーと思うので実装に向けた調整を行いたい感じです
現状問題がある点とそれに対する自分の案を乗せておきます。問題がない場合、これで実装します
- ヒーロー：光の加護とヴィラン：闇の加護が第三陣営(ニュートラル)に対して刺さりすぎてる問題
  - 案：光の加護はインポスター限定、闇の加護はクルー限定にする
    - 第三陣営の勝利もしやすくなるはず
- ヒーロー：光の加護はインポスターの特殊キルすら守れるのか
  -  案：守れないでいい気がする
- ヒーロー：One for Allの発動具合
  - 案：第一段階が一人死亡(どんな人数でも)、第2段階が5人死亡(33％死亡)、第3段階が10人死亡(66％死亡)
- ヴィランが最後のインポスターで吊られた時のヴィジランテはどうしましょうか
  - 案1：そのまま、他の第三陣営が居ない場合は敗北が確定
  - 案2：インポスターが全滅した場合何らかの勝利条件を設ける

**Comment by MasakaTukumo** [comment]
4つ目勝利条件について
ヴィジランテの陣営移行時の処理でキル能力を付与（キルクール遅め？）、勝利条件は陣営移動を適用させるはダメでしょうか？
記述の状況だと、「自分とクルー1人以下の状況になる」が勝利条件になる。

他の項目についてはyukieijiさんの案で問題ないと思います。

**Comment by yukieiji** [comment]
> 4つ目勝利条件について
ヴィジランテの陣営移行時の処理でキル能力を付与（キルクール遅め？）、勝利条件は陣営移動を適用させるはダメでしょうか？
記述の状況だと、「自分とクルー1人以下の状況になる」が勝利条件になる。

ヴィランが最後に釣られた場合、新しい有害な第三陣営として覚醒するという形で問題ないでしょうか

**Comment by MasakaTukumo** [comment]
陣営がインポスター側に移り、追加のインポスターとして覚醒する形です。(ヒーローが残っていれば)
ヴィジランテの単独勝利が不可能になった場合、ヒーローorヴィランの意志を引き継ぐ形にしたいです。
状況では実質インポスター+1になりますが、第3陣営はそんなものかと思います。
ヒーローとヴィランの完全同士討ちの場合は敗北確定になってもらうしか・・・。

**Comment by yukieiji** [comment]
> 陣営がインポスター側に移り、追加のインポスターとして覚醒する形です。(ヒーローが残っていれば)
ヴィジランテの単独勝利が不可能になった場合、ヒーローorヴィランの意志を引き継ぐ形にしたいです。
状況では実質インポスター+1になりますが、第3陣営はそんなものかと思います。

そうなると実質的にインポスターが強くなってしまう(ヴィランとキルできないヴィジランテをクルーが相手しないといけない)のでやるならば、有害な第三陣営として覚醒する感じの方がバランス的には取れそうな気がします(覚醒する条件もインポスターが全滅してて有害な第三陣営が存在しない場合というレアケースと言えばレアケースですし)

> ヒーローとヴィランの完全同士討ちの場合は敗北確定になってもらうしか・・・。

これがヴィジランテ的には勝利判定に入るので問題無いと思います。
唯一問題があるとすればゲームの早い段階でヒーローとヴィランが同士討ちしてしまった場合ですかね(同士討ちが発生する時間の猶予をオプションで設けるとかでしょうか)

**Comment by yukieiji** [comment]
> ヴィランが最後のインポスターで吊られた時のヴィジランテはどうしましょうか

ここわかりにくかったので少し補足します
ヴィランやヒーローが落ちて(キル、追放、切断)その陣営としての勝利が無くなる場合(以下の例)のヴィジランテの勝利条件をどうするのか？って感じです
- 例1：ヴィランがラストインポスターで落ちた時
- 例2：ヒーロー1、クルー1、ヴィラン1、インポスター1、ヴィジランテ1の盤面でヒーローが落ちた時

**Comment by MasakaTukumo** [comment]
例1：第3陣営として覚醒（新たなヴィランとなる）
例2：クルー陣営に移る為インポスターとクルーが同数になり、インポスター勝利

でどうかと思うのですが、この場合動きの傾向が偏る可能性があるのが心配になります。

**Comment by yukieiji** [comment]
> 例2：クルー陣営に移る為インポスターとクルーが同数になり、インポスター勝利

例1と例2は基本的に似たような状態なので個人的には新しく有害な第三陣営に覚醒という形にしたいですがどうでしょうか
例1と例2に似たような状態以外でヒーローやヴィランが落ちた場合は基本的にクルー陣営かインポスター陣営に着く感じにはなるので基本コンセプトとしては崩壊してないと思います

**Comment by MasakaTukumo** [comment]
ゲーム的にはその方がバランスが取れる思うのでいいと思います。
どちらにしろヒーロー,ヴィランの勝利を妨げる勢力になる立ち位置は変わらないのでコンセプト的にもOKです。

**Comment by yukieiji** [comment]
v2.1.0.0開発用ブランチのコミット1909a88c81b39a2459ddb93318e474ce047710c1で一応完成したためクローズします
