### ISSUE TITLE
指揮官（インポスター役職：仲間のキルCT短縮）

### ISSUE THREAD

**Issue by UzomuZo** [yukieiji/ExtremeRoles#30]
意図しない投稿がされていましたので、改めて投稿させていただきます。

### 役職名 / Role Name
指揮官(コマンダー)

### 役職の説明 / Role description
「仲間のキルを援護して皆殺しにしよう」
自身のキルのクールタイム(以下CT)と時間を共有した能力を使用して仲間のキルCTを短縮して援護する。

### 役職の能力 / Role ability

「攻撃指令」の能力を使用すると自分のキルCTが消費されてその代わりに仲間のキルCTが短縮される。

能力CTはキルCTと共有、使用すると船全体のインポスター仲間のキルCTを短縮（例　キルCT20秒 → 短縮時間各5秒）
ただし仲間がキルできる状態（CTが溜まっている）でも消費される。

_メリット_
自分がキルが苦手でも仲間のキルCTを短縮することでキルしてもらえる。
キルCTと能力CTが共有なのでキルせずに仲間に任せて潜伏も可能。

_デメリット_
仲間がいなければ能力の意味はない。
能力を使用するとCTが消費されるので自分はキルできない。
自分のキルCTよりは短縮される時間は短く、無駄になることもある。
船全体にかかるため、仲間からは誰が能力使用者かわからない。

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
自分以外が落ちた時、ただのインポスターになってしまうという点と自分自身のキルクールと連動しているのでキルペースは全体的に落ちてしまうのでメリットよりデメリットが多い気がします(「攻撃司令」が空振りしなくとも他の人がそこでキルできるかどうかは分からない)

**Comment by UzomuZo** [comment]
前半は能力連打して潜伏しつつ支援、後半は能力なしで普通のキルと考えていましたが、たしかにデメリットは多いですね。

変更案１．
回数制限制(1～2回)、キルCTとは非共有にする
（付近に仲間がいればダブルキルしつつCT短縮で仲間がさらにキルを狙える）

案２．
キルCTと共有、キルCT短縮以外に別能力（キルレンジを次回延長、サボタージュのゲージを短縮など）を付与する（１つでも複数でも）

**Comment by UzomuZo** [comment]
どちらの案も微妙となると、できるかわかりませんがキルCT共有だけどインポスターの人数に応じて自身のキルCT短縮とかどうでしょうか？（例：インポスターが一人減るごとに2.5秒短縮、20→17.5→15秒）

短縮量の設定次第ですが、仲間が減った分を補えるのではないでしょうか？

**Comment by yukieiji** [comment]
> どちらの案も微妙となると、できるかわかりませんがキルCT共有だけどインポスターの人数に応じて自身のキルCT短縮とかどうでしょうか？（例：インポスターが一人減るごとに2.5秒短縮、20→17.5→15秒）
短縮量の設定次第ですが、仲間が減った分を補えるのではないでしょうか？

それくらいは可能でしょう

**Comment by UzomuZo** [comment]
永続が微妙なら、キルする毎に会議後に短縮が戻る。
会議を挟まなければ連続キルも可能。

例1：20 → 味方1人目死亡後の会議 → 17.5 → 1キル → 会議 → 20 →
　　 2人目死亡後の会議 → 17.5 → 会議 → 17.5 → 2キル → 17.5 → 会議 → 20
例2：20 → 味方2人死亡 → 15 → 1キル → 会議 → 17.5
例3：20 → 味方2人死亡 → 15 → 2キル → 会議 → 20

**Comment by yukieiji** [comment]
> 永続が微妙なら、キルする毎に会議後に短縮が戻る。
会議を挟まなければ連続キルも可能。

味方のインポスターがキルされる毎にその人の分だけキルクールが短くなるということでしょうか

**Comment by UzomuZo** [comment]
> 味方のインポスターがキルされる毎にその人の分だけキルクールが短くなるということでしょうか

そうです。

味方がキルされる(デス)ことによる短縮と自分がキルすることによる延長が会議ごとに発生する感じです。
ただしキルによる延長は初期のキルクールタイムまでで。
もし会議ごとじゃなくて即時にするなら、キルによる延長時間をデスによる短縮より少なくする感じでしょうか。

**Comment by yukieiji** [comment]
大分返信が遅れました

> 前半は能力連打して潜伏しつつ支援、後半は能力なしで普通のキルと考えていましたが、たしかにデメリットは多いですね。

これはすごい私情なのですが、能力連打するみたいな役職はプレイングのつまらなさと戦術がワンパターンになるという点で問題がある気がします(この能力連打が前提なら、その役職でキルクールを調整しないのはなぜってなる気がします)

> 味方がキルされる(デス)ことによる短縮と自分がキルすることによる延長が会議ごとに発生する感じです。
ただしキルによる延長は初期のキルクールタイムまでで。
もし会議ごとじゃなくて即時にするなら、キルによる延長時間をデスによる短縮より少なくする感じでしょうか。

この能力がこの役職のコンセプトと名前として合ってるのか疑問です

**Comment by UzomuZo** [comment]
> 大分返信が遅れました

幽霊役職等の対応お疲れ様です。

> この能力がこの役職のコンセプトと名前として合ってるのか疑問です

指揮官が指揮する相手が少なくなったのでキルする余裕ができると考えるならありかな、と思ったのですが。

> これはすごい私情なのですが、能力連打するみたいな役職はプレイングのつまらなさと戦術がワンパターンになるという点で問題がある気がします(この能力連打が前提なら、その役職でキルクールを調整しないのはなぜってなる気がします)

たしかにワンパターンになると問題ですね。
通常キルはたしか各職クールタイム初期は共通でしたよね？
前に別のissueを見て個別にキルクール変更はできないと記憶していました。
というわけで変更案を考えてみました。

案1．
回数制限をつける。（初期回数と上限設定あり）
自身のキル数に応じて増加（例えば2キルで+1回）
仲間が1人減るごとにキルCT短縮。

案2．
能力を使うとクール延長、キルすると減少。（上下限設定あり）
仲間が減るとキルCTの限界が強化。（実質キルCT短縮）
例えば仲間2人の場合は-2～+6秒だが、仲間1人減るごとに-4～+6秒、-6～+6秒と変わる。
あるいは-2～+6、-4～+5、-6～+4と上限も減る。

**Comment by yukieiji** [comment]
> たしかにワンパターンになると問題ですね。
通常キルはたしか各職クールタイム初期は共通でしたよね？
前に別のissueを見て個別にキルクール変更はできないと記憶していました。

基本的に共通なのですがキル役職は全員オプションで個別設定が出来るはずです(自動生成されるので大丈夫かと、別のissuesにあったのは追加でそのオプションを追加してか最初からキルクールを少なくしてって話だったと思います)

> 案1．
回数制限をつける。（初期回数と上限設定あり）
自身のキル数に応じて増加（例えば2キルで+1回）
仲間が1人減るごとにキルCT短縮。
案2．
能力を使うとクール延長、キルすると減少。（上下限設定あり）
仲間が減るとキルCTの限界が強化。（実質キルCT短縮）
例えば仲間2人の場合は-2～+6秒だが、仲間1人減るごとに-4～+6秒、-6～+6秒と変わる。
あるいは-2～+6、-4～+5、-6～+4と上限も減る。

やるなら案1の方でしょう、キルCT短縮ってより能力で下がるキルクールタイム増加とかの方がいい機がします

**Comment by UzomuZo** [comment]
> 基本的に共通なのですがキル役職は全員オプションで個別設定が出来るはずです(自動生成されるので大丈夫かと、別のissuesにあったのは追加でそのオプションを追加してか最初からキルクールを少なくしてって話だったと思います)

なるほど、多分最初から少なくしてっていうので、勘違いしてました。

> > 案1．
> > 回数制限をつける。（初期回数と上限設定あり）
> > 自身のキル数に応じて増加（例えば2キルで+1回）
> > 仲間が1人減るごとにキルCT短縮。
>
> やるなら案1の方でしょう、キルCT短縮ってより能力で下がるキルクールタイム増加とかの方がいい機がします

前に出た話で一人になったときに無力化されるっていうのでキルCT短縮にしたんですが、
仲間が減るごとに能力で下がるクールタイム増加に併せて、仲間が全滅した場合は能力が使う意味がないのでキルCT短縮にするのもできるんでしょうか？

**Comment by yukieiji** [comment]
> 前に出た話で一人になったときに無力化されるっていうのでキルCT短縮にしたんですが、
仲間が減るごとに能力で下がるクールタイム増加に併せて、仲間が全滅した場合は能力が使う意味がないのでキルCT短縮にするのもできるんでしょうか？

色々と話しが混じってますが以下の感じでどうでしょうかと言う形です
- キル数に応じて回数増加
- 仲間が減る毎に能力強化

**Comment by UzomuZo** [comment]
> 色々と話しが混じってますが以下の感じでどうでしょうかと言う形です
> 
> * キル数に応じて回数増加
> * 仲間が減る毎に能力(キルクールタイム減少量)強化

それでいきましょう。

**Comment by yukieiji** [comment]
実装をいつかお約束は出来ませんがとりあえずの優先度と実装内定であることをセットします

**Comment by UzomuZo** [comment]
わかりました。そのうち実装してください。

**Comment by yukieiji** [comment]
司令官の英語であるコマンダーとして実装が完了しましたクローズします

**Comment by UzomuZo** [comment]
ありがとうございます。
