### ISSUE TITLE
[クルー/Crewmate] :ネゴシエイター /Negotiator (クルー陣営に引き込む役職)

### ISSUE THREAD

**Issue by akirayasushi** [yukieiji/ExtremeRoles#306]
### 役職名 / Role Name

ネゴシエイター

### 役職の色 / Role color

クルー/白

### 役職の説明 / Role description

相手陣営をクルー陣営に引き込む役職です。

### 役職の能力 / Role ability

交渉術/対象のインポスター、第三陣営をクルー陣営に引き込む役職です。
能力が強力なので、タスク進捗が8割以上で、生き残りがゲーム開始の半数以下にならないとボタンがアクティブ化しない。また、クルー陣営に使用すると、自身と相手の両方が死亡する。
引き込まれた人のタスクは、ネゴシエイターが済ませているタスクの半数が追加される。
これがデフォルト設定と考えています。

### 他陣営への影響 / Effect on other teams

相手のお仲間は寝取られた事がわかる。

### 陣営 / Team

- [X] クルー/Crewmate
- [ ] インポスター/Impostor
- [ ] ニュートラル/Neutral

**Comment by yukieiji** [comment]
> クルー/白

白は無職と変わらないので、別の色にしていただければ

> 交渉術/対象のインポスター、第三陣営をクルー陣営に引き込む役職です。
能力が強力なので、タスク進捗が8割以上で、生き残りがゲーム開始の半数以下にならないとボタンがアクティブ化しない。また、クルー陣営に使用すると、自身と相手の両方が死亡する。
引き込まれた人のタスクは、ネゴシエイターが済ませているタスクの半数が追加される。

個人的にはコストはこれでも見合ってないとは思います
以下が理由です(要約すると「能力が使いやすい終盤であんまりデメリットを考えずに使える」って感じでしょうか、当たれば-1人外+1クルー白確+1が確定して外しても白確+2確定する)
 - タスクが8割進んでいる状況は人数がほぼ半数以下であることが多い(2つ目のコストが意味を成してない)
 - この役職の能力のことを時を考えると恐らく終盤と序盤が一番強いと思ってます。なので強い終盤に覚醒する
   - 序盤は適当な人を対象にしても人がいるから問題ない、終盤は人外っぽい人を対象に取りやすい(クルー勝利が見えていれば黒っぽい人に使う、人外勝利が見えているのであれば適当に使っていい)
 - クルーに使うともろとも死ぬということは白を2人作る => 簡易的なシェリフとして使えてしまう(個人的にシェリフの自爆白出しは本来想定されてないと思ってるのでそういった使い方ができる役職はちょっとって思ってしまいます)

以前放送等にも言って案にすら上がってないのはこういう強すぎる部分に対してのコストが測れないのが理由ですかね
序盤、終盤は覚醒できないようなシステムにして中盤に覚醒 + 相応のコストを払ってやっとだと思ってます

**Comment by akirayasushi** [comment]
﻿こんにちは。
内容を拝見しました。
クルー陣営に引き込める役職が有ればいいなと思って色々考えましたが、確かにご指摘の通りだと思いました。シェリフの自爆白出しとして使える点等考慮していませんでした。白が2人飛ぶなら中々使用できないかなーくらいにしか考えていなかったもので…
残念ですが、非常に難しいという点が分かりました。

ありがとうございました。

**Comment by yukieiji** [comment]
> クルー陣営に引き込める役職が有ればいいなと思って色々考えましたが、確かにご指摘の通りだと思いました。シェリフの自爆白出しとして使える点等考慮していませんでした。白が2人飛ぶなら中々使用できないかなーくらいにしか考えていなかったもので…
残念ですが、非常に難しいという点が分かりました。

ちゃんとコストを設定することができれば実装は出来ると思っています
個人的には上にも書いたのですが役職本体の覚醒と逆覚醒(素クルー化)の要素を入れ、中盤頃に覚醒し終盤前位に逆覚醒する
その上で能力を発動するためのコストを払えれれば問題ないと思います

追加でこの役職自体をSKしたりサーヴァント化したりするとネゴシエーターでクルー化した人も引き込めるみたいな要素もあると戦略が広がりそうではありますね

**Comment by akirayasushi** [comment]
> クルー陣営に引き込める役職が有ればいいなと思って色々考えましたが、確かにご指摘の通りだと思いました。シェリフの自爆白出しとして使える点等考慮していませんでした。白が2人飛ぶなら中々使用できないかなーくらいにしか考えていなかったもので…
> 残念ですが、非常に難しいという点が分かりました。
> 
> ちゃんとコストを設定することができれば実装は出来ると思っています
> 個人的には上にも書いたのですが役職本体の覚醒と逆覚醒(素クルー化)の要素を入れ、中盤頃に覚醒し終盤前位に逆覚醒する
> その上で能力を発動するためのコストを払えれれば問題ないと思います
> 
> 追加でこの役職自体をSKしたりサーヴァント化したりするとネゴシエーターでクルー化した人も引き込めるみたいな要素もあると戦略が広がりそうではありますね
> 

返信とアドバイスありがとうございます。
ご指摘の点も踏まえてじっくりと考えてみました。

タスク進捗が3割終わった所で覚醒し、6割終わると逆覚醒する形でしょうか。そうするとネゴシエイターのタスク進捗が必然的に遅れるのでクルー全体の進捗が遅くなりますから、クルーにとってデメリットになるかなって思いました。それに加えて生き残りが半数以下になっても逆覚醒すれば良いのかなって思いました。
後、交渉術ですから、能力使用して対象に5秒密着（アンブレイヤーみたいに）するにすれば使用し辛くなります。
使用した相手がクルーだった場合は両方死亡するか、相手だけ死亡するかが悩みどころではあります。自身だけが死亡するはシェリフと同じ使われ方をする可能性が高いので、これは除外しても良いと思います。
中盤限定能力と考えると中盤でクルー2人飛ぶのはクルー陣営としては辛い場面だと思いますので、両方死亡が良いような気はします。確かに2人が白確してしまう点はありますので人外を詰めやすくなるとは思いますが…それでも中盤でクルー2人飛ぶのは辛いのではないかなって思います。

・タスク進捗3割で覚醒、更にもう1タスク終わってから能力アクティブ化
・タスク進捗6割or全体の生き残りが半数以下で逆覚醒
・交渉術は使用して5秒間対象に密着
・クルーに引き込まれた人外のタスクはネゴシエイターの残りタスクと同じ
・使用した相手がクルーなら両方死亡する
・能力使用は一度きり

これに加えてyukieijiさんのアドバイスにあった通り、ネゴシエイターがSK、サーバント、ドール化された場合はクルー化した相手もその陣営に引き込める若しくはクルー化した相手が弾けると確かに色々な意味で面白いと思います。

ご検討いただけると幸いです。

哲泰

**Comment by yukieiji** [comment]
> タスク進捗が3割終わった所で覚醒し、6割終わると逆覚醒する形でしょうか。そうするとネゴシエイターのタスク進捗が必然的に遅れるのでクルー全体の進捗が遅くなりますから、クルーにとってデメリットになるかなって思いました。それに加えて生き残りが半数以下になっても逆覚醒すれば良いのかなって思いました。

個人的にタスクをしないという選択肢をMOD側で追加するのは良くないかなって思います、覚醒したあとアドミンとかに張り付いていいですよって理由を与えるわけですから
あとは人数による覚醒も”使わないと損になってしまう”って印象が大きくなりそうだと感じています(人が何人死んだかがわかるのは会議が始まらないとわからない以上脅迫的に使わないとと思うと思います)

**Comment by akirayasushi** [comment]
> タスク進捗が3割終わった所で覚醒し、6割終わると逆覚醒する形でしょうか。そうするとネゴシエイターのタスク進捗が必然的に遅れるのでクルー全体の進捗が遅くなりますから、クルーにとってデメリットになるかなって思いました。それに加えて生き残りが半数以下になっても逆覚醒すれば良いのかなって思いました。
> 
> 個人的にタスクをしないという選択肢をMOD側で追加するのは良くないかなって思います、覚醒したあとアドミンとかに張り付いていいですよって理由を与えるわけですから
> あとは人数による覚醒も”使わないと損になってしまう”って印象が大きくなりそうだと感じています(人が何人死んだかがわかるのは会議が始まらないとわからない以上脅迫的に使わないとと思うと思います)
> 

ご指摘ありがとうございます。
確か覚醒する方の条件はともかくとして、素クルーに戻る逆覚醒はタスク進捗にせよ人数減少にせよ明確な条件があるだけで『能力使わなきゃ』って思ってしまいますね。
それとタスクをしない選択肢を与えてしまう逆覚醒条件のひとつとして案に上げていたタスク進捗は無くして別の条件を考える必要がありますね…
人数による条件も同様に使わないと損っていう心理が働くのもその通りだと思います。ですのでそれ以外で考えたものを挙げてみますと、
・自身のタスク進捗での逆覚醒は無くす
・全体のタスク進捗が6割（ただこれもタスクバーが見ないorリアルタイム反映でない設定の場合は人数条件の時と大して変わらない気がします）
・覚醒後、3会議行われるまで（これも同じ結末になりそうですね…）
・覚醒後、誰か1人が追放されるまで（盤面次第では同上）
・覚醒後、3キル起きるまで（同上）

色々考えてみましたが、素クルーに戻る条件が明確な場合と不明確な場合いずれにおいても、前者の場合は条件達する前に使わないと損となりますし、後者においてはいつ使えなくなるか分からないから、使わなきゃってなりますので難しいですね。

私の固い頭ではこれ以上アイデアが出て来ませんでした。
この度は私ごときの為に貴重な時間を使ってお付き合いいただきありがとうございました。
これからも応援しています。

哲泰

**Comment by yukieiji** [comment]
> 確か覚醒する方の条件はともかくとして、素クルーに戻る逆覚醒はタスク進捗にせよ人数減少にせよ明確な条件があるだけで『能力使わなきゃ』って思ってしまいますね。
それとタスクをしない選択肢を与えてしまう逆覚醒条件のひとつとして案に上げていたタスク進捗は無くして別の条件を考える必要がありますね…

明確な条件というより、恐らくですがプレイヤー自身がコントロールできない要因によって能力が奪われると脅迫感が出るのだと思われます
ユーザーが完璧にコントロールできるという点では恐らくタスクによる逆覚醒が一番だとは思います

それでも能力がなくなるって考えると逆覚醒自体をなくして能力発動のコストを上げるのも手段ではあります
もしくは能力発動自体に大きなデメリットをつけるってのもありだと思います

**Comment by akirayasushi** [comment]
> 明確な条件というより、恐らくですがプレイヤー自身がコントロールできない要因によって能力が奪われると脅迫感が出るのだと思われます
> ユーザーが完璧にコントロールできるという点では恐らくタスクによる逆覚醒が一番だとは思います
> 
> それでも能力がなくなるって考えると逆覚醒自体をなくして能力発動のコストを上げるのも手段ではあります
> もしくは能力発動自体に大きなデメリットをつけるってのもありだと思います
> 

ありがとうございます。
中々良いアイデアが浮かびませんが、もっと時間をかけて考えてみて、妙案があればまた相談してみたいと思います。
ご連絡ありがとうございました！
