### ISSUE TITLE
名前未定(犬猿の仲なコンビ役職):第三陣営

### ISSUE THREAD

**Issue by Nushigami** [yukieiji/ExtremeRoles#31]
### 役職名 / Role Name
名前未定(コンビ役職)

### 役職の色 / Role color
※名前決めたあとに決めたいです。

### 役職の説明 / Role description
- 犬猿の仲な第三陣営
  - ２人がアサインする。※１
  - 他のこの役職の人がわかりません。※２
  - 1度だけキル可能。※３
  - 視界はクルーと同じ。※４
  - 勝利条件
→他のこの役職が死亡+生存で他の陣営の勝利に乗れる。
(この役職が2人以上生存している場合、敗北する。)

※１ 設定で２人以上アサインできるよう変更可
※２ 設定でわかるように変更可
※３ 設定でキルができるかと回数を変更可
※４ 設定で別の視界を得るかを変更可

### 他陣営への影響 / Effect on other teams
この役職は他のこの役職が死亡かつ生存していたら勝てるためインポスターやジャッカルがPPできるようになる。

### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
最初に片方を落としてしまえば勝利が確定するつまらない役職だと思いますがどうでしょうか

**Comment by Nushigami** [comment]
生存してないといけませんし、最初に片方落とさないといけないといってももう片方がわからないからそう簡単に落ちないと思うのですが

**Comment by yukieiji** [comment]
> 生存してないといけませんし、最初に片方落とさないといけないといってももう片方がわからないからそう簡単に落ちないと思うのですが

会議でCOして終わりだと思うのですがどうでしょうか

どちらにせよニュートラルなのにクルーとインポスター両方に害がないです

**Comment by Nushigami** [comment]
> 会議でCOして終わりだと思うのですがどうでしょうか

COした場合、他のこの役職の人にバレるリスクがあるため、あまりCOすべきではないと思いますが
(インポスター陣営とPPも可能なので、COした場合吊られる可能性もありますし)

> どちらにせよニュートラルなのにクルーとインポスター両方に害がないです

クルー陣営に対してはインポスター陣営とともにPP盤面を作れることですかね。
インポスター陣営に対しては、この役職はキルが１回できるため、護身で殺されるリスクがあるくらい?

**Comment by yukieiji** [comment]
> COした場合、他のこの役職の人にバレるリスクがあるため、あまりCOすべきではないと思いますが
(インポスター陣営とPPも可能なので、COした場合吊られる可能性もありますし)

同じ役職なので同じ勝利になるのではないでしょうか？
もしそうでなければ[現プログラムの実装](https://github.com/yukieiji/ExtremeRoles/blob/b81505b2ebbb18761d5466f3cedf109a12e939e7/ExtremeRoles/Patches/AmongUsClientPatch.cs#L106-L146)上不可能です

> クルー陣営に対してはインポスター陣営とともにPP盤面を作れることですかね。
インポスター陣営に対しては、この役職はキルが１回できるため、護身で殺されるリスクがあるくらい?

基本クルー有利なゲームでインポスターに味方するメリットは有るのかを聞きたいです

**Comment by Nushigami** [comment]
同じ役職なので同じ勝利になるのではないでしょうか？
もしそうでなければ[現プログラムの実装](https://github.com/yukieiji/ExtremeRoles/blob/b81505b2ebbb18761d5466f3cedf109a12e939e7/ExtremeRoles/Patches/AmongUsClientPatch.cs#L106-L146)上不可能です

**Comment by Nushigami** [comment]
> 同じ役職なので同じ勝利になるのではないでしょうか？
もしそうでなければ[現プログラムの実装]上不可能です。

残った人のみが勝利できます(言葉足らずでしたね)
同じ役職で無理なら別々の役職にすればいいと思います
(その場合1組３人以上でアサインできませんが)

> 基本クルー有利なゲームでインポスターに味方するメリットは有るのかを聞きたいです

最初から味方するわけでもありませんし、自身が生存している状態でPP盤面になる可能性も全然あります。

**Comment by yukieiji** [comment]
> 残った人のみが勝利できます(言葉足らずでしたね)

残った人だけ判定するコードは現実装ではありません(コード書いて拡張してくれるなら話は違いますが)
ラバーズ見たくフレキシブルな役職アサインだと役職のIDとゲーム内部管理ID両方が同じになるので判定は不可能になります

> 同じ役職で無理なら別々の役職にすればいいと思います
(その場合1組３人以上でアサインできませんが)

重複した同じコードが増えると可読性が下がりバグの原因になるので実装したくないです(役職のIDと勝利IDだけが異なるだけのほぼ同じ役職の実装なので重複したコードが増えるのは目に見えてわかります、また、一つの役職の実装をするだけなのに2つもIDを消費するのも嫌です)

> 最初から味方するわけでもありませんし、自身が生存している状態でPP盤面になる可能性も全然あります。

最初からクルーを味方をしていればインポスターにしか害がないのでは？最初からクルーを味方して裏切れば殺されるのは確定ですし、最初はクルーの方が有利な状態でインポスターの味方をするメリットは有るのでしょうか

**Comment by Nushigami** [comment]
> 最初からクルーを味方をしていればインポスターにしか害がないのでは？最初からクルーを味方して裏切れば殺されるのは確定ですし、最初はクルーの方が有利な状態でインポスターの味方をするメリットは有るのでしょうか

別に最初から味方するとは言ってないです
ただPP盤面になった時は、PPした方が確実だと思うのですが

>重複した同じコードが増えると可読性が下がりバグの原因になるので実装したくないです(役職のIDと勝利IDだけが異なるだけのほぼ同じ役職の実装なので重複したコードが増えるのは目に見えてわかります、また、一つの役職の実装をするだけなのに2つもIDを消費するのも嫌です)

製作者が嫌なら考えるだけで無駄ですかね
(コードは自分詳しくないので拡張は無理です。) 
このIssuesはクローズしますね

**Comment by Nushigami** [comment]
(一応２つの能力を別々で考えてもいいが自分じゃ能力の強さを均等にできないと思ったので)
