### ISSUE TITLE
ローカルゲームでダミープレイヤーがいるとSubmergedマップのゲームを開始できない

### ISSUE THREAD

**Issue by aoirint** [yukieiji/ExtremeRoles#310]
### 期待される動作 / Your Expectation

Extreme Rolesに加えて、Extreme Roles MODマネージャーを使って、Submerged v2023.8.2を導入した状態です。

SubmergedマップでExtreme Rolesの役職を試すため、ローカルゲームでダミープレイヤーを使って、
Submergedマップのゲームを開始しようとしました。

### 実際の動作 / The Reality

「一部のプレイヤーがSubmergedを導入していないためゲームが開始できません」というメッセージが表示され、ゲーム開始に十分な人数がいても開始ボタンが有効化されません。

以下のスクリーンショット内の「未導入者」には、すべてのダミープレイヤーが列挙されています。

![screenshot_xion_dummy_and_submerged](https://github.com/yukieiji/ExtremeRoles/assets/27213639/e3a50415-bc2b-4042-92f7-588dfb985d6b)

なお、以下のスクリーンショットのように、Submergedを導入した状態でも、マップをSubmerged以外に変更するとローカルゲームを開始できるようになります。

![screenshot_xion_dummy_and_not_submerged](https://github.com/yukieiji/ExtremeRoles/assets/27213639/c2d58ab5-378f-465d-901d-328975a22e21)

### あなたの意見 / Your Proposal

ダミープレイヤーを使って、Submergedマップでローカルゲームを開始できるようにしてほしいです。

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2023-08-14T14-24-18.zip](https://github.com/yukieiji/ExtremeRoles/files/12331764/ExtremeRolesDumpedLogs.2023-08-14T14-24-18.zip)

### Among Usバージョン/ Among Us Version

Among Us v2023.7.12s

### Modバージョン / Mod Version

Extreme Roles v8.2.0.5

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [ ] ExR専用(東京)

### プレイヤー人数/Player Num

4

### 使用したオプション/Use Option

[option.csv](https://github.com/yukieiji/ExtremeRoles/files/12331768/option.csv)

**Comment by yukieiji** [comment]
これはかなり前から(昨年の6月時点)あるやつですね
サブマ側が多分ダミープレイヤーですらサブマ導入チェックをやっているってやつですね
ちょっと本家に問い合わせてみます

**Comment by yukieiji** [comment]
一応上のサブマ側の返信によるととりあえず対応策を模索してみるとのことですが急ぎで対応してほしい感じですかね？

**Comment by yukieiji** [comment]
サブマージド側で修正されたのとその対応自体がv9.0.0.2で対応できたのでクローズ
