### ISSUE TITLE
Submergedにおいてテレポート系の役職の能力でプレイヤーを階層移動させると想定外の場所に移動する

### ISSUE THREAD

**Issue by aoirint** [yukieiji/ExtremeRoles#311]
## 開発者追記：影響を受ける役職
   - デリュージョナー
     - 回避不能のため使用しないことを推奨
   - リザレクター
      - 不具合が発生しても壁抜けが発生しないため無害
   - テレポーター
     - 階層移動させない「ポータル」を設置することで回避可能
   - ゾンビ
      - 不具合が発生しても壁抜けが発生しないため無害
   - マジシャン
     - 回避不能のため使用しないことを推奨

### 期待される動作 / Your Expectation

Extreme Rolesに加えて、Extreme Roles MODマネージャーを使って、Submerged v2023.8.2を導入した状態です。

Submergedマップでデリュージョナーのボタン能力「被害を逸らす」を使って、
アッパーセントラルにいるプレイヤーを、ロワーのろ過室付近にいる他のプレイヤーの位置にテレポートさせようとしました。

### 実際の動作 / The Reality

能力は発動し、対象のプレイヤーはテレポートしましたが、ロワーのろ過室付近ではなく、アッパーの診察室付近の壁の中にテレポートしました。

再現動画: https://www.youtube.com/watch?v=92gDIjdoE5w
問題のテレポートの箇所: https://youtu.be/92gDIjdoE5w?t=35

### あなたの意見 / Your Proposal

今回の場合、対象のプレイヤーの階層をロワーに移動させた上で、ロワーのろ過室付近にテレポートさせるようにしてほしいです。

### バグ発生時のログやエラー / log when issue occur

ホスト: [ExtremeRolesDumpedLog 2023-08-14T15-35-04.log](https://github.com/yukieiji/ExtremeRoles/files/12332038/ExtremeRolesDumpedLog.2023-08-14T15-35-04.log)（Reactorログのカスタムサーバーアドレスをマスク加工）

### Among Usバージョン/ Among Us Version

Among Us v2023.7.12s

### Modバージョン / Mod Version

Extreme Roles v8.2.0.5

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [X] カスタム/Custom
- [ ] ExR専用(東京)

### プレイヤー人数/Player Num

4

### 使用したオプション/Use Option

[option.csv](https://github.com/yukieiji/ExtremeRoles/files/12331940/option.csv)

**Comment by yukieiji** [comment]
これちょっと確認なんですが、ダンプするときにカスタムサーバーのIPはリプレイスされるように作ってたはずなんですがリプレイスされてなかったですかね

この不具合本体は多分階層がズレてるときに発生する不具合ですね、多分テレポートする系の役職すべてがこれに値しそうな気がします

**Comment by aoirint** [comment]
> リプレイスされてなかったですか

リプレイスされていなかったです。以下のようなログがF8キーで出力されたzipファイル内の、BackupLogsではないログに含まれていました。

```
[Info   :   Reactor] Joining {ImpostorのIPアドレス}:{ImpostorのUDPポート番号}
[Warning:   Reactor] Connected to a vanilla HTTP matchmaking server
[Info   :   Reactor] Currently using dtls: False. Should use dtls: False
[Warning:   Reactor] Server is not modded, falling back to HAAS
[Info   :   Reactor] Joining {ImpostorのIPアドレス}:{ImpostorのUDPポート番号}
[Warning:   Reactor] Connected to a vanilla HTTP matchmaking server
[Info   :   Reactor] Currently using dtls: False. Should use dtls: False
[Warning:   Reactor] Server is not modded, falling back to HAAS
```

カスタムサーバーの設定値はこんな感じです。

カスタムサーバーのIP: `https://example.com`
カスタムサーバーのポート: `443`

HTTPマッチングサーバ（Impostor.Http）を介していること、IPアドレスではなくホスト名を入力していること、スキームを含めていること、が怪しくはあるかもですが、HTTPマッチングサーバのアドレスはログ出力されていなさそうなので、UDPサーバのIPアドレス、ポート番号を置き換えられるようになっていればよさそうです。

**Comment by yukieiji** [comment]
> HTTPマッチングサーバ（Impostor.Http）を介していること、IPアドレスではなくホスト名を入力していること、スキームを含めていること、が怪しくはあるかもですが、HTTPマッチングサーバのアドレスはログ出力されていなさそうなので、UDPサーバのIPアドレス、ポート番号を置き換えられるようになっていればよさそうに思いました。

うーん、ログ出力時にログの文字列全検査して置き換えてたはずなのですが・・・(https://github.com/yukieiji/ExtremeRoles/blob/1308c20b9ab0e9e7923d88acfa0495f3a9b45123/ExtremeRoles/Helper/Logging.cs#L130 - L144)
こちらもちょっと調査します

不具合についてなのですが、アッパーからロワーではなくロワーからアッパーでもこの不具合は発生しましたか？
サブマのコードを見る限り普通に動きそうではありますが

**Comment by aoirint** [comment]
検証してみましたが、ロワーからアッパーでもこの不具合は発生しました。

「被害を逸らす」でテレポートさせられたプレイヤー

![image](https://github.com/yukieiji/ExtremeRoles/assets/27213639/af0e16c4-cc26-4487-90cc-6ce973370254)

テレポート先のプレイヤー

![image](https://github.com/yukieiji/ExtremeRoles/assets/27213639/1c21c48a-4eac-404d-9302-bb1696c201f6)

**Comment by aoirint** [comment]
補足で、関連しそうな役職と能力をいくつか検証してみました。

|役職と能力|発生する?|状況|
|:--|:--|:--|
|マジシャンのジャグリング|Yes|階層をまたぐテレポートでは、階層を移動しない（デリュージョナーと同様）|
|メリーの陣|No|階層をまたぐ陣でも、階層を移動する|
|テレポーターのポータル|Yes|階層をまたぐポータルでは、階層を移動しない（デリュージョナーと同様）|

**Comment by yukieiji** [comment]
v9.0.2.0で修正済み、他人から見た時の挙動が一瞬おかしくなる不具合があるがそれはサブマ側の問題のためクローズ
