### ISSUE TITLE
アリスの勝利条件に不具合

### ISSUE THREAD

**Issue by tukihatu** [yukieiji/ExtremeRoles#316]
### 期待される動作 / Your Expectation

インポスター生存1、アリス生存2、クルー生存1の状況で、試合が継続すること。
条件：
同じロールの第三陣営の勝利を同じにする オン
第三陣営の特殊勝利による強制勝利を無効化する オン

### 実際の動作 / The Reality

インポスター生存1、アリス生存2、クルー生存1の状況で、アリス勝利で試合が終了した。
画像とログを確認してください。
![2023-09-03_22h29_09](https://github.com/yukieiji/ExtremeRoles/assets/18047281/c76f2623-8da2-4a11-973c-9ba2b5a52ce8)

### あなたの意見 / Your Proposal

キル持ち陣営が2陣営以上いる場合、試合が継続するように修正してほしい

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2023-09-03T22-31-18.zip](https://github.com/yukieiji/ExtremeRoles/files/12506328/ExtremeRolesDumpedLogs.2023-09-03T22-31-18.zip)

### Among Usバージョン/ Among Us Version

Among Us v2023.7.12e(3365)

### Modバージョン / Mod Version

Extreme Roles v8.2.2.0

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [X] ExR専用(東京)

### プレイヤー人数/Player Num

10

### 使用したオプション/Use Option

[option.csv](https://github.com/yukieiji/ExtremeRoles/files/12506330/option.csv)

**Comment by yukieiji** [comment]
これはバグではなく実装当時から意図していた正常な挙動ですね
この状態だと**アリスが負けることが絶対にないため**アリス勝利で強制的に試合を終了させています

以前のなのそんでも同じことがあったと思います(動画をぱっと見つけれない)

**Comment by tukihatu** [comment]
了解しました。納得しましたのでクローズさせていただきます！
