### ISSUE TITLE
スレイヴドライバーの強化案

### ISSUE THREAD

**Issue by tukihatu** [yukieiji/ExtremeRoles#317]
### 追加する機能の詳細 / Feature details
#266 にてリワークしたスレイヴドライバーですが、やはり使用率が低いとおもいますので強化案を提示します。

### 現状の確認
役職のコンセプト：「"タスク"関連に特化させたインポスター」
ボタン能力「ハラスメント」により、クルーのタスク完了数を巻き戻すことが可能
現状のメリット：タスク完了を遅らせることでクルー勝利を妨害できる
現状のデメリット：状況次第でスレイヴドライバーが特定される可能性あり、タスクのない一部第三陣営に効果なし

### 現状の問題点と強化軸のコンセプト
問題点1.ボタン能力について、メリットに対して「スレイヴドライバーが特定される可能性」というデメリットが大きすぎると感じる。デメリットを減らしたい。
→スレイヴドライバーが特定される可能性を低くしたい。
問題点2.ボタン能力について、第三陣営の一部にはタスクが存在しないため、効果がないというデメリットがある。能力回数消費型としてはデメリットが大きすぎると感じる。デメリットを減らしたい。
→第三陣営にも効果のある新要素を加えたい。

### 上記問題点に対する強化案の提示
問題点1.スレイヴドライバーが特定される可能性を低くしたい
上記に対する具体的な強化案
「ハラスメント」を受けた人のタスク巻き戻りタイミング（能力発動タイミング）を変更する。
現在：能力使用後の次の会議
強化案：対象が一定のタスク進捗率に到達した後の会議
スレイヴドライバーの特定要因「行動を共にしていたことがある」の範囲時間を広げることで、容易な特定を防ぐ。
能力を使用した際に、対象が既に指定したタスク進捗率に到達している場合は、従来の仕様と同じになる想定。
→ゲーム後半でのタスク増加は強いメリットだと思うので、ゲーム後半での身バレのリスクは増加（仕様的には現状維持）させる。

強化案の問題点：バランスを崩壊させるほどの強化ではないと個人的には考えている。

オプション：「ハラスメント」を受けた人に、タスクの巻き戻りを発生させるタスク進捗率（名前長いので仮。長くても問題なければこのまま）
0%-100%で10%刻み。デフォルト50％。
能力を使用後、スレイヴドライバーが死亡した場合でも能力は継続される。
発動までマークは付与されたままとなる。マーク付与中の対象への重複能力使用不可。
タスクのない第三陣営へ使用した場合は、従来の仕様のまま。

問題点2.第三陣営にも効果のある新要素を加えたい。
上記に対する具体的な強化案
能力使用後、決められた会議数を消化しても規定のタスク量に到達しなかった人物に対して、限定のキルクールボーナスを付与。
リワーク前の能力である「タスクの遅い者に対しての特攻要素」を新設する形。
特攻状態になると、対象は「スロース（怠け者/sloth）」に変化。付与されているマークが変化。
変化したことはスレイヴドライバー以外にはわからない。スレイヴドライバーのみ次会議時のチャット欄で知る事が可能。
クルーにもタスクのない第三陣営にも効果がある想定。
「スロース」変化後に規定のタスク量に到達した場合、「スロース」状態は解除される。
→「スロース」状態が解除されないことによる、安易な第三陣営バレにつながる可能性があるので、オプションとして「スロース」のままになるか解除するか、ONOFF実装してもよいかもしれない。

強化案の問題点：
スレイヴドライバーに第三陣営がわかってしまう可能性がある。→タスクの遅いクルーにも同様の効果が表れるようにする＋オプションで調整してもらう
マーク変化形はユーザーにとってわかりにくいかもしれない。→変化時にチャットでお知らせするなどのフォローをする
バウンティとの差別化は？→タスクに関連した効果ではあるので、差別化は図れていると思われる

オプション：能力使用後、対象が「スロース」に変化する会議回数
1-5　デフォルト3
オプション：対象が「スロース」に変化しなくなるタスク進捗率
0%-100%で10%刻み。デフォルト50％。
→イメージ的には問題点1のオプションと同期させてもよい。独立していた方がカスタマイズ性は上がる想定
オプション：自身が「スロース」をキルした場合のキルクール減少率
0％-100％で10%刻み。デフォルト80％。

### 他陣営への影響 / Effect on other teams
・タスクのないクルー
→「スロース」に変化しやすくなるが、タスクがない＝怒る上司という形でキルボーナスが乗るのは、コンセプトから大きく外れていないと思われる。
・タスクマスター
→勝ちを妨害できてしまうが、それはそれでよいと思う（エージェンシーがタスクマスターの勝ちをアシストできる？のと同様）
・サーヴァント
→タスクが復活することで、タスク終了時のキルクール減少率が変化してしまうが、それはそれでよいと思う

### 強化による懸念点
能力が複雑な仕様に戻ってしまうので、結局わからないから使わないということになりそうではある

**Comment by yukieiji** [comment]
> 問題点1.ボタン能力について、メリットに対して「スレイヴドライバーが特定される可能性」というデメリットが大きすぎると感じる。デメリットを減らしたい。
→スレイヴドライバーが特定される可能性を低くしたい。

これはどちらかというと戦略的な部分が大きいのではないかなーって思います
リワークされたスレドラを使った試合を見る限り、キルと能力を別々のタイミングで使ってる印象を多く見受けてます

例えばこれが、キルする前に能力を使ってその人を霊界に送るとかなら1キル + タスク妨害となってかなり強力だと思ってますがどうなんでしょうか(霊界でタスクした分も会議でリセットされますし、タスクをしない選択をすればその分タスク勝利が遠のく)
つられそうになったら会う人会う人にボタンを使う + キルでかなりのタスク妨害が出来る気がします

>  問題点2.ボタン能力について、第三陣営の一部にはタスクが存在しないため、効果がないというデメリットがある。能力回数消費型としてはデメリットが大きすぎると感じる。デメリットを減らしたい。
→第三陣営にも効果のある新要素を加えたい。

それはそうですが、現状でも能力が第三陣営発見器能力としてかなり優秀な部類に入ってる気がします

> 問題点1.スレイヴドライバーが特定される可能性を低くしたい
上記に対する具体的な強化案
「ハラスメント」を受けた人のタスク巻き戻りタイミング（能力発動タイミング）を変更する。
現在：能力使用後の次の会議
強化案：対象が一定のタスク進捗率に到達した後の会議
スレイヴドライバーの特定要因「行動を共にしていたことがある」の範囲時間を広げることで、容易な特定を防ぐ。
能力を使用した際に、対象が既に指定したタスク進捗率に到達している場合は、従来の仕様と同じになる想定。
→ゲーム後半でのタスク増加は強いメリットだと思うので、ゲーム後半での身バレのリスクは増加（仕様的には現状維持）させる。
強化案の問題点：バランスを崩壊させるほどの強化ではないと個人的には考えている。

これを考えた時に一番問題になるのは複数人への重ねがけを容認するかどうかでしょうか
「重ねがけ」を容認した場合：タスク進捗が少ない人への集中攻撃が発生しそう => 試合を無駄に長引かせる要因になる
「重ねがけ」を容認しない場合：誰も使えない場面がある可能性がある

> 問題点2.第三陣営にも効果のある新要素を加えたい。
上記に対する具体的な強化案
能力使用後、決められた会議数を消化しても規定のタスク量に到達しなかった人物に対して、限定のキルクールボーナスを付与。
リワーク前の能力である「タスクの遅い者に対しての特攻要素」を新設する形。
特攻状態になると、対象は「スロース（怠け者/sloth）」に変化。付与されているマークが変化。
変化したことはスレイヴドライバー以外にはわからない。スレイヴドライバーのみ次会議時のチャット欄で知る事が可能。
クルーにもタスクのない第三陣営にも効果がある想定。
「スロース」変化後に規定のタスク量に到達した場合、「スロース」状態は解除される。
→「スロース」状態が解除されないことによる、安易な第三陣営バレにつながる可能性があるので、オプションとして「スロース」のままになるか解除するか、ONOFF実装してもよいかもしれない。
強化案の問題点：
スレイヴドライバーに第三陣営がわかってしまう可能性がある。→タスクの遅いクルーにも同様の効果が表れるようにする＋オプションで調整してもらう
マーク変化形はユーザーにとってわかりにくいかもしれない。→変化時にチャットでお知らせするなどのフォローをする

二重能力になって分かりにくそうかなーって思ってしまいました
個人的にはキルクール周りはもうお腹いっぱいって意見が出てたのでキルクールよりもっと別の感じに寄せたいですね・・・

> バウンティとの差別化は？→タスクに関連した効果ではあるので、差別化は図れていると思われる

以前もタスク周りの効果でしたけど図れてないという意見が出てましたね・・・・

シンプルに強くするのであれば能力のタスク巻き戻りをパーセンテージ化するくらいでしょうかね？100％まで実装して発動させれば全タスクリセット、後半になればなるほど強くなる

**Comment by tukihatu** [comment]
ありがとうございます。

> これはどちらかというと戦略的な部分が大きいのではないかなーって思います
> リワークされたスレドラを使った試合を見る限り、キルと能力を別々のタイミングで使ってる印象を多く見受けてます
> 例えばこれが、キルする前に能力を使ってその人を霊界に送るとかなら1キル + タスク妨害となってかなり強力だと思ってますがどうなんでしょうか(霊界でタスクした分も会議でリセットされますし、タスクをしない選択をすればその分タスク勝利が遠のく)

キルと能力を別々のタイミングで使ってる試合を私もよく見ていまして、
その場合にスレドラの疑惑がかかってしまい、キルにも妨害にも動きにくくなってしまっていました。
もう少し気軽に能力を使えたらいいのかなと思っています。

キル + タスク妨害が強力なのは同意見です。この使い方を運営として推し進めるのであれば、
極論、キルしたときに自動でタスク妨害効果が乗っかる形でもよいのかもしれません。
能力ボタンがあったほうが使うタイミングを選べる自由があるのでこのままでよいとは思いますが。

> > スレイヴドライバーの特定要因「行動を共にしていたことがある」の範囲時間

いろいろ書きだしてみて思ったのですが、オプションでハラスメントのクールタイムを0.5などにすれば、問題点1で上げた上記は解決できるような気がしてきました。

> これを考えた時に一番問題になるのは複数人への重ねがけを容認するかどうかでしょうか

「重ねがけ」は容認しない形を考えていました。書かれている通り、重複はいろいろ問題が大きいとおもいます。



> > 問題点2.ボタン能力について、第三陣営の一部にはタスクが存在しないため、効果がないというデメリットがある。能力回数消費型としてはデメリットが大きすぎると感じる。デメリットを減らしたい。
> > →第三陣営にも効果のある新要素を加えたい。
> 
> それはそうですが、現状でも能力が第三陣営発見器能力としてかなり優秀な部類に入ってる気がします

こちらは第三陣営に能力を使用すると、タスクが減ったことに気が付かないから、スレドラに第三陣営バレしてしまうという意味でとらえて大丈夫でしょうか。
確かにおっしゃる通りだと思いました。エージェンシーと違って音などがなりませんからね・・・
現状第三陣営にも効果を及ぼしているのであれば、問題点2はスルーしてよさそうです。
キルクール短縮以外の効果が思いつかないというのもあります。
できるとしたら、移動速度低下とか視界低下とかでしょうか。


> シンプルに強くするのであれば能力のタスク巻き戻りを最低保証を付けた上でパーセンテージ化するくらいでしょうかね？100％まで実装して発動させれば全タスクリセット出来るようになったり、確率になることで後半になればなるほど強くなる

今の「ハラスメント」で巻き戻るタスク数　を数値ではなく割合にするということでしょうか。
確かに強力ですね。後半になると能力が凶悪になるのも面白いです。
巻き戻るタスク数を10％-100％あたりで選べるようにすれば、強さの調整も簡単そうです。
ただ私的には、スレドラの能力自体は「発動すれば強力」であると考えているので、
これ以上のメリット強化は過剰である気はします。
この程度ならそれほど影響ないですかね・・・


一旦、問題点1はオプション設定でどうにかなるかもしれない。問題点2は解決している。
という形で、次の何試合かで試してみようかと思います。
その後、やはり使いづらいということになったら、上記でだして頂いた割合への変更か、
試合で出てきた問題点の改良かを提案させてもらえればと思います。

ここまで読んでいただけたらクローズで問題ないです。
（これってクローズした後も再オープンで議論続けられるんでしたっけ？）

**Comment by yukieiji** [comment]
> キルと能力を別々のタイミングで使ってる試合を私もよく見ていまして、
その場合にスレドラの疑惑がかかってしまい、キルにも妨害にも動きにくくなってしまっていました。
もう少し気軽に能力を使えたらいいのかなと思っています。

気軽に使えないっていう部分はそうですね

> キル + タスク妨害が強力なのは同意見です。この使い方を運営として推し進めるのであれば、
極論、キルしたときに自動でタスク妨害効果が乗っかる形でもよいのかもしれません。
能力ボタンがあったほうが使うタイミングを選べる自由があるのでこのままでよいとは思いますが。

僕個人的にはこの使い方が強いよってだけで推し進めるって訳では無いですね（あくまで使い方の一つの例として上げてる感じです）
但し、能力の使い方が限定的すぎる狭すぎるという見方もあるとは思いますなので、能力的な使い道を増やすようにしてもいいとは思います

キルに乗るようになるとよくわからない役職ってなりそうな気がしますね

> いろいろ書きだしてみて思ったのですが、オプションでハラスメントのクールタイムを0.5などにすれば、問題点1で上げた上記は解決できるような気がしてきました。

逆に考えると現在のデフォルト秒数でバランスを取れてないってことですよね・・・

> こちらは第三陣営に能力を使用すると、タスクが減ったことに気が付かないから、スレドラに第三陣営バレしてしまうという意味でとらえて大丈夫でしょうか。

そうですね、会議発生時に巻き戻りが発生するので会議開始前5秒前等に能力を使わないと確実とは言い切れないですが
クルーより第3陣営が多いようなルールだと優秀な気がします

> キルクール短縮以外の効果が思いつかないというのもあります。
できるとしたら、移動速度低下とか視界低下とかでしょうか。

ドアを適当に閉めるとかどっかに飛ばすとか、使用ボタンが押せなくなるとか色々とあるとは思います
以外に出来ないと思ってたことも出来るとは思います

> 今の「ハラスメント」で巻き戻るタスク数　を数値ではなく割合にするということでしょうか。
確かに強力ですね。後半になると能力が凶悪になるのも面白いです。
巻き戻るタスク数を10％-100％あたりで選べるようにすれば、強さの調整も簡単そうです。
ただ私的には、スレドラの能力自体は「発動すれば強力」であると考えているので、
これ以上のメリット強化は過剰である気はします。
この程度ならそれほど影響ないですかね・・・

今のオプションを「タスクの巻き戻りの最低保証数」としてリネームして、新オプションとして「タスクの巻戻り率」ってのを追加するって感じですね
挙動とすれば「タスクの巻戻り率」巻き戻せれなければ「タスクの巻き戻りの最低保証数」分必ず巻き戻るようにする、「タスクの巻き戻りの最低保証数」分巻戻せれなければ追加タスクとして生やさせるって感じですね(追加タスク発生はオプションでもいいとは思います)
巻き戻り率を小さくして「タスクの巻き戻りの最低保証数」を大きくすれば現状と同じように使える、逆に巻き戻り率を大きくすればより後半に強くダイレクトに動く役職として設定できる

> ここまで読んでいただけたらクローズで問題ないです。
（これってクローズした後も再オープンで議論続けられるんでしたっけ？）

リポジトリ管理者以外は再オープンできないのでこのまま置いておいて大丈夫です(30日間放置されると勝手にクローズされますが)
いくつか試していただいてそれでも問題がある調整した方がいいのであれば議論を続ける、必要なければクローズするでいいと思います
