### ISSUE TITLE
フェイカーのダミーをアドミンに反映されるようにする

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#318]
### 追加する機能の詳細 / Feature details
 - フェイカーのダミーでアドミンの情報を騙せるようにする
   - 例 : 以下だとアドミンに4人と表示される
      - メインホール:プレイヤー1人
      - ダミー(プレイヤー):2人
      - ダミー(死体):1人
   - インポスターが見る場合は正常、それ以外は騙される

### 機能を追加するメリット / Benefits of adding features
- 多少使い道が増える

**Comment by tukihatu** [comment]
フェイカーを改修するなら、ものすごく個人的な要望なんですが、
「ダミー(プレイヤー)」の発動条件、左の「Shiftキー」を、
左 または 右の「Shiftキー」に変更できますでしょうか。ALTとCtrlもできればお願いします。
←↑→で操作していると左のShiftキーを押すのがつらかったので…
wasdでも動かせるので、フェイカーをやるときは、そう切り替えればいい話なんですが。

他のショートカット機能と被ってしまうとか、実装時間かかるとか、実装する意味を見出せないとかなら
スルーしていただいて構わないです。ついでの要望意見なので。

**Comment by yukieiji** [comment]
> フェイカーを改修するなら、ものすごく個人的な要望なんですが、
「ダミー(プレイヤー)」の発動条件、左の「Shiftキー」を、
左 または 右の「Shiftキー」に変更できますでしょうか。ALTとCtrlもできればお願いします。
←↑→で操作していると左のShiftキーを押すのがつらかったので…
wasdでも動かせるので、フェイカーをやるときは、そう切り替えればいい話なんですが。
他のショートカット機能と被ってしまうとか、実装時間かかるとか、実装する意味を見出せないとかなら
スルーしていただいて構わないです。ついでの要望意見なので。

これは別の改善(キーの左右区分をなくして欲しい)になりそうなんで別途チケット切ってもらってもいいですか(切らなくてもいいんですが)？

**Comment by yukieiji** [comment]
強化の改善と別の改善があるとどこが改善したのかが分かりにくかったので切ったほうがいいかなって感じでした
まぁ左右区別周りの調整は終わったのですが
