### ISSUE TITLE
ハンター(追跡者)&フォックス(化け狐)：第三陣営

### ISSUE THREAD

**Issue by ghost** [yukieiji/ExtremeRoles#32]
### 役職名 / Role Name
ハンター(追跡者)&フォックス(化け狐)
### 役職の色 / Role color
明るい紫系。
### 役職の説明 / Role description
ハンター「フォックスを探し出してぶち殺せ」
フォックス「とにかく隠れて生き延びよう」
### 役職の能力 / Role ability
第三陣営役職。

「ハンター」は誰でも殺せるキルボタンを持つ第三陣営。ただし、インポスターやジャッカル、ミッショナリーなどとは勝利条件が異なり、「フォックス」をキルする事で単独勝利する事ができる。逆を言えば、フォックスの生存を許せば何人殺そうと勝利できない。
「ハンター」側からは誰が「フォックス」なのかを知る事は出来ない他、「フォックス」が他陣営に殺害されたり吊られたりすると、自分も死んでしまう。そのため、「フォックス」らしい人間が議論で疑われた場合は庇って乗り切らせなければならない。

「フォックス」は、ボタンを押して一定時間透明化する事ができる第三陣営。ただし、透明化には使用回数制限があり、また透明化中は移動速度が著しく低下する。そのうえ透明化している最中でも「フォックス」のキル自体は可能(キルボタンが反応する)である。
タスクを全てこなした上で最後まで生き残るのが勝利条件であり、これを満たすと単独勝利する事ができる。
「ハンター」が「フォックス」を見分けられないように、「フォックス」からもまた、誰が「ハンター」なのかは分からない。
また、緊急サボタージュを直す事ができない為、直している人間に紛れ込むなどしなければ疑われるリスクがある。
タスクを全てこなした上で最後まで生き残るのが勝利条件であり、これを満たすと単独勝利する事ができる。

TOR GMの妖狐の改変版であり、「鬼ごっこ」「かくれんぼ」がモデルであり、動画投稿者のニコライ・ボルコフさんと戌宮！さんがモチーフ。
「よっしゃあああああ！！戌宮さん殺しますね！」
「えええええええええ！！」

### 他陣営への影響 / Effect on other teams
「ハンター」はどの陣営からしても、「フォックス」と誤解されて殺される危険性がある上に、勝利を共にできない存在でもある為、「ハンター」は他プレイヤー全員から排除対象となる。

また、「フォックス」は生かしておくと最終的に勝利を掠め取る存在なので、こちらもまた早急な排除対象となる。特に「フォックス」は、排除に成功すれば自動的に「ハンター」も死ぬので、皆殺しを目的とする陣営からは優先的に狙われることになる。

### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [X] :ニュートラル/Neutral

**Comment by issyoukimizu** [comment]
始めてセット役職を考えてみました。
ご意見お待ちしております。

**Comment by yukieiji** [comment]
> 「ハンター」は誰でも殺せるキルボタンを持つ第三陣営。ただし、インポスターやジャッカル、ミッショナリーなどとは勝利条件が異なり、「フォックス」をキルする事で単独勝利する事ができる。逆を言えば、フォックスの生存を許せば何人殺そうと勝利できない。

「フォックス」が先に死んたら何も出来ないつまらない役職に見えますがどうでしょうか？

> タスクを全てこなした上で最後まで生き残るのが勝利条件であり、これを満たすと単独勝利する事ができる。

最後までというのはどこまででしょうか？

**Comment by issyoukimizu** [comment]
>「フォックス」が先に死んたら何も出来ないつまらない役職に見えますがどうでしょうか？
「フォックス」が他陣営に殺害されたり吊られたりすると自分も死んでしまう、と上に書いています。
まあ、「フォックス」が死んだら勝利条件が変化するとかもいいかもしれませんが。

>最後までというのはどこまででしょうか？
生き残ったうえで何らかの陣営が勝利するとその勝利を横取りして勝てるという事です。

**Comment by yukieiji** [comment]
> 「フォックス」が他陣営に殺害されたり吊られたりすると自分も死んでしまう、と上に書いています。
まあ、「フォックス」が死んだら勝利条件が変化するとかもいいかもしれませんが。

どちらにせよ防げない要因で死なれて勝利条件を達成できないのはバランスやプレイしているプレイヤー的にどうなのかという疑問があります

**Comment by issyoukimizu** [comment]
>防げない要因で死なれて勝利条件を達成できないのは～

だからまあ、フォックスが外的要因で死んだらキルボタンが消えてクルー陣営で勝利できるようになる、とか、逆に自分以外皆殺しを目指す、とかはしてもいいとは思います。

あるいは
「フォックス」を殺した相手が「狐憑き」になって、自分以外皆殺しを目的にするようになる。
「狐憑き」を殺すとその人物も「狐憑き」になる。
↓
「ハンター」は「狐憑き」を殺すことで勝利する。

とかもアリかもしれません。

**Comment by yukieiji** [comment]
> だからまあ、フォックスが外的要因で死んだらキルボタンが消えてクルー陣営で勝利できるようになる、

インポスターに害がなくなりますが

> とか、逆に自分以外皆殺しを目指す、とかはしてもいいとは思います。

皆殺しが目標になる場合、適当に殺して狐に当たったら勝利するだけの役職になってしまいます

> 「フォックス」を殺した相手が「狐憑き」になって、自分以外皆殺しを目的にするようになる。
「狐憑き」を殺すとその人物も「狐憑き」になる。

「狐憑き」はどういう役職になるのですか？

**Comment by issyoukimizu** [comment]
>「狐憑き」はどういう役職になるのですか？

あの後色々考えた結果、かなり変わりました。

まず、「フォックス」が「ハンター」以外に殺された場合はその殺した相手が「狐憑き」となります。「フォックス」が吊られてしまった場合は、「ハンター」以外の誰かが一人ランダムで「狐憑き」になります。

「狐憑き」になったプレイヤーは呪われてしまい、何らかの陣営が勝つまで生き残っても勝つことができなくなってしまいます。その代わり、役職が無効化されると同時にキルボタンが生えてきます。そして『ハンターが何らかの要因で死ぬ』か、『「ハンター」を抹殺する』ことで呪いを解く、つまり「狐憑き」の属性を完全に無くすことができます。

また、「ハンター」以外のプレイヤーが「狐憑き」を殺すと、殺した相手に「狐憑き」の属性が移行し、殺された側からは「狐憑き」の属性がなくなります。吊られた場合はまた「ハンター」以外の別のプレイヤーにランダムで移行します。


この場合、「ハンター」の勝利条件を『「フォックス」か「狐憑き」を殺した後、死ぬか会議で吊られないこと』にしたうえで、「ハンター」は「狐憑き」の位置が分かるようにしてもいいかもしれません。

**Comment by yukieiji** [comment]
> まず、「フォックス」が「ハンター」以外に殺された場合はその殺した相手が「狐憑き」となります。「フォックス」が吊られてしまった場合は、「ハンター」以外の誰かが一人ランダムで「狐憑き」になります。
「狐憑き」になったプレイヤーは呪われてしまい、自陣営が勝っても勝つことができなくなってしまいます。その代わり、役職の能力が無効化されると同時にキルボタンが生えてきます。そして『ハンターが何らかの要因で死ぬ』か、『「ハンター」を抹殺する』ことで呪いを解く、つまり「狐憑き」の属性を完全に無くすことができます(ただし、呪いが解けたかどうかは会議を挟まないとわからない)。
また、「ハンター」以外のプレイヤーが「狐憑き」を殺すと、殺した相手に「狐憑き」の属性が移行し、殺された側からは「狐憑き」の属性がなくなります。吊られた場合はまた「ハンター」以外の別のプレイヤーにランダムで移行します。

役職が奪われるのが後半になればなるほど元の陣営を取り戻すメリットが無くなってる気がします(なんなら、キルボタンが生えてきてる時点で完全に敵対してます、その状態で「ハンター切りましたー」って言えないので序盤でも元の陣営に戻るメリットが無い気がします)
そうなってしまうと無限サイドキックループと同じような形(それの上位互換)になってしまうので強すぎる気がします

> この場合、「ハンター」の勝利条件を『「フォックス」か「狐憑き」を殺した後、死ぬか会議で吊られないこと』にしたうえで、「ハンター」は「狐憑き」の位置が分かるようにしてもいいかもしれません。

「狐憑き」の位置を分かるようにするのはバランス的にどうなのでしょうか

**Comment by issyoukimizu** [comment]
>役職が奪われるのが後半になればなるほど元の陣営を取り戻すメリットが無くなってる気がします(なんなら、キルボタンが生えてきてる時点で完全に敵対してます、その状態で「ハンター切りましたー」って言えないので序盤でも元の陣営に戻るメリットが無い気がします)
そうなってしまうと無限サイドキックループと同じような形(それの上位互換)になってしまうので強すぎる気がします

いえ、「狐憑き」は『ハンターを殺す事で元陣営に戻る選択肢もある』のではなく、『ハンターが死なない限り絶対勝てなくなってしまうから、何が何でもハンターを殺して元の陣営に戻らざるを得ない』というのが正確です。そういう意味ではTORの「チェインシフター」にも少し似ているかもしれません。

**Comment by yukieiji** [comment]
> いえ、「狐憑き」は『ハンターを殺す事で元陣営に戻る選択肢もある』のではなく、『ハンターが死なない限り絶対勝てなくなってしまうから、何が何でもハンターを殺して元の陣営に戻らざるを得ない』というのが正確です。そういう意味ではTORの「チェインシフター」にも少し似ているかもしれません。

「ハンター」は適当に殺していっても勝利条件を満たせるのに「狐憑き」自体が勝利条件を持たないのであれば完全に「ハンター」に勝利条件を満たさせないためだけに用意された増殖する役職にしか見えないのですがそれいいのでしょうか？(チェインシフターと同じくニュートラルとしての他陣営に影響を与えるという部分が強すぎる気がします)

また、クルー側が「狐憑き」になった場合、ほぼ死亡していることが確定してしまいます(「ハンター」を切って元の陣営に戻ったとしても元の陣営に戻ったという証拠はない上にキルをしたという証拠があるのでグレー位置から外れることはない、そう考えると高い確率で吊られてしまいます。= クルーを「狐憑き」にする or なるとそのクルーは生き残れないことを覚悟しなければならないと思います)

**Comment by yukieiji** [comment]
ユーザーが削除されたためチケットをクローズします
