### ISSUE TITLE
クルーコンビネーション役職：探偵、助手、見習い探偵(名前未定)

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#33]
### 役職名 / Role Name
- 探偵、助手、見習い探偵

### 役職の色 / Role color
- 未定

### 役職の説明 / Role description
- Readmeに記載されている役職です
- クルーオンリーのコンビネーション役職
- 「助手」は「探偵」のアシストを行い、「探偵」は「助手」がいれば能力をフルに活用しやすい

### 役職の能力 / Role ability
- 助手
  - 自分が通報した死体の完全なキル時間が分かる
  - 探偵が居ないと無力に近くなる

- 探偵
  - 通報された死体の場所に一定時間とどまる事で様々な情報を手に入れることができる
  - 情報は完全な死亡時刻(1回目)、通報までの時間(2回目)、殺した陣営(3回目)、役職(4回目)
  - 助手が通報した死体だと上記の時間が短くなる、それ以外のクルーだと2回目を得ることが難しい時間に調整する

- 見習い探偵
  - 「探偵」がキルもしくは追放されれば「助手」が「見習い探偵」に、「助手」がキルもしくは追放されれば「探偵」が「見習い探偵」になる
  - 死体を通報することで完全な死亡時刻が分かる
  - 能力ボタン
    - いつでも緊急会議ボタン押すことが出来る(回数制限付き、自分の押したボタンの数も影響する)

### 他陣営への影響 / Effect on other teams

- 「探偵」は「助手」が通報していない死体だと基本的に能力をフルに使うことが出来ないので1試合で活躍するのはせいぜい1回、2回発動することは稀だと思われるため、全滅が目的の陣営にとって影響は少ないと思います(推理の材料が増えますが時間がかかるのでそこはイーブンと思ってます)
- 「探偵」の能力発動中は基本的に無防備に近いため絶好のキルチャンス
- インポスターは「助手」をキルすることで「探偵」を大幅に弱体化させること出来るので、クルー側からしたら「助手」をCOすることは難しいはず
- 逆に「探偵」がキルされれば「助手」が強化されるのでクルー側からしたら、1落ちでも一つのチャンスを作ることが出来る

### 陣営 / Team
- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by Nushigami** [comment]
完全な死亡時刻と通報までの時間は何が違うのでしょうか？
