### ISSUE TITLE
アドミンに死体が表示されない不具合の修正が動作していない

### ISSUE THREAD

**Issue by aoirint** [yukieiji/ExtremeRoles#333]
### 期待される動作 / Your Expectation

アドミンに表示される場所でインポスターがクルーメイトをキルして、アドミンを確認すると、死体とインポスターでクルーメイトのマークが2つ表示されるはずが、1つだけ表示されてしまう。

### 実際の動作 / The Reality

Airship、Skeldのアドミンで死体が表示されないことを確認しました。他マップ、スーパーバイザー能力によるアドミンは未確認です。

Airshipでの再現動画

https://github.com/yukieiji/ExtremeRoles/assets/27213639/5c62c1ab-01ca-42ff-8656-9bede4b61c9a

なお、フェイカーが設置したダミーの死体やダミーのプレイヤーは、アドミンに表示されました。

<details>
<summary>フェイカーのダミーのアドミン表示を確認した再現動画</summary>

https://github.com/yukieiji/ExtremeRoles/assets/27213639/9489858d-42b7-4387-900d-467cb2de88f4

</details>

### あなたの意見 / Your Proposal

不具合として修正する方針に変更がなければ、アドミンに死体が表示されるようにしてほしい。

アドミンに死体が表示されない不具合の修正は、[Extreme Roles v5.0.0.4](https://github.com/yukieiji/ExtremeRoles/releases/tag/v5.0.0.4)で実装されています。

### バグ発生時のログやエラー / log when issue occur

- [ExtremeRolesDumpedLogs 2023-12-02T02-02-16_AirshipAdmin.zip](https://github.com/yukieiji/ExtremeRoles/files/13530537/ExtremeRolesDumpedLogs.2023-12-02T02-02-16_AirshipAdmin.zip) （Airshipでの再現動画のログ）
- [ExtremeRolesDumpedLogs 2023-12-02T02-17-46_Skeld_Faker_Admin.zip](https://github.com/yukieiji/ExtremeRoles/files/13530653/ExtremeRolesDumpedLogs.2023-12-02T02-17-46_Skeld_Faker_Admin.zip)（フェイカーのダミーのアドミン表示を確認した再現動画のログ）

### Among Usバージョン/ Among Us Version

Among Us v2023.11.28s

### Modバージョン / Mod Version

Extreme Roles v9.1.0.0

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [ ] ExR専用(東京)
- [x] ローカル

### プレイヤー人数/Player Num

4

### 使用したオプション/Use Option

- [option_2023-12-02_AirshipAdmin.csv](https://github.com/yukieiji/ExtremeRoles/files/13530304/option_2023-12-02_AirshipAdmin.csv)（Airshipでの再現動画のoption.csv）
- [option_2023-12-02_SkeldFakerAdmin.csv](https://github.com/yukieiji/ExtremeRoles/files/13530657/option_2023-12-02_SkeldFakerAdmin.csv)（フェイカーのダミーのアドミン表示を確認した再現動画のoption.csv）

**Comment by yukieiji** [comment]
またどっかのアプデでアドミン周りが変わった時に発生した不具合だと思われます(修正は終わりました)
