### ISSUE TITLE
ムーバーのムーブ能力でタスクの位置を指す矢印が移動しない

### ISSUE THREAD

**Issue by aoirint** [yukieiji/ExtremeRoles#334]
### 期待される動作 / Your Expectation

タスク・緊急タスクの位置を指す矢印が表示された状態で、ムーバーがタスクの位置を移動させたとき、矢印がムーバーの位置またはタスクを設置した位置を指すことを期待したが、もとの位置を指し続けてしまった。

![image](https://github.com/yukieiji/ExtremeRoles/assets/27213639/660d62c4-a15e-4628-bdaf-55995f977562)

### 実際の動作 / The Reality

<details>
<summary>再現動画: Skeldの配線タスク</summary>

https://github.com/yukieiji/ExtremeRoles/assets/27213639/53896483-256e-4661-906a-9cfcbbe0cd27

</details>

<details>
<summary>再現動画: Polusの耐震安定装置の緊急タスク</summary>

https://github.com/yukieiji/ExtremeRoles/assets/27213639/ae98d1f9-ec53-4061-884c-97f7538c2648

</details>

### あなたの意見 / Your Proposal

矢印がムーブ能力によって移動された先のタスク・緊急タスクの場所を指すようにしてほしい。

### バグ発生時のログやエラー / log when issue occur

なし

### Among Usバージョン/ Among Us Version

Among Us v2023.11.28

### Modバージョン / Mod Version

Extreme Roles v9.1.0.0

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [ ] ExR専用(東京)
- [x] ローカル

### プレイヤー人数/Player Num

4

### 使用したオプション/Use Option

- [option_2023-12-01_Mover.csv](https://github.com/yukieiji/ExtremeRoles/files/13530826/option_2023-12-01_Mover.csv)

**Comment by yukieiji** [comment]
これはバグではなく仕様に近いんですよね・・・・
マップで確認すれば正しい位置に見えるはずですが

**Comment by aoirint** [comment]
なるほどです！　確かに、マップで確認すると正しい位置に表示されていました。

実現するのであれば機能要望になると思いますが、回避策がわかったことで、Issue作成者としては仕様として納得したので、こちらでいったんCloseします。

（通信サボタージュ中に完了したタスクの矢印が消えない公式不具合もありますし、矢印はそれほど重要ではないかなと思いました）

**Comment by yukieiji** [comment]
治そうと思えば治せるような気がしますがかなり面倒ですね
