### ISSUE TITLE
アドミンを正しく無効化することが出来ない(オプション及び時間制限両方共)

### ISSUE THREAD

**Issue by aoirint** [yukieiji/ExtremeRoles#335]
### 期待される動作 / Your Expectation

「アドミンを無効化する」オプションを「オン」に設定して、Skeldのアドミンを使用できないようにしようとした。

### 実際の動作 / The Reality

アドミンを使用できてしまい、各部屋のクルーメイトの数が表示されてしまった。

![945360_20231203205605_1](https://github.com/yukieiji/ExtremeRoles/assets/27213639/a7c73683-0ef3-4d70-aa96-d88f6515b406)

![945360_20231203205615_1](https://github.com/yukieiji/ExtremeRoles/assets/27213639/cffdba2b-165f-48e6-8ce5-c0e26b1a2636)

### あなたの意見 / Your Proposal

「アドミンを無効化する」オプションが「オン」に設定されているとき、アドミンを使用できないようにしてほしい。

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2023-12-03T21-05-26.zip](https://github.com/yukieiji/ExtremeRoles/files/13538843/ExtremeRolesDumpedLogs.2023-12-03T21-05-26.zip)

### Among Usバージョン/ Among Us Version

Among Us v2023.11.28s

### Modバージョン / Mod Version

Extreme Roles v9.1.0.1

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [ ] ExR専用(東京)
- [x] ローカル

### プレイヤー人数/Player Num

4

### 使用したオプション/Use Option

[option_2023-12-03_アドミン無効化.csv](https://github.com/yukieiji/ExtremeRoles/files/13538832/option_2023-12-03_.csv)

**Comment by yukieiji** [comment]
Skeldのみの不具合でした

**Comment by aoirint** [comment]
> Skeldのみの不具合でした

同様の設定（Among Us v2023.11.28s, Extreme Roles v9.1.0.1、ローカルゲームのシオン）で他マップについて検証したところ、MIRA HQ、Polus、Airshipでも不具合が発生しましたが、修正によって再現しなくなったのであれば問題ありません！（修正ありがとうございます！）

検証の詳細

- 「アドミンを無効化する」オプションが「オン」のとき、マップにアドミンがあるSkeld、MIRA HQ、Polus、Airshipのいずれでも、アドミンを使用でき、内容が表示されてしまった（不具合が発生）。
- 「アドミンを無効化する」オプションが「オフ」のとき、「Airshipの有効なアドミン」に「コックピットのみ有効」、「アーカイブのみ有効」のいずれを選択しても、どちらのアドミンも使用でき、内容が表示されてしまった（類似した不具合が発生）。

なお、Among Us v2023.7.12s,  Extreme Roles v8.2.6.2（同Among Usバージョン対応の最終版）時点の挙動は、「アドミンを無効化する」オプションが「オン」のとき、アドミンのある位置に近づいても使用ボタンが光らず、使用できないというものでした。

<details>
<summary>（スクリーンショット）Among Us v2023.7.12s,  Extreme Roles v8.2.6.2時点のアドミン無効化の挙動（使用ボタンが光らない）</summary>

![スクリーンショット 2023-12-04 020219](https://github.com/yukieiji/ExtremeRoles/assets/27213639/3c741062-fa1d-45d7-b62f-00ab4f579c90)

</details>

また参考までにAirshipでは、ローカルゲームのダミープレイヤーのスポーン位置がマップ左上の壁の中（アドミンに映らない）に変わったようです。
Among Us v2023.7.12s,  Extreme Roles v8.2.6.2では、昇降機左下の壁の中でした（アドミンでは昇降機の判定）。

<details>
<summary>（スクリーンショット）Among Us v2023.7.12s,  Extreme Roles v8.2.6.2時点のダミープレイヤーのスポーン位置（昇降機）</summary>

![スクリーンショット 2023-12-04 021608](https://github.com/yukieiji/ExtremeRoles/assets/27213639/6a12a9b2-b9f7-4f5c-873d-b32a2f33ac8b)

</details>

<details>
<summary>（スクリーンショット）Among Us v2023.11.28s, Extreme Roles v9.1.0.1時点のダミープレイヤーのスポーン位置（マップ左上）</summary>

![945360_20231203204226_1](https://github.com/yukieiji/ExtremeRoles/assets/27213639/9644c187-e182-4d10-8f84-2438bee9c6bb)

</details>

**Comment by aoirint** [comment]
> これファングルでも発生しますかね？

アドミンの無効化についてであれば、ファングルにはマップにアドミンが設置されていないので、不具合は発生しないと思います。「アドミンを無効化する」オプションは、マップに設置されたアドミンが対象で、役職の能力によるアドミンは対象でないという認識です。

ダミープレイヤーのスポーン位置についてであれば、ファングルではマップ左上にスポーンするという現象は発生しませんでした。通常プレイと同様、初期スポーン位置は焚火を囲む位置でした。なお、緊急会議を挟んだ後は通常プレイと異なり、ミーティングルームには配置されず、焚火を囲む位置に配置されていました。

<details>
<summary>（スクリーンショット）Fungleでのダミープレイヤーのスポーン位置（Among Us v2023.11.28s, Extreme Roles v9.1.0.1）</summary>

![image](https://github.com/yukieiji/ExtremeRoles/assets/27213639/b3c70620-ee03-466f-a3be-1d9526bcf21f)

</details>

**Comment by yukieiji** [comment]
ダミープレイヤーのスポーン位置は恐らくAmongUs本体の不具合ですね

アドミンのオプション周りの不具合は確認できました、どこかのアプデでアドミンの内部的な仕様変更を忘れてたのが原因ですね
