### ISSUE TITLE
Webチャット機能でチャットを送信できない

### ISSUE THREAD

**Issue by aoirint** [yukieiji/ExtremeRoles#337]
### 期待される動作 / Your Expectation

ローカルゲームのロビーでチャット画面を開いた状態で、ブラウザ（Google Chrome 119）からWebチャット（`http://localhost:57700/au/chat/ui/`）を開き、チャット送信ボタンを押してチャットを送信しようとした。

### 実際の動作 / The Reality

チャット送信ボタンを押してもチャットを送信できなかった。Web Socket API（`http://localhost:57700/au/chat/ui/ws/`）への接続が完了した際のメッセージ（「AmongUsとのソケット通信に成功しました」）も表示されていない。

![image](https://github.com/yukieiji/ExtremeRoles/assets/27213639/dd8b8265-2a9e-4361-94b9-e5b5115b924d)

### あなたの意見 / Your Proposal

チャットを送信できるようにしてほしい。

v9.1.0.1で追加された翻訳キーの`OverMaxLengthMessage`に対応する日本語訳に改行が含まれているため、置換処理の結果、JavaScriptの構文エラー（Uncaught SyntaxError）になり、（チャットの文字数に関わらず）ページ上でJavaScriptが実行されていなさそうです。

https://github.com/yukieiji/ExtremeRoles/blob/d4fd95743d12f1d77c5e2c1b8d654b7626dc14e8/ExtremeRoles/Module/ApiHandler/OpenChatWebUi.cs#L154-L156

https://github.com/yukieiji/ExtremeRoles/blob/d4fd95743d12f1d77c5e2c1b8d654b7626dc14e8/ExtremeRoles/Module/ApiHandler/OpenChatWebUi.cs#L238-L245

![image](https://github.com/yukieiji/ExtremeRoles/assets/27213639/1e31021a-7ef6-4b0d-b34f-570723cf2dba)

![image](https://github.com/yukieiji/ExtremeRoles/assets/27213639/b5fa3a44-1f21-44b1-8cc2-a330c9743cf4)

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2023-12-05T18-21-31.zip](https://github.com/yukieiji/ExtremeRoles/files/13557881/ExtremeRolesDumpedLogs.2023-12-05T18-21-31.zip)

### Among Usバージョン/ Among Us Version

Among Us v2023.11.28s

### Modバージョン / Mod Version

Extreme Roles v9.1.0.1

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [ ] ExR専用(東京)

### プレイヤー人数/Player Num

1

### 使用したオプション/Use Option

なし

Among Us本体の言語設定: 日本語

**Comment by yukieiji** [comment]
改行の不具合でした開発版で修正済み
