### ISSUE TITLE
新機能：パブリックベータモード

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#340]
### 追加する機能の詳細 / Feature details
 - 現状、新しい機能をちゃんとして追加するほどではないけど意見を求めたいという場合、実装を断念もしくはズルズル時間がかかるすることが多い
   - また、適当にテストしてやっぱりやめたということもユーザーが多いので出来ない
 
 - そこで「パブリックベータモード」というものを追加し、ユーザーの意見を求めつつ機能追加の実装速度を上げる
  - 「パブリックベータモード」
    - クライアントオプションに実装
      - 表示に影響する部分であれば各クライアントのみに影響
      - 役職やオプションに関しては基本的に非表示にオフの場合は非表示とし、ホストがオンの場合は全員が動作するようにする
    - ここに追加されるものは基本的にちゃんと作らない、適当に作って適当にテストする
    - リポジトリも別管理 => サブモジュールとして管理し必要な部分を読み込んで使う
    
- テスター等の違いとしては、**このモードで有効になるものは必ず実装されるとは限らない** => 完全な実験場として利用する
  - ユーザーフィードバックを得やすいように起動後にどんな機能があるかを表示する

### 機能を追加するメリット / Benefits of adding features
- 実装速度を上げる
- ユーザーフィードバックを得やすいようにする

**Comment by yuhgao** [comment]
翻訳を行う側としてはサイドキックやサーヴァント、ヴィジランテの各状態など特殊環境下のロール説明文も表示するようなデバッグ（クライアント）オプションがあればありがたいです。

**Comment by yukieiji** [comment]
> 翻訳を行う側としてはサイドキックやサーヴァント、ヴィジランテの各状態など特殊環境下のロール説明文も表示するようなデバッグ（クライアント）オプションがあればありがたいです。

ヴィジランテの状態はわかりますが、サイドキックとかサーヴァントの状態ってなんかありましったっけ？(翻訳キー変えてたかな？)

**Comment by yuhgao** [comment]
サイドキックやサーヴァントはロビーHキーでの表示がされないので、一度シオンでロールに切り替えなくてはならない状態であると認識しています。もし可能であればヴィジランテ含めてこれもロビーで見られるようになるとかなりありがたいのですが.......いかがでしょうか。

**Comment by yukieiji** [comment]
> サイドキックやサーヴァントはロビーHキーでの表示がされないので、一度シオンでロールに切り替えなくてはならない状態であると認識しています。もし可能であればヴィジランテ含めてこれもロビーで見られるようになるとかなりありがたいのですが.......いかがでしょうか。

あぁ確かにそうですね
サイドキックやサーヴァント、ヴィジランテもそうなんですけどアイツらのテキストをどこにどんなふうに表示するのか問題がありましてね・・・

**Comment by yuhgao** [comment]
デバッグオプションがオンのときのみ通常ロールと同じ枠に表示では難しいでしょうか？状態の切り替えを独自に追加するのはコストが高そうですし、、、

**Comment by yukieiji** [comment]
> デバッグオプションがオンのときのみ通常ロールと同じ枠に表示では難しいでしょうか？状態の切り替えを独自に追加するのはコストが高そうですし、、、

どっちにしろ状態の切り替えを実装する必要はあるはずですね、その役職独自の処理が必要になってくるので
