### ISSUE TITLE
システム予約語の追加・導入

### ISSUE THREAD

**Issue by yuhgao** [yukieiji/ExtremeRoles#341]
### 追加する機能の詳細 / Feature details
翻訳テキストファイルで使用可能な予約語を追加する。予約語は現在の {0} のように使用でき、予め書式タグも記入されている。
 - 各種ロール、陣営  例： `{impostor} = <b><color=red>インポスター</color></b> `
 - その他ロールイントロ、設定名等他で表示するもの　例：`{JackalIntroDescription} = <alpha=#CC><i>サイドキックを作り、この船を乗っ取れ</i><alpha=#FF>`
 - 各種ボタン機能 例：`{killbutton} = <b>キルボタン</b>`
 - 現在の陣営（ナイス、イビルなど陣営が別れたり、ヴィジランテなど切り替わる場合）
 - 説明等を区切る線 (`<b>―――――――――</b>`)
 - 自動で役職カラーを取得するタグ　例：`{color_impostor}インポスターだぞ</color> = <color=red>インポスターだぞ</color>`
 - ボタン能力名に自動で役職のカラーを付けて表示 例：`{liightOff} = <color=red><b>強制停電</b></color>`
    - 予約語in予約語が可能なら `{liightOff} = {color_impostor}<b>強制停電</b></color> = <color=red><b>強制停電</b></color>`
 - など

### 機能を追加するメリット / Benefits of adding features
書式タグを導入した記述を中心に可読性の向上と表示方法の統一、および作業の効率化が期待できる。
現状ではすべてのワードに対して手動でタグを挿入している関係で、一箇所を変えるとなるとすべてを虱潰しに変更したり、手記入だと一部書式がぶれたりしてしまう。
導入により作業量が三割程度減るものと思われる。翻訳においてもマスター部分を変更するだけで複雑な書式が簡単に流用できるようになる。

デメリット：翻訳ファイルを触る人がドキュメントを理解していないといけなくなる。（ yukieiji/ExtremeRoles.Beta#2  新書式の導入においても起こることではある）

**Comment by yukieiji** [comment]
> 翻訳テキストファイルで使用可能な予約語を追加する。予約語は現在の {0} のように使用でき、予め書式タグも記入されている。

{0}みたいなやつって文字列取ってくる時に`string.Format("{0}秒", 10)`ってやってて文字列の中でも重ための処理なんですよね・・・
これを全システムに共通してやると速度がガッツリ落ちそうな気がしなくもないです

もし全体的にやるってなった場合別ファイルで用意してPythonでコンバートする時に文字列埋め込むくらいですかねー

**Comment by yuhgao** [comment]
なるほど了解です。そうするとナイス・イビルの判定をして表示など、ゲーム内状態の取得は負荷かかりそうな感じでしょうか。
それ以外であればコンバートで対応できそうですね。

**Comment by yukieiji** [comment]
> そうするとナイス・イビルの判定をして表示など、ゲーム内状態の取得は負荷かかりそうな感じでしょうか。

これどういうことです？

**Comment by yuhgao** [comment]
これはtextrevampの話になりますが、たとえばCombination枠であるゲッサー・ムーバーなどは「陣営」の枠をクルー・インポスター併記することで役職が陣営固定でない点を解消しています。可能であればナイス・イビルにアサインされたときの判定を用いて表示できれば、この併記が必要なくなる他、他のロール表示も含めて表記が統一できるのでは、と。

**Comment by yukieiji** [comment]
> これはtextrevampの話になりますが、たとえばCombination枠であるゲッサー・ムーバーなどは「陣営」の枠をクルー・インポスター併記することで役職が陣営固定でない点を解消しています。可能であればナイス・イビルにアサインされたときの判定を用いて表示できれば、この併記が必要なくなる他、他のロール表示も含めて表記が統一できるのでは、と。

これ確か出来るけどめんどいんですよね、以前イビルゲッサーがサーヴァントされた時にナイスゲッサー表記になってたと思うんですが内部的な陣営ってころころ変わるから一概簡単に取得できないので初期化時に強制的にやっててそれと似たようなことをやる必要が出てきますね

**Comment by yukieiji** [comment]
ここらへんの翻訳をこれを本当にガチ目にやりたいのであれば役職クラスを根本的に書き直す必要があるとは思いますね

**Comment by yuhgao** [comment]
うーむ、流石にそこまでやるものではないですね。現実的に考えますとやはりPythonのコンバート時に入れ替えられる部分を予約語とする形が妥当でしょうか。

**Comment by yukieiji** [comment]
いつかは書き直さないと限界が出てくるとは思うのですが現状は問題ないからね・・・
Python変換時に入れるにしても予約語を自動で検出はできないので自分自身で作る必要はありますね
