### ISSUE TITLE
Webチャット機能から左角括弧を送信すると、ルームから追い出される場合がある

### ISSUE THREAD

**Issue by aoirint** [yukieiji/ExtremeRoles#347]
### 期待される動作 / Your Expectation

アジア公式サーバーのロビーで、Webチャット機能から左角括弧を含むチャット`test [`を送信しようとした。

![image](https://github.com/yukieiji/ExtremeRoles/assets/27213639/ec0f5bd9-145d-4e9a-9183-caf19eefd8a1)

### 実際の動作 / The Reality

送信ボタンを押すと、自動的にルームから追い出されてしまった。

![945360_20231223164932_1](https://github.com/yukieiji/ExtremeRoles/assets/27213639/2123e81f-0b39-479e-979e-f1c448512ee3)

ExR東京サーバーでは、ルームから追い出されることなく送信することができた。

![945360_20231223173844_1](https://github.com/yukieiji/ExtremeRoles/assets/27213639/7dd4234d-4384-4c6a-a00d-0dcab03d61ad)

Among Us本体のチャット入力欄では、`"$*+@[]_{|}~`などの一部の記号が入力できない（タイプしてもテキストに追加されない）ようになっていますが、例に挙げたうち、左角括弧`[`が含まれていると、ルームから追い出されました。右角括弧`]`など他に例に挙げたものでは追い出されませんでした。

### あなたの意見 / Your Proposal

Webチャット機能から左角括弧`[`を含むチャットを送信できないようにしてほしい。

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2023-12-23T17-41-44.zip](https://github.com/yukieiji/ExtremeRoles/files/13758481/ExtremeRolesDumpedLogs.2023-12-23T17-41-44.zip)

### Among Usバージョン/ Among Us Version

Among Us v2023.11.28s

### Modバージョン / Mod Version

Extreme Roles v9.2.0.3

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [X] アジア/Asia
- [ ] カスタム/Custom
- [ ] ExR専用(東京)

### プレイヤー人数/Player Num

1

### 使用したオプション/Use Option

なし

**Comment by yukieiji** [comment]
よく見たらXion周りのエラーが出てますがシオンをオフにしたらどうなりますか？

**Comment by aoirint** [comment]
> シオンをオフ

シオンをオフにしてからロビーを開き、`[`を送信しても、ルームから追い出されました。

Xionのエラーは、チャット入力欄に何も入力していない状態でEnterキーを押すと出るようです。

```plain
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at ExtremeRoles.Roles.Solo.Host.Xion.ParseCommand(String chatStr) in D:\a\ExtremeRoles\ExtremeRoles\ExtremeRoles\Roles\Solo\Host\Xion.Command.cs:line 27
   at ExtremeRoles.Patches.Controller.ChatControllerSendChatPatch.Prefix(ChatController __instance) in D:\a\ExtremeRoles\ExtremeRoles\ExtremeRoles\Patches\Controller\ChatControllerPatch.cs:line 133
   at DMD<ChatController::SendChat>(ChatController this)
   at (il2cpp -> managed) SendChat(IntPtr , Il2CppMethodInfo* )
```

コマンドかどうか判定する部分に空文字列が来ていそうです。

https://github.com/yukieiji/ExtremeRoles/blob/27687709581e1db0a12f4c41f6f0bc1e24c3270b/ExtremeRoles/Roles/Solo/Host/Xion.Command.cs#L27
