### ISSUE TITLE
ダミープレイヤーの名前をチャットで入力できる文字に変更してほしい

### ISSUE THREAD

**Issue by aoirint** [yukieiji/ExtremeRoles#349]
### 追加する機能の詳細 / Feature details

ローカルゲームのシオン有効化時に使用できるダミープレイヤー機能では、プレイヤー名にアンダースコア`_`が含まれています。

<details>
<summary>スクリーンショット: ダミープレイヤーが参加する緊急会議</summary>

![945360_20231223222733_1](https://github.com/yukieiji/ExtremeRoles/assets/27213639/a567a71c-d0eb-4b23-b40b-8b52e237df3e)

</details>

ダミープレイヤーの名前を指定するコード箇所

https://github.com/yukieiji/ExtremeRoles/blob/27687709581e1db0a12f4c41f6f0bc1e24c3270b/ExtremeRoles/Roles/Solo/Host/Xion.Keyboard.cs#L33

Among Usのチャット機能ではアンダースコアは入力できない文字のため、`/SetRole`コマンドで対象のプレイヤー名として指定することができません。

```plain
# 入力できない
/SetRole XionDummy_B3AR6KFRXU SpecialCrew

# 入力できる
/SetRole XionDummy-B3AR6KFRXU SpecialCrew
```

ダミープレイヤーの名前のうちアンダースコア`_`をハイフン`-`に変更するなど、プレイヤー名をチャットで入力できる文字で構成するようにしてほしいです。

引数2個の`/SetRole`を処理するコード箇所

https://github.com/yukieiji/ExtremeRoles/blob/27687709581e1db0a12f4c41f6f0bc1e24c3270b/ExtremeRoles/Roles/Solo/Host/Xion.Command.cs#L121-L142

### 機能を追加するメリット / Benefits of adding features

ダミープレイヤーに`/SetRole`コマンドで役職を割り当てることができるようになる。

**Comment by yukieiji** [comment]
そのままPR送ってもらっても構わないですよ・・・・

**Comment by aoirint** [comment]
了解です。PR作成してみました。

- #350
