### ISSUE TITLE
何としてでも生き残ることが目標の第三陣営

### ISSUE THREAD

**Issue by GrunVogel** [yukieiji/ExtremeRoles#35]
### 役職名 / Role Name

プレッサー（仮）

### 役職の色 / Role color

黒っぽい赤

### 役職の説明 / Role description

他人を身代わりにしてでも生き残れ。
仕事もやろう。

### 役職の能力 / Role ability

他人に自分の死を押し付ける第三陣営。システム的にはクルー役職ボディーガードの逆バージョン。
対象に自分だけに見える赤い縁取りを付与して自分がキルされた時に代わりに死んでもらう役職。
能力を発動できるのは会議を挟むたびに一回のみで試合全体では設定で変えて最大値は１５回くらい。
会議毎一回の理由は複数人に能力を使った際の処理がめんどくさそうだったから。

仮案ではクルーメイトにのみ能力が発動でき勝利条件はタスクを終わらせたうえで生き残り続けること。
他の陣営の勝利に乗っかることができる。
設定で他陣営の勝利を乗っ取ることができるのもいいかもしれない。

クルー陣営だけに使えるのは一部第三陣営の理不尽な死を防ぐためである。
ここは設定でインポスターや第三陣営が相手でも能力を発動できるよう切り替えできてもいいかもしれない。

タスクがある理由は暇にならないように。
あと、ただ生き残るだけだとTORのオポチュニストとほとんど変わらないので。

この役職の欠点をあげていくと

- 基本ルールだとクルー陣営以外に能力を使うと効果が発動しないこと。

- 身代わり先が先に死ぬと効果が使えないこと。

- 他の陣営への影響力が他と比べてそんなにないこと。

辺りでしょうか

### 他陣営への影響 / Effect on other teams

クルー陣営としては味方が身代わりにされてしまうからなるべく排除しておきたい存在。

インポスターや第三陣営は特に影響はないが勝利条件的に途中で裏切られる可能性もあるから
やっぱり排除しておきたい存在。

### 陣営 / Team

- [ ] クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 仮案ではクルーメイトにのみ能力が発動でき勝利条件はタスクを終わらせたうえで生き残り続けること。
他の陣営の勝利に乗っかることができる。
設定で他陣営の勝利を乗っ取ることができるのもいいかもしれない。

仮案ではなく、きちんと固まってる案をお願いします・・・。固まってない文章をプログラムに落とし込んで実装するのはすごい難しいので

クルー陣営を減らせるのに他陣営の勝利に乗っかれるした理由を伺いたいです。

>他の陣営への影響力が他と比べてそんなにないこと。

これが解消されないと強化第三陣営ニートや強化タスクマスターと同じに見える気がします。

**Comment by GrunVogel** [comment]
> 仮案ではなく、きちんと固まってる案をお願いします・・・。固まってない文章をプログラムに落とし込んで実装するのはすごい難しいので

それはついては申し訳ない。こういうものを作るのは初めてでしたので…。

> 各会議でほぼ確定でクルー陣営を減らせるのに他陣営の勝利に乗っかれるした理由を伺いたいです。

言われてみればその通りですね…。会議毎にクルーを一人持って行ける可能性があるのなら
他陣営の勝利に乗っかれる設定があると基本的にインポスター陣営との相乗りになってしまいますね…。
これだとクルーが不利すぎますね。

> 他の陣営への影響力が他と比べてそんなにないこと。

ここを改善するとするなら基本値がクルーよりも多い妨害修理の能力をつけることで
インポスター陣営への妨害を仕掛ける能力にすればインポスター陣営から
早急に排除したい存在になるのではないでしょうか。
バランス的な面で少し問題が出るかもしれませんが…

以上のことから改めて、

- 能力はクルーメイトにのみ発動することができる身代わりと
メンテナーよりも多く妨害を修理することのできる第三陣営

- 勝利条件はタスクを終わらせて生き残り続けること。
他陣営の相乗りはできないようにする。

こうすることによりクルー陣営は生き残らせておくことで妨害を修理してくれる可能性があり
インポスター陣営は身代わりにされたクルーメイトが謎の死を遂げ
事件を詰められなくすることができるかもしれません。

しかし最後まで残っていると勝利をかっさらわれるところから
最終的にはどの陣営からも排除対象になる役職です。

これなら指摘された部分の修正ができたと思います。
いつもお疲れ様です。

**Comment by yukieiji** [comment]
> ここを改善するとするなら基本値がクルーよりも多い妨害修理の能力

これはどういうことでしょうか？

> インポスター陣営への妨害を仕掛ける能力にすればインポスター陣営から早急に排除したい存在になるのではないでしょうか。

妨害を仕掛ける能力ってのがどんな妨害をどのように追加するのでしょうか
タスクマスターにも仮案ですが能力を付けるのでそれともかぶらないようにする必要があります

**Comment by yukieiji** [comment]
意見や返信がないためクローズさせていただきます
