### ISSUE TITLE
アサシンがキルされるかがオフなのにイーターの丸呑みによってアサシンがキルされてしまう

### ISSUE THREAD

**Issue by natsu30** [yukieiji/ExtremeRoles#358]
### 期待される動作 / Your Expectation

イーターがアサシンに丸呑みを使用し丸呑みが成功してもアサシンはキルされずイーターの勝利までの人数も進まない

### 実際の動作 / The Reality

イーターがアサシンに丸呑みを使用し丸呑みが成功するとそのままキルされてしまいアサシン会議へと移行してしまう

### あなたの意見 / Your Proposal

イーターがアサシンに丸呑みを使用し丸呑みが成功してもアサシンはキルされずイーターの勝利までの人数も進まないようにしてほしい

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2024-03-17T00-08-48.zip](https://github.com/yukieiji/ExtremeRoles/files/14624242/ExtremeRolesDumpedLogs.2024-03-17T00-08-48.zip)
アサシン Natsu30視点

[ExtremeRolesDumpedLogs_2024-03-17T00-09-16.zip](https://github.com/yukieiji/ExtremeRoles/files/14624244/ExtremeRolesDumpedLogs_2024-03-17T00-09-16.zip)
イーター めーぷる視点

### Among Usバージョン/ Among Us Version

Among Us v2024.3.5s(build num: 3971)

### Modバージョン / Mod Version

Extreme Roles v10.0.0.1

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [X] ExR専用(東京)

### プレイヤー人数/Player Num

9名

### 使用したオプション/Use Option

[option.csv](https://github.com/yukieiji/ExtremeRoles/files/14624251/option.csv)
option.csvファイルをとるのを忘れてしまいこのファイルは発生当時の設定をできる限り再現したものになります

**Comment by yukieiji** [comment]
不具合を確認し、修正が完了しました
急ぎ使用する予定等はありますか？なければ今週金曜日のアプデに合わせて修正する予定ですが

**Comment by natsu30** [comment]
特にないです
対応ありがとうございます！
