### ISSUE TITLE
MIRA HQのランダムスポーンがオフの時、MiraHQの会議終了時に暗転する

### ISSUE THREAD

**Issue by aoirint** [yukieiji/ExtremeRoles#359]
### 期待される動作 / Your Expectation

MIRA HQマップで緊急会議を開き、全員がスキップして会議を終了しようとした。

### 実際の動作 / The Reality

「進行まであと0秒」が表示された後、追放確認画面が表示される前に、画面が暗転してゲームが進行しなかった。

![image](https://github.com/yukieiji/ExtremeRoles/assets/27213639/0d3527d7-c5b1-4405-95ab-ebd0be752b37)

<details>
<summary>再現動画: 会議終了時の画面</summary>

https://github.com/yukieiji/ExtremeRoles/assets/27213639/851a079a-9f32-4b07-a2ab-4dbd404e723e

</details>

<details>
<summary>再現動画: 試合開始から会議終了まで</summary>

https://github.com/yukieiji/ExtremeRoles/assets/27213639/45b6bea2-ee43-420f-80dc-c56fe970adf4

</details>

追放時、スキップ時のどちらでも不具合が発生した。

他マップSkeld、Polus、Airship、Fungleでは追放確認画面が表示され、正常に進行した。

### あなたの意見 / Your Proposal

会議が正常に終了してゲームが進行するようにしてほしい。

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2024-03-17T22-01-54.zip](https://github.com/yukieiji/ExtremeRoles/files/14627482/ExtremeRolesDumpedLogs.2024-03-17T22-01-54.zip) （ホストのログ）

### Among Usバージョン/ Among Us Version

Among Us v2024.3.5s

### Modバージョン / Mod Version

Extreme Roles v10.0.0.1

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [X] カスタム/Custom
- [ ] ExR専用(東京)

### プレイヤー人数/Player Num

4

### 使用したオプション/Use Option

[option_2024-03-17_ExR_MIRAHQ.csv](https://github.com/yukieiji/ExtremeRoles/files/14627463/option_2024-03-17_ExR_MIRAHQ.csv)

**Comment by yukieiji** [comment]
不具合の確認と修正を完了しました
直近で使用する予定がありますか？なければ金曜日のアプデにて修正版をリリース予定です

**Comment by aoirint** [comment]
> 直近で使用する予定がありますか？

直近で使用する予定はありません。修正ありがとうございます！
