### ISSUE TITLE
「塗り」をしている状態で会議が開始されると、会議開始後のテレポートまで他人の画面上でアーティストの「塗り」が継続される

### ISSUE THREAD

**Issue by sakiya1016** [yukieiji/ExtremeRoles#361]
### 期待される動作 / Your Expectation

ボタンを押したら塗りが発生、押していなければ塗りは発生しない

#### 開発者追記
会議開始前に「塗り」を発動している状態で会議が開始される、会議開始時のテレポート終了時まで他人の視点上では見えてしまう
 - アーティスト自身の「塗り」が継続されていないため、勝利には一切関係なく表示上の不具合です

#### 元々のチケット
何もしていないのに他人視点では経路上にアーティストのインクが見えていた
また幽霊になった後に本来は入れない場所にもインクが見えた

### あなたの意見 / Your Proposal

正常な状態に直せるならお願いします

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2024-04-06T23-04-14.zip](https://github.com/yukieiji/ExtremeRoles/files/14893825/ExtremeRolesDumpedLogs.2024-04-06T23-04-14.zip)

### Among Usバージョン/ Among Us Version

Among Us v2024.3.5

### Modバージョン / Mod Version

Extreme Roles v10.1.0.1

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [X] アジア/Asia
- [ ] カスタム/Custom
- [ ] ExR専用(東京)

### プレイヤー人数/Player Num

15

### 使用したオプション/Use Option

バウンティ、イビルゲッサー、クラッカー
シェリ、TM、パン屋、覚醒キャプテン50％、覚醒ベイト70％、メンテナー（1回）
クイーン（サバがキル役職だと自爆しない）、アーティスト

**Comment by sakiya1016** [comment]
キルされる前の他人視点　[https://youtu.be/ey0jlxwcOYk](url)
キルされた後のアーティスト本人視点　[https://youtu.be/3OgQ6-MzVac](url)

**Comment by sakiya1016** [comment]
キルされる前の他人視点：https://youtu.be/ey0jlxwcOYk
キルされた後のアーティスト本人視点：https://youtu.be/3OgQ6-MzVac

**Comment by sakiya1016** [comment]
他の幽霊視点
![A1](https://github.com/yukieiji/ExtremeRoles/assets/152633226/78191ff0-4978-44d9-a1a6-bed8c72c4707)
![A2](https://github.com/yukieiji/ExtremeRoles/assets/152633226/de68dc23-d72b-4123-9ddf-ea77416916b1)

**Comment by sakiya1016** [comment]
> キルされる前の他人視点：https://youtu.be/ey0jlxwcOYk 幽霊になったアーティスト本人視点：https://youtu.be/3OgQ6-MzVac

**Comment by yukieiji** [comment]
不具合を確認しました、「塗り」中に会議が発生すると発動する不具合です

**Comment by yukieiji** [comment]
[v10.1.0.2](https://github.com/yukieiji/ExtremeRoles/releases/tag/v10.1.0.2)で修正
