### ISSUE TITLE
アサシン会議終了時にハッターのスキップカウントが加算されてしまう

### ISSUE THREAD

**Issue by U1kirby** [yukieiji/ExtremeRoles#362]
### 期待される動作 / Your Expectation

ハッターの「勝利出来る会議スキップ回数」が4回なのに対して3回スキップを行った状態でアサシン会議に突入、アサシンはマーリンを当てることができず、クルー4人インポスター1人キルボタンを持たないニュートラル2人(ハッター含む)が残っていたため試合を続行する。

### 実際の動作 / The Reality

https://github.com/yukieiji/ExtremeRoles/assets/143887123/46d8a664-b3ca-4ca7-9505-283283cba668

アサシン会議終了時点でハッターが勝利した。

### あなたの意見 / Your Proposal

「アサシン会議でマーリンを当てることに失敗すること」はハッターの「勝利出来る会議スキップ回数」としてはカウントしないでほしい。

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesBackupLog 2024-04-13T01-16-30.log](https://github.com/yukieiji/ExtremeRoles/files/14981444/ExtremeRolesBackupLog.2024-04-13T01-16-30.log)
私自身はホストではなかったため不完全かもしれません。また、ログは後から取ったので次以降の試合のログも入ってしまっています。

### Among Usバージョン/ Among Us Version

Among Us v2024.3.5

### Modバージョン / Mod Version

Extreme Roles 10.1.0.2

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [X] ExR専用(東京)

### プレイヤー人数/Player Num

13

### 使用したオプション/Use Option

csvファイルが残っておらず、記憶も曖昧であるため、確認がお手数かと思いますが動画を添付します。

https://github.com/yukieiji/ExtremeRoles/assets/143887123/79e65d56-52b3-493e-8e28-14fe3abc5563

添付の動画は同日の別試合における設定で、人数の変動と役職の入れ替えがいくつかありましたが、全体の設定は変更がないはずです。

肝心のハッターの設定が映っていないのは申し訳ありません。「勝利出来る会議スキップ回数」が4回であったこと以外は不明です。

**Comment by yukieiji** [comment]
プログラムのコード的にこのような自体が発生し得ない感じに見えます
また、ログの中にアサシン会議後にハッターが勝利したというログが一切見当たらないですがこの試合のログは正しく取れてますでしょうか？

**Comment by U1kirby** [comment]
このアサシン会議は普通にアサシンを会議で追放して始まっています。
追放以外の方法でアサシンを排除できる役職は投入されていません。

ログが正しく取れているかどうかの判断は私にはできないのですが、たしかに該当の会議はアサシン会議ではないことになっているようですね。

ホストのログはより詳しい情報が載るようなので、もらってきました。以下に添付いたします。
こちらではアサシン会議後にハッターが勝利しているのが確認できると思います。

[ExtremeRolesBackupLog_2024-04-13T01-12-11.log](https://github.com/yukieiji/ExtremeRoles/files/15011853/ExtremeRolesBackupLog_2024-04-13T01-12-11.log)

**Comment by yukieiji** [comment]
ログを確認しました、以下の点を追加で確認です

1. ホストとサーバーとの通信状況はどれくらいだったのでしょうか(Pingの値等)
2.  同じプレイヤーが勝利しているみたいなので「森守」さんとサーバーとの通信状況はどれくらいだったのでしょうか(Pingの値等)

**Comment by U1kirby** [comment]
ホストの通信状況はping値17～20msだったそうです。

森守さんの状況はニコ生のアーカイブ( https://live.nicovideo.jp/watch/lv344903616 )で確認できますが、こちらもping値は基本的に数ms、時々十数msになるくらいのようです。
(当該のアサシン会議は2:31:00頃から、その前の試合は1:58:45に最終会議が始まります。)

**Comment by yukieiji** [comment]
v10.1.0.4にて修正完了

**Comment by U1kirby** [comment]
ご対応いただきありがとうございました。
