### ISSUE TITLE
ジェイラーの「「投獄」が失敗時、自決するか」がオフであっても、能力を使用すると自決してしまう

### ISSUE THREAD

**Issue by 0zenico** [yukieiji/ExtremeRoles#373]
### 期待される動作 / Your Expectation

『「投獄」が失敗時、自決するか』がオフになっている状態で
ジェイラーが人外を投獄した際に人外をヤードバードに変更して自身も生存する。

### 実際の動作 / The Reality

『「投獄」が失敗時、自決するか』がオフになっている状態で
ジェイラーで人外を投獄した時に人外をヤードバードに変更できるが自身が自決する。

### あなたの意見 / Your Proposal

何度か検証したのですが投獄に成功しても自爆してしまうので生存できるように修正して頂きたいです。

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2024-07-28T01-01-40.zip](https://github.com/user-attachments/files/16400814/ExtremeRolesDumpedLogs.2024-07-28T01-01-40.zip)

### Among Usバージョン/ Among Us Version

Among Us v2024.6.18s

### Modバージョン / Mod Version

Extreme Roles v11.1.0.1

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [X] アジア/Asia
- [ ] カスタム/Custom
- [ ] ExR専用(東京)

### プレイヤー人数/Player Num

4

### 使用したオプション/Use Option

クルー、ジェイラー、、配下が作れる第三陣営、ヒプノティスト

**Comment by yukieiji** [comment]
色々と間違えていました
**この仕様はバグではなく最初から意図されている仕様になります**

ですが、能力使用回数0回の自決をオフにするには「「投獄」が失敗時、自決するか」がオフではないと設定できないのはおかしいはずですのでそこを修正します

問題なければそのままクローズします

**Comment by 0zenico** [comment]
『「投獄」が失敗時、自決するか」がオフの時』に『能力使用回数0回の自決をオフ』が設定できるようになるという解釈でよろしいでしょうか。でしたら問題ありません。

**Comment by yukieiji** [comment]
[v11.1.1.0](https://github.com/yukieiji/ExtremeRoles/releases/tag/v11.1.1.0)で対応が完了
