### ISSUE TITLE
会議中に能力が使える役職がゲッサー能力があると使えなくなる

### ISSUE THREAD

**Issue by rikku-YU** [yukieiji/ExtremeRoles#375]
### 発生原因

- 本来ゲッサー等の**コンビネーションでありながらのシングル役職は複数能力を持つことを前提に開発はされてない**です、そのため設定できる事自体が想定外の挙動となります
  - v11のオプション構造変更時のミスによって設定できるようになっていました(v11より前のバージョンではオプションとしては内部的に存在していましたが設定できないようになっていました)

### 対処法
 - オプションを設定しないでください、本来想定されていない挙動であるため色々と不整合が発生することが予想されます

### 期待される動作 / Your Expectation

ナイスゲッサー&キャプテンの場合、会議中にゲッサーとキャプテンの特殊投票が使える。

### 実際の動作 / The Reality

ナイスゲッサー&キャプテンの場合、ゲッサーのアイコンと特殊投票のアイコンが重なり合ってしまい、能力が使えなくなる。

### あなたの意見 / Your Proposal

アイコンをそれぞれ順番に並ぶようにするか、アイコンの出現する位置を変更する。被らなければ問題ないので、切り替えるなども。

### バグ発生時のログやエラー / log when issue occur

なし

### Among Usバージョン/ Among Us Version

Among Us v2024.6.18s

### Modバージョン / Mod Version

Extreme Roles v11.1.0.1

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [X] アジア/Asia
- [ ] カスタム/Custom
- [ ] ExR専用(東京)

### プレイヤー人数/Player Num

7

### 使用したオプション/Use Option

[settingsExR.csv](https://github.com/user-attachments/files/16564583/settingsExR.csv)

**Comment by yukieiji** [comment]
ナイスゲッサー等のシングル役職は本来の挙動的に複数の役職能力を持つこと自体が想定されていないものになります

2024.6.18対応でオプションを修正した際にオプションで設定できるようになっていた事自体が不具合になります

**Comment by yukieiji** [comment]
次期アップデートにて設定できないように再調整いたします(オプション自体作られなくなり読み込みにも影響が出ないようにします)

**Comment by yukieiji** [comment]
@rikku-YU 調査し検証したところオプション自体の作成を無効化した際に多大な影響が出そうなため、v10で想定されている従来通りの挙動に戻します
その際、アップデート後別能力周りのオプションが**再設定できない**ようになりますのでアプデ前に設定しないようにしてください

**Comment by yukieiji** [comment]
[v11.1.1.0](https://github.com/yukieiji/ExtremeRoles/releases/tag/v11.1.1.0)で対応が完了
