### ISSUE TITLE
モデレーターのボタン能力が動作していない

### ISSUE THREAD

**Issue by tukihatu** [yukieiji/ExtremeRoles#377]
### 期待される動作 / Your Expectation

モデレーターのボタン能力を発動したとき、次の会議時間が増加する

### 実際の動作 / The Reality

ボタン能力を発動しても、次の会議時間が増加していない。
ボタン自体は押すことができ、押した際、左下のメッセージも表示される。
（ローカル、シオンで再現可能）

### あなたの意見 / Your Proposal

期待される動作に修正してほしい

### バグ発生時のログやエラー / log when issue occur

[ホストExtremeRolesDumpedLogs 2024-08-25T23-57-34.zip](https://github.com/user-attachments/files/16742891/ExtremeRolesDumpedLogs.2024-08-25T23-57-34.zip)
[モデレータ本人ExtremeRolesDumpedLogs 2024-08-25T23-43-39.zip](https://github.com/user-attachments/files/16742892/ExtremeRolesDumpedLogs.2024-08-25T23-43-39.zip)

### Among Usバージョン/ Among Us Version

Among Us v2024.8.13e(build num: 4431)

### Modバージョン / Mod Version

Extreme Roles ver.12.0.0.0

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [X] ExR専用(東京)

### プレイヤー人数/Player Num

10

### 使用したオプション/Use Option

[option.csv](https://github.com/user-attachments/files/16742949/option.csv)

**Comment by yukieiji** [comment]
バグ修正が完了しました
SEのロードミスによる不具合です

**Comment by yukieiji** [comment]
[v12.0.0.1](https://github.com/yukieiji/ExtremeRoles/releases/tag/v12.0.0.1)にて対応が完了
