### ISSUE TITLE
エージェンシーがクルー役職の全タスクを肩代わりすると完了しているはずの共通タスクが残ってしまう

### ISSUE THREAD

**Issue by tukihatu** [yukieiji/ExtremeRoles#379]
### 期待される動作 / Your Expectation

■条件
最初に割り振られるタスク数が3（1/1/1）の状態でエージェンシーがクルー役職（リザレクター）から3タスクを取る
■結果
肩代わりを受けたクルーはタスク完了が3/3となり、全タスクにアクセス(インタラクト)できなくなり、全クルーがタスクを完了すればタスク勝利できる

### 実際の動作 / The Reality

上記条件時
■結果
肩代わりを受けたクルーはタスク完了が3/3となるが、共通タスクにアクセスが可能となっている。
3/3の状態で共通タスクを完了させると、タスク表記が1/3となり、この状態になると全クルーがタスクを完了させてもタスク勝利できない
また、肩代わりを受けたクルー役職がリザレクターだった場合、3/3の状態で死亡＋復活後共通タスクを完了させると幽霊になる（検証試合にて、幽霊状態で壁判定あり）

試合開始から
https://www.youtube.com/live/M-7t4s31Otg?si=P1YaA8UcCHAGextb&t=6962
エージェンシーがリザレクターのタスクを肩代わりした場面
https://www.youtube.com/live/M-7t4s31Otg?si=jSebL8XX2vo4yQIc&t=7028
タスク3/3完了時に共通タスク(IDコード)を行い、タスク数が1/3になった場面
https://www.youtube.com/live/M-7t4s31Otg?si=8AoiM8Fa4f6ZZkWf&t=7134
リザレクター死亡・復活時
https://www.youtube.com/live/M-7t4s31Otg?si=3kNMHkwvZSauXGju&t=7402
リザレクター2回目死亡後、幽霊でタスクを探した場面
https://www.youtube.com/live/M-7t4s31Otg?si=i6UPtUXbKJGTV9cf&t=7787

検証試合 試合開始から
https://www.youtube.com/live/M-7t4s31Otg?si=5pqiLqZCAuiMjZP-&t=10243
検証試合 エージェンシーがリザレクターのタスクを肩代わりした直後の会議
https://www.youtube.com/live/M-7t4s31Otg?si=s5T6SoudCUNPO1tB&t=10304
検証試合 上記後にリザレクターが死亡、復活後共通タスクを完了させると幽霊に
https://www.youtube.com/live/M-7t4s31Otg?si=CHM35-T6cCW70K83&t=10418
検証試合 エージェンシーがクルーのタスクを肩代わりし、その後クルーが共通タスクを完了
https://www.youtube.com/live/M-7t4s31Otg?si=NgqHntOY8si1mBqK&t=10948
検証試合 上記後に全員がタスクを完了させるがタスク勝利にならない
https://www.youtube.com/live/M-7t4s31Otg?si=V3jyY4M2cAyEskBb&t=11251
検証試合 リザルト
https://www.youtube.com/live/M-7t4s31Otg?si=8yHU1y2NDspgKONq&t=11453

### あなたの意見 / Your Proposal

期待される動作に修正してほしい

### バグ発生時のログやエラー / log when issue occur

[ホストリザレクターExtremeRolesDumpedLogs 2024-08-25T23-27-02.zip](https://github.com/user-attachments/files/16743558/ExtremeRolesDumpedLogs.2024-08-25T23-27-02.zip)
[エージェンシー側ExtremeRolesDumpedLogs 2024-08-25T23-28-46.zip](https://github.com/user-attachments/files/16743559/ExtremeRolesDumpedLogs.2024-08-25T23-28-46.zip)

検証試合
[ホストクルーExtremeRolesDumpedLogs 2024-08-26T00-25-49.zip](https://github.com/user-attachments/files/16743562/ExtremeRolesDumpedLogs.2024-08-26T00-25-49.zip)
[リザレクターExtremeRolesDumpedLogs 2024-08-26T00-15-04.zip](https://github.com/user-attachments/files/16743563/ExtremeRolesDumpedLogs.2024-08-26T00-15-04.zip)
[エージェンシーExtremeRolesDumpedLogs 2024-08-26T00-26-17.zip](https://github.com/user-attachments/files/16743564/ExtremeRolesDumpedLogs.2024-08-26T00-26-17.zip)

### Among Usバージョン/ Among Us Version

Among Us v2024.8.13e(build num: 4431)

### Modバージョン / Mod Version

Extreme Roles ver.12.0.0.0

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [X] ExR専用(東京)

### プレイヤー人数/Player Num

10

### 使用したオプション/Use Option

[option.csv](https://github.com/user-attachments/files/16743568/option.csv)

検証試合オプション
[検証時option.csv](https://github.com/user-attachments/files/16743570/option.csv)

**Comment by yukieiji** [comment]
バグ修正が完了しました
SEのロードミスによる不具合です

**Comment by yukieiji** [comment]
[v12.0.0.1](https://github.com/yukieiji/ExtremeRoles/releases/tag/v12.0.0.1)にて対応が完了
