### ISSUE TITLE
スマッシャー：インポスター役職

### ISSUE THREAD

**Issue by kisaRagi05** [yukieiji/ExtremeRoles#38]
### 役職名 / Role Name
スマッシャー
### 役職の色 / Role color
インポスター色
### 役職の説明 / Role description
1度だけキルクールの無いキルボタン「スマッシュ(SMASH)」を使えるインポスター陣営
設定が少なく複雑性が無いシンプルなのがテーマ
### 役職の能力 / Role ability

設定詳細：
- 説明文の通り、通常のキルとは別のキルボタン「スマッシュ」を追加
- 通常のキルボタンとは一切連動しない
- 使用回数は1回（設定変更不可）
- ロビーでの設定変更は「スポーン数」のみとする

メリット：

- 二人組を狙う事が可能
- 別のキルボタン持ちとの撃ち合いで必勝が可能
- 通常キルクールよりも早い会議ボタンより早くキルが可能
- ラバーズ読みで通常キル、違うならもう1名をスマッシュキルという作戦も可能
- 通常キルのクール明け前に死体に近付く人への対策としても有効
- 終盤に一人でダブルキルをして勝利を狙う事も可能

デメリット：

- 上記のメリットは全て1回限定
- スマッシュキルを発動後は普通のインポスターと同じになる
- スマッシュキルは通常キルと同じくタイムマスターやフェンサーの能力には勝てない
- 序盤に使用すると終盤で使えば勝てる場面で使えない
- 終盤に使用しようと抱え落ちして使えない事も

複雑で設定の多い役職が多く説明も長くなる事が多いので
逆に一言で説明できる役職なんてどうでしょうと案を投稿しました。
元ネタはスマブラの「最後の切り札」

クローズされた「サムライ」と非常に似ていますが
「シンプル」「わかりやすい」「誰でも簡単に能力を使える」
この点は魅力的だと思います。

### 他陣営への影響 / Effect on other teams

- 通常キルと同じく死体は残るので推理で吊る事が可能
- スマッシャーの能力発動を確定出来ない場合、常にスマッシュキルを警戒しなければならない

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
こちらでは初めまして

本当に申し訳ないのですが、以下の点でこの役職をチケットの意見のままその通りに実装することは出来ないです

> ロビーでの設定変更は「スポーン数」のみとする

インポスターの役職を作る(能力とか何にも考えなしでも)と「スポーン数」以外に「視界」、「キルクール」、「キルレンジ」の設定計7個は自動的に作成されるので、オプションを「スポーン数」だけにするのは無理です・・・(申し訳ない)
また、能力の使用回数がある能力ボタンを持つ際は基本的なオプションがいくつか作成されます

> 1度だけキルクールの無いキルボタン「スマッシュ(SMASH)」を使えるインポスター陣営

ボタンのクールタイムは全てあることを前提に作ってるのでクールタイムがないボタンが作れるか作ったとしても正しく動作するか微妙です

**Comment by kisaRagi05** [comment]
挨拶が遅れました。こちらでは初めまして。よろしくお願いします。

> インポスターの役職を作る(能力とか何にも考えなしでも)と「スポーン数」以外に「視界」、「キルクール」、「キルレンジ」の設定計7個は自動的に作成されるので、オプションを「スポーン数」だけにするのは無理です・・・(申し訳ない)
また、能力の使用回数がある能力ボタンを持つ際は基本的なオプションがいくつか作成されます

なるほど、でしたら「設定」できるものを最低限にするで大丈夫ですね。
設定項目を少なくするがテーマなので、必ずしもスポーン数のみにする必要はありませんでした。

> ボタンのクールタイムは全てあることを前提に作ってるのでクールタイムがないボタンが作れるか作ったとしても正しく動作するか微妙です

ではキルクールを「0秒」でなく「最短」にしましょう。最速で何秒までいけるかは分かりませんが、「0.5秒」とかいけましたかな？

**Comment by yukieiji** [comment]
> なるほど、でしたら「設定」できるものを最低限にするで大丈夫ですね。
設定項目を少なくするがテーマなので、必ずしもスポーン数のみにする必要はありませんでした。

それであれば大丈夫です

> ではキルクールを「0秒」でなく「最短」にしましょう。最速で何秒までいけるかは分かりませんが、「0.5秒」とかいけましたかな？

能力の使用制限付きボタンの場合、オプションが以下の仕様で作成されます(サンドワームはクールの減り方が全く異なっているボタンという点とボタン自体の能力がシンプルだったため、特殊なボタンを作って実装しているためこれに沿いません)
 - 使用回数：1～設定数
 - デフォルト：設定数
 - クールタイム：0.5秒～120秒
 - デフォルトクールタイム：30秒

**Comment by kisaRagi05** [comment]
>  使用回数：1～設定数
>   デフォルト：設定数
>   クールタイム：0.5秒～120秒
>   デフォルトクールタイム：30秒

これで良いと思います。
「使用回数」は最大14回でシェリフのキル数と同数に。
「デフォルト」は1回にしましょう。

ネタプレイでキル回数14回の0.5秒キルクールとかで遊ぶ事もできるように。
卓によっては「30秒1キル」や「0.5秒1キル」など合わせられるように。

基本的に使用回数は1回を推奨という感じで良いかと思います。

**Comment by yukieiji** [comment]
> これで良いと思います。
「使用回数」は最大14回でシェリフのキル数と同数に。
「デフォルト」は1回にしましょう。

こうなってくると本格的にクローズされた「サムライ」に近くなってますね(あっちはキルクールが特殊ではあるけど共通なのでこっちのほうがちょっと強め？私個人の意見としては強いってなると何らかのペナルティやデメリットが欲しくなっては来ます)

**Comment by kisaRagi05** [comment]
なるほど、ちなみに使用回数1～1にした場合は変えられない設定項目みたいに表示される感じでしょうか？
使用回数を1～1にする事になにか不備があるかなと勝手に思ってしまい、別の仕組みにしようと思いました。
1だけの設定に問題が無ければ1だけにするのを希望します

ペナルティとしてはスマッシュキルを使用すると
永続デバフとして通常キルクールが伸びるとかどうでしょうか
卓によってペナルティ無しや致命的なペナルティを与えられるように
0秒～任意の秒数で設定する感じにします

例えるならポケモンの「オーバーヒート」みたいな反動による弱体化ですね
極めて強い攻撃の反動で攻撃力が大幅に下がるみたいな感じとなります

**Comment by yukieiji** [comment]
> なるほど、ちなみに使用回数1～1にした場合は変えられない設定項目みたいに表示される感じでしょうか？
使用回数を1～1にする事になにか不備があるかなと勝手に思ってしまい、別の仕組みにしようと思いました。
1だけの設定に問題が無ければ1だけにするのを希望します

それを試したことがないのでやってみないとわからないとしか言えないです(おそらく大丈夫だとは思いますが)

> ペナルティとしてはスマッシュキルを使用すると
永続デバフとして通常キルクールが伸びるとかどうでしょうか
卓によってペナルティ無しや致命的なペナルティを与えられるように
0秒～任意の秒数で設定する感じにします

それくらいなら問題ないと思います。永続であるって部分でデメリットは重いと思いますので
デフォルトは4秒程度でしょうか？

**Comment by kisaRagi05** [comment]
> それを試したことがないのでやってみないとわからないとしか言えないです(おそらく大丈夫だとは思いますが)

ではお試しお願いします！

> それくらいなら問題ないと思います。永続であるって部分でデメリットは重いと思いますので
デフォルトは4秒程度でしょうか？

デフォルト4秒で良いと思います

**Comment by yukieiji** [comment]
マイルストーンをExtreme Roles v2.0.5.0(リリース時期4月22日目標)へセットします

**Comment by yukieiji** [comment]
一応、9割型完成したので仕様の確認です

- スマッシュの使用回数の件
  - スマッシュの使用回数は1～1にすることは出来ました。ただし、値を変更することが出来ないオプションとして表示されています
  - このままだと見栄え的な部分でも邪魔なので1～14の案で実装を考えたいのですがどうでしょうか(1～1でどうしてもというならそのまま行きます)
- キルクールペナルティーの適用の件
  - キルクールペナルティーは現在のキルクールに対しても設定されるべきなのでしょうか、それとも次回キルボタンを使用した時に加算されるのでしょうか
    - 現在のキルクールに設定される場合、現在のキルボタンのキルクール+ペナルティーと言う形で実装しようと思います
- キルクールペナルティーの設定幅は0.5～30秒で問題ないでしょうか？

**Comment by kisaRagi05** [comment]
>    スマッシュの使用回数は1～1にすることは出来ました。ただし、値を変更することが出来ないオプションとして表示されています
>    このままだと見栄え的な部分でも邪魔なので1～14の案で実装を考えたいのですがどうでしょうか(1～1でどうしてもというならそのまま行きます)

1～14でいきましょう

> キルクールペナルティーは現在のキルクールに対しても設定されるべきなのでしょうか、それとも次回キルボタンを使用した時に加算されるのでしょうか 

「次回キルボタンを使用した時に加算」にしましょう
現在のキルクールに対しても設定した場合、キルクールの見誤りによる事故がありそうだと思います
なのでプレイヤーに余計な考えを与えない設計でいきましょう

> キルクールペナルティーの設定幅は0.5～30秒で問題ないでしょうか？

0～30秒は可能ですか？
強さインフレのお遊び回とかで無反動とか出来れば良いかなと思いましたが
技術的または考え的に難しいようであれば
0.5～30秒で問題ありません

**Comment by yukieiji** [comment]
> 1～14でいきましょう

承知しました

> 「次回キルボタンを使用した時に加算」にしましょう
現在のキルクールに対しても設定した場合、キルクールの見誤りによる事故がありそうだと思います
なのでプレイヤーに余計な考えを与えない設計でいきましょう

承知しました

> 0～30秒は可能ですか？
強さインフレのお遊び回とかで無反動とか出来れば良いかなと思いましたが
技術的または考え的に難しいようであれば
0.5～30秒で問題ありません

0～30秒で実装しました

**Comment by yukieiji** [comment]
Extreme Roles v2.0.5.0の開発用ブランチ「develop-v2.0.5.0」のコミット7f27b92b4e4fb8552a5263fc90a8e43f7c406b84にて実装が完了したためクローズします
