### ISSUE TITLE
ロビー画面にて「編集」「ExtremeRoles」ボタンを押してから画面を閉じると、キーボード操作を受け付けなくなる

### ISSUE THREAD

**Issue by tukihatu** [yukieiji/ExtremeRoles#381]
### 期待される動作 / Your Expectation

「編集」「ExtremeRoles」ボタンを押した後もマウス+キーボードで操作（移動）可能

### 実際の動作 / The Reality

「編集」「ExtremeRoles」ボタンを押した後、画面を閉じると、移動ができなくなる。
マウス操作、チャット文字入力は可能。

### あなたの意見 / Your Proposal

期待される動作に修正してほしい

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2024-09-08T21-47-45.zip](https://github.com/user-attachments/files/16922243/ExtremeRolesDumpedLogs.2024-09-08T21-47-45.zip)

### Among Usバージョン/ Among Us Version

Among Us v2024.9.4

### Modバージョン / Mod Version

Extreme Roles v12.0.1.0

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [X] ExR専用(東京)

### プレイヤー人数/Player Num

10

### 使用したオプション/Use Option

[option.csv](https://github.com/user-attachments/files/16922247/option.csv)
![2024-09-08_21h49_10](https://github.com/user-attachments/assets/aa56d0c5-ad39-43e7-a42b-dd5af5228e5a)
移動ボタン両方使用できない

**Comment by yukieiji** [comment]
[v12.0.1.1](https://github.com/yukieiji/ExtremeRoles/releases/tag/v12.0.1.1)で修正
