### ISSUE TITLE
インポスターがラバーズにアサインされる確率が10%でも100%になっている

### ISSUE THREAD

**Issue by piropirohiko** [yukieiji/ExtremeRoles#382]
### 期待される動作 / Your Expectation

インポスターがラバーズにアサインされる設定をオンにし、確率を10%に設定するとたまにラバーズがインポスターになる。

### 実際の動作 / The Reality

10%ではなく100%の確率でラバーズにインポスターがアサインされる。
![945360_14](https://github.com/user-attachments/assets/22e6ea93-d193-4ab2-96b5-b2bd63d55342)

### あなたの意見 / Your Proposal

既知のバグらしいが、誰もバグ報告をしていなかった。

### バグ発生時のログやエラー / log when issue occur

[ExtremeRolesDumpedLogs 2024-09-23T00-26-28.zip](https://github.com/user-attachments/files/17090235/ExtremeRolesDumpedLogs.2024-09-23T00-26-28.zip)

### Among Usバージョン/ Among Us Version

Among Us v2024.9.4s

### Modバージョン / Mod Version

Extreme Roles v12.0.1.2

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [X] ExR専用(東京)

### プレイヤー人数/Player Num

15

### 使用したオプション/Use Option

[option.csv](https://github.com/user-attachments/files/17090241/option.csv)

**Comment by yukieiji** [comment]
> 既知のバグらしいが、誰もバグ報告をしていなかった。

既知ってどれくらい前から既知であったかわかりますか？
コード的にはオプションを変更したv11より前では発生しなさそうですが、それより前からあると本格的に治すのがかなり面倒になりそうですが

**Comment by piropirohiko** [comment]
少なくとも7月25日とのことでした。
https://youtu.be/X03gOb9tlIY?t=1189
https://youtu.be/X03gOb9tlIY?t=2321

**Comment by yukieiji** [comment]
7/25であればv11で発生した不具合ですね
おそらく上記の修正コミットで修正されていると思われます

**Comment by yukieiji** [comment]
[v12.0.2.0](https://github.com/yukieiji/ExtremeRoles/releases/tag/v12.0.2.0)で修正済み
