### ISSUE TITLE
タイムマスターの「タイムシールド」がクールタイム中にも反応する

### ISSUE THREAD

**Issue by kisaRagi05** [yukieiji/ExtremeRoles#384]
### 期待される動作 / Your Expectation

タイムマスターの「タイムシールド」のクールタイム中に能力発動ボタンを押しても反応せず
クールタイム開け以降はボタンを押すと反応して、「タイムシールド」の効果が発動する

### 実際の動作 / The Reality

タイムマスターの「タイムシールド」がクールタイム中でも反応して
「タイムシールド」の持続時間に切り替わるが能力は発動していない
その状態での持続時間中にキルされるのを確認

### あなたの意見 / Your Proposal

役職「フェンサー」では同様の症状は発生せず
他の役職にも類似の症状があるかは未確認

### バグ発生時のログやエラー / log when issue occur

バグ発生時のアーカイブ
49:25～
https://live.nicovideo.jp/watch/lv346370243

ローカルでの再現性確認時のログ
[ExtremeRolesDumpedLogs 2024-11-24T09-24-35.zip](https://github.com/user-attachments/files/17887383/ExtremeRolesDumpedLogs.2024-11-24T09-24-35.zip)

### Among Usバージョン/ Among Us Version

Among Us v2024.11.26s

### Modバージョン / Mod Version

Extreme Roles v12.0.2.4

### リージョン/Region

- [ ] 北アメリア/Noth America
- [ ] 欧州/Europa
- [ ] アジア/Asia
- [ ] カスタム/Custom
- [X] ExR専用(東京)

### プレイヤー人数/Player Num

15

### 使用したオプション/Use Option

[option.csv](https://github.com/user-attachments/files/17887674/option.csv)

**Comment by yukieiji** [comment]
不具合の確認と修正が完了しました
かなり前からある不具合っぽいです

**Comment by yukieiji** [comment]
[v12.1.0.0](https://github.com/yukieiji/ExtremeRoles/releases/tag/v12.1.0.0)にて修正が完了
