### ISSUE TITLE
【クルー陣営のみのコンビネーション役職】二人は相棒！「バディーズ」

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#39]
### 役職名 / Role Name
バディーズ

### 役職の色 / Role color
黄色みがかったオレンジ

### 役職の説明 / Role description
基本となるのは本家人狼でいうところの共有者
ただしタスクを一定量こなさないとバディーズであることと相方を把握できない
お互いに白確できるできるので会議を主導しやすい

#### パッシブ能力
二人一組で構成される。
カーペンターのように、最初は通常のクルーとしてアサインされる。
2人がタスクを一定量こなすと覚醒し、自分がバディーズであること、そして相方が誰なのかを把握できる。
例えば、タスク進捗75%で覚醒する場合、バディーズになる予定のクルーAとB両方が75%以上タスクを完了しないと双方覚醒しない。

### 他陣営への影響 / Effect on other teams
覚醒するまでの間にキルを重ねてバディーズ予定のクルーを死なせることで、騙りによるバディーズ乗っ取りが可能になる。

### 陣営 / Team
- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
ラバーズの上位互換で白証明が簡単にできる役職なので、個人的にはデメリットが欲しくなりますが何か無いでしょうか

**Comment by melonjagaimo** [comment]
では、片方が死んだ後は相方を喪ったショックで移動速度が低下するというのはどうでしょうか
会議を挟むごとに立ち直って速度が通常に近づくというのもよさげですね
…覚醒は完全に立ち直ってからの方がいい気がしてきました

**Comment by yukieiji** [comment]
> では、片方が死んだ後は相方を喪ったショックで移動速度が低下するというのはどうでしょうか
会議を挟むごとに立ち直って速度が通常に近づくというのもよさげですね
…覚醒は完全に立ち直ってからの方がいい気がしてきました

デメリットというか片方が落ちても白確証明が出来ているので、それはメリットにしかなってないと思います
時間経過でも無くボタンで解除できるという点でも時間がバラバラかつ、ほぼ任意で解除できるようなデメリットに思えます

**Comment by melonjagaimo** [comment]
では、覚醒云々をなくして片方が死んだ後は永続的に視界が狭くなるのはどうですか？

**Comment by yukieiji** [comment]
> では、覚醒云々をなくして片方が死んだ後は永続的に視界が狭くなるのはどうですか？

配信等の見栄えが著しく悪くなりますがそれはよろしいのでしょうか？

**Comment by melonjagaimo** [comment]
ああしまった、強弱のバランスを考えるあまりそこを見落としてました。
相方の死後、永続的に視界が狭くなる代わりに1度だけ、「発動することで一定時間、視界が広がる能力」を追加することを考えました。
強すぎませんか…？

**Comment by yukieiji** [comment]
> ああしまった、強弱のバランスを考えるあまりそこを見落としてました。
相方の死後、永続的に視界が狭くなる代わりに1度だけ、「発動することで一定時間、視界が広がる能力」を追加することを考えました。
強すぎませんか…？

それはそんなに変わらない気がしますがよろしいでしょうか？

**Comment by melonjagaimo** [comment]
言われてみればそうですね…。強弱のバランスと見栄えはこんなに両立しづらいものだとは……。
しかし相棒を喪って視界が狭くなるのは個人的にはいいデメリットだと思うのです。
となると1人きりになった後に一度だけ何かしらの能力を使えると見栄えが良くなると考えてます。
今、その条件で考えついた効果は
・1度だけキルボタンによるキルを防ぐシールドが自分に付与される（相棒の形見が銃弾を防ぐイメージ）
または
・相方をキルしたプレイヤーが死んだ場合、生きている方のバディーズに通知される
です。どうでしょうか……

**Comment by yukieiji** [comment]
> ・1度だけキルボタンによるキルを防ぐシールドが自分に付与される（相棒の形見が銃弾を防ぐイメージ）
または
・相方をキルしたプレイヤーが死んだ場合、生きている方のバディーズに通知される

視界が狭いから更に追加でメリットを追加するってことでしょうか？
個人的にそれは基本的にラバーズの上位互換であるこの役職にそれを追加するのはどうなのかと思います(実装予定である「探偵」と「助手」は互いにわからないようにはなる予定です)

**Comment by melonjagaimo** [comment]
……よく考えたら元ネタの共有者も地味でした。見栄えが悪くてもお互いを常に把握する代わりに片方死ぬと視界狭くなるだけでいい気がしてきました。
お互い白確出せるのはクルー陣営にとって中々のメリットですし、インポスターやジャッカル陣営はさっさと両方とも噛めば騙りもできそうですし

**Comment by yukieiji** [comment]
視界が狭いのは配信の見栄えって部分もありますし、この役職をプレイしているプレイヤー自身にストレスを与える因子ではないかなーって思ってます

**Comment by melonjagaimo** [comment]
そうですか。それでは視界狭くなるのはまずいですね。
他に、相棒に死なれたデメリットとして考えつくのは…
・相棒が死んだら黙祷して一定時間（10秒程度）動けなくなる
・相棒が死んだ後は、会議後のリスポーン直後に黙祷して一定時間（5秒程度）動けない
・逆に両方とも生きている間だけのメリットをもう一つ用意する

そして両方とも生きている間だけのメリットとしては
・会議開始時最終位置を自動的に相棒に知らせる
・相棒の投票先を把握する

いかがでしょうか？

**Comment by yukieiji** [comment]
> そうですか。それでは視界狭くなるのはまずいですね。
他に、相棒に死なれたデメリットとして考えつくのは…
・相棒が死んだら黙祷して一定時間（10秒程度）動けなくなる
・相棒が死んだ後は、会議後のリスポーン直後に黙祷して一定時間（5秒程度）動けない
・逆に両方とも生きている間だけのメリットをもう一つ用意する
そして両方とも生きている間だけのメリットとしては
・会議開始時最終位置を自動的に相棒に知らせる
・相棒の投票先を把握する
いかがでしょうか？

個人的には能力がなくてもラバーズと近がってこの役職には以下のメリットがあります。これらのメリットは非常に強力なので二人で生きている時にデメリット合ってもいい気がしています
これ以上メリットを追加すると強すぎる気がします
- COするデメリットがない
- COすればほぼ確実に2人白確が取れる
- 片方が落ちてもCOすることで死体の役職の可能性を狭める(死体のクルーが他の役職の可能性を減らす)
- COして一緒に行動すればキル陣営からして絶対に殺すことが出来ない
- キル陣営的にこの役職を殺すメリットがない

**Comment by melonjagaimo** [comment]
ラバーズっぽくなってしまいますが、相棒に一定時間接近していると視界が狭くなる（相棒がキルされても相手が分からないくらいに狭くなる。一定時間生きている相棒と離れると解除される）のはどうですか？

このデメリットを思いついたとき、もう一つ聞きたいことができました。ラバーズの自決する人数を0にする（つまり同じ組のラバーズが1人きりになってもキルボタンを得ず、自決もしない。）設定は可能でしょうか。

**Comment by yukieiji** [comment]
> ラバーズっぽくなってしまいますが、相棒に一定時間接近していると視界が狭くなる（相棒がキルされても相手が分からないくらいに狭くなる。一定時間生きている相棒と離れると解除される）のはどうですか？

サボタージュ等で集まった時に暗くなってしまうのですがそれはそれでいいのでしょうか
また、このデメリットだと一定時間経過する前に離れて、また近づくっていうのようなプレイングをしてデメリットを回避する見たいな使い方ができると思いますがどうでしょうか(行動で白確を証明できるようになってしまう)
出来るかどうかわからないですがこの役職の投票は常に1票だけになるとかでしょうかね(どっちかの投票しか反映されないとか)


> このデメリットを思いついたとき、もう一つ聞きたいことができました。ラバーズの自決する人数を0にする（つまり同じ組のラバーズが1人きりになってもキルボタンを得ず、自決もしない。）設定は可能でしょうか。

現状実装されているラバーズは出来ません
 - プログラムで実装可能か : 出来ます
 - 実装予定：無いです、ラバーズという役職のコンセプト「恋に運命と身を任せる船員」から大きく外れるので

**Comment by melonjagaimo** [comment]
白確定を行動で示してしまいますか、それはまずいですね…。
それに比べてバディーズが片方の投票のみ反映されるのはいい考えですね。
では、バディーズをAとB（仮称）に分けてAが投票するまでBは投票できず、BはAと同じ対象にしか投票できない。というのはいかがですか？

**Comment by yukieiji** [comment]
> その場合バディーズをAとB（仮称）に分けてAは常に投票に参加でき、BはAが生きている限り投票に参加できないという構成になるのですか？

どっちかはランダムにする予定です。けど二人で票合わせればあんまり意味がない気がしてますけどね

**Comment by melonjagaimo** [comment]
投票先が合っても片方が反映されないことによって吊りの可否が変わる可能性があるから問題なさそうに思えます。
それにその仕様なら、バディーズがいるとクルーの総投票数が減り、例えばインポスター陣営が（15人村の場合）残り7人までにバディーズをキルせず3人とも生き残れば、クルーの総投票数は3になり、投票で負けなくなります。
お互いに白確を出せる代わりにPPに弱くなるのは個人的にいい調整だと思います。

**Comment by yukieiji** [comment]
> 投票先が合っても片方が反映されないことによって吊りの可否が変わる可能性があるから問題なさそうに思えます。
それにその仕様なら、バディーズがいるとクルーの総投票数が減り、例えばインポスター陣営が（15人村の場合）残り7人までにバディーズをキルせず3人とも生き残れば、クルーの総投票数は3になり、投票で負けなくなります。
お互いに白確を出せる代わりにPPに弱くなるのは個人的にいい調整だと思います。

推理を2人で合わせてしまえばそんなに強いくはないかなーって思います。推理自体も会議の主導役が2人になりやすくなるのでクリアにはなりやすいと思います(1人ではドツボでハマるような内容を相方とすり合わせできるってのが強みになる。しすて片方の投票がなかったとしても、2人で議論を手動すればクルーの民意を合わせやすい気がします)
そう考えるとバディーズの投票券も要らない気はしますね

**Comment by melonjagaimo** [comment]
では、投票権の有無を設定で変更できるというのはどうですか？
バディーズ2人合計で0〜2票といった感じで。

個人的には最初の会議で片方だけCOして相方を潜伏させて、吊られそうになったらもう片方もCOして回避する戦法もとれそうだなと考えてます

**Comment by yukieiji** [comment]
> では、投票権の有無を設定で変更できるというのはどうですか？
バディーズ2人合計で0〜2票といった感じで。

消すなら消す、消さないなら消さないの方が楽です(第一実装できるかどうかもわからないですし)
アサシン見たく会議全体に影響を与えるなら楽なんですが、出来るできないが入り交じると複雑になります

**Comment by melonjagaimo** [comment]
これまでの話を総合すると…
・お互い、会議中でも相方を把握する
・ラバーズと異なり、相方に死なれても後追いしない
・ただし投票権を持たない（実装可能かは不透明）
ですかね。

投票権をなくす（減らす）機能が実装できなかった場合、別のデメリット能力として考えたのは、両方とも生きている間は緊急会議ボタンを押せない（死体通報は可能）ですね。どうでしょうか…？

もしも投票権をなくす・減らす機能が実装できたならば、増やす方も面白くなりそうですね（PP回避に有効な代わりにその役職のプレイヤーを騙せば強引に吊り誘導させられるような役職の実装）

**Comment by yukieiji** [comment]
> 投票権をなくす（減らす）機能が実装できなかった場合、別のデメリット能力として考えたのは、両方とも生きている間は緊急会議ボタンを押せない（死体通報は可能）ですね。どうでしょうか…？

デメリットとしてはそんなに強くはないと思うので追加でなにか欲しい気がします

> もしも投票権をなくす・減らす機能が実装できたならば、増やす方も面白くなりそうですね（PP回避に有効な代わりにその役職のプレイヤーを騙せば強引に吊り誘導させられるような役職の実装）

それはただの強化メイヤーと変わらないので実装はしません

**Comment by melonjagaimo** [comment]
両方とも生きている間は緊急タスクの修復もできなくする、のはどうですかね

**Comment by yukieiji** [comment]
> 両方とも生きている間は緊急タスクの修復もできなくする、のはどうですかね

緊急タスクもボタンが使えないってのはCOしてしまえば困る状態に陥ることは稀だと思います(最終盤面で2人生き残ってるとかなら問題がある気がしますがそこまで生きるのは結構稀はなず？それをケアするって部分で必ずこの役職を一人吊り押すって事態も発生しそうですね)

**Comment by melonjagaimo** [comment]
死ぬと死んだバディーズ自身のタスク進捗が一部または全部リセットされる（完了したタスクの一部または全部を、同じカテゴリの未完了タスクに置き換える）のはどうですか？

初手COしたバディーズを中盤〜終盤にキルすることでタスクをリセットしてタスク勝ちを阻止できます。

**Comment by yukieiji** [comment]
> 死ぬと死んだバディーズ自身のタスク進捗が一部または全部リセットされる（完了したタスクの一部または全部を、同じカテゴリの未完了タスクに置き換える）のはどうですか？

試合のテンポが悪くなるという点と吊ったらその人がバディーズだと完全にわかるのはいいのでしょうか
よくよく考えるとあと片方が落ちた時になにかする系は片方をSKしたときの処理を考えないといけないですね

**Comment by melonjagaimo** [comment]
それではいけませんね。
……そろそろ素人のオレではいい案が浮かばなくなってきました。

**Comment by yukieiji** [comment]
バディーズのメリット
 - 確定で2人作れる
 - 2人1組で行動すれば確実に殺せない
この2つが強力すぎるので釣り合うようなデメリットが投票権をなくす位しか無い気がします
私が浮かぶ能力ボタンがないクルーのデメリットは以下の感じです、基本的に上の方が重め
- 自分、民意以外の意思で死ぬ(情報を残せずに死ぬ)
- 投票券がない
- (ここに大きな壁がある気がする)
- セキュ使えない or バイタル使えない
- アドミン使えない
- (ここに大きな壁がある気がする)
- タスクを終わらせる
- サボタージュ治せない
- ボタン押せない
- 自分や民意の意思で死ぬ(情報を残して死ねる)

**Comment by melonjagaimo** [comment]
個人的にはこの中なら死体通報ができない、をそのままか
・死体の一定範囲内に5秒程度滞在しないと通報できない
がいいと思います。

**Comment by yukieiji** [comment]
「通報できない」ってのも単に上げただけで、現EXロールの実装段階では無効にしたことがないので出来るかどうかもわからないですけどね(本家TORで通報を無効化するってのが合ったから出来るとは思うけどEXロールでやったことはないです)

**Comment by melonjagaimo** [comment]
この状態、と言いますと
・ラバーズのようにお互い相方を把握し、片方が死んでも後追いしない
・ただし投票権を持たない
でよろしいですか？

**Comment by yukieiji** [comment]
> この状態、と言いますと
・ラバーズのようにお互い相方を把握し、片方が死んでも後追いしない
・ただし投票権を持たない
でよろしいですか？

そうです、その投票が実装できなかったら通報できなくする形です

**Comment by melonjagaimo** [comment]
分かりました。よろしくお願いします。

**Comment by yukieiji** [comment]
> 分かりました。よろしくお願いします。

優先度「低」でラベル設定させていただきます

**Comment by melonjagaimo** [comment]
改善案を思いつきました。
・最初は2人ともクルーとしてアサインされ、タスクを一定数こなさないと自分がバディーズであると把握できない。
片方が覚醒すると覚醒した方は相方を把握できる。ただし覚醒してない方は自分も覚醒しないと相方を把握できない。

**Comment by yukieiji** [comment]
> タスクを一定量こなすと自分がバディーズであること、そして相方が誰なのかを把握できる。

これ自分のタスクだけでしょうか？

**Comment by melonjagaimo** [comment]
現状は
・自分のタスクを一定量こなすと自分がバディーズになり、相方（バディーズに覚醒しているかは問わず）を一方的に把握する
のように考えています。

・バディーズ2人ともの合計進捗が一定の割合を達成すると同時に覚醒する
の方がいいのでしょうか。

**Comment by yukieiji** [comment]
> ・自分のタスクを一定量こなすと自分がバディーズになり、相方（バディーズに覚醒しているかは問わず）を一方的に把握する
のように考えています。

そうするとタスク進捗が早い人が先に気づいて一方的にラインがつなげるのが問題かなって思います(インポスターと同じく同時にラインがつなげてないので、もう片方が覚醒すると簡単に白確が出来る(AとBがいてAが先に覚醒してBにラインをつなげてAが覚醒するとAとBがほぼ白確になる(サポーターの上位互換的なものになってる気がします)))

> ・バディーズ2人ともの合計進捗が一定の割合を達成すると同時に覚醒する

個人的にはそれがいいと思ってます

**Comment by melonjagaimo** [comment]
分かりました。
それにより決めたいことができました。

・例えばオプションでバディーズ覚醒に必要な合計進捗を50%とした場合に「バディーズA進捗100%:バディーズB進捗0%でも覚醒すること」を良しとするか。
→自分としてはナシ。それぞれの個人進捗もある程度必要にしたい。
例:バディーズABそれぞれ50%以上、2人合計80%で覚醒するようにする

**Comment by yukieiji** [comment]
> ・例えばオプションでバディーズ覚醒に必要な合計進捗を50%とした場合に「バディーズA進捗100%:バディーズB進捗0%でも覚醒すること」を良しとするか。
→自分としてはナシ。それぞれの個人進捗もある程度必要にしたい。
例:バディーズABそれぞれ50%以上、2人合計80%で覚醒するようにする

普通に両方の進捗率がそれぞれ一定値以上で覚醒でいいのではないのでしょうか？

**Comment by melonjagaimo** [comment]
それぞれの進捗で覚醒となると
例えば覚醒に必要な進捗を75%と設定した場合
バディーズ予定クルーAが自分のタスクを75％完了すると自分がバディーズであることと相方がBであることを把握する
一方バディーズ予定クルー Bも75%タスクを完了すると自分がバディーズであることと相方がAであることを把握する

という感じになりますね。

**Comment by melonjagaimo** [comment]
おっと、そうでしたか。
それで行きましょう。

**Comment by yukieiji** [comment]
一個決め忘れてたことがありました

タスク覚醒役職にするとこの役職はコンビ役職でありながら別役職の能力を持つことができなくなりますがよろしいでしょうか？

**Comment by melonjagaimo** [comment]
オレとしてはそれでいい（バディーズになる予定のクルーは、他のクルー陣営役職とは重複しない）と思っております。

**Comment by yukieiji** [comment]
> オレとしてはそれでいい（バディーズになる予定のクルーは、他のクルー陣営役職とは重複しない）と思っております。

基本的にはコンビ役職は他の役職を持つ可能性がある設定が全部付いてるのです

覚醒時にその役職も追加付与みたいな形にしてもいいかなって思いましたけど色々とめんどいと感じました

**Comment by melonjagaimo** [comment]
それもありますし、
・「お互いに相方を白確定できる」のがこの役職のメリットとなので他の役職も持つと強すぎるように思う

・逆に言えば、バディーズとして覚醒するまでその役職も封印されるので、最初は実質クルー陣営役職が2つまで欠けることになる。役職が多いルールだとこれはかなり痛いように考えられる

点から、オレはバディーズは「コンビ役職でありながら他の役職との重複を許さない」ことにしようと考えています。
