### ISSUE TITLE
イエティ:インポスター役職

### ISSUE THREAD

**Issue by Nushigami** [yukieiji/ExtremeRoles#4]
### 役職名 / Role Name
イエティ

### 役職の色 / Role color
※インポスター役職

### 役職の説明 / Role description
**クルーを凍らせて殺すインポスター陣営の役職**
 - 勝利条件:インポスター陣営の勝利条件
 - プレイヤーを凍らせることができる。
 →能力の内容は"役職の能力"にて

### 役職の能力 / Role ability

- 凍らせる
→対象のプレイヤーを凍らせる。
(プレイヤーを凍らせる度、設定された秒数クールタイムが伸びる。)
※キルボタンのクールタイムと同期させるかは要検討

- 凍ったプレイヤー
  - 動けない。
  - キルボタンと能力ボタンを押せない。
  - 死体の通報や、緊急会議ボタンを押すことができない。
  - 条件を満たすと死ぬ。
    - 凍ってから設定された秒数(初期設定12秒)が経つ。
    - 会議がおこなわれる。
    - インポスター陣営以外の全てプレイヤーが凍る。

- 凍ったプレイヤーを助ける方法
  - イエティ以外の設定された人数(初手設定2人)の凍っていないプレイヤーが凍ったプレイヤーに密接する。
  - そのプレイヤーを凍らせたイエティをキルする。

- 能力のメリット・デメリット
(今までこういう能力がなかった為、憶測ですが)
- `メリット`
  - 凍らせた時とキルが別タイミングなので自分のキルだとバレにくい。

- `デメリット`
  - 凍らせたプレイヤーに自分がインポスター陣営だとバレる。(サボタージュ等で軽減できる。)

### 他陣営への影響 / Effect on other teams
多人数でいることが増える

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 誰が凍らせたか人目でわかるので、助けることができれば一発でバレることがリスクですかね。

クルーからしたら能力を使ってる(ウォッチドッグ等)のか凍ってるのか判断できないのではないでしょうか

**Comment by Nushigami** [comment]
名前で判別することって可能なんでしょうか?
(まぁ触れば溶けるので関係ないと思いますが)

**Comment by Nushigami** [comment]
項目１について
名前の色を変えたりするとかアイコンを出すとかですかね
項目２について
はい ずっと近くにいる場合だと凍ったプレイヤーでの籠りが強いと思ったので、、、(凍ったプレイヤーの近くでは凍らせる能力が使えないでもいいが)

**Comment by yukieiji** [comment]
> スキルのクールは早めでキルクが遅めっていう運用を目的としてます。
ちなみにバレるのはしょうがないです。リスクです。

多分それだとTORの魔女見たく普通にキルしたほうが良いってなりませんか

**Comment by Nushigami** [comment]
そう、、、かなぁ?
バレるリスクも停電中に使用することでカバー出来ますし、凍っている秒数もそれほど長くする訳じゃないから、スキルのクールを普通のインポのキルクールより早めればいいわけだし、、、(バレないようにするわけじゃなくてキルペースをあげるためかな)

**Comment by yukieiji** [comment]
どちらかというとメリットに対してのデメリットやコストが多すぎるってことですね
メリット：
1.キルクールを空けずに殺せる
デメリット：
1.  クルーに一瞬で解除される
2.  解除されると即バレする
3.  サボタージ等をつかわないとバレるけど、人が集まるから使っても意味ない

**Comment by Nushigami** [comment]
、、、確かに(キルクールの半分くらいを想定してたがその時点であれか、、、)
停電中は密接しないと溶けない仕様のつもりなので可能だと思いますが、、、解除できるまでの秒数追加しますか、、、

**Comment by yukieiji** [comment]
どちらにせよ解除されるとインポスターが即バレするってのが私にとってはデメリットが大きすぎる気がします

エボルバーやオーバーローダーはバレるの覚悟で莫大なメリット(キルクールが永久減少やキルクール減少率75％等)が手に入ることでバランスは取ってますが、このイエティだと1人しか持っていけない、それも解除されたり会議が挟まると全くの無意味になってしまうので・・・

**Comment by Nushigami** [comment]
会議が挟まった場合はその時点で死ぬので、、、
なんかメリットを大きくするような何かが必要ですかね、、、(例えば近くにいる人を全員凍らせるとか)

**Comment by Nushigami** [comment]
ローダーみたいな速さでの能力使用スピードだとそれこそローダーで良くないかってなりますもんね

**Comment by yukieiji** [comment]
> 会議が挟まった場合はその時点で死ぬので、、、

会議が挟まるとどうなるかは書いてなかったのでリセットされる物だと思いました

**Comment by Nushigami** [comment]
能力説明の５行目の通報がなった時ですね、、、会議って書けばよかった

**Comment by Nushigami** [comment]
解除されたら即バレのリスクをどうにか軽減しないといけないんだか、、、能力を使ってから凍るまでにタイムラグをつけるとか、溶かすのに人数がいるとかしか思いつかないですね、、、

**Comment by Nushigami** [comment]
> 溶かすのに人数がいるのはいいとは思いますけどね、最終盤面だと強いのでそこでバランス調整しないといけない気がします

例えば1人でも溶かせるが時間がかかるとか、凍らせる度にクールタイムを追加するとかですかね。

**Comment by Nushigami** [comment]
最初のissuesを書き直しました。
また、少し能力の設定を変えました。

**Comment by Nushigami** [comment]
最初のissuesの話し合いで変更した部分を書き換えました。
また、凍らせたときのクールタイムの増加を追加しました。

**Comment by Nushigami** [comment]
｢凍らせる｣のクールタイムをキルクールと同期させない場合、キルした後に来た人を凍らせるというプレイングができるんですよね

**Comment by yukieiji** [comment]
返信がだいぶ遅れました
別のキルボタンをもつスマッシャーが実装されたため、この役職にはスマッシャーに無いメリットがほしい感じにはなりました

> ｢凍らせる｣のクールタイムをキルクールと同期させない場合、キルした後に来た人を凍らせるというプレイングができるんですよね

同期させない場合は本当にスマッシャーで良くないかとなりそうです
なので基本的には同期させないようにする方がいいと思います

**Comment by Nushigami** [comment]
>別のキルボタンをもつスマッシャーが実装されたため、この役職にはスマッシャーに無いメリットがほしい感じにはなりました

キルタイミングのタイミングがずれることが強みですかね。

> 同期させない場合は本当にスマッシャーで良くないかとなりそうです
なので基本的には同期させないようにする方がいいと思います

自分も同期させた方がいいと思います。
(まぁこちらはすぐキルできないかわりに複数回できてキルクールも増えない点で差別化できてなくはないと思いますが)

**Comment by yukieiji** [comment]
> キルタイミングのタイミングがずれることが強みですかね。

タイミングがズレてしまうからインポスター即バレしてしまうって点デメリットが強すぎる気がしますね
デメリットでメリットが潰れてる気がします(魔女と同じく能力を使わずにキルしたほうがバレない可能性が高い)

**Comment by Nushigami** [comment]
> タイミングがズレてしまうからインポスター即バレしてしまうって点デメリットが強すぎる気がしますね

自分とは違う場所でキルがおきるから他の人に即バレすることは少ないと思っています。
確かに凍らせた人には即バレしますが、自分的に凍った人が助かることがそこまでないと思っているので関係ないですかね

> デメリットでメリットが潰れてる気がします(魔女と同じく能力を使わずにキルしたほうがバレない可能性が高い)

TORの魔女はどの盤面で能力を使っても弱いですが、イエティは残り人数が少なくなっている状況や広いマップでは強いと思っています。
(エアシップやポーラスは広いですし、スケルドはが自らでは開かないドアなのでサボ等活用すればなんとか。ミラHQは知らん)

**Comment by yukieiji** [comment]
> 自分とは違う場所でキルがおきるから他の人に即バレすることは少ないと思っています。
確かに凍らせた人には即バレしますが、自分的に凍った人が助かることがそこまでないと思っているので関係ないですかね

助かることがない理由は何でしょうか

> TORの魔女はどの盤面で能力を使っても弱いですが、イエティは残り人数が少なくなっている状況や広いマップでは強いと思っています。
(エアシップやポーラスは広いですし、スケルドはが自らでは開かないドアなのでサボ等活用すればなんとか。ミラHQは知らん)

初期盤面で使えないって点が問題だと思ってます
広いマップだと人数が多いので最初で能力を使って人数を減らさないとインポスター的に辛くなると思います

**Comment by Nushigami** [comment]
> 助かることがない理由は何でしょうか

ドア閉めやサボタージュ等で簡単に凍死までの時間を稼げるからです。
また、助けるためにはプレイヤー2人必要で1人が見つけても助からないということもあるからです。

> 初期盤面で使えないって点が問題だと思ってます
広いマップだと人数が多いので最初で能力を使って人数を減らさないとインポスター的に辛くなると思います

 初手は人数多いため能力を使っても次のクールまでに見つかると思います。
またこの能力は使う度クールタイムが伸びるため自分的には後半で巻き返す役職だと思っています。
(通常キルを行ってもデメリットがないので)

**Comment by yukieiji** [comment]
> ドア閉めやサボタージュ等で簡単に凍死までの時間を稼げるからです。
また、助けるためにはプレイヤー2人必要で1人が見つけても助からないということもあるからです。

ドア閉めやサボタージュのことを頭から抜けていました
これを考えると解凍に2人かかるという時点で強すぎる気がします
逆に1人だとだと早く解凍できすぎてバレてしまう

> 初手は人数多いため能力を使っても次のクールまでに見つかると思います。
またこの能力は使う度クールタイムが伸びるため自分的には後半で巻き返す役職だと思っています。
(通常キルを行ってもデメリットがないので)

最初のほうでキルできない(人数を減らせない)ってなると能力は使えず、その状況はいつまで経っても改善しない気がします

これは完全な私見なのですがもしこのまま実装してもTORの魔女と同じような結果になると思います(気に入らない、そんなことはないと思うのであれば無視していただいて構いません)
以下理由です
- 魔女とこの役職が似ている部分(メリットのバレなければ複数人持っていけるってのとデメリットのバレると即吊りなど)が多い
  - TORの魔女
    - メリット
      - 呪いをつけると何人でも持っていける(このメリットはイエティ似てる)
      - 人数が多ければ隠れやすい人数が少なければ相互視認が取れないのでバレなければ強い
    - デメリット
      - すれ違った人を覚えるだけでほぼ確実吊れる
      - 魔女が落ちたってわかる(インポスター)だと即バレしてしまう(ここが大きい)
      - 使えば使うほど普通のキルが出来ない
    - このデメリットをどうにかして解決しようとするとインポスターだと強すぎるからどうしようもない
      - 結果=>能力に関して強化も弱体化も出来ず通常キルの方が良いのでは？となる
  - イエティ
    - メリット
      - バレなければ複数人持っていける(このメリットは魔女と似ている) 
      - 人数が少なければ確実に能力が通る
    - デメリット
      - 凍ってる人を解凍してしまえば即視認からバレて、確実にインポスターを吊れる(ここが大きい)
      - 人が多いと能力使えない
     - 解凍のデメリットを解消しようとすると強いし、解消出来なければ弱い
     - 能力を使うためには人を減らす必要があるけど、人を減らす力がイエティない(あるけど使うとバレる) => キルをすると吊られるリスク↑ =>能力を使えずに不発になる可能性が多い => 能力を使わずキルをしたほうがいいのでは？(人数が減ってもキルしたほうが目撃視認等を消せるので)

**Comment by Nushigami** [comment]
> ドア閉めやサボタージュのことを頭から抜けていましたこれを考えると解凍に2人かかるという時点で強すぎる気がします
逆に1人だとだと早く解凍できすぎてバレてしまう

バレるリスクをどうするかですね
(タスク中や停電時は視認バレのリスクが少なくなりますが)

**Comment by yukieiji** [comment]
> バレるリスクをどうするかですね
(タスク中や停電時は視認バレのリスクが少なくなりますが)

この能力のままだとどうしてもバレる問題を解決することは難しいと思います

**Comment by Nushigami** [comment]
いい改善案が思い浮かばないのでこのissueはcloseします
