### ISSUE TITLE
ローグ(乱暴者):インポスター役職

### ISSUE THREAD

**Issue by Nushigami** [yukieiji/ExtremeRoles#40]
### 役職名 / Role Name
ローグ(乱暴者)

### 役職の色 / Role color
※インポスター役職

### 役職の説明 / Role description
- **_機械を壊して使えなくさせるインポスター役職_**
  - 能力「壊す」で近くのアドミン・バイタル・カメラ・ドアログ・緊急招集ボタンを一定時間全てプレイヤーが使えなくなる。
 
### 役職の能力 / Role ability

- 能力「壊す」
→能力を使用した時、近くのアドミン・バイタル・カメラ・ドアログ・緊急招集ボタンを設定した時間、全プレイヤーが使用できなくなる。
能力を使用する度、能力のクールタイムが伸び、再びキルのクールタイムが始まる。

 ※ ただしスーパーバイザーなどの能力でアドミン等は使用でき、メンテナーの能力「リペア」を使用すると即座に使用できるようになる。

- `能力のメリット`
   - アドミン等で得られる情報が少なくなる。
   - 緊急招集ボタンを押せなくするため、ボタンを押されるとまずい場面で役に立つ

- `能力のデメリット`
  - 他プレイヤーの近くで能力を使用するとバレる恐れがある。
  - 能力を使用するとキルクールタイムが再び始まるのでキルペースが落ちる。

- `能力の設定`
  - 能力のクールタイム
    - デフォルトでは30秒
  - 能力を使用した後のクールタイム増加秒数
    - デフォルトでは2.5秒
  - キルクールと共有するか
    - デフォルトではON
  - アドミン等使用できなくなる距離
      - デフォルトでキル範囲ショートくらい
  - アドミン等を使用できなくさせる時間。
    - デフォルトでは120秒
  - メンテナーの「リペア」で即座にアドミン等を使用できるようにするか。
    - デフォルトではON
  - 緊急招集ボタンを使えなくさせるか。
    - デフォルトではON
 
### 他陣営への影響 / Effect on other teams
アドミンやバイタル等が使用できなくなるため、議論等が難しくなる。

### 陣営 / Team
- [ ] :クルー/Crewmate
- [X] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
この能力の使用できなくなるってのはニート等のアクセス権限を失うことでしょうか？それとも使用ボタン自体を封じるということでしょうか？

**Comment by Nushigami** [comment]
使用ボタンが消えるって感じですかね
(機械自体を対象に取る能力のつもり)

**Comment by yukieiji** [comment]
> 使用ボタンが消えるって感じですかね
(機械自体を対象に取る能力のつもり)

やったことがないので時間はかかりますがよろしいでしょうか？

**Comment by Nushigami** [comment]
わかりました よろしくお願いしますm(_ _)m

**Comment by yukieiji** [comment]
かなり返信が送れました
アドミン等の制限実装時に使用ボタンすら見えなくすることには成功しましたが制限がついてたり、無効化されているとするとこの役職自体の意味が内容に思えますがどうでしょうか

**Comment by Nushigami** [comment]
返答遅れました。
この能力で無効化できるもの全て無効化した場合、この役職が無意味になるのは能力上仕方ないと思います。
(この役職をアサインさせなければいいだけの話ですが、)
ただルールで先天性に使えなくさせるのと、能力で後天的に使えなくさせるのとでは難易度的な違いがあると思います。
能力で使えなくさせる場合、能力を使う前や元に戻った後は使えるので、縛り的に緩いです。
またルールでの縛りやコミュサボと違いそこに行くまで使えないかどうか分からないので無駄足にさせることさえあります。
(コミュサボと違い、能力+他サボなど使える代わりにその場所に行かなくてはならないという差別化点があります)

話は変わりますけどキルクール共有なくていい気がします。
コミュサボ後即キルできるため、コミュサボと違ってその場にいかないといけないかつクールが延びるこの能力が共有あった場合弱いと感じたからです。

**Comment by yukieiji** [comment]
> この能力で無効化できるもの全て無効化した場合、この役職が無意味になるのは能力上仕方ないと思います。
(この役職をアサインさせなければいいだけの話ですが、)
ただルールで先天性に使えなくさせるのと、能力で後天的に使えなくさせるのとでは難易度的な違いがあると思います。
能力で使えなくさせる場合、能力を使う前や元に戻った後は使えるので、縛り的に緩いです。

いや最初からの制限もそうですけど、時間制限もつけれるようになったExRでこの役職が必要かなってのが疑問点ですね
この役職を入れたいってなった時の需要とすればマップオブジェクトに対して何らかの制限を加えたいってときだと思います。その場合であれば時間制限で十分ではないかなって思います

> またルールでの縛りやコミュサボと違いそこに行くまで使えないかどうか分からないので無駄足にさせることさえあります。
(コミュサボと違い、能力+他サボなど使える代わりにその場所に行かなくてはならないという差別化点があります)

それはどっちかというと弱くなってませんか・・・？
サボを使うと治しにいかないと治らないってデメリット(そこにいるとキルされる可能性が増えるけどメリットととして治った瞬間にすぐ使える)がありますけど、この能力の場合治さなくてもいい => 使えなかったら待機して治るのを待つ(デフォルト120秒ってありますけどそこまでするなら時間制限の方がいいですし、逆に短かったら治るのが待機ってなるような気がします)

**Comment by Nushigami** [comment]
> この役職を入れたいってなった時の需要とすればマップオブジェクトに対して何らかの制限を加えたいってときだと思います。その場合であれば時間制限で十分ではないかなって思います

縛りって面で見ればそうかもしれませんが、妨害という点ではそうとは限らないと思います。
アドミン等普通に使用できるようにしたいが妨害もしたいという時はこちらが採用されますし、能力＋別サボという使い方もできるためコミュニティサボタージュでいいとはならないと思います。

> この能力の場合治さなくてもいい => 使えなかったら待機して治るのを待つ(デフォルト120秒ってありますけどそこまでするなら時間制限の方がいいですし、逆に短かったら治るのが待機ってなるような気がします)

確かに待機すればいいだけですが、その時すぐに使用できないことには変わりませんし、いつ直るかだってわかりません｡(その場待機の場合はその間タスクができなかったり浮いてキルされたり、また戻るにしても、無駄足させた時点で機能してると思います｡)
またコミュニティサボタージュはすぐに直されてしまう可能性だってあります｡

**Comment by yukieiji** [comment]
> アドミン等普通に使用できるようにしたいが妨害もしたいという時はこちらが採用されますし、能力＋別サボという使い方もできるためコミュニティサボタージュでいいとはならないと思います。

この役職が別サボとして機能するかと言われれば違う気がします
サボタージュの目的は妨害以外に人払いや足止めという役割がありますが、ここで提案されているものは足止めにも人払いにもなってないと思います

> 確かに待機すればいいだけですが、その時すぐに使用できないことには変わりませんし、いつ直るかだってわかりません｡(その場待機の場合はその間タスクができなかったり浮いてキルされたり、また戻るにしても、無駄足させた時点で機能してると思います｡)
またコミュニティサボタージュはすぐに直されてしまう可能性だってあります｡

人が一箇所に集まるようなコミュサボと違って個人的に浮くことがないんじゃないんですかね
コミュサボは人が一箇所に集まる + 注目が行くという部分で行かなければ浮くんですが、提案されいるものは注目も行かなければ集まるようなこともないので浮いているときはもとから浮いているという状況になる気がします(コミュサボは「使えない」=>「治さなきゃ」 => 「治しに行く or 待つ」がありますけど「使えない」=>「あっそっか」ここで終わる、何なら仕様ボタンすら光らないので1秒も無駄足にできているのかってのもあります)

あと基本的にすぐ使用したいって時がどれくらいあるかって言われるとそこまで無いような気がします。そういった場合は基本的に待機でいいと思います(上で書いてましたが待機秒数が長すぎると時間制限でいいじゃん、短すぎると意味をなしてないってのがこのことです)

**Comment by Nushigami** [comment]
> この役職が別サボとして機能するかと言われれば違う気がします

ここでは別サボと併用して使える点で言ってます。
コミュサボタ中はほかのサボタージュは使えませんが、この能力はほかのサボタージュを使いながらアドミン等を使えなくすることができます。

> 人が一箇所に集まるようなコミュサボと違って個人的に浮くことがないんじゃないんですかね
コミュサボは人が一箇所に集まる + 注目が行くという部分で行かなければ浮くんですが、提案されいるものは注目も行かなければ集まるようなこともないので浮いているときはもとから浮いているという状況になる気がします

そう言われたらそうかもしれないと言わざるおえないですが、この能力は浮かせることが目的ではないので、

> コミュサボは「使えない」=>「治さなきゃ」 => 「治しに行く or 待つ」がありますけど「使えない」=>「あっそっか」ここで終わる、何なら使用ボタンすら光らないので1秒も無駄足にできているのかってのもあります

コミュサボ中はわざわざ行かなくても使えないってことが分かりますがこの能力は使えるかどうか行かなければ分からないのでそれを使うために移動して使えないとなったら無駄足になるのではないでしょうか?

> あと基本的にすぐ使用したいって時がどれくらいあるかって言われるとそこまで無いような気がします。そういった場合は基本的に待機でいいと思います

その時点で得られるはずだった情報がなくなることは結構な痛手になると思います。

> 上で書いてましたが待機秒数が長すぎると時間制限でいいじゃん、短すぎると意味をなしてないってのがこのことです

時間制限あるにしても情報が見れることには変わりませんし、使えなくするにしてもこの役職がいなくなったら問題なく使えるようになるのでそれでいいじゃんってことはないはずです。

**Comment by yukieiji** [comment]
> ここでは別サボと併用して使える点で言ってます。
コミュサボ中はほかのサボタージュは使えませんが、この能力はほかのサボタージュを使いながらアドミン等を使えなくすることができます。

併用して使えるメリット自体が無い気がするのですがどうなんですかね

> そう言われたらそうかもしれないと言わざるおえないですが、この能力は浮かせることが目的ではないので、

じゃあどういう目的がこの能力なんですか

> コミュサボ中はわざわざ行かなくても使えないってことが分かりますがこの能力は使えるかどうか行かなければ分からないのでそれを使うために移動して使えないとなったら無駄足になるのではないでしょうか?

無駄足にさせたところでせいぜい1秒程度しか稼げてないってのが問題じゃないんですかね

> その時点で得られるはずだった情報がなくなることは結構な痛手になると思います。
時間制限あるにしても情報が見れることには変わりませんし、使えなくするにしてもこの役職がいなくなったら問題なく使えるようになるのでそれでいいじゃんってことはないはずです。

平均して1ゲーム15分の内30秒も使わないようなそれらのマップモジュールに対して、それ以上の制限を加える意味が有るのかってのが私の中の根本的な疑問です。その上でプレイヤーがいつマップモジュールにアクセスしてるか分からないのにその情報を追加で封殺する必要性があるのか(30秒も使わないようなものを追加で握りつぶすなら無効化すべきではって話です)

**Comment by Nushigami** [comment]
最近忙しくてこちらを見てまおりせんでした。
この先、こちらに時間取れそうないので、こちらはクローズのままにしときます。
