### ISSUE TITLE
【クルー陣営】敵の死を知らせよう「ミーディアム」

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#42]
### 役職名 / Role Name
ミーディアム

### 役職の色 / Role color
白っぽい灰色

### 役職の説明 / Role description
本家人狼で言うところの霊能者・霊媒師
インポスターたちが死んだことを知れる

#### パッシブ能力
会議での追放や他の陣営のキルなどによってインポスター陣営のプレイヤーが死んだ場合は、次の会議開始時にミーディアム本人にのみ通知が入る。死因は追放・死亡の2種類で区別できる。
ただし役職まではわからず、インポスターがサイドキックになった場合は通知されない（インポスターがサイドキックになってすぐに死んだ場合はニュートラル陣営の死として扱う）
例：「前の会議でインポスターが追放された」「この会議開始までにインポスターが死亡した」
また、複数人一気に死んでも通知内容は変化しないが追放と死亡が同時に起きた場合それぞれ通知される

設定変更によりニュートラル陣営のプレイヤーの死に対しても通知が入る（この場合も役職まで把握できない）
インポスター陣営とニュートラル陣営のプレイヤーの死が同時に通知されることもある

#### アクティブ能力
なし

#### 能力のメリット
クルーたちはインポスターやニュートラルを追放できたことを知れるので推理が円滑になり、発言内容からのさらなる推理につながる

#### 能力のデメリット
ミーディアム本人が白証明する手段はないので他の陣営が騙りをすることができる
伝えた情報を敵に利用されることもある

### 他陣営への影響 / Effect on other teams
インポスター陣営・ニュートラル陣営：人数減少がバレるが、騙りができたり全滅させないといけない相手陣営の減少を知る手掛かりにもなる

### 陣営 / Team
- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> ミーディアム本人が白証明する手段はないので他の陣営が騙りをすることができる
伝えた情報を敵に利用されることもある

COしてしまえば基本的にもう白確定と言えるでしょう
騙りをしたらローラーすればいいので騙りは基本的にデメリットではないです(黒を確実に吊れるのでメリットとしても取れるでしょう)

デメリットなして落ちた赤がほぼ確実に分かる時点で霊能や霊媒より遥かに強力です、デメリットをつけてもバランスを取ることは難しいと思います

**Comment by melonjagaimo** [comment]
証明する手段が（他プレイヤー視点で）ない以上COの信憑性はあまり高くないと考えての判断でした。
これ以上の案が浮かばないのでクローズします。
