### ISSUE TITLE
【タスクで職を得るクルー】[クルー陣営] : ワーカホリック

### ISSUE THREAD

**Issue by hijiki55** [yukieiji/ExtremeRoles#49]
### 役職名 / Role Name
ワーカホリック
(別名候補)ラーナー/トレイニー/アシスタント/見習い
### 役職の色 / Role color
白
### 役職の説明 / Role description
タスク完了でランダムな役職に変化する。アサイン時、フラグを立てた上で素クルーとして潜伏する。
### 役職の能力 / Role ability

 - オプションにより、《ワーカホリック》がアサインされたとき、自身に潜伏フラグを立てた上で役職を《クルー》に変更する。この《クルー》プレイヤーは、自分が《ワーカホリック》候補であることが分からない。
 - 会議の終了時、《ワーカホリック》か潜伏フラグを立てられた《クルー》が生存し、かつ設定割合のタスクを完了しているなら、その役職をオプションの重み付けに応じた確率で変更する。
    - 例えば、重み付けがA職=2 / B職=1 / C職=1である場合、それぞれ50% / 25% / 25%の確率で変更する。
    - 候補が存在しない場合、潜伏《クルー》は《ワーカホリック》になる。
    - オプションにより、覚醒に必要なタスク率をゲームの進行度に伴って減少、または増加させる。この進行度は、プレイヤーの生存人数によって0%～100%になる。
      - この方法で必要なタスク率を軽減すると、タスク遂行能力の差異が薄まり、ゲームの進行に沿った覚醒が発生するようになる。
    - オプションにより、複数の《ワーカホリック》or潜伏《クルー》から重複した役職に変更されなくなる。
### 他陣営への影響 / Effect on other teams
白役職の存在が曖昧になり、人外陣営はタスク偽装の有効性が上がる。COパワーを下げつつ配分される役職を増やすことができる。
### 陣営 / Team
- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

少し前に話題になっていたので素クルーからタスク完了で職を得る役職を。
白役職の一部に変化するだけでも機能すると思われます。

**Comment by yukieiji** [comment]
元々設定されて役職がアサインされるものと違って、その役職が必ずアサインされる訳ではないという点と元々設定している役職数を突破して新しい役職が生まれるので、バランス観点的にワーカホリックで付与される役職がどれであるかはとても重要ですがどのようなクルー役職をアサイン予定ですか？

**Comment by hijiki55** [comment]
> 元々設定されて役職がアサインされるものと違って、その役職が必ずアサインされる訳ではないという点と元々設定している役職数を突破して新しい役職が生まれるので、バランス観点的にワーカホリックで付与される役職がどれであるかはとても重要ですがどのようなクルー役職をアサイン予定ですか？

タスクでボーナスを得る系の役職とリソースを食い合う、単純に実働時間が少ないなど、転職先は通常と異なるオプションバランスを調整する前提になるため、初期アサインと役職を重複させるのは非推奨になると個人的には考えています
ここの個別調整が過剰に柔軟というか、どこに落とし込むかでホスト側が悩むことになりそうなのはあります

以下、私見で順位を付けた表です

 - 押し度　大
   - シェリフ　黒を当てても信用度が低い　白塗り自爆は通常通りできる
   - メンテナー　素直に白確がしやすい
   - フェンサー　死体を作るのでTM以上に信用度が低い　転職後COして人外を牽制する用法になるか
   - ウィスパー　白確は少し難しい　キル情報を複数回出せれば可能か
   - オープナー　ラインを作る必要はあるが白確はしやすい
   
 - 押し度　中
   - タイムマスター　分かりやすい当たり枠　しかし黒視点ケアできないため交通事故感は増す
   - ニート　分かりやすいハズレ枠　オポ化オプションで勝利条件が変わるのは奇妙に思える
   - スーパーバイザー　頭抜けて強い　転職枠に入れることでナーフしているとも言えなくもない
   - パン屋　転職後即ボタン押して白確するシークエンスが初手ボタン禁止ルールの穴になる
   - ボディーガード　白確が難しく不意の死で議論を混乱させやすい 　弱役職の枠にはニートより向いているかもしれない
   
 - 押し度　低
   - ウォッチドッグ　白確可能だが複数の会議を挟んで手間がかかる
   - エージェンシー　後半転職はタスク移し替えのメリットが薄い　転職条件とはシナジーがある
   - カースメーカー　後半転職は死体遭遇の機会が少ない
   - ミッショナリー　一応可能性のありそうな第三　ゲーム途中からの単独陣営化は人を選びそう

信用度が一律で低くなるのでかなり扱いが変わりますね
恐らく転職したことも併せてCOすることになるので、初期アサインされた役職側の信憑性はそれほど下がらないと思っています（戦略的に転職側が嘘をついてしまう場合を考慮しなければ）

**Comment by yukieiji** [comment]
かなりの役職が候補に上がってますが、今後新しいクルーを作ったら追加していくってことでしょうか

これクルー役職の種類を聞く前に言うべきだったのですが(今気づいた)追加される各役職のオプションはどうすればいいのでしょうか
新しく追加するのは流石に面倒ですしデフォルト値を入れるにしてもオプション数が不確定なので難しい気がします

**Comment by hijiki55** [comment]
> かなりの役職が候補に上がってますが、今後新しいクルーを作ったら追加していくってことでしょうか

追加は考えてなかったです。おそらく私的に脳内検討はすると思いますが
元々はシェリフの潜伏オプションのアイディアを、複数の役職に跨れると思いついて分離したものだったりするので
表はあくまでブレスト的メモだと受け取って頂きたく……、本命は上の５役職ですかね

> これクルー役職の種類を聞く前に言うべきだったのですが(今気づいた)追加される各役職のオプションはどうすればいいのでしょうか
新しく追加するのは流石に面倒ですしデフォルト値を入れるにしてもオプション数が不確定なので難しい気がします

オプション値は通常役職のものをそのまま流用する考えでした

**Comment by yukieiji** [comment]
> オプション値は通常役職のものをそのまま流用する考えでした

そうなると実際に入るような役職以外調整されない気がしますが、それでバランスが取れるのかという問題が出てきてしまいます
入らないようなオプションはゲーム内で最後に調整された値が入る(これはデフォルト値ではない)ため意図されない値が混入する可能性があります

**Comment by hijiki55** [comment]
> そうなると実際に入るような役職以外調整されない気がしますが、それでバランスが取れるのかという問題が出てきてしまいます

初期重み付けを《ワーカホリック》自身を１、他の各役職をすべて０にして、プレイヤーの任意で役職を加えていく形ではどうでしょうか？

**Comment by yukieiji** [comment]
> 初期重み付けを《ワーカホリック》自身を１、他の各役職をすべて０にして、プレイヤーの任意で役職を加えていく形ではどうでしょうか？

どういうことでしょうか？

**Comment by hijiki55** [comment]
> どういうことでしょうか？

一手間かけさせることで転職先の役職のオプションに誘導する意図がありました
ええと読み違えている気がするので確認させて下さい

> 入らないようなオプションはゲーム内で最後に調整された値が入る(これはデフォルト値ではない)ため意図されない値が混入する可能性があります

『ゲーム内で最後に調整された値』というのは最後にオプションを更新したタイミングの値という意味ですか？
初期アサインされなかった役職のオプション値はワーカホリック側から直接呼び出せないという意味でしょうか？

**Comment by yukieiji** [comment]
> 『ゲーム内で最後に調整された値』というのは最後にオプションを更新したタイミングの値という意味ですか？
初期アサインされなかった役職のオプション値はワーカホリック側から直接呼び出せないのでしょうか？

最初の「『ゲーム内で最後に調整された値』というのは最後にオプションを更新したタイミングの値という意味ですか」で間違ってはいないです
2つめの部分はワーカホリック側から呼び出そうと思えば呼び出せます

**Comment by hijiki55** [comment]
> 2つめの部分はワーカホリック側から呼び出そうと思えば呼び出せます

そうでしたら、転職先のオプション値は呼び出されたオプション値とイコールになる形でできますか？

**Comment by yukieiji** [comment]
> 転職先のオプション値は呼び出されたオプション値とイコールになる形

この意味がよくわからないのですが、呼び出されたオプションの値が役職アサイン時にロードされる値と同じ意味を指すのであれば問題ないと思います

**Comment by hijiki55** [comment]
> オプションにより、必要なタスク達成率をプレイヤーの死亡数につき一定値低下させる。

の部分の数値調整がしにくいと感じたため

> オプションにより、タスク率ノルマを幽霊プレイヤーの人数に伴って低下、または増加させる。この補正幅には上限がある。

に変更しました
説明のために想定しているオプションと計算式を付記します

#### オプション
|  オプション名 |  詳細  |
| ---- | ---- |
| タスクノルマ | 覚醒に必要なタスク率 |
| 幽霊人数によるノルマ増減 | 幽霊人数によるノルマ増減の最大幅 |
| ノルマ増減が最大幅になる幽霊人数 | 幽霊人数がこの値以上でノルマ増減が最大幅になる |

#### 計算式([]はオプション値)
```
実際のタスクノルマ=
[タスクノルマ] + [幽霊人数によるノルマ増減] * min(幽霊人数, [ノルマ増減が最大幅になる幽霊人数])/[ノルマ増減が最大幅になる幽霊人数]
```

**Comment by yukieiji** [comment]
まだ、この役職の実現性がちょっと怪しいところがあるのでオプション周りはまだなんとも言えないです

役職のオプションロード周りは上で私が言ったものでいいのでしょうか？

**Comment by hijiki55** [comment]
> まだ、この役職の実現性がちょっと怪しいところがあるのでオプション周りはまだなんとも言えないです
役職のオプションロード周りは上で私が言ったものでいいのでしょうか？

実装できる形でお願いしたいです
一応他役職への変更ではないパターンも考えておきます

**Comment by yukieiji** [comment]
> はい、実装できる形でお願いしたいです

実装できる形かhijiki55さんが希望する形で実現させるかによって仕様は大きく変わります
実装できる形を優先するなら選択肢がいっぱいあるより覚醒して固定の役職になる方が楽ではあります

**Comment by hijiki55** [comment]
週末のふにんがすをようやく見終えたところです
覚醒を狙ってタスク優先した結果、分散孤立してしまうなどリスクとしては機能しているようでした
あとは複数位置に跨るタイプのタスクの存在から、タスク率は費やす労力よりも遅れることをフォローするべきかと思いました（例えば生存者のタスク率50%は試合の折り返しよりもほぼ遅くなる)

> 実装できる形かhijiki55さんが希望する形で実現させるかによって仕様は大きく変わります
> 実装できる形を優先するなら選択肢がいっぱいあるより覚醒して固定の役職になる方が楽ではあります

カーペンターで実装された仕様でも個別にノルマを調整できるメリットがありますね
実際のところ、先述した「潜伏シェリフ」単体でやりたい事の7割ぐらい成立していたりはするので
後者の実装に合わせて良いと思います

**Comment by yukieiji** [comment]
> 後者の実装に合わせて良いと思います

実装できる形を優先するのであればタスク覚醒の役職として新しい役職を考えるべきだと思いますがどうでしょうか(既存の役職に覚醒するよりかはバランスが取りやすいという部分です)

**Comment by yukieiji** [comment]
> 新しい覚醒役職はいくつか考えてラフ書きはしてみました
ただバランスについて、覚醒役職のCO力がどの程度あるのかよく分からないんですよね…
現状は騙りの選択肢になる感じがなくて、無能力役職への覚醒COも普通に通りそうでした
とりあえず次のチケットはオプション幅を取れるようにして、受け口を広くする感じで出したいです

新しいチケットを作るということで問題ないでしょうか？

**Comment by yukieiji** [comment]
ではクローズします
