### ISSUE TITLE
ギャンブラー(仮称):インポスター役職

### ISSUE THREAD

**Issue by ittyann-ika** [yukieiji/ExtremeRoles#5]
### 役職名 / Role Name
ギャンブラー(仮称)

### 役職の色 / Role color
インポスターと同様

### 役職の説明 / Role description
キル時に確率で特殊効果が付くネタインポスター役職.
ゲーム開始時の文言は「大当たりを出せ！」

### 役職の能力 / Role ability

キル時に5%の確率で以下の特殊効果からいずれかがランダムで発生する.
なお特殊効果発生時には一定時間*画面の周辺にキラキラとしたエフェクトが発生する.
- キルクールタイムが短くなる
- 死体が消える
- 自身の姿が一定時間*他のクルーから見えなくなる(TORのニンジャと同様,移動速度は要検討)
-  その場に,一定時間*後に爆発するボムを設置する(ボマーと同様)
*能力の発動時間で設定した時間

また,能力のクールタイムが経過するごとに1回判定を行い,3%の確率でフィーバータイムに突入する.
フィーバータイムの特徴は以下の通り.
- キルボタンが“押せ！”という表示に変わる
- 体が虹色に光る(自身と味方インポスター以外からは見えない)
- この状態でキルした場合,確定で特殊効果が発生する

フィーバータイムの時間と特殊能力およびフィーバータイムの確率は設定可能.

`メリット`
- 見た目が楽しい
- 特殊能力やフィーバータイムが発動するとテンションが上がる

`デメリット`
- 特殊能力の発動を自分で制御できない

`開発者のデメリット`
- 能力の判定回数が多い

### 他陣営への影響 / Effect on other teams
- 死体が消えている時の推理要素が増える
- 死体が複数並んでいる時の推理要素が増える

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
ネタ役職は追加したくない(人狼ゲームなので推理要素を残した上でアクションを楽しんでほしい)ですし、能力も発動せずに終わることが多い気がします

> 死体が消えている時の推理要素が増える

死体が消える時点で推理要素は消し飛んでると思われます

そのため特に意見等がない場合はクローズします

**Comment by ittyann-ika** [comment]
コメントありがとうございます.

>能力も発動せずに終わることが多い気がします

上述の確率はあくまで暫定的なものなので,もっと発動しやすい確率にしても問題ありません.

>死体が消える時点で推理要素は消し飛んでると思われます

“死体が消える”に関してはエボルバーの対抗要素として提案させていただきました.(現在死体が消えている=エボルバーがいることが確定となっているため)
特殊効果については単純なメリットとエボルバーやボマーといった他役職の対抗的な効果で羅列したものですので,開発者様が気になるのでしたら効果から削除していただいても構いません.

本役職はネタ役職ではありますが,ランダム要素によりキルした後の行動にバリエーションを与え,会議では推理の選択肢を広げることができるのではないか考えております.
何卒ご検討のほどよろしくお願いいたします.

**Comment by yukieiji** [comment]
> “死体が消える”に関してはエボルバーの対抗要素として提案させていただきました.(現在死体が消えている=エボルバーがいることが確定となっているため)
特殊効果については単純なメリットとエボルバーやボマーといった他役職の対抗的な効果で羅列したものですので,開発者様が気になるのでしたら効果から削除していただいても構いません.

エボルバーの人がかならず死体を消さなければならないってわけではないのでこれを逆用してプレイや会議をすすめることが出来ます。(一回目のキルだけ食べて、次の会議では食べない(エボルバが落ちたとクルーに誤認させる等))
同じような能力を持つとどの役職の能力が発動したのかクルー側から判断できないためどうしても会議が伸びてしまい、追加で様々なリスク(吊らないリスク、ボタンを押さなくていいリスク等)を考える必要が出てきてしまいます。

> 本役職はネタ役職ではありますが,ランダム要素によりキルした後の行動にバリエーションを与え,会議では推理の選択肢を広げることができるのではないか考えております.

行動にバリエーションを与えるという点では良いのですが、クルーが考慮しないといけない要素が増えすぎているのではないかなって思っています(クルー側からしたら推理する情報が無いので推理の幅ではないはず(言葉遊びのような気がしなくもないですが))

**Comment by ittyann-ika** [comment]
>同じような能力を持つとどの役職の能力が発動したのかクルー側から判断できないためどうしても会議が伸びてしまい、追加で様々なリスク(吊らないリスク、ボタンを押さなくていいリスク等)を考える必要が出てきてしまいます。

開発者様は同様の能力を持つ役職を追加したくないと考えておられるのでしょうか.
私はクルーに様々な可能性を与えて吊りを回避することも立派なインポスターの戦略だと考えていますし,それを追加するというのが役職modの役割だと考えているのですが違うのでしょうか.

>クルーが考慮しないといけない要素が増えすぎているのではないかなって思っています(クルー側からしたら推理する情報が無いので推理の幅ではないはず(言葉遊びのような気がしなくもないですが))

死体が消えるということが開発者様にとってNGということでしたら,死体の透明化や通報不可化などでも問題ありません.
1つ目の質問にNGと回答された場合は他の効果を考える必要がありますが,考案者としては以下の条件に当てはまるような特殊効果があれば良いと考えております.
- 特殊効果の候補が複数ある(単一の効果だと他役職の下位互換でしかなくなるため)
- 一目でどの特殊効果が発生したか分かる(特殊効果の差別化のため)
- デメリットがないor少ない効果(任意発動できないという点がデメリットのため)

**Comment by yukieiji** [comment]
> 開発者様は同様の能力を持つ役職を追加したくないと考えておられるのでしょうか.

優劣をつけてしまうので、同様の能力を持つ役職は基本的に追加したくないです。(差別化は必ず必要です、第三陣営は例外)

> 私はクルーに様々な可能性を与えて吊りを回避することも立派なインポスターの戦略だと考えていますし,それを追加するというのが役職modの役割だと考えているのですが違うのでしょうか.

プレイング関係なく役職がいるだけで可能性を与えるのはインポスターの役割ではなく第三陣営の役割(この役職が第三陣営であれば特に不満はない)です（日曜のふにんがすを見ればミッショナリー(1人)がいるってだけでどれだけ会議がグッチャグチャになるか分かると思います。TORのヴァンパイアからキル時間が推測できなくなっただけであれだの効果があるのならば、この役職を今のまま実装すればミッショナリー以上に会議が混乱することは容易に想像できるはずです）
なので、インポスターは基本的にプレイングによって可能性を広げていただきたいと考えています

> 死体が消えるということが開発者様にとってNGということでしたら,死体の透明化や通報不可化などでも問題ありません.
1つ目の質問にNGと回答された場合は他の効果を考える必要がありますが,考案者としては以下の条件に当てはまるような特殊効果があれば良いと考えております.

複数の能力を持つというのがこの役職の最も強い部分です(それがランダムであったとしても)。それ以上に他の役職と全く同じ能力を持つように強くする必要はないと思っています(似たような能力を持つとしても弱体化は必要だと思います)

> - デメリットがないor少ない効果(任意発動できないという点がデメリットのため)

任意にキルした時に(ランダムであっても)発動する時点でこの役職の能力は任意発動として捉えるべきでしょう
狙った能力を使えない部分がデメリットでしょう

**Comment by ittyann-ika** [comment]
>優劣をつけてしまうので、同様の能力を持つ役職は基本的に追加したくないです。(差別化は必ず必要です、第三陣営は例外)

>プレイング関係なく役職がいるだけで可能性を与えるのはインポスターの役割ではなく第三陣営の役割(この役職が第三陣営であれば特に不満はない)です

インポスターの対抗は別陣営にするべきということですね.理解しました.
既にジャッカルやミッショナリーといったキルできる第三陣営がいる中でさらにキル陣営を増やすことはクルー不利要素になってしまうのではないかという懸念があったこと,
また単独キル陣営だとどうしても勝ち筋が薄くなってしまうと考えたことからインポスター役職として提案させていただいた次第です.
前者はルームホストに役職の数を調整してもらうことで,後者は他の勝利条件を追加することで解決できるということであれば,私もこの役職を第三陣営とすることに異論はありません.

>複数の能力を持つというのがこの役職の最も強い部分です

能力のランダム性にばかり気をとられていてこの考えに至っておりませんでした.鋭いご指摘ありがとうございます.
第三陣営として考えるのであれば能力を弱体化することも異論はありません.

>狙った能力を使えない部分がデメリットでしょう

言葉足らずで申し訳ありません.その認識で間違いありません.
修正いただきありがとうございます.

**Comment by yukieiji** [comment]
> インポスターの能力対抗は別陣営にするべきということですね.理解しました.
既にジャッカルやミッショナリーといったキルできる第三陣営がいる中でさらにキル陣営を増やすことはクルー不利要素になってしまうのではないかという懸念があったこと,
また単独キル陣営だとどうしても勝ち筋が薄くなってしまうと考えたことからインポスター役職として提案させていただいた次第です.
前者はルームホストに役職の数を調整してもらうことで,後者は他の勝利条件を追加することで解決できるということであれば,私もこの役職を第三陣営とすることに異論はありません.

第三陣営が必ずしもキル能力を持つ必要はありません、生存勝利ではない特殊勝利を付与しても問題はないです。ジェスターとかタスクマスターは実際持ってませんし、アリスは特殊勝利以外は難しいと考えています(ミッショナリーはキルがバレにくいことを利用すれば勝てるでしょう)

**Comment by ittyann-ika** [comment]
>生存勝利ではない特殊勝利を付与しても問題はないです

ありがとうございます.
ギャンブラーの特殊勝利条件として以下はいかがでしょうか.

- 死亡して幽霊になった時,一定時間ベットボタンが発生する
- ベットしたプレイヤーの陣営が勝利した場合,自分も同時に勝利となる(勝利の乗っ取りはなし)
- ベットしたプレイヤーの陣営が敗北した場合,自分も敗北となる
- 制限時間内に誰にもベットできなかった場合は敗北となる(終盤までベットボタンを温存できない)

開発者様の考えを聞かせていただけると幸いです.

**Comment by yukieiji** [comment]
> 死亡して幽霊になった時,一定時間ベットボタンが発生する

死亡しなければ勝利条件を満たすことが出来ないということで間違いないでしょうか

> ベットしたプレイヤーの陣営が勝利した場合,自分も同時に勝利となる(勝利の乗っ取りはなし)
ベットしたプレイヤーの陣営が敗北した場合,自分も敗北となる

これは別途するタイミングでゲーム内にいる全ての陣営が分かってしまうのですがそこは問題ないのでしょうか

**Comment by ittyann-ika** [comment]
>死亡しなければ勝利条件を満たすことが出来ないということで間違いないでしょうか

生存勝利の他に,上記の特殊勝利があるという想定です.

>これは別途するタイミングでゲーム内にいる全ての陣営が分かってしまうのですがそこは問題ないのでしょうか

ここはご相談したいところでして,ベットするまで他の人の役職名が見えないという処理は実装可能なのでしょうか.

**Comment by yukieiji** [comment]
> 生存勝利の他に,上記の特殊勝利があるという想定です.

キル能力を持っているのに死んだら同時勝利が可能なので、キル能力を使うメリットが全く無いように見えますがどうでしょうか(キルせず最終盤面で適当につられて、勝ちやすい方にベッドするだけの役職になる気がします)
個人的には生存勝利と特殊勝利条件を持つ場合は特殊勝利(メインの勝利条件、乗っ取り可)を目指しつつ、生存勝利(サブの勝利条件、乗っ取り可)を目指すって形がキレイだと思います

> ここはご相談したいところでして,ベットするまで他の人の役職名が見えないという処理は実装可能なのでしょうか.

それは出来ます

**Comment by ittyann-ika** [comment]
>キルせず最終盤面で適当につられて、勝ちやすい方にベッドするだけの役職になる気がします

幽霊にならないとベットができないので吊られたタイミングで試合が終了すると確定敗北ですし,赤陣営があと少しで勝てるタイミング(赤陣営が有利だがクルーが過半数以上いる状態)で何もしていない自称ギャンブラーを吊るメリットがクルー側にはあまりないので怪しまれるためにキルボタンを使う必要はあると思っております.
ただ,積極的にキルした方が他陣営を錯乱できるのにそれをするメリットがないというのは確かにその通りなのですよね.
一定時間キルしないと自爆(ギャンブルできなくて発狂みたいなイメージで)とかがあればキルせざるを得なくなりますが,流石に能力を盛りすぎでしょうか.

>個人的には生存勝利と特殊勝利条件を持つ場合は特殊勝利(メインの勝利条件、乗っ取り可)を目指しつつ、生存勝利(サブの勝利条件、乗っ取り可)を目指すって形がキレイだと思います

キル陣営で特殊勝利を目指すとなると特定の人をキルするなどでしょうか.
その方向性で行くと,試合開始時に内部的にターゲットを抽選してターゲットキルできたら単独勝利というのはいかがでしょうか.(単独勝利ガチャみたいなイメージで)

**Comment by yukieiji** [comment]
> ただ,積極的にキルした方が他陣営を錯乱できるのにそれをするメリットがないというのは確かにその通りなのですよね.

キルすると最初の方で自分が吊られてしまうので、今の状態だとキルする行為自体が能力を発動させるためのトリガーでしかなくキルせず能力を発動しないほうが勝利には近づきやすいでしょう

> 一定時間キルしないと自爆(ギャンブルできなくて発狂みたいなイメージで)とかがあればキルせざるを得なくなりますが,流石に能力を盛りすぎでしょうか.

流石にそれは能力を盛りすぎですね

> キル陣営で特殊勝利を目指すとなると特定の人をキルするなどでしょうか.
その方向性で行くと,試合開始時に内部的にターゲットを抽選してターゲットキルできたら単独勝利というのはいかがでしょうか.(単独勝利ガチャみたいなイメージで)

個人的にはこの役職自体がキル能力を持つ必要があるのかを確認したいです

**Comment by ittyann-ika** [comment]
>個人的にはこの役職自体がキル能力を持つ必要があるのかを確認したいです

始めはインポスター役職として考案したため,キル能力に付加効果としていました.
しかし第三陣営ということでしたらキル能力を持つ必要はないと考えております.
キルをトリガーとしない場合どのように能力を使用するかアイデアがありましたらお聞かせ願いたいです.

**Comment by yukieiji** [comment]
> しかし第三陣営ということでしたらキル能力を持つ必要性はないと考えております.
キルをトリガーとしない場合どのように能力を使用するかアイデアがありましたらお聞かせ願いたいです.

普通に能力ボタンとして能力が発動するようにすればいいと思います

**Comment by ittyann-ika** [comment]
>普通に能力ボタンとして能力が発動するようにすればいいと思います

単に能力ボタンとした場合,能力の対象と種類がどのようなものになる想定されているのでしょうか.

**Comment by yukieiji** [comment]
> 単に能力ボタンとした場合,能力の対象と種類がどのようなものになる想定されているのでしょうか.

能力自体がキルをベースに考えてるので新しく能力を考えてもいいかもしれないです

**Comment by ittyann-ika** [comment]
>能力自体がキルをベースに考えてるので新しく能力を考えてもいいかもしれないです

能力をインポスターと混同できるようなものでなくしてしまったらそれこそこの役職を第三陣営にした意味がなくなってしまわないでしょうか.
であれば生存勝利や死亡時勝利はなしで,n人殺したら単独勝利とかの方が良いと思います.

**Comment by ittyann-ika** [comment]
>対象を死体もしくはクルーの対象に対して能力を使用するとかで解決できるのではないでしょうか

生存するクルーに何かアクションして勝利するとなると確率発動という点がネックになりますし,例に上げていただいたような能力だと能力を使った時点でクルーにバレるので難しい気がします.

>流石にそれは強すぎるのでは？

2,3人なら流石に強いですが,1/3〜半分とすれば単独陣営ということもあり結構難易度は上がると考えております.
もし別の案ということでしたら,ノルマではなく試合終了時点で一番キル数が多かった場合乗っ取り勝利というのはいかがでしょうか.他のキル陣営のキルも促せて,なかなかキルが起きずに試合がグダるのを防ぐこともできると思います.

**Comment by yukieiji** [comment]
> 生存するクルーに何かアクションして勝利するとなると確率発動という点がネックになりますし,例に上げていただいたような能力だと能力を使った時点でクルーにバレるので難しい気がします.

どんな能力を追加するのかにもよりますが、生存者に向けて能力使ってその能力が死体向け能力だった場合不発に終わって何も起きないので問題ないと思います

> 2,3人なら流石に強いですが,1/3〜半分とすれば単独陣営ということもあり結構難易度は上がると考えております.
もし別の案ということでしたら,ノルマではなく試合終了時点で一番キル数が多かった場合乗っ取り勝利というのはいかがでしょうか.他のキル陣営のキルも促せて,なかなかキルが起きずに試合がグダるのを防ぐこともできると思います.

それはもうギャンブラーって役職の名前と能力、役割にあってない気がします

**Comment by ittyann-ika** [comment]
>どんな能力を追加するのかにもよりますが、生存者に向けて能力使ってその能力が死体向け能力だった場合不発に終わって何も起きないので問題ないと思います

確率で能力発動しても必ず効果が出るとは限らないという仕様で考えておられるということですね.承知いたしました.
その場合どのような勝利条件を想定されているのでしょうか.

>それはもうギャンブラーって役職の名前と能力、役割にあってない気がします。
あとその人数を殺せないって分かった時に役職としてなんにもできなくなってしまいます

確かにシリアルキラーみたいなものになっていますね.

でしたら賭け金というステータスを用意して,キルした際に相手の陣営によって倍率がかかるようにして(例えば素クルーなら1倍,役職持ちクルーなら2倍,インポスターは5倍といった風に),最終的に賭け金を目標以上にできたら勝利というのはいかがでしょうか.
ギャンブラー要素を残しつつキルを促せるようになると思います.

**Comment by yukieiji** [comment]
> 確率で能力発動しても必ず効果が出るとは限らないという仕様で考えておられるということですね.承知いたしました.

issueに書いてある確率でも、私が考えている確率(20％？位)でも発動しないことはあると思われます

適当に考えてる能力の案的なものです
- 範囲内のクルーを無差別に1人吹き飛ばす
- 範囲内のクルーをどこかにテレポートさせる
- 範囲内のクルーを一定時間見えなくする
- 範囲内の死体を一つ消す
- 範囲内の死体を見えなくする
- 範囲内の死体をどこかにテレポートさせる

> その場合どのような勝利条件を想定されているのでしょうか.

以下はどうでしょう
- 能力の対象になったプレイヤーの勝利条件がギャンブラーの勝利条件(同時勝利可能ただし一定時間後に消滅、ギャンブル依存症的何かの再現)
- 対象にしたプレイヤーの陣営がすでに滅んでいた場合、キル能力を一定期間得る(このときだけ、生存勝利を目指すことが出来る)

> でしたら賭け金というステータスを用意して,キルした際に相手の陣営によって倍率がかかるようにして(例えば素クルーなら1倍,役職持ちクルーなら2倍,インポスターは5倍といった風に),最終的に賭け金を目標以上にできたら勝利というのはいかがでしょうか.

それでも掛け金が達成できないとわかれば何も出来なくなってしまいます

**Comment by ittyann-ika** [comment]
>適当に考えてる能力の案的なものです

範囲内の〜とすることによってすれ違いでは判断できないようにするということですね.納得しました.

>以下はどうでしょう
> - 能力の対象になったプレイヤーの勝利条件がギャンブラーの勝利条件(同時勝利可能ただし一定時間後に消滅、ギャンブル依存症的何かの再現)
> - 対象にしたプレイヤーの陣営がすでに滅んでいた場合、キル能力を一定期間得る(このときだけ、生存勝利を目指すことが出来る)

特に前者はヒモっぽくてとても面白いと思います.
後者の条件というのは死体を対象にした時ということですよね.

>それでも掛け金が達成できないとわかれば何も出来なくなってしまいます

賭け金は試合中に見れない想定だったので,キルした相手の陣営を的確に把握していない限り達成できないとわかることはないと考えております.

**Comment by yukieiji** [comment]
> 範囲内の〜とすることによってすれ違いでは判断できないようにするということですね.納得しました.

あとは能力発動がミッショナリーとかと同じくランダムで発動するようにするとかでしょうかね、そうすれば、推測はできないでしょう

> 後者の条件というのは死体を対象にした時ということですよね.

死体を対象にした場合と勝利条件が消える前に相手の陣営が絶滅したときです

> 賭け金は試合中に見れない想定だったので,キルした相手の陣営を的確に把握していない限り達成できないとわかることはないと考えております.

賭け金を見えなくした理由は何でしょうか

**Comment by ittyann-ika** [comment]
>あとは能力発動がミッショナリーとかと同じくランダムで発動するようにするとかでしょうかね、そうすれば、推測はできないでしょう

あとはかけられた本人にはわからない効果,例えば対象のプレイヤーの名前の色が他のプレイヤーからランダムで見えるようになったり守護天使のようなバリアーを付けられたりするなら即時発動でもどのタイミングから効果が発生したか推測しにくくなると思います.

>死体を対象にした場合と勝利条件が消える前に相手の陣営が絶滅したときです

補足ありがとうございます.
確認ですがこの場合,例えば最終盤面インポスター1ジャッカル1ギャンブラー1の状態でギャンブラーがジャッカルに能力をかけた後にジャッカルがインポスターにキルされると,ギャンブラーがキル能力を持つ第三陣営扱いになって,どちらかが死ぬもしくは相乗り有効時間が切れるまで試合が終了しないという仕様になるのでしょうか.

>賭け金を見えなくした理由は何でしょうか

倍率によって確実に陣営が把握できてしまうためです.
勝ちを諦めたギャンブラーがその情報を元にクルーに加担してインポスター不利になることがあるならばそれは第三陣営として不適切だと考えております.

**Comment by yukieiji** [comment]
> あとはかけられた本人にはわからない効果,例えば対象のプレイヤーの名前の色が他のプレイヤーからランダムで見えるようになったり守護天使のようなバリアーを付けられたりするなら即時発動でもどのタイミングから効果が発生したか推測しにくくなると思いますがいかがでしょうか.

私が能力を決定するわけではないので好きな能力を考えていただければ(実装できるできない、バランス的にどうこうは言いますけど)

> 補足ありがとうございます.
確認ですがこの場合,例えば最終盤面インポスター1ジャッカル1ギャンブラー1の状態でギャンブラーがジャッカルに能力をかけた後にジャッカルがインポスターにキルされると,ギャンブラーがキル能力を持つ第三陣営扱いになって,どちらかが死ぬもしくは相乗り有効時間が切れるまで試合が終了しないという仕様になるのでしょうか.

現状は無害な第三陣営と害のある第三陣営を切り替えるような設計では無い(PR送って改善していただいてもいいです)ので恐らくジャッカルがキルされた瞬間に勝利判定が入るようになります(ギャンブラーは敗北)

> 倍率によって確実に陣営が把握できてしまうためです.
勝ちを諦めたギャンブラーがその情報を元にクルーに加担してインポスター不利になることがあるならばそれは第三陣営として不適切だと考えております.

見えない勝利に向かっていくのはプレイヤーとしても不安だし嫌だと思うので表示するか、倍率が毎回変化するとかにして見えるようにするのがいいのではないでしょうか

**Comment by ittyann-ika** [comment]
>現状は無害な第三陣営と害のある第三陣営を切り替えるような設計では無い(PR送って改善していただいてもいいです)ので恐らくジャッカルがキルされた瞬間に勝利判定が入るようになります(ギャンブラーは敗北)

あまり勝利条件を複雑にしてもユーザ側が仕様について混乱するだけなので,死体への能力はなしにして能力は生存者にのみにした方が良いと思いました.
相手の陣営が滅びた場合は次の能力相手を探すという風にした方がシンプルでわかりやすいと思います.

>見えない勝利に向かっていくのはプレイヤーとしても不安だし嫌だと思うので表示するか、倍率が毎回変化するとかにして見えるようにするのがいいのではないでしょうか

では,倍率をランダムにしてフィーバータイムの時に高倍率が確定するのはいかがでしょうか.(例えば通常だと1倍2倍5倍のどれかでフィーバータイムは5倍確定など)

**Comment by ittyann-ika** [comment]
現状出ている二種類の案をそれぞれ整理させていただきます.

1. 生存者に対して能力を使用する場合

- 勝利条件: 能力を使用した相手の陣営に相乗り勝利
- フィーバータイムは能力の確定発動
- 能力は範囲内のクルーのうち1人にかけられる
- 能力案例
  - 能力をかけた相手がランダム時間後にテレポートする
  - 能力をかけた相手のプレイヤー名が一定時間ランダムな色に変化して他のプレイヤーから見えるようになる
  - 能力をかけた相手に一定時間キルされないシールドを張る
  - 能力をかけた相手がランダム時間経過後から一定時間の間移動速度が速くなる


2. キル時に能力が付加効果として発生する場合

- 勝利条件: 賭け金が一定倍率以上で単独勝利
- フィーバータイムは賭け金の高倍率確定
- 能力案例
  - キルクールタイムが1回短くなる
  - 死体が一定時間透明になる(通報は可)
  - 死体が一定時間通報できなくなる
  - 自身の姿が一定時間透明になる

**Comment by ittyann-ika** [comment]
お忙しい中大変恐縮ですが,上記二案の所感についてお返事いただけると幸いです.

**Comment by yukieiji** [comment]
意見がぐちゃぐちゃになってるのでまずはチケット全体を更新してもらってよろしいですか

**Comment by yukieiji** [comment]
あと催促はやめて下さい
自分のチケットが放置される気持ちはわかりますが、限られたリソースで返信しやすく片付けやすいチケットから返信しないとチケットが溜まっていきGithubでのタスク管理が機能しなくなります

**Comment by yukieiji** [comment]
4/24までに返信がないもしくはチケットが更新されない場合はクローズさせていただきます

**Comment by yukieiji** [comment]
返信や更新がないためクローズします
