### ISSUE TITLE
[ニュートラル陣営] : トレイター

### ISSUE THREAD

**Issue by kisaRagi05** [yukieiji/ExtremeRoles#51]
### 役職名 / Role Name
トレイター
### 役職の色 / Role color
紫色
### 役職の説明 / Role description
クルー役職の肩書と能力を持ちキルが出来る第三陣営
### 役職の能力 / Role ability

- 試合開始時に「トレイター（クルー役職名）」と表示させる
  - そのクルー役職は設定されたスポーン数以上にならない
  - 例：シェリフが設定で1ならトレイターシェリフを引くとクルーシェリフはスポーンしない
- キルとベントは可能、サボタージュは不可能
  - キルはジャッカルと同様に普通のキル行為とする
  - サボタージュはジャッカル陣営も使えないので同様に使えないように
- 能力「与えられた白役職の能力を使う」
  - 例1：タイムマスタートレイターならタイムシールドを使用可能
  - 例2：メンテナートレイターなら緊急修理を使用可能
  - 例3：パン屋トレイターなら通常通り会議後の告知が出る
  - 例4：ニートトレイターならアドミンやカメラが見えなくなる
### 勝利条件
インポスター及びキル能力を持つニュートラルが全滅しており、生存者の半数以上が同じ陣営。

### 他陣営への影響 / Effect on other teams
対抗が出ない騙りが絶対通るのでクルー陣営の役職COの信頼度を大きく下げます
能力も使えるので能力での白証明も出来なくなる
インポスター陣営からトレイター陣営にはならないので、ジャッカル＆サイドキックよりは脅威度は下がります

### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

### 要確認
- クルー役職を使えるようにするか肩書だけにするか
  - 肩書だけの場合、別の能力を考える必要があると思う
- シェリフトレイターの場合の処理をどうするか
  - シェリフのキルボタンとトレイターのキルボタンの二つを表示させる
  - シェリフのキルボタンはトレイターなら全員キル可能の状態にする

**Comment by yukieiji** [comment]
> 能力「与えられた白役職の能力を使う」

一応確認なのですが、一番最初にアサインされるようなコンビ役職全般(ヒーロー、マーリン、サポーター等)は非対応になりますがよろしいでしょうか

> シェリフのキルボタンとトレイターのキルボタンの二つを表示させる
シェリフのキルボタンはトレイターなら全員キル可能の状態にする

ニュートラルのキルボタンとクルーのキルボタンは共通であるという点と同じ処理を通るようになっていてその処理の中でシェリフの自爆処理を行っている点でこれは不可能だと思います

**Comment by kisaRagi05** [comment]
> 一応確認なのですが、一番最初にアサインされるようなコンビ役職全般(ヒーロー、マーリン、サポーター等)は非対応になりますがよろしいでしょうか

非対応で問題ありません
役職によって確定白があるのは悪く無いと思います

> ニュートラルのキルボタンとクルーのキルボタンは共通であるという点と同じ処理を通るようになっていてその処理の中でシェリフの自爆処理を行っている点でこれは不可能だと思います

なるほど、ではシェリフ+トレイターとなった場合にクルーを切る方法として
- シェリフ+トレイターからクルー+トレイターに変換して回避する
- そもそもシェリフはトレイターにならなくなる

あと考えられる手段はこの2つでしょうか
ニートはハズレ枠でもいいと思ってますが
クルーを切らなきゃいけないのにクルーを切ると自爆するのシェリフは
ゲームとして成り立たない事になりますので解決したいですね

**Comment by yukieiji** [comment]
> なるほど、ではシェリフ+トレイターとなった場合にクルーを切る方法として
シェリフ+トレイターからクルー+トレイターに変換して回避する
そもそもシェリフはトレイターにならなくなる
あと考えられる手段はこの2つでしょうか

ディスカッションの方にも上げましたがクルー役職を消し飛ばすのが楽といえば楽です(新役職が実装された時にあれこれ考える必要も消えるので)

> ニートはハズレ枠でもいいと思ってますが

ニートの部分で忘れてたのですが、毎フレームごとに[別役職の部分と比較して優秀な部分を取り出すという処理](https://github.com/yukieiji/ExtremeRoles/blob/97b2dac778bae7a3e6802f3d82f67245b7e20bfc/ExtremeRoles/Roles/API/RoleBase.cs#L617-L651)をやっているのでニートのデメリットは消し飛ぶという部分を忘れてました

**Comment by kisaRagi05** [comment]
> ディスカッションの方にも上げましたがクルー役職を消し飛ばすのが楽といえば楽です(新役職が実装された時にあれこれ考える必要も消えるので)

クルー役職を消し飛ばす場合は特にパン屋トレイターがCO不可能になるのが厄介だと思います
しかしプレイヤーが大変な感じになるだけなので運が悪かったとするだけでもいいかもしれません

クルー役職能力+トレイターなら第三陣営でありながらもクルー役職能力を体験できるという魅力があると思いますが
スペシャルクルーやエンジニアは完全に能力を潰されるようなものなのでクルー役職を消し飛ばすという方針も良いと思います

ちなみに役職を消し飛ばす場合、元クルー役職のサイドッキックみたいなものなので
少し便利な追加能力を所持するべきかなと思います

> ニートの部分で忘れてたのですが、毎フレームごとに[別役職の部分と比較して優秀な部分を取り出すという処理](https://github.com/yukieiji/ExtremeRoles/blob/97b2dac778bae7a3e6802f3d82f67245b7e20bfc/ExtremeRoles/Roles/API/RoleBase.cs#L617-L651)をやっているのでニートのデメリットは消し飛ぶという部分を忘れてました

でしたら特殊能力も何もない感じになりますね

**Comment by yukieiji** [comment]
> クルー役職を消し飛ばす場合は特にパン屋トレイターがCO不可能になるのが厄介だと思います
しかしプレイヤーが大変な感じになるだけなので運が悪かったとするだけでもいいかもしれません

パン屋に関しては役職を追加する処理の前の初期化中に役職外のゲームデータを管理する所にパン屋設立処理が入るので消し飛ばしても残るようにするってことも可能だと思います

> ちなみに役職を消し飛ばす場合、元クルー役職のサイドッキックみたいなものなので
少し便利な追加能力を所持するべきかなと思います

消し飛ばすなら能力があっても問題はないと思います

> でしたら特殊能力も何もない感じになりますね

そうですね

**Comment by kisaRagi05** [comment]
> パン屋に関しては役職を追加する処理の前の初期化中に役職外のゲームデータを管理する所にパン屋設立処理が入るので消し飛ばしても残るようにするってことも可能だと思います

それなら大丈夫そうですね！
では改めて考えるとメンテナーとオープナー以外なら結構騙りいけるので
本格的にクルー役職能力を消し飛ばす方向で良いと思います

> 消し飛ばすなら能力があっても問題はないと思います

では能力として下記を提案します

- 能力：クラッキング
  - アドミン、バイタル、カメラをどこからでも見れるボタンを追加
    - 能力の使用には時間制限がある
    - クラッキングボタン → クラッキング先を選択する画面 → アドミン等 とする
  - クールタイムがあるが何度でも使用可能
  - ゲーム開始時は能力未開放
  - 能力解放条件：誰かをキルする（基本1回キルでOKの回数任意設定型）
- メリット
  - 科学者、ウォッチドッグ、スーパーバイザーをより強く騙る事が可能となる
  - それ以外のトレイターでもクラッキングを駆使して役職騙りが可能となる
  - クルーやインポスター等に不利な情報を提供して議論を乱せる
- デメリット 
  - ノーキルでは能力を使えないので潜伏し続けて能力を使う事は不可能
  - 何もない場所で止まる必要の無い騙り役職だと不自然となる
  - 普段以上にアドミン等の情報を出して逆に怪しまれる

**Comment by yukieiji** [comment]
> クラッキング先を選択する画面

クラッキング先の選択画面をどうやって出すのかという問題があります・・・・

**Comment by kisaRagi05** [comment]
> クラッキング先の選択画面をどうやって出すのかという問題があります・・・・

クイックチャットのメニューのような選択画面はどうでしょうか？
難しいようでしたら

1. クラッキングを押す度にアドミン→バイタル→カメラ→アドミンという感じに順繰りにする
2. クラッキングを押す度にランダムで選ばれる
3. ゲーム開始時に見れるものが1つで固定される

番号順で希望となります

**Comment by yukieiji** [comment]
> クイックチャットのメニューのような選択画面はどうでしょうか？

クイックチャットメニューの選択画面も難しい気がします

能力が順々に変わる位なら問題ない気がします

**Comment by kisaRagi05** [comment]
> 能力が順々に変わる位なら問題ない気がします

ではそれでいきましょう

**Comment by kisaRagi05** [comment]
追記として役職の無いクルーもトレイターにする事は可能でしょうか
クルー役職が少ない場合、全部トレイターとなる可能性と
クルー役職が無い試合でどうするのかの問題の対策です

案としましては

- クルー陣営からランダムでトレイターが決まる
  - 例：トレイター2人が両方役職無しの場合も両方役職ありの場合も起こりえる
- 設定で調整可能にする
  - ゲームオプションのクルーのロール数最小最大のようにする
  - 最小1 最大2 なら片方は必ず役職持ちからのトレイター　もう片方は役職無しからになる場合もある
  - 最小0 最大0 ならトレイターは役職持ちからアサインされない
  - 最小0 最大2 ならランダムでトレイターが決まる

**Comment by kisaRagi05** [comment]
> ソロのコンビ役職としてこの役職は実装されるため乱数の機嫌次第ではクルー役職があっても役職のないトレイターになることはあります(EXRolesが採用された3月のふにんがすであったラバーズ+クルーみたいなことになるだけです)

問題無さそうですね。
でしたら他にトレイターの追加点とかも無く充分かと思います

ちなみにタスクを一定数完了すると役職が分かる系のクルー役職は
トレイターになると最初から役職わかる感じでしょうか？
それとも最後まで普通のクルーとしか表示されない感じですか？

**Comment by yukieiji** [comment]
あと問題のあるとすれば本当にクラッキングでいいのかとクラッキングの仕様はスーパーバイザー等の使用で問題ないかくらいでしょうか

**Comment by kisaRagi05** [comment]
> あと問題のあるとすれば本当にクラッキングでいいのかとクラッキングの仕様はスーパーバイザー等の使用で問題ないかくらいでしょうか

キルで能力解放の仕様はこのままでいいと思います

通信妨害のサボタージュをするインポスターと真逆の存在として情報を見て場面を立ち回る
トレイターというのをイメージしていますので
これもこのままでいいと思います

スーパーバイザー等には「タスクを終了させることで役職に設定された充電の持続時間まで回復する」が
ありますけど、トレイターも本当にタスクが出来て充電回復が可能にするのもありかもしれませんね
これも終盤でもタスクやってるとかで普段と異なる疑惑を持たれる気がします

3種類の能力を順繰りで使うのでスーパーバイザー等よりは若干
クールタイム回復等を緩めにしていいと思います

**Comment by yukieiji** [comment]
> トレイターも本当にタスクが出来て充電回復が可能にするのもありかもしれませんね
これも終盤でもタスクやってるとかで普段と異なる疑惑を持たれる気がします

トレイターにタスクをもたせるとクルーとしての見分けがつかなくなりそうってのがありますので、そこは議論の余地がありそうです

> 3種類の能力を順繰りで使うのでスーパーバイザー等よりは若干
クールタイム回復等を緩めにしていいと思います

クールタイムの仕様は一律30秒です

これクリック毎に変わるって感じなのでしょうか、それとも使用時間が終わるまで切り替わらないという形なのでしょうか

**Comment by kisaRagi05** [comment]
> トレイターにタスクをもたせるとクルーとしての見分けがつかなくなりそうってのがありますので、そこは議論の余地がありそうです

「タスクを終了させることで役職に設定された充電の持続時間まで回復する」
これも完全に同一にするならタスクありにしまして

トレイターは「キルによる解禁」以外の特殊条件無く能力を使える
こちらにするならタスク無しでよいかなと思います

タスク偽造しながらクラッキングとかも考えられるので
やっぱりタスクは無しが良いかなと思います

> クールタイムの仕様は一律30秒です

了解しました
ではここは各々の村の設定次第ということで

> これクリック毎に変わるって感じなのでしょうか、それとも使用時間が終わるまで切り替わらないという形なのでしょうか

使用時間が終わるまでだと切り替えが大変不便なので
クリック毎に変わるにしましょう

**Comment by kisaRagi05** [comment]
> あと使用時間は全能力一律で問題ないですかね？それとも個別管理でしょうか

全能力一律と考えています

それトレイター同士は色で識別出来る感じでしょうか？
ジャッカル二人にしてもお互い分からなかったようなので、この設定がどうなってるかなと思いました
トレイターはジャッカル＆サイドキックのようにお互いを色で識別できる職であるべきと思ってます

**Comment by kisaRagi05** [comment]
> ソースコードを見る限り全ての第三陣営が同じ役職の色を確認できるようにしてなかったです。そのため、1つでも第三陣営役職で確認できるようにするとなると全ての第三陣営にそれを適用する必要があると思います
なのでトレイターだけ特別に実装という訳にはいかないです

色での識別でなくても記号やら何かしらの視覚的情報で
仲間が誰かが分かればいいですが
難しいようでしたら無くても問題ありません

でしたらジャッカル同士のようにお互いの確認手段は
お互いをキルできないって理由で見つける手段が残ってた気がしますので
まだ何とかなるかなと

> (全体の制御オプション実装 + 全ての第三陣営役職の実装(サイドキック同士が見えない問題の解決も含めて)が必要、役職で対応というよりかは別対応になります)

ルール作成の幅が広がりますので、全体制御による実装は良い感じになると思います！

**Comment by yukieiji** [comment]
> 色での識別でなくても記号やら何かしらの視覚的情報で
仲間が誰かが分かればいいですが
難しいようでしたら無くても問題ありません

ジャッカルと同じくキルボタン周りは同じ役職同士(一応オプションで有効時なんですが)だと判定されないようになってるのでそれでどうにか出来ると思います

**Comment by kisaRagi05** [comment]
> ジャッカルと同じくキルボタン周りは同じ役職同士(一応オプションで有効時なんですが)だと判定されないようになってるのでそれでどうにか出来ると思います

では味方は分からない（オプションによるキルボタン無反応にて判断する）
色でわかるようにするのは第三陣営全てに関する設定を今後実装するならの場合
「全体の制御オプション実装 + 全ての第三陣営役職の実装(サイドキック同士が見えない問題の解決も含めて)」
これでいきましょう

**Comment by yukieiji** [comment]
あと考えるべきことといえばこの役職をどのバージョンに入れるかでしょうか([マイルストーン](https://github.com/yukieiji/ExtremeRoles/milestones)に一応のリリース予定があります、v2.2.0.0:6月10日、v3.0.0.0:6月24日)
予定の遅れなしで実装するなら7/15リリース予定のv3.1.0.0、他のバージョンに合わせてほしいとのことであればその合わせたバージョンの後のバージョンが遅れます(特にサブマージドに合わせるとそのリリースが遅れます)

**Comment by kisaRagi05** [comment]
特に急ぐ気も希望もありませんので、7/15で良いと思います！

**Comment by yukieiji** [comment]
マイルストーンをv3.1.0.0、優先度を低に設定します

**Comment by yukieiji** [comment]
開発版にて完成しました
テストしたところパン屋を奪っても表示は出ませんでした
あとベントに関しては記載が無いのでなしでよろしいですか

**Comment by suikouzatta** [comment]
> できなくはないですが今までは役職アサイン後に計算量がO(n)で実装できていたものが役職セットアップ時に最良計算量O(n)、最悪計算量O(n!)の実装になってしまいます(nはプレイヤー数)
上の方にも一応「可能だとは思います」という返信なので・・・・

あくまでラギさんがそう考えたのかな？ってだけなんでご相談はお任せします

**Comment by kisaRagi05** [comment]
> できなくはないですが今までは役職アサイン後に計算量がO(n)で実装できていたものが役職セットアップ時に最良計算量O(n)、最悪計算量O(n!)の実装になってしまいます(nはプレイヤー数)
> 上の方にも一応「可能だとは思います」という返信なので・・・・

パン屋トレイターは絶対パン屋CO出来ないという状況になるだけなので
無くても大丈夫ですがあったら嬉しいですね

> 読みミスってました、すぐに追加します

ベント使用はジャッカルと同様の仕様でお願いします

**Comment by yukieiji** [comment]
> パン屋トレイターは絶対パン屋CO出来ないという状況になるだけなので
無くても大丈夫ですがあったら嬉しいですね

パン屋の表示は出せず、ベントは使用できる状態にしておきました
その状態で開発版に入ったためクローズします
