### ISSUE TITLE
[ニュートラル陣営] : トトカルチョ 

### ISSUE THREAD

**Issue by kisaRagi05** [yukieiji/ExtremeRoles#52]
### 役職名 / Role Name
トトカルチョ
### 役職の色 / Role color
TORのオポチュニストと同じ緑色、または金をイメージする黄色
### 役職の説明 / Role description
プレイヤーに賭けをして、そのプレイヤーが勝利したら便乗で勝利する役職
### 役職の能力 / Role ability

- 能力ボタン「賭ける」
ゲーム中に任意の生存者を賭けてその人が勝利するように支援や応援を行ったりします
使用回数は変更可能だが別の人を賭けると前回の人から賭け対象が変更となります
同じ人を何度も賭けて使用回数を消費する事も可能とする
使用回数が0回となると賭けた対象の役職が分かるようになる
- 会議中に賭け対象の選択や変更は出来ない（ボタン等が無い）
- キル、ベント、サボタージュはありません
- 単独勝利はありません
### 備考
- 死んでも勝機はあるので死んだら負け確定のオポチュニストより試合を楽しめると思われます
- 誰か勝者となるかを推理するので別方向の楽しみ方ができると思われます
### 確認
- 幽霊になってからも賭けボタンが機能出来るか

### 他陣営への影響 / Effect on other teams
クルーやインポスター、第三陣営の味方にも敵にもなります
脅威度はTORのオポチュニストや弁護士と同レベルとなります
クルーからもインポスター等からもTORのオポチュニストと同等扱いなので
トトカルチョCOしたら基本的に吊られます

### 陣営 / Team
- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
以前にも似たような能力や役職を提案されて以下の理由が解決出来ないので頓挫した記憶があります
- 人を対象にするというロジックをどうするのか
- クルー有利のAmongUs(非対称の人狼ゲーム全般)において、クルー側以外を対象にするメリットが無い
- 複数回対象を変更できると一回適当に誰か選択した後、生きていれば勝ちが決まりそうな陣営の人に選択をするだけで高い勝率をある程度キープ出来てしまう

他人の勝利に乗れる系の第三陣営としてはニートとヴィジランテが居ますが、上記の問題は以下で解決してます
- ニート：クルーにも敵対しやすいようにサボタージュが治せなかったりセキュが使えない
- ヴィジランテ：ヴィランやヒーローが落ちてるかどうかを確認する方法がない(ヒーローはCOしてれば確認できますが、先にどっちが落ちてるかなんて把握する方法はない、相打ちしている可能性もある)のでヴィジランテの発言の信憑性は薄くなります

**Comment by kisaRagi05** [comment]
> 人を対象にするというロジックをどうするのか

案としましては

1. サイドキックボタンと同様に試合中に近くの人を対象として発動
2. シェイプシフターと同様に任意のタイミングでタブレットを表示し相手を選ぶ
3. ゲーム開始時に(2)のタブレット画面が強制表示され必ず選ばなければいけない

この3点を選択方法として考えました

> クルー有利のAmongUs(非対称の人狼ゲーム全般)において、クルー側以外を対象にするメリットが無い
> 複数回対象を変更できると一回適当に誰か選択した後、生きていれば勝ちが決まりそうな陣営の人に選択をするだけで高い勝率をある程度キープ出来てしまう

確かに、序盤でクルーを賭け対象に選択からの後半でマズくなったら
キル陣営に乗り移るとかもありまして全然賭博をしている感がありません
ボタン形式なら回数とかがあり、賭博な役職としては勝利した時の快感が少な目です

なので変更等としまして

- ゲーム開始時に選択画面が強制表示され必ず選ばなければいけない
  - 選択画面表示中は行動不可能にする
  - 制限時間があり、誰も選ばない場合はランダムで賭け対象が決定される
  - 選択画面はシェイプシフターの画面を使い回す感じで出来ますでしょうか？
- 賭け対象者の役職は見えない
  - 立ち回りも賭け対象の役職がハッキリしない限り決めるのが難しい
  - そのため序盤はクルーやインポスターや第三陣営の味方もできず中途半端な行動となってしまう
- 誰に賭けたか忘れない為に名前の横に＄マーク（お金の記号）を表示する
  - この表示は自分にしか見えず賭け対象者や他の人からは見えない

この内容に変更してみます

**Comment by yukieiji** [comment]
> ゲーム開始時に選択画面が強制表示され必ず選ばなければいけない
選択画面表示中は行動不可能にする
制限時間があり、誰も選ばない場合はランダムで賭け対象が決定される
選択画面はシェイプシフターの画面を使い回す感じで出来ますでしょうか？

これは初期ボタンが直ぐ押された時の処理であったり、選択中にキルされた時の処理をどうするか考える必要が出てきます(スポーン等も人の通信速度等にも影響されますので)
あと選択中止まっている時間で役職が即バレしそうですが問題ないでしょうか(バレてとりあえず吊っときましょうってなりませんか)

あと自分では防げない要因で賭けた対象の陣営の敗北が確定すると何も出来ないし干渉できない役職になりますがそれで大丈夫でしょうか

**Comment by kisaRagi05** [comment]
> 初期ボタンが直ぐ押された時の処理

制限時間前に会議や通報が発生した場合は会議後に再度選択（制限時間は戻る）とかにするといいと思います

> 選択中にキルされた時の処理

1. 幽霊になっても改めて選択できる
2. キルしてきた相手が賭け対象となる
3. ランダムで賭け対象が決定される

希望は番号順となります

> あと選択中止まっている時間で役職が即バレしそうですが問題ないでしょうか(バレてとりあえず吊っときましょうってなりませんか)

あぁ確かに、これは逆に選択中も動けるとかにしたほうがいいかもしれないですね
タスクの位置に動いてから選択とかにする感じで
逆に動けるというのは実現可能でしょうか？

> あと自分では防げない要因で賭けた対象の陣営の敗北が確定すると何も出来ないし干渉できない役職になりますがそれで大丈夫でしょうか

ジェスターバレしたジェスターのような状態と思ってますのでそれは良いと思います
でも有り金全部賭けて負けて自棄で命を絶つ的な意味で（最悪な表現）
自爆ボタンがあってもいいかもしれないですね
負けが確定なので変な所で自爆して余計な嫌がらせをするとか
賭け対象の陣営以外に混乱を与えたりとか

**Comment by yukieiji** [comment]
今ソースコードを確認しましたけどシェイプシフターの画面を持ってくることは技術上不可能でした

> ジェスターバレしたジェスターのような状態と思ってますのでそれは良いと思います

EXRolesのジェスターは暴発という能力を持ってるので消さない限り悪質な嫌がらせが続きます(その結果、推理が変わる可能性もあると思います)
なので、ジェスターバレしたジェスターより、ジャッカルが落ちてもバグで昇格しなかったサイドキックの方が的確かもしれないです

**Comment by kisaRagi05** [comment]
> 今ソースコードを確認しましたけどシェイプシフターの画面を持ってくることは技術上不可能でした

何か代わりの全プレイヤー表示＆選択方法とかありますでしょうか？
無ければサイドキックボタンのようにするか、会議画面で選択するかになりますね
どれでも賭けですので1回限りとしましょう

> EXRolesのジェスターは暴発という能力を持ってるので消さない限り悪質な嫌がらせが続きます

自身の勝利は出来なくなったが嫌がらせをするという機能が何か必要ならば
先ほど記入した自爆ボタンにしましょう

- 自分自身は生き残る必要性はそこまで無いのでいつ使っても良い
- クルーだらけの場所で自爆して議論や推理を乱したりする
- どの陣営相手にもキル容疑を与えることが出来る
- 賭け対象がクルーなら使う必要は無い

**Comment by yukieiji** [comment]
> 何か代わりの全プレイヤー表示＆選択方法とかありますでしょうか？

ない気がします

> 無ければサイドキックボタンのようにするか

ボタンにすると最後に勝ちが決まりそうな陣営の人に選択をするって感じになります

> 会議画面で選択するかになりますね

会議画面の処理はあんまりいじりたくないです・・・・
どちらにせよ最後に勝ちが決まりそうな陣営の人に選択をするって感じがします

> 自身の勝利は出来なくなったが嫌がらせをするという機能が何か必要ならば

嫌がらせが必要というか、ジェスターに取って嫌がらせをし続けるメリットは有るという部分があります(以下理由)
- ジェスターが「暴発」を使い続ける意味
  - 特殊勝利無効化時
    - 「暴発」は脅し材料として使え、最後に吊ってもらえることもある(なのそんでありました)
  - 特殊勝利有効化時
    - 「暴発」で議論が混乱化して推理が変わる可能性もある

**Comment by kisaRagi05** [comment]
> 全員のボタン的なものを用意するってのを一つ思い浮かびましたが
最後に勝ちそうな人を選択でほぼ勝ちが決まるという問題が未解決になってしまいます
会議画面の処理はあんまりいじりたくないです・・・・
結局これも最後に勝ちそうな人を選択でほぼ勝ちが決まるという問題が未解決になってしまいます

- 試合開始時に任意で選べるようにする
- 最後まで温存させない為に制限時間等を与える
- それにより開始時～序盤にしか賭け対象を選べないようにする

この3つが必要となりますが
全員のボタン的な物を用意して強制表示して制限時間を付与しないと
実現は難しそうですね
最初からシステム側で選んでもらうのも役職のコンセプトが異なる気がしますし

> 嫌がらせが必要というか、ジェスターに取っても嫌がらせをし続けるメリットは有るという部分があります
> あと自分では防げない要因で賭けた対象の陣営の敗北が確定すると何も出来ないし干渉できない役職になりますがそれで大丈夫でしょうか

インポスターの人に賭けてインポスターが全滅宣言されたりしても
それが嘘かもと抗ったり、負け確定なのが分からず最後まで足掻いて
試合終了後に判明するとかもありますので
別の勝利条件を追加とかは不要で大丈夫です

> PS.これ忘れてましたが動けるようにして任意に選択できるようにするとゲーム開始時に一人選ばせるというロジック全体が破綻する気がします

これはやはり行動停止として速攻で選ぶ作戦をしてもらうしかないですね
試合時に沸いた後数秒停止後に動き出すとかどの陣営でもやりますし
多少の誤魔化しは通用するはずです

**Comment by yukieiji** [comment]
> インポスターの人に賭けてインポスターが全滅宣言されたりしても
それが嘘かもと抗ったり、負け確定なのが分からず最後まで足掻いて
試合終了後に判明するとかもありますので
別の勝利条件を追加とかは不要で大丈夫です

個人的にはゲーム開始して最速10秒で敗北が確定する可能性があるという部分があるので、新しい勝利条件や何かが欲しいと思います

**Comment by kisaRagi05** [comment]
> 個人的にはゲーム開始して最速10秒で敗北が確定する可能性があるという部分があるので、新しい勝利条件や何かが欲しいと思います

最速10秒で敗北確定とは例えば賭け相手が10秒でキルされて負け確定とかでしょうか？

何か賭け事に関する他の勝利条件は考えておきます
新しい何かとなると賭け事としてはイカサマとかですかね
具体的な能力詳細が整理できたら改めて記入します

**Comment by melonjagaimo** [comment]
トトカルチョを幽霊役職にするのはどうでしょうか。

・どのような死因であれ、死んでしまったニュートラル陣営がなるニュートラル陣営幽霊役職。
・ただしジャッカル、サイドキックなどの「自身が死亡した瞬間に敗北確定、とはならない」ニュートラル陣営からは派生しない。

・自身が生きていた時の情報をもとに、勝ちそうなプレイヤーを対象に能力を使用して賭ける。
・そのプレイヤーが勝てばあらゆる陣営の勝利に便乗して勝利できる。

**Comment by kisaRagi05** [comment]
> 新しい何かとなると賭け事としてはイカサマとかですかね

「イカサマ」能力としましては

- 試合開始後の賭けをして、賭け対象が死亡後の会議後に「賭け」が「イカサマ」に変化
- 賭け対象を変更する（方法は最初に賭け対象を選ぶと同じ内容）
- クールタイムの計算を「死亡者数」×「設定秒数」×「イカサマ使用回数(n％)」とする
  - 試合序盤なら数秒で賭け対象を変更できる
  - 試合が終盤になればなるほどクールタイムが伸びて変更が難しくなる
- 死亡した賭け対象の陣営が勝つと信じて使用しなくても良い

これで終盤まで生き残って勝てそうなのを選んで簡単に勝利というのも難しくなると思います

> トトカルチョを幽霊役職にするのはどうでしょうか。

それもありですね
賭け対象を幽霊で見守り応援するというので暇を何とかできる気がします

**Comment by yukieiji** [comment]
> 試合開始後の賭けをして、賭け対象が死亡後の会議後に「賭け」が「イカサマ」に変化

確認です
「賭け」は14人分ボタンを用意して、それを選択する形になるのでしょうか、それとも1つの能力ボタンで対象に対して使用するものなのでしょうか
その能力がどんな感じのものになるのでしょうか(ボタンの数がどうなるのかとか)

> クールタイムの計算を「死亡者数」×「設定秒数」×「イカサマ使用回数(n％)」とする

このクールタイムは「賭け」が出来るクールタイムで問題ないですか
あとは「死亡者数」より「1.0 + 生存者に対する死亡者率」の方が人数が少ないルールにも応用できるはずです

> これで終盤まで生き残って勝てそうなのを選んで簡単に勝利というのも難しくなると思います

これが大きな問題点でしたが、クールタイムの計算式を死亡者率や使用回数でバランスが取れる気もしなくはないので対象に対して使用する能力として実装してクールタイムがリアルタイムに変わるようにするってのが一番楽な実装にはなる気がします

> トトカルチョを幽霊役職にするのはどうでしょうか。
賭け対象を幽霊で見守り応援するというので暇を何とかできる気がします

通常の能力ボタン以外のクールタイムタイマーを更新するようなインターフェースは幽霊役職は持たない実装にするで決定していた気がするのでこれは難しい気がします(通常の役職だとIRoleUpdateという毎回更新するようなインターフェースをもたせれば出来るのですが、幽霊役職は通常役職のインターフェースは持たせない、かつパッシブ能力は持たせないという話で進んでいるはずです)

**Comment by kisaRagi05** [comment]
> 確認です
「賭け」は14人分ボタンを用意して、それを選択する形になるのでしょうか、それとも1つの能力ボタンで対象に対して使用するものなのでしょうか
その能力がどんな感じのものになるのでしょうか(ボタンの数がどうなるのかとか)

最初の「賭け」は14人分ボタンを用意しての選択が良いと思います
「イカサマ」は下記の内容でイメージしています

1. 「イカサマ」で「賭け」の14人ボタンが復活、再度選択可能になる
2. 「イカサマ」で誰にも賭けてない初期状態にリセットし、再度選択可能になる
3. 「イカサマ」に関しては「賭け」と異なりサイドキックにするように近くの人を選ぶ仕組みにする

1と2の違いは途中に「イカサマ」と「賭け」の途中にリセットが入るか入らないかの違いだけです

> このクールタイムは「賭け」が出来るクールタイムで問題ないですか
あとは「死亡者数」より「1.0 + 生存者に対する死亡者率」の方が人数が少ないルールにも応用できるはずです

人数が少ないルールでも応用できるようにそれでいきましょう

> これが大きな問題点でしたが、クールタイムの計算式を死亡者率や使用回数でバランスが取れる気もしなくはないので対象に対して使用する能力として実装してクールタイムがリアルタイムに変わるようにするってのが一番楽な実装にはなる気がします

これは上記の3の内容になりますね
終盤ではクールタイムも伸びて遭遇率も下がり、能力使用が難しくなるが
負け確定には至ってないので色々頑張る事は出来るので適切かと思います

> 通常の能力ボタン以外のクールタイムタイマーを更新するようなインターフェースは幽霊役職は持たない実装にするで決定していた気がするのでこれは難しい気がします(通常の役職だとIRoleUpdateという毎回更新するようなインターフェースをもたせれば出来るのですが、幽霊役職は通常役職のインターフェースは持たせない、かつパッシブ能力は持たせないという話で進んでいるはずです)

幽霊役職の仕様については詳しく確認していないので
トトカルチョに似たようなのを実装したい人がいましたら
その人にお任せしたいと思います

**Comment by yukieiji** [comment]
> これは上記の3の内容になりますね
終盤ではクールタイムも伸びて遭遇率も下がり、能力使用が難しくなるが
負け確定には至ってないので色々頑張る事は出来るので適切かと思います

これは「賭け」も「イカサマ」も同じ上記3の能力にしてしまって最初から「誰か一人の対象を取る」という能力で行くのが楽だしシンプルで説明しやすい役職になるかなって思っただけです(多分そちらのほうが実装的にも楽 + アクション要素もあるのでいい気がします)
クールタイムはゲームが進むに連れて増えていくという仕様にすれば問題は無いとは思われますし

**Comment by kisaRagi05** [comment]
> これは「賭け」も「イカサマ」も同じ上記3の能力にしてしまって最初から「誰か一人の対象を取る」という能力

トトカルチョの最初に考えたやりかたですね
シンプルなのも重要なので両方3の能力にしましょう

そしてクールタイムがゲームが進むにつれて伸びるのは結構ユニークさがあって良いかなと思いました

**Comment by yukieiji** [comment]
> そしてクールタイムがゲームが進むにつれて伸びるのは結構ユニークさがあって良いかなと思いました

デフォルトでどれくらいを設定するのかを決める必要があると思います

**Comment by yukieiji** [comment]
> 「1.0 + 生存者に対する死亡者率」
15人回なら5人で1.0+33.3　クールタイム34.3秒
最終局面にて12人　1.0+80　クールタイム81秒

これだとボタンの初期クールを伸ばすと全体も伸びて、減らすと全体も減るので調整がしにくい気がします
多分これは以下のような計算式にすると問題ない気がします(xが現在のボタンクールタイム、zが最終クールタイム、yがデフォルトのクールタイム)

$$ x = (z - y) (1.0 + (生存者数/プレイヤー数)) $$

あとこの式とラギさんの提案された式の問題点があるとするなら人外が最初に落ちてクルー9人 vs 赤1 vs 青1とかの盤面だと簡単にクルーに乗り換えれる点でしょうか

**Comment by yukieiji** [comment]
あと最後に考えないといけないことを忘れていました
妖狐とかヴィジランテ、ヤンデレの片思い人等を対象にした場合どうするのかを考えないといけない気がします(ヤンデレの片思い人は頑張ったら取れるとは思います、それ以外は処理の順番的にキツイ気がします)

**Comment by kisaRagi05** [comment]
> 多分これは以下のような計算式にすると問題ない気がします(xが現在のボタンクールタイム、zが最終クールタイム、yがデフォルトのクールタイム)

これでいきましょう

> あとこの式とラギさんの提案された式の問題点があるとするなら人外が最初に落ちてクルー9人 vs 赤1 vs 青1とかの盤面だと簡単にクルーに乗り換えれる点でしょうか

レアケースな盤面としてはありえるわけですが、このケースにも対抗できる設定を考えるのは余計な気がします
この場合は運が良かった程度でいいんじゃないでしょうか

> 妖狐とかヴィジランテ、ヤンデレの片思い人等を対象にした場合どうするのかを考えないといけない気がします(ヤンデレの片思い人は頑張ったら取れるとは思います、それ以外は処理の順番的にキツイ気がします)

ヤンデレの片思い相手は処理的に可能なら、無理なら大丈夫です
妖狐は第三陣営の勝利含め全部奪う仕組みなので、妖狐を賭け対象にしてもトトカルチョの勝利も奪う事にしましょう
ヴィジランテは詳しくないのでわかりません、キツイようでしたら対応しなくていいと思います

**Comment by yukieiji** [comment]
あと考えるべきことといえばこの役職をどのバージョンに入れるかでしょうか([マイルストーン](https://github.com/yukieiji/ExtremeRoles/milestones)に一応のリリース予定があります、v2.2.0.0:6月10日、v3.0.0.0:6月24日)
予定の遅れなしで実装するなら7/15リリース予定のv3.1.0.0、他のバージョンに合わせてほしいとのことであればその合わせたバージョンの後のバージョンが遅れます(特にサブマージドに合わせるとそのリリースが遅れます)

**Comment by kisaRagi05** [comment]
こちらも特に急ぐ気も希望もありませんので、7/15で良いと思います！

**Comment by yukieiji** [comment]
マイルストーンをv3.1.0.0、優先度を低に設定します

**Comment by yukieiji** [comment]
v3.2.0.0ブランチにマージされたためクローズ
