### ISSUE TITLE
[インポスター陣営] : パワーロード

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#56]
### 役職名 / Role Name
パワーロード

### 役職の色 / Role color
インポスター陣営なので赤色

### 役職の説明 / Role description
パワーをチャージすることで通常のキルボタンで複数人キルできるようになるインポスター陣営

### 役職の能力 / Role ability

キルクールタイムが明けている状態でのみ能力を使用可能。
能力ボタンを押すとその場で静止してパワーチャージが開始される。2段階までチャージ可能。
再度能力ボタンを押すことでチャージを中断できる。1段階目のチャージが完了してから中断すると次のチャージは2段階目のチャージから始まる。
完了したチャージ段階は本人だけが常に把握でき、キルボタンを押すまでリセットされない。
チャージ能力のクールタイムは、キルクールタイムが明けてからのみカウントされる。

パワーがチャージされた状態でキルボタンを押すと、その時のチャージ状況に応じて複数人キルできる。キルワープは最も遠いキル対象に移動する。
チャージしていない：通常通り1人まで
1段階目のチャージが完了：2人まで
2段階目のチャージが完了：3人まで

ただしチャージ状態でのキルを実行した場合、キルできた人数にかかわらず次のキルクールタイムが増加する。
増加量はデフォルトキルクールタイムの一定割合で、2段階目のチャージが完了していた場合、1段階目のチャージが完了していた場合の2倍の遅延効果を受ける。
この効果で増加したキルクールタイムはキルクールタイムが明けるまでリセットされない。

例1：デフォルトキルクールタイム20秒、遅延効果75％、1段階目のチャージが完了していた場合
20+(20×0.75×1)=35秒

例1：デフォルトキルクールタイム25秒、遅延効果100％、2段階目のチャージが完了していた場合
25+(25×1.00×2)=75秒

#### 能力のメリット
1人でダブル・トリプルキルできる
終盤、一気にPP圏内に持って行ったりフィニッシャーになりやすい

#### 能力のデメリット
チャージ中は移動できないので浮き位置からの冤罪吊りの標的になる危険性あり
チャージを温存して通常のキル、ができないので最大人数をキルしようとして抱え落ちする恐れあり
チャージ状態でのキル後、キルクールタイムが明けるまでの時間に会議を連発されるとキルできない

#### 固有の設定項目
1段階目のチャージが完了するまでの時間（秒）
2段階目のチャージが完了するまでの時間（秒）
チャージ能力のクールタイム（秒）
チャージを中断した場合のチャージ能力のクールタイム（秒）
チャージ状態でのキル後のクールタイム遅延効果（％）

#### 同じく範囲攻撃を持つボマーとの相違点
パワーロードが優れている点：自滅しない・範囲内の指定人数までのクルーを（タイムマスターのシールド等は考慮しない場合）確実にキルできる・待ち時間が固定
ボマーが優れている点：直接の現行犯を見られない・通常のキルと範囲攻撃を使い分けられる・運任せとはいえ4人以上キルできる場合もある

### 他陣営への影響 / Effect on other teams
何人かで固まっての移動にリスクが生まれる

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 再度能力ボタンを押すことでチャージを中断できる。1段階目のチャージが完了してから中断すると次のチャージは2段階目のチャージから始まる。

フェイクタスクしながらチャージをすれば簡単に2段階くらい溜まりそうなのですがどうでしょうか

> パワーがチャージされた状態でキルボタンを押すと、その時のチャージ状況に応じて複数人キルできる。キルワープは最も遠いキル対象に移動する。

複数人のキル対象をセットするのはキルボタンの仕様上不可能なのでそれをどうするかという問題があります

**Comment by melonjagaimo** [comment]
キルボタンを強化するタイプのインポスター陣営でしたが技術的に難しそうですね
クローズします
