### ISSUE TITLE
???:クルー陣営(自分がキルされた時の能力)

### ISSUE THREAD

**Issue by Nushigami** [yukieiji/ExtremeRoles#6]
### 役職名 / Role Name
(決めてない)
### 役職の色 / Role color
(決めてない)
### 役職の説明 / Role description
・キルされると数秒後に自身の死体の方向を知らせるクルー役職。
### 役職の能力 / Role ability

・自身がキルされると、数秒後(初期設定10秒)に自身の死体のある方向を全プレイヤーに表示させる。
 `メリット`
・矢印が出るため長い間、死体が見つからないということがない。
・別の死体が通報されても矢印の方向である程度場所がわかる。
`デメリット`
・キルされないと能力を発動できない。
・キルされてもすぐ矢印が出ないため、すぐに会議が挟まったり、死体を消されると能力が発揮できない。
・全プレイヤーに表示されるため、クラッカーや、エボルバー等に死体の位置がバレる。
### 他陣営への影響 / Effect on other teams
キル役職に影響が出ると思います。
### 陣営 / Team
- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
デメリットが少ないのでベイトとあんまり変わらないですし、何ならベイトでキル役職に10秒後に自動通報されるとかのほうがバランスが取れてる気がします

**Comment by Nushigami** [comment]
やっぱりデメリット少ないですよね、、、

> 10秒後に自動通報される

それだと知らずにベイト噛んだインポスターが他のプレイヤーとすれ違った後に自動通報されたら現行犯と何ら変わりないような気がします。

**Comment by yukieiji** [comment]
> それだと知らずにベイト噛んだインポスターが他のプレイヤーとすれ違った後に自動通報されたら現行犯と何ら変わりないような気がします。

一応インポスター側にも何秒後に通報されますよって通告を出すって感じですけどね

**Comment by Nushigami** [comment]
>一応インポスター側にも何秒後に通報されますよって通告を出すって感じですけどね

あっそかぁ 元のベイトよりかは心臓に良さそうなのかな?

**Comment by Nushigami** [comment]
もう思い浮かばないのでクローズしときます。
