### ISSUE TITLE
[ニュートラル] : マイナー/Miner (地雷で遠隔キル出来る役職)

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#60]
### 役職名 / Role Name

マイナー/Miner

### 役職の色 / Role color

濃いめの緑

### 役職の説明 / Role description

地雷で遠隔キルをする役職
ベント使用可能

- 勝利条件
  - 自分以外の生存者が一人で他の人がクルーか無害な第三陣営(ニート等)の時

### 役職の能力 / Role ability

- 地雷設置
  - ボタンを押してから数秒後に地雷が設置され、有効化される
- 地雷
  - 近くに来たプレイヤー1人を問答無用(アサシンの場合はニュートラルからのキル可能設定時のみ)を吹き飛ばす
     - 複数人来た場合はランダムで1人吹き飛ばす  
  - キルアニメーションはマイナーの人のモーション(探偵で調査しやすい)
  - 自分も巻き込まれる
  - 自分も他人にも見えない
  - 会議で消えない
  - 一度起動したらその地雷は撤去される
  - マップに複数設置可能
  - 会議後10秒間作動しない(オプションで設定可)
  - マイナーの人が消えると全部解除される
  - ベント使用可

- 推理要素的な部分
  - 自分も巻き込まれるため、地雷付近で挙動が不審な人が出てくる
  - 人から離れるような動きを取りやすい人がマイナーの可能性が高い
    - 地雷を設置したい + 一緒に動いて巻き込まれたくない

- ミッショナリーとの差別化部分
  - 自発的にキルできない
    - ボタンを押して確実に殺せないけど、ミッショナリーより追いにくい
    - 設置した地雷が確実に発動する保証はない
  - 決闘になった時の勝率は高い(近づく必要がなく設置した場所に誘導すれば勝てる)
  - 自決してしまう可能性もある

### 他陣営への影響 / Effect on other teams
- 他陣営的には移動経路を簡易的に塞がれるのでむちゃくちゃうざい

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by melonjagaimo** [comment]
地雷が時間で消えない場合、サボタージュ修復の場所（例えば通信室の機器の前）に置くとサボタージュがいつまでも直らず、簡単にゲームが傾いてしまうように思います

これを防止するために、特定の範囲内には置けない設定はできますかね？

**Comment by yukieiji** [comment]
> 地雷が時間で消えない場合、サボタージュ修復の場所（例えば通信室の機器の前）に置くとサボタージュがいつまでも直らず、簡単にゲームが傾いてしまうように思います

一回誰かが犠牲になれば会議で詰めれるから問題ないって思ってます(これがインポスターなら問題ないと思いますが)、そこで発動されれば地雷は撤去されますし
治さなかったらサボタージュ付近に居た(そっちの方面から歩いてきた)人はマイナーの可能性は非常に高いという推理も出来ます
マイナーはベント使えるので衝突も怖くはないでしょう

**Comment by Nushigami** [comment]
仕様の確認ですけど

1. 地雷はマップ上に複数個設置できるのか
2. 地雷は会議後有効になるのか即座に有効になるのか(直後に有効の場合、自身が即座に踏んで自爆してしまうため数秒間は無効化しないといけないが)
3. 同時に踏んだ場合の処理はどうするのか

**Comment by melonjagaimo** [comment]
ああ、1度発動したら消えるのですね。
それならそこまで膠着はしないですね

**Comment by yukieiji** [comment]
> 地雷はマップ上に複数個設置できるのか

複数個設置できます

> 地雷は会議後有効になるのか即座に有効になるのか(直後に有効の場合、自身が即座に踏んで自爆してしまうため数秒間は無効化しないといけないが)

上にある通りボタン発動して数秒後に地雷が設置され有効になります

> 同時に踏んだ場合の処理はどうするのか

同時に踏んだってのはどういうことでしょうか複数人で同時に地雷のキル範囲に入った処理でしょうか
それはランダムに一人吹き飛ばします

**Comment by Nushigami** [comment]
了解です

**Comment by yukieiji** [comment]
v3.2.0.0ブランチにマサージされたためクローズ
