### ISSUE TITLE
[ニュートラル陣営] : モンスターラーヴァ (食べ物や死体を食べて完全体を目指そう)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#61]
### 役職名 / Role Name
モンスターラーヴァ

### 役職の色 / Role color
暗めの茶色

### 役職の説明 / Role description
食べ物や死体を食べて一定数の栄養を得ると勝利する
TORのヴァルチャーを、能動的にかつ終盤でも勝利に向かえるよう改変した

#### 勝利条件
食べ物や死体を食べて栄養を一定数集めると単独勝利
例：栄養15点で勝利
食べ物1個1点・死体1個3点

#### 能力「食べる」
マップ上の食べ物や死体を食べて栄養を獲得する。能力を発動して一定時間対象の近くにいるとそれを食べて、食べ物や死体が消える。

#### 「食べ物」
モンスターラーヴァのアサイン率が0ではない場合、ゲーム開始時にマップ上に食べ物がポップし、会議ごとに減った分が補充される。モンスターラーヴァが脱落しても食べ物は出続ける。
他のプレイヤーは食べ物に一定時間接近すると食べることができる。他のプレイヤーが食べる場合、モンスターラーヴァより食べるのが少しだけ遅い。
モンスターラーヴァ以外のプレイヤーが食べた場合、食べたものによって異なる効果を得る。

肉・栄養ドリンク:少しの間視界が広くなる
果物・お菓子:その時発生している能力クールタイムが短縮される
ベントは使えるが、キル・サボタージュ発動は不可能。

クラッカーによって通報できなくされた死体は食べられる。
キャリアーによって運ばれている途中の死体は食べられない。
フェイカーによって作成された偽物の死体も食べられない。

#### 固有の設定項目
勝利に必要な栄養:10〜30
食べ物の栄養:1〜3
死体の栄養倍率:1〜3
食べ終わるまでの時間（秒）
食べるクールタイム（秒）

他のプレイヤーが食べる追加の時間（秒）
マップ上の食べ物の数:3〜5（個）
食べ物で視界が広くなる時間（秒）
食べ物で広くなる視界倍率
食べ物で短くなる能力クールタイム（秒）

### 他陣営への影響 / Effect on other teams
食べ物をモンスターラーヴァや敵より先に食べることで有利に進められるため、他のプレイヤーは片手間にでも食べ物を取りに行くことが予想される。
また食べ物を食べる現場を見られた場合、食べる時間が短いように見えたから彼はモンスターラーヴァなのか、あれは食べてる途中だったから私はモンスターラーヴァじゃないなどの議論が発生する。

死体に食べ物より多い栄養が設定されている場合、インポスターによる死体消しのための通報や会議ボタンが起きやすくなるかもしれない

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 早い話が、TORのヴァルチャー

TORのヴァルチャーをExRoleに実装を行っていない理由は以下です、これを解決できない(主に1番が大きい)とこの役職も実装でないと思います
1. キル能力を持つ他人任せの職であるがゆえに、能動的に動けない、受動的になってしまう(キルが起きないと何も出来ない)
2. ゲーム終盤になればなるほど勝ち筋が無くなっていく
3. クルーに100害はあるけどインポスターへの害が少ない(あんまり考えなくてもいい気がするけど)

**Comment by melonjagaimo** [comment]
そう言われると、受け身なのはまずいかも知れませんね。
改善案としては
①キル能力。ただしこの役職がキル役職扱いになると強すぎるので、特殊キル扱いにする。
一定時間死体を捕食できないでいると飢えで暴走して一時的に特殊なキル能力が解禁される。キル能力使用で暴走は治まる。

②死体探知の能力で、消えた死体を復活させて食べられるようにする。

が浮かびました。

**Comment by yukieiji** [comment]
> ①キル能力。ただしこの役職がキル役職扱いになると強すぎるので、特殊キル扱いにする。
一定時間死体を捕食できないでいると飢えで暴走して一時的に特殊なキル能力が解禁される。キル能力使用で暴走は治まる。
 ②死体探知の能力で、消えた死体を復活させて食べられるようにする。

この2つは結局、人が減ってくると勝利できなくなってしまいます
最初に動かないと勝てないし、温存するメリットがないっていう問題点です

**Comment by melonjagaimo** [comment]
最初に動かなくても勝てるような能力ですか。

それでしたら勝利条件を「一定回数の会議を生き残ること」に変更し、自然に成長する要素を追加するのはどうでしょうか。
自分が生き残った会議終了後に1点、更に死体を食べるごとにボーナス得点を得られるようにすればいいと思います。

例:8点取ると勝利。会議1回を生き残ると1点、死体を食べると1つにつき2点得る

**Comment by yukieiji** [comment]
> それでしたら勝利条件を「一定回数の会議を生き残ること」に変更し、自然に成長する要素を追加するのはどうでしょうか。
自分が生き残った会議終了後に1点、更に死体を食べるごとにボーナス得点を得られるようにすればいいと思います。

前も合ったのですがこれは役職のコンセプトと合っているのかという疑問が出てきます

**Comment by melonjagaimo** [comment]
会議を生き残るごとにこっそり食料をくすねるイメージで「生き残るごとに自然成長」を付け足したのですが、いけませんでしたか？

**Comment by yukieiji** [comment]
> 会議を生き残るごとにこっそり食料をくすねるイメージで「生き残るごとに自然成長」を付け足したのですが、いけませんでしたか？

TORの弁護士の会議勝利のようにとりあえずボタンだろうが何だろうが会議を起こそうってなりませんか・・・

**Comment by melonjagaimo** [comment]
そうなってしまう気がしますね。

……ダメです、自分なりに考えましたがどう頑張っても全ての問題（能動的に、能力ボタンなしで、生きてる限り詰まない）を同時に解決はできませんでした。クローズします。

**Comment by yukieiji** [comment]
> ……ダメです、自分なりに考えましたがどう頑張っても全ての問題（能動的に、能力ボタンなしで、生きてる限り詰まない）を同時に解決はできませんでした。クローズします。

能力ボタンをなしにする必要もないとは思いますよ、別のなにか解決できそうな能力があればそれを追加するのも一つだと思います

何かあればまたこのチケットに書き込んで下さい、再オープンします

**Comment by melonjagaimo** [comment]
能力ボタンを使わないで、というのは能力ボタンを「死体を食べる」に使うからという意味で書きました。
なにか解決できそうなら書き込んで再度オープンしますね

**Comment by melonjagaimo** [comment]
能力ボタンを「食べる」のままにして問題を解決できそうな仕様を考えました！
見ての通り現在オープンして議論中のファントムシーフとモロ被りなので、もしファントムシーフの方が実装してもいいとなればこちらは凍結されます。逆にこちらを実装するならファントムシーフの方が凍結されます。

以下が新しいモンスターラーヴァです。

役職名:モンスターラーヴァ
色:暗い茶色
要約:食べ物や死体を食べて完全体を目指す魔物の幼体。ニュートラル陣営

勝利条件
栄養を一定値ためるとその瞬間、単独勝利。
例:栄養15点貯めれば勝利
食べ物:1点
死体:3点

能力「食べる」
マップ上の食べ物や死体を食べて栄養を獲得する。捕食を発動して一定時間対象の近くにいるとそれを食べて、食べ物や死体が消える。

「食べ物」
モンスターラーヴァのアサイン率が0ではない場合、ゲーム開始時にマップ上に食べ物がポップし、会議ごとに減った分が補充される。モンスターラーヴァが脱落しても食べ物は出続ける。
他のプレイヤーは食べ物に一定時間接近すると食べることができる。他のプレイヤーが食べる場合、モンスターラーヴァより食べるのが少しだけ遅い。
モンスターラーヴァ以外のプレイヤーが食べた場合、食べたものによって異なる効果を得る。

肉・栄養ドリンク:少しの間視界が広くなる
果物・お菓子:その時発生している能力クールタイムが短縮される

他陣営への影響
食べ物をモンスターラーヴァや敵より先に食べることで有利に進められるため、他のプレイヤーは片手間にでも食べ物を取りに行くことが予想される。
また食べ物を食べる現場を見られた場合、食べる時間が短いように見えたから彼はモンスターラーヴァなのか、あれは食べてる途中だったから私はモンスターラーヴァじゃないなどの議論が発生する。


固有設定項目
勝利に必要な栄養:10〜30
食べ物の栄養:1〜3
死体の栄養倍率:1〜3
食べる時間（秒）
食べるクールタイム（秒）

他のプレイヤーが食べる追加の時間（秒）
マップ上の食べ物の数:3〜5（個）
食べ物で視界が広くなる時間（秒）
食べ物で広くなる視界倍率
食べ物で短くなる能力クールタイム（秒）

**Comment by yukieiji** [comment]
> 能力ボタンを「食べる」のままにして問題を解決できそうな仕様を考えました！
見ての通り現在オープンして議論中のファントムシーフとモロ被りなので、もしファントムシーフの方が実装してもいいとなればこちらは凍結されます。逆にこちらを実装するならファントムシーフの方が凍結されます。

ファントムシーフでこれを目指したいのか、モンスターラーヴァーでこれを目指したいのかどっちでしょうか
モンスターラーヴァーは別でやりたいって言うのであればチケットは残しますが

**Comment by melonjagaimo** [comment]
個人的な意見としてはモンスターラーヴァの方が絵面的にもいい役職になるのではないかと思うのです
なので今どちらの提案を推すかを選ぶならモンスターラーヴァを選びますね

**Comment by yukieiji** [comment]
> 個人的な意見としてはモンスターラーヴァの方が絵面的にもいい役職になるのではないかと思うのです
なので今どちらの提案を推すかを選ぶならモンスターラーヴァを選びますね

ではシーフの方をクローズしてもらっていいですか？

**Comment by melonjagaimo** [comment]
言われてみると推理要素はなさそうですね。
推理要素の観点で言えば、例えばモンスターラーヴァが食べ物や死体を食べた場合、少しの間食べかすが残るのはどうでしょうか。

食べ物に近づくだけ、と書いたのはマップ上の食べ物に全プレイヤー共通の使用ボタン（タスクをしたり緊急直したりするのに使うボタン）を適用できるか不明だったためです。

**Comment by yukieiji** [comment]
> 例えばモンスターラーヴァが食べ物や死体を食べた場合、少しの間食べかすが残るのはどうでしょうか。

それが見つけられなかったら分からないのが問題な気がします

> 食べ物に近づくだけ、と書いたのはマップ上の食べ物に全プレイヤー共通の使用ボタン（タスクをしたり緊急直したりするのに使うボタン）を適用できるか不明だったためです。

使用ボタンを適用するのは難しいはずです

**Comment by melonjagaimo** [comment]
推理要素を加えるとなると
・食べ物の出る場所を固定
・食べ物の状況は会議中マップで把握可能（モンスターラーヴァが食べたことも把握可能）

このようなことが考えられます。


使用ボタンの適用は難しいですか。それなら一定時間の接近で食べられる仕様はそのままでいいです。

**Comment by yukieiji** [comment]
> 推理要素を加えるとなると
・食べ物の出る場所を固定
・食べ物の状況は会議中マップで把握可能（モンスターラーヴァが食べたことも把握可能）

そうするとこれを実装するために会議中にマップを開ける機能が必要になって時間がかかります

**Comment by melonjagaimo** [comment]
会議中のマップ表示は現状未実装でしたか、失礼しました。

ところで、貴方がTwitterに書いた「ExR版ヴァルチャーの案」はどのようなものですか？
一応、この役職も元々はTORのヴァルチャーをExRに実装しようとして提案したものですから、もしそちらの方が現実的ならこのチケットをクローズしますが…

**Comment by melonjagaimo** [comment]
では、一旦こちらのチケットは現状手詰まり気味なのでクローズします。
そちらの案が詰まったりしたら、そちら側で発生した問題の改善法を引っ提げて再度オープンしますね。
