### ISSUE TITLE
[インポスター陣営] : ドゥーム (吊れなかった相手を追跡し消滅させるインポスター)

### ISSUE THREAD

**Issue by hijiki55** [yukieiji/ExtremeRoles#63]
### 役職名 / Role Name
ドゥーム
(別名候補)ドゥームズデイ/レッドローズ/イビルローズ/死神/ハングマン/ビホルダー
### 役職の色 / Role color
赤
### 役職の説明 / Role description
吊れなかった相手に追跡&死体消滅効果を与えるインポスター
### 役職の能力 / Role ability

 - 《ドゥーム》がプレイヤーに投票し、そのプレイヤーが吊り対象にならなかった場合、その投票相手を『ドゥーム』状態にする。
   - 『ドゥーム』状態を新たに付与できる回数には上限がある。この数はすべての『ドゥーム』プレイヤーで共有する。
   - 『ドゥーム』状態を同時に付与できる人数には上限がある。この数はすべての『ドゥーム』プレイヤーで共有する。
  - インポスター陣営と幽霊は『ドゥーム』状態であるプレイヤーの名前にマークが見える。本人には見えない。
   - オプションにより、マークがつかなくなる。
 - 『ドゥーム』状態のプレイヤーの死体は即座に消滅する。
 - 《ドゥーム》は『ドゥーム』状態のプレイヤーの位置を矢印で知ることができる。
### 他陣営への影響 / Effect on other teams
クルーは『ドゥーム』に狙われたプレイヤーになるべく同行し、孤立しないようにする。投票意見が割れた時に態度を曖昧にしようとするプレイヤーを疑う。
### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

<details>
<summary>初期案</summary>

### 役職名 / Role Name
ゲイザー
### 役職の色 / Role color
赤
### 役職の説明 / Role description
役職を見破った相手に消滅効果を与えるインポスター
### 役職の能力 / Role ability

 - 《ゲイザー》は会議中、プレイヤー１人と役職を選ぶことができる。選ばれたプレイヤーと役職が一致しているなら、会議後にそのプレイヤーを『見破る』。
    - オプションにより、選べる役職から素クルーを外す。
 - 『見破られた』プレイヤーの死体は即座に消滅する。
 - インポスター陣営と幽霊は『見破られた』プレイヤーの名前にマークが見える。本人には見えない。
 - 《ゲイザー》は『見破られた』プレイヤーの位置を矢印で知ることができる。
### 他陣営への影響 / Effect on other teams
CO含む役職能力にリスクが生じる。キル陣営はCOしたプレイヤーを積極的にターゲットにできる。
### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

ゲッサ―に比べるとローリスクローリターン……というか手動キルでリスクの後払いをする

</details>

**Comment by yukieiji** [comment]
役職の能力の「見破る」と「消滅」はどういった関係性なのでしょうか？

> 《ゲイザー》は会議中、プレイヤー１人と役職を選ぶことができる。選ばれたプレイヤーと役職が一致しているなら、会議後にそのプレイヤーを『見破る』。

これはどうやって実装するのかという問題があります(ゲッサーの選択画面はバグる可能性があるのでので実装したくないです)

> インポスター陣営と幽霊は『見破られた』プレイヤーの名前にマークが見える。本人には見えない。

これはこれ専用の処理を追加する必要があるので実装したくないです

**Comment by hijiki55** [comment]
> 役職の能力の「見破る」と「消滅」はどういった関係性なのでしょうか？

https://dic.pixiv.net/a/%E3%82%B2%E3%82%A4%E3%82%BA
ゲイザー＝『見つめるもの』で所謂イビルアイ系モンスターから採りました。卓ゲ的に色々有名な『ビホルダー』の変名及び『ゲッサ―』との語呂合わせです
フレイバーはゴーゴン的な石化でも、バックベアード的な消滅光線でも、写輪眼的な空間切り取りでも…
狙われたプレイヤーが、人外からの雑キルを警戒してその動きを縛られるところがこの役職のキモです

> 後こういう役職選択系は何も考えずマーリンを当てるゲームが始まるのでやりたくないってのもあります(あの人を勘で「マーリン」選択するというゲームが始まる)

とりあえずクルーとマーリンへのデバフ付与を不可能にはできます。書き忘れましたがゲッサ―同様に使用回数には制限ありです

> これはこれ専用の処理を追加する必要があるので実装したくないです

主観でしか分からない情報をなるべく減らしたいと思ったので
ヤンデレターゲットなど幽霊目線から推測しきれない情報があると配信視聴者的に盛り上がりづらいという体感があって「効果が幽霊から見える」を書きました
とは言えここの可視化に関しては無くても仕様として成立するので、「効果がインポスターから見える」部分も含めてカット可能です

> これはどうやって実装するのかという問題があります(ゲッサーの選択画面はバグる可能性があるのでので実装したくないです)

…とここまで書いてなんですが、ゲッサーコンパチでない案をまとめたので入れ替えます。元案は折りたたんで残します

**Comment by yukieiji** [comment]
名前も能力も変わるのでできれば別のチケットとして作ってほしかったです(今はもう大丈夫ですが)

> ゲイザー＝『見つめるもの』で所謂イビルアイ系モンスターから採りました。卓ゲ的に色々有名な『ビホルダー』の変名及び『ゲッサ―』との語呂合わせです
フレイバーはゴーゴン的な石化でも、バックベアード的な消滅光線でも、写輪眼的な空間切り取りでも…
狙われたプレイヤーが、人外からの雑キルを警戒してその動きを縛られるところがこの役職のキモです

いや能力として「見破る」と「消滅」があってそれの説明が全く無かったので何なのかなって言う話です

> とりあえずクルーとマーリンへのデバフ付与を不可能にはできます。書き忘れましたがゲッサ―同様に使用回数には制限ありです

そうするとその人がクルーかマーリンかって分かってしまいますがそれは大丈夫でしょうか

> 主観でしか分からない情報をなるべく減らしたいと思ったので
ヤンデレターゲットなど幽霊目線から推測しきれない情報があると配信視聴者的に盛り上がりづらいという体感があって「効果が幽霊から見える」を書きました
とは言えここの可視化に関しては無くても仕様として成立するので、「効果がインポスターから見える」部分も含めてカット可能です

他人の人の画面に何らかの情報を出そうとすると、その人で動いている役職の情報なり表示するための情報を更新しないと行けないのでそのような処理は追加で別処理が必要になります

**Comment by hijiki55** [comment]
> 名前も能力も変わるのでできれば別のチケットとして作ってほしかったです(今はもう大丈夫ですが)

> いや能力として「見破る」と「消滅」があってそれの説明が全く無かったので何なのかなって言う話です

失礼しました…

> そうするとその人がクルーかマーリンかって分かってしまいますがそれは大丈夫でしょうか

無能力のクルーに影武者という役割が生まれるのは面白い気がします

それに実際に投票するアサシンとゲイザーは同じ視点を持つ訳ではないので、効率的な可能性の潰し方は必ずしもできないと思われます
(マーリン会議に音声チャットを使う場合には、マーリンに渡せる情報量がまた違ってくるかもしれませんが)

マーリン以外のインポスターが先行して動かなければならず、ゲイザーが最終段階まで生き残るというのも現実的でありませんし
発動回数を適切に制限する、クルーの数、他役職の種類を増やす等でバランスの取れる範囲だと思います


付け加えると、疑わしいプレイヤー一人を「クルーorマーリン」に絞れるまで深堀りする択以外にも、サポーター疑いを横に洗っていくという択もありえます
ふにんがすのマーリンゲーム中、サポーターが黒疑いに乗じてマーリンをローラーし、言動を一切追えなくなってしまうという一幕がありました
ケアの難しすぎたマーリン埋葬戦術に一石投じるのは面白い気がします
（まあ、あの時は人外側のキル圧が設定的に弱かったというのもありましたが…）

**Comment by yukieiji** [comment]
> 無能力のクルーに影武者という役割が生まれるのは面白い気がします

これはクルーの動きであってゲイザーの動きではないので考えるべき内容ではないです

> 付け加えると、疑わしいプレイヤー一人を「クルーorマーリン」に絞れるまで深堀りする択以外にも、サポーター疑いを横に洗っていくという択もありえます

どちらにせよ、アサシン会議に優良すぎる情報を与えるのはダメだと思います

> ふにんがすのマーリンゲーム中、サポーターが黒疑いに乗じてマーリンをローラーし、言動を一切追えなくなってしまうという一幕がありました
ケアの難しすぎたマーリン埋葬戦術に一石投じるのは面白い気がします
（まあ、あの時は人外側のキル圧が設定的に弱かったというのもありましたが…）

マーリン埋葬戦術はそれはそれでありだと思います(それをアクションでカバーする必要もない気がします)

以上ゲイザーの話、このチケットはもうゲイザーではないのでここで終了しましょう
以下ドゥームの話

> 『ドゥーム』状態のプレイヤーには名前の横にすべてのプレイヤーに見えるマークがつく。

上にもある通り他人の人の画面に何らかの情報を出そうとすると、その人で動いている役職の情報なり表示するための情報を更新しないと行けないのでそのような処理は追加で別処理が必要になるため実装したくないです

**Comment by hijiki55** [comment]
> 上にもある通り他人の人の画面に何らかの情報を出そうとすると、その人で動いている役職の情報なり表示するための情報を更新しないと行けないのでそのような処理は追加で別処理が必要になるため実装したくないです

ゲームオプションと役職と投票先と現在のドゥームフラグでドゥームフラグが立つかどうか決まるので、他の人のデータを更新に行く必要はないような気がします
