### ISSUE TITLE
[クルー陣営] : チューナー (アドミン・バイタルを強化できる)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#64]
### 役職名 / Role Name
チューナー

### 役職の色 / Role color
緑系の色

### 役職の説明 / Role description
アドミンやバイタルをチューニングして強化できるクルー陣営。TORのハッカーをアレンジした

### 役職の能力 / Role ability

アドミンやバイタルの前で能力を発動すると、通信障害が起きるか一定回数の会議が終わるまでその設備を強化する。
この能力には回数制限があり（デフォルトで2回を想定）、1度発動すると強化効果が切れるまで再発動できない。

アドミンを強化すると、プレイヤーのアイコンに色がついて誰がどこにいるかがわかるようになる。
バイタルを強化すると、死んでいる（赤い表示）プレイヤーが死後何秒経過したかがわかるようになる。

強化された設備は「誰でも」使用できる。ニートなど本来アドミンやバイタルへのアクセス権限を持たない役職でも利用できる

#### メリット
強化した設備で情報戦に強くなる

#### デメリット
インポスター陣営などにも利用される
通信障害が起きたらすぐに効果が切れる

#### 固有設定項目
能力の使用回数（回）
強化が切れるまでの会議回数（回）

### 他陣営への影響 / Effect on other teams
敵の陣営も強化された設備を利用できるので、そこで得られる情報と通信障害の利点を天秤にかけることになる

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> インポスター陣営などにも利用される

インポスター陣営がこれを能力の恩恵を受けることはない気がします

> バイタルを強化すると、死んでいる（赤い表示）プレイヤーが死後何秒経過したかがわかるようになる。

探偵の能力を喰ってる気がします

> アドミンを強化すると、プレイヤーのアイコンに色がついて誰がどこにいるかがわかるようになる。

スーパーバイザーの強化能力を喰ってる気がします

正直デメリットなしでアドミンやバイタルを強化できるのは能力が強すぎると思います
