### ISSUE TITLE
[インポスター陣営] : ジキルとハイド (会議ごとにクルーとインポスターを行き来する)

### ISSUE THREAD

**Issue by hiragi117** [yukieiji/ExtremeRoles#69]
### 役職名 / Role Name
ジキルとハイド/Jekyll and Hyde

### 役職の色 / Role color
インポスターの色

### 役職の説明 / Role description
会議ごとにクルー(ジキル)とインポスター(ハイド)が切り替わる
(ゲーム開始時にランダムでどちらからスタートするか決まる)
全体的にジキルとハイド本人はあまり強くないが、クルーや他陣営を混乱させやすい

※アサイン時のテキスト例
→「2つの顔を使い分けろ」

勝利条件
自分以外の生存者が一人で他の人がクルーか無害な第三陣営(ニート等)の時
(自分がクルー時でもインポスターとしてカウントする)

### 役職の能力 / Role ability
クルー時
・通常クルーと同じようにタスクができる(ビジュアルタスクも他クルーから見える)
・シェリフで撃たれても死なない
・妖狐の気配察知では「敵ではない」と表示される

インポスター時
・クルー時にタスクを行った回数分、インポスター時にキルクールが短縮される
・その他の能力は通常インポスターと同じ
・全てのタスクを終えて会議を挟むとそれ以降はインポスター固定になる

設定可能なオプション項目
・クルー時のタスク量
・キルクール短縮回数を次回インポスター時に持ち越すか否か(持ち越すor持ち越さない。デフォルトは持ち越す)
・キルクールを通常インポスターより何秒短縮するか(0～１５秒。デフォルトは5秒)
・インポスター固定時のキルクール(0～15秒。デフォルト１０秒)
デフォルト時の例)通常インポスターのキルクールが２５秒の時、2個タスクを終えていたら２回キルクールが20秒になる。(３回目以降は通常と同じ２５秒)
インポスター固定になった後はキルクールが15秒で固定になる。

メリット
・クルー時があることでシェリフからの白確を貰いやすい
・クルー時は本物のタスクなのでタスク偽装で見抜かれない
・インポスター時はキルクールの短縮によりキルがしやすくなる

デメリット
・クルー時はキルが出来ない
・クルー時がある為、ダブルキルの成功率が下がる

### 他陣営への影響 / Effect on other teams
・クルーはビジュアルタスクやシェリフの自爆で安易な白確が出来なくなる
・妖狐は気配察知の判定結果が会議ごとに変わる為、混乱する。

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

原作小説のジキルとハイドをモデルに善行(タスク)をこなすことで殺人衝動が増し、最終的には裏人格に飲まれてしまうという職。
ゲーム内ではとにかく会議を混乱させて、クルーはシェリフ自爆が起きてもクルーかジキルとハイドか、と考え続けなければならず疑心暗鬼が深まる。
インポスターとしての能力はあまり強くないが、上手く白確を得られれば会議を主導し味方インポスターのフォローに回ることも可能。

**Comment by yukieiji** [comment]
> (自分がクルー時でもインポスターとしてカウントする)
・シェリフで撃たれても死なない
・妖狐の気配察知では「敵ではない」と表示される

これは多分両立しないです

> ・キルクールを通常インポスターより何秒短縮するか(0～１５秒。デフォルトは5秒)

これは二重オプションになるので実装したくないです

> ・クルー時にタスクを行った回数分、インポスター時にキルクールが短縮される

これはどういうことでしょうか

ソースコードを読む感じクルー時多分他のインポスターからの表示やキルを防げれない気がします

**Comment by melonjagaimo** [comment]
裏人格に飲まれていない間はハイドもクルー陣営とみなすのはどうでしょうか。その場合、

・「ジキル」はクルー陣営役職
・最初はジキル状態で、会議ごとにハイド状態とジキル状態を行き来する

・タスク完了およびハイド状態での時間経過で殺人衝動が蓄積する
・ジキル状態での時間経過で殺人衝動が減少する。ただし満タンになると減少しなくなる

・殺人衝動が満タンになった後に会議を終えるとインポスター陣営役職「ハイド」になる

といった仕様になると思います
