### ISSUE TITLE
[クルー陣営] : ポルターガイスト (死体を移動させる幽霊)

### ISSUE THREAD

**Issue by Inumiya** [yukieiji/ExtremeRoles#70]
### 幽霊役職名 / Role Name
ポルターガイスト
### 幽霊役職の色 / Role color
黒っぽい色
### 幽霊役職の説明 / Role description
死体を移動させる幽霊役職
見つかりにくい場所にある死体を見つけやすい場所に移動させて生存者を支援する
### 幽霊役職の能力 / Role ability

騒霊
-  死体を３秒程度持ち運んで移動させる
- 移動中の死体は生存者から見えて通報もできる
  - キャリアーは運搬中の死体を奪って運搬できる（ポルターガイストがキャリアーから奪う事はできない）
- 死体を壁の中に移動させることに対して制限は設けない

デメリット
- 死体を探すことを優先するとタスクが疎かになる
- タスクが終わった後は死体探しに専念できるが、生存者の数が減っているため、死体を動かしても通報してもらえる可能性がそこまで上がらない
- 死体を下手に動かすと議論が混乱するおそれがある

### 死亡前の役職 / Role befor Dead
特に指定なし

### 他陣営への影響 / Effect on other teams
キル陣営への影響が大きい
- ポルターガイストのタスクが終わると張り付かれてしまうのでキルペースを上げないといけない
- ポルターガイストに張り付かれた場合、キルした直後の死体を犯人を追尾するように動かすといったことをされる

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 移動中の死体は生存者から見えて通報もできる

バランス的に通報できるようにすると幽霊が動かしたって分かってしまうので、運んでいる時は見えなくして通報も出来なくしたほうがいい気がしますがどうでしょうか

**Comment by Inumiya** [comment]
会議中に能力を使用した通知が出るので、幽霊が死体を動かしたかどうかはどちらにせよわかってしまう気がします。
死体が見えて通報できると、キル陣営がポルターガイストに死体を持って追いかけられた場合にセルフ通報して運搬を阻止することもできるので、キル陣営にも恩恵があると考えています

**Comment by yukieiji** [comment]
そう言われればたしかにそうですね、あとデフォルトクールタイム60秒+その後に死体を見つけるって事を考えると問題ないかなって思いました

キャリヤーだったらに奪い返せるとかなら面白いこともできそうかなって思いました

**Comment by Inumiya** [comment]
> キャリヤーだったらに奪い返せるとかなら面白いこともできそうかなって思いました

面白いですね
実装お願いできますか？

**Comment by yukieiji** [comment]
> 面白いですね
実装お願いできますか？

多分出来る気がします

**Comment by Inumiya** [comment]
キャリアーの部分、チケット更新しておきました

**Comment by Inumiya** [comment]
死体を壁に埋めてもクルーにはほぼデメリットしかないでしょうし、仕様で大丈夫です

**Comment by yukieiji** [comment]
動作確認が出来たためクローズします
