### ISSUE TITLE
[インポスター] :ベントガイスト  (ベントをパカパカさせる)

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#71]
以前ふにちかさんがTwitterで言ってた役職

### 幽霊役職名 / Role Name
(名称未定)
### 幽霊役職の色 / Role color
インポスターレッド

### 幽霊役職の説明 / Role description
ベントを使用を偽造させる

### 幽霊役職の能力 / Role ability

 - ベント開閉
   - サンドワームと同じようなベントアニメーションを再生させる

### 死亡前の役職 / Role befor Dead
- 特になし

### 他陣営への影響 / Effect on other teams
- クルー陣営への心理的かつ推理に多大なダメージを与える
  - 能力使った通告が出るから問題ないと言えば問題ない気がする
  - 使用制限をつけてもいいかもしれない(1～2回)

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by melonjagaimo** [comment]
役職名の提案です。まだ決まってないなら参考にしてくださると嬉しいです
1:ベントゴースト

2:パカパカ
