### ISSUE TITLE
[クルー陣営] : フローター(ベントの蓋を開けてクルーを飛び出させる)

### ISSUE THREAD

**Issue by vcf0902** [yukieiji/ExtremeRoles#72]
### 幽霊役職名 / Role Name
フローター
### 幽霊役職の色 / Role color
青紫色(強い要望はありません。紫系統で被らない色がいいかな？程度です)
### 幽霊役職の説明 / Role description
+ 任意のベントを開けて底に潜むクルーを陣営問わず飛び出させるクルーの幽霊役職
+ ゲーム中のフレーバー案：ベントからクルーを浮かばせて驚かそう
### 幽霊役職の能力 / Role ability

+ 固有能力「フローティング」
	+ クールタイム経過後、任意のベントに接近すると「フローティング」ボタンが活性化する。
		+ なお、この際の「ベント」とはマップ中に元から存在し、かつ使用可能なベントを指し、
		「メリー」などによる特殊ベントは対象としない想定。
	+ 活性化した「フローティング」ボタンをクリックすると、一定時間、対象のベントに以下の効果を与える。
		+ 対象のベント直下にいるクルーを強制的にベントから追い出す
		+ 発動時間中は、対象のベントに入った場合、または別のベントから移動してきた場合も追い出し対象となる
		+ この際、ベント掃除時にクルーが飛びだした際のSEを鳴らすとよいかは要検討
		(周囲に能力によるベント飛び出しと判断できる要素としての案)
		+ ベントから追い出される陣営は問わない(エンジニア等も追い出される)

+ オプション
	+ 「フローティング」能力クールダウン(秒)
		+ デフォルト：60秒
		+ 設定範囲：15秒～120秒、5秒刻み
	+ ベントのフタが開く(=追い出し状態になる)時間(秒)
		+ デフォルト：5秒
		+ 設定範囲：1秒～10秒、1秒刻み

+ 能力のメリット
	+ 強制的なベント排出、ベント移動の阻止により、ベントの安易な使用を控えさせることができる
	+ クルーが多い場面で能力が機能すれば即吊り対象を炙り出せることとなる

+ 能力のデメリット
	+ 敵陣営がベントに潜ったことを視認する、かつクルーが複数いる状況でなければ能力を用いても機能しづらい
	+ ベントから飛び出したさい、故意か能力によるものか挙動を見極めて判断する必要もある
	+ ベント使用可能役職が多数あれば、能力による事故が起きても騙られる危険性は十分に残る
	+ クルーや第三陣営にも作用するため、推理が誤っていれば逆に不利にする可能性もある

### 死亡前の役職 / Role before Dead
+ 指定なし(クルー陣営のいずれか)

### 他陣営への影響 / Effect on other teams
+ クルー役職(生存者)
	+ 敵対役職が人為的なベントガバを起こしてくれる可能性が上がるため、
	吊るべき対象を見つけやすくなるでしょう。もちろん、見つけてしまったせいで狙われる可能性もあります。

+ その他陣営(主にベント使用可能な役職全般)
	+ 特権ともいえるベント移動を封じてくる上、かつ生存者をキルしても防止できないためやっかいです。
	この役職による能力が発生するとわかった場合はベントの使用回数を減らしたり、
	飛び出してしまった際の言い訳を考えておく必要が生じるでしょう。

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

### 補足
はじめまして。いつも本MODが用いられた様々なAmong USプレイ動画を楽しませていただいています。
カスタムの幽霊役職を実装すると伺ったので、初提案です。
能力イメージは、「ポルターガイスト現象によって、ベントのフタがひとりでに開いてしまう」という単純なものです。
アモアスにおける心霊現象を考えた際に、真っ先に「ベント掃除しようとしてインポスターが飛び出す」ビックリ現象が思い起こされたため、
それを能力として意図的に起こすのはどうだろうか、と思い至りました。
が、チケット発効前に同名の提案がありましたため、「ベントから浮かせる能力」としてフロート(float/浮かす)に名称を変えて提案いたします。

**Comment by yukieiji** [comment]
簡易的にベントを封鎖しているかつそれが外から見て全くわからないということを考えるとかなり強力な役職だと思いますがどうでしょうか(ポルターガイストは死体を探す必要があるという点とキルクールとの兼ね合いを含めるとそこまでかなって思います)

> 「フローティング」能力クールダウン(秒)
デフォルト：30秒
設定範囲：15秒～120秒、5秒刻み

Wikiの幽霊役職のところにもある通りデフォルトは60秒です

**Comment by vcf0902** [comment]
> 簡易的にベントを封鎖しているかつそれが外から見て全くわからないということを考えるとかなり強力な役職だと思いますがどうでしょうか(ポルターガイストは死体を探す必要があるという点とキルクールとの兼ね合いを含めるとそこまでかなって思います)

確かに、待ち伏せ的に利用できるのは強くなってしまいますね…あまり幽霊役職で状況を好転させやすいのはよくないと私も思います。
それでは、能力発動条件に「すでに対象のベント内にクルーがいる」を追加すればどうでしょうか。発動難易度がある程度運によるものになると思います。
  
> Wikiの幽霊役職のところにもある通りデフォルトは60秒です

ご指摘ありがとうございます。チケットを修正しました。

**Comment by yukieiji** [comment]
> それでは、能力発動条件に「すでに対象のベント内にクルーがいる」を追加すればどうでしょうか。発動難易度がある程度運によるものになると思います。

そのベントに人が居て確実に排出できるような場面で使えるって考えるとあんまり変わってないように思えます
キル役職に張り付いてキルして逃げようとベントに入った瞬間にこの能力を使えるってことになるので

**Comment by vcf0902** [comment]
> そのベントに人が居て確実に排出できるような場面で使えるって考えるとあんまり変わってないように思えます
> キル役職に張り付いてキルして逃げようとベントに入った瞬間にこの能力を使えるってことになるので

なるほど…狙って発動でき、不発がない時点で強い(デメリットとしてはかなり薄い)、ということでしょうか
そうなると、不発が起きるよう制限を強めるのであれば、以下2つの案を出してみます
1. 対象を「最も近いベント」→「ランダムな1つのベント」とし、能力使用時に能力発動判定
1. 任意のベントを指定、能力使用後、「一定時間経過後(最低10秒以上、30秒以上がよいか？)」に能力発動判定

どちらの案でも、発動判定時に対象となったベントにクルーがいなければ不発となり、封鎖効果も適用されないとし、
不発となった場合は会議時にもメッセージ表示は行わない

ここまでくると有効発動率も一気にがた落ちするとは思いますが、心霊現象モチーフなので場所を選べない方がらしいかも、とは思います。案1の際に複数のベントが対象となるというのもありますが、それはやりすぎと考えています

**Comment by yukieiji** [comment]
> どちらの案でも、発動判定時に対象となったベントにクルーがいなければ不発となり、封鎖効果も適用されないとし、
不発となった場合は会議時にもメッセージ表示は行わない

ボタンを押した瞬間に能力を使った報告が出るようになってます(分けるのが面倒だったからです)
なのでこれは申し訳ないですが出来ないです

上記が問題なければ1も2でも可能だとは思います

**Comment by vcf0902** [comment]
> ボタンを押した瞬間に能力を使った報告が出るようになってます(分けるのが面倒だったからです)
> なのでこれは申し訳ないですが出来ないです

仕様として報告が確定する件、わかりました。不発かどうかにかかわらずメッセージの表示はありで問題ありません。
能力不発自体は実装可能という認識でよいでしょうか。
認識があっており、かつどちらかの案を採用すれば能力バランスの課題も解決するのであれば案1がよいかと思っています。
能力を使う側も動くベントを予想できず、当たればラッキーという「幽霊の能力らしさ」があるほうがフレーバーとしてもよいかと思っています。

**Comment by yukieiji** [comment]
> 能力不発自体は実装可能という認識でよいでしょうか。

不発をどういう物にするかによりますが、ボタン押しても何も起きない = 不発にするなら出来ると思います

> 認識があっており、かつどちらかの案を採用すれば能力バランスの課題も解決するのであれば案1がよいかと思っています。

案1位なら実装は可能だと思います

**Comment by vcf0902** [comment]
> 不発をどういう物にするかによりますが、ボタン押しても何も起きない = 不発にするなら出来ると思います

不発については、その認識であっています。
整理となりますが、能力ボタン使用→対象ベントをランダム指定して能力発動判定となり、以下の場合分けとなる認識です。
どちらとなっても、クールタイムは発生となります(念のため)
+ 選ばれたベントにクルーが潜んでいる　：クルーが追い出され、一定時間そのベントから追い出される効果も発生
+ 選ばれたベントにクルーが潜んでいない：何も起こらず、一定時間そのベントから追い出される効果も発生しない(=不発)
後者の切り分けが難しい場合は、追い出し効果のみ発動してもいいとは思います

> 案1位なら実装は可能だと思います

ありがとうございます。実装意義があるとなりました場合は、この方向で進めていただけると幸いです。

**Comment by yukieiji** [comment]
大分返信が遅れましたがモヤッとした部分が言葉になったので

> 不発については、その認識であっています。
整理となりますが、能力ボタン使用→対象ベントをランダム指定して能力発動判定となり、以下の場合分けとなる認識です。
どちらとなっても、クールタイムは発生となります(念のため)

能力の仕様として戦略性があまりないように思えます
とりあえずクールが開けて人がベントに入ったら能力を使う、その人がベントに飛び出さなかったら何も起きない(打ち損が無いって感じでしょうか)

**Comment by vcf0902** [comment]
> 能力の仕様として戦略性があまりないように思えます

画期的な対案は正直出せませんが、以下の変更案はあります。

+ 任意のベントを指定可能だが、ボタン使用後3秒経過時(調整可能)に指定ベントにクルーが居た場合のみ追い出す。効果は一瞬として持続時間は廃止
	+ 遅効性を持たせることで狙ったクルーがベントに入って即発動しても、移動に使われただけなら不発に終わる

+ タスク未完了時の場合、会議終了後から一定数のタスクをこなさないと能力ボタンが活性化しない
	+ 妨害対象のクルーを追いかけまわせなくする。クールタイムを60秒未満にする場合に検討

元々、勝ちにつなげる能力発動は、「複数人が視認できる状態でベントから敵対陣営を追い出す」シチュエーションだと思っているため、
いたずらにキル陣営を追い回すだけでは効果的にはこの能力を扱えないと考えています。
そこに、「狙った相手が都合よくベントに潜伏する」などのタイミングを見極める駆引きを追加することで
キル陣営もただ理不尽に追い出されないように出来るのではないかと思います。

**Comment by yukieiji** [comment]
> 任意のベントを指定可能だが、ボタン使用後3秒経過時(調整可能)に指定ベントにクルーが居た場合のみ追い出す。効果は一瞬として持続時間は廃止
遅効性を持たせることで狙ったクルーがベントに入って即発動しても、移動に使われただけなら不発に終わる
タスク未完了時の場合、会議終了後から一定数のタスクをこなさないと能力ボタンが活性化しない
妨害対象のクルーを追いかけまわせなくする。クールタイムを60秒未満にする場合に検討

この2つともなんですが、能力として成立するのかなってのはあります
1つ目の部分：3秒後そこにいるかどうかを見極めれるかどうか(逆に短くすると強いですし、長くする使えない能力になってしまいます)
2つ目の部分：タスクの進捗に合わせて使えるようになるってのは一つのデメリットとしては問題ないとは思いますが、タスクが終わってるゲーム終盤は人外はよくベントを使うのでそれを邪魔されるって考えるとデメリットとして機能していない気がします

> 元々、勝ちにつなげる能力発動は、「複数人が視認できる状態でベントから敵対陣営を追い出す」シチュエーションだと思っているため、
いたずらにキル陣営を追い回すだけでは効果的にはこの能力を扱えないと考えています。
そこに、「狙った相手が都合よくベントに潜伏する」などのタイミングを見極める駆引きを追加することで
キル陣営もただ理不尽に追い出されないように出来るのではないかと思います。

最も効果的に使うと言うのであれば、その使い方で間違ってはないと思います
しかし、人外的に言えば一回ベントから追い出されるだけで数秒のロスが発生するのでかなりうざいです(その数秒の間に人が来て見られるということもありますし、移動が阻害されるってのもあります)

**Comment by vcf0902** [comment]
> この2つともなんですが、能力として成立するのかなってのはあります

1つ目については正直効果量は実際に使って使われてしないとバランスはわからないかなというのが正直なところです。
個々人のプレイスタイルにも依るので正解はないと思ってます。(即追い出しが強いという点は不動だと思いますが)

2つ目は、タスクによる制約以外に付加できるものがあればいいのですが、正直思いつかないです。クルーを追跡させず動き回らせる手段があればベターだと思われますが。
(現実性を度外視しても、クール回復後一定時間しか能力を使えない、移動量が拾えるなら移動しないと視界が広がらないといった案しか持ち合わせがないです)

> しかし、人外的に言えば一回ベントから追い出されるだけで数秒のロスが発生するのでかなりうざいです

ベントから一定時間追い出す機能は前回のリプライ時点でオミットする前提だったので、使われる意識があれば追い出された瞬間潜ることは可能な認識です。数秒ロスというイメージはなかったです
(闇鍋ルールでこの役職の存在を意識できない場合はこの限りではないかもしれませんが)

**Comment by yukieiji** [comment]
返信が遅れました

> 2つ目は、タスクによる制約以外に付加できるものがあればいいのですが、正直思いつかないです。クルーを追跡させず動き回らせる手段があればベターだと思われますが。
(現実性を度外視しても、クール回復後一定時間しか能力を使えない、移動量が拾えるなら移動しないと視界が広がらないといった案しか持ち合わせがないです)
あるいはシンプルに、強い分には強いとして発動上限回数を設け、かつタスク進捗率で使用回数を開放するのでもいいのかもしれません
(上限回数をXとしてタスク進捗率100/X%進行ごとに1回使用可能とするイメージ。上限2回ならタスク50%、100%で1回ずつ)

結局、上でも述べましたがタスクが終わっている時(人が減ってきた終盤)によくベントを使うのであんまり制限の意味になってるのかなってのはあります
それならもとから1回の制限等にしたほうがバランス的にもありだとは思います

> ベントから一定時間追い出す機能は前回のリプライ時点でオミットする前提だったので、使われる意識があれば追い出された瞬間潜ることは可能な認識です。数秒ロスというイメージはなかったです
(闇鍋ルールでこの役職の存在を意識できない場合はこの限りではないかもしれませんが)

追い出された瞬間って言っても出てくるアニメーションがどうしても入るので同じ状態に戻るためには2秒くらいはかかるとは思います

**Comment by vcf0902** [comment]
返信が遅れてしまい申し訳ありません。

> それならもとから1回の制限等にしたほうがバランス的にもありだとは思います

そうですね。「タスク完了したのち発動可能 or 残タスクありでも発動可能」、「能力使用は回数上限(デフォルト1回)」でよいと思います。

> 追い出された瞬間って言っても出てくるアニメーションがどうしても入るので同じ状態に戻るためには2秒くらいはかかるとは思います

専用のモーション・アニメーションを設けるのではなければ、(反応できるかはともかく)いわゆる最速ベントパカパカと相違ない速度でリカバリーできるイメージでいました。(所定の操作は出て入ってに1秒かかっていない印象を持っています)
…実際は驚いてラグが生じる可能性は十分考えられます。
実装するとして実際どれくらいのロスが確定発生するかがわからないのでこれ以上はこちらから意見は出せません。
その点を踏まえての発動上限でよいかと思います。

**Comment by yukieiji** [comment]
> そうですね。「タスク完了したのち発動可能 or 残タスクありでも発動可能」、「能力使用は回数上限(デフォルト1回)」でよいと思います。

いやタスク制限自体要らないって思ってます、タスクが終わるような状況で1回以上使えるかって言われたら違いますし
