### ISSUE TITLE
[クルー陣営] : ヒトダマ (クルーを照らす明かり)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#74]
### 幽霊役職名 / Role Name
ヒトダマ

### 幽霊役職の色 / Role color
薄いオレンジ

### 幽霊役職の説明 / Role description
クルーの視界を広げてくれるクルー陣営幽霊役職

### 幽霊役職の能力 / Role ability

能力を発動すると少しの間、クルー陣営の視界が広くなる。

### 死亡前の役職 / Role befor Dead
全てのクルー陣営役職

### 他陣営への影響 / Effect on other teams
視界が広いことはインポスター陣営にとって危険であると同時に、視界が広いことによる人外透けを防止することにつながるかもしれない

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 能力を発動すると少しの間、クルー陣営の視界が広くなる。

視界が広くなると確定でクルーだってなりませんか(視界が広くなってAさんを見たんで幽霊から白確をもらいましたーみたいな)

**Comment by melonjagaimo** [comment]
では、「能力を発動すると1度だけ停電の効果を受けなくなる」というのはどうでしょうか。
インポスター陣営なら基本的に停電の効果を受けませんし

**Comment by yukieiji** [comment]
> では、「能力を発動すると1度だけ停電の効果を受けなくなる」というのはどうでしょうか。
インポスター陣営なら基本的に停電の効果を受けませんし

結局幽霊はクルーしか能力を使わないから変わりが無いのでは無いでしょうか

**Comment by melonjagaimo** [comment]
ダメでしたか。

残る案としては
「誰かの近くで発動することで、そのプレイヤーは少しの間視界が広くなる」

「能力を発動すると幽霊を中心とした一定範囲内が明るくなる」

があります。

**Comment by yukieiji** [comment]
> 残る案としては
「誰かの近くで発動することで、そのプレイヤーは少しの間視界が広くなる」
「能力を発動すると幽霊を中心とした一定範囲内が明るくなる」
があります。

ライターの能力を簡易的であるけど他の人に任意の人につけれるってことを考えればバランス的にどうなのかという疑問がどうしても残ってしまいます

**Comment by melonjagaimo** [comment]
そもそもが強すぎましたか…。
この提案はクローズします。
