### ISSUE TITLE
[インポスター陣営] : テラーゴースト (おどかしてクルーの腰を抜かそう)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#75]
### 幽霊役職名 / Role Name
テラーゴースト

### 幽霊役職の色 / Role color
インポスターなので赤

### 幽霊役職の説明 / Role description
他人を脅かして少しの間だけ移動できなくする

### 幽霊役職の能力 / Role ability

他のプレイヤーに近づいて能力を使用するとそのプレイヤーを脅かす。
脅かされたプレイヤーは腰を抜かして少しの間移動できない。移動以外の行動はとれる

### 死亡前の役職 / Role befor Dead
インポスター陣営

### 他陣営への影響 / Effect on other teams
単独で動けなくなると危険なので注意が必要
味方にも使えるため脅かされた＝インポスターではない、が必ずしも成立しない

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 味方にも使えるため脅かされた＝インポスターではない、が必ずしも成立しない

幽霊視点からでもインポスター同士は見えるので、インポスターに使うってことはない気がします
そう考えると確実に赤以外を見分ける目印になってしまいますね・・・・

**Comment by melonjagaimo** [comment]
その点に関しては、TORのイビルゲッサーが吊られそうな味方を撃つことでイビルゲッサーが落ちたと錯覚させるように、味方に使うことで白塗りが可能と考えました

**Comment by yukieiji** [comment]
> その点に関しては、TORのイビルゲッサーが吊られそうな味方を撃つことでイビルゲッサーが落ちたと錯覚させるように、味方に使うことで白塗りが可能と考えました

味方に使うメリットが無い気がします
一時的な白確しか出来ないのとキルしやすいように足止めするのとでは後者の方に偏りそうですが

**Comment by melonjagaimo** [comment]
そういうことですか。

個人的には脅かされた対象への白塗り（実際はニュートラルもいるかも知れないが…）は足止めのデメリットとして釣り合うと思います。
数秒の足止めで、例えば死体を発見する前に足止めして、その間に仲間のインポスター（あるいはジャッカルとか）がキルをして、いざ通報したら死体が複数見つかったとなれば仲間のキルを隠蔽できます。

また足止めしたプレイヤーをキルすれば、そのプレイヤーが足止めされたことは、仲間が足止めを食らったと嘘をつくなどして言いくるめられそうに思います。

**Comment by yukieiji** [comment]
インポスター陣営にとっての短時間の足止めって結構強力な能力だと思っています
- インポスター陣営の足止めで出来ること
  - キルのアシスト
  - 死体の隠蔽の時間稼ぎ
  - サボタージュの妨害(Skeldのリアクター等は結構ぶっ刺さるのでは？)

**Comment by melonjagaimo** [comment]
そうなると何らかのデメリットが必要ですかね…。
今思い浮かぶのは
①回数制限。1度だけ脅かせる

②脅かすために顔を出すという設定で、脅かされたプレイヤーには脅かしたテラーゴーストがバレる。つまり吊りが正解だったり食い合いが起きていたりしたことがバレる

の2つですね。

**Comment by yukieiji** [comment]
> ①回数制限。1度だけ脅かせる

回数制限はありだとは思います

> ②脅かすために顔を出すという設定で、脅かされたプレイヤーには脅かしたテラーゴーストがバレる。つまり吊りが正解だったり食い合いが起きていたりしたことがバレる

能力を使った瞬間に会議で報告されるので、あんまり意味がないような気がします

**Comment by melonjagaimo** [comment]
では回数制限を持たせます。デフォルトでは1回がよろしいでしょう。
設定で変更可能にしますか？（ふにんがすの余興などで見られる役職インフレルールのため。最大5回程度を想定）

**Comment by peki-orion** [comment]
横から失礼致します。
> 短時間の足止めって結構強力な能力だと思っています

> そうなると何らかのデメリットが必要ですかね…。

デメリットというよりはメリットのナーフとなる案なのですが、「テラーゴースト」が直接脅かせて足止めさせるのではなく、罠（例えばトラバサミなど）を設置しそれを踏んだ人が足止めされるというのはいかがでしょうか。
（インポスター陣営は罠を視認可能で、罠の対象ともなる。インポスター陣営は罠を避けることもできるしわざと引っかかって白確に使うこともできる）
その場合、任意の相手に対する確実な足止めは出来なくなるのでいくらか使い勝手が悪くなると思います。任意の相手を驚かすことにビジョンがあるのであればそこからはズレてしまいますが…

**Comment by melonjagaimo** [comment]
罠ではなくテラーゴーストが待ち伏せする形でなら、それもいいと考えています

**Comment by yukieiji** [comment]
> デメリットというよりはメリットのナーフとなる案なのですが、「テラーゴースト」が直接脅かせて足止めさせるのではなく、罠（例えばトラバサミなど）を設置しそれを踏んだ人が足止めされるというのはいかがでしょうか。
（インポスター陣営は罠を視認可能で、罠の対象ともなる。インポスター陣営は罠を避けることもできるしわざと引っかかって白確に使うこともできる）
その場合、任意の相手に対する確実な足止めは出来なくなるのでいくらか使い勝手が悪くなると思います。任意の相手を驚かすことにビジョンがあるのであればそこからはズレてしまいますが…

そこに罠がある時点でルートを簡易的に潰せるという部分で強い気がします
それがインポスターも引っかかるなら使いにくいですし、見えてるなら強い気がします

> では回数制限を持たせます。デフォルトでは1回がよろしいでしょう。
設定で変更可能にしますか？（ふにんがすの余興などで見られる役職インフレルールのため。最大5回程度を想定）

回数制限を付けたとしてもかなり強力だと思います、もう少しデメリットが必要だと思います

**Comment by melonjagaimo** [comment]
もう少しデメリットが必要、ですか。それでは

・能力発動から効果適用までタイムラグがある

・驚かされたプレイヤーは移動解禁後、一時的に移動速度が増加する

はどうでしょうか。

**Comment by yukieiji** [comment]
> ・能力発動から効果適用までタイムラグがある。その間にテラーゴーストから離れると発動が無効になる

インポスターは基本的に動き回るってことはないと思います

> ・驚かされたプレイヤーは移動解禁後、一時的に移動速度が増加する

足止めできてる部分で強いのでその後を解消しても意味ない気がします

**Comment by melonjagaimo** [comment]
これ以上いい案が出ないのでクローズします
