### ISSUE TITLE
[ニュートラル] : ハイエナ (死体を食う役職)

### ISSUE THREAD

**Issue by appleaoi** [yukieiji/ExtremeRoles#76]
### 役職名 / Role Name
ハイエナ
### 役職の色 / Role color
茶色
### 役職の説明 / Role description
TORのヴァルチャーにキルボタンを持たせたもの
ボタン「貪る」を使い、死体の上に居続けると空腹カウントが減っていく(死体は消えない)
空腹カウントは画面左下に常時表示
・ベント使用可
・サボタージュ不可
#### 勝利条件
1.合計で50カウント（設定で変更可）消費すると勝利
2.自分以外の生存者が一人で他の人がクルーか無害な第三陣営(ニート等)の時

#### ボタン「貪る」
死体の上でのみ使用可。使用するとボタン「解除」に変更
解除をするまで動けず、視界が狭くなる（集中して噛り付いているイメージ）
解除すると、再度「貪る」までクールタイムがある
「貪る」中はキルクールの時間は減らない
　貪り中にクルーにばれた時に、通報防止のためにキルをすることをさせないようにするため
　他人がキルした死体の場合、キルクールが溜まっていれば返り討ちにできる（他人の死体のメリット）

#### 動き方のイメージ
序盤はクルーも多いので、死体を見つけて（自身でキルしても）少しカウントを減らせるぐらいか。
通報するか、逃げるか戦術が分かれる
後半はクルーが少ないので、長時間カウントを減らすチャンスが多いと思われる
貪る中は視界が狭いため、どこまで貪り続けるかの駆け引きがある

### 他陣営への影響 / Effect on other teams
クルー目線：キルボタン持ちなので敵
インポスター目線：味方も殺される可能性があるぐらい

### 陣営 / Team

- [ ] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
役職全体的な疑問として死体を食えば勝利できる役職になぜキルボタンを持たせる必要があるのかを聞きたいです

> 死体の上でのみ使用可。使用するとボタン「解除」に変更
解除をするまで動けず、視界が狭くなる（集中して噛り付いているイメージ）
解除すると、再度「貪る」までクールタイムがある

死体見つけてバレそうな場所だと少し貪って通報、見つけにくい場所で切って貪るだけで勝てそうな気がするのですがどうでしょうか

**Comment by appleaoi** [comment]
初めまして。返答ありがとうございます。
いつも動画などで楽しませてもらい、自分も少しでも協力できればと思い、
今回投稿させてもらいました。
引用の仕方がよくわかってないため、見辛いかもしれませんがお許しください。

まず、キルボタンを持たせた理由ですが、
・キルが遅い村だと死体が出るまでが長時間待ちになってしまう
・キルができない第三陣営は生存優先になり、ほかのクルーと団体行動をして、
　全体のキルペースが落ちやすいと思うので抑制したい
　（生存優先を否定するわけではないです）
・キルボタンが無いと後半勝利条件を満たせなくなり、詰む可能性を避けたい
・個人的な考えですが、インポスターがクルーをキルして浮いてしまうリスクと勝利に近づく割合がキルして死体の上に居続け長時間浮いてしまうリスクとカウントを減らして勝利に近づく割合が同じ位だと判断しました（カウント量にもよりますが）


- 見つけにくい場所で切って貪るだけで勝てそうな気がするのですがどうでしょうか
これについて考えているリスクと対策です
リスク
・貪っている間確実に誰からも視認がなくなるので、別の通報があった場合浮き釣りされやすい
対策
・貪っている間、視界が徐々になくなる設定のつもりなので、プレイヤーに緊張感から適量での解除を促したい
　（自分はビビりなのでそう思いました。配信映えしなくなると言われたらキツイですが）
・設定に盛り込むか悩んだのですが、一つの死体で貪れる上限を設けてもいいかと思ってます。
　（ただ、その場合、勝利条件1が早めに詰む可能性があるので設定するか悩んでいます）

以上です。よろしくお願いします。

**Comment by yukieiji** [comment]
自分の中でもやもやしていたものがやっと言葉になったので返信します
きつい言葉になるかもしれないですが「貪る」という行為自体にデメリットしか無いのが問題でしょう(貪らなくて残ってキルしたほうが勝率高いってなりそう・・・？)
「貪る」のカウントを小さくするのが解決策みたいな感じなりそうですが、そこしか調整枠が無いので調整しにくい(小さくすると勝利しやすいし、上げ過ぎると「貪る」必要性がない)ってのも問題だと思っています
- 貪る
  - メリット
    - 勝利への道が続く
  - デメリット
    - 死体が消えないのでほぼ確実に浮く
    - 見つかったら即吊り
- キル
  - メリット
    - 自分で死体を作れる
    - 細い勝利に近づける
    - 貪らなくてもいい(逆に貪らない方がいい)
  - デメリット
    - 人を落とすので黒位置に立ちやすい

> ・貪っている間確実に誰からも視認がなくなるので、別の通報があった場合浮き釣りされやすい

基本的にキルをしている時点で浮いているのでそこまでかなって思います

**Comment by appleaoi** [comment]
お疲れ様です。返答ありがとうございます。

>貪らなくて残ってキルしたほうが勝率高いってなりそう・・・？

改めて指摘されると、「貪る」という行為にメリットが少なく、
プレイヤーが利用し辛いと理解しました。

そこで新たに思いついた、プレイヤーに序盤から「貪る」をうながす案です。
どれもほかの役職の特徴を真似たようなアイデアなので、新しさが無く申し訳ありません。
全部採用となると、設定モリモリでバランスが悪くなってしまうと思うので、
採用するとしても、どれかだと思います。（もしくは全て没か）

#### 案1　貪るをしなくてはならなくする案
・「餓死カウント」を追加し、一定時間貪らないと自爆する（TORのシリアルキラーのイメージ）　
  ‣一度貪るとタイマーがリセットされる、もしくは貪った時間×設定分回復する
  ‣会議中は止まるが、会議ではリセットされない（シューターと似たような仕組み）
　 もしくは会議でリセットされる（餓死が会議でリセットはイメージ的に変ですが・・・）
　課題
　　‣会議連打されると、死体が出ないために自爆を防げなくなり、設定の調整が難しそう
　　（「会議でリセットする」の場合は考える心配なし）
　　‣カウントが増えるので、画面情報が多すぎないかが心配

#### 案2　貪るにメリットを追加する案1（一度に貪れる上限を設けた場合）
・一度に貪れるカウント限界を超えると死体を消せる
　‣死体を消して、ほかのクルーの視認を作りに行ける
　‣貪るを途中でやめて、死体を残して視認を作る作戦もあり。
　「貪る」クールタイム回復後に再度貪るもよし
　‣疑似的にTORのヴァルチャーを再現できる
　　 (キルクールを伸ばし、貪り限界時間を短くし、合計カウントを小さくすれば、
　　　どうしてもTORのヴァルチャーがいいという希望も叶えられるか)
　課題
　　能力説明が複雑な気がする（プレイヤーが理解しきれるか？）
　　完全に消してしまうと推理要素がなくなるため強すぎるか？
　　（消すまでに長時間かかる想定なので、それくらいでバランスが取れている気もする）

#### 案3　貪るのデメリットを軽減する案1（一度に貪れる上限を設けた場合）
・貪る中は死体が消え、通報できなくなる（死体を隠し持っているイメージ）
　‣パッと見では立ち止まっているだけに見える、タスクの場所だと違和感も消える
　‣ほかのクルーからも視認がもらえる可能性があがる
　‣解除すると死体が現れるので、解除するタイミングが重要になる
　課題
　‣視界が無い状態で解除になるので、解除のタイミングが運次第になりやすい
　（下の案4と併用なら無難か？）
　‣タスクの場所でほかの通報まで立っているのが安牌になってしまうか？
　（時間上限で自動解除なら問題なしか？）

#### 案4　貪るのデメリットを軽減する案2
・貪り中、視界が狭くなると人が近づくと文章が出る
　‣妖狐と同じ要領で人が近づくと「近くで物音がする！」と文章がでる。
　　（いないときは「静かだ・・・」）
　‣正しい情報が出るかは確率で決まる
　課題
　　そこまでの強化ではない

今思いついたのはこれくらいです。
いろいろな案を思いついたのはいいですが、新しい特徴を盛り過ぎたため、
全体的にわかりにくくなってしまったかもしれません。
（元々がプレイヤーへのわかりやすさを重視していたためかもしれませんが）
質問およびダメ出しくだされば、説明させてもらいます。

また、別Issuesにて「イーター」というヴァルチャー候補を提案されているみたいですので、
そちらが採用予定でしたら、こちらの役職は没にしてしまって構いません。
（自分的には第三陣営が増えてうれしいので、どちらでも構いません）

以上です。よろしくお願いします

**Comment by yukieiji** [comment]
基本的にどの案でも問題ないといえば問題ないのですこういうものはデメリットをなくしたり、しなければならない制限を追加するよりメリットを増やすことのほうが良い気がします

個人的には提案されているメリットでは弱い気がします

> また、別Issuesにて「イーター」というヴァルチャー候補を提案されているみたいですので、
そちらが採用予定でしたら、こちらの役職は没にしてしまって構いません。
（自分的には第三陣営が増えてうれしいので、どちらでも構いません）

あれは私が提案しているものなのでほぼ採用確定だと思っていただいて構いません

**Comment by appleaoi** [comment]
お疲れ様です。返答ありがとうございます。
>個人的には提案されているメリットでは弱い気がします
ご意見ありがとうございます。今後、第三陣営を提案する機会があれば参考にさせてもらいます

>あれは私が提案しているものなのでほぼ採用確定だと思っていただいて構いません

了解しました。でしたら、こちらは役職的に被っているIssuesなので、クローズさせてもらいます
（初めてなので間違えていたら、クローズしてください）

今回、初めて役職提案（TORの流用のものですが）をさせて頂き、非常に楽しめたとともに、難しさ・大変さを体験することができました。
このような、議論の場を設けてくださり、ありがとうございました
次回提案する機会がありましたら、よろしくお願いします

以上です。ありがとうございました。
