### ISSUE TITLE
[クルー/ニュートラル] : 妄執者/妄執犯 (投票されるとキル出来る役職)

### ISSUE THREAD

**Issue by RanasGlif** [yukieiji/ExtremeRoles#77]
### 役職名 / Role Name
妄執者/妄執犯
### 役職の色 / Role color
灰色
### 役職の説明 / Role description
クルーメイトとしてアサインして自分以外から投票されると自分へ投票した人の色が解るようになり
投票した相手をキル出来るようになる役職
キルをするまでは妄執者/クルーメイトであり
キルをすると妄執犯/ニュートラルになり自分に投票した相手を一定数キルすると勝利になる

### 役職の能力 / Role ability
自分以外から投票される事で役職が判明する
投票を逆恨みしてキル出来るが殺さないという選択肢も取れる

勝利条件
妄執者/他のクルーメイトと同様
妄執犯/自分に投票した相手を一定数キルすると勝利になる

開幕投票でキラーが生まれる役職
「今、私に投票したの誰？」

### 他陣営への影響 / Effect on other teams
クルー目線/投票しない限り味方　覚醒しても自分に投票した人から黒票を洗える可能性も？
インポスター目線/投票しない限りただのクルーメイト
### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 自分へ投票した人の色が解るようになり

これはどういうことでしょうか

**Comment by RanasGlif** [comment]
アサシンのように投票した人の色が判別できるようになるといった意図で　
判別できるのは自分に投票した人だけという感じで考えています

**Comment by yukieiji** [comment]
> アサシンのように投票した人の色が判別できるようになるといった意図で　
判別できるのは自分に投票した人だけという感じで考えています

その人だけ見えるって処理は難しかったような気がします

**Comment by RanasGlif** [comment]
なるほど　色が見えて　クルー足りえる　しかも発動は特殊条件と　変異出来る事から本当にクルー側か？疑心暗鬼になれそうな職なので実装出来たら結構面白くはなりそうだと思います！
勝利条件間違って記入してるところがあるのですが投票した人をX人キルで統一で認識して頂ければと

**Comment by yukieiji** [comment]
> なるほど　色が見えて　クルー足りえる　しかも発動は特殊条件と　変異出来る事から本当にクルー側か？疑心暗鬼になれそうな職なので実装出来たら結構面白くはなりそうだと思います！

その人だけ見えるって処理はできないです(コード的にも出来る気がしない)

> 勝利条件間違って記入してるところがあるのですが投票した人をX人キルで統一で認識して頂ければと

チケットは編集できるのでしていただければ
