### ISSUE TITLE
[インポスターorニュートラルの幽霊] : ナイトメア (殺される夢を見せる)

### ISSUE THREAD

**Issue by UzomuZo** [yukieiji/ExtremeRoles#79]
### 幽霊役職名 / Role Name
ナイトメア

### 幽霊役職の色 / Role color
インポスターレッドor 黒系

### 幽霊役職の説明 / Role description
生存しているプレイヤーに能力を使用するとキルのアニメーションが再生されるが、死なない。

### 幽霊役職の能力 / Role ability

生存しているプレイヤーに能力を使用するとキルアニメーションで視界を塞ぎ、キルされたと勘違いさせることができる。
（可能であれば）移動やタスクはキャンセルされないので、キルかナイトメアか判別可能。

### 死亡前の役職 / Role befor Dead
特になし

### 他陣営への影響 / Effect on other teams
クルー陣営への心理的なダメージ。（キルされたと思って悲鳴を上げたら何ともなかったなど）
キルアニメーションで視界が塞がれることによる現行犯発見やタスク妨害。（回数制限付きでも可）

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [x] :ニュートラル/Neutral

**Comment by UzomuZo** [comment]
そうですか、残念ですがクローズしておきます。

**Comment by yukieiji** [comment]
今後出来る様になるかもしれないのでその時は私が再度オープンさせていただきます
