### ISSUE TITLE
ヒーローの第一段階に正しく移行しない

### ISSUE THREAD

**Issue by sigcolotet** [yukieiji/ExtremeRoles#80]
### 実際の動作 / The Reality

プレイヤーを1キルしても第1段階に移行せず、インポスターからのキルが発生してしまう。
プレイヤーを1キルし、ヒーローがキルできないことを確かめようとしたが、インポスター、およびインポスター陣営であるヴィランからキルできてしまった。
なお、第2段階に関しては問題なく動作していることを確認した。

#### 動画URL
https://youtu.be/25JRB1wQ5ag

### このバグに対するあなたの意見 / Your Proposal

===

### Among Usバージョン/ Among Us Version

Among Us v
2022.3.29s(build#:1864)

### Modバージョン / Mod Version

Extreme Roles v
2.1.1.6

### リージョン/Region

- [ ] :北アメリア/Noth America
- [ ] :欧州/Europa
- [x] :アジア/Asia
- [ ] :カスタム/Custom

### プレイヤー人数/Player Num

8人-12人のいずれも

### 使用したオプション/Use Option

Extreme Roles,Version,2.1.1.6
Id,Name,Option Value,SelectedIndex
1,強力なシャッフルを使用する,オン,1
2,クルーのロール数　最少,5,5
3,クルーのロール数　最大,5,5
4,第三陣営のロール数　最少,1,1
5,第三陣営のロール数　最大,1,1
6,インポスターのロール数　最少,1,1
7,インポスターのロール数　最大,1,1
8,合計緊急会議回数,10,10
9,投票スキップ禁止,オフ,0
10,自殺投票禁止,オフ,0
11,マップのベントを無効化する,オフ,0
13,ベント内のプレイヤーをキルできるか,オフ,0
12,エンジニアのベント使用をインポスターと同じにする,オフ,0
14,メッドベイのスキャンを同時使用できるか,オフ,0
15,毎回マップがランダムに変わるか,オフ,0
16,同じロールの第三陣営の勝利を同じにする,オン,1
17,第三陣営の特殊勝利による強制終了を無効化する,オフ,0
18,ウマングアスを有効にする,オフ,0
71,スペシャルクルー,0%,0
70,スポーン数,1,0
72,別の視界設定を持つか,オフ,0
73,ビジョン,2x,7
74,視界効果を受けるか,オン,1
121,シェリフ,100%,10
120,スポーン数,1,0
122,別の視界設定を持つか,オフ,0
123,ビジョン,2x,7
124,視界効果を受けるか,オン,1
127,別のキルクールタイムを持つか,オフ,0
128,キルクールタイム,30秒,58
125,別のキルレンジを持つか,オフ,0
126,キルレンジ,ショート,0
101,アサシンをキルできるか,オフ,0
102,第三陣営をキルできるか,オン,1
100,キルできる回数,14回,13
103,タスクに関する設定を有効化する,オフ,0
104,1つのタスク完了によるキルクール減少量,2秒,10
105,キルクールの減少が永続か,オフ,0
106,キルできる回数がタスク完了によって増加するか,オフ,0
171,メンテナー,0%,0
170,スポーン数,1,0
172,別の視界設定を持つか,オフ,0
173,ビジョン,2x,7
174,視界効果を受けるか,オン,1
185,「緊急修理」のクールタイム,30秒,59
186,「緊急修理」の回数,2回,1
221,ニート,0%,0
220,スポーン数,1,0
222,別の視界設定を持つか,オフ,0
223,ビジョン,2x,7
224,視界効果を受けるか,オン,1
200,緊急会議を起こせるか,オフ,0
201,サボタージを治せるか,オフ,0
203,第三陣営か,オフ,0
202,タスクを持つか,オフ,0
271,ウォッチドッグ,0%,0
270,スポーン数,1,0
272,別の視界設定を持つか,オフ,0
273,ビジョン,2x,7
274,視界効果を受けるか,オン,1
285,セキュリティとログのクールタイム,30秒,59
287,充電の持続時間,3秒,5
321,スーパーバイザー,0%,0
320,スポーン数,1,0
322,別の視界設定を持つか,オフ,0
323,ビジョン,2x,7
324,視界効果を受けるか,オン,1
335,アドミンのクールタイム,30秒,59
337,充電の持続時間,3秒,5
300,「アドミン」がタスク進捗によって強化されるか,オフ,0
301,「アドミン」が強化されるタスク進捗率,100％,10
371,ボディーガード,100%,10
370,スポーン数,1,0
372,別の視界設定を持つか,オフ,0
373,ビジョン,2x,7
374,視界効果を受けるか,オン,1
350,「シールド」を付与できる範囲,1,10
385,「シールド」のクールタイム,30秒,59
386,「シールド」が付与できる回数,2回,1
421,ウィスパー,0%,0
420,スポーン数,1,0
422,別の視界設定を持つか,オフ,0
423,ビジョン,2x,7
424,視界効果を受けるか,オン,1
400,停止してから能力が発動するまでの時間,3秒,4
401,「耳すまし」の持続時間,4秒,6
402,キルされたテキストの表示時間,3秒,4
403,キルされたテキストの最大表示数,3,2
471,タイムマスター,100%,10
470,スポーン数,1,0
472,別の視界設定を持つか,オフ,0
473,ビジョン,2x,7
474,視界効果を受けるか,オン,1
485,「タイムシールド」のクールタイム,30秒,59
487,「タイムシールド」の持続時間,3秒,5
450,「タイムシールド」によって巻き戻る時間,5秒,8
521,エージェンシー,0%,0
520,スポーン数,1,0
522,別の視界設定を持つか,オフ,0
523,ビジョン,2x,7
524,視界効果を受けるか,オン,1
500,「肩代わり」で取れるタスク数の上限,2,1
501,「肩代わり」が発動できる範囲,1,5
535,「肩代わり」のクールタイム,30秒,59
536,「肩代わり」が発動できる回数,2回,1
571,パン屋,0%,0
570,スポーン数,1,0
572,別の視界設定を持つか,オフ,0
573,ビジョン,2x,7
574,視界効果を受けるか,オン,1
550,パンの焼き加減が変わるかどうか,オン,1
551,パンが焼ける会議との合間時間,60秒,30
552,パンが焦げる会議との合間時間,120秒,30
621,カースメーカー,0%,0
620,スポーン数,1,0
622,別の視界設定を持つか,オフ,0
623,ビジョン,2x,7
624,視界効果を受けるか,オン,1
600,「呪い」が発動できる死体からの距離,2.5,4
601,「呪い」によって付与されるキルクールペナルティ,5秒,40
635,「呪い」のクールタイム,30秒,59
637,「呪い」が完了するまでの時間,5秒,9
636,「呪い」の使用回数,1回,0
602,死体を指す矢印を表示するか,オン,1
603,複数回、死体への矢印を表示させるか,オフ,0
604,キルされてから矢印が表示されるまでの時間,60秒,119
605,矢印の表示されるまでの時間がタスク進捗によって減少するか,オフ,0
606,タスク進捗率,100％,10
607,減少する時間,30秒,59
671,フェンサー,100%,10
670,スポーン数,1,0
672,別の視界設定を持つか,オフ,0
673,ビジョン,2x,7
674,視界効果を受けるか,オン,1
685,「カウンター」のクールタイム,30秒,59
687,「カウンター」の受付時間,3秒,5
686,「カウンター」の使用回数,2回,1
650,キルボタンが付与されてからなくなるまでの時間,5秒,5
721,オープナー,0%,0
720,スポーン数,1,0
722,別の視界設定を持つか,オフ,0
723,ビジョン,2x,7
724,視界効果を受けるか,オン,1
735,「ドア開け」のクールタイム,30秒,59
736,「ドア開け」の基本使用回数,2回,1
700,「ドア開け」の扉からの発動距離,2,15
701,「ドア開け」のクール減少率,45％,40
702,「ドア開け」の追加使用回数,5回,4
771,カーペンター,0%,0
770,スポーン数,1,0
772,別の視界設定を持つか,オフ,0
773,ビジョン,2x,7
774,視界効果を受けるか,オン,1
750,カーペンターに覚醒するタスク進捗率,70％,7
785,「ベント封鎖」と「カメラ設置」のクールタイム,15秒,26
786,「ネジ」の総本数,15回,10
751,「ベント封鎖」によって消費する「ネジ」の本数,10本,9
752,「ベント封鎖」にかかる時間,5秒,6
753,「カメラ設置」によって消費する「ネジ」の本数,5本,4
754,「カメラ設置」にかかる時間,2.5秒,3
821,スペシャルインポスター,0%,0
820,スポーン数,1,0
822,別の視界設定を持つか,オフ,0
823,ビジョン,2x,7
824,視界効果を受けるか,オフ,0
827,別のキルクールタイムを持つか,オフ,0
828,キルクールタイム,30秒,58
825,別のキルレンジを持つか,オフ,0
826,キルレンジ,ショート,0
871,エボルバー,0%,0
870,スポーン数,1,0
872,別の視界設定を持つか,オフ,0
873,ビジョン,2x,7
874,視界効果を受けるか,オフ,0
877,別のキルクールタイムを持つか,オフ,0
878,キルクールタイム,30秒,58
875,別のキルレンジを持つか,オフ,0
876,キルレンジ,ショート,0
850,進化時、アニメーションを行うか,オン,1
851,進化後、死体を消すか,オン,1
852,「捕食」を行える範囲,2.5,4
853,進化後のキルクール減少率,10％,9
854,進化毎のキルクール減少率の倍率,1x,0
885,進化のクールタイム,30秒,59
887,「捕食」を行う時間,5秒,9
886,最終進化までの回数,5回,4
921,キャリヤー,0%,0
920,スポーン数,1,0
922,別の視界設定を持つか,オフ,0
923,ビジョン,2x,7
924,視界効果を受けるか,オフ,0
927,別のキルクールタイムを持つか,オフ,0
928,キルクールタイム,30秒,58
925,別のキルレンジを持つか,オフ,0
926,キルレンジ,ショート,0
935,「キャリー」のクールタイム,30秒,59
937,「キャリー」で死体を運べる時間,5秒,9
900,「キャリー」が発動できる死体からの距離,1,0
901,死体運搬時、通報されるかどうか,オン,1
971,サイコキラー,0%,0
970,スポーン数,1,0
972,別の視界設定を持つか,オフ,0
973,ビジョン,2x,7
974,視界効果を受けるか,オフ,0
977,別のキルクールタイムを持つか,オフ,0
978,キルクールタイム,30秒,58
975,別のキルレンジを持つか,オフ,0
976,キルレンジ,ショート,0
950,キルクールの減少率,5％,4
951,最大キルコンボ数,2,1
952,キルコンボを会議時にリセットするか,オン,1
1021,バウンティーハンター,0%,0
1020,スポーン数,1,0
1022,別の視界設定を持つか,オフ,0
1023,ビジョン,2x,7
1024,視界効果を受けるか,オフ,0
1027,別のキルクールタイムを持つか,オフ,0
1028,キルクールタイム,30秒,58
1025,別のキルレンジを持つか,オフ,0
1026,キルレンジ,ショート,0
1000,ターゲット更新時間,60秒,60
1001,ターゲットキル時のキルクール,5秒,8
1002,ターゲット以外キル時のキルクール,45秒,88
1003,ターゲットを指す矢印を表示するか,オフ,0
1004,矢印の更新時間,60秒,118
1071,ペインター,0%,0
1070,スポーン数,1,0
1072,別の視界設定を持つか,オフ,0
1073,ビジョン,2x,7
1074,視界効果を受けるか,オフ,0
1077,別のキルクールタイムを持つか,オフ,0
1078,キルクールタイム,30秒,58
1075,別のキルレンジを持つか,オフ,0
1076,キルレンジ,ショート,0
1085,「ペイント」のクールタイム,30秒,59
1051,「ペイント」が行える距離,1,0
1050,「ペイント」した後の死体の色がランダムか,オフ,0
1121,フェイカー,0%,0
1120,スポーン数,1,0
1122,別の視界設定を持つか,オフ,0
1123,ビジョン,2x,7
1124,視界効果を受けるか,オフ,0
1127,別のキルクールタイムを持つか,オフ,0
1128,キルクールタイム,30秒,58
1125,別のキルレンジを持つか,オフ,0
1126,キルレンジ,ショート,0
1135,「ダミー」のクールタイム,30秒,59
1171,オーバーローダー,0%,0
1170,スポーン数,1,0
1172,別の視界設定を持つか,オフ,0
1173,ビジョン,2x,7
1174,視界効果を受けるか,オフ,0
1177,別のキルクールタイムを持つか,オフ,0
1178,キルクールタイム,30秒,58
1175,別のキルレンジを持つか,オフ,0
1176,キルレンジ,ショート,0
1185,「オーバーロード」のクールタイム,0.5秒,0
1187,「オーバーロード」発動後、解除可能になるまでの時間,7.5秒,14
1150,「オーバーロード」時のキルクールの減少率,60％,10
1151,「オーバーロード」時のプレイヤーの移動速度,1x,0
1221,クラッカー,0%,0
1220,スポーン数,1,0
1222,別の視界設定を持つか,オフ,0
1223,ビジョン,2x,7
1224,視界効果を受けるか,オフ,0
1227,別のキルクールタイムを持つか,オフ,0
1228,キルクールタイム,30秒,58
1225,別のキルレンジを持つか,オフ,0
1226,キルレンジ,ショート,0
1235,「クラック」のクールタイム,30秒,59
1236,「クラック」の使用回数,2回,1
1201,「クラック」が発動できる範囲,1,0
1200,「クラック」によって死体を消すか,オフ,0
1271,ボマー,0%,0
1270,スポーン数,1,0
1272,別の視界設定を持つか,オフ,0
1273,ビジョン,2x,7
1274,視界効果を受けるか,オフ,0
1277,別のキルクールタイムを持つか,オフ,0
1278,キルクールタイム,30秒,58
1275,別のキルレンジを持つか,オフ,0
1276,キルレンジ,ショート,0
1285,「爆弾設置」のクールタイム,30秒,59
1287,「爆弾設置」が完了する時間,2.5秒,4
1286,「爆弾設置」の使用回数,2回,1
1250,爆弾の爆発範囲,2,1
1251,爆発範囲に居たクルーが死亡する確率,50％,25
1253,「爆弾設置」後、爆発するまでの時間の最小時間,15秒,20
1252,「爆弾設置」後、爆発するまでの時間の最大時間,60秒,30
1254,爆発を役職の人に教えるかどうか,オン,1
1321,メリー,0%,0
1320,スポーン数,1,0
1322,別の視界設定を持つか,オフ,0
1323,ビジョン,2x,7
1324,視界効果を受けるか,オフ,0
1327,別のキルクールタイムを持つか,オフ,0
1328,キルクールタイム,30秒,58
1325,別のキルレンジを持つか,オフ,0
1326,キルレンジ,ショート,0
1335,「陣」のクールタイム,30秒,59
1336,「陣」の使用回数,3回,2
1300,「陣」が活性化するのに必要なプレイヤー数,3,2
1301,「陣」がプレイヤーを検知する範囲,2,19
1371,スレイヴドライバー,0%,0
1370,スポーン数,1,0
1372,別の視界設定を持つか,オフ,0
1373,ビジョン,2x,7
1374,視界効果を受けるか,オフ,0
1377,別のキルクールタイムを持つか,オフ,0
1378,キルクールタイム,30秒,58
1375,別のキルレンジを持つか,オフ,0
1376,キルレンジ,ショート,0
1350,「ボーナスキル」が発生しない全体のタスク進捗からの遅れ,10％,5
1351,「ボーナスキル」のキルクール減少率,25％,24
1352,ゲーム開始から「特攻」が入らない時間,60秒,60
1354,生存者とタスク進捗による「特攻」が入るようになる時間,600秒,10
1353,「特攻」が入った時のキルクール減少率,50％,25
1355,タスクを持たない船員をキルしたときの「ボーナスキル」発生の確率,50％,30
1356,タスクを持たない船員をキルしたときの「特攻」発生の確率,10％,5
1359,「特攻」で追加されるコモンタスクの数,1,1
1357,「特攻」で追加される通常タスクの数,1,1
1358,「特攻」で追加されるロングタスクの数,1,1
1421,サンドワーム,0%,0
1420,スポーン数,1,0
1422,別の視界設定を持つか,オフ,0
1423,ビジョン,2x,7
1424,視界効果を受けるか,オフ,0
1427,別のキルクールタイムを持つか,オフ,0
1428,キルクールタイム,30秒,58
1425,別のキルレンジを持つか,オフ,0
1426,キルレンジ,ショート,0
1401,通常キルのキルクールペナルティ,5秒,40
1400,「強襲」及び停電中のキルのキルクールボーナス,3秒,20
1402,「強襲」が使用できる範囲,2,19
1435,「強襲」のクールタイム,15秒,145
1471,スマッシャー,0%,0
1470,スポーン数,1,0
1472,別の視界設定を持つか,オフ,0
1473,ビジョン,2x,7
1474,視界効果を受けるか,オフ,0
1477,別のキルクールタイムを持つか,オフ,0
1478,キルクールタイム,30秒,58
1475,別のキルレンジを持つか,オフ,0
1476,キルレンジ,ショート,0
1485,「スマッシュ」のクールタイム,30秒,59
1486,「スマッシュ」の使用回数,1回,0
1450,「スマッシュ」によるキルクールペナルティ,4秒,8
1521,アサルトマスター,0%,0
1520,スポーン数,1,0
1522,別の視界設定を持つか,オフ,0
1523,ビジョン,2x,7
1524,視界効果を受けるか,オフ,0
1527,別のキルクールタイムを持つか,オフ,0
1528,キルクールタイム,30秒,58
1525,別のキルレンジを持つか,オフ,0
1526,キルレンジ,ショート,0
1535,「リロード」のクールタイム,30秒,59
1500,「ストック」の上限数,2本,1
1501,死体通報による貯まる「ストック」の本数,1本,0
1502,緊急会議ボタンによる貯まる「ストック」の本数,3本,2
1503,「コッキング」によるキルクール減少,2秒,10
1504,「ストック」1本あたりのキルクール減少,5秒,30
1505,キルによって「リロード」のクールタイムがリセットされるか,オン,1
1506,上限を超えた「ストック」1本あたりの「リロード」クールタイム減少率,75％,45
1571,アリス,0%,0
1570,スポーン数,1,0
1572,別の視界設定を持つか,オフ,0
1573,ビジョン,2x,7
1574,視界効果を受けるか,オフ,0
1577,別のキルクールタイムを持つか,オフ,0
1578,キルクールタイム,30秒,58
1575,別のキルレンジを持つか,オフ,0
1576,キルレンジ,ショート,0
1550,サボタージュを使えるか,オン,1
1585,「破壊工作」のクールタイム,30秒,59
1586,「破壊工作」の回数,2回,1
1552,「破壊工作」によって巻き戻るロングタスクの数,1,1
1551,「破壊工作」によって巻き戻るショートタスクの数,1,1
1553,「破壊工作」によって巻き戻る通常タスクの数,1,1
1621,ジャッカル,100%,10
1620,スポーン数,1,0
1622,ジャッカルが別の視界設定を持つか,オフ,0
1623,ジャッカルのビジョン,2x,7
1624,ジャッカルが視界効果を受けるか,オフ,0
1627,別のキルクールタイムを持つか,オフ,0
1628,キルクールタイム,30秒,58
1625,別のキルレンジを持つか,オフ,0
1626,キルレンジ,ショート,0
1635,サイドキック作成能力のクールタイム,30秒,59
1636,サイドキック作成数,1回,0
1601,サイドキック作成能力の範囲,ショート,0
1602,ラバーズをサイドキックに出来るか,オン,1
1603,ラバーズを置き換えてサイドキックにするか,オン,1
1604,ジャッカル死亡時、昇格するサイドキック数,1,0
1607,昇格したジャッカルがサイドキックを作成できるか,オフ,0
1600,昇格したジャッカルがサイドキックを作成できる再帰上限数,1,0
1605,インポスターをサイドキックにできるか,オフ,0
1606,サイドキックされたインポスターの表示をインポスターにするか,オフ,0
1610,サイドキックがサボタージュを使えるか,オン,1
1611,サイドキックがベントを使えるか,オン,1
1612,サイドキックがキルできるか,オフ,0
1613,サイドキックが別のキルクールを持つか,オフ,0
1614,サイドキックのキルクールタイム,30秒,58
1615,サイドキックが別のキルレンジを持つか,オフ,0
1616,サイドキックのキルレンジ,ショート,0
1617,サイドキックが別の視界設定を持つか,オフ,0
1618,サイドキックの視界,2x,7
1619,サイドキックが視界効果を受けるか,オフ,0
1671,タスクマスター,0%,0
1670,スポーン数,1,0
1672,別の視界設定を持つか,オフ,0
1673,ビジョン,2x,7
1674,視界効果を受けるか,オフ,0
1650,サボタージュを使えるか,オン,1
1651,追加のショートタスク数,1,1
1652,追加のロングタスク数,1,1
1653,追加の通常タスク数,1,1
1721,ミッショナリー,0%,0
1720,スポーン数,1,0
1722,別の視界設定を持つか,オフ,0
1723,ビジョン,2x,7
1724,視界効果を受けるか,オフ,0
1700,宣教後の自決が分かるかどうか,オン,1
1701,宣教後自決する時間の最小時間,10秒,18
1702,宣教後自決する時間の最大時間,30秒,30
1703,「宣教」できる範囲,1.2,12
1735,「宣教」のクールタイム,30秒,59
1771,ジェスター,0%,0
1770,スポーン数,1,0
1772,別の視界設定を持つか,オフ,0
1773,ビジョン,2x,7
1774,視界効果を受けるか,オフ,0
1751,「暴発」を発動できる距離,1,10
1750,サボタージュを使えるか,オン,1
1785,「暴発」のクールタイム,30秒,59
1787,「暴発」後キルが発生するまでの時間,2秒,3
1786,「暴発」の使用上限,5回,4
1821,ヤンデレ,0%,0
1820,スポーン数,1,0
1822,別の視界設定を持つか,オフ,0
1823,ビジョン,2x,7
1824,視界効果を受けるか,オフ,0
1800,「邪魔者」を殺した時のキルクール減少率,85％,35
1801,「邪魔者」以外を殺したときのキルクールペナルティ,1.2x,2
1802,ゲーム開始から「邪魔者」が登録されない時間,5秒,9
1803,「邪魔者」が登録される「片思いの人」からの距離,1.8,13
1804,「邪魔者」が登録される時間,2秒,19
1805,「邪魔者」の登録数上限,5,4
1806,「邪魔者」が無くなってから「暴走」するまでの時間,60秒,140
1807,「片思いの人」を指す矢印を表示するか,オン,1
1808,「邪魔者」を指す矢印を表示するか,オン,1
1871,妖狐,0%,0
1870,スポーン数,1,0
1872,別の視界設定を持つか,オフ,0
1873,ビジョン,2x,7
1874,視界効果を受けるか,オフ,0
1850,「気配察知」の範囲,7.5,5
1851,「気配察知」の発動間隔,10秒,14
1852,「気配察知」が正しい情報を教える確率,50％,5
5171,アサシンとマーリン,0%,0
5170,スポーンセット数,1,0
5180,別役職の能力を持つか,オフ,0
5222,アサシンが別の視界設定を持つか,オフ,0
5223,アサシンのビジョン,2x,7
5224,アサシンが視界効果を受けるか,オフ,0
5227,アサシンが別のキルクールタイムを持つか,オフ,0
5228,アサシンのキルクールタイム,30秒,58
5225,アサシンが別のキルレンジを持つか,オフ,0
5226,アサシンのキルレンジ,ショート,0
5200,アサシンがキルされるか,オフ,0
5201,キル能力を持つクルー役職がアサシンをキルできるか,オフ,0
5202,キル能力を持つ第三陣営がアサシンをキルできるか,オフ,0
5203,アサシン死亡時、強制的に会議を行うか,オン,1
5204,アサシン死亡後の最初の会議前にロールを見ることができるか,オフ,0
5205,アサシンが投票を見ることができるか,オン,1
5272,マーリンが別の視界設定を持つか,オフ,0
5273,マーリンのビジョン,2x,7
5274,マーリンが視界効果を受けるか,オン,1
5250,マーリンがタスクを持つか,オフ,0
5251,マーリンがアサシンを見ることができるか,オン,1
5252,マーリンが投票を見ることができるか,オン,1
5253,マーリンが第三陣営を見ることができるか,オフ,0
5254,マーリンがベントを使えるか,オフ,0
5421,ヒーロー、ヴィラン、ヴィジランテ,100%,10
5420,スポーンセット数,1,0
5430,別役職の能力を持つか,オフ,0
5472,ヒーローが別の視界設定を持つか,オフ,0
5473,ヒーローのビジョン,2x,7
5474,ヒーローが視界効果を受けるか,オン,1
5485,ヒーロー「サーチ」のクールタイム,0.5秒,0
5487,ヒーロー「サーチ」の発動時間,10秒,19
5450,ヒーロー「One for All」の第二段階発動のプレイヤー死亡率,20％,0
5451,ヒーロー「One for All」の第三段階発動のプレイヤー死亡率,50％,0
5522,ヴィランが別の視界設定を持つか,オフ,0
5523,ヴィランのビジョン,2x,7
5524,ヴィランが視界効果を受けるか,オフ,0
5527,ヴィランが別のキルクールタイムを持つか,オフ,0
5528,ヴィランのキルクールタイム,30秒,58
5525,ヴィランが別のキルレンジを持つか,オフ,0
5526,ヴィランのキルレンジ,ショート,0
5535,ヴィラン「サーチ」のクールタイム,0.5秒,0
5537,ヴィラン「サーチ」の発動時間,10秒,19
5500,ヴィジランテが能力発動時、ヴィランがその人の位置を認知できる時間,10秒,18
5572,ヴィジランテが別の視界設定を持つか,オフ,0
5573,ヴィジランテのビジョン,2x,7
5574,ヴィジランテが視界効果を受けるか,オフ,0
5585,ヴィジランテ「エマージェンシーコール」のクールタイム,0.5秒,0
5587,ヴィジランテ「エマージェンシーコール」の発動時間,10秒,19
5586,ヴィジランテ「エマージェンシーコール」の発動可能回数,10回,9
5550,ヴィジランテ「エマージェンシーコール」の発動可能範囲,3,18
5671,探偵と助手,0%,0
5670,スポーンセット数,1,0
5680,別役職の能力を持つか,オフ,0
5722,探偵が別の視界設定を持つか,オフ,0
5723,探偵のビジョン,2x,7
5724,探偵が視界効果を受けるか,オン,1
5700,探偵が「犯行現場」を調べれる距離,1,5
5701,探偵が「犯行現場」の1調査にかかる時間,6秒,30
5702,探偵が助手のサポートを受けた「犯行現場」の1調査にかかる時間,4秒,20
5703,調査結果の画面表示時間,60秒,550
5772,助手が別の視界設定を持つか,オフ,0
5773,助手のビジョン,2x,7
5774,助手が視界効果を受けるか,オン,1
5650,見習い探偵が別の視界設定を持つか,オフ,0
5651,見習い探偵のビジョン,2x,7
5652,見習い探偵が視界効果を受けるか,オフ,0
5686,見習い探偵「緊急招集」の使用回数,1回,0
5685,見習い探偵「緊急招集」のクールタイム,30秒,59
5687,見習い探偵「緊急招集」によって緊急会議ボタンを押せる時間,3秒,4
5653,見習い探偵「緊急招集」によって緊急会議ボタンを消費しないか,オフ,0
5654,消費されない回数,1回,0
5871,ラバーズ,0%,0
5881,1組あたりのアサイン数,2,0
5870,スポーンセット数,1,0
5882,インポスターがアサインされるか,オフ,0
5883,インポスターのアサインレート,0%,0
5880,別役職の能力を持つか,オフ,0
5922,別の視界設定を持つか,オフ,0
5923,ビジョン,2x,7
5924,視界効果を受けるか,オン,1
5900,第三陣営かどうか,オフ,0
5901,第三陣営に変わるかどうか,オフ,0
5906,自殺が行われる1組辺り人数,1,0
5927,別のキルクールタイムを持つか,オフ,0
5928,キルクールタイム,30秒,58
5925,別のキルレンジを持つか,オフ,0
5926,キルレンジ,ショート,0
5902,第三陣営に変化後、別の視界設定を持つか,オフ,0
5903,第三陣営に変化後のビジョン,2x,7
5904,第三陣営に変化後、視界効果を受けるか,オフ,0
5905,第三陣営に変化後、ベントを使用できるか,オフ,0
6121,サポーター,0%,0
6131,SupporterAssignsNum,1,0
6120,スポーンセット数,1,0
6132,インポスターがアサインされるか,オフ,0
6133,インポスターのアサインレート,0%,0
6130,SupporterIsMultiAssign,オフ,0
6172,別の視界設定を持つか,オフ,0
6173,ビジョン,2x,7
6174,視界効果を受けるか,オン,1
6177,別のキルクールタイムを持つか,オフ,0
6178,キルクールタイム,30秒,58
6175,別のキルレンジを持つか,オフ,0
6176,キルレンジ,ショート,0
6421,シェアーズ,0%,0
6431,1組あたりのアサイン数,2,0
6420,スポーンセット数,1,0
6430,別役職の能力を持つか,オフ,0
6472,別の視界設定を持つか,オフ,0
6473,ビジョン,2x,7
6474,視界効果を受けるか,オフ,0
6477,別のキルクールタイムを持つか,オフ,0
6478,キルクールタイム,30秒,58
6475,別のキルレンジを持つか,オフ,0
6476,キルレンジ,ショート,0
6450,別の「シェアーズ」のキルを教えるか,オン,1

**Comment by yukieiji** [comment]
リリースが可能な開発用ブランチにマージされたためクローズします
