### ISSUE TITLE
[インポスター陣営] : パラサイト (自分をキルした相手を乗っ取る)

### ISSUE THREAD

**Issue by melonjagaimo** [yukieiji/ExtremeRoles#83]
### 役職名 / Role Name
パラサイト

### 役職の色 / Role color
インポスターなので赤

### 役職の説明 / Role description
キルされたとき、自分をキルしたプレイヤーを会議後に乗っ取って味方にするインポスター陣営

### 役職の能力 / Role ability

能力ボタンを押すと一定時間「寄生の構え」をとる。構えている間にパラサイトが「キルボタンによるキル」でキルされた場合、パラサイトをキルしたプレイヤーに寄生虫がつく。
寄生虫がついているかどうかは、生きているプレイヤーでは誰にもわからない。
寄生虫をつけられたプレイヤーは次の会議終了時に生きていた場合、パラサイトになる。この効果は無効化されない。

#### メリット
自分へのキルを実質返り討ちにできる
乗っ取りが成功すれば味方を減らさず確実に厄介なプレイヤーを削れる

#### デメリット
インポスターをキルボタンでキルできる役職が少ないので能力が腐りやすい
ミッショナリーの宣教などの特殊なキル行為や追放には無力
寄生させても次の会議までにそのプレイヤーが死んでしまっては意味がない

#### 固有設定項目
寄生の構え持続時間
能力クールタイム

### 他陣営への影響 / Effect on other teams
シェリフやフェンサーが仕事後の騙りをケアする吊りにより積極的になる。
逆にこれを止めようとした場合、パラサイトをキルされたインポスターが乗っ取りのために吊らせまいとしているかもしれない。

インポスターをキルしたニュートラルをインポスターがかばう戦術も発生しうる。
サイドキックなど、味方がいるニュートラル陣営は味方の乗っ取りを把握できる。

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by melonjagaimo** [comment]
当初はそれをデメリットとしましたが能力が腐りすぎる気がしてきました。
そこで改善案を提示します。

・乗っ取りの構えをパッシブ能力にしてアクティブ能力を変更。
・変更後のアクティブ能力を発動するとその場で自害し、最も近い敵プレイヤーに寄生虫をつける。

**Comment by yukieiji** [comment]
> 変更後のアクティブ能力を発動するとその場で自害し、最も近い敵プレイヤーに寄生虫をつける。ただしこの能力は「最初にパラサイトとしてアサインされたプレイヤー」にしか発動できない。

キルをして、通報してきた人を問答無用でインポスター陣営に率い入れる事が可能なのはどうなのでしょうか・・・

**Comment by melonjagaimo** [comment]
TORのように、キル能力とクールタイムを連動させるのはどうでしょうか。
キル能力を使用すると自爆能力のクールタイムがリセットされるのでキルして見られたら自爆、ができなくなります

**Comment by yukieiji** [comment]
> ORのクリーナーのように、キル能力とクールタイムを連動させるのはどうでしょうか。
キル能力を使用すると自爆能力のクールタイムがリセットされるのでキルして見られたら自爆、ができなくなります

どちらにせよ、一時的にインポスターを4人出来るというのはどうなのでしょうか・・・

**Comment by melonjagaimo** [comment]
パラサイト死亡から次の会議が終わる（つまり乗っ取り完了）までの間、寄生虫が付いているプレイヤーは元々の役職のままです。
つまり最後に残ったパラサイトが自害やニュートラルなどのキルボタンで死亡した場合、乗っ取りが完了するまでの間インポスター陣営が全滅した状態になります。

**Comment by yukieiji** [comment]
> つまり最後に残ったパラサイトが自害やニュートラルなどのキルボタンで死亡した場合、乗っ取りが完了するまでの間インポスター陣営が全滅した状態になります。

全滅している状況だとそうだとは思いますが、全滅していない状況だと強すぎませんか・・・

> パラサイト死亡から次の会議が終わる（つまり乗っ取り完了）までの間、寄生虫が付いているプレイヤーは元々の役職のままです。

ゲーム開始後クールが空けた瞬間に誰か一人に寄生させてボタンで会議起こせばインポスター4人+クルー11人以下の状態になるのですが・・・

**Comment by melonjagaimo** [comment]
オレとしては、これ以上この役職のコンセプトを崩さずにバランスを良くする案が思いつきません。
クローズします。
