### ISSUE TITLE
[インポスター陣営] : 怪盗(クルー役職の一人から役職と能力を奪うインポスター)

### ISSUE THREAD

**Issue by tansanUSB** [yukieiji/ExtremeRoles#85]
### 役職名 / Role Name
怪盗
### 役職の色 / Role color
インポスターの赤
### 役職の説明 / Role description
クルーの役職を一つ消し、その役職と同じ能力を持つ事ができる
消された人は気づけないため、消した役職を騙りやすい
（※ニュートラル陣営とコンビ役職は対象外）
### 役職の能力 / Role ability

ゲーム開始直前に他のクルー役職のどれかを消し、その役職に合わせた能力を得る

－－－－－－－役職に対する能力案－－－－－－－－－
＞シェリフ　　　　　自爆ボタンを追加
＞メンテナー　　　　緊急タスク修理ボタン
＞ニート　　　　　　何か書く必要ある？
＞ウォッチドッグ　　カメラがいつでも見れる（一部マップではドアログ）
＞スーパーバイザー　アドミンがいつでも見れる
＞ボディーガード　　自爆ボタン
＞ウィスパー　　　　キルの時間と方角が分かる　味方と連携可能
＞タイムマスター　　時間を巻き戻すボタン
＞エージェンシー　　近くのクルーのタスク数を減らすボタン
＞パン屋　　　　　　ボタンは無し、会議後にメッセージが流れる
＞カースメーカー　　死体を消せるボタン
＞フェンサー　　　　追加ボタン無し
＞オープナー　　　　近くのドアを開けるボタン
＞カーペンター　　　カメラ設置とベント封鎖ができるボタン
－－－－－－－－－－－－－－－－－－－－－－－－－

・強み
　○役職騙りの難易度が低くなり役職騙りを通しやすい
　○存在するだけで白役職が能力で白確定する事を抑制できる
　○あえて騙らない選択肢もある。
　　スーパーバイザーの能力を奪った場合　アドミンが見れるインポスターとして活動できる
　○自分だけ最初から存在しない役職の情報を持つ事ができる

・リスク
　○役職騙りをした場合、騙りながらキルしていく必要性がある
　○消す役職は選べないので役に立たない能力を得る場合がある
　○その場合は能力的にはデフォのインポスター同然
　○何の役職が消えるか分からないので配役によるバランス調整が難しい
　○ニートを消した場合、働けるクルーを増やすことになる
　○厳密に同じ能力ではないので、役職を理解し上手く立ち回らなければならない
　　例：シェリフが一発しか撃てない設定なのに二発目を撃ったと発言して騙りがバレる

・設定項目
　○各役職能力のクールタイムや使用回数やボタンオンオフ等による騙り難易度の調整
　　例1：シェリフの自爆ボタンのオンオフ設定　＞　自爆できない事から騙りとばれる可能性を作れる　等
　　例2：パン屋の会議後メッセージを、焼けなかったに固定し、騙りが発覚するリスクを高める
　　（パン屋は実質無能力な代わりアナウンスで白確定しやすい役職と解釈してるので、騙り難易度を上げる設定はほしい）

### 他陣営への影響 / Effect on other teams

職を奪われる人が必ず一人でるため、配役設定から役職が一人消えて無能力クルーが一人増える
騙りをしやすい役職なので、クルー役職の能力証明による白確定を抑制できる

### 陣営 / Team
- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

### 問題点等
・そもそも開始直前に役職を消すという挙動が可能かどうか
・消した役職が何かを判別して能力追加ができるかどうか
・役職を消されたクルーがそれに気づけないようにできるか
・クルー役職とほぼ同数の設定項目があるので製作者さんの労力が大きい
・今後クルー役職が追加実装された場合それに合わせた能力の追加による労力更にドン

**Comment by yukieiji** [comment]
> クルーの役職を一つ消し、その役職と同じ能力を持つ事ができる

これはどういうことでしょうか？いつ度のタイミングで消すのでしょうか

> 消された人は気づけないため、消した役職を騙りやすい
（※ニュートラル陣営とコンビ役職は対象外）

コンビ役職が多いルールやニュートラル陣営が多いルール(人外村が例)の時、この役職はどうするのでしょうか

> ウィスパー　　　　キルの時間と方角が分かる　味方と連携可能

シェアーズの能力を完全に喰っている気がします

> タイムマスター　　時間を巻き戻すボタン

時間を巻き戻すとはどういうことでしょうか

> ○各役職能力のクールタイムや使用回数やボタンオンオフ等による騙り難易度の調整
例1：シェリフの自爆ボタンのオンオフ設定　＞　自爆できない事から騙りとばれる可能性を作れる　等
例2：パン屋の会議後メッセージを、焼けなかったに固定し、騙りが発覚するリスクを高める
（パン屋は実質無能力な代わりアナウンスで白確定しやすい役職と解釈してるので、騙り難易度を上げる設定はほしい）

今、ソロのクルー役職が15役職いるはずですがその全てのオプションを実装して、更にクルーを追加で実装したらこの役職のオプションも実装するということでしょうか

> クルー役職とほぼ同数の設定項目があるので製作者さんの労力が大きい
・今後クルー役職が追加実装された場合それに合わせた能力の追加による労力更にドン

正直、実装コストするとこの役職を維持していくメンテコストが異常に高すぎて非現実的な気がします(メンテしてくれるなら話は別ですけど)

あと問題があるとすれば今後予定している会議中に何らかのアクションを起こすような役職をどうするのかとか

**Comment by tansanUSB** [comment]
こんな拙い提案に丁寧な返信ありがとうございます

> > クルーの役職を一つ消し、その役職と同じ能力を持つ事ができる
> 
> これはどういうことでしょうか？いつ度のタイミングで消すのでしょうか
> 
具体的な役職消去のタイミングはゲーム開始時の、　インポスター　等、自分の役職が表示が出る直前ですかね
ここの抽選結果が通達されてるタイミングで　インポスター　　怪盗/タイムマスター　のような表示が出るのを想像してました

この発想が本家人狼の役職欠けを元にし、白役職の確定を抑制するために騙りをやりやすい事を一番重視して考えたんですが
「・そもそも開始直前に役職を消すという挙動が可能かどうか」　これができないと難しいんですよね。
ここが不可能だと、この提案した役職自体が成立しないと思っています。

> > 消された人は気づけないため、消した役職を騙りやすい
> > （※ニュートラル陣営とコンビ役職は対象外）
> 
> コンビ役職が多いルールやニュートラル陣営が多いルール(人外村が例)の時、この役職はどうするのでしょうか
> 
恐らくコレは、対象になるクルー役職が存在しない場合の事ですかね？この辺りは考えが足りてませんでしたね

> > ウィスパー　　　　キルの時間と方角が分かる　味方と連携可能
> 
> シェアーズの能力を完全に喰っている気がします
> 
ウィスパー騙りを考えた結果なので、この辺りの能力の強弱はそこまで詰め切ってません。
コレを弱体化して劣化シェアーズ程度に納める場合、アドミンを一時的に見れるとかになりますかね？
下記の問題点があるんでここは後回しとします

> > タイムマスター　　時間を巻き戻すボタン
> 
> 時間を巻き戻すとはどういうことでしょうか
> 
これも騙りを考えたタイムマスターの効果と同じ処理をするを想定してましたね。上記と同じく詰めきってません
同じく下記の問題があるので一旦後回しにします


> > ○各役職能力のクールタイムや使用回数やボタンオンオフ等による騙り難易度の調整
> > 例1：シェリフの自爆ボタンのオンオフ設定　＞　自爆できない事から騙りとばれる可能性を作れる　等
> > 例2：パン屋の会議後メッセージを、焼けなかったに固定し、騙りが発覚するリスクを高める
> > （パン屋は実質無能力な代わりアナウンスで白確定しやすい役職と解釈してるので、騙り難易度を上げる設定はほしい）
> 
> 今、ソロのクルー役職が15役職いるはずですがその全てのオプションを実装して、更にクルーを追加で実装したらこの役職のオプションも実装するということでしょうか
> 
ここは理想をぶち込み過ぎたと反省してます、申し訳ない。

> > クルー役職とほぼ同数の設定項目があるので製作者さんの労力が大きい
> > ・今後クルー役職が追加実装された場合それに合わせた能力の追加による労力更にドン
> 
> 正直、実装コストするとこの役職を維持していくメンテコストが異常に高すぎて非現実的な気がします(メンテしてくれるなら話は別ですけど)
> 
> あと問題があるとすれば今後予定している会議中に何らかのアクションを起こすような役職をどうするのかとか

会議中にアクションを起こす役職、これを消して自分の能力として実装するのは難しそうですね
すべての役職を騙りできるようにと考えてよくばりすぎたので
だいぶと簡略化して想定すると、「消した役職の能力が使える」という部分をまるっと削除して
どの役職が消えたかの情報を持ち、役職騙りができそうなら狙う感じのインポスターになるでしょうか？

ニュートラルやコンビは役職騙りする事の少なさから除外してましたが、
そちらメインの配役を考えるとするとニュートラルも対象に含めるてもいいかもしれませんが
人外村を想定した場合クルーが生まれてしまうのが難しい所ですね
コンビ役職は、役職を乗っ取るではなく無職にする処理の関係から対象外にするしか無いと思ってます

役職欠けを起こすだけでは、かなり地味だし、人外村では不発になる事を考えた場合
別方向から能力を追加を考えてもいいかもしれません。
僕の発想ではないですが、噛んだ相手の役職が分かる等ですかね。

これも処理として可能なのかは分からないですが、他の人の情報が増えるのは、騙りやすくはなると思います
ただこの場合、アサシンとの相性が良すぎたり色んな影響が考えられますね。
沢山の情報を得て戦う事を考えると、インポスターより単独でキル能力を持ったニュートラル陣営向きな気はします

**Comment by yukieiji** [comment]
> 具体的な役職消去のタイミングはゲーム開始時の、　インポスター　等、自分の役職が表示が出る直前ですかね
ここの抽選結果が通達されてるタイミングで　インポスター　　怪盗/タイムマスター　のような表示が出るのを想像してました
この発想が本家人狼の役職欠けを元にし、白役職の確定を抑制するために騙りをやりやすい事を一番重視して考えたんですが
「・そもそも開始直前に役職を消すという挙動が可能かどうか」　これができないと難しいんですよね。
ここが不可能だと、この提案した役職自体が成立しないと思っています。

その感じだと今実装されているインターフェースだと恐らく出来ないでしょう、ホストとクライアントで処理の速度が異なるので通信速度的も考えると出来ない気がします(役職のアサイン処理の終わりの処理に追加することも出来るとは思いますが、この役職のためだけに100行近い新しい処理を追加するのはちょっと・・・)

> どの役職が消えたかの情報を持ち、役職騙りができそうなら狙う感じのインポスターになるでしょうか？

役職を消すって処理が多分出来ない気がします

> 役職欠けを起こすだけでは、かなり地味だし、人外村では不発になる事を考えた場合
別方向から能力を追加を考えてもいいかもしれません。
僕の発想ではないですが、噛んだ相手の役職が分かる等ですかね。

それは #86 で議論しているのでそちらにお願いします

**Comment by tansanUSB** [comment]
> その感じだと今実装されているインターフェースだと恐らく出来ないでしょう、ホストとクライアントで処理の速度が異なるので通信速度的も考えると出来ない気がします(役職のアサイン処理の終わりの処理に追加することも出来るとは思いますが、この役職のためだけに100行近い新しい処理を追加するのはちょっと・・・)
> 
> 役職を消すって処理が多分出来ない気がします
> 
これは無理そうですね。見切り発車な部分の大きい提案でしたが、丁寧な返答ありがとうございました

**Comment by tansanUSB** [comment]
はい、大丈夫です。ありがとうございました
