### ISSUE TITLE
[インポスター] : サイコメトラー（キルした相手の役職がわかる）「なりすさん放送より」

### ISSUE THREAD

**Issue by nukodesu21** [yukieiji/ExtremeRoles#86]
### 役職名 / Role Name
サイコメトラー（仮）
### 役職の色 / Role color
未定
### 役職の説明 / Role description
なりすさんの放送より
自らがキルした相手の役職がわかるインポスター陣営
### 役職の能力 / Role ability
「サイコメトリー」
キルした相手の役職が直後の会議開始にゲーム内チャット欄若しくはHキーを押した際の役職説明に表示される
表示された役職の能力は使えない
キルしたのがマーリンだった場合はクルー表示される
デフォルトで分かる役職数は1
初めてキルした相手のみ分かり2番目以降にキルした相手の役職は分からない（設定次第）

### 他陣営への影響 / Effect on other teams
クルー役職を乗っ取りやすくなるため、COしたクルー役職が信用されにくくなる
COしてもクルー陣営とすぐ分からないためクルー役職を増やしやすくなる

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
相手の職が分かるような役職はアサシンとマーリンに混ぜて使えない(別のクルーの役職が判明しても推理に影響があるので)ので実装するとなっても優先度は低いです

その上で以下気になる点
> デフォルトで分かる役職数は1
初めてキルした相手のみ分かり2番目以降にキルした相手の役職は分からない（設定次第）

これ最初に第三陣営切った瞬間に無力なインポスターになる気がしますがどうでしょうか

**Comment by tansanUSB** [comment]
自分が別で、役職欠けを元にした能力を提案したのは
自分の役職が死んだ後に乗っ取られると考えた場合、最初の会議から「自分乗っ取られる前にCOします、シェリフです」
といった、本来の目的とは真逆のCO促進の可能性が考えられたからですね。

騙り促進と白役職のCO抑制、中々難しいです

**Comment by tansanUSB** [comment]
騙り促進と白役職のCO抑制を忘れてこの能力を活かす場合、アサシンの相方として強すぎるのも含めて考えると
キル能力を持ち人数優位で勝利する（ジャッカルと同じ）ニュートラル陣営が適してると思います。
ジャッカルと比べ仲間を作れない単独陣営の不利を情報量で有利を取って立ち回る感じですね。

それに合わせて役職が分かる条件がキルよりも、単純に死亡した人の役職が分かるの方がいいと提案します
分かる役職の数は3くらいが妥当かなと　（10人村想定だと2が妥当かもしれません）

単独のニュートラル陣営かつ判明条件がキルの場合
単独故に吊られる可能性が高まるのは敗北の可能性を大きく高め、
逆にキルをしない場合何の情報も得られない劣化ジャッカルになります。

単純な死亡した死体で判明する場合
死体が全てクルーであれば、真面目に議論して人外探しをするクルー寄りの動きにシフトしたり
死体にインポスターが混じっていれば、議論を見出したりキルの積極性を上げたりと人外側の動きにシフトしたりと
状況に合わせて立ち回りを買える第3陣営が想定できると思います

**Comment by yukieiji** [comment]
> 影響が大きいのであれば弱体化案として表示される能力が確率でクルーになるとかはどうでしょうか？
その場合表示される能力数を増やす必要があると思います

確率にしてもマーリンだって分かる確率がある以上私の中的には優先度が下がります

> 他の実装予定役職を把握していないので優先度はお任せします

[マイルストーン](https://github.com/yukieiji/ExtremeRoles/milestones)の場所に大体の実装予定とリリース時期が書いてありますのでそれを参考にしていただければ(優先度が下の場合(優先度最低等)は基本的にここのマイルストーンの最後より、あとは確実で+1ヶ月位以上(7月までに新しい何かが来るかもしれないので・・・)お時間をいただくことになります)

> 乗っ取り出来なくてもこの役職がいることによりクルー役職の信用低下、盤面に残っていない役職の把握による情報量で立ち回りの切り替えを容易にすることが出来ると思います。

これは無力なインポスターになっても問題ないという認識で問題ないでしょうか

> ニュートラル陣営でも考えたのですがキルしないと情報を得られないことや単独であることでジャッカルの弱体化に感じてしまいインポスター陣営で提案しました。ニュートラル陣営で死亡した人の役職が分かるのはかなり良いと思いますが、これだけだと他のニュートラル陣営より弱いのは確かです。情報量と立ち回りに特化したニュートラル陣営は面白いと思うのですが難しいですね。

この能力をニュートラルとして考えるのであれば別途考えることが必要なので別チケットで対応しましょう

**Comment by nukodesu21** [comment]
確率にしてもマーリンだって分かる確率がある以上私の中的には優先度が下がります
＞マーリンをキルした場合はクルー表示されても変わらないでしょうか？
分かった時点で勝敗に直結してしまう役職は100％クルー表示することが難しいのであれば後回しで構いません。
確率で正しく能力が表示される設定と合わせ、マーリンが自分がキルした中にいるのか、ほかの人がキルした死体にいるのか、まだ生きているのかとなればアサシンの相方になれるのではと思います。

これは無力なインポスターになっても問題ないという認識で問題ないでしょうか
＞キル能力という面では他のインポスター役職で劣りますが情報量の多さによる盤面把握しやすくなり立ち回りを切り替えやすい役職で無力なインポスターになるとは思いません。

**Comment by yukieiji** [comment]
> マーリンをキルした場合はクルー表示されても変わらないでしょうか？

変わらないです、斬った役職がわかったらそれはそれで「あの人はあの役職だった」で一つ選択肢を減らせます、斬った役職が「クルー」であれば「あの人がマーリンだった可能性もある」ということになるためです

> 分かった時点で勝敗に直結してしまう役職は100％クルー表示することが難しいのであれば後回しで構いません。

クルー表示することは難しくはないです

> 確率で正しく能力が表示される設定と合わせ、マーリンが自分がキルした中にいるのか、ほかの人がキルした死体にいるのか、まだ生きているのかとなればアサシンの相方になれるのではと思います。

それはいかに役職の人を斬って候補を減らせるかという別ゲーが始まるので私は反対です
せっかく推理や行動、言動で上手く自分の役職を隠してマーリンを偽っていたのにこの役職の能力でバレたらつまらないと思います

> キル能力という面では他のインポスター役職で劣りますが情報量の多さによる盤面把握しやすくなり立ち回りを切り替えやすい役職で無力なインポスターになるとは思いません。

ニュートラルを斬った時、騙れなくなるけど問題はないということでよろしいでしょうか

**Comment by nukodesu21** [comment]
アサシン採用時にこの役職は難しいと分かりました。

ニュートラルを斬った時、騙れなくなるけど問題はないということでよろしいでしょうか
＞この役職がいることによるクルー役職の信用低下がメインであり、騙りはおまけでのようなもので騙れなくても問題ありません。

**Comment by yukieiji** [comment]
> この役職がいることによるクルー役職の信用低下がメインであり、騙りはおまけでのようなもので騙れなくても問題ありません。

私自身、騙りが発生しないとクルー役職の信用が下がらないと思いますがどうでしょうか
騙れなかったら「死んでる中にその役職が居たんだね」で話が進むので信用がそこまで変わらない気がします
