### ISSUE TITLE
[インポスター役職] : 殉教者/Martyr (自爆してデバフを与える)

### ISSUE THREAD

**Issue by Inumiya** [yukieiji/ExtremeRoles#94]
### 役職名 / Role Name
殉教者/Martyr 
### 役職の色 / Role color
赤
### 役職の説明 / Role description
- コンセプトは以下です
  - 任意のタイミングで自爆できる
  - 自爆を目撃したプレイヤーへ生きている間クルーにとってデメリットのあるデバフをかける

- この役職が存在するだけで、
  - シェリフ自爆による白塗りを抑制できる
  - シェリフが自爆して白塗りしたのか、殉教者が自爆してデバフを掛けたのか区別がつかない（真シェリフがCOせずに死んでいる場合）
  - 自爆を目撃したクルーは白塗りされず吊るす方向へ議論を持っていける
 - これを防ぐためシェリフに早い段階でCOさせられる
### 役職の能力 / Role ability

- 殉教
  - ミドルレンジのプレイヤーへ使用可能なボタン能力
  - 自爆する
  - 最も近くにいたプレイヤー１人を次の会議後に目撃者状態にする
- 目撃者状態
  - 目撃者が生存している限り、他インポスターのキルクールタイムが減少する
  - 殉教ボタン使用時にミドルレンジ内に居たプレイヤーの数が少ないほど、クールタイムの減少量は多くなる
  - 誰が目撃者状態になっているか確認するすべはない
  - インポスターが目撃者になってしまった場合は特になんの効果もない
- メリット
  - 役職説明に記載した通り、この役職がいるだけでシェリフへ圧力を掛けられる
  - 幽霊役職へ能動的になれる
  - マーリン探しのヒントにもなる
- デメリット
  - インポスターの数が減る
  - 他インポスターが先に吊られると無力

### 他陣営への影響 / Effect on other teams
- クルー
  - 議論面での影響が大きい
  - シェリフは早い段階でCOするか選択を迫られる
- 第３陣営
  - インポスターのキルクールが減少するのでキルの打ち合いに負けやすくなる

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by yukieiji** [comment]
> 他インポスターのキルクールタイムが減少する

この能力は司令官( #30)ともろかぶりしてしまってます

シェリフ自爆を語れるだけでインポスター1落ちって考えると能力的にもデメリットが大きい気がします

シェリフ自爆を騙りやすい役職としては一応私がチケットを出しているラストウルフ(#97)が居ます(個人的にはシェリフ一騎打ちになっても勝てる+インポスターが残るという部分でラストウルフの方が良いのではって思ってしまします)

**Comment by Inumiya** [comment]
デバフの内容変えたとしても、キルワープなしのインポスターが実装予定ならこの役職いらないですね
クローズでお願いします
