### ISSUE TITLE
[クルー/Crewmate] : サバイバー/Survivor (死ぬと勝てないクルー役職)

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#96]
恐らくのえぞうさん提案

### 役職名 / Role Name
- サバイバー/Survivor

### 役職の色 / Role color
- 未定

### 役職の説明 / Role description
- タスク覚醒役職
  - タスク一定値完了で死亡しても勝てるようになる
- クルー陣営であるが生き残らないと勝てないクルー

### 役職の能力 / Role ability

- 無し

### 他陣営への影響 / Effect on other teams
- クルー陣営にダメージあり：クルーの命が全体的に重くなる

### 陣営 / Team

- [x] :クルー/Crewmate
- [ ] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by suikouzatta** [comment]
質問なのですが、もしもキルや吊りなどで死んでしまったとき、タスク条件をクリアしてなかった場合死後、タスクをするメリットが無くなってしまうと思います。
その場合はどうなるのでしょうか？
また、達成した後に死んだ場合サバイバーのタスクはクルーのタスク勝利に必要なのでしょうか？
