### ISSUE TITLE
[インポスター/Impostor] : ラストウルフ/LastWolf (インポスターの覚醒役職)

### ISSUE THREAD

**Issue by yukieiji** [yukieiji/ExtremeRoles#97]
### 役職名 / Role Name

- ラストウルフ/LastWolf

### 役職の色 / Role color

インポスターレッド

### 役職の説明 / Role description
- インポスターの覚醒役職
  - 覚醒条件：インポスターが一定以下になる
  - 未覚醒状態は通常のインポスター

### 役職の能力 / Role ability

- パッシブ能力「熟練の狩人」
    - 覚醒したラストウルフのキルはキルワープしない
- パッシブ能力「血塗られた牙」
   - 生存者の数に応じて会議後一回のキルクールが短くなる(1人×2％)、一回キルすると元通り
   - 覚醒前に自分がキルした数に応じてボーナスが入る(1キル4％)
- 能力ボタン「強制停電」
    - 自分以外全て(第三陣営とクルー)の視界を一定時間落とす
    - 生存者の数に応じてクールタイムが伸びる(最初は5秒 => 最終60秒)

### 他陣営への影響 / Effect on other teams
- クルー陣営：インポスター1人でもかなり強力な役職が残るのでタスクで行きましょうが少なくなる
- インポスター陣営：自分のキルでラストウルフになる人が強くなるという責任感が生まれるため、キルペースが跳ね上がる
- ニュートラル陣営：インポスターのキルペースが上がるため最初から動く必要がある

### 陣営 / Team

- [ ] :クルー/Crewmate
- [x] :インポスター/Impostor
- [ ] :ニュートラル/Neutral

**Comment by melonjagaimo** [comment]
質問です。ラストウルフへの覚醒条件は何ですか？

役職名を見ると、「残りのインポスター陣営がラストウルフに覚醒する予定のインポスターのみになる」と解釈できそうです。

もし違うようでしたらお知らせください。

**Comment by yukieiji** [comment]
> 質問です。ラストウルフへの覚醒条件は何ですか？
役職名を見ると、「残りのインポスター陣営がラストウルフに覚醒する予定のインポスターのみになる」と解釈できそうです。
もし違うようでしたらお知らせください。

記載忘れてました、記載しておきました

**Comment by yukieiji** [comment]
v3.2.0.0ブランチにマージされたためクローズします
